### ISSUE TITLE
Better feedback when Storage Endpoint is invalid

### ISSUE THREAD

**Issue by nebunez** [owncast/owncast#1000]
It appears that the "Endpoint" input field in the Storage section of the Admin has some kind of validation that checks for a valid url. This is good, but there is no feedback to the user for when this is invalid, only the Save button is greyed out. A common problem is that the user forgets to prepend their url with "https://'. We should give better feedback to the user when they have input an "invalid" url.

**Comment by gabek** [comment]
I've thought about just setting the protocol if one is missing in the past, but figured that would just cause _more_ issues if we assume it's https and it's only http or vice versa.  In this case the placeholder specifically says what the value should look like, but I'm sure that's ignored most of the time.  I'm not sure offhand what the validation feedback should look like.  We could highlight the field visually but I'm thinking you want human readable text somewhere that says "this URL is invalid" when the field loses focus?  If anybody has any ideas on how that should look and wants to take a stab at it, give it a go!

**Comment by gingervitis** [comment]
I've added some enhancements on the markup and css side. 
Now onBlur of that particular field , if it doesn't match "https://*" pattern, it will turn red.

![image](https://user-images.githubusercontent.com/9563255/119247754-3c11cd00-bb41-11eb-84b8-0bbfd77a5c74.png)
