### ISSUE TITLE
Provide command line option for setting the RTMP listening port

### ISSUE THREAD

**Issue by aaronpk** [owncast/owncast#1001]
I am trying to install Owncast on a new server which is already set up to have nginx listen on port 1935, so I can't start the app in order to get into the config to change the RTMP port. I'd like to see a command line option to set the RTMP port that way I can start the service without shutting down nginx first.

**Comment by gabek** [comment]
If anybody gets to this before I do, we already do this exact same thing for the web server, so it should be trivial to just copy how that's pulled in, stored and used.

**Comment by leuc** [comment]
I'll have a look and implement it.
