### ISSUE TITLE
Update chat scroll handling (jump to bottom, initial position, etc)

### ISSUE THREAD

**Issue by gingervitis** [owncast/owncast#101]
If you're late to a stream with a chatty party and a ton of messages have already queued up, it's super annoying when the message list keeps trying to jump to the bottom to reveal the latest incoming message, while you're still trying to read all past messages above.

How do we know if a user is still trying to previous read messages so we can prevent auto scrolling to the bottom?

Possible ideas - 
- Perhaps if the use has scrolled up past x% of the available message container height, just leave them where they are? and maybe display a button for "click here to see new messages" which would jump them down to the latest?

- Check to see if user has scrolled in the list at all within some debounced amount of time. If so, prevent jump to bottom? (though it may be hard to distinguish between user-initiated scroll events vs a scroll event from autoscrolling..)

- something cleaner?

**Comment by gabek** [comment]
We should probably figure this out.  I think it was @graywolf336 who brought it up tonight in the chat.

**Comment by jeyemwey** [comment]
Not sure if this is a bug, but the initial scroll position of the chat is currently the very top, which I don't recommend. IMO, the user should see the latest messages per default, and be able to scroll up if desired.
