### ISSUE TITLE
Chat is disabled after stream begins

### ISSUE THREAD

**Issue by luismelloleite** [owncast/owncast#1014]
I made quite a lot of tests in Tricaster Mini and so far Owncast worked flawlessly, the only issue is that you have to send the Stream Key as an unencrypted parameter called "Stream ID" (and it took me quite a lot of time to figure it out).

Also, after I start the stream the chat remain disabled, any ideia why?

Anyway, love the project! Thank you!

**Comment by gabek** [comment]
I'm glad you were able to figure that out!  I'll find some place to put that bit of info for future people using Owncast with the Tricaster.

Take a look at https://owncast.online/docs/troubleshooting/#chat-is-disabled, you might be seeing a websocket proxying issue.

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="/favicon.png" height="14"> Owncast</div><div><strong><a href="/docs/troubleshooting/">Troubleshooting</a></strong></div><div>Some categories of issues you might run into and some next steps to help troubleshoot.</div></blockquote>

**Comment by gabek** [comment]
Hi, @luismelloleite.  Were you able to track down your chat issue?

**Comment by gabek** [comment]
Feel free to re-open if you have anything we can help with.

**Comment by luismelloleite** [comment]
Hello Gabe, sorry for taking so long to respond!

I did manage to find out the root of the problem, it was a proxying issue all along, we are using https://king.host/ for the server and they have some ports and proxying for anything JS related, that being the reason it was not working. I can't relate how they manage to solve the problem, I just called them for support and they automagically solved the problem.

Thank you very much for the support and for taking time to adress my issue!

<blockquote><img src="https://cdn-cms.king.host/2020/10/og-image-facebook.png" width="48" align="right"><div>Kinghost</div><div><strong><a href="https://apiki-prod.king.host/">KingHost | Hospedagem de Site com SSL Grátis e Suporte 24x7</a></strong></div><div>Potencialize seu projeto com soluções digitais para tudo o que seu site precisa e uma equipe que se dedica para o seu sucesso.</div></blockquote>
