### ISSUE TITLE
Multistreaming options

### ISSUE THREAD

**Issue by kilomeow** [owncast/owncast#1027]
It seems that your backend could be modified to support multistreaming - in the same way as platforms like Restream work.

There is an existing self-hosted solution for this task: it could be done with [nginx-rtmp-module](https://github.com/arut/nginx-rtmp-module) with proper configuration. However it lacks a good web interface. So maybe it's simpler to extend yours. Have you considered this direction?

My activist friends who do streams are extremely interested in this functionality. Go is not my native land, but I think I can handle it with your tip.

**Comment by controlfreakstudio** [comment]
please see https://github.com/owncast/owncast/discussions/712
I imagined a free and non-corporate methodology to use the recording output of obs but that would require an icecast extension of owncast. I was pointed to this: https://github.com/muesli/prism

To push boundaries I have sucessfully tested the paid  Restream.io simultaneous to multiple commercial platforms  including the single allowed custom send to owncast. 
However!
at this time with the live 0.0.6 and 0.0.7 in dev this causes warnings first at connect but it does hold then errors and service crashes upon disconnect so it is not friendly for anyone not happy to quickly cli and stop and start services on their owncast
https://github.com/owncast/owncast/issues/999

<blockquote><img src="https://opengraph.githubassets.com/1e1515ac01e58ff0b60b93778ea1435b8b10fb15aa3bf79842933fec28209191/muesli/prism" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/muesli/prism">muesli/prism</a></strong></div><div>An RTMP stream recaster / splitter. Contribute to muesli/prism development by creating an account on GitHub.</div></blockquote>

**Comment by gabek** [comment]
Owncast is a destination in and of itself and we don't plan on turning it into a middle man to allow for streaming to other destinations.  Like mentioned above https://github.com/muesli/prism is a good solution for this.

<blockquote><img src="https://opengraph.githubassets.com/1e1515ac01e58ff0b60b93778ea1435b8b10fb15aa3bf79842933fec28209191/muesli/prism" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/muesli/prism">muesli/prism</a></strong></div><div>An RTMP stream recaster / splitter. Contribute to muesli/prism development by creating an account on GitHub.</div></blockquote>
