### ISSUE TITLE
Curl Installer to .7 from .6 failed

### ISSUE THREAD

**Issue by PNMIC** [owncast/owncast#1031]
I ran this:
 curl -s https://owncast.online/install.sh | bash

I got this error message

Existing install found in //owncast.  Will update it to v0.0.7. If this is incorrect remove the directory and rerun the installer.
Backing up your files before upgrading to v0.0.7cp: cannot stat '*.yaml': No such file or directory
Your Owncast installation did not complete successfully.
Please report your issue at https://github.com/owncast/owncast/issues

It should be known that ever since .5, I have updated to .6 manually. I think cannot stat *.yaml might be part of the issue? I have my server at Digital Ocean and this was before DO had it as a one installer.

**Comment by gabek** [comment]
Good catch, thanks for reporting this!  Config files aren't a thing anymore, so for a lot of people they won't have a config file laying around unless they had an older version at some point.  I'll fix this up.

**Comment by gabek** [comment]
Fixed.  Removed the upgrade trying to deal with currently non-existent config files.
