### ISSUE TITLE
Player video quality setting icon is sometimes not centered

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1044]
Not sure what causes this.  In this case it was in the embed player, so maybe that has something to do with it.  We should probably find a better icon, too.  I'm not sure I like this one.

![image](https://user-images.githubusercontent.com/414923/119237817-ae5bc080-baf3-11eb-80a4-f983284759ab.png)

**Comment by PNMIC** [comment]
In addition to the quality center icon not centered, on mobile, it does not show the options. I guess this might have to do with using hover rather than click? I'm using a Android 10 phone running Chrome.

**Comment by MFTabriz** [comment]
@gabek What about using <img height = 24 src=https://raw.githubusercontent.com/Donnnno/Arcticons/main/icons/settings.svg> or <img height = 24 src=https://raw.githubusercontent.com/Donnnno/Arcticons/main/icons/automation.svg> instead?

src: 
* https://github.com/Donnnno/Arcticons/blob/main/icons/settings.svg 
* https://github.com/Donnnno/Arcticons/blob/main/icons/automation.svg

_Note: The icons are white lines on the transparent background. Check them out in the GitHub's dark mode!_

<blockquote><img src="https://opengraph.githubassets.com/0c753ae7478ac1149913b84f2a98f2c46cbbb5f19c2a4b0af0c715af13a97d45/Donnnno/Arcticons" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/Donnnno/Arcticons">Donnnno/Arcticons</a></strong></div><div>A monotone line-based icon pack for android. Contribute to Donnnno/Arcticons development by creating an account on GitHub.</div></blockquote>
<blockquote><img src="https://opengraph.githubassets.com/0c753ae7478ac1149913b84f2a98f2c46cbbb5f19c2a4b0af0c715af13a97d45/Donnnno/Arcticons" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/Donnnno/Arcticons">Donnnno/Arcticons</a></strong></div><div>A monotone line-based icon pack for android. Contribute to Donnnno/Arcticons development by creating an account on GitHub.</div></blockquote>

**Comment by gingervitis** [comment]
Pushed a fix for this that just uses some built-in videoJS icon fonts for that icon.

<img width="248" alt="image" src="https://user-images.githubusercontent.com/9563255/120084986-77545480-c089-11eb-9e2d-6fa7febbbc97.png">
