### ISSUE TITLE
Stream stops working when client refreshes page until OBS restarts the stream.

### ISSUE THREAD

**Issue by AE720** [owncast/owncast#1046]
Whenever a stream is active, it works the first time for a computer but refreshing it and then pressing play when the stream is online yields nothing. The browser console gives these errors:

core-f87370e0.js:2642 VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) video append of 527648b failed for segment #0 in playlist 0-0/stream.m3u8 MediaError {code: 3, message: "video append of 527648b failed for segment #0 in playlist 0-0/stream.m3u8"}
(anonymous) @ core-f87370e0.js:2642
log.error @ core-f87370e0.js:2830
error @ core-f87370e0.js:27590
(anonymous) @ videojs-http-streaming.min.js:2429
data.dispatcher @ core-f87370e0.js:4707
trigger @ core-f87370e0.js:4843
EventTarget.trigger @ core-f87370e0.js:5246
(anonymous) @ videojs-http-streaming.min.js:2429
data.dispatcher @ core-f87370e0.js:4707
trigger @ core-f87370e0.js:4843
EventTarget.trigger @ core-f87370e0.js:5246
i.handleAppendError_ @ videojs-http-streaming.min.js:2426
(anonymous) @ videojs-http-streaming.min.js:2426
core-f87370e0.js:2642 VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) audio append of 81584b fa

I turn OBS streaming off and back on and then the play button works but then they refresh or anything like that and the same issue occurs. I'm using Video Passthrough and h264_omx but I've yet to find a configuration that doesn't make this happen

Only other thing to note is in the hls folder, the stream is only audio when I just to play it

Here's what HLSAnalyer shows. My guess is the the m3u8 file has something broken in it's creation
![image](https://user-images.githubusercontent.com/63013864/119274375-9a8c8900-bbdd-11eb-8e06-0a58a5ab15cb.png)

Here is the transcoder.log

ffmpeg started on 2021-05-23 at 15:53:38
Report written to "transcoder.log"
Command line:
/usr/bin/ffmpeg -hide_banner -loglevel warning -fflags +genpts -i /tmp/streampipe.1935 -map v:0 -c:v:0 copy -map "a:0?" -c:a:0 copy -preset ultrafast -var_stream_map "v:0,a:0 " -f hls -hls_time 3 -hls_list_size 3 -segment_format_options "mpegts_flags=+initial_discontinuity:mpegts_copyts=1" -tune zerolatency -pix_fmt yuv420p -sc_threshold 0 -master_pl_name stream.m3u8 -strftime 1 -hls_segment_filename "http://127.0.0.1:38981/%v/stream-pmX9GAqGg%s.ts" -max_muxing_queue_size 400 -method PUT -http_persistent 0 "http://127.0.0.1:38981/%v/stream.m3u8"
Input #0, flv, from '/tmp/streampipe.1935':
  Metadata:
    fileSize        : 0
    audiochannels   : 6
    2.1             : false
    3.1             : false
    4.0             : false
    4.1             : false
    5.1             : true
    7.1             : false
    encoder         : obs-output module (libobs version 25.0.0)
  Duration: 00:00:00.00, start: 0.000000, bitrate: N/A
    Stream #0:0: Audio: aac (LC), 44100 Hz, 5.1, fltp, 327 kb/s
    Stream #0:1: Video: h264 (High), yuv420p(tv, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 2048 kb/s, 30 fps, 30 tbr, 1k tbn, 60 tbc
[hls @ 0x55bf6506c180] Opening 'http://127.0.0.1:38981/0/stream-pmX9GAqGg1621799620.ts' for writing
Output #0, hls, to 'http://127.0.0.1:38981/%v/stream.m3u8':
  Metadata:
    fileSize        : 0
    audiochannels   : 6
    2.1             : false
    3.1             : false
    4.0             : false
    4.1             : false
    5.1             : true
    7.1             : false
    encoder         : Lavf58.20.100
    Stream #0:0: Video: h264 (High), yuv420p(tv, progressive), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 2048 kb/s, 30 fps, 30 tbr, 90k tbn, 30 tbc
    Stream #0:1: Audio: aac (LC), 44100 Hz, 5.1, fltp, 327 kb/s
Stream mapping:
  Stream #0:1 -> #0:0 (copy)
  Stream #0:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=   57 fps=0.0 q=-1.0 size=N/A time=00:00:01.89 bitrate=N/A speed=3.52x    
frame=   68 fps= 65 q=-1.0 size=N/A time=00:00:02.26 bitrate=N/A speed=2.18x    
frame=   88 fps= 57 q=-1.0 size=N/A time=00:00:02.93 bitrate=N/A speed= 1.9x    
frame=  103 fps= 50 q=-1.0 size=N/A time=00:00:03.43 bitrate=N/A speed=1.68x    
frame=  118 fps= 46 q=-1.0 size=N/A time=00:00:03.93 bitrate=N/A speed=1.55x    
[hls @ 0x55bf6506c180] Opening 'http://127.0.0.1:38981/0/stream-pmX9GAqGg1621799623.ts' for writing
[hls @ 0x55bf6506c180] Cannot use rename on non file protocol, this may lead to races and temporary partial files
[hls @ 0x55bf6506c180] Opening 'http://127.0.0.1:38981/0/stream.m3u8' for writing
[hls @ 0x55bf6506c180] Opening 'http://127.0.0.1:38981/stream.m3u8' for writing
frame=  131 fps= 43 q=-1.0 size=N/A time=00:00:04.36 bitrate=N/A speed=1.44x    
frame=  145 fps= 41 q=-1.0 size=N/A time=00:00:04.83 bitrate=N/A speed=1.36x    
frame=  164 fps= 40 q=-1.0 size=N/A time=00:00:05.46 bitrate=N/A speed=1.34x    
frame=  180 fps= 39 q=-1.0 size=N/A time=00:00:05.99 bitrate=N/A speed=1.29x    
[hls @ 0x55bf6506c180] Opening 'http://127.0.0.1:38981/0/stream-pmX9GAqGg1621799625.ts' for writing
[hls @ 0x55bf6506c180] Opening 'http://127.0.0.1:38981/0/stream.m3u8' for writing
frame=  191 fps= 37 q=-1.0 size=N/A time=00:00:06.36 bitrate=N/A speed=1.24x    
frame=  211 fps= 37 q=-1.0 size=N/A time=00:00:07.03 bitrate=N/A speed=1.24x    
frame=  223 fps= 36 q=-1.0 size=N/A time=00:00:07.43 bitrate=N/A speed= 1.2x    
frame=  239 fps= 36 q=-1.0 size=N/A time=00:00:07.96 bitrate=N/A speed=1.19x    
frame=  253 fps= 35 q=-1.0 size=N/A time=00:00:08.43 bitrate=N/A speed=1.17x    
frame=  271 fps= 35 q=-1.0 size=N/A time=00:00:09.03 bitrate=N/A speed=1.17x    
frame=  288 fps= 35 q=-1.0 size=N/A time=00:00:09.59 bitrate=N/A speed=1.17x    
[hls @ 0x55bf6506c180] Opening 'http://127.0.0.1:38981/0/stream-pmX9GAqGg1621799629.ts' for writing
[hls @ 0x55bf6506c180] Opening 'http://127.0.0.1:38981/0/stream.m3u8' for writing
frame=  301 fps= 34 q=-1.0 size=N/A time=00:00:10.03 bitrate=N/A speed=1.14x    
frame=  320 fps= 34 q=-1.0 size=N/A time=00:00:10.66 bitrate=N/A speed=1.15x    
frame=  334 fps= 34 q=-1.0 size=N/A time=00:00:11.13 bitrate=N/A speed=1.14x    
frame=  350 fps= 34 q=-1.0 size=N/A time=00:00:11.66 bitrate=N/A speed=1.13x    
[hls @ 0x55bf6506c180] Opening 'http://127.0.0.1:38981/0/stream-pmX9GAqGg1621799631.ts' for writing
[hls @ 0x55bf6506c180] Opening 'http://127.0.0.1:38981/0/stream.m3u8' for writing
frame=  361 fps= 33 q=-1.0 size=N/A time=00:00:12.03 bitrate=N/A speed=1.11x    
frame=  384 fps= 34 q=-1.0 size=N/A time=00:00:12.79 bitrate=N/A speed=1.12x    
frame=  399 fps= 33 q=-1.0 size=N/A time=00:00:13.29 bitrate=N/A speed=1.11x    
frame=  416 fps= 33 q=-1.0 size=N/A time=00:00:13.86 bitrate=N/A speed=1.11x    
frame=  427 fps= 33 q=-1.0 size=N/A time=00:00:14.23 bitrate=N/A speed= 1.1x    
frame=  447 fps= 33 q=-1.0 size=N/A time=00:00:14.89 bitrate=N/A speed= 1.1x    
frame=  462 fps= 33 q=-1.0 size=N/A time=00:00:15.39 bitrate=N/A speed= 1.1x    
frame=  477 fps= 33 q=-1.0 size=N/A time=00:00:15.89 bitrate=N/A speed=1.09x    
[hls @ 0x55bf6506c180] Opening 'http://127.0.0.1:38981/0/stream-pmX9GAqGg1621799635.ts' for writing
[hls @ 0x55bf6506c180] Opening 'http://127.0.0.1:38981/0/stream.m3u8' for writing
frame=  494 fps= 33 q=-1.0 size=N/A time=00:00:16.46 bitrate=N/A speed=1.09x    
frame=  508 fps= 33 q=-1.0 size=N/A time=00:00:16.93 bitrate=N/A speed=1.09x    
frame=  524 fps= 33 q=-1.0 size=N/A time=00:00:17.46 bitrate=N/A speed=1.09x    
frame=  538 fps= 32 q=-1.0 size=N/A time=00:00:17.93 bitrate=N/A speed=1.08x    
[hls @ 0x55bf6506c180] Opening 'http://127.0.0.1:38981/0/stream-pmX9GAqGg1621799637.ts' for writing
[hls @ 0x55bf6506c180] Opening 'http://127.0.0.1:38981/0/stream.m3u8' for writing
frame=  550 fps= 32 q=-1.0 size=N/A time=00:00:18.33 bitrate=N/A speed=1.07x    
frame=  570 fps= 32 q=-1.0 size=N/A time=00:00:18.99 bitrate=N/A speed=1.08x    
frame=  586 fps= 32 q=-1.0 size=N/A time=00:00:19.53 bitrate=N/A speed=1.08x    
frame=  600 fps= 32 q=-1.0 size=N/A time=00:00:19.99 bitrate=N/A speed=1.07x    
frame=  610 fps= 32 q=-1.0 size=N/A time=00:00:20.33 bitrate=N/A speed=1.06x    
frame=  630 fps= 32 q=-1.0 size=N/A time=00:00:20.99 bitrate=N/A speed=1.07x    
frame=  645 fps= 32 q=-1.0 size=N/A time=00:00:21.49 bitrate=N/A speed=1.07x    
frame=  659 fps= 32 q=-1.0 size=N/A time=00:00:21.96 bitrate=N/A speed=1.06x    
[hls @ 0x55bf6506c180] Opening 'http://127.0.0.1:38981/0/stream-pmX9GAqGg1621799641.ts' for writing
[hls @ 0x55bf6506c180] Opening 'http://127.0.0.1:38981/0/stream.m3u8' for writing
frame=  671 fps= 32 q=-1.0 size=N/A time=00:00:22.36 bitrate=N/A speed=1.06x    
frame=  691 fps= 32 q=-1.0 size=N/A time=00:00:23.03 bitrate=N/A speed=1.06x    
frame=  708 fps= 32 q=-1.0 size=N/A time=00:00:23.59 bitrate=N/A speed=1.06x    
[hls @ 0x55bf6506c180] Opening 'http://127.0.0.1:38981/0/stream-pmX9GAqGg1621799643.ts' for writing
[hls @ 0x55bf6506c180] Opening 'http://127.0.0.1:38981/0/stream.m3u8' for writing
frame=  721 fps= 31 q=-1.0 size=N/A time=00:00:24.03 bitrate=N/A speed=1.05x    
frame=  742 fps= 32 q=-1.0 size=N/A time=00:00:24.73 bitrate=N/A speed=1.06x    
frame=  757 fps= 32 q=-1.0 size=N/A time=00:00:25.23 bitrate=N/A speed=1.05x    
frame=  774 fps= 32 q=-1.0 size=N/A time=00:00:25.79 bitrate=N/A speed=1.06x    
frame=  786 fps= 31 q=-1.0 size=N/A time=00:00:26.19 bitrate=N/A speed=1.05x    
frame=  802 fps= 31 q=-1.0 size=N/A time=00:00:26.73 bitrate=N/A speed=1.05x    
frame=  817 fps= 31 q=-1.0 size=N/A time=00:00:27.23 bitrate=N/A speed=1.05x    
frame=  833 fps= 31 q=-1.0 size=N/A time=00:00:27.76 bitrate=N/A speed=1.05x    
[hls @ 0x55bf6506c180] Opening 'http://127.0.0.1:38981/0/stream-pmX9GAqGg1621799647.ts' for writing
[hls @ 0x55bf6506c180] Opening 'http://127.0.0.1:38981/0/stream.m3u8' for writing
frame=  850 fps= 31 q=-1.0 size=N/A time=00:00:28.33 bitrate=N/A speed=1.05x    
frame=  867 fps= 32 q=-1.0 size=N/A time=00:00:28.89 bitrate=N/A speed=1.05x    
frame=  881 fps= 31 q=-1.0 size=N/A time=00:00:29.36 bitrate=N/A speed=1.05x    
frame=  897 fps= 31 q=-1.0 size=N/A time=00:00:29.89 bitrate=N/A speed=1.05x    
[hls @ 0x55bf6506c180] Opening 'http://127.0.0.1:38981/0/stream-pmX9GAqGg1621799649.ts' for writing
[hls @ 0x55bf6506c180] Opening 'http://127.0.0.1:38981/0/stream.m3u8' for writing
frame=  912 fps= 31 q=-1.0 size=N/A time=00:00:30.39 bitrate=N/A speed=1.05x    
frame=  928 fps= 31 q=-1.0 size=N/A time=00:00:30.93 bitrate=N/A speed=1.05x    
frame=  942 fps= 31 q=-1.0 size=N/A time=00:00:31.39 bitrate=N/A speed=1.05x    
frame=  958 fps= 31 q=-1.0 size=N/A time=00:00:31.93 bitrate=N/A speed=1.05x    
frame=  968 fps= 31 q=-1.0 size=N/A time=00:00:32.26 bitrate=N/A speed=1.04x    
frame=  985 fps= 31 q=-1.0 size=N/A time=00:00:32.83 bitrate=N/A speed=1.04x    
frame= 1004 fps= 31 q=-1.0 size=N/A time=00:00:33.46 bitrate=N/A speed=1.04x    
frame= 1019 fps= 31 q=-1.0 size=N/A time=00:00:33.96 bitrate=N/A speed=1.04x    
[hls @ 0x55bf6506c180] Opening 'http://127.0.0.1:38981/0/stream-pmX9GAqGg1621799653.ts' for writing
[hls @ 0x55bf6506c180] Opening 'http://127.0.0.1:38981/0/stream.m3u8' for writing
frame= 1029 fps= 31 q=-1.0 size=N/A time=00:00:34.29 bitrate=N/A speed=1.04x    
frame= 1046 fps= 31 q=-1.0 size=N/A time=00:00:34.86 bitrate=N/A speed=1.04x    
frame= 1060 fps= 31 q=-1.0 size=N/A time=00:00:35.33 bitrate=N/A speed=1.04x    
frame= 1077 fps= 31 q=-1.0 size=N/A time=00:00:35.89 bitrate=N/A speed=1.04x    
[hls @ 0x55bf6506c180] Opening 'http://127.0.0.1:38981/0/stream-pmX9GAqGg1621799655.ts' for writing
[hls @ 0x55bf6506c180] Opening 'http://127.0.0.1:38981/0/stream.m3u8' for writing
frame= 1095 fps= 31 q=-1.0 size=N/A time=00:00:36.49 bitrate=N/A speed=1.04x    
frame= 1111 fps= 31 q=-1.0 size=N/A time=00:00:37.03 bitrate=N/A speed=1.04x    
frame= 1127 fps= 31 q=-1.0 size=N/A time=00:00:37.56 bitrate=N/A speed=1.04x    
frame= 1141 fps= 31 q=-1.0 size=N/A time=00:00:38.03 bitrate=N/A speed=1.03x    
frame= 1160 fps= 31 q=-1.0 size=N/A time=00:00:38.66 bitrate=N/A speed=1.04x    
frame= 1175 fps= 31 q=-1.0 size=N/A time=00:00:39.16 bitrate=N/A speed=1.04x    
frame= 1186 fps= 31 q=-1.0 size=N/A time=00:00:39.53 bitrate=N/A speed=1.03x    
[hls @ 0x55bf6506c180] Opening 'http://127.0.0.1:38981/0/stream-pmX9GAqGg1621799659.ts' for writing
[hls @ 0x55bf6506c180] Opening 'http://127.0.0.1:38981/0/stream.m3u8' for writing
frame= 1201 fps= 31 q=-1.0 size=N/A time=00:00:40.03 bitrate=N/A speed=1.03x    
frame= 1218 fps= 31 q=-1.0 size=N/A time=00:00:40.59 bitrate=N/A speed=1.03x    
frame= 1235 fps= 31 q=-1.0 size=N/A time=00:00:41.16 bitrate=N/A speed=1.03x    
frame= 1253 fps= 31 q=-1.0 size=N/A time=00:00:41.76 bitrate=N/A speed=1.03x    
[hls @ 0x55bf6506c180] Opening 'http://127.0.0.1:38981/0/stream-pmX9GAqGg1621799661.ts' for writing
[hls @ 0x55bf6506c180] Opening 'http://127.0.0.1:38981/0/stream.m3u8' for writing
frame= 1268 fps= 31 q=-1.0 size=N/A time=00:00:42.26 bitrate=N/A speed=1.03x    
frame= 1284 fps= 31 q=-1.0 size=N/A time=00:00:42.79 bitrate=N/A speed=1.03x    
frame= 1300 fps= 31 q=-1.0 size=N/A time=00:00:43.33 bitrate=N/A speed=1.03x    
[hls @ 0x55bf6506c180] Opening 'http://127.0.0.1:38981/0/stream.m3u8' for writing
frame= 1303 fps= 31 q=-1.0 Lsize=N/A time=00:00:43.43 bitrate=N/A speed=1.03x    
video:10698kB audio:1700kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown

**Comment by gabek** [comment]
Please turn off passthrough.  https://owncast.online/docs/troubleshooting/#misc-video-issues

That log seems to say your audio is 5.1 surround sound, is that accurate?

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="/favicon.png" height="14"> Owncast</div><div><strong><a href="/docs/troubleshooting/">Troubleshooting</a></strong></div><div>Some categories of issues you might run into and some next steps to help troubleshoot.</div></blockquote>

**Comment by AE720** [comment]
> Please turn off passthrough. https://owncast.online/docs/troubleshooting/#misc-video-issues
> 
> That log seems to say your audio is 5.1 surround sound, is that accurate?
> 
> > <img alt="" width="48" src="/images/owncast-logo-1000x1000.png"><img alt="" height="14" src="/favicon.png"> Owncast**[Troubleshooting](/docs/troubleshooting/)**Some categories of issues you might run into and some next steps to help troubleshoot.

Thank you for your response. Correct, OBS is set to 5.1 audio and I tried experimenting with stereo but the same issue persisted. Even thought I was SURE I tried it with Video passthrough off, that seems to have made it work properly again. (Though I did try redoing it from scratch before too). The Bizarre thing is how it works fine the first time but stops when you refresh so I didn't think to explore that much more thoroughly. 

Thank you again. I take it there's nothing particular I can do to make it continue working with passthrough on such as any settings in OBS?

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="/favicon.png" height="14"> Owncast</div><div><strong><a href="/docs/troubleshooting/">Troubleshooting</a></strong></div><div>Some categories of issues you might run into and some next steps to help troubleshoot.</div></blockquote>

**Comment by gabek** [comment]
Because it works with passthrough disabled probably means there are changes you can make in OBS to make it work, but unfortunately I can't say specifically what they are :(.

I'm not sure if this is helpful, but one thing we've found to cause issues in OBS is if you're using the Apple encoder and have the keyframes set to "Auto".  https://github.com/owncast/owncast/issues/955.  But I'm not sure if this is applicable for your particular setup or not.  But passthrough does what it says, it passes through what you're generating from your streaming client, so Owncast doesn't have an opportunity to fix things up and re-encode it into a more compatible format if what is coming in isn't directly playable.

**Comment by AE720** [comment]
> Because it works with passthrough disabled probably means there are changes you can make in OBS to make it work, but unfortunately I can't say specifically what they are :(.
> 
> I'm not sure if this is helpful, but one thing we've found to cause issues in OBS is if you're using the Apple encoder and have the keyframes set to "Auto". #955. But I'm not sure if this is applicable for your particular setup or not. But passthrough does what it says, it passes through what you're generating from your streaming client, so Owncast doesn't have an opportunity to fix things up and re-encode it into a more compatible format if what is coming in isn't directly playable.

Thank you for your help. This was kind of a duh moment for me but changing the Encoder from Hardware (AMD) to Software (x264) did the trick. I'm always mentally adamant against software as a force of habit. Hopefully this will be useful for others with the same issue.

**Comment by gabek** [comment]
There should be no reason you can't use the AMD encoder, so hopefully some experimentation in the future might allow you to find the culprit of the setting.  I don't have a AMD GPU to test with or I'd be able to help troubleshoot, but I wish you luck!
