### ISSUE TITLE
Maximum viewer count

### ISSUE THREAD

**Issue by timowevel1** [owncast/owncast#1058]
Hey,

I got a server 10Gbit/s Up/Down and I would love to know how many viewers it could handle.

Any ideas or is their any limitation?

Thanks!

**Comment by gabek** [comment]
It depends on your configuration.  Read more here: https://owncast.online/docs/scaling/

I generally suggest using an external storage provider.  Chat will have other limitations, but if you aren't using the web interface then you don't have to worry about chat.  So, it all depends on your setup.

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="/favicon.png" height="14"> Owncast</div><div><strong><a href="/docs/scaling/">Scaling Owncast</a></strong></div><div>A place to start when needing to increase the capacity of your server.</div></blockquote>

**Comment by timowevel1** [comment]
> It depends on your configuration. Read more here: https://owncast.online/docs/scaling/
> 
> I generally suggest using an external storage provider. Chat will have other limitations, but if you aren't using the web interface then you don't have to worry about chat. So, it all depends on your setup.
> 
> > <img alt="" width="48" src="/images/owncast-logo-1000x1000.png"><img alt="" height="14" src="/favicon.png"> Owncast**[Scaling Owncast](/docs/scaling/)**A place to start when needing to increase the capacity of your server.

I got 12 dedicated Cores/24 Threads, 64GB of Ram, 10GB/s Bandwith. Any suggestion?

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="/favicon.png" height="14"> Owncast</div><div><strong><a href="/docs/scaling/">Scaling Owncast</a></strong></div><div>A place to start when needing to increase the capacity of your server.</div></blockquote>

**Comment by gabek** [comment]
If you're experiencing a specific issue I'm happy to troubleshoot, but I don't know exactly what you're aiming for or any problems you might be experiencing, so unfortunately I don't have any actionable items for you.

Configure using the documentation as a guide, and test.  If you are having issues I'm happy to help!

**Comment by timowevel1** [comment]
I was just wondering if you know an estimated viewer count the machine can handle. Thanks, I will try it!
