### ISSUE TITLE
Port configuration without /admin page

### ISSUE THREAD

**Issue by Qubik65536** [owncast/owncast#1062]
Due to my server provider's service policy, I can only get a few port to use, and port 8080 is not under my control, so I cannot access to the webpage.
And I saw this in the description of release `0.0.6`
> The config file has been removed.

So is it possible to change the port conf in another way? It would be nice if we can set the port with a conf file or arguments while installing this software.

Best regards

**Comment by gabek** [comment]
You can set a few config settings from the command line:
`./owncast --help`

Specifically you can set `./owncast --webserverport 8081`
