### ISSUE TITLE
"/" in stream key breaks OBS streams

### ISSUE THREAD

**Issue by moan0s** [owncast/owncast#1069]
# Steps to reproduce

* Change Owncast stream key to ZPHwVFJglIHz
* Try streaming with OBS -> should succeed
* Change Owncast stream key to ZPHwV/FJglIHz
* Try streaming with OBS - fails (Owncast log says invalid streaming key; rejecting incoming stream)

# Expected behaviour

* OBS is able to stream with stream Key that includes a slash
* **OR** Owncast puts out a warning, that OBS does not support stream keys containing "/"

This was tested with Owncast v0.0.7 and OBS studio 26.1.2-2

**Comment by gabek** [comment]
Sounds like a bug with OBS!

Is our key generator generating a key with a slash in it, or are you just saying, in general, we should let people know any time they use a slash it won't work with OBS?  If it's us that's generating a key that's not compatible with software we should change that, but if people want to use a slash in their key themselves I don't think we should have a specific flow just for OBS users, as not everyone uses OBS and people should be allowed to use a slash if they want.

**Comment by moan0s** [comment]
No it is not the Key generator, this was a password my password manager generated. I suggest a at least warning, which would've saved me a lot of time debugging. This could be a problem which only affects OBS, but also it would be nice to check other streaming software.

**Comment by aaronpk** [comment]
I just tested streaming via ffmpeg with a slash in the streaming key and it also failed, so it's not a problem unique to OBS.

**Comment by gabek** [comment]
I'm guessing it's up to every client (or in the case of ffmpeg, you personally) to url encode the key properly so any special characters get sent as expected.  There's probably characters other than the slash that would cause issues as well, depending on the broadcasting client and how/if they're encoded. If there's a specification that's common to how all clients are sending along the key we can have documentation around those specifics, but I'm not sure there's anything server-side we should be doing.   While I admit it's lousy if something doesn't work, I don't think we should be saying somebody should or shouldn't be using specific characters.

**Comment by moan0s** [comment]
Just for reference: I found this today in the Documentation, don't know when it was added. Glad this is there!
https://owncast.online/docs/troubleshooting/#your-software-says-your-key-is-incorrect

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="/favicon.png" height="14"> Owncast</div><div><strong><a href="/docs/troubleshooting/">Troubleshooting</a></strong></div><div>Some categories of issues you might run into and some next steps to help troubleshoot.</div></blockquote>
