### ISSUE TITLE
owncast directory bot v7 no go

### ISSUE THREAD

**Issue by controlfreakstudio** [owncast/owncast#1077]
on multiple owncast instanceas, all were updated manual from v6 to v7, the directory announce bot will not trigger for the stream.

instance shows up IN the directory

No change after unticking and reticking admin to be in the directory and restarting service and streaming, nor after hitting the resync to directory option...

confirmed in rocketchat jumboshrimp also in same state

**Comment by controlfreakstudio** [comment]
noticed some minutes after stream established like around when the directory auto toot worked pre update to v7

error | 2:05:16 AM 06/10/2021 | invalid character 'u' looking for beginning of value
-- | -- | --
warning | 2:05:16 AM 06/10/2021 | YP Ping error returned from service:

**Comment by gabek** [comment]
The instance of the directory API is actually completely different between 0.0.6 and 0.0.7.  I'm not sure if that has anything to do with it, but it's very possible.  But the Twitter integration is working, so who knows.

I'll get to it eventually, but my guess is most people don't miss this, as it's really just a spam bot that nobody actually follows :).  But I know how it's nice to get some automated posts out into the world.  Sorry it's been broken!

**Comment by MFTabriz** [comment]
@gabek For me and [more than 100 others](https://botsin.space/users/owncast/followers) this is really a convenient way to get notified when the streams start!

**Comment by gabek** [comment]
Ok maybe I'm not giving it enough credit calling it a spam bot :)

**Comment by gabek** [comment]
Fixed!  https://botsin.space/@owncast/106384960228601005

<blockquote><img src="https://files.botsin.space/media_attachments/files/106/384/960/208/875/136/original/131c139286be0a33.jpg" width="48" align="right"><div><img src="/favicon.ico" height="14"> botsin.space</div><div><strong><a href="https://botsin.space/@owncast/106384960228601005">Owncast (@owncast@botsin.space)</a></strong></div><div>Attached: 1 image

The Bat Station has just started streaming on their #owncast server! Check them out at:
https://batstationrad.io/.  

Now Playing: Wolfsheim - Heroin, She Said

#music #industrial #radio #90s #ebm #futurepop</div></blockquote>
