### ISSUE TITLE
UI Improvement: send button for the chat

### ISSUE THREAD

**Issue by ctsde-markus** [owncast/owncast#1081]
The only feedback i got on my first test was a missing "send" button for the chat in the UI.

When you type some text and add some emojis you need to manually switch back to the normal keyboard to get the "enter" button on mobile devices. This is a bit annoying. Having a "send" button in the UI would circumvent this.

**Comment by gabek** [comment]
Before anybody starts on this check in with @gingervitis to see if she has any ui/button thoughts.
