### ISSUE TITLE
Don't show the viewer count in the embed player when offline

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1088]
Just like the non-embed UI, we shouldn't show the viewer count if the stream is offline.

For anybody looking to work on this, it'll be in `app-video-only.js`.

![image](https://user-images.githubusercontent.com/414923/121468557-d5c5e080-c96f-11eb-95f5-67ba7403e55e.png)

**Comment by MFTabriz** [comment]
@gabek this should be solved now!
