### ISSUE TITLE
Some small updates to backups

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1093]
1. Change the default backup directory to be data directory + `backup`.  So by default `data/backup`.
1. Allow changing this directory via a command line flag (#1082)
1. Make sure this directory is created in `backup.go` when the backup is run and the directory doesn't exist.

**Comment by MFTabriz** [comment]
@gabek Can you explain more what exactly you mean by the 2nd point? How should it be configurable?

Also, for the 3rd point, should we abort if the directory already exists?
