### ISSUE TITLE
Embedable Player

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#110]
Seems like with people wanting to put Owncast video into their own sites it might make sense to have a standardized embeddable player that can be brought in via an iframe.  I only bring this up now so we keep it in mind when we start building the new web components.

**Comment by jeyemwey** [comment]
I am not sure whether iframe is the optimal solution here. I'd suggest creating a ready-to-copy `<video>` tag with some JS, so the video integrates better with the rest of the page.

**Comment by gabek** [comment]
The problem is a video tag isn't enough because many browsers don't support HLS natively, it needs to have videojs (or an equivalent) and css included just for basic playback.  There's nothing stopping people from adding a video tag and importing these extras themselves, but it would be nice to have a simple solution for people to drop in.  Not to mention displaying things like online/offline and viewer counts.  But in lieu of an iframe we could have a piece of javascript that writes everything to the DOM, but there's lots of places where things could get messy there with conflicting styles.  I figure we just take the same approach YouTube does.  Twitch supports both an iframe and DOM replacement with Javascript.

But I don't actually feel strongly about any of it :)

**Comment by jeyemwey** [comment]
I see your point, let's go with iframes.

**Comment by geekgonecrazy** [comment]
Maybe a web component?  So it’s as easy as bringing in the .js file and then the component and args to initialize?  This way all logic is contained with in

**Comment by gingervitis** [comment]
#120 includes a starter "`video-only.html`" file which could server as a source to an embeddable iframe. 

We'll need to iron out some details as to what sort of info/meta data to include on that page if we move forward in that direction.
