### ISSUE TITLE
Change to Configuration → Storage → Optional Settings does not enable Save button

### ISSUE THREAD

**Issue by aral** [owncast/owncast#1108]
A change to Configuration → Storage → Optional Settings does not enable the Save button.

## To reproduce

1. Go to Configuration → Storage
2. Add regular settings, hit save
3. Open the Optional Settings accordion panel
4. Add a URL under Serving Endpoint 

## What should happen

Save button should re-enable as there’s been a change.

## What actually happens

Save button stays disabled.

## Workaround

Also one of the settings in the main Configuration → Storage settings (e.g. Endpoint), save, then change the main setting back and save again.

**Comment by gabek** [comment]
Thanks for reporting this!
