### ISSUE TITLE
Stream embeds do not work when installed using Site.js

### ISSUE THREAD

**Issue by aral** [owncast/owncast#1109]
__This is a Site.js issue, not an Owncast issue.__ Opening it here so there’s a record of it.

Site.js sets the `X-Frame-Options` header to `SAMEORIGIN` by default as a security feature.

This blocks Owncast streams from being embedded.

## Fix (new installations)

This has now been fixed in Site.js 17.2.0, which is live. Any future Owncast installations made with this version of Site.js will not send the `X-Frame-Options` header and so your Owncast streams can be embedded on other sites.

## Fix (existing installations)

While Site.js will auto-update to the latest 17.2.0 within the next six hours, it will not auto-heal from this issue without a manual disabling and re-enabling (as it needs to recreate the systemd service to add the new `--allow-embeds` flag to the Site.js launch command.)

To fix an existing installation:

1. SSH into your server.
2. Run: `site disable`
3. Run: `site enable --owncast`

That’s it. Your server should now allow embeds.

**Comment by aral** [comment]
Closing the issue as this has now been fixed in Site.js and the steps for existing installations has been documented here.

Please feel free to reopen if you run into any problems.

**Comment by gabek** [comment]
Makes sense, thanks for dropping that here in case people run into it!
