### ISSUE TITLE
Viewer count does not increase with embedded player

### ISSUE THREAD

**Issue by aral** [owncast/owncast#1110]
![Screenshot from 2021-06-16 16-57-35@2x](https://user-images.githubusercontent.com/41798/122254385-fa1c4280-cec4-11eb-9629-aa723a55d5f5.png)

When someone watches via an embedded player, the viewer count does not increase.

## Steps to reproduce

1. Open https://owncast.online/docs/embed/ in multiple browser windows.

## What should happen

The viewer count should increase.

## What actually happens

The viewer count does not increase.

## Note

I saw in the code that there was a recent move from using sockets to pings. I waited for the 10 second ping duration to ensure that it was not that and confirmed that the viewer count does not increase after 10 seconds either.

**Comment by gabek** [comment]
watch.owncast.online is using the `develop` branch of Owncast that is heavily in development and is being changed to the new ping method.  Any 0.0.7 install will be using the old method and looks to be functioning properly.  For example open up multiple copies of https://omusictv.stream/embed/video.

<blockquote></blockquote>

**Comment by aral** [comment]
Awesome, thanks. Please feel free to close this :)
