### ISSUE TITLE
Offline Web UI: Display when the last time there was a stream

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1111]
Sometimes I'll visit an instance and I'll be curious when the last time they streamed was.  It would make sense to find a place to put this in the web UI somewhere.  There's already a `lastConnectTime` in the `/api/status` response we could use for this.

I'd like @gingervitis's opinion of where this could go and what it should look like before anybody actually makes the change.

**Comment by gingervitis** [comment]
something like this? I'm seeing `lastConnectTime` come back as null.
<img width="820" alt="image" src="https://user-images.githubusercontent.com/9563255/122438644-c5a19880-cf4f-11eb-9239-f71d365f5700.png">

**Comment by gabek** [comment]
I think it resets on server restart currently, but I can change it so it's persisted.

We could use `lastDisconnectTime` instead, since that's probably closer to what "online" what would mean.
