### ISSUE TITLE
Monitor the time it takes for a single video segment to get transferred to clients

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1116]
We can merge this with #875 and create a specific controller for returning local HLS segments, and we can monitor the time between request start and request end.  If this duration is greater or equal than the duration of a single HLS segment we can throw a warning that clients may be having a bad playback experience. 

We could do this on a per-client basis (single client X is having a bad time) or on average (many clients may be having a bad time).  Average would be easier and less noisy, and probably more useful, as one person's bad connection isn't the streamer's fault, but if most people have having a bad time then the streamer should know about it so they can fix their configuration.

Could probably use/update the `performanceTimer` that's already in the project for this that was originally built for monitoring the speed of sending segments to 3rd party storage providers, a similar problem: https://github.com/owncast/owncast/blob/develop/utils/performanceTimer.go

**Comment by gabek** [comment]
@geekgonecrazy Next time you're looking to pick up a standalone Owncast thing, this might be a good one.  It should help streamers get a basic idea if their stream quality is more than their outbound connection to their viewers can handle.

**Comment by geekgonecrazy** [comment]
Hm.. this would be interesting.

It would almost have to be client side tracked.  Since segments might be on s3 or cdn.

I assume we wouldn't want to tell backend about every issue but only if pattern or x occurrences?

**Comment by gabek** [comment]
I was thinking this would just be for non-s3 and non-cdn scenarios, since that's how most people are setup.  And if they are using a storage provider or a CDN then they probably don't even have the problem to begin with.  So I think it's fair to monitor just the request/response duration on the backend for this specific scenario.  As long as we can get the connection close event from the http request.  In the future, though, I'd like to go all out on real client-side performance metrics.  But that's a much bigger thing requiring a bunch of moving parts with the frontend, new APIs and dashboard work: #793.

**Comment by gabek** [comment]
Closing in favor of client-side metrics. https://github.com/owncast/owncast/issues/793
