### ISSUE TITLE
Directory looks to have a performance problem

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1117]
Browser CPU usage seems to go up if you leave the directory open.  Time to do some profiling.

**Comment by gabek** [comment]
CPU drops when closing the tab.  
![image](https://user-images.githubusercontent.com/414923/122489836-636b8680-cf95-11eb-82a4-2b431d2026e3.png)

**Comment by thilobillerbeck** [comment]
I could take a look at that.

**Comment by gabek** [comment]
Awesome!

**Comment by thilobillerbeck** [comment]
Just a quick update, that a possible solution for the performance problem ist found. It just needs to be tested some more.

**Comment by gabek** [comment]
@thilobillerbeck Were you ever able to track this down?  My laptop just froze up from leaving a directory tab open too long and I figured we should fix this :)

**Comment by thilobillerbeck** [comment]
Did you try out the fix I pushed to the separate branch? My intention was for people to test it before it gets merged.

**Comment by gabek** [comment]
OH! I had no idea there was a branch!

**Comment by gabek** [comment]
Closed in https://github.com/owncast/owncast-yp/pull/78.
