### ISSUE TITLE
Web frontend external actions container div creates blank space

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1119]
`#external-actions-container` has a margin of `1em` even when there are no external action buttons, creating an empty spot in the UI.  Maybe we can not render that div at all if it's empty.

![image](https://user-images.githubusercontent.com/414923/122501100-e77b3980-cfa8-11eb-980d-3ca420529621.png)

**Comment by jyggiz** [comment]
Hey! Can i take this issue?

**Comment by gabek** [comment]
Absolutely, thanks!

**Comment by gabek** [comment]
Weird.  This issue returned after it was fixed.

![image](https://user-images.githubusercontent.com/414923/127235005-ed4718ef-7469-4dbf-9a7c-869e29029af5.png)
