### ISSUE TITLE
Admin chat message moderation UI selected state is a bad color

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1120]
The selected state color of the rows makes the content unreadable.

![image](https://user-images.githubusercontent.com/414923/122511332-e99ac380-cfbb-11eb-84c3-c25df0fe44e7.png)

**Comment by jyggiz** [comment]
Hey, can I take this issue? What can you advise in this case? Maybe use one of the colors that are already in use within the project?

**Comment by gabek** [comment]
Yeah!  Feel free to experiment.  As long as it's readable it's probably fine.

Let me know if you have any questions getting the [owncast/owncast-admin](https://github.com/owncast/owncast-admin) project running.

**Comment by gabek** [comment]
Hey @jyggiz!  Are you still looking at this?

**Comment by gabek** [comment]
I'll go ahead and unassign this from you @jyggiz, just in case somebody else wants to grab it.  But feel free to chime in if you still want to contribute!
