### ISSUE TITLE
Improve caching headers for .ts files

### ISSUE THREAD

**Issue by nodomain** [owncast/owncast#1129]
During our live event I was investigating the cache hit ratio. The TS files are served to 30% from the CloudFront cache. I feel that can be improved.

After skimming through https://d1.awsstatic.com/whitepapers/amazon-cloudfront-for-media.pdf I noticed that AWS recommends a shorter `max-age` compared to that what you are using ("cache forever because it does not change").

> Ensure the origin is sending a Cache-Control header with appropriate values. In a live streaming scenario, expect the Origin setting max-age value close to video segment length for manifest files. For VOD workloads both manifest and video segments can be considered as static assets, therefore max- age can be set for longer period, to the extent of days or weeks. If managing cache-control directives is too complicated to be done on the origin level, CloudFront provides the possibility to set a Minimum, Default and Maximum TTL. However, in this case it’s advisable to create separate behaviors for video segments and manifest because they may require different TTL settings and cache key policies. 

This makes total sense in a live scenario because the cache just serves the most recent stuff, because it is live - right?

I might send a PR to this after further optimiziation ;-)

**Comment by nodomain** [comment]
I think I'll contribute to the docs repo.

> Remove the Accept-Encoding header from the cache key by disabling compression support in cache policy. The video content is compressed in the encoding process at the origin with adequate compression format for this type of content.

Now *most* of the TS is coming from the cache, using these settings in a *.ts specific behavior.

![image](https://user-images.githubusercontent.com/104389/122771271-8ef8b480-d2a6-11eb-8e04-652f87700b10.png)

**Comment by gabek** [comment]
> In a live streaming scenario, expect the Origin setting max-age value close to video segment length **for manifest files**.

In this case it's referring to the HLS playlists, not the video segments themselves.  We set the value to `0` for playlists because we don't want them to be cached at all in a live situation since they're changing.  But like the doc says, we _could_ cache them up to the segment length, but I feel better about playlists not being cached at all.  This blurb doesn't seem to state any downside to caching video segments for a longer duration.

Good find disabling `Accept-Encoding`!  Owncast isn't itself doing compression of HTTP responses, but it's likely any kind of proxy server in front of Owncast might be.

**Comment by nodomain** [comment]
Yes - I'll iterate to the best solution and try to give something back by contributing to the docs. Keep up the great work!

**Comment by gabek** [comment]
Awesome, thank you!

**Comment by nodomain** [comment]
Further improvement: the "Origin" header has to be part of the cache key because of the video.js CORS preflight requests.
Then you can achieve a >90% cache hit ratio:
![image](https://user-images.githubusercontent.com/104389/122890935-69ba8380-d344-11eb-8000-5d3a1e656901.png)
