### ISSUE TITLE
IndieAuth?

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#113]
Somebody suggested we look into IndieAuth.

https://indieauth.com/developers

I could see a scenario where we continue to allow un-auth'ed users, but if somebody wants to authenticate in some way they could be shown as such in the chat via some kind of styling.

Just an idea we can think about for down the road.

**Comment by Ruxton** [comment]
Happy to help make this happen

**Comment by gabek** [comment]
Awesome!  The web UI is going through a refactor right now (#103), so any changes that effect the frontend will need to wait for that.  But it allows for some brainstorming of how this might function in the meantime.

It looks like not a lot of services provide support for IndieAuth.  When testing it with my web site that has Mastodon, Keybase, Linkedin, Spotify and LastFM links only Github came back as a provider.  This is fine, but it does put it a bit in the category of something only advanced/power users would use or understand unless mainstream services (Like Facebook or Instagram or something) were compatible.

If only power users were to use this, and we style people to say "these people are authenticated and these people are not" then it kind of creates this weird dichotomy in the chat between people who support a very specific thing and those who don't.

All something to think about.

**Comment by geekgonecrazy** [comment]
Indie web is just oauth right?  If so I’d target oauth and let people chose to use indie web, or maybe even their own solution

**Comment by gabek** [comment]
I don't believe at the moment we have a solid use case for adding any user-facing auth, especially after we removed avatars in chat, so I'm closing this.
