### ISSUE TITLE
Collapse news content in the admin home page

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1137]
Right now it shows the entire content.  We should just show the description and collapse the full body under a "read more" or something similar.

Antd collapse: https://ant.design/components/collapse/

![image](https://user-images.githubusercontent.com/414923/123191399-0e78b600-d456-11eb-94a4-2a9af4e4aaa4.png)

**Comment by MFTabriz** [comment]
@gabek Can I give it a try?

**Comment by gabek** [comment]
Yeah, absolutely!  Thanks!
