### ISSUE TITLE
Custom target framerates

### ISSUE THREAD

**Issue by bsncubed** [owncast/owncast#1138]
Hi 

Is it possible for you to add 25fps and 50 fps? In v0.05 i could manually edit the config file to make it work, but i can't find a work around now.

**Comment by gabek** [comment]
I haven't seen others ask for non-standard framerates, but I'll keep this open for a bit to let others chime in.  Adding this would add complexity to the configuration and I'm not sure there's many people who would utilize it.

**Comment by YohannLYD** [comment]
I too would be interested in having 25/50fps as an option.
This is actually a broadcast standard framerate in the European broadcast sector and haven't been able to use the software in production for this reason.

**Comment by gabek** [comment]
If all we want to do is add it to our current selector control, we can do that.  I fear it'll start confusing people with too many options and that we would need to change to a completely different way to select framerates.  But if somebody wants to add this to the control we can give it a spin.

**Comment by YohannLYD** [comment]
If too many framerates is confusing to people (is it really?) I'd be down to replace 24fps with 25fps to keep the number of options to the minimum.
After all 24fps is not really a video standard, but a cinema/film one.

**Comment by bsncubed** [comment]
Would you be open to adding 50fps as well? just to keep the feature set on par with the US framerates (30/60)

**Comment by gabek** [comment]
>  I'd be down to replace 24fps with 25fps to keep the number of options to the minimum.

I'm sure you would be ok with it, you're the one who asked for it :)

The concern I have is things are kind of setup to be "low, medium, high, stupid high".  So adding more is like saying "low, a different low, medium, another medium"... and that doesn't make a lot of sense to people trying to make a decision.  Like why would we have 24 _and_ 25?  I know it makes sense to you, but I can see that being kind of weird to normal people.

Just for my own knowledge, why does "broadcast standard" matter when it's the internet?  If you were to downsample 25fps to 24fps, what is the major drawback there?  I understand if this was broadcast television where standards need to be adhered to or the television won't play back a signal, but internet video is certainly more flexible.

**Comment by gabek** [comment]
But again, if somebody wants to add these FPS options let's give it a spin.  If nobody does it then I'll eventually get around do it and if it's confusing or the control just doesn't work with it then it'll have to be readdressed.

**Comment by YohannLYD** [comment]
> Just for my own knowledge, why does "broadcast standard" matter when it's the internet? If you were to downsample 25fps to 24fps, what is the major drawback there? I understand if this was broadcast television where standards need to be adhered to or the television won't play back a signal, but internet video is certainly more flexible.

Because of workflow. I'm not working in a TV channel, but in conditions that uses broadcast settings where I find interesting potential uses for owncast. Like online conferences and such.
I've been testing owncast with a stream coming from a Blackmagick Web Presenter. The camera outputs 25fps to the streaming device. It works well but since the streaming engine (owncast) doesn't provide 25fps, I will have image drops during the stream which could have been avoided.

Similarly if I had to make a video edit that would include a recording of the owncast stream. Having a 24fps source in a 25fps project sequence is a bother for the very same reasons (image drops and maybe audio skips).

**Comment by Kunsi** [comment]
Maybe we could just have an option to allow arbitrary frame rates? The bitrate setting allows incrementing in 100kbit/s steps, why shouldn't the framerate selector do the same?

**Comment by oixtron** [comment]
> Maybe we could just have an option to allow arbitrary frame rates? The bitrate setting allows incrementing in 100kbit/s steps, why shouldn't the framerate selector do the same?

I second that suggestion. Hiding that option behind another menu won't "confuse" anyone imo. But also, 25 and 50 fps aren't arbitrary at all and besides professional TV and broadcasting, 50fps is a de facto standard for video refresh rates here in Europe.

**Comment by aaronpk** [comment]
I would not recommend a slider for setting arbitrary frame rates. But I would recommend adding the standard Europe frame rates, 25 and 50fps

**Comment by controlfreakstudio** [comment]
assign pls. I have some changes tested to propose based on balance and the above input. will offline a small chicken vs egg paradox.
