### ISSUE TITLE
Add proper landing page for browsers without the JS support

### ISSUE THREAD

**Issue by MFTabriz** [owncast/owncast#1139]
I understand that we need the client-side JS support for the app to work. But the JS-disabled browsers should be presented with

1. A proper explanation of why Owncast needs JS to work, and
2. Some alternative ways of watching the stream (maybe just throw a HLS link for now)

What they are currently encountering is this:
![Screenshot 2021-06-26 at 18-08-33 Owncast](https://user-images.githubusercontent.com/39205857/123519300-948d3a80-d6aa-11eb-81d7-eec632ba7570.png)

**Comment by gingervitis** [comment]
There's currently `<noscript>` block, which I agree could use more attention.
https://github.com/owncast/owncast/blob/develop/webroot/index.html#L95

<blockquote><img src="https://repository-images.githubusercontent.com/266445736/4f82fb80-a5b1-11ea-8f1c-69d316f861b5" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/owncast/owncast">owncast/owncast</a></strong></div><div>Take control over your live stream video by running it yourself.  Streaming + chat out of the box. - owncast/owncast</div></blockquote>
