### ISSUE TITLE
aarch64 / armv8 support

### ISSUE THREAD

**Issue by Stayingfalse** [owncast/owncast#1156]
Great to see arm7 support however as Arm Arch develops would be great to see further support for aarch64 and armv8.

**Comment by gabek** [comment]
arm64 has been added to the architecture list for the next release list, but armv8 hasn't been.  So that can be added as well.

**Comment by gabek** [comment]
Looks like unfortunately our cross-architecture toolchain, xgo, doesn't currently support armv8 :(.

https://github.com/crazy-max/xgo/blob/e5bbdc1cd854b4f4d9a14c2e30977f4ca142d82c/doc/usage/limit-build-targets.md

<blockquote><img src="https://opengraph.githubassets.com/a9c563ec5fcae8c250f802a4bcac34d2487b3c1ff533506bd6abac82d4c23587/crazy-max/xgo" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/crazy-max/xgo">crazy-max/xgo</a></strong></div><div>Go CGO cross compiler. Contribute to crazy-max/xgo development by creating an account on GitHub.</div></blockquote>

**Comment by Stayingfalse** [comment]
Arm64 and Armv8 are the same thing 64bit was added in v8 so that is cool.

Aarch64 also essentially being another name for Arm64 should mean future Arm64 feature should include all.

**Comment by gabek** [comment]
Oh ok, great!  Good to go, then!
