### ISSUE TITLE
can i host this on heroku ?

### ISSUE THREAD

**Issue by satyammayy** [owncast/owncast#1157]

**Comment by gabek** [comment]
You cannot run this on any kind of dynamic application platform.  You need something with persistent storage, not something that will spin up and down dynamically.  And Heroku, if I remember correctly, will have multiple copies of your application running  load balanced, and that won't work for Owncast.  Owncast is designed to be run as a single instance.

**Comment by gabek** [comment]
If you have any other specific questions, please feel free to re-open.
