### ISSUE TITLE
Firefox issues (or maybe just Waterfox and LibreWolf)

### ISSUE THREAD

**Issue by closewall** [owncast/owncast#1158]
I hosted a stream yesterday, and while it worked mostly fine, I found that on LibreWolf 89.0(latest) on both Windows and Linux, I couldn't use the chat. It would just say "Chat is offline" even though the stream is running and chat is enabled. I mitigated this by just using an Ungoogled Chromium appimage, but I'd still prefer it working with LibreWolf.

On top of that, Waterfox outright won't work at all, even with all addons disabled. It just loads the splash screen and nothing more. I also had a viewer yesterday using Waterfox, and he said the chat wasn't working for him.

I am using the ich777 docker image of Owncast: https://hub.docker.com/r/ich777/owncast/

I already asked the maintainer, and he says he wasn't sure what the problem was. He's only using the Owncast binary to make it work and isn't doing anything special with it.

**[Edit]** I solved the issue on LibreWolf. The LocalCDN extension was breaking the chat, and turning it off fixes it.

**[Edit]** The Waterfox issue is a reference error:
![img778934](https://user-images.githubusercontent.com/49519142/124399653-2dcde800-dd60-11eb-803c-df3f298a3612.png)

LibreWolf screenshot:
![img7366](https://user-images.githubusercontent.com/49519142/124398417-f871cc00-dd58-11eb-9d53-611c971fefa9.jpg)

Waterfox screenshot:
![img83467](https://user-images.githubusercontent.com/49519142/124398416-f6a80880-dd58-11eb-8508-ef132e8d27db.jpg)

**Comment by gabek** [comment]
Could you share any errors in the browser console that you're seeing?

**Comment by closewall** [comment]
> Could you share any errors in the browser console that you're seeing?

For Waterfox, it's simple:

![img778934](https://user-images.githubusercontent.com/49519142/124399653-2dcde800-dd60-11eb-803c-df3f298a3612.png)
[edit] fixed screenshot

For LibreWolf:

Websocket Error. Chat is likely not working. Visit troubleshooting steps to resolve. https://owncast.online/docs/troubleshooting/#chat-is-disabled: Websocket closed. websocket.js:165:13
Firefox can’t establish a connection to the server at wss://awatches.techxodus.org/entry. websocket.js:47:15
Uncaught SyntaxError: JSON.parse: unexpected character at line 1 column 2 of the JSON data
    onError https://awatches.techxodus.org/js/utils/websocket.js:124
websocket.js:124:54
Firefox can’t establish a connection to the server at wss://awatches.techxodus.org/entry. websocket.js:47:15
Uncaught SyntaxError: JSON.parse: unexpected character at line 1 column 2 of the JSON data
    onError https://awatches.techxodus.org/js/utils/websocket.js:124
websocket.js:124:54
Websocket Error. Chat is likely not working. Visit troubleshooting steps to resolve. https://owncast.online/docs/troubleshooting/#chat-is-disabled: Websocket closed. websocket.js:165:13
Firefox can’t establish a connection to the server at wss://awatches.techxodus.org/entry. websocket.js:47:15
Websocket Error. Chat is likely not working. Visit troubleshooting steps to resolve. https://owncast.online/docs/troubleshooting/#chat-is-disabled: Websocket closed. websocket.js:165:13
Uncaught SyntaxError: JSON.parse: unexpected character at line 1 column 2 of the JSON data
    onError https://awatches.techxodus.org/js/utils/websocket.js:124
    createAndConnect https://awatches.techxodus.org/js/utils/websocket.js:50
websocket.js:124:54
Firefox can’t establish a connection to the server at wss://awatches.techxodus.org/entry. websocket.js:47:15
Websocket Error. Chat is likely not working. Visit troubleshooting steps to resolve. https://owncast.online/docs/troubleshooting/#chat-is-disabled: Websocket closed. websocket.js:165:13
Uncaught SyntaxError: JSON.parse: unexpected character at line 1 column 2 of the JSON data
    onError https://awatches.techxodus.org/js/utils/websocket.js:124
    createAndConnect https://awatches.techxodus.org/js/utils/websocket.js:50
    setTimeout handler*scheduleReconnect https://awatches.techxodus.org/js/utils/websocket.js:130
    onClose https://awatches.techxodus.org/js/utils/websocket.js:119
    createAndConnect https://awatches.techxodus.org/js/utils/websocket.js:49
websocket.js:124:54

There's a lot more, but it's mostly the same.

**Comment by gabek** [comment]
What happens when you click "Learn more" in the "customElements is not defined" message? That sounds like the browser you're using doesn't support WebComponents.

>  Firefox can’t establish a connection to the server at wss://awatches.techxodus.org/entry

I just tried with Firefox and it seems to be working ok.  Do you have any kind of extension that's blocking websockets or something?

**Comment by closewall** [comment]
> What happens when you click "Learn more" in the "customElements is not defined" message? That sounds like the browser you're using doesn't support WebComponents.

It redirects me to this page: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Not_defined

I also edited my post to include the part on the right. I believe the error is referring to lite-youtube.js:300:1

> > Firefox can’t establish a connection to the server at wss://awatches.techxodus.org/entry
> 
> I just tried with Firefox and it seems to be working ok. Do you have any kind of extension that's blocking websockets or something?

Yeah, up to date vanilla Firefox seems to work fine. It seems to be the forks like Waterfox and LibreWolf having problems.

My LibreWolf is full of extensions (as seen in the screencap) but I turned off all extensions for Waterfox and still get that error.

<blockquote><img src="https://developer.mozilla.org/mdn-social-share.0ca9dbda.png" width="48" align="right"><div><strong><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Not_defined">ReferenceError: "x" is not defined - JavaScript | MDN</a></strong></div><div>The JavaScript exception "variable is not defined" occurs when there is a
  non-existent variable referenced somewhere.</div></blockquote>

**Comment by gabek** [comment]
Discussed in in chat: https://owncast.rocket.chat/channel/general?msg=qBxCMYewnG5kwYZtH

Solution: There was a CDN extension interfering with the websocket, and some Firefox forks don't yet support WebComponents.

<blockquote><img src="assets/favicon_512.png" width="48" align="right"><div><strong><a href="https://owncast.rocket.chat/channel/general?msg=qBxCMYewnG5kwYZtH">Owncast</a></strong></div></blockquote>
