### ISSUE TITLE
Detect if the directories we expect to write to have bad permissions

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1166]
Right now we fail silently if we can't write to the hls directories.  We should be nice and proactively check things like this at launch to alert on this issue.  This can probably done at the same time as https://github.com/owncast/owncast/issues/875.

See https://owncast.rocket.chat/channel/general?msg=d8i9CoqERqji3ejSt for context.

**Comment by MFTabriz** [comment]
@gabek Is it enough if we check the hls and all of its subdirectories (if any) are writable or not?

**Comment by gabek** [comment]
We remove and recreate the hls directories at launch as a quick way to start fresh, since old files aren't useful. I think we just need to be better about handling any errors that come from that.

https://github.com/owncast/owncast/blob/develop/core/core.go#L117-L127

<blockquote><img src="https://repository-images.githubusercontent.com/266445736/4f82fb80-a5b1-11ea-8f1c-69d316f861b5" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/owncast/owncast">owncast/owncast</a></strong></div><div>Take control over your live stream video by running it yourself.  Streaming + chat out of the box. - owncast/owncast</div></blockquote>
