### ISSUE TITLE
Add VideoToolbox support to enable hardware encoding for macOS users

### ISSUE THREAD

**Issue by cablebox** [owncast/owncast#1176]
on Macs, [FFmpeg can use VideoToolbox](https://trac.ffmpeg.org/wiki/HWAccelIntro#VideoToolbox) which then abstracts away the offloading of video encoding to hardware as available (QuickSync/GPU/SoC, etc). 

A note that It's not as flexible in terms of quality options, but does have a `-realtime` flag.

`ffmpeg -hide_banner -codecs | grep 264
 DEV.LS h264                 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (encoders: libx264 libx264rgb h264_videotoolbox )`

**Comment by gabek** [comment]
I'm not sure how many people are running Owncast on a Mac publicly (as opposed to using it for testing or development purposes) but I'll leave this open to let others chime in if they find it useful to them.  If people would like to see it, it can be added.
