### ISSUE TITLE
Update Backblaze storage documentation

### ISSUE THREAD

**Issue by closewall** [owncast/owncast#1183]
My Owncast stream was functioning when I wasn't using external storage, though I wanted to expand my upload bandwidth to prevent users from getting buffering.

I tried Backblaze on the 10gb free trial, configured it as the docs specify, but when trying to watch my stream, the video doesn't play. It's just a slide show that shows a different instance of the video every 20 seconds or so and a constant buffering circle in the middle. Here's the log of the constantly looping error:

```
time="2021-07-13T19:31:19+10:00" level=warning msg="Giving up on hls/0/stream-tyNTKxmng1626168670.ts InvalidArgument: Unsupported value for canned acl 'public-read'\n\tstatus code: 400, request id: dd7a3b1ab254c85e, host id: aMyNiomMFONIwpWVLZsIy0zDxM5NmdTAD"

time="2021-07-13T19:31:19+10:00" level=error msg="Giving up on hls/0/stream-tyNTKxmng1626168670.ts"
```

I'm using ich777's Owncast docker container. I don't think he'll be able to help much with this though, it's a pretty vanilla image.

https://hub.docker.com/r/ich777/owncast/

**Comment by gabek** [comment]
Looks like the error is
> Unsupported value for canned acl 'public-read'

I don't know the specifics of the innards of Backblaze, but does that ACL mean anything to you?  Are you setting that somewhere?

**Comment by closewall** [comment]
> Looks like the error is
> 
> > Unsupported value for canned acl 'public-read'
> 
> I don't know the specifics of the innards of Backblaze, but does that ACL mean anything to you? Are you setting that somewhere?

Nope. I just followed the instructions here: https://owncast.online/docs/storage/backblaze/

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="/favicon.png" height="14"> Owncast</div><div><strong><a href="/docs/storage/backblaze/">Backblaze B2</a></strong></div><div>Backblaze B2's first 10G of storage is free, and the first 1G of download per day is free after that.  Afterwards they charge $0.01/G.</div></blockquote>

**Comment by gabek** [comment]
Looks like there's a default acl of `public-read`, but according to Backblaze's documentation that seems to be correct.

> The call will succeed only when specified ACL matches the ACL of the bucket.

Is your bucket public?

> The Backblaze S3 Compatible API features limited support for ACLs (Access Control Lists). Get Object ACL and Get Bucket ACL calls will work as expected. However, object-level ACLs are not supported. For example, a Get Object ACL call returns the ACL for the Bucket the object is contained in.
>
>If a Bucket is private, the ACL returned for the Bucket and any files within the bucket will be “private”. If a Bucket is public, the ACL returned for the Bucket and any files within the bucket will be “public-read”.
>
>The S3 Compatible API supports the Put Bucket ACL call to change between "private" and “public-read” only. Attempting to put a different value will return an error.
>
>The Put Object ACL call only supports the same canned ACL values mentioned previously. The call will succeed only when specified ACL matches the ACL of the bucket.

**Comment by closewall** [comment]
> Looks like there's a default acl of `public-read`, but according to Backblaze's documentation that seems to be correct.
> 
> > The call will succeed only when specified ACL matches the ACL of the bucket.
> 
> Is your bucket public?

Looks like setting it to public fixed it. I was just following the docs and I didn't see anything about setting the bucket to public.

Another thing: when generating the application keys, you have to make sure "Allow access to Bucket(s):" is set to "All" and not just the bucket you created.
