### ISSUE TITLE
Remove chat avatars

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#119]
* Do we want to keep them?
* If so, we should replace them.

I was thinking of an identicon based solution using the username of the person as a hash: https://github.com/jakobvarmose/go-qidenticon

But I don't know.  Maybe we don't want them at all, I'm not sure if they add anything.

**Comment by gabek** [comment]
I'm more along the lines of maybe removing avatars all together, like Twitch.  They look nice, but they don't add a lot.

Gravatars are handy, but I'd like to hold off on forcing any kind of identification until we have to.  We've talked about auth options, but I don't think it's currently worth the added complexity on a user's part.

**Comment by gabek** [comment]
No changes on this front planned.  Closing.

**Comment by gabek** [comment]
In talking to @gingervitis and doing an informal poll I think we're going to remove them.  They don't provide any real personalization or value.

**Comment by devadeka** [comment]
any chance i can have a crack at this for hacktoberfest...? thanks

**Comment by gabek** [comment]
Hey @devadeka, absolutely!  Thanks for wanting to take a look at it.  @gingervitis chime in if you have any specific thoughts around if there needs to be any design changes in order to facilitate this.

**Comment by gingervitis** [comment]
Yeah I think this one would be as simple as removing all the implementations of the user avatars that show up in the messages, as well as in the username change form in the header. I believe the avatar urls also get sent per message, as well as are saved to localStorage,  so all those will have to get cleaned up as well.

Thanks for helping out!

**Comment by devadeka** [comment]
sweet... cheers...

**Comment by gabek** [comment]
Hi @devadeka, just checking in.  Are you still looking to do this?  Thanks!

**Comment by devadeka** [comment]
@gabek yes I am still looking to do this... but other stuff came up
 if there is someone else looking to take it over, I have no issues if you reassign

**Comment by jeyemwey** [comment]
I can do it if @devadeka doesn't have the time.

**Comment by devadeka** [comment]
> I can do it if @devadeka doesn't have the time.

All yours mate... sorry @gabek
