### ISSUE TITLE
doing a ctrl+c to copy something closes the chat panel

### ISSUE THREAD

**Issue by gingervitis** [owncast/owncast#1201]
I know we're not looking doing keyboard shortcuts when the chat text field is in focus, but if someone wanted to do a ctrl+c to copy/paste something from the page, the text field will lose focus, then the chat panel will close which is a jarring experience.

This seems to happen in Safari, but not Chrome.

**Comment by MFTabriz** [comment]
This does not happen in Firefox either.

**Comment by gabek** [comment]
https://github.com/owncast/owncast/issues/1489 is a similar issue. I feel like we're always running into the keyboard shortcuts being accidentally fired and then we go back and fix it. This will keep coming up as new input fields get added. It'd be nice to fix this for good.

**Comment by gabek** [comment]
Made a change where the "target" element must explicitly be the general body of the page, meaning it's not being fired based on an input field. This should fix it for good going forward I hope.
