### ISSUE TITLE
Trying to restream from a nginx rtmp server to owncast, twitch and whatever else...

### ISSUE THREAD

**Issue by teklynk** [owncast/owncast#1213]
I have set up simple nginx server specifically for rtmp traffic on port 1935. This is running inside a docker containers and I have mapped port 9095 to 1935. In OBS my streaming server points to rtmp://192.168.x.x:9095/live/. I have tested this with an alternate Twitch account and it works fine. However, when I try to push to my owncast server.... nothing happens. Here is part of my nginx config.

`        application live {
            live on;
            record off;
            push rtmp://192.168.0.xx/live/xxxxxxstreamkeyxxxxx;
            push rtmp://iad05.contribute.live-video.net/app/xxxxxxstreamkeyxxxxx;
        }`

My goal is to fire up OBS. Point it to my nginx rtmp server and have it automatically stream to Twitch and Owncast.
Does Owncast allow pushing to the server with just an owncast url/stream key? Am I just not passing in the correct rtmp url parameters?

**Comment by gabek** [comment]
Hi there.

You can certainly stream to Owncast using `rtmp://server/live/key`, so I'm not sure what issues you might be running into.  I've seen a handful of people using [Prism](https://github.com/muesli/prism) as a middle man to do exactly this.

What port is Owncast listening on?  I'm not really following your port descriptions since you mentioned nginx is listening on port 1935 but it also looks like Owncast is listening on 1935.

Do you see any errors?  Do you see anything connecting to the Owncast server at all?

**Comment by teklynk** [comment]
Hmm. That is good to hear. So it must be something on my end.

The nginx rtmp server is a docker container with mapped ports 9095:1935. I also have Owncast running in a docker container on the same server with mapped ports 1935:1935. I then proxy-pass my owncast domain to the container that is running owncast. I know it sounds confusing, but I have all public domains going through a reverse-proxy and then to the docker containers. It is just my way of avoiding opening up ports on my router, plus I use Cloudflare to add some firewall rules and security.  

BTW: I can stream to the Owncast server just fine using rtmp://192.168.0.40:/live/ and the stream key with OBS. I can even see my stream in the owncast directory and view the stream from my domain. So, Owncast is working great there. No port forwarding or firewall issues with the Owncast instance. 

My thinking was that If I wanted to multi-stream I would use rtmp://192.168.0.40:9095/live/ (the nginx rtmp server) and If I wanted to only stream to Owncast I would use rtmp://192.168.0.40:/live/ (the owncast server). Maybe that just wont work?

**Comment by teklynk** [comment]
I got it to work!

I changed the nginx rtmp docker server to use 9095:9095 for rtmp and update the nginx.conf to use 9095 for rtmp traffic.
My nginx config:

```
# RTMP configuration
rtmp {
    server {
        listen 9095;
        chunk_size 4095;

        application live {
            live on;
            record off;
            push rtmp://172.27.0.4/live/owncaststreamkeyxxxx;
            push rtmp://iad05.contribute.live-video.net/app/live_twitchstreamkeyxxxx;

        }

        application source {
            live on;
            record off;
        }
    }
}
```

I then set the nginx rtmp docker container to use the same network that the Owncast docker container is using. Both containers are now on the same subnet and can see/talk to each other. I think that was the main problem. Owncast is on containerr 172.27.0.4 and the nginx rtmp server is now on 172.27.0.5.

**Comment by gabek** [comment]
Awesome!  I'm going to close this unless there's anything else, but I'm glad you figured it out!
