### ISSUE TITLE
Shortcut triggers when typing p inside chat emoji search field

### ISSUE THREAD

**Issue by ma-hartma** [owncast/owncast#1228]
While using the chat's emoji search field I've discovered unexpected behaviour.

"p" is the shortcut for play/pause and it even triggers when typing inside the search input field.
Users are not able to type the letter "p" and the stream pauses/unpauses instead.

**Comment by gabek** [comment]
Fixed in https://github.com/owncast/owncast/issues/1025, but thanks for making sure knew about it!  It'll be fixed up in the next release.
