### ISSUE TITLE
The name change notification is missing a space

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1231]
Whoops.

![image](https://user-images.githubusercontent.com/414923/126429064-38e65cd1-c56c-45f5-9a34-fe9dc84d7142.png)

https://github.com/owncast/owncast/blob/develop/webroot/js/components/chat/message.js#L30

**Comment by soham4abc** [comment]
I am willing to work on this

**Comment by gabek** [comment]
Awesome, thank you!
