### ISSUE TITLE
is there a list of all possible configuration options

### ISSUE THREAD

**Issue by themancalledjakob** [owncast/owncast#1234]
Hi,

I am trying to figure out all possible configuration options, but somehow this is not very easily accessible (or I am being exceptionally stupid). Is there somewhere a complete documentation of which options there are?

Am I supposed to run it first, and then adjust the configuration via the admin page? I would prefer being able to start it immediately with the options I want. A configuration file would be ideal. And indeed at various points a `config.yaml` is referenced, but for some reason I seem to not be able to find an example file with all options. Does it exist?

I stumbled over a `config-example-full.yaml` or `config-example.yaml`  .. this would be fantastic, but I can't find a one.. It is also referenced by the example [docker-compose.yaml file.](https://github.com/owncast/owncast/blob/develop/examples/docker-compose.yaml) But... where is it?
I tried this:
```
$ git clone https://github.com/owncast/owncast
$ find owncast -iname "*config*.yaml"
```

Well, then I gave up on finding this file, or a full list of options. Other possibilities are the online documentation. But `https://owncast.online/docs/configuration/` is obviously not complete. Do I have to just install it, and configure everything via the admin page? This seems a bit awkward, I'd love to be able to just run it fully configured.

I apologize if a proper documentation is there, but I just can't find it.

**Comment by jeyemwey** [comment]
Hi, yes we have moved the configuration to be entirely inside the admin panel (except if you need to reset the password). The amount of stuff that can be configured has become so large, so we have decided to move it into the database.

> Am I supposed to run it first, and then adjust the configuration via the admin page?

Yes, that is the way to go. This allows non-technical users to not touch the server after setup, which we found beneficial. If you are keen, you can try provisioning the server [with http POST requests against the api](https://owncast.online/docs/api/).

> I stumbled over a config-example-full.yaml or config-example.yaml ..

Those are artifacts of the way we’ve done config before, but they are not supported anymore (iirc they will be [migrated to the config db](https://owncast.online/releases/owncast-0.0.6/) format but I don’t know if this code is still in there).

I hope this clears things up. If you have any more questions, just ask here or [in the Rocket.Chat](https://owncast.rocket.chat).

**Comment by gabek** [comment]
There are a handful of configuration options you can set via the command line, just run `./owncast --help` to see the various options you can provide.

**Comment by themancalledjakob** [comment]
@jeyemwey @gabek This indeed clears most things up. I'll research a bit what benefit the new config format has in contrast to a textfile, and will drop by in the chat should there be more questions. Thank you so much :)

As a summary:
- before the service is running, part of the configuration can be done with the binary. To get an overview over this, one needs to have a running version of owncast. Note: a configuration call does not start owncast itself. (`./owncast -streamkey cba321` and then again `./owncast`)
```
./owncast --help
Usage of ./owncast:
  -configFile string
    	Config file path to migrate to the new database (default "config.yaml")
  -database string
    	Path to the database file.
  -enableDebugFeatures
    	Enable additional debugging options.
  -enableVerboseLogging
    	Enable additional logging.
  -restoreDatabase string
    	Restore an Owncast database backup
  -streamkey string
    	Set your stream key/admin password
  -webserverport string
    	Force the web server to listen on a specific port
```
- once the service is running, it is possible to configure owncast completely with POST requests
- once the service is running, it is possible to configure owncast completely through the admin interface

if the complete setup has to be done before publishing the service, it would be best to configure it in a safe environment first, and then migrate the database to the production environment. Or something like that.

Then I'd close this issue, thanks!
