### ISSUE TITLE
Welcome message in the admin chat settings cannot be disabled

### ISSUE THREAD

**Issue by MFTabriz** [owncast/owncast#1236]
When the welcome message field is empty, the save button gets disabled!

![Animation](https://user-images.githubusercontent.com/39205857/126529584-957919da-a8ab-4f0c-bee1-87f8ef766a99.gif)

**Comment by gabek** [comment]
Yeah both the forbidden usernames and welcome message fields update buttons are backwards for some reason, they're showing by default and then hiding.  https://github.com/owncast/owncast/issues/1230

**Comment by MFTabriz** [comment]
@gabek I don't get the the same issue with forbidden usernames. The update button stays active even when the field is empty.
![Animation2](https://user-images.githubusercontent.com/39205857/126531593-fe1128d7-b771-4150-a2a1-cb833f00e93e.gif)
