### ISSUE TITLE
autoComplete should not move the caret to the end of the text

### ISSUE THREAD

**Issue by MFTabriz** [owncast/owncast#1248]
Currently, the username autocomplete moves the cursor to the end of the line.

![Animation3](https://user-images.githubusercontent.com/39205857/126825900-2ea4f1ae-f9aa-40e1-a60e-05806ca93f26.gif)

I think there should be a 
`setCaretPosition(this.formMessageInput.current, at + this.suggestion.length + 1);`
or something similar at the end of `autoCompleteNames()`. But I couldn't make the `setCaretPosition()` work properly.

**Comment by gabek** [comment]
Closing in favor of future rewrite. #1868
