### ISSUE TITLE
Hiding chat makes video larger than the window height

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#125]
![Untitled](https://user-images.githubusercontent.com/414923/91331955-566c7500-e780-11ea-9bab-7fbcf29a56d1.gif)

**Comment by gingervitis** [comment]
is this son your iPad?

**Comment by gabek** [comment]
Nope just in my browser, Brave.  I haven't tried other browsers.

**Comment by gabek** [comment]
@gingervitis fixed it.
