### ISSUE TITLE
Preserve the caret position after adding an emoji

### ISSUE THREAD

**Issue by MFTabriz** [owncast/owncast#1254]
The cursor moves to the ~~start~~ end of the text after adding an emoji. These images should be added next to each other.

![Animation5](https://user-images.githubusercontent.com/39205857/126866741-113eb722-a7dc-48e7-b8de-2d84245ac8ea.gif)

**Comment by gabek** [comment]
With webv2 after you add an emoji it places it in the correct place, but moves the cursor to the end of the content. Updating the issue.
