### ISSUE TITLE
Disable the chat backend when the stream is offline

### ISSUE THREAD

**Issue by MFTabriz** [owncast/owncast#1257]
![Screenshot 2021-07-25 at 16-56-03 Owncast Nightly](https://user-images.githubusercontent.com/39205857/126903605-fc4f4b04-2053-4ca8-ac24-64c2f07ae332.png)

**Comment by gabek** [comment]
I think stopping regular users from sending messages would be a good change, but allowing system messages and 3rd party tools to send things would still be nice.  For example when a stream is starting it says "Stream is starting" in the chat, and I think that's a nice touch.  So things like that I don't think should be blocked.  We can just reject incoming messages through the websocket.
