### ISSUE TITLE
Username autocomplete suggestions should not include the read-only embed chat users

### ISSUE THREAD

**Issue by MFTabriz** [owncast/owncast#1265]
These users are currently named "chat-embed-*".

**Comment by gabek** [comment]
These users being surfaced in chat are a stop gap anyway, so I wouldn't worry about it long term.  The real solution is to treat them as a different kind of user that doesn't show up in chat: https://github.com/owncast/owncast/issues/1219

**Comment by MFTabriz** [comment]
@gabek that would be really nice!
