### ISSUE TITLE
Catch null lastDisconnectTime if server was never online

### ISSUE THREAD

**Issue by jeyemwey** [owncast/owncast#1267]
## Bug Report

If the server has never delivered a stream, the calculation of `lastDisconnectTime` is invalid and produces a `nullish` value:

```json
{"lastConnectTime":null,"lastDisconnectTime":"0001-01-01T00:00:00Z", "...":"..."}
```

(From `/api/status` on a fresh install)

This will then produce bad data in the frontend:

![Screenshot of Owncast, saying "Last live: 1.1.1"](https://user-images.githubusercontent.com/2796271/127048959-04469ff9-d8bf-4e34-bfa0-5742ba9a5909.jpeg)

## Ways to solve this

1. I'd like to have the API deliver `"lastConnectTime":null,"lastDisconnectTime": null` on fresh installs. We can clearly distinguish `null` from any nullish dates that Go produces. For this, it is necessary to touch the backend.
2. Hide the "Last live:" block using JavaScript if `lastDisconnectTime` is null.

**Comment by gabek** [comment]
These are currently the case.  I've never seen "1.1.1", so I'm curious how you're getting in that state.

![image](https://user-images.githubusercontent.com/414923/127076837-e9b4da40-144c-474c-9fa8-453491866b18.png)

https://github.com/owncast/owncast/blob/develop/webroot/js/utils/helpers.js#L161-L163

![image](https://user-images.githubusercontent.com/414923/127076959-5327dd67-a9bf-4b83-ba83-12ce274fe4da.png)


<blockquote><img src="https://repository-images.githubusercontent.com/266445736/4f82fb80-a5b1-11ea-8f1c-69d316f861b5" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/owncast/owncast">owncast/helpers.js at develop · owncast/owncast</a></strong></div><div>Take control over your live stream video by running it yourself.  Streaming + chat out of the box. - owncast/helpers.js at develop · owncast/owncast</div></blockquote>

**Comment by jeyemwey** [comment]
I've seen it with https://nightly.owncast.tv/ though I don't have the db for that.

<blockquote><div><strong><a href="https://nightly.owncast.tv/">Owncast</a></strong></div></blockquote>

**Comment by gabek** [comment]
Oh that explains it.  In a previous build it saved a bad value to its database so it continues to use it.  But that was a month or so ago.

**Comment by gabek** [comment]
I went ahead and streamed something on nightly so that old value would be overwritten.

**Comment by gabek** [comment]
Please re-open if you can reproduce this.
