### ISSUE TITLE
Chat disables when stream ends instead of 5 minutes later

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1268]
When a stream ends the chat is supposed to stay alive for 5 minutes before it's shut down to allow people to say goodbye.  This no longer looks to be functioning as it once was. Now when the stream ends the chat input immediately is disabled.

**Comment by MFTabriz** [comment]
[This part](https://github.com/owncast/owncast/blob/dcc7a7c5c3a9ef8dfa7e39714f642490d712b6ed/core/chat/events.go#L84) should also be modified to keep the backend active for 5 minutes after the stream ends.
