### ISSUE TITLE
Initial chat auth UI to support IndieAuth

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1273]
@aaronpk wrote [this article](https://aaronparecki.com/2018/07/07/7/oauth-for-the-open-web) with this example login UI:

![image](https://user-images.githubusercontent.com/414923/127199513-271991d9-00d7-440d-ba7a-bcf46c37a2c1.png)

Since Owncast will support IndieAuth our UI can have some more specific verbiage specifically speaking to Owncast server admins, since that's the primary audience as most other people won't have access to IndieAuth.

See https://github.com/owncast/owncast/discussions/440#discussioncomment-532137 for the previous discussion about this topic.

Actual backend implementation is a prerequisite: https://github.com/owncast/owncast/issues/1272

**Comment by gabek** [comment]
I'm not sure I'll be able to come up with anything better than this.
![indieauth-test2](https://user-images.githubusercontent.com/414923/161143619-2258eaee-f967-4d59-af93-8ecc1896a893.gif)

**Comment by gabek** [comment]
@suzie97 referred to this mock from https://github.com/owncast/owncast/discussions/440


I do like the idea of having a consolidated place to change the name and authenticate like in the below original mock.  So I think we can use this as a starting point.  Here's the things that would need to change, though:

1. I don't think it should auto-display when focusing on the chat box.
1. We need a way to get to this modal that isn't just the first-run experience. Right now I have a little Lock icon in the upper right (lock because of authentication), but if it's also the name change it doesn't make sense for it to be a lock. So maybe it can simply be changed to a user icon.
1. IndieAuth requires a text box to type in the URL.
1. Maybe when you click the "IndieAuth" button it changes the text field above that was originally to change your name, but now allows you to put in your IndieAuth URL. And if you change your mind you can click the "Change name" button
1. Maybe the "just type in your name" could be listed as a button below as "Anonymous" auth, just so all the buttons feel like they're doing auth stuff. Saying specifically it's anonymous also might be a plus in making it clear to people they don't have to login.

Two questions I have with this idea:
1. Is it too confusing for the bottom buttons to be treated as kind of a "mode" that impacts the top half of the modal?
1. If somebody wants to set their name _and_ login they'd have to open this modal twice and that's probably not clear.

Original mock:
![image](https://user-images.githubusercontent.com/414923/162637535-7777e13a-c1a1-4954-bc21-37552f6470a7.png)

My [scribbles](https://www.figma.com/file/kQL9SM76BFIvjAwXvrdPxp/auth-modal?node-id=0%3A1) with the current use case:

![image](https://user-images.githubusercontent.com/414923/162637568-cfe39c47-bfb3-4b05-bffb-4f932ec8d043.png)

**Comment by Suzie97** [comment]
> 1. Is it too confusing for the bottom buttons to be treated as kind of a "mode" that impacts the top half of the modal?

Just sharing whatever ideas that come to my mind. 

Rather than directly showing a text field to input the username and buttons below to change the mode to login, we could display two equally important buttons - one for setting/changing the username and the other one for logging in with IndieAuth and Fediverse. After the buttons are clicked, the modal can switch to a new view dedicated to the purpose of the button i.e. if the Change Name button was clicked it would just display a text field to change the name and a confirm button but if the other one was clicked, it would display options to login.

Another way we could handle this is to use a tab based approach. We can use the same approach as mentioned above but instead of buttons, we could just display a segmented button/tab at the top.

**Quick Wireframe**
![Login Modal](https://user-images.githubusercontent.com/68198116/162639757-00fa2bc5-1d94-4ef8-a282-dfa4afd8fcb3.png)

Let me know what you think of this idea. @gabek if you approve, I could do some user testing using a similar concept with random people who might not necessarily be Owncast users.

**Comment by gabek** [comment]
Oh yeah I think all that makes more sense and is less confusing. I think the tabs have the additional benefit of being able to switch between the different options quickly if you change your mind, or you're trying to figure out what they mean by clicking on them. This also gives each option more room for information text.

In the future full redesign we could use each of these tabs as a standalone modal that's shown from a user options dropdown or something, so this is all good. Thank you!

**Comment by Suzie97** [comment]
> Oh yeah I think all that makes more sense and is less confusing. I think the tabs have the additional benefit of being able to switch between the different options quickly if you change your mind, or you're trying to figure out what they mean by clicking on them. This also gives each option more room for information text.
> 
> In the future full redesign we could use each of these tabs as a standalone modal that's shown from a user options dropdown or something, so this is all good. Thank you!

Glad to help. If you need any help figuring out the UI of the tabs, ping me :)

**Comment by gabek** [comment]
It's not pretty, but it's something. I need to find some way to explain what IndieAuth is in this modal, but it's a pretty complex topic to fit in one sentence. 

![image](https://user-images.githubusercontent.com/414923/163635934-9d5ef9c0-c25e-445d-ba48-bcf245089f9d.png)

**Comment by gabek** [comment]
Updates.

![image](https://user-images.githubusercontent.com/414923/163693179-7cf3e889-0027-492a-ba73-f7d9a5d8c9bb.png)

**Comment by Suzie97** [comment]
> Updates.
> 
> ![image](https://user-images.githubusercontent.com/414923/163693179-7cf3e889-0027-492a-ba73-f7d9a5d8c9bb.png)

I think the text makes sense and will be useful for people who want more information on IndieAuth. But it is a lot of text to throw at the user by default and makes the modal look complicated at first glance. Hiding it in some kind of learn more button seems more appropriate.

## Lo-fi Prototype
https://user-images.githubusercontent.com/68198116/163699124-a716e5a7-53c8-47a7-84ab-19a0eda077e8.mov

**Comment by gabek** [comment]
I agree with all of that!

I was thinking "I'll do it if HTML has a disclosure element, but I really don't want to build a new component for it!" and it turns out, HTML does have a disclosure element! https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details

I'm on it!

<blockquote><img src="https://developer.mozilla.org/mdn-social-share.cd6c4a5a.png" width="48" align="right"><div><strong><a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details"><details>: The Details disclosure element - HTML: HyperText Markup Language | MDN</a></strong></div><div>The <details> HTML element creates a disclosure widget in which information is visible only when the widget is toggled into an "open" state. A summary or label must be provided using the <summary> element.</div></blockquote>

**Comment by gabek** [comment]
Ugh but it sucks. I can't wait until I can use Ant components!

![image](https://user-images.githubusercontent.com/414923/163699954-45e834fb-e7e3-4f61-885a-a27df23cc1cd.png)

![image](https://user-images.githubusercontent.com/414923/163699965-667a6423-0adf-4dd2-a364-0f232a2c9518.png)

**Comment by gabek** [comment]
Ok this might work.

![image](https://user-images.githubusercontent.com/414923/163700080-cc7dd73d-1cc9-4a0d-850f-eb8f1b0ce8bb.png)
