### ISSUE TITLE
Replace redirect of /embed URLs to return content directly

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1281]
I'm not sure why I did it this way in the first place, but we should change it.

Example: Instead if redirecting `/embed/video` to `index-video-only.html` it should read `index-video-only.html` and return the content directly.  Same with the chat versions.

Some import changes may need to be made in the files since the URL for the content will be different, but this will be cleaner since it probably confuses people as to why a different file is loaded when they use an embed url.

**Comment by krashanoff** [comment]
I might be interested in tackling this. Is there anyone on it as of now?

**Comment by gabek** [comment]
Nope, nobody!  Let me know if you have any questions.
