### ISSUE TITLE
Support png logo fallback if a svg is provided

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1286]
Many 3rd party services can't render SVGs, so if we think a SVG is being used as a logo within Owncast we should fallback to a png version of the generic Owncast logo and throw a log message explaining they may want to use a png instead.

This would only be used when sharing via the `metadata.html` or ActivityPub.  A new `/logo/compatible` endpoint+controller can be created and used instead of `/logo` for these cases.

**Comment by MFTabriz** [comment]
Should we automatically convert the svg to png and use it instead?

**Comment by gabek** [comment]
I thought about that, but the amount of extra junk we'd have to add to the project to do that in a reliable way isn't worth it.  Anything that's Go-only doesn't have full compatibility for all of SVG features.  I thought about maybe utilizing ffmpeg since we already have access to it, but it would require users to specifically have `librsvg` compiled in, not something that's guaranteed.  It's possible we should just not support SVGs at all, but it's unfortunate to reduce functionality because of other services when SVGs look just fine within Owncast itself and it's our current default logo image.
