### ISSUE TITLE
Frontend to allow people to perform moderation actions within chat

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1291]
Part 2 of https://github.com/owncast/owncast/issues/499

- The backend will support telling a specific user they're now a moderator via the `CONNECTED_USER_INFO` event.
- This should allow a new UI control to show up within chat messages to enable them to remove messages or remove the user.

**Comment by gingervitis** [comment]
Will the `user` object in a `message` indicate if that user is a moderator ?
