### ISSUE TITLE
Relay RSS into Rocket.Chat

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1294]
It was [suggested in a previous call](https://collab.owncast.tv/code/#/2/code/view/Mhf7jsNaPvMQLLXcS4jn7qCK0b05HoxTjKWDN7Flg3w/) we relay the posts from https://owncast.online/news/index.json to post in Rocket.Chat.

**Comment by jeyemwey** [comment]
I've created a bot for this, it will only need to be deployed now where @gabek comes to play.

**Comment by gabek** [comment]
Awesome!  One tweak, though, instead of running and exiting, could you make it stay running and fire every X minutes on a timer?  By default if it fires and exits, and would get immediately restarted.

**Comment by jeyemwey** [comment]
Finally found the time to do it: https://github.com/owncast/owncast-feed-forwarder/commit/3d6577d56720f750f4d40f873ecc734add2606e0

You can specify the `REFRESH_INTERVAL` env variable to load the data every `n` seconds.

**Comment by gabek** [comment]
Deployed!
