### ISSUE TITLE
0.0.8, Chat broken when behind a password protected stream (Apache)

### ISSUE THREAD

**Issue by andrewfer000** [owncast/owncast#1300]
Hi,

Just decided to upgrade to 0.0.8 today, seems that everything works great however on my private stream that uses Apache's htaccess system seems to have issues with chat. What happens is when the site loads and I log in I get assigned a username and chat appears for a second then it flashes, slows the site down, and crashes after a while. 

I do not use the chat on my private stream however this may be used by others so I'd thought I'd put it out there.

**Comment by gabek** [comment]
Hey there, thanks for letting us know.  Could you add some more detail about what "crashes" and "slows the site down" specifically means in your case?

What errors do you see in your browser console?  Is there anything in your Apache config that might be removing or overriding the access token being provided to chat?

**Comment by andrewfer000** [comment]
Okay, Let's get started.
1. Owncast-Private.conf for Apache. Just the auth part. (x is used to omit private detail). This is all that is modified from the sample in the documentation.
``` 
       <Proxy *>
        #Authencation
          AuthType Basic
          AuthName "Password Required"
          AuthUserFile  /var/xxx/xxx/xxx/.htpasswd
          Require valid-user
        #End Authencation
          Order deny,allow
          Allow from all
        </Proxy>
```
2. Browser Log outputs this message repeatedly (using mydomain.tld for privacy reasons. I would of got more but the page slowed down to the point of being unusable.
```
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
    onMessage https://privatelive.mydomain.tld/js/utils/websocket.js:161
    createAndConnect https://privatelive.mydomain.tld/js/utils/websocket.js:56
    Websocket https://privatelive.mydomain.tld/js/utils/websocket.js:45
    setupChatAuth https://privatelive.mydomain.tld/js/app.js:584
    handleWebsocketMessage https://privatelive.mydomain.tld/js/app.js:532
    notifyRawMessageListeners https://privatelive.mydomain.tld/js/utils/websocket.js:110
    notifyRawMessageListeners https://privatelive.mydomain.tld/js/utils/websocket.js:109
    onMessage https://privatelive.mydomain.tld/js/utils/websocket.js:179
    createAndConnect https://privatelive.mydomain.tld/js/utils/websocket.js:56
    Websocket https://privatelive.mydomain.tld/js/utils/websocket.js:45
    setupChatAuth https://privatelive.mydomain.tld/js/app.js:584
    setConfigData https://privatelive.mydomain.tld/js/app.js:225
    getConfig https://privatelive.mydomain.tld/js/app.js:186
    promise callback*getConfig https://privatelive.mydomain.tld/js/app.js:185
    componentDidMount https://privatelive.mydomain.tld/js/app.js:140
    Preact 4
    <anonymous> https://privatelive.mydomain.tld/:93
 undefined websocket.js:163:17
    onMessage https://privatelive.mydomain.tld/js/utils/websocket.js:163
    createAndConnect https://privatelive.mydomain.tld/js/utils/websocket.js:56
    Websocket https://privatelive.mydomain.tld/js/utils/websocket.js:45
    setupChatAuth https://privatelive.mydomain.tld/js/app.js:584
    handleWebsocketMessage https://privatelive.mydomain.tld/js/app.js:532
    notifyRawMessageListeners https://privatelive.mydomain.tld/js/utils/websocket.js:110
    notifyRawMessageListeners https://privatelive.mydomain.tld/js/utils/websocket.js:109
    onMessage https://privatelive.mydomain.tld/js/utils/websocket.js:179
    createAndConnect https://privatelive.mydomain.tld/js/utils/websocket.js:56
    Websocket https://privatelive.mydomain.tld/js/utils/websocket.js:45
    setupChatAuth https://privatelive.mydomain.tld/js/app.js:584
    setConfigData https://privatelive.mydomain.tld/js/app.js:225
    getConfig https://privatelive.mydomain.tld/js/app.js:186
    (Async: promise callback)
    getConfig https://privatelive.mydomain.tld/js/app.js:185
    componentDidMount https://privatelive.mydomain.tld/js/app.js:140
    Preact 4
    <anonymous> https://privatelive.mydomain.tld/:93
``` 
As well as
```
Chat has been disconnected and is likely not working for you. It's possible you were removed from chat. If this is a server configuration issue, visit troubleshooting steps to resolve. https://owncast.online/docs/troubleshooting/#chat-is-disabled: Websocket closed. websocket.js:190:13
    handleNetworkingError https://privatelive.mydomain.tld/js/utils/websocket.js:190
    onClose https://privatelive.mydomain.tld/js/utils/websocket.js:128
    createAndConnect https://privatelive.mydomain.tld/js/utils/websocket.js:54
    Websocket https://privatelive.mydomain.tld/js/utils/websocket.js:45
    setupChatAuth https://privatelive.mydomain.tld/js/app.js:584
    setConfigData https://privatelive.mydomain.tld/js/app.js:225
    getConfig https://privatelive.mydomain.tld/js/app.js:186
    (Async: promise callback)
    getConfig https://privatelive.mydomain.tld/js/app.js:185
    componentDidMount https://privatelive.mydomain.tld/js/app.js:140
    Preact 4
    <anonymous> https://privatelive.mydomain.tld/:93
```
3. IN ADMIN
No usernames show up in the user section of the panel. If I somehow manage to send a message, nothing appears in Admin.


4. Tested on
Firefox on Linux, Firefox on Android, Google Chrome on Android.

**Comment by gabek** [comment]
Just curious, did chat ever work for you?  Is Apache proxying the websocket properly?  https://owncast.online/docs/sslproxies/apache/

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="/favicon.png" height="14"> Owncast</div><div><strong><a href="/docs/sslproxies/apache/">Apache</a></strong></div><div>If you're already using Apache you can use it as a proxy.</div></blockquote>

**Comment by andrewfer000** [comment]
> Just curious, did chat ever work for you?  Is Apache proxying the websocket properly?  https://owncast.online/docs/sslproxies/apache/
> 
> <blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="/favicon.png" height="14"> Owncast</div><div><strong><a href="/docs/sslproxies/apache/">Apache</a></strong></div><div>If you're already using Apache you can use it as a proxy.</div></blockquote>

yes. It worked fine on 0.0.7 and works fine on non-password 0.0.8.

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="/favicon.png" height="14"> Owncast</div><div><strong><a href="/docs/sslproxies/apache/">Apache</a></strong></div><div>If you're already using Apache you can use it as a proxy.</div></blockquote>

**Comment by gabek** [comment]
Thank you for providing that log.  Could you also open up the browser developer tools under the "Network" tab and inspect some of the traffic that's having problems?  You should be able to see the status codes and the payloads.  I'm most curious about the websocket connection and any `/api/chat` requests.  Sorry to be so vague, but I'm not exactly sure what's failing and how from the log, but it's clear something is failing, forcing it to retry.  So if you can help track down the actual failing calls, and the payloads in there that'd be a huge help.

**Comment by andrewfer000** [comment]
I don't see anything for /api/chat but there is a lot of 101 status codes popping up. On my public 0.0.8 instance, only one 101 status code appears. So it seems the web socket is not getting upgraded properly and it keeps trying to do it over and over again.
 
Here is the websocket that keeps trying:
`wss://privatelive.mysite.tld/ws?accessToken=vtGd1aqqXXxxxXWr5LxxXNgFiVxxxxVBSnpy1goiNI%3D` (Some Xx thrown in there for security!)

**Comment by nebunez** [comment]
I am using the exact Apache config for ProxyPass port-forwarding, but I am not using any auth. I would like to test this auth setup this weekend. @andrewfer000 can you please provide an example of the .htpasswd file I would use with this, so I can make sure I'm replicating your setup?

**Comment by andrewfer000** [comment]
Before all, run this command to get the tools on Ubuntu/Debian
`sudo apt-get install apache2 apache2-utils`

0. Make a directory to store the htaccess file

`mkdir -p /etc/apache2/passwords/owncast-private`

1. First, Create a htaccess file and make admin the first user by running the below command. Make the admin password your stream key or else the admin panel won't work. Like all Linux passwords, you won't see it when you enter it. Enter it twice. (aka copy-paste out of OBS)

`sudo htpasswd -c /etc/apache2/passwords/owncast-private/.htpasswd admin`

2. Second, Create an account for a viewer user. Set the password to whatever you want.
`sudo htpasswd /etc/apache2/passwords/owncast-private/.htpasswd viewer`

3. Thrid, Edit your owncast reverse-proxy config by going to the `<proxy>` section and adding the below contents above the ` Order deny,allow` line. Not sure if it makes a diffrence if this is put above or below just as long as it's in the `<proxy>` section.
```
        #Authencation
          AuthType Basic
          AuthName "Password Required"
          AuthUserFile  /etc/apache2/passwords/owncast-private/.htpasswd
          Require valid-user
        #End Authencation
```

4. Fourth, Set the permissions so Apache can read the password file by running. Replace www-data with the webserver user your distro uses. If you do this wrong you will get http 500 errors. If that's the case check your apache logs for more details.
` chmod -r www-data:www-data /etc/apache2/passwords/`

5. Lastly, restart apache2 and test.
`systemctl restart apache2`

**Comment by gabek** [comment]
@nebunez Tried to reproduce this using his Apache setup. A bunch of us tuned in, being greeted by HTTP Basic auth, and forced to login.  Unfortunately, none of us experienced any issues.  We were able to login and chat without issue.

So I'm not sure where to go from here. Something very specific to your configuration must be impacting something.  Sorry we don't have the answers, as I'm sure this is frustrating.

**Comment by andrewfer000** [comment]
Interesting. This is actually a good thing because it means we don't have to fix anything in Owncast itself. It might just be caused by my browsers so let me clear my data and I'll give you guys an update. Hopefully it works and we can close this issue.

**Comment by andrewfer000** [comment]
Okay I fixed it. Turns out it was my apache file! I forgot to set the correct port for `RewriteRule` so it was pointing to the wrong Owncast server! 

In conclusion, it's not a bug. It was an Apache configuration issue. I will now close this! Thanks for your time.

**Comment by gabek** [comment]
Great news!  Thanks for looking into it and reporting back!
