### ISSUE TITLE
Implement Prometheus compatible metrics endpoint

### ISSUE THREAD

**Issue by unclearParadigm** [owncast/owncast#1303]
Hello,

[Prometheus](https://prometheus.io/) is an [open-source](https://github.com/prometheus/prometheus) Apache 2.0 licensed [federated](https://prometheus.io/docs/prometheus/latest/federation/) time-series database, which crawls its metrics by HTTP requesting endpoints on applications that expose metrics. Prometheus is a pull-based alternative to InfluxDB and is commonly used in Server/Application Health- & Performance Monitoring scenarios - especially in combination with [Grafana](https://grafana.com/), which is a Frontend for various time-series sources where one create fancy dashboards and most importantly Alerting.

Usually you configure Prometheus to poll your metrics endpoint in a given interval. So the metrics endpoint does not need to return historical data like `/api/admin/viewersOverTime` does. Just the status quo (current) values are sufficient. Prometheus builds the time-series internally itself then.

Prometheus does HTTP requests on a preconfigured endpoint in a preconfigured interval. The response needs to be formatted according to the Prometheus documentation. Here's an example:
```
viewer_count{target_hostname="localhost", target_domain="live.owncast.com", owncast_version="0.0.8"} 3
cpu_usage_in_percent{target_hostname="localhost", target_domain="live.owncast.com", owncast_version="0.0.8"} 42
ram_usage_in_mb{target_hostname="localhost", target_domain="live.owncast.com", owncast_version="0.0.8"} 1024
total_chat_messages{target_hostname="localhost", target_domain="live.owncast.com", owncast_version="0.0.8"} 14
current_users_in_chat 3
```
Prometheus also provides libraries for Go that helps building metrics in this format [prometheus_client GO](https://pkg.go.dev/github.com/prometheus/client_golang).

## Benefits

* Owncast performance is monitorable from external applications
* Owncast usage (e.g. users, chat messages, etc ...) is monitorable from external applications
* Prometheus is very little invasive to implement - just add another HTTP endpoint that spits out these metrics
* Alerting on Resource-Limits can be created, (e.g. in Grafana or in Prometheus Alert Manager) that rigger further actions (e.g. assign docker container more disk space, RAM, ease resoure limits, etc. ....)
* Give users the possibility to get even more insights into the metrics of Owncast over longer periods
* Prometheus is easy to implement, but it's opening compatibility to all major APMs and time-series databases (e.g. through telegraf)

## Security

Metrics most likely should not be available publicly for everyone. The Endpoint most likely should be authenticated. Prometheus does support [HTTP basic authenticated] metrics-requests as well.

**Comment by gabek** [comment]
There's some previous discussion about Prometheus over at https://github.com/owncast/owncast/discussions/128 that you might want to add your thoughts to.  There's never been a clear consensus to "what is the problem" and "what is the solution" so it's never gone anywhere.

**Comment by unclearParadigm** [comment]
To my understanding, it feels like the discussion in #128 focuses more on writing a plugin architecture rather than actually writing the API providing the metrics to third-party applications. I'm not quite sure if I can implement a full-fledged plugin system into a relatively new codebase (at least for me), with Go (which is also not a "fluent" lang for me) and a Pluginsystem with tons of pitfalls (see the comments in #128)  in a "timely" manner. This'd require a ton of knowledge in Go, Go Plugins, a decent analysis on the security impact and lots of guidance from you (@gabek and other core-developers). If that's what you're aiming for, and that's the way you want the Metrics API for Prometheus to be implemented I'd love to give it a try - though I'd probably need you on a call for ~~one~~ a few hours or so, just to "set the frame".

What I had mind when writing this Story/Featurerequest was more or less a very "dumb" controller, behind a HTTP Basic Auth middleware, that just responds with metrics on a HTTP GET. 

What I really wanted to make sure, if there's even a need for this feature exists for other maintainers of Owncast instances as well. That last thing I'd want to happen is that I'm the only one utilizing this, and at some point it'd just end up as unsupported "dead code" in the repo. I personally run a full-fledged Prom/Grafana/Loki stack and love the piece of mind having everything in regards of Server- & Servicemonitoring + Alerting.

Would be happy to hear your thoughts on how this can/should be done. I'll give it a try either way.

**Comment by gabek** [comment]
I think in general we've given up on the true plugin idea, just because there was no obvious way to pull it off.

And as for metrics collection, my concern was always, sure we could add Prometheus directly to Owncast, but then somebody would want another format, and then somebody else would want a third, so once we add one we'd have to continue adding direct support for others.  So that's why the discussion of plugins came about, where if people wanted to add support then they could add it without us adding 5 different metrics collection APIs directly into the core codebase.  But I think that plugin thing isn't going to work.

So that doesn't really answer your question, but it's just where things have landed.  I'm not sure if you plan on joining the call on Thursday, but maybe we can discuss it as a group there.

**Comment by unclearParadigm** [comment]
I understand your concerns and I fully agree on your standpoint. 

On the other hand, one could argue to implement Prometheus, for the sake of having an "easy-to-implement-and-maintain"-solution (let's be honest, it won't get easier than adding an HTTP endpoint) and then point users, that require different formats, to tools like [Telegraf](https://www.influxdata.com/time-series-platform/telegraf/). Telegraf for example does exactly that, it takes various forms of formats as input(s), and converts/batches/maps them to the desired output format. It is basically the swiss-army-knife of metrics collection, processing, conversion. So if some owncast users need push-based InfluxDb-compatible metrics, guide 'em Telegraf. That's the only argument I can come up with in defense of Prometheus. Still, I fully understand your standpoint!

Sadly I couldn't join last week. I haven't found it on the Cryptpad as discussion point yet, so I assume it wasn't discussed. I'd be happy if I could join the next public Owncast call then. Maybe we'll find consensus.

**Comment by gabek** [comment]
Yeah I figured if you happened to be around we could spend some time clarifying what we want and how, but maybe next time!

**Comment by gabek** [comment]
@unclearParadigm Still interested in giving this a go?  After the conversation in #1478 it makes sense to do this by supporting Prometheus than building an a fuller-featured internal metrics platform.

**Comment by unclearParadigm** [comment]
@gabek: Absolutely, I'd love to! Though, I can't really give you a ETA for completion yet. Quite a lot going on over here at the moment. But I'm going to tackle it!
