### ISSUE TITLE
GeoLite city database not working with 0.0.8

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1304]
From chat:

> First, thanks everyone for the hard work to get 0.0.8 released!!! Anyone else having issues with 0.0.8 and the GeoLite city database pulling in location info to the admin users list? i've chowned it to the owncast user and root but neither seems to work. Thanks!

**Comment by jeyemwey** [comment]
I wonder if we can catch this kind of errors with automated testing (in the unit testing section) or manual testing (before a release).

**Comment by gabek** [comment]
Yes we can.
