### ISSUE TITLE
Web assets (JS & CSS) are read from cache after updates

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#131]
Not that caching is bad, when larger web updates get pushed things can go badly if things aren't in sync.

Bundlers deal with this by changing the file name.  Since we're not bundling we need to find an alternative.  Anybody know the current best practices for dealing with this?

**Comment by jeyemwey** [comment]
Go's `net/http` "ServeFile" method looks out for filechanges automatically and returns Cache-Headers accordingly. However, the changed "Last-Modified:" header is only transmitted if the browser does a request. You can try to trigger browser requests by adding `Expires: n` for all requests and responding `304 Not Modified` with an empty body. (mostly taken from [this reddit discussion](https://www.reddit.com/r/golang/comments/6p9moz/help_with_httpfileserver_and_stale_assets/))

**Comment by gabek** [comment]
Interesting!  Sounds like there's no completely straightforward answer.  Maybe we can just set a cache expiration of like a day or something as a middle ground for now.
