### ISSUE TITLE
Create external API to enable sending a message directly to a client instead of publicly

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1316]
An example is a bota sending welcome messages as somebody joins.  See https://github.com/owncast/owncast-examples/pull/1 for some use cases.

**Comment by gabek** [comment]
I originally said send message to a _user_ but the more correct implementation in this case would be to send to a single _client_.

Each client connection already has a client ID: https://github.com/owncast/owncast/blob/develop/core/chat/server.go#L26

So if we sent this client ID along with the `USER_JOINED` webhook event we could create a new API of `/api/integrations/chat/system/client/CLIENTID` and simply look up that client using the ID in the above map. Then use the existing `sendSystemMessageToClient` https://github.com/owncast/owncast/blob/develop/core/chat/server.go#L306-L315 to pass the message along.

If we wanted something other than system message support (like user message support in `/api/integrations/chat/send`) we could create a new `sendUserMessageToClient` or something instead and use that.

<blockquote><img src="https://repository-images.githubusercontent.com/266445736/4f82fb80-a5b1-11ea-8f1c-69d316f861b5" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/owncast/owncast">owncast/server.go at develop · owncast/owncast</a></strong></div><div>Take control over your live stream video by running it yourself.  Streaming + chat out of the box. - owncast/server.go at develop · owncast/owncast</div></blockquote>
<blockquote><img src="https://repository-images.githubusercontent.com/266445736/4f82fb80-a5b1-11ea-8f1c-69d316f861b5" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/owncast/owncast">owncast/server.go at develop · owncast/owncast</a></strong></div><div>Take control over your live stream video by running it yourself.  Streaming + chat out of the box. - owncast/server.go at develop · owncast/owncast</div></blockquote>

**Comment by unclearParadigm** [comment]
Awesome. Thank you for writing down your thoughts and explaining the high-level API design more in detail! I'd really love to tackle this!

**Comment by gabek** [comment]
All yours! :100:

**Comment by unclearParadigm** [comment]
Heyho

after a long time, I finally managed to get my stuff together and work on this.

Here are the PRs to resolve this issue:
* [Documentation PR](https://github.com/owncast/owncast.github.io/pull/56)
* [Owncast Demo Bot PR](https://github.com/owncast/owncast-examples/pull/2)
* [Owncast PR](https://github.com/owncast/owncast/pull/1351)

Please review these if you have a few minutes left. If you want anything changed, hit me up -> I'll patch it up right away.

Cheers,
Ruffy
