### ISSUE TITLE
Chromecast support

### ISSUE THREAD

**Issue by Vittelius** [owncast/owncast#1318]
It would be nice to have some sort of smart TV support. The easiest way to support a wide range of devices would be to support google cast. 

Afaik casting works only with encrypted sites so it would have to be an optional feature.

![mockup_owncast1](https://user-images.githubusercontent.com/3718818/129454864-c2a44d2f-1769-42b0-aad2-a5e15037547c.png)

![mockup_owncast2](https://user-images.githubusercontent.com/3718818/129454828-e6961480-b948-458d-bb9c-2e65f32404db.png)

**Comment by gabek** [comment]
There had been some discussion previously at https://github.com/owncast/owncast/issues/410, but I think the idea of adding Google's Chromecast library to Owncast is a bit of a deal breaker.

**Comment by gabek** [comment]
However, we do support AirPlay directly from the player without any 3rd party libraries.

**Comment by gabek** [comment]
Hi there!  Tracking this over at https://github.com/owncast/owncast/issues/410, so I'll close this issue in favor of that one.  Thanks!
