### ISSUE TITLE
Directory hero player won't autoplay on Firefox for Nebunez, but working for others

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1322]
@nebunez has got it to work previously, however.

**Comment by gingervitis** [comment]
It autoplayed for me on my FF, Mac version `90.0.2`

**Comment by gingervitis** [comment]
Though I wonder if this quickly incrementing warning might be related?


<img width="757" alt="image" src="https://user-images.githubusercontent.com/9563255/129506845-af87f07d-de7e-4648-9cc5-af6c9b71760b.png">

**Comment by gabek** [comment]
I just tested and auto-play works for me on Firefox + Linux as well.  So it seems like it's only not working for @nebunez?

**Comment by nebunez** [comment]
It seems that some addons cause warnings/errors in console, which may be preventing stream from playing. On an alternate profile, without as many addons, the stream will autoplay. This seems to be a user configuration error.
