### ISSUE TITLE
Improve chat scrolling

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1324]
In some cases a new message will get rendered, but the chat will not auto-scroll to the bottom.

I _think_ what is happening is any message that is heavily asynchronously rendered, meaning it's a message that has a lot of formatting via markdown, or images, the auto-scroll logic is only scrolling far enough for the initial, unrendered, content to be taken into account.  Once the image loads or the markdown renders, the scroll has already taken place, and therefore the message is larger than the logic took into account and it gets hidden.

![image](https://user-images.githubusercontent.com/414923/129496957-43334701-3bec-49f0-9382-614c162cfd23.png)

**Comment by MFTabriz** [comment]
a related issue:  #739

**Comment by gabek** [comment]
Can we create a hook to tie into changes of the chat's height, so when it changes we can scroll to the bottom instead of our current method of scrolling after a new message comes in?  @gingervitis

**Comment by gingervitis** [comment]
Sorry I don't have computer access for the weekend, but if I recall we actually do have some sort of "hook" that detects when there are changes in the chat div's height or contents.. but maybe the current method is the wrong approach or maybe we need to add a sort of check to see if the async formatting is done yet, before checking chat height.

**Comment by gingervitis** [comment]
> Sorry I don't have computer access for the weekend, but if I recall we actually do have some sort of "hook" that detects when there are changes in the chat div's height or contents.. but maybe the current method is the wrong approach or maybe we need to add a sort of check to see if the async formatting is done yet, before checking chat height.

Try looking for "mutation observer" code in components/chat/chat.js, which handles the height checking

**Comment by gabek** [comment]
This is still an issue with images.

1. Message comes in.
2. Chat scrolls to the bottom.
3. Image asynchronously loads, changing the size of the message.
4. Chat doesn't move, leaving the message cut off.

I _think_ what is happening here is when the image loads, the chat viewport is scrolled so far away from the bottom at that point that the logic to "not auto-scroll if you are scrolled x from the bottom" kicks in.  I previously improved this by increasing that value, and we could continue to increase it, but that would start to auto-scroll to the bottom when people are scrolling through the chat backlog.

Maybe a bit more logic is needed.  While we don't want to auto-scroll to the bottom if you're scrolled up **and** a new message comes in, if you're "scrolled up" **and** the viewport changes **without** a new message coming in, then it should auto-scroll.

![image](https://user-images.githubusercontent.com/414923/146091323-bf20807f-1483-46d2-b078-e93880fb6730.png)

**Comment by gabek** [comment]
Closing in favor of the future rewrite.
