### ISSUE TITLE
Support on OpenBSD

### ISSUE THREAD

**Issue by Pythone** [owncast/owncast#1327]
This should be ported to openbsd

**Comment by gabek** [comment]
Hey there.  What about Owncast isn't compatible with OpenBSD currently?  If there's something specific we can fix up, I'd love to hear it!

**Comment by gabek** [comment]
I went ahead and added automated tests for FreeBSD and OpenBSD so we can keep tabs on any issues with the source building on those platforms.  If there's anything specific that Owncast is having issues with on OpenBSD please let me know.

**Comment by Pythone** [comment]
thanks
