### ISSUE TITLE
"Disable chat" setting is confusing

### ISSUE THREAD

**Issue by aaronpk** [owncast/owncast#1330]
It's kind of confusing having the chat enabled setting be opposite of the toggle like this:

![image](https://user-images.githubusercontent.com/113001/129647357-73a9c57b-e15f-4aa1-ab51-ad16ffe477c2.png)

![image](https://user-images.githubusercontent.com/113001/129647321-554dc587-5d60-405f-8099-0a3da919b260.png)

It would be clearer if the setting were "Enable chat" and the default were "On". That way the "on" state of the toggle switch matches when the chat is visible.

**Comment by MFTabriz** [comment]
It would be simpler to call it just "chat" with a simple on-off button.
