### ISSUE TITLE
Make it clearer what your chat name is and how to change it

### ISSUE THREAD

**Issue by aral** [owncast/owncast#1339]
![Screenshot from 2021-08-19 14-01-31@2x](https://user-images.githubusercontent.com/41798/130072926-34c2fa13-d4fe-4c7a-a8fd-8bce69ee3dbb.png)

I love that we’re not using “user” any more but perhaps the interface could use some text for newcomers to explain what it is they’re seeing? :)

e.g., “You’re now known as thirsty-link” or even if the chat icon and the handle were visually grouped, it would be clearer what it pertains to (they are close but the chat area has a different colour and the chat handle falls outside of that).

**Comment by gabek** [comment]
It's a little less obvious when chat isn't active like this example.  But if you were streaming, and chat was active, you'd see `thirsty-link has joined the chat`, making it slightly clearer that you just joined, and that's your name, and it's the same name in the upper right.  But given how many people don't understand how to change their name in general, it seems we might have to do better.

**Comment by gabek** [comment]
For reference, here's something that was briefly discussed before but didn't go anywhere.  https://github.com/owncast/owncast/issues/215

**Comment by hollunder** [comment]
Hatnix added a message to work around this issue but it is obviously a kludge.
![edit_name](https://user-images.githubusercontent.com/8207622/143507807-853b3cec-bda1-4994-869e-5fd50bb78b34.png)

We threw around a couple of ideas of what could be done to make it more obvious that this is the user name and that it can be edited by clicking there.

Ideas that came up, in about the order they came up in:
 - Add "Edit name here ->" to the stream title.
 - Add an icon, a gear or a pen, next to the user name.
 - Make it into a button containing the user name.
 - Make it into a text field containing the user name.

Do you think any of those ideas are a feasible solution?

This seems to be the most relevant piece of code: https://github.com/owncast/owncast/blob/cae02f09022d18c57b45c5859605b526c6c1bb3a/webroot/js/app.js#L771

**Comment by gabek** [comment]
0.0.11 will release with a couple small tweaks to hopefully help in the short term.

- Changed the color of the text to white so it stands out, hopefully catching people's attention more.
- Added a user icon next to it to provide a hint to the user that that it is linked to your user.

#1648, a longer term fix, is a larger initiative that will be worked on with a revamp of the web interface.

**Comment by gabek** [comment]
0.0.12 has a chat dropdown menu in #1648 that includes a "change name" option. This should make it much easier for people to know what's going on and change their name.
