### ISSUE TITLE
owncast(using nvenc) seems not compatible with OBS's auto configuration wizard

### ISSUE THREAD

**Issue by Resend1298** [owncast/owncast#1344]
Well, I'm pretty sure that's not owncast's fault. However, maybe add a hint in docs or admin panel will prevent someone to keep thinking where they do wrong for not being able to use nvenc.
To be clear, streaming with owncast using nvenc works fine, only OBS's wizard has the problem. Also, OBS's wizard with owncast using libx264 works fine.
I got logs such as
`Frame Dimension less than the minimum supported value`
`your copy of ffmpeg may not support your selected codec of h264_nvenc`
`Error while opening encoder for output stream`
All in all, thank you guys for making this amazing product.

**Comment by gabek** [comment]
Hey there!

Just to clarify, streaming works fine, even with OBS using nvenc, but the only time it doesn't work is using the OBS wizard?  Just want to make sure I'm understanding correctly.

Thanks for chiming in!

**Comment by Resend1298** [comment]
Yes, I think you understand it correctly. Nvenc and libx264 I mentioned above are what owncast is using, what encoder obs is using doesn't matter.
When using obs's wizard, obs seems to stream a test video in order to test network between obs and the stream server. And it seems that ffmpeg can't handle this test video using nvenc. At this time, obs gets stucked so it can't finish auto configuration for you. However, if you 
1. Let owncast use libx264, run obs's wizard and then reset owncast to use nvenc
or
2. Keep owncast to use nvenc but you'll have to configure obs manually

than it all works fine.
