### ISSUE TITLE
More options for bans and anti-spam filtering

### ISSUE THREAD

**Issue by closewall** [owncast/owncast#1348]
I just finished a 7 hour stream, and for the first time I had to deal with a very obnoxious spammer who was at it for 5 hours. I noticed Owncast just included support for bans in the latest update to the container, which was good timing for me, but it's still not enough. Every time I banned this guy, he just came back within 30 seconds and started spamming again.

To make things worse, every time he started spamming his long message, the chat autoscroll stopped working, so at times it was actually difficult to tell when the spam was occurring. Sometimes it felt like the chat felt silent, and I think "what's going on", then I scroll down the chat and realize there has been a heap of fast spam, which broke the autoscrolling.

Some suggestions:

- Add user roles. I'm sure this had been requested before and may be on the roadmap, but as things currently stand, all users are temporary and can never have roles. All moderation has to be handled by the streamer through the admin panel. I wouldn't mind having moderators to help combat annoyances.
- I'd like the ability to ban from the main page (IE- the stream page). It's a pain to have to go to the admin panel every time I want to ban someone.
- Extending from the previous suggestion, I'd like to be able to delete posts easily from the main page. As of now, the only way to delete posts is by going to the admin panel > chat&users > messages. It doesn't delete them either, it just hides them. This is troublesome because banning users doesn't always delete all their messages, and having users refresh their page is the only way to clear it.
- Have some kind of spam filter that prevents the same 20+ character message from being posted more than 3 times every 2 seconds. Have it result in an autoban or an automute.
- Have some kind of word or phrase filter. There is currently a username filter, but I would like to have one to filter out spammer phrases, which if posted, result in an autoban.

Some additional notes:

- As outlined in the second paragraph, there is some kind of bug that causes autoscroll to stop working. I'm not sure if it's because of long messages or 5+ messages spammed in a second.
- Even though bans are meant to purge all messages from a user, some are often left over, and cannot be deleted(hidden), and the only way to stop them from appearing is by refreshing the page. This is is a user-end issue too, the only thing I can do as the admin is ask users to refresh to remove the banned user's posts on their end.

**Comment by gabek** [comment]
> every time he started spamming his long message, the chat autoscroll stopped working

We're tracking this issue in: https://github.com/owncast/owncast/issues/1324

> Add user roles. I'm sure this had been requested before and may be on the roadmap, but as things currently stand, all users are temporary and can never have roles. All moderation has to be handled by the streamer through the admin panel. I wouldn't mind having moderators to help combat annoyances.

Users seem like they're temporary, but they're actually not, and in the future we'll be adding the support to give these users moderation access. https://github.com/owncast/owncast/issues/499

> * I'd like the ability to ban from the main page (IE- the stream page). It's a pain to have to go to the admin panel every time I want to ban someone.
>  I'd like to be able to delete posts easily from the main page.

Adding functionality to the UI to support moderation is being worked on at https://github.com/owncast/owncast/issues/1291

> * Have some kind of spam filter that prevents the same 20+ character message from being posted more than 3 times every 2 seconds. Have it result in an autoban or an automute.

> * Have some kind of word or phrase filter. There is currently a username filter, but I would like to have one to filter out spammer phrases, which if posted, result in an autoban.

I just added an issue to increase the sensitivity of our rate limiter. https://github.com/owncast/owncast/issues/1349 with a time out period if it fires.  However, I don't think an autoban is a good idea as a core feature.  I think a ban should be an explicit action.

> * Even though bans are meant to purge all messages from a user, some are often left over, and cannot be deleted(hidden), and the only way to stop them from appearing is by refreshing the page. This is is a user-end issue too, the only thing I can do as the admin is ask users to refresh to remove the banned user's posts on their end.

I just filed https://github.com/owncast/owncast/issues/1350 to look into this.

**Comment by gabek** [comment]
Just increased the sensitivity of our rate limiter and added a "timeout" in https://github.com/owncast/owncast/issues/1349.

**Comment by gabek** [comment]
I'm going to close this in favor of tracking all the individual items independently in the issues above.
