### ISSUE TITLE
Potential security problem(s)

### ISSUE THREAD

**Issue by intrigus-lgtm** [owncast/owncast#1357]
Hi, could you please create a new [draft security advisory](https://help.github.com/en/github/managing-security-vulnerabilities/creating-a-security-advisory) and 
[invite me](https://help.github.com/en/github/managing-security-vulnerabilities/adding-a-collaborator-to-a-security-advisory) to it?
Any other private communication channel would also be fine.
I think I've found a potential (minor) security problem.

**Comment by gabek** [comment]
Could you share with me what the issue is first?  Feel free to email me: gabek@real-ity.com

**Comment by intrigus-lgtm** [comment]
I've sent you a mail.

**Comment by gabek** [comment]
Closed in https://github.com/owncast/owncast/commit/7278ce8f26a88399bf73f9f331cfafb90e296271
