### ISSUE TITLE
Integrate vdo.ninja in the workflow

### ISSUE THREAD

**Issue by nicopace** [owncast/owncast#1359]
Many of the streamings tend to be debates in between people.
[vdo.ninja](https://github.com/steveseguin/vdo.ninja) simplify how to bring people to your stream.
It would be worth checking out a possible integration, that would basically mean include the webrtc stream in from vdo.ninja, host it in the same host, and maybe conceptualize workflows for whoever is organizing a vlog/video podcast.

**Comment by aaronpk** [comment]
Definitely an interesting idea, but this is a pretty huge change compared to how video is normally ingested into streaming platforms like OwnCast.

I could see one integration point which is to add a new ingestion mechanism in OwnCast to pull the WebRTC feed from one of VDO.ninja's "scenes". That way you could treat VDO.ninja essentially like StreamYard where you can add one or more people to a scene which would end up getting streamed on OwnCast.

I would be interested in seeing this prototyped first outside of OwnCast, which is doable if you can find some software to pull the WebRTC feed and push it to OwnCast's RTMP endpoint.

**Comment by nicopace** [comment]
Not in my capacity right now, but hopefully someone else picks up the challenge!

The big challenge is that VDO.ninja relies on end user hardware capacities (so, the better computer you have, the better stream you will have... and the opposite applies too) while StreamYard doesn't.

I am thinking of using a gpu-enabled VPS to use chrome from there (while a better option appears):
https://medium.com/@pigiuz/hw-accelerated-gui-apps-on-docker-7fd424fe813e

<blockquote><img src="https://miro.medium.com/max/1060/1*eXLDjtdxdqHg8bOFb9qetQ.png" width="48" align="right"><div>Medium</div><div><strong><a href="https://medium.com/@pigiuz/hw-accelerated-gui-apps-on-docker-7fd424fe813e">HW accelerated GUI apps on Docker</a></strong></div><div>Given that the large majority of examples leveraging Docker are specific to server development and management, Docker is often perceived as…</div></blockquote>

**Comment by gabek** [comment]
Any time we're talking about a specific source integration I think it's immediately a no-go, as Owncast is meant to be as general purpose as possible.  We've never taken an opinion on what you should use to stream with.

But as Aaron said, an argument could be made to support an additional protocol for ingestion, but RTMP is very much the standard and the number of use cases that would need WebRTC as a source are limited.

Unfortunately I think this is out of scope for what we're able to do right now.  Sorry about that.
