### ISSUE TITLE
Owncast discourse thread chat conversation

### ISSUE THREAD

**Issue by nicopace** [owncast/owncast#1360]
I've created a guide on how to host webinars using discourse.org here: https://hackmd.io/@nicopace/holding-webinar-on-discourse
It would be great if we could use the discourse.org post for the event as the chat window (similar to rocket.chat is used also).

**Comment by nicopace** [comment]
BTW amazing project!!! Have been following along, and just installed it using the yunohost plugin: https://github.com/YunoHost-Apps/owncast_ynh

<blockquote><img src="https://opengraph.githubassets.com/439b617c8d03beb8892d4a93d811fa5312ddcd7389222fe9080756b35db6f126/YunoHost-Apps/owncast_ynh" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/YunoHost-Apps/owncast_ynh">GitHub - YunoHost-Apps/owncast_ynh: Owncast package for YunoHost</a></strong></div><div>Owncast package for YunoHost. Contribute to YunoHost-Apps/owncast_ynh development by creating an account on GitHub.</div></blockquote>

**Comment by aaronpk** [comment]
You could embed the OwnCast player in the Discourse post, or you could do what I did with Rocket.chat which was to create a separate website that embeds both OwnCast and Rocket.chat in the same web page.

**Comment by nicopace** [comment]
Excellent! Now that I have it running, I will give it a go!
Will report the updates once I do. Thanks for the responsiveness @aaronpk !

**Comment by gabek** [comment]
Yeah!  Take a look at our embedding options and see if that can help you at all:

https://owncast.online/docs/embed/

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="/favicon.png" height="14"> Owncast</div><div><strong><a href="/docs/embed/">Embedding into your site</a></strong></div><div>You can easily embed your chat or video into another site.</div></blockquote>

**Comment by gabek** [comment]
I'm going close this since it doesn't seem like there's anything actionable at the moment, but feel free to chime in if there's any issues or specific requests that need to be looked into.
