### ISSUE TITLE
Option to hide version number from web and API

### ISSUE THREAD

**Issue by dodomedia** [owncast/owncast#1366]
I would like to suggest an option to hide the server version number from the web page and the /status/ API endpoint.

**Comment by gabek** [comment]
What's the use case?

**Comment by dodomedia** [comment]
Attackers can search for this information (by scraping the page or requesting the public status endpoint of the API) and find not yet patched or vulnerable servers if there are any security related issues in the future.

**Comment by gabek** [comment]
Chatted about this with some others and it was determined the risk is low, and the drawbacks are high from a troubleshooting standpoint.  Attackers will attack regardless.
