### ISSUE TITLE
Followers tab that displays Fediverse followers

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1370]
Will display a list of those on the Fediverse who follow this instance.

Will only display if Federation is enabled on the Owncast server.

**Comment by gabek** [comment]
The followers API is `/api/followers`.  Example: https://ap-test.owncast.tv/api/followers

`/api/config` now has a `federation` node that says if it's enabled or not so specific features can be shown.

```
"federation": {
  "enabled": true,
  "account": "testing@ap-test.owncast.tv",
  "followerCount": 2
}
```

**Comment by gabek** [comment]
I started a followers component and slapped it on the page just for ease of development and testing. It pulls some fake data since the followers API is going to be empty right now without any real followers.

![image](https://user-images.githubusercontent.com/414923/134080345-3ecb8a1a-a7ff-4889-956d-2d13044d302b.png)

**Comment by gingervitis** [comment]
Got a preference of whether tabs should be under the tags?
<img width="780" alt="image" src="https://user-images.githubusercontent.com/9563255/134787568-d30b37eb-bd35-4929-9c7c-6cb3dcd1406d.png">

or under everything?
<img width="799" alt="image" src="https://user-images.githubusercontent.com/9563255/134787612-7ddc44fa-32bc-45ad-869e-e1789b2f20d3.png">

**Comment by gingervitis** [comment]
Option C (A2)
<img width="799" alt="image" src="https://user-images.githubusercontent.com/9563255/134787778-6dd5da3f-046e-433b-a47d-82e49b11d834.png">
<img width="800" alt="image" src="https://user-images.githubusercontent.com/9563255/134787784-a1897bf2-3c49-45a4-bac4-0d9d04bf3566.png">

**Comment by gabek** [comment]
I vote for C!
