### ISSUE TITLE
Fediverse Follow button and modal UI

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1372]
Press button to start the Fediverse Follow flow.

This is just the button + modal UI. #1371 is filed for the actual flow logic.

**Comment by gabek** [comment]
It's functionally working, now a design for the modal and button needs to be made.

![remotefollow](https://user-images.githubusercontent.com/414923/132274418-8dbdc815-9f88-46a4-9b91-a10994f668cd.gif)

**Comment by gabek** [comment]
@gingervitis I'm added you to this, but feel free to unassign.

**Comment by gabek** [comment]
`/api/config` now has a `federation` node that says if it's enabled or not so specific features can be shown.

```
"federation": {
  "enabled": true,
  "account": "testing@ap-test.owncast.tv",
  "followerCount": 2
}
```

**Comment by gabek** [comment]
I just realized we already use the "Follow me" wording with the social links, so we might have to reword that.

**Comment by gabek** [comment]
I'll need to come up with some additional copy about what's going on and what "account" you need to put in there, or how to manually follow by providing the server's account info.

![image](https://user-images.githubusercontent.com/414923/134063466-cfb00053-b47c-4189-acfa-6f2ed157eb55.png)

**Comment by gingervitis** [comment]
Ok I've have some progress here at https://github.com/owncast/owncast/pull/1418.  The PR has a few things a bit out of scope but it cleans up the layout a bit in the "user info" area. 

- Moves the External Actions buttons to be more prominently above the User Content, right below the video
- Cleans up the social icons layout a bit 
- Cleans up the Logo and social buttons layout on mobile/single col views

While I'm not terribly familiar with the proper wording or coloring of a Fediverse Follow button, but we could do a few things in terms of placement.. 

### A. Just put a Follow button next to the title.
<img width="812" alt="image" src="https://user-images.githubusercontent.com/9563255/134253998-3de12638-828d-4e6e-b304-463664e5951d.png">

#### A2. Here's what it would look like on mobile.
<img width="531" alt="image" src="https://user-images.githubusercontent.com/9563255/134254555-f1195e85-ed17-49ab-b26c-5a5009a15404.png">

### B.  Or why don't we put it up with the External Actions?
<img width="855" alt="image" src="https://user-images.githubusercontent.com/9563255/134254763-aae8c7ff-68a0-46d5-9c85-38b74d68d84f.png">

**Comment by gingervitis** [comment]
Ok going with Option B.
