### ISSUE TITLE
[Feature request] Ability to change chat font size

### ISSUE THREAD

**Issue by marek-lach** [owncast/owncast#1387]
For readability purposes. A small **Aa** icon could be present right next to the emoji picker in the chat input box.

**Comment by gabek** [comment]
If you'd like to customize your own site's font globally you can use CSS to change it to look any way you like: https://owncast.online/docs/website/#custom-styles-via-css.

But I'm afraid I don't see us adding a font size selector into the interface. If people have a personal need to increase their font size they should use the browser tooling to zoom or change defaults.

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="/favicon.png" height="14"> Owncast</div><div><strong><a href="/docs/website/">Web Site + Chat</a></strong></div><div>Customize your Owncast web page by adding additional content and links.</div></blockquote>
