### ISSUE TITLE
Add storage provider for Microsoft Azure Blob Storage

### ISSUE THREAD

**Issue by jeyemwey** [owncast/owncast#139]
Hi,

Microsoft Azure offers a generous Azure Sponsorship for non-profit organizations like churches or sports clubs. However, the nomenclature in Azure is different to other services. It would be very helpful (to me, and hopefully to other people, too) to have a tutorial for Azure's S3-thingy.

**Comment by graywolf336** [comment]
Do you have a link where people can apply for this? I have a use case for this and would love to try it out so it can be documented.

**Comment by jeyemwey** [comment]
We are using https://www.microsoft.com/en-us/nonprofits/azure for the German National Boy Scouts Organization, in this case the Federal Office. Since they are using Office365 either way, they were donated $3,500. I am not sure if this can be applied for every small soccer club, we are the head quarters of a 100k people org.

**Comment by gabek** [comment]
I'm having a hard time finding that Azure Blob Storage is S3 compatible at all.  Most people suggest running MinIO to proxy Azure requests to S3 or something: https://min.io/solutions/azure-s3-api-integration.

We could create a new storage provider that uses the Azure SDK and support it natively.

**Comment by gabek** [comment]
Is this native Azure Blob Storage support something worthwhile adding?  I can take this on and get it into a future release if we think this would be useful.

**Comment by jeyemwey** [comment]
If you have the time, I would really appreciate that. Maybe, we can abstract the Storage interface, so other people can implement other solutions quickly?

**Comment by gabek** [comment]
Cool, I have #9 in the works and after that's in it'll be easier to add this new storage provider.

**Comment by gabek** [comment]
We should check in as a group again and see if we want to add this as a native storage provider internally, or if we want to support storage plugins.  Though we haven't exactly been sure what our plugin story would be, I do think storage would be a good candidate.

**Comment by argium** [comment]
What's the latest on Azure support?  Is there a technical limitation?

**Comment by gabek** [comment]
Owncast doesn't support any specific provider, but it does support the S3 protocol since that's what all storage providers (I guess except Azure) supports.  So if we were to add Azure storage support it would be specifically to support a single company.  Since only two people (including you) have ever shown interest in this, I don't see myself adding it, since it just makes sense for people to use any number of storage providers that use a standard API.
