### ISSUE TITLE
[Feature Request] Chat timeout

### ISSUE THREAD

**Issue by jlamothe** [owncast/owncast#1403]
It would be nice to specify a timeout after which messages automatically disappear from the chat. This would keep the chat from stagnating when being used as an overlay in OBS studio (via /embed/chat/readonly)

**Comment by gabek** [comment]
The use case is understandable, but that sounds more like it falls into the realm of having a custom interface just for embedding into your stream that has the specific features needed for that.  Unfortunately that's probably not something we'll be focusing on.

However, other people are.  I'm thinking along the lines of https://ownextend.online/.  

<blockquote><img src="/favicon.png" width="48" align="right"><div><strong><a href="https://ownextend.online/">Ownextend</a></strong></div></blockquote>
