### ISSUE TITLE
Update react-markdown to 7.0.x

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1405]
The updated `react-markdown` package in admin doesn't build. It's probably some small changes in our code to make it work.

Pull down the PR in https://github.com/owncast/owncast-admin/pull/290 and make any changes required to make it run.  The build error currently is:

```
./components/user-popover.tsx:7:10
Type error: Module '"react-markdown"' has no exported member 'ReactNode'. Did you mean to use 'import ReactNode from "react-markdown"' instead?

   5 | import formatDistanceToNow from 'date-fns/formatDistanceToNow';
   6 | import format from 'date-fns/format';
>  7 | import { ReactNode } from 'react-markdown';
     |          ^
```

**Comment by sytranvn** [comment]
Hi @gabek , I put up a PR for this issue https://github.com/owncast/owncast-admin/pull/313

**Comment by gabek** [comment]
Merged. Closed in https://github.com/owncast/owncast-admin/pull/313
