### ISSUE TITLE
Spike: The Owncast instance directory

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#142]
I took advantage of the long weekend to work on an experiment.

In conversations with random people the topic of discoverability comes up.  Usually it's in the form of "that sounds cool, but how will people find my stream?" and "How can I find other people's streams?"

Owncast out of the box helps fill in the infrastructure for live streaming, but I hope that we can provide something to allow people to continue building their live streaming communities.  Obviously this isn't for everyone.  If you're using Owncast as a piece of infrastructure for your own web site, then you (maybe) don't want it publicly advertised.  But for others having a little place that can be indexed and browsed might make the idea of the whole thing a little more accessible.

It's admittedly very much a chicken and egg scenario.  Why would we build any kind of platform to increase visibility of independent Owncast instances if there are few to none in production?  But it's kind of a non-starter for people who live stream for social and community reasons that nobody would know they ever existed.

But I thought I'd take a stab at it, modeled after [Shoutcast YP (Yellow Pages)](http://wiki.shoutcast.com/wiki/SHOUTcast_Listing_Requirements), where people who ran an independent Shoutcast internet radio server would show up in a global directory.

## How it works
1. The config will be expanded with a bool that defaults to `false` to list themselves in the directory.
1. When a live stream is taking place the instance will `ping` the YP service every `n` minutes with details about the instance such as name, tags, description and when the current stream went live.
1. If it's the first time an instance is ping'ing the YP service, the YP service returns back a `key`.  This key is then used for the instance to identify itself for subsequent updates.  If somebody tries to update YP with an instance name but does not supply the correct key then the update is rejected.  The URL of the instance and key must match going forward.
1. This data is then used to populate the directory.

This WIP branch of the Owncast server has the YP ping: https://github.com/owncast/owncast/blob/gek/yp-ping/yp/yp.go

## What the YP service does now
1. It filters out `NSFW` instances (as defined by `PING` payload) by default.
1. Instances can be tagged as anything they want, but only a specific set of whitelisted tags show up on the `Browse` page.  But you can still click through a link to see other instances tagged arbitrarily.
1. Sorts instances into currently live and not live for displaying in different places
1. Thumbnail and logos are shown.

I have the client/server WIP in https://github.com/owncast/owncast-yp.  The web UI is pretty rough, and there's lots of (security, validation, etc) questions that need to be answers and things tightened up if it's something that is continued to be pursued.  And while I always wanted the Owncast instance web UI to be simple(ish) without tooling, because this YP site/server is a centralized thing I used all the bells and whistles (Next.js, React, GORM...).

I'd love to hear all of your thoughts.  We all have our own use cases for Owncast, but I think this would be a great addition as a separate project.  Obviously in no rush, and there's far more important things to focus on, but I think this could be pretty cool.

@mattdsteele @graywolf336 @jeyemwey @gingervitis

![image](https://user-images.githubusercontent.com/414923/92422841-a90c4080-f133-11ea-8396-44576239c529.png)

![image](https://user-images.githubusercontent.com/414923/92424162-6731c900-f138-11ea-8acb-ee834da8fa13.png)

**Comment by gingervitis** [comment]
Since I don't do much broadcasting at all, while I've been building and testing owncast, I'm often finding myself in the mindset of a user browsing for videos to watch when I'm interested in finding something, or just bored and curious what weird things people might be into. I guess basically how I use Twitch right now. As a viewer I am likely to assume that owncast is just like Twitch (esp since it has chat and crazy emojis too!) And I would sort of expect or at least be interested in seeing what else there is on this platform that I can't find on Twitch. So a YP index of sorts would be pretty cool.  I can also see other budding streamers being interested in getting listed in it for discoverability. 

Then again I don't know what the most of the use cases are going to be. Maybe most streamers will just be sharing their video elsewhere and no one will be using the interface? (Though I guess that doesn't matter for the YP).

**Comment by jeyemwey** [comment]
I would love to see a "gallery" on the homepage that showcases embeds and users of Owncast. However, I am not sure, if I'd use a directory since my use of Twitch is usually restricted to few, selected channels.

Maybe, we can run (opt-in) analytics on the viewer stats, online stats with this application in the backend?

**Comment by mattdsteele** [comment]
I like this idea. It'll obviously depend on use case (I wouldn't have listed my wedding, but if I stream my future Zwift bike rides I'd want it registered), but I think this seems like a nice way to get a social aspect back.

Beyond a centralized directory, I wonder if this could also be useful embedding onto a streamer's site directly. Add your friends' stream names to your DB, and when they're streaming, its thumbnail could show up on your site in the sidebar... kind of like webrings of old?

**Comment by mattdsteele** [comment]
Another consideration: I like modeling this off Shoutcast, but most radio stations I listen to are streaming 24/7; while I think this'll be rarer with Owncast. With Twitch, on the other hand, I tend to discover streamers by navigating to their channel, then watching a recording of a previous stream. Would this be more useful if Owncast better supported recordings?

**Comment by graywolf336** [comment]
With it defaulting to off, I think this is a nice feature. Could add it as a primary button in the owncast homepage so that people can easily get to it. In addition to that, on the homepage of the YP you could tell people how to enable it so that those who want listed can easily do it without digging through pages of documentation.

**Comment by gabek** [comment]
Thank you for all the feedback, everyone!  It sounds like in general it's worth continuing to pursue, so I'll keep working on it on the side.  If you have any interest in working on the front or backends of this project, as always, I'm super happy to have you! And hopefully by the time it's ready there will be more instances to show off 👍 

Even without a polished page available I'll see where the YP PING api can fit in so people who run instances can enable it, even if we're not not quite ready for them yet.

> And I would sort of expect or at least be interested in seeing what else there is on this platform that I can't find on Twitch. So a YP index of sorts would be pretty cool. I can also see other budding streamers being interested in getting listed in it for discoverability.

That sums it up nicely. 

> Maybe most streamers will just be sharing their video elsewhere and no one will be using the interface?

The nice part of this approach is we can link directly to somebody's instance.  No "profile pages" or embedding their video into the directory UI.  There's no reason to keep them on the site.  The faster we can get somebody to somebody's independent instance's page the better.

> I like modeling this off Shoutcast, but most radio stations I listen to are streaming 24/7; while I think this'll be rarer with Owncast.

Absolutely.  I kind of saw the solution being to feature those that are live now, but still expose instances that aren't live and maybe it'll catch somebody's attention to keep an eye on for later.  Because realistically if only live instances were surfaced then it'd be pretty empty and sad looking.

> Would this be more useful if Owncast better supported recordings?

Yes!  It would give somebody content to view even if the instance was not currently live, and that would be much nicer.  I have some video pipeline changes in #9 that should help lay the groundwork for recordings.

> I would love to see a "gallery" on the homepage that showcases embeds and users of Owncast. 

Because we wouldn't be able to hard code specific instances (because they'd be offline most of the time) we could probably use the YP APIs to embed instances we know that are live.  Or like Bradley mentioned, we could make the link to the full directory prominent.  But having a couple live instances right in the web page and embedded has value too.

> Beyond a centralized directory, I wonder if this could also be useful embedding onto a streamer's site directly. Add your friends' stream names to your DB, and when they're streaming, its thumbnail could show up on your site in the sidebar... kind of like webrings of old?

I like the idea!  I'm not sure formalizing is necessary, but if we see communities of people spinning up instances then I could see them wanting to link to others.  And as an aside, I learned about something on Twitch this weekend called "Raiding".  It's the idea that when your stream ends you can send all the viewers currently tuned into you to another stream.  It's a neat idea, and a basic implementation could certainly be added to Owncast to facilitate this ring idea too.  When your stream ends you redirect them to an arbitrary url.

>  on the homepage of the YP you could tell people how to enable it so that those who want listed can easily do it without digging through pages of documentation.

Yes! That makes a lot of sense, plus it might point people to learning more about running their own instance when they see what that's all about.  The idea of a web admin dashboard (#114) is something that I think will make a big difference here too.  The original version of the dashboard I see as being a read-only "status page", but I think it's a logical next step to add additional functionality to configure the instance.

Thanks again, everyone.

**Comment by gabek** [comment]
Closing discussion since I got some great feedback.
