### ISSUE TITLE
Streaming URL

### ISSUE THREAD

**Issue by siavashfazli** [owncast/owncast#1423]
hi . 
I run owncast by docker-compose and use nginx as a router and its work correctly.
ports opened in nginx config
now i what start streaming by OBS
i use streaming url in admin panel but doesn't work because it has port on url and ports are opened in nginx
What should I enter as a server name in obs setting ?

 ` webserver:
    container_name: nginx
    image: nginx:latest
    volumes:
      - /home/wordpress/nginx_data:/etc/nginx/conf.d:rw
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks:
      - nginx-network

  owncast:
    container_name: stream

    image: gabekangas/owncast:latest

    restart: unless-stopped

    volumes:
      - /home/data:/app/data

    expose:
            - "8080/tcp"
            - "1935/tcp"
    networks:
      - nginx-network`

and nginx config is 
server {
        server_name owncast.xxx.ir;
        location / {
        proxy_pass http://owncast:8080;
        proxy_set_header Host owncast.xxx.ir;
        }
}
server {
        server_name owncast.xxx.ir:1935;
        location / {
        proxy_pass http://owncast:1935;
        proxy_set_header Host owncast.xxx.ir;
        }
}

**Comment by jeyemwey** [comment]
Hi, do I understand it correctly that you can see the website and make changes in the admin panel, but cannot connect to Owncast via OBS?

Have you made sure that your host firewall allows for access on port 1935? There is documentation on connecting Owncast with OBS: https://owncast.online/docs/broadcasting/obs/

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="/favicon.png" height="14"> Owncast</div><div><strong><a href="/docs/broadcasting/obs/">OBS/Streamlabs OBS</a></strong></div><div>OBS is a popular piece of free software for live streaming.</div></blockquote>

**Comment by siavashfazli** [comment]
Hi, with docker run connect correctly ,also i can connect with OBS and start streaming it's ok , when i use docker-compose as you can see owncast and nginx in a network and nginx response pockets.in this condition i can see website and admin panel but i cant connect with OBS. i use name server . what should i insert as server in obs(without port) that can read 1935 port.
is it in nginx config file?

**Comment by siavashfazli** [comment]
Dear jeremwey, imagine you want run owncast by docker-compose through nginx, what is streamserver url in OBS ?

**Comment by jeyemwey** [comment]
The RTMP stream from OBS to Owncast does not run through nginx, so the scenario should be the same as before. So you can give OBS any domain name that points to your server.

**Comment by siavashfazli** [comment]
Thanks a lot 🙏🙏🙏 for your help

**Comment by jeyemwey** [comment]
Okay, I will close this now. If you have any more questions, please ask here or hop into the chat at https://owncast.rocket.chat :)

<blockquote><img src="assets/favicon_512.png" width="48" align="right"><div><strong><a href="https://owncast.rocket.chat/">Owncast</a></strong></div></blockquote>
