### ISSUE TITLE
Server URL not saving

### ISSUE THREAD

**Issue by sitehatchery** [owncast/owncast#1426]
I just upgraded to version 0.0.8. When I try to save the Server URL, it does not save. It says "Success", but if I reload the page, the value is blank.

**Comment by sitehatchery** [comment]
This is on version 0.0.8, which I just upgraded to.

**Comment by sitehatchery** [comment]
NM. It was because I had a stream going.

**Comment by jeyemwey** [comment]
Hi, you have closed the issue - did you figure out what happened?

Feel free to share what you did to fix it :)

**Comment by sitehatchery** [comment]
Yes, for some reason it was blank when the stream was going. I kept refreshing after saving. But then when I ended the stream, I was able to save it.  Not sure what is going on there, but I was ultimately able to save it.
