### ISSUE TITLE
Owncast Viewers does not update

### ISSUE THREAD

**Issue by sitehatchery** [owncast/owncast#1427]
I updated to version 0.0.8. In 0.0.7 this was working. 

I am running Owncast as a service.

When I stream and then view the stream, it does show that there is an active stream, but the viewer count will not update.

In addition, when I chat, it doesn't show the connected chat participant or any of the chat messages I send.

When I refresh the streaming video, the chat message I entered disappears.

**Comment by gabek** [comment]
I can't say I've seen anything like this, and nobody else has mentioned they have experienced this.  Do you see any errors in your browser console or in Owncast logs?  Does it happen in every browser you try?

**Comment by sitehatchery** [comment]
Few things that might help:
- In order to see the online status in the admin console, I need to do a hard refresh.
- In order to see the video start playing on the website (with embedded iframe) I need to refresh the page
- On the current test, it shows "Max viewers in this session" as 2. But the "Current viewers" is 0.
- The chat messages appear within the Chat Messages admin after like 1 or 2 minutes instead of right away.
- If I start a chat as a users, I can see the chat, but then if I refresh my screen, I don't see it anymore. 
- The chats only show up if I select all the chats in admin and click the "Show" button.  But then if I refresh the chat window, they are all hidden again.

**Comment by gabek** [comment]
Unfortunately none of that is much help.

Are you seeing any errors either in the browser or the Owncast logs?  Are you seeing this with all browsers?  If you go to other Owncast installs such as https://watch.owncast.online can you see the viewer count?  Can you chat?

<blockquote><div><strong><a href="https://watch.owncast.online/">Owncast</a></strong></div></blockquote>

**Comment by sitehatchery** [comment]
Note really any errors. There is this but it seems harmless: 
Video transcoder started using x264 with 1 stream variants.

I've tested in Chrome and Firefox.

The viewer count is what I am seeing in admin, not the streaming video page (you mentioned https://watch.owncast.online). It shows Current viewers: 0 always. 

Chats do show during the chat session. But refreshing the page causes all the chats to disappear from the comment box.

<blockquote><div><strong><a href="https://watch.owncast.online/">Owncast</a></strong></div></blockquote>

**Comment by gabek** [comment]
Are there any errors in your browser console?

**Comment by sitehatchery** [comment]
There are a few things. They aren't critical errors, but maybe they have something to do with it.

![image](https://user-images.githubusercontent.com/2289893/134725175-0049e3f3-8dab-4a02-a0b5-6e5796daa0ce.png)

One thing is" We received no playlist to switch to. Please check your stream." keeps repeating over and over.

**Comment by gabek** [comment]
I feel like something overarching is wrong somewhere.  Video has nothing to do with chat.  Having to refresh your page to get updates has nothing to do with chat moderation.  None of what you reported has to do with a lot of other things you reported.  So I'm not sure if you have any proxies in play, or any additional layers of anything, but I'd recommend simplifying as much as possible.

I wish I had something actionable to suggest, but none of what you're mentioning is pointing to a specific problem, as there's no errors anywhere.

**Comment by sitehatchery** [comment]
Alright, thanks for your quick replies. You are on it!

**Comment by sitehatchery** [comment]
The biggest issue I'm having is that I cannot see any connected chat
participants. And so therefore I can't moderate chat users.

I did upgrade from 0.0.7 if that makes any difference.

**Comment by sitehatchery** [comment]
Actually, now that I have upgraded to 0.0.9, I am seeing these issues in
Chrome's browser console:


Front end:

[image: image.png]

Admin:
[image: image.png]


Jason Cox
(530) 924-3828

To create a *support ticket*, send an email to ***@***.*** or
log in here: https://sitehatchery.freshdesk.com/

**Comment by gabek** [comment]
Closing as there doesn't seem to be anything actionable on the Owncast side and haven't been provided any errors that need to be resolved.
