### ISSUE TITLE
Show chat in embed

### ISSUE THREAD

**Issue by sitehatchery** [owncast/owncast#1428]
When I use the iframe embed code for the websites, it doesn't include chat. Is there a parameter I can pass to include chat, or do I need to embed the chat as stand alone?

**Comment by gabek** [comment]
That's correct, if you want to embed chat then you must do that as well.  Embedding video will only embed video.  Please take a look through the embedding documentation for details.  https://owncast.online/docs/embed/

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="/favicon.png" height="14"> Owncast</div><div><strong><a href="/docs/embed/">Embedding into your site</a></strong></div><div>You can easily embed your chat or video into another site.</div></blockquote>
