### ISSUE TITLE
Localize the Quickstart

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1430]
With the new Quickstart wizard it supports multiple languages.  If you speak something other than English, it would be great to have your assistance!

Data file: https://github.com/owncast/owncast.github.io/blob/master/static/wizardassets/data/quickstart_pages.json

For reference here's the library we're utilizing: https://expeditionjs.com/

**Comment by jeyemwey** [comment]
Starting on the `de-DE` translation. Is there a roadmap on offering the different translations?

**Comment by vinicio** [comment]
Hi there! Can I translate it to portuguese (Brazil)?

**Comment by jeyemwey** [comment]
@vinicio Sure, please base your changes off the lingo/quickstart-de branch, so we can merge them better later.

**Comment by LoicB** [comment]
Hello! If you want I can translate it into French.

**Comment by gabek** [comment]
Sure! I haven't had a chance to dig through the wizard to see if it automatically selects the correct language or not, so the other translations are waiting on figuring that out. But if you want to add French, we can add it to the list once that part is functioning.

**Comment by LoicB** [comment]
That's great. Do you want me to include previous pr (German and Portuguese) as well or just French?

**Comment by gabek** [comment]
@LoicB German is already taken care of, but Portuguese and French would be awesome!  Could you branch from the [lingo/quickstart-de](https://github.com/owncast/owncast.github.io/tree/lingo/quickstart-de) branch?  Thanks!
