### ISSUE TITLE
Remove old chat messages

### ISSUE THREAD

**Issue by sitehatchery** [owncast/owncast#1434]
How do I remove old chat messages from the front end chat list? Even if I hide them in admin, they still show on the front end. 

Each time we stream from OBS, we want to clear the previous chats.

**Comment by gabek** [comment]
There's no way to auto-clear all the messages when starting a new stream. Messages eventually drop off over time.

Messages do get removed from chat history when you remove them via moderation in the admin, but there's something that's being tracked where sometimes they're not being removed in real-time for people already connected to chat.  https://github.com/owncast/owncast/issues/1350

**Comment by sitehatchery** [comment]
I don't see where to remove or moderate a particular chat message. I only
see a way to hide them. Am I missing something? Being able to delete
specific chat messages would be great.

Jason Cox
(530) 924-3828

To create a *support ticket*, send an email to ***@***.*** or
log in here: https://sitehatchery.freshdesk.com/

**Comment by gabek** [comment]
You go to `/admin/chat/messages/` and click on the little eyeball to the right of any message and then that message will no longer be returned in the chat history.

**Comment by gabek** [comment]
Closing as messages can be hidden via the admin and an auto-hide will not be added.
