### ISSUE TITLE
invalid memory address or nil pointer dereference 

### ISSUE THREAD

**Issue by ghost** [owncast/owncast#1439]
```
INFO[2021-09-29T12:13:43-05:00] Video transcoder started using x264 with 1 stream variants.
INFO[2021-09-29T12:14:53-05:00] Inbound stream disconnected.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xc5d3fd]

goroutine 3431 [running]:
github.com/owncast/owncast/core.SetStreamAsDisconnected()
	/go/src/github.com/owncast/owncast/core/streamState.go:97 +0x16d
github.com/owncast/owncast/core.setStreamAsConnected.func1.1(0x0, 0x0)
	/go/src/github.com/owncast/owncast/core/streamState.go:62 +0x20
github.com/owncast/owncast/core/transcoder.(*Transcoder).Start(0xc000f3d2b0)
	/go/src/github.com/owncast/owncast/core/transcoder/transcoder.go:126 +0x501
github.com/owncast/owncast/core.setStreamAsConnected.func1(0xc001266028)
	/go/src/github.com/owncast/owncast/core/streamState.go:67 +0x7e
created by github.com/owncast/owncast/core.setStreamAsConnected
	/go/src/github.com/owncast/owncast/core/streamState.go:59 +0x263
```

Streaming with external S3 storage. I haven't tried to reproduce the crash.

Version: v0.0.9

**Comment by gabek** [comment]
If you have a chance to reproduce this, or can share any specific configuration that makes this occur, please do.

**Comment by ghost** [comment]
To reproduce:

1. Start v0.0.9 with empty data directory
2. Open OBS Studio to configure to stream to owncast instance
3. Rapidly click "Start Streaming"/"Stop Streaming"
4. owncast will crash

I believe there's data races happening. In just taking a peek at the code, I notice there is a lack of locking on global variables (e.g. `_hasInboundRTMPConnection`), which would account for variables being in an invalid state.

**Comment by bontibon** [comment]
I believe there's data races happening. In just taking a peek at the code, I notice there is a lack of locking on global variables (e.g. `_hasInboundRTMPConnection`), which would account for variable be in an invalid state.

**Comment by gabek** [comment]
> Rapidly click "Start Streaming"/"Stop Streaming"

Certainly sounds like a race condition to me.

**Comment by gabek** [comment]
I've unfortunately been unable to reproduce this by starting/stopping a RTMP stream over and over again in quick succession.  I'll try again at another time.

**Comment by jaydn** [comment]
This is how you can reliably reproduce this crash
Causes crash of whole owncast container
Not dangerous and requires authentication as far as I can tell
Using VLC media player 3.0.16 Vetinari (revision 3.0.13-8-g41878ff4f2) on host

```bash
mkdir owncast_crash
cd owncast_crash
git clone https://github.com/owncast/owncast.git
cat <<EOF > docker-compose.yml
---
version: "2.1"
services:
  owncast:
    build: ./owncast
    ports:
      - 127.8.0.1:1935:1935
    volumes:
      - ./data:/app/data
EOF
sudo docker-compose up
```

when ready for crash
```bash
cvlc  --sout "#transcode{vcodec=h264,acodec=aac}:std{access=rtmp,mux=ffmpeg{mux=flv},dst=rtmp://127.8.0.1:1935/live/abc123" https://raw.githubusercontent.com/anars/blank-audio/master/500-milliseconds-of-silence.mp3 https://raw.githubusercontent.com/anars/blank-audio/master/500-milliseconds-of-silence.mp3
```

**Comment by jeyemwey** [comment]
This looks like you're only sending an audio stream and (maybe?) a 0x0 resoluted video? Anyways, Owncast should not crash from this but it might be a problem.

**Comment by jaydn** [comment]
> This looks like you're only sending an audio stream and (maybe?) a 0x0 resoluted video? Anyways, Owncast should not crash from this but it might be a problem.

Yeah I ran into this when attempting to stream normal videos, swap with a couple of video files of your liking and it'll still do it, the 2 small remote files is just for convenience
Have not dug into it much sorry just spotted this in the issue tracker with same stack trace, might be a completely different problem even

**Comment by gabek** [comment]
Thank you for providing a way to reproduce the issue!
