### ISSUE TITLE
Safari wrongly shows "chat offline"

### ISSUE THREAD

**Issue by jameskimmel** [owncast/owncast#1443]
Safari 15.0 shows chat offline despite it being online. Same owncast instance with Firefox does shows chat online as it should be.

Docker Owncast v0.0.8

**Comment by gabek** [comment]
Could you share any browser console errors you have?

**Comment by jameskimmel** [comment]
```
WebSocket connection to 'wss://3D' failed: Unexpected response code: 401

SyntaxEChat has been disconnected and is likely not working for you. It's possible you were removed from chat. If this is a server configuration issue, visit troubleshooting steps to resolve. https://owncast.online/docs/troubleshooting/#chat-is-disabled: Websocket closed.

Error: JSON Parse error: Unexpected identifier "object"

```

Hope that helps. I unfortunately have no clue about web stuff.

**Comment by gabek** [comment]
Is `3D` the name of your Owncast server?

**Comment by jameskimmel** [comment]
Shortened version, yes.

Updated the three browser errors for better visibility.

**Comment by jameskimmel** [comment]
Issue is only with one instance.
Probably a problem of the NGINX reverse proxy of the instance and not my machine. 

Sorry I did not get the idea to test that sooner.

**Comment by aaronpk** [comment]
Possibly related to this: https://github.com/glowing-bear/glowing-bear/issues/1199
