### ISSUE TITLE
Unable to submit Embeddable Chat messages on mobile

### ISSUE THREAD

**Issue by fullyaccountable** [owncast/owncast#1445]
On mobile (Android 11, OnePlus 9 Pro, stock keyboard), I'm unable to submit chat messages. The return key creates a new line instead of submitting the message, and there's no explicit Send button visible in the chat window to click.

Edit: I was able to get around this by adding Custom CSS in the admin to force the Send button to show:

`#send-message-button{display:block; opacity: 1;}`

**Comment by gabek** [comment]
Sounds like there's two issues here:

1. Enter isn't sending chat messages on mobile in the embedded chat.
2. The mobile-only "send" button isn't showing up in the embedded chat.

**Comment by gabek** [comment]
Verified the same on Safari. The input field doesn't show. 

![image](https://user-images.githubusercontent.com/414923/135692531-33f263c4-0de3-4cd7-bd2c-28826e1bad37.png)

**Comment by gabek** [comment]
Brave on iOS is fine.  Safari on iPad is fine.

**Comment by gabek** [comment]
Closing in favor of redesign+rebuild. #1859
