### ISSUE TITLE
Document that Backblaze B2 is unsupported due to CORS

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#145]
It's S3 compatible storage, so it should be straightforward.  Just would be good to know that it works so we can document any details around it.

https://www.backblaze.com/b2/cloud-storage.html

**Comment by gabek** [comment]
CORS strikes again.  Even after setting a CORS policy to "Share everything in this bucket with every origin" the files are still blocked in Chrome.  Safari is fine and if you play the video outside the browser (I'm using Quicktime) it also works fine.  I'm guessing this is because Safari using native HLS playback, and Chrome is using video.js.  So I'll have to see if video.js is doing something weird.

![image](https://user-images.githubusercontent.com/414923/92866363-4fff0f80-f3b4-11ea-8076-e7a1749860da.png)

**Comment by gabek** [comment]
So it turns out B2 doesn't support CORS with it's S3 compatible API.  And Videojs has to play by CORS rules where Safari and Quicktime don't, because they're using native (non-browser based) HLS implementations.  So I'll add to documentation that B2 is not supported. 

> At this time, CORS rules are not supported with the S3 compatible API. If you wish to utilize CORS rules on your bucket, you must use the B2 native API: https://www.backblaze.com/b2/docs/

**Comment by graywolf336** [comment]
Wow, that's sad :( I was looking forward to using B2 with S3 support

**Comment by gabek** [comment]
Disappointing for sure!  Add it to the list of possible future storage providers I guess.

![image](https://user-images.githubusercontent.com/414923/93249699-8f2bb880-f746-11ea-8df3-9e8849fa6fbc.png)
