### ISSUE TITLE
Test and document Vultr S3-compatible object storage

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1451]
I'm verifying that Vultr sees video as an acceptable use case for their storage product first, and then we can add it to our list of storage options.  https://www.vultr.com/docs/vultr-object-storage

They do have a 400 request per second per IP limit, but that shouldn't impact what we'd be doing.

**Comment by gabek** [comment]
Vultr clarified with me that using video on their storage product is acceptable.

**Comment by spannerman79** [comment]
I would love to know the outcome of your testing @gabek as I use Vultr myself personally.

**Comment by koad** [comment]
I was able to get s3 external storage using vultr working.

After setting up the storage and configuring owncast, i had to deal with cors on the object storage using a command line utility called s3cmd.

I set up s3cmd to work with my object storage using vultr's documentation.
[https://www.vultr.com/docs/how-to-use-s3cmd-with-vultr-object-storage](https://www.vultr.com/docs/how-to-use-s3cmd-with-vultr-object-storage)

I set cors on the vultr object storage also using the vultr documentation.
[https://www.vultr.com/docs/how-to-apply-cors-policies-to-vultr-object-storage-buckets](
https://www.vultr.com/docs/how-to-apply-cors-policies-to-vultr-object-storage-buckets)

I am unsure of the limitations here, and will be testing but I am not social/popular enough to test how many viewers one can have before it gets expensive/unreliable.

<blockquote><div><strong><a href="https://www.vultr.com/docs/how-to-use-s3cmd-with-vultr-object-storage">Please Wait... | Cloudflare</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://www.vultr.com/docs/how-to-apply-cors-policies-to-vultr-object-storage-buckets">Please Wait... | Cloudflare</a></strong></div></blockquote>

**Comment by gabek** [comment]
Awesome, thank you @koad! I went ahead and added Vultr to the storage provider documentation along with your links and notes.  I really appreciate your help trying this out and reporting back, I'm sure it'll be a big help for people.
