### ISSUE TITLE
Not able to change Server URL

### ISSUE THREAD

**Issue by nwoltering** [owncast/owncast#1452]
After installing Owncast via the automatic installer i am not able to change the URL and connect to the server from a differnt PC. When restarting the Server no matter what URL has been set, the Server is always listening on 0.0.0.0:8080.

**Comment by gabek** [comment]
There is a difference between what the public URL of the server is and what IP address it's listening on.

Changing the server URL (in the admin under Configuration -> General) has nothing to do with what interface on your machine the service is binding to.  Unless you are looking to bind the service to a specific IP address, such as loopback only, or you have multiple network interfaces that you want to choose between, then `0.0.0.0` will be correct and there's nothing you need to change.
