### ISSUE TITLE
Change page title to something different than server name + local storage option

### ISSUE THREAD

**Issue by ClaraCrazy** [owncast/owncast#1458]
Greetings!

Lovely what you created here however I have two small issues:

1. I would love to have my page title not be my streamer name (yes it makes sense for it to be like that since I'm gonna be the only streamer as far as I understood that HOWEVER, I would still love to change it to something else like "{Name} - Live / Stream" I looked through the index.html but that didn't help and I didn't have the time to look through all the files just to find where it actually changes the page title.

2. Allow local storage for videos, please!
I host this on a high-capacity server and would love not to set up a different service to simulate an s3 so I can store videos locally. Just allow storing to a local path or something like that.

Again, otherwise, it's an amazing project!

Keep up the great work!

**Comment by jeyemwey** [comment]
Hi, we’re glad you like it! :)

> changing the ˋ<title>ˋ

The title can [change for multiple reasons](https://github.com/owncast/owncast/search?l=JavaScript&q=title), including new chat messages while you were tabbed out, and a change in the online/offline status. So it’s a little more complicated. You can however create a feature request, if you need more/other functionality (or we piggy-back on this issue).

> local storage

If you don’t enable S3, the video files should be stored and served from your server’s hard drive. The files are stored in ˋdata/hlsˋ. Please note that the folders are destructed after each stream (during the clean up phase), so symlinking that folder somewhere might not work.

Let us know if you have any more issues or questions.

**Comment by ClaraCrazy** [comment]
> The title can change for multiple reasons,

yeah, true. Well, all I would love to have is an option to have a different streamer name than the actual page name. Gonna make a feature request later for that

> the video files should be stored and served from your server’s hard drive

Uhm... I'm probably just super stupid right now but how would a user access old streams then? I thought that's what the storage options are for since OBS etc. record already anyways (meaning the streamer doesn't need another recording)

**Comment by jeyemwey** [comment]
> all I would love to have is an option to have a different streamer name than the actual page name. Gonna make a feature request later for that

Did you see that you can set a title for a stream? I’m not sure if that’s „enough“ if we just pop that into the title tag, or we need another field.

> how would a user access old streams then?

They would not. Recording streams and showing them afterwards is on the road map, but is not programmed yet. If you want to put the video to YouTube (or wherever), id suggest pulling the stream chunks before formally ending the stream in OBS and merging the best encoding setting (with ffmpeg or ˋcatˋ).

**Comment by ClaraCrazy** [comment]
> Did you see that you can set a title for a stream? I’m not sure if that’s „enough“ if we just pop that into the title tag, or we need another field.

I did and could actually agree on "Streamer_name - Stream_title" and "Streamer_name - Offline" when there's no stream


> Recording streams and showing them afterwards is on the roadmap but is not programmed yet.

alright, gotcha. You got an approx. eta (like Idk.. before Christmas or something like that. Just a rough timeframe) or can perhaps tell me how high it is priority-wise on the to-do list?

You can close the issue with your response if you have no further questions then btw

**Comment by jeyemwey** [comment]
Absolutely no ETA, sorry.

If you have any more questions, feel free to open another issue or come in the chat at owncast.rocket.chat
