### ISSUE TITLE
docker-compose examples are broken

### ISSUE THREAD

**Issue by muesli** [owncast/owncast#1475]
The example docker-compose configs are rather convoluted and broken. We should offer a basic config here.

**Comment by gabek** [comment]
I kind of think we should get rid of them all together. They're not terribly helpful unless you have those exact configurations. They probably made sense at one point but not so much now.

**Comment by muesli** [comment]
That's why I'm suggesting a barebone basic config that's universally usable. No reverse proxying, just a plain Owncast docker-compose.

**Comment by gabek** [comment]
If we need to add something specific to docker-compose to our documentation we can do that, but I'm guessing we probably don't since we already point people to the image in our Docker page.  I went ahead and removed the confusing, overly specific examples from the repo.
