### ISSUE TITLE
Extend the viewers timeline

### ISSUE THREAD

**Issue by ghost** [owncast/owncast#1478]
It would be great to extend the timeline shown on the 'viewers info' screen, which shows you the number of viewers, as well as a graph with historical data over what looks like approximately 15 hours. That timeframe is good to see the number of viewers over a day, though it would be helpful to be able to use this graph to easily compare the number over several days, a week, 4 weeks etc.

**Comment by gabek** [comment]
I'm not opposed to this. It might be nice to store the viewer data in the database and then query for whatever time window.

**Comment by gabek** [comment]
On another note, would it be useful at all to expose the viewer count to use an external time series database for tracking this kind of thing? Ultimately long-duration time series data will be better served with something that's built for it.  https://github.com/owncast/owncast/issues/1303

**Comment by ghost** [comment]
That would be useful for sure.

**Comment by gabek** [comment]
Whatever limited internal time series data we use for playback metrics we can use for this as well.  See https://github.com/owncast/owncast/issues/793

**Comment by gabek** [comment]
https://github.com/nakabonne/tstorage seems like a nice option for an embedded time series database.

<blockquote><img src="https://opengraph.githubassets.com/5d776dba6616de3baab85944787201926a77a89e7d80f83b3207ce7eb6ac8b29/nakabonne/tstorage" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/nakabonne/tstorage">GitHub - nakabonne/tstorage: An embedded time-series database</a></strong></div><div>An embedded time-series database. Contribute to nakabonne/tstorage development by creating an account on GitHub.</div></blockquote>
