### ISSUE TITLE
webrtc

### ISSUE THREAD

**Issue by pjebs** [owncast/owncast#149]
Is there someway to use webrtc technology instead for streaming using this pkg: https://github.com/pion/webrtc?

**Comment by pjebs** [comment]
https://www.wowza.com/blog/using-webrtc-as-rtmp-alternative#:~:text=RTMP%20vs.,delivers%20several%20advantages%20over%20RTMP.&text=Secondly%2C%20at%20sub%2D500%2D,lowest%20latency%20protocol%20out%20there.

**Comment by gabek** [comment]
I'm afraid not at the moment.  Owncast aims to have compatibility with the mainstream pieces of broadcasting software, and RTMP is by far the most popular for broadcasting at this time. 

Even that article says as much.

> ...remains the standard for first-mile video contribution on many social platforms. But even that could change with time.

But if that were to ever change I'd certainly be up for re-evaluating. But out-of-the-box compatibility is most important.

**Comment by beriberikix** [comment]
What about the other way around - have a WebRTC server output RTMP? This would be very useful to livestream an existing a group discussion. Pion has a very basic [example](https://github.com/pion/example-webrtc-applications/tree/master/twitch) along those lines.

**Comment by graywolf336** [comment]
I believe Jitsi meet can already do this, I seen discussion about it in Rocket.Chat. Not sure if it is documented yet.

**Comment by gabek** [comment]
Yes!  We have some documentation about using it with Zoom, and recently learned that Jitsi can do it as well.  We'll update the documentation soon.
