### ISSUE TITLE
Dropbox File Storage

### ISSUE THREAD

**Issue by sitehatchery** [owncast/owncast#1493]
I'd like to use DropBox for storing videos that have streamed.

**Comment by sitehatchery** [comment]
This should be the end point:
https://www.dropbox.com/developers/documentation/http/documentation#files-upload

Requires a S3 compatible storage provider, but I would love if this worked with Dropbox.



<blockquote><img src="https://cfl.dropboxstatic.com/static/images/logo_catalog/dropbox_webclip_200_vis.png" width="48" align="right"><div>Dropbox</div><div><strong><a href="https://www.dropbox.com/developers/documentation/http/documentation">HTTP - Developers - Dropbox </a></strong></div><div>Dropbox is a free service that lets you bring your photos, docs, and videos anywhere and share them easily. Never email yourself a file again!</div></blockquote>

**Comment by aaronpk** [comment]
Dropbox dropped support for static file serving a few years ago, so it won't be possible to use Dropbox for hosting the actual streaming segments during a livestream. I could see it being useful to store the archived recordings in Dropbox once the recording feature is added, but that's still a ways out.

**Comment by sitehatchery** [comment]
Yep, it will be for archived recordings.

I do like what I see here:  https://www.backblaze.com/b2/cloud-storage.html

Does setting this up not archive the recordings yet? I hoped so.

Jason Cox
Support Phone: (530) 924-3828
Cell: (530) 680-2734

To create a *support ticket *for help with your website or software
project, please send an email to ***@***.*** or log in here:
https://sitehatchery.freshdesk.com/

**Comment by aaronpk** [comment]
Correct, there is no recording feature at the moment. It's on the roadmap but IIRC there are some other priorities in the works at the moment too. https://github.com/owncast/owncast/milestone/5

<blockquote><img src="https://repository-images.githubusercontent.com/266445736/4f82fb80-a5b1-11ea-8f1c-69d316f861b5" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/owncast/owncast">v0.1.0 - Recordings Milestone · owncast/owncast</a></strong></div><div>Take control over your live stream video by running it yourself.  Streaming + chat out of the box. - v0.1.0 - Recordings Milestone · owncast/owncast</div></blockquote>

**Comment by sitehatchery** [comment]
Thanks!

Jason Cox
Support Phone: (530) 924-3828
Cell: (530) 680-2734

To create a *support ticket *for help with your website or software
project, please send an email to ***@***.*** or log in here:
https://sitehatchery.freshdesk.com/

**Comment by gabek** [comment]
The plan for recordings allows for replays, not for archival.  I know they might sound like the same thing, but the I still want to optimize for somebody being able to press "Play" and streaming a replay of a prior stream, with all of the benefits of HLS and adaptive bitrates. Not a directory with rendered files to download.

So in short, none of this would be compatible with Dropbox.
