### ISSUE TITLE
Steam as a Social Platform

### ISSUE THREAD

**Issue by b-squared42** [owncast/owncast#1501]
Small Feature Request:
I can choose between many social platforms in the general settings. I would like to have _Steam_ in there as well.
[Logopedia](https://logos.fandom.com/wiki/Steam)
[Official Steam Branding Guidelines pdf](https://steamcdn-a.akamaihd.net/steamcommunity/public/images/steamworks_docs/german/Steam_Guidelines_1217.pdf)

**Comment by gabek** [comment]
If anybody wants to add this you can append to the list of existing platforms at: https://github.com/owncast/owncast/blob/develop/models/socialHandle.go#L22

<blockquote><img src="https://repository-images.githubusercontent.com/266445736/4f82fb80-a5b1-11ea-8f1c-69d316f861b5" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/owncast/owncast">owncast/socialHandle.go at develop · owncast/owncast</a></strong></div><div>Take control over your live stream video by running it yourself.  Streaming + chat out of the box. - owncast/socialHandle.go at develop · owncast/owncast</div></blockquote>
