### ISSUE TITLE
Add automated tests for Webhooks

### ISSUE THREAD

**Issue by jeyemwey** [owncast/owncast#1528]
Currently, Webhooks are only tested manually (see e.g. [here](https://github.com/owncast/owncast/pull/1525#issuecomment-967743810)).

To check that they don't break, we should add some manual tests related to this topic. For this, I'd start a separate http server and check if the webhooks are coming through.

**Comment by mdonoughe** [comment]
I've started working on this.

**Comment by gabek** [comment]
Very cool! Thank you!
