### ISSUE TITLE
Strip out problematic and confusing characters from chat display names

### ISSUE THREAD

**Issue by Semisol** [owncast/owncast#1541]
Currently, nicknames can contain any character, such as unicode.
This cam cause problems, such as people using a banned nickname with ZWSPs or adding dots/etc at the end.
I recommend the character set `A-Z`, `a-z`, `0-9`, `-` and `_` for nicknames.

**Comment by gabek** [comment]
Seems artificially limiting, no? I see people use longer display names with spaces and punctuation and it doesn't hurt anybody. They're just display names so there's no reason they can't be whatever they want them to be.

We match against the blocked username list by trimming whitespace and checking for substrings, so it doesn't have to be an exact match.

If there are specific examples you're concerned about we should fix them, however.

**Comment by Semisol** [comment]
ZWSP and similar are causing problems. I would suggest a configuration parameter for a regex, which would give users freedom to pick what characters they want + block some obviously bad ones (ZWSP, \ufeff, ...)

**Comment by gabek** [comment]
Most people aren't going to write their own regex, and I wouldn't want to ask them to.  But I'm not opposed to internally stripping more characters that humans wouldn't use.  Like I mentioned, we're already trimming whitespace characters (is ZWSP not seen as whitespace?), but we could add to that.

**Comment by jeyemwey** [comment]
> I recommend the character set A-Z, a-z, 0-9, - and _ for nicknames.

Hi from everyone outside of the USA whose name isn't limited to these few characters (e.g. accents, umlauts, emojis, kyrillic and asian characters).

**Comment by Semisol** [comment]
> > I recommend the character set A-Z, a-z, 0-9, - and _ for nicknames.
> 
> Hi from everyone outside of the USA whose name isn't limited to these few characters (e.g. accents, umlauts, emojis, kyrillic and asian characters).

Understandable. I proposed above to add a regex instead.



> Most people aren't going to write their own regex, and I wouldn't want to ask them to. But I'm not opposed to internally stripping more characters that humans wouldn't use. Like I mentioned, we're already trimming whitespace characters (is ZWSP not seen as whitespace?), but we could add to that.

Advanced option? I would propose having a few presets "mostly everything", "basic ASCII", and a custom field, or just having a good preset that includes nearly if not all languages that can be changed later.

**Comment by gabek** [comment]
Yeah I think stripping special characters and having a blocklist of explicitly problematic characters internally makes a lot of sense. I'd rather it not be something people have to think about or worry about.  If it's worth blocking for one instance it's worth blocking for them all.

**Comment by gabek** [comment]
Not going to implement this.
