### ISSUE TITLE
Moderator badge always shows up

### ISSUE THREAD

**Issue by Semisol** [owncast/owncast#1543]
At the place where you have your nickname, the moderator badge is always shown.

**Comment by gabek** [comment]
It's highly suggested you run a release instead of the development branch. The development branch is always in development and is bleeding edge. If you want to build from source check out the `v0.0.10` tag.

This was already fixed yesterday in https://github.com/owncast/owncast/issues/1536, but these things will probably continue to come up if you deploy `develop`.  Unless you're helping test, in that case, your help is appreciated!

**Comment by Semisol** [comment]
I'm not deploying develop, I tried it once and saw that. But yep, I was just testing (and will continue).

**Comment by gabek** [comment]
Ok, cool!  We're not ready for real v.0.0.11 testing yet, however, there's still lots of work before it gets released, so active development will continue to take place.  Please don't be surprised if everything breaks in the develop branch between now and then. If you're testing the software for yourself I recommend using a release, but if you're helping out by testing new features you're in for a ride :)

**Comment by Semisol** [comment]
I have a non-develop instance for myself, but yep I was testing the progress on the newer version.

**Comment by Semisol** [comment]
> Ok, cool! We're not ready for real v.0.0.11 testing yet

How can I get notified when it is at least suitable enough that it won't break my personal server? I'm interested in the new features.

**Comment by gabek** [comment]
We usually announce when actual releases are available, but as far as the development process goes we don't try to make any guarantees about the state of things until then.  There's usually a time when pencils are down and I try to get people to test the upcoming release, and that's probably a good time. But even then the point of that testing period is to find and fix issues, so you might still get broken :)

But testing requests usually are announced in our Rocket.Chat if you're at all interested in lurking in there.  https://owncast.rocket.chat

<blockquote><img src="assets/favicon_512.png" width="48" align="right"><div><strong><a href="https://owncast.rocket.chat/">Owncast</a></strong></div></blockquote>

**Comment by Semisol** [comment]
> We usually announce when actual releases are available, but as far as the development process goes we don't try to make any guarantees about the state of things until then. There's usually a time when pencils are down and I try to get people to test the upcoming release, and that's probably a good time. But even then the point of that testing period is to find and fix issues, so you might still get broken :)

Yep thank you! I'll wait for the release, then.
