### ISSUE TITLE
Chromium fails to load, Firefox works fine, maybe some trusted-types issue

### ISSUE THREAD

**Issue by EdJoPaTo** [owncast/owncast#1545]
Chromium fails to open OwnCast, Firefox works without problems.
Chromium: `Version 96.0.4664.45 (Official Build) Arch Linux (64-bit)`

The Dev Tools Issue tab links the following issue: https://web.dev/trusted-types/?utm_source=devtools#fix-the-violations

This is the console log:

```plaintext
Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.
emoji-button.js:15 This document requires 'TrustedHTML' assignment.
(anonymous) @ emoji-button.js:15
wo @ emoji-button.js:15
(anonymous) @ emoji-button.js:15
get @ emoji-button.js:15
(anonymous) @ emoji-button.js:15
emoji-button.js:15  Uncaught TypeError: Failed to set the 'innerHTML' property on 'Element': This document requires 'TrustedHTML' assignment.
    at emoji-button.js:15
    at wo (emoji-button.js:15)
    at Object.<anonymous> (emoji-button.js:15)
    at Object.get (emoji-button.js:15)
    at emoji-button.js:15
(anonymous) @ emoji-button.js:15
wo @ emoji-button.js:15
(anonymous) @ emoji-button.js:15
get @ emoji-button.js:15
(anonymous) @ emoji-button.js:15
```

I don't know if this causes the problem or is only some other irrelevant issue here to the page not loading.
Opening the page results only in the blank loading screen with the big very low contrast icon. The normal view isnt even loading in Chromium. Firefox works fine.

The Issue title should be updated once we know more about the actual cause.

**Comment by gabek** [comment]
I just went and grabbed a stock version of Chromium to test, and it worked out of the box without any issues.  Are you running any extensions that might be blocking something or getting in the way?

![image](https://user-images.githubusercontent.com/414923/142490931-aa30ad61-dd36-4e2c-b42d-57bfb7967b97.png)

**Comment by EdJoPaTo** [comment]
I do not normally use chromium and installed it as a friend asked me why my stream isnt working. As I am using Firefox normally I had no problems before.

**Comment by EdJoPaTo** [comment]
Interestingly the https://watch.owncast.online instance works in Chromium, my own doesn't.

**Comment by gabek** [comment]
According to that link you shared it looks like "Trusted Types" is a part of the security policy header. Do you have a proxy in front that might be inserting that requirement?

**Comment by EdJoPaTo** [comment]
This is indeed the case, the CSP header [`require-trusted-types-for`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/require-trusted-types-for) was set which isnt yet supported by Firefox also explaining why it works there.

Removing it ends up working. Looks like I added and tested it before any browser actually supported it. Thanks for the help!
