### ISSUE TITLE
Single line chat layout

### ISSUE THREAD

**Issue by hollunder** [owncast/owncast#1559]
Hi there.
I find the default chat layout to take up excessive amounts of vertical space. In part that is because even a short message takes up two lines, one for the name, another for the message. Add to that padding and margins and every message takes up a lot of vertical space.

So this is an example of what my chat looks like. About ten messages, no more, and a fair part of them could fit on one line. ![vertical_space](https://user-images.githubusercontent.com/8207622/143507247-61fecaf6-18aa-46f3-a295-7f5b769d6750.png)

So instead of this:
![vertical_space_two_lines](https://user-images.githubusercontent.com/8207622/143507285-2cc09a3b-63aa-4a88-8c37-0be6ece7d0a6.png)
The same message could look like this (mock):
![vertical_space_one_line](https://user-images.githubusercontent.com/8207622/143507297-56953e94-dcb4-469c-a2c2-0afd93b0253d.png)

One could consider reducing the padding a bit as well, but I think this change would go a long way already.
What do you think?

I think this is the most relevant piece of code: https://github.com/owncast/owncast/blob/f6015dfe5030ad7562470c7cb74e830e4eae3bca/webroot/js/components/chat/chat-message-view.js#L99

**Comment by gabek** [comment]
I respect your style preference and I totally get where you're coming from. But in general I think what we have is working just fine. If there was an outpouring of people listing issues with it we should discuss it, but you're the only one to mention it. 

Also as it stands we rely on the styling of the messages to be what it is for the moderation actions, and would have to redesign that feature as well because of the change in the messages. So that all would be a lot of churn for zero real payoff.

I suggest you use the CSS feature to style the chat messages in any way you like. That way you can have it look how you'd prefer without limits.

**Comment by hollunder** [comment]
One CSS hack that seems to work OK (thanks Samuel).
```
.message-author, .message-text {
    display: inline;
}
```
Not tested wrt. admin interface.
This also has reduced padding.
![single_line](https://user-images.githubusercontent.com/8207622/143655988-0ab073a5-a050-4b76-93cb-3ad8723f4d13.png)

**Comment by gabek** [comment]
I'm curious why you consider CSS styling a "hack".  We added the ability to add CSS directly from the admin for this exact use case, so people can do whatever they want. I think this freedom and flexibility is way better than hoping every request gets baked directly into the software itself. This feature is built for people like you who want to customize things :)

**Comment by hollunder** [comment]
I mainly consider it a hack because it has not been tested with the moderator interface or applied via admin interface.
At this point I'm just a regular viewer of Hatnix' streams.

**Comment by gabek** [comment]
It would be cool to have a place where people can share their CSS tweaks so things like this can be more collaborative, but I'm not sure of a good way to do that without building a whole other site that would need to be manged.

**Comment by hollunder** [comment]
Maybe some sort of wiki would be good enough?
Hatnix shares his tweks in his Discord for now, but that's a bad place for things like that IMHO.

**Comment by hollunder** [comment]
It seems like that CSS change has no bearing on the moderation interface. Unless there is another one, but if so Hatnix doesn't know it.
![no_influence_on_moderation](https://user-images.githubusercontent.com/8207622/143721325-941580d7-47ef-4546-8571-fc5972146c33.png)

**Comment by gabek** [comment]
Oh sorry, that's not what I was referring to.  The inline moderation UI isn't released yet.  See here: https://github.com/owncast/owncast/pull/1331#issuecomment-948235352

**Comment by hollunder** [comment]
Oh yeah, that makes more sense.
As far as I can tell from looking at the code this change will place a flex styled div in between the name and message. My CSS fu is not strong enough that I'd dare predict what will happen to that when the two elements are styled inline. I guess we'll see when the time comes. Maybe it just works with the moderation div in between the name and text.

I guess making things inline is not great anyway when things are generally done using flexbox. Maybe there is is a nicer solution using flexbox, then we maybe be able to use the order property to move the moderation thing before the user name.
