### ISSUE TITLE
Do not perform username highlighting inside urls

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#156]
In this case I typed "http://gabekangas.com"

![image](https://user-images.githubusercontent.com/414923/93561181-987c7700-f938-11ea-8cdc-a04f7c09361a.png)

**Comment by gabek** [comment]
I cannot reproduce this.  I'm very confused.

![image](https://user-images.githubusercontent.com/414923/93656976-54927c00-f9e3-11ea-96a8-2a41848b972d.png)

**Comment by gabek** [comment]
HAH!  Figured it out.  It's only broken if you type in specifically the url gabekangas.com.

I know that sounds crazy.  But it makes more sense when you realize my username is "gabe" and we have string highlighting.  We need to not do username highlighting in urls.

**Comment by gabek** [comment]
This is actually a pretty specific edge case, where the url has to have your username in it.  Probably not something we should fix for 0.0.2 because I think it'll require reworking how we're doing linking and I'd rather not introduce regressions from that.

**Comment by gabek** [comment]
I'm thinking in order to fix this we might have to do the following:

Instead of running the string highlighter over the entire message as it does now:

1. Iterate over each DOM element in the message.
1. Run each element's `innerHTML` through the string highlighter.
1. Replace that plain text with a new child DOM element that has a new highlighted `span` element in it.

This all feels fragile, though.

**Comment by gingervitis** [comment]
Hmm I thought we only highlighted names if someone @'s your name while they write the message?
If not, should we just do that?

**Comment by gabek** [comment]
We highlight on `@name` and `name`.

Limiting to `@name` would make it significantly less likely to trigger the bug, but not impossible.  If somebody linked to http://something.org/@ginger it would still break.  And while I don't think there are circumstances where this type of url would be common, I could see jerks discovering this bug and spamming the chat with broken markup.  If it's broken we should fix it properly.

**Comment by gabek** [comment]
I was going to take care of this, but I figured this approach above is probably too complex, but I'm not sure what the simpler option is when dealing with DOM elements.  This is outside my wheelhouse :)

@mattdsteele do you have any thoughts of an elegant way to resolve this?  In short we highlight string `x`, but if `x` is a substring of an HTML tag then it breaks the tag.  It's a simple find and replace `x` right now.

**Comment by mattdsteele** [comment]
Like most modern JS developers I just lean on libraries. I've used this one in the past: https://markjs.io/

I'll see if it can be easily integrated!

**Comment by gabek** [comment]
I never even thought of looking elsewhere, good call!  Especially with something like this with lots of edge cases, pulling in something like this makes a lot of sense.  Thank you, Matt!
