### ISSUE TITLE
Text when composing chat messages is hard to read

### ISSUE THREAD

**Issue by hollunder** [owncast/owncast#1560]
The text when composing chat messages is very hard to read for me. There are two reasons:
1. The text is smaller than the regular chat text:
    `font-size: 12.25px;` due to `.text-sm 0.875rem`
versus
    `font-size: 16.1px;` due to `#chat-container .message 1.15em` and `.text-sm 0.875rem`.
2. The text is in grey on white and while it still technically has good contrast (6.68 AA), in combination with the small text size I find it hard to read.
![smol_grey_text](https://user-images.githubusercontent.com/8207622/143508144-b4676659-5486-4807-b76a-c4f744c60f83.png)

I would suggest to do at least one or both changes:
1. Increase text size to match the chat text
2. Change the text colour to something with more contrast, a darker grey or black.

**Comment by gabek** [comment]
That's totally fair, we can discuss bumping that up a bit. 

Also, like other things this can be styled via CSS and customized to look any way you like.

**Comment by hollunder** [comment]
I was looking at parts of the GUI last night that bother me as a user and that looked like easy changes.
Sure one can customise things via CSS but not everyone is able to do that and good defaults benefit every user at the same time.
Obviously for defaults to become defaults the developers need to agree with the change, hence these tickets.

**Comment by gabek** [comment]
Closing in favor of the redesign. #1859
