### ISSUE TITLE
Cursor when composing chat message appears on the right-hand side of the text field in Firefox

### ISSUE THREAD

**Issue by hollunder** [owncast/owncast#1561]
This is probably a bug, small but somewhat irritating.
The cursor initially appears on the right-hand side of the text field rather than on the left side.
![cursor_bug](https://user-images.githubusercontent.com/8207622/143508800-3f2cbec0-9e3a-4a6a-bac5-b1d5956e2c1d.png)
Once you start typing it behaves as expected.

**Comment by gabek** [comment]
What browser and OS are you seeing that on? I haven't seen that myself.

**Comment by hollunder** [comment]
Firefox 94.0.2 on Linux. At least another person in chat saw that too but I did not ask about browser version. I can do so tonight (UTC+1 here).

**Comment by gabek** [comment]
Ah that explains it, I don't use Firefox myself, so it's probably specific to that.

**Comment by hollunder** [comment]
Multiple Firefox users reported it is on the right.
A Edge Windows 10 user said: "Left, but in about one third at the right of the input field, my click is ignored."
I tried:
Chromium on Linux: left.
Falkon on Linux: left, but no Emoji picker shows up, different text as well (Not just "Message" like in FF).

**Comment by hollunder** [comment]
Silly bot, it's a bug, not a feature and at least on Hatnix' instance it is still there.

**Comment by le-fractal** [comment]
Hi, I did some investigating on this issue and found out something which might help:

If I **delete the local storage** for the site in the browser and then reload the page, **the cursor is correctly placed for the first message sent**. 
For any subsequent message, the cursor is at the far right of the input again (the local storage has been set again).

I could reproduce the steps on two different owncast instances.

**Comment by le-fractal** [comment]
A bit more info:

If the placeholder is emptied, the cursor snaps back to the left.

```css
#message-input:empty::before {
  content: "";
}
```
I think I'm stuck now, maybe this will help someone else!

**Comment by t1enne** [comment]
Apparently it's an issue firefox has with "contenteditable" elements. From my tests both localStorage being set and content being empty don't affect the problem. I found that setting "padding-right: 100%" fixes the issue in Firefox, but breaks the message-input on Chrome. All tests made on a debian.
Hope this helps!

**Comment by gabek** [comment]
Is there a standardized way to set CSS only for one browser?

**Comment by t1enne** [comment]
Found a more elegant solution with pos:absolute. Created a PR!
