### ISSUE TITLE
Option to disable join messages

### ISSUE THREAD

**Issue by hollunder** [owncast/owncast#1562]
We discussed this tonight in Hatnix' chat a bit and we would generally prefer not to see user join messages.
![join_message](https://user-images.githubusercontent.com/8207622/143508995-7818b114-0e60-4380-b95d-325e7302a67d.png)
Ideally there would be a toggle-able list of connected users, but that deserves a separate issue I think.

**Comment by gabek** [comment]
The one other person I've seen not want this message has hid it with CSS. 

Given that this is a pretty standard part of a chat system I don't see us wanting to remove it or adding more toggles to have people turn it off. But I do think customizing via CSS is the answer here. If there's a reason styling isn't sufficient please let me know.
