### ISSUE TITLE
People find the video player progress bar distracting

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#159]
If the player doesn't see you at what it determines is "live" then you get the progress bar jumping around as new segments get downloaded.

This video was sent me from the test stream last night saying it was distracting:
https://www.dropbox.com/s/js4j2b3tittgjhn/jumping.mp4?dl=0

I don't really see a point of showing this progress bar for live.  I know we discussed at one point giving the option to rewind, but in practice it's very uncommon and in many cases, not even possible (due to the the HLS playlist keeping references to very few segments).

If we can't just turn it off via a video.js option, then I think we should hide it via CSS.

**Comment by mattdsteele** [comment]
For my wedding's website, I used the `liveui: true` option VideoJS provides, and it worked pretty well.

Some docs: https://docs.videojs.com/tutorial-live.html

**Comment by gabek** [comment]
We are actually setting that as well.  But if somebody clicks on the progress bar (for some reason) and jumps a second or two in the past, then the progress bar will always be jumping around.  We should not let them jump into the past and get into this state.  Live or bust!  (Until recordings)

![Untitled](https://user-images.githubusercontent.com/414923/93723533-12d51300-fb54-11ea-909f-a502c4b94e45.gif)

**Comment by gabek** [comment]
Looks like we might be able to programmatically turn it of:

https://docs.videojs.com/docs/guides/components.html#progress-control

**Comment by mattdsteele** [comment]
Ah weird! Yeah I recall for my website I was able to turn it off entirely as well, but I don't think I had to do anything with progresscontrol; though that might be the better solution.

For what it's worth, here's my full videojs setup:

```html
      <video preload="auto" controls playsinline class="video-js"></video>
```

```js
const setupPlayer = () => {
  const video = document.querySelector('video');
  const videoSrc = 'https://stream1.steele-codr.wedding/hls/stream.m3u8';

  const player = videojs(video, {
    controls: true,
    autoplay: false,
    preload: 'auto',
    html5: {
      vhs: {
        enableLowInitialPlaylist: true,
      },
    },
    liveui: true,
    liveTracker: {
      trackingThreshold: 0,
      liveTolerance: 5,
    },
    fluid: true,
    fill: true,
    responsive: true,
  });
  player.src({ type: 'application/x-mpegURL', src: videoSrc });
};
```
