### ISSUE TITLE
Enable federation modal: Discuss the text and make sure it's very clear

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1594]
"Federation" doesn't make sense for most people, so we need to make sure it's 100% clear what it is, what it requires, and what features come from it.  Below is the first pass, but I want to go over this with different people and get input.

![image](https://user-images.githubusercontent.com/414923/146084415-dfcda290-24f9-46d4-8313-fe6cc91e8ae3.png)

**Comment by jeyemwey** [comment]
Can we add another button to the action bar? "I understand" does not sound fitting, I'd rather have a "I understand and want to continue" and a more visible "Abort/Cancel/Go back" button additionally to the `&times;` on the top right.

**Comment by gabek** [comment]
Yeah, I think more explicit buttons makes sense.

**Comment by gabek** [comment]
Larger idea, and not one I'm sold on, but want to mention it anyway.  Instead of using "Federation" everywhere, and trying to explain it, just simplify it by calling it "social" and referring to "social features".

On one hand I think we should try to evangelize the idea of the Fediverse and talk about what it is, federation. On the other hand it does sound scary to new comers and they might not turn it on because they're intimidated or confused.

As an example, Rocket.Chat has a "Federation" screen in their admin and I still don't know what it does and I sure wouldn't enable it.  I want to make sure we're better than that.  No offense, Rocket.Chat team :)

![image](https://user-images.githubusercontent.com/414923/146445257-367ef5c2-8ab9-4192-86a9-f8a751b3acfb.png)

**Comment by aaronpk** [comment]
I like that idea, also because "federation" often also refers to federated login like delegating to a company's OpenID Connect server

**Comment by gabek** [comment]
I guess I'm changing things to refer to "social". Though I'm concerned people might think it means Facebook, Twitter, etc.

**Comment by gabek** [comment]
It's a lot, but it tries to be clear and slightly educational, bridging the gap between the generic term "social" and the concrete "fediverse".

![image](https://user-images.githubusercontent.com/414923/147716896-63e383e0-ec7a-449d-a96b-51bc8fcd4cf4.png)

**Comment by gabek** [comment]
I'm going to close this. I'm sure we'll get more feedback in testing, and updates can take place as that happens.
