### ISSUE TITLE
Increase the max size of the chat welcome message

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1595]

**Comment by f35f0ef9d0e827dae86552d3899f78fc** [comment]
P'haps this be the place:

https://github.com/owncast/owncast-admin/blob/979f339b3cbbb029ffe81cfd02f26c5267843f25/utils/config-constants.tsx#L81

<blockquote><img src="https://opengraph.githubassets.com/714ba14e4419ba907e4268df9aed36a0fe52408e34e47fa4dd3a083ed9ef9ee9/owncast/owncast-admin" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/owncast/owncast-admin">owncast-admin/config-constants.tsx at 979f339b3cbbb029ffe81cfd02f26c5267843f25 · owncast/owncast-admin</a></strong></div><div>The admin web application for managing an Owncast server. - owncast-admin/config-constants.tsx at 979f339b3cbbb029ffe81cfd02f26c5267843f25 · owncast/owncast-admin</div></blockquote>

**Comment by gabek** [comment]
Indeed!

**Comment by f35f0ef9d0e827dae86552d3899f78fc** [comment]
You can assign me, then, and I will learn how you want pull requests to look.

`maxLength` makes me think character length, not word count.

That looks like this:
```
500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500 
```

How huge would be OK? 2,500?

**Comment by gabek** [comment]
Awesome! Yeah, it's character count.  Sure, 2,500 works for me. If people want a huge message, let them have it :)  This was requested by a streamer who wanted to add more links in the message, that includes markdown, so the characters go fast in that case.  Thank you!

**Comment by f35f0ef9d0e827dae86552d3899f78fc** [comment]
Alright, I put it here:
https://github.com/owncast/owncast-admin/pull/401
