### ISSUE TITLE
Disable the play button when first enter the stream

### ISSUE THREAD

**Issue by Zidichy** [owncast/owncast#1602]
Hi, would it be possible to disable the play button and have the stream just start as soon as someone enters the live stream instead of the users pressing play?

**Comment by aaronpk** [comment]
Browsers don't let arbitrary websites autoplay video with sound. The best you'd get is the stream playing with no sound, and it would require the user click the unmute button to hear it, which sounds like a worse experience to me than having the page load with the stream stopped.

**Comment by gabek** [comment]
Closing this for the reasons Aaron mentioned above. The play button is bigger than the mute button :)

**Comment by moira-lachesis** [comment]
"Browsers don't let arbitrary websites autoplay video with sound." - This is simply false. There is a vast range of behaviours, including just playing the video with sound, or the browser displaying their own play button. It can also depend on whether you are in an iframe or top-level. Furthermore, users may set their own behaviour in browser settings or add-ons. I've been using autoplay just fine on YT for ages and I have plenty of user feedback.

Please consider adding the option to skip this step, this will make it a lot easier to use on some scenarios.

**Comment by gabek** [comment]
There was a proposal in this thread https://github.com/owncast/owncast/pull/495#issuecomment-1435467159 but it seems like it wasn't good enough so it didn't go anywhere.
