### ISSUE TITLE
Create explicit "Donate" button next to "Follow"

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1605]
While we have offered a "donate" link as one of the available social options for some time, I wonder if people would find it nicer to add an explicit "Donate" button on the top level list of buttons next to "Follow" and the custom external actions.

People can create their own using the "External Actions" feature in the admin, but I do think maybe just having a text field where somebody can drop a link is easier for most people. We can then style the button uniquely to call it out as a donate button without the server admin having to worry about the styling as they would with a custom external action.

![image](https://user-images.githubusercontent.com/414923/146689840-73ce6493-e0d1-41d7-b90b-88fb3885c10e.png)

From branch `gek/activity-pub-1`

**Comment by deepto98** [comment]
@gabek I'd like to work on this, can you point me to the files I should look at?

**Comment by gabek** [comment]
This requires a design pass to decide how we'd want to do it, so unfortunately it's not ready to go in just yet.  Sorry about that!  I plan on bringing it up at our next Owncast call that looks like it'll be on the 17th.  You're welcome to join! https://doodle.com/poll/95ud2raip7grurkg

<blockquote><img src="https://cdn2.doodle.com/groups/favicon.65225a36fe566957b313.ico" width="48" align="right"></blockquote>

**Comment by gabek** [comment]
I'm going to close this feature idea, as I don't think it's a problem right now that people don't know how to create buttons themselves. The existing action buttons offer up functionality that would be duplicated here and in retrospect probably isn't required.
