### ISSUE TITLE
Create an admin text input that auto expands to fit the content

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1611]
Suggested in https://github.com/owncast/owncast-admin/pull/401#issuecomment-998903521.

Would be useful for text fields that can have a highly dynamic amount of content.

@f35f0ef9d0e827dae86552d3899f78fc mentioned they'd be interested in looking at this.

**Comment by f35f0ef9d0e827dae86552d3899f78fc** [comment]
I'm still planning to look into this even though I forgot about it for a few days. My friends and I have been having too much fun in a new PC game we got recently. Just wanted to say I'm still "here."

**Comment by gabek** [comment]
Seems with the correct parameter we already have an expanding text field. Closing.

![image](https://user-images.githubusercontent.com/414923/149469411-8df826f1-bf7b-44b9-b2c2-40512e64b3c8.png)
