### ISSUE TITLE
Feature Request: Optional User-Name Registration with a self-signed Certificate

### ISSUE THREAD

**Issue by 0lhi** [owncast/owncast#1647]
Mumble allows to join Voice-Chats without registration, but a registration is possible with a single click:

>No Password Set, Certificate in Client
>
>If a client is registered to a user name by another user (or themselves, if privileges allow) from inside the Mumble client (by right clicking on the user, or themselves, and clicking "Register"), the account is created with no password but the certificate is connected to that account and only a user with that certificate will be able to connect as that user. This is probably the most common case, especially if no external user management is being used.
>
>If no password is set, and the user connects from a Mumble installation that does not have their matching certificate, they will not be able to use that account. See below.
>
>https://wiki.mumble.info/wiki/Authentication
>
The same certificate is used across every Server, and can be exported & imported to other Mumble Clients.

This approach could be tremendously beneficial to Owncast as well. It would give Users a quick way to gain unambigious identifiability. And Streamers could get more security if they can configure whether Chatters have to be registered, and for how long. Ideally, this can be changed on the fly so it can be enabled mid-stream when a Troll attack occurs.

Perhaps the Owncast Browser Extention could provide a way to import/export the certificate, which can then be conveniently stored inside a Password Manager such as KeePass.

How do you feel about this approach? Speaking for myself, this would instantly erase every doubt I have about the Owncast Chat.

**Comment by aaronpk** [comment]
The browser's client certificate UI for this has always been horrible, I would not recommend doing this. Here's what happens in Chrome:

![image](https://user-images.githubusercontent.com/113001/148460656-df3aca24-82a0-4723-a0e2-6eaac041d1fc.png)

You're prompted to choose a list of certificates, and I don't even know where most of those came from. The user would have to know which one to choose and why, and also have to have a way to create and manage them.

There's already a good plan in place for improving the chat identity system: https://github.com/owncast/owncast/discussions/440

There's also a recent PR merged that would let you handle user authentication at the web server layer however you want, opening yourself up to a million different possibilities for how to handle it in a way that makes sense for your viewers without needing to modify OwnCast at all. https://github.com/owncast/owncast/pull/1633

**Comment by 0lhi** [comment]
I didn't suggest using the Browser's Certificate UI.

**Comment by aaronpk** [comment]
I'm not sure what you're suggesting then. But take a look at the change in #1633 because that will let you do whatever you want at your web server for user authentication! I'm planning on using that to integrate an instance with a website where people already have user accounts so they'll automatically be logged in to the chat with the same username they have on the main site!
