### ISSUE TITLE
Hiding duplicate video element conflicts with Video Speed Controller extension

### ISSUE THREAD

**Issue by mattdsteele** [owncast/owncast#165]
When running a new Owncast instance I noticed my streams were only getting audio, but no video was appearing.

This was happening across most of my devices (Windows, ChromeOS) and browsers (Edge, Firefox, Chrome); though Safari on iOS was OK.

Running a bisect I see the blank screen began with this commit:

https://github.com/owncast/owncast/commit/206d57e79ef419da6562bca9ae3c3dc120116594

It appears this is conflicting with a browser extension I install almost everywhere 🙃 In particular, the Video Speed Controller extension ([Chrome](https://github.com/igrigorik/videospeed), [Firefox](https://github.com/codebicycle/videospeed)) adds a `.vsc-controller` wrapper to `<video>` elements to let you change their playback speed.

As such, the `.vjs-tech:not(:first-child)` ends up selecting the actual video element:

![image](https://user-images.githubusercontent.com/389077/93713577-7c3c2e00-fb22-11ea-9f0c-f424dd9e4135.png)

This is in comparison to when the extension is disabled:

![image](https://user-images.githubusercontent.com/389077/93713703-303db900-fb23-11ea-9af9-f168678dbfc3.png)

I'd update the selector, but I haven't seen the original issue @gingervitis worked around, so I'm hesitant to hack a hack 😬  Is it a second `<video>` element on the screen we're looking to hide?

**Comment by gingervitis** [comment]
Crazy. I can't repro the original issue anymore when commenting out that hack. 🤯 

So originally, at some smaller screen layouts, I would see a secondary `<video id="video_html5_api"..>` tag get embedded at the end of `<div id="video">`. It had no src.  
``` 
<video class="vjs-tech" id="video_html5_api" preload="auto" playsinline="playsinline" tabindex="-1"></video>```



<img width="590" alt="image" src="https://user-images.githubusercontent.com/9563255/93717187-f7084780-fb28-11ea-910a-f0a9fa5c1ae3.png">

It would just sit there and take up space, so the main video would often look squished/short, within the <main> container.  I wasn't sure why this second video was getting created at small screens.  But I can't seem to repro at the moment.

**Comment by mattdsteele** [comment]
Ah interesting, thanks for the context!

If the flaky video element was lacking a `src` attribute could we use `.vjs-tech:not([src])`, or similar selector? Or if you think the issue's fixed itself, we could remove it entirely?

**Comment by gabek** [comment]
It's possible it was a bug with video.js that has since been fixed with a recent update.  I couldn't find anything in their release notes that point to such a thing, but you never know.

**Comment by gingervitis** [comment]
Yeah let me try it out a few more times when I get back later today. Then I'll remove it if I can no longer repro.

**Comment by gingervitis** [comment]
Ah ha! found it .. happens on iOS Safari.
Right now I can only repro on Mac Safari's "Responsive Design Mode", simulating with the iPad mini iOS13.1.3.  Though I'm pretty sure I saw this happening on actual iPhones. This may have been a more prevalent issue when everything was iOS13, and no longer with iOS14. 

<img width="540" alt="image" src="https://user-images.githubusercontent.com/9563255/93723510-ddc8c080-fb53-11ea-9a15-89b76cb4ebf5.png">

<img width="676" alt="image" src="https://user-images.githubusercontent.com/9563255/93723535-15376d00-fb54-11ea-947b-6f566d3d5ae1.png">

Looks like I can also repro in Chrome Dev tools with UA set to some old iOS Safari version as well such as
```
Mozilla/5.0 (iPad; CPU OS 11_0 like Mac OS X) AppleWebKit/604.1.34 (KHTML, like Gecko) Version/11.0 Mobile/15A5341f Safari/604.1```

**Comment by gingervitis** [comment]
I think for now I'll just update our code to use your suggested `.vjs-tech:not([src])` trick to work around this for now.  Thanks @mattdsteele  for your interesting use case!

**Comment by mattdsteele** [comment]
Just updated my server and it's working great with the extension enabled. Thanks! 🎉
