### ISSUE TITLE
Web push notifications

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1656]
I know everyone says no to these, but I'm thinking if we added a YouTube style "ring the bell to be notified" contextual action button people might say yes to being notified when the stream goes live, just like how people install the Owncast browser extension. Except this would be for a single stream, and for people who don't want, or isn't familiar with the browser extension.

**Comment by aaronpk** [comment]
I love this idea, I know people who have asked for web push notifications even for my youtube streams. I 100% agree it should only prompt the user after the user requests notifications rather than all those spammy news sites that pop that up as soon as you visit them.

**Comment by gabek** [comment]
Hopefully we can get this into v0.0.12 if we can come up with a design for the notification modal. The design of this modal is the difference between "Yes I want to be notified" and "No Owncast sucks stop asking to spam me like those other sites", so we need to do it right.
