### ISSUE TITLE
Build testing infrastructure around HLS spec conformance + encoding performance

### ISSUE THREAD

**Issue by ogmkp** [owncast/owncast#1657]
Hi and thank you for this great project.

I set up my server to serve 4 streams, but ffmpeg slows down considerably while the CPU goes up between 2.9 ~ 3.2 of load.
If I run ffmpeg by myself on the same machine along owncast, I get a good fps rate because CPU remains free usage while transcoder.log averages 30 ~ 35 fps who results of a terrible HLS lagging and cuts.
Do you have any idea?

Owncast v0.0.10

[owncast-ffmpeg-slow-hls.log](https://github.com/owncast/owncast/files/7834760/owncast-ffmpeg-slow-hls.log)

![Capture du 2022-01-09 10-20-33](https://user-images.githubusercontent.com/17526713/148676711-1216c4d7-0632-40a5-a85a-14e3eaa5eb07.png)

Thank you.

**Comment by ogmkp** [comment]
If I remove 1080p60 6 Mbps, I get 60 fps on all others streams (720p60, 480p60, 240p60) and don't know why.
All presets uses the lowest CPU utilization profile.

I can see that lowest and highest CPU utilization bar use same "superfast" x264 profile.
And low, medium uses "Faster" preset who is much complexified than highest.

**Comment by ogmkp** [comment]
https://emby.media/community/index.php?/topic/52686-ffmpeg-only-using-75-of-cpu-when-transcoding/

From a user of emby product who encounter same problem, remove -maxrate and/or -bufsize makes better fps at the end of the ffmpeg chain.

Is it possible to find a workarround before more investigation ?

<blockquote><div><img src="https://emby.media/community/uploads/monthly_2020_11/android-chrome-512x512.png" height="14"> Emby Community</div><div><strong><a href="https://emby.media/community/index.php?/topic/52686-ffmpeg-only-using-75-of-cpu-when-transcoding/">FFmpeg only using 75% of CPU when Transcoding</a></strong></div><div>Transcoding only uses 75% of the CPU, only 7 out of 8 threads. Processor: i7-2600 @ 3.8 GHz Transcoding log: Application version: 3.2.36.2 http://192.168.0.3:40330/emby/videos/418d80970834ea0588c1bb0697edb255/hls1/main/0.ts?DeviceId=0f646ede5a6cee1566fe5433befcb07c53005e86&MediaSourceId=418d8...</div></blockquote>

**Comment by gabek** [comment]
It's not surprising removing those parameters would ease up some of the CPU use, it would be less strict about the video compression. Less compression taking place means less CPU being used.

Without these values the bitrate will exceed the thresholds in the HLS specifications as outlined by Apple.

I know CPU use is important, but having a stream that exceeds the bitrate it reports could lead to video that's not playable at all for some people.

I'll hijack this issue and make it a TODO to automate some future tests to compare fps/cpu vs. specification adherence for different settings. Maybe if I put together some tooling I can improve the performance. Maybe not, but it's worth having.

**Comment by ogmkp** [comment]
Is it normal that ffmpeg does not use all the CPU capacity to satisfy the fps demand?
Because, it uses only 380% maximum on 800% and it drags at 29 ~ 32 fps while I require 60 fps.
There's a bottleneck at the half usage of the whole cpu.

**Comment by ogmkp** [comment]
Hi @gabek , do you think you can find a workaround for this ffmpeg bottleneck at half cpu?

**Comment by ogmkp** [comment]
After many tests, it's better to run several ffmpeg processes for each encoding rather than asking it to manage one string. I'm closing this ticket.
