### ISSUE TITLE
Limit "external site requested your logo" warning message

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1668]
This logs every time it's requested, and it's annoying. I guess limiting it to just the first time is fine.

> an external site requested your logo. because many social networks do not support SVGs we returned a placeholder instead. change your current logo "logo.svg" to a png or jpeg to be most compatible with external social networking sites.

**Comment by aaronpk** [comment]
Might actually be helpful to add this to the social tab in the admin UI too, since not everyone is going to be looking at their logs.

**Comment by gabek** [comment]
We don't currently have any way to label or query for logs of a specific category (social only, for example).  The real answer is to stop letting people use SVGs as their logo image, but that would make me sad.  So this was the compromise.

**Comment by aaronpk** [comment]
oh I was just thinking more along the lines of the admin UI testing whether the logo was an SVG and showing a notice on the social page, not tying into the logging system
