### ISSUE TITLE
Modal is too small on mobile

### ISSUE THREAD

**Issue by jeyemwey** [owncast/owncast#1669]
See this screenshot:

![Screenshot_20220114-011129.png](https://user-images.githubusercontent.com/2796271/149428996-3cb399af-2edb-4ae4-9da6-1388ff577110.png)

Also, when you tap into a text input, the viewport gets smaller and reaches over the sides. When attempting to scroll, the info area scrolls.

I'm testing with Android and a recent Chromium, not sure how this behaves on iPhones

**Comment by gabek** [comment]
Updated title to reflect that it's not an iframe.

**Comment by gabek** [comment]
Hopefully increasing the width fixed it for you. Looks ok for me.
![image](https://user-images.githubusercontent.com/414923/149452512-27ae633f-88b7-4326-bc81-bbae2507dfd5.png)
