### ISSUE TITLE
Join us to chat and sync-up about Owncast.

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#167]
Hey, all!  This is a longish message that came out of a conversation we had Thursday.

To begin with, I had a great time chatting with @graywolf336, @geekgonecrazy and @gingervitis the other day.  We didn't really plan to have a more encompassing "team call", but to everyone else that didn't get notified, we'd love to have you join us if you'd like to next week.  We talked high level about the project, and wanted to detail a list of different potential goals we can focus on in the near-ish term.

## Owncast sync this week

This Thursday, the 24th, [3pm Pacific, 5pm Central](https://www.worldtimebuddy.com/?qm=1&lid=5391959,6,100&h=100&date=2020-9-19&sln=22-23) we'll be chatting again.  So @mattdsteele, @jeyemwey join us if you're interested and you're free.  I created this little link on Eventolist to have an easy way to download an ics. Hopefully that's usable and puts it in your local timezone. https://www.eventolist.com/e/DCFFIO5BLK1L8LDH05ZA.
Meeting Link: https://meet.jit.si/owncast-discovery-meeting

Actionable things I'd like to discuss this week

1. How can we plan for, and leverage Hacktoberfest? (#161)
2. Releasing [0.0.2](https://github.com/owncast/owncast/milestone/2).
3. Spinning up demo instances.
4. Beginning the admin site project. (#114)
5. Discussing the current approach to the directory's YP API. (Low priority background work)

## Goals

As far as goals, I split things into four categories: The **core project**, **awareness + adoption**, **broadcaster community + engagement**, and what's needed to offer a **hosted solution**.  Luckily I believe many of these go hand-in-hand.  This is not encompassing, but hopefully it'll get everyone thinking about what direction and features they'd like to see.

Some of these items I've already been splitting up into the [release milestones](https://github.com/owncast/owncast/milestones) in Github issues.  As some things have dependencies on others, spitting features up in this way seems to make sense.  I encourage you to take a look.

## Core Project

These are the things that I believe are requirements for the project itself to be useful to a wide variety of people, fulfilling the initial vision.

### Web admin (#114)

Have a read-only page for operators to see how their instance is configured and the status of it.  The second step is allowing configuration changes through this admin site, while things like managing recordings, chat moderation, etc will be added as well.

### Recordings (#102)

People expect to have recordings as as core functionality for them.  It has a direct dependency on the web admin as being able to delete, hide, and edit metadata of your recordings will be required.

For the initial version of recordings I don't think we will have chat integration, but for future updates I can see us wanting to replay the chat history synchronized with the video.

I can start documenting some of the specifics around this so we can discuss the pieces in play, because it touches a lot.  So hopefully soon we can break it into actionable chunks of work.

### Scheduled events (#150)

This is useful with both the specific use case that Bradley outlined in his original proposal, but also as engagement between broadcasters and viewers.

Much like recordings, this is a feature that would touch many pieces, so hopefully soon we can break this feature into chunks of work post-initial admin site.

## Awareness and adoption

These are the things that help clarify to people what the goals of the project are, how it can be useful to them, and reduce the number of reasons people may not be interested in trying it.

### Owncast instance directory (#142)

There are two camps of people who live stream: Those who have an audience (conferences, churches, businesses) and those looking to build an audience (hobbyists, people in the arts, performers, online personalities).  For the later crowd a bare minimum answer to the question "how will people discover my content?" is required.  So it really solves two problems: It clarifies what the project is by offering a wide variety of instances for people to visit, and it supports broadcasters looking to increase their reach.  The downside of this directory is it'll be empty until there are more instances.  I have a WIP I've been playing with here and there at https://owncast-web-test.gabek.vercel.app/ and the project (frontend and backend) lives in https://github.com/owncast/owncast-yp.  It'll need polish, but I'll continue getting it functional.

### Demo instance(s)

We don't currently have any instances of Owncast running that people can actively check out.  A 24/7 instance that's streaming some kind of accessible content (like public domain cartoons or or a recording of a previous stream), while not *exactly* like a live stream, since the content isn't live, will give people a feel for it.  I'm also not above having fake chat messages scroll by so people can get the feel of activity.  A secondary benefit of running instances ourselves is it'll start populating the directory, as well.

## Broadcaster community and engagement 

This is a category I don't know how deep, if at all, we want to dive into.  If people look at Owncast as an alternative to Facebook Live, Twitch, YouTube live, etc then there's certain things that people expect. 

### Following & Notifications

Allowing people to "follow" an instance, and get notified of every time a live stream begins would increase the engagement of each individual instance.  This is something that people expect coming from the more social streaming world.  Also, with the future ability to schedule live events (as mentioned above #150) it gives more engagement points when reaching out to viewers (Example: "Only three more hours until wedding/service/party/etc!")

### Monetization

While I believe it's out of scope for this project, it's something to keep in mind that monetization of live streams is really big right now.  And while I don't think we should build a twitch-level payment platform, there may be a middle ground we can find to have built-in linking to existing payment processors, bitcoin, etc.

### Near-term

Instead of a custom infrastructure and deployment solution I propose when we're at the place where we can offer "hosted" for a select few people we just spin up, manually, standalone instances, and run it for them, likely free of charge.  This solution doesn't scale, but for an early experiment we could probably learn a lot from this simple setup.

### Configuration/Data management

- Use a real database server instead of of SQLite for hosted customers.  Our config can probably be expanded upon to support different DSNs.

- Use a database instead of the file system for config, stats, and other misc persisted values. A perfect world scenario would allow for standalone instances to use a config file + sqlite and hosted customers to be completely database driven to allow for scalability and flexible deployment.

- Statically assign a set of default video variants that each customer gets instead of allowing people to worry about and customize it. High, medium and low. 

- We already support external storage of video segments, so we could probably just use a single bucket for bulk storage of video segments (depending on security concerns of such things).

- Chat moderation may be a must-have since hosted customers will be less technical and won’t be taking on the risk themselves.  As a hosting provider we'll be taking on the risk and responsibility of reducing harassment and other possible unwanted chat content.

### Deployment

- Deployment architecture that spins up an instance and knows where to find the config and transcoders for that user. 

- Scalable transcoders that are decoupled from the standalone instance. The web UI and APIs are lightweight and many can be run on a single machine in comparison to the work needed to transcode the video.

**Comment by jeyemwey** [comment]
3pm Pacific is midnight in Central Europe, so I'm not sure if I can make it. But I will try!

**Comment by mattdsteele** [comment]
Yeah I'm in!

**Comment by gabek** [comment]
Looking forward to chatting with you all tomorrow!

**Comment by gabek** [comment]
I'm not sure when is good for everyone else, but to be a bit kinder to @jeyemwey, what earlier time works for all of you next week?  I'm currently pretty flexible.  Can we bump it back maybe a couple hours so he's not up at midnight? :)

**Comment by jeyemwey** [comment]
8pm UTC / 1pm Pacific / 10pm CEST would be great for me, if that is possible.

**Comment by gingervitis** [comment]
Are weekends an option?

**Comment by gabek** [comment]
They work for me.

**Comment by graywolf336** [comment]
Weekends are an option, although generally would have to be on Saturdays or a short time window on Sundays. Usually around 2pm to 4pm, Sundays are one of my busiest days off a computer.

**Comment by gingervitis** [comment]
I won't be able to consistently make our current Thursday afternoon times. 
Sundays are pretty busy for me as well.

I would also be open to doing a Tues or Thurs mornings before 10am Pacific / 12pm CT / 5pm UTC.
I can also make Saturdays work.

**Comment by gabek** [comment]
Not sure if this poll thing is useful (or even if it works at all!) but I'm willing to try it.

Mark your availability!  https://doodle.com/poll/pes8tfa2u6dn8epw

**Comment by gabek** [comment]
Date selected, thanks!

### [This Thursday, 9:30am Pacific, 4:30pm UTC](https://www.worldtimebuddy.com/?qm=1&lid=5391959,6,100&h=100&date=2020-10-1&sln=16.5-17.5)

We'll chat about the following:

* Admin backend work is moving forward.  Frontend stuff will start soon.  Probably not much to need to discuss there.
* Broadcasting demo site.  Clarify how we want the stream key rotation to work.  #182 
* Javascript dependencies.  It's come up a couple times now that people aren't comfortable with external sourcing, plus it slows down loading of the site.   How do we move forward and resolve this?  #189 
* Are there small, non-technical/non-feature related things we can start on now as background work to help us get to a hosted Owncast offering?  Product/feature related things are all being worked on, but what about other categories of work that needs to be accomplished in order to offer things to people as a service?
* Discuss releases and testing (manual & automated).  Due to a human error on my part we had a bug that went unseen in the 0.0.2 release.

**Comment by mattdsteele** [comment]
Sorry folks, I got pulled into a work meeting this morning and won’t be able to attend.

**Comment by gabek** [comment]
## Let's sync-up next week (Week of Oct 19)

Mark your availability here: https://doodle.com/poll/phmk4pyw87d8xwvt

@mattdsteele @geekgonecrazy @gingervitis @graywolf336 @jeyemwey 
@jmhobbs If you're interested, join us!  Anybody else who sees this and is interested you're invited too!

Some topics:

1. The road to [0.0.3](https://github.com/owncast/owncast/milestone/3).
1. The status of the admin project.
1. Planning for [0.0.4](https://github.com/owncast/owncast/milestone/4) and a read/write, persistent data store.  Start to discuss the proposed approach, how to migrate to it, how much of it we want to move at once, and what functionality we need to make that happen.
1. The status of the [YP project](https://directory.owncast.online).
1. Continued background planning on what we can accomplish now to move us closer to a hosted solution.  Let's come up with one actionable item we can work towards.
1. Discuss how people are discovering Owncast.  Can we leverage this and learn anything from it?  Can we get feedback from any of these people?

**Comment by gabek** [comment]
Date and time set!  [Thurs Oct 22 9:15 AM](https://www.worldtimebuddy.com/?qm=1&lid=5391959,6,100&h=5391959&date=2020-10-22&sln=9.25-10.25)

Looking forward to chatting with you all soon!  https://meet.jit.si/owncast-discovery-meeting

See above for some topics we can go over, and bring your own.

**Comment by gabek** [comment]
Recap of some of the things from the call:

* @bitspill and @jmhobbs joined us!
* @bitspill let us know that Owncast doesn't work on Windows.
* @jmhobbs is experimenting with Go Plugins.  But it turns out they don't work on Windows either :)
* The admin project is moving forward.  There's a layout, and charts, and tables.
* Figuring out continued decoupling of the video pipeline from the Owncast instance is the next big step in being able to support a hosted architecture.  We need a transcoder instance to be able to save video without passing it back to the lightweight owncast (web, chat) instance, but owncast will still need to know where to find the HLS stream.  I have some ideas I'll write up that we can discuss.
* @jeyemwey is going to see if he can get the YP project running and help with the frontend.
* I've been working on the persistent config framework and it should be ready to go once we have our first read/write config functionality.

If I missed anything that we chatted about, please post!

**Comment by gabek** [comment]
Closing, as next time we schedule a sync-up we can do it over on our Discussions https://github.com/owncast/owncast/discussions.
