### ISSUE TITLE
Setting stream key by hand leaves /admin unprotected

### ISSUE THREAD

**Issue by AlessandroPomponio** [owncast/owncast#1670]
Hello everyone!

In my tests it appears that if I set the stream key by hand, Owncast doesn't log me out and stops asking for the password when navigating to the /admin endpoint, leaving everything unprotected. Making Owncast generate a new stream key does instead seem to work as expected.

I'm on Owncast v0.0.10.

**Comment by AlessandroPomponio** [comment]
Actually, I seem to be getting the same error even when generating the stream key automatically, but only sometimes, not always

**Comment by gabek** [comment]
It is indeed blocking access from future admin requests after you change the key as seen in the screenshot below:

![image](https://user-images.githubusercontent.com/414923/149655442-ba74dd27-245c-4391-9f0d-229bed80d555.png)

Past admin requests, obviously, the data is already made available to you.

You saying the admin is "unprotected" makes it sound like anybody can access it, that is absolutely not true.

**Comment by AlessandroPomponio** [comment]
Unfortunately that is indeed the case in my installation: I can still access it using Incognito mode and when I asked other friends of mine to go to my endpoint, they were able to access it too without authentication. The same thing was happening with 0.0.8 for me, unfortunately.

**Comment by gabek** [comment]
I'm unable to reproduce this. The admin still requires me to log in with the new key when trying to access it in a private window.

![admin-key-change](https://user-images.githubusercontent.com/414923/149655670-4c6c9c4d-d521-4400-a76f-37d5a2d792f9.gif)

**Comment by AlessandroPomponio** [comment]
It seems to be something that only happens every now and again in my case: do you mind if I share a screen recording with you using the email in your profile, so that I don't have to blur all the details?

EDIT: I sent the email

**Comment by gabek** [comment]
You mentioned in your email "I would think it could have been a session issue in the reverse-proxy (Caddy, in my case)". Could you perform testing without Caddy or any other software in the way?  Given nobody else has seen this before, and I can't reproduce it it makes sense to figure out why you're seeing it, and only sometimes.

**Comment by AlessandroPomponio** [comment]
I attempted to reproduce the issue once more now and it doesn't seem to be happening again - neither via reverse proxy nor via ssh tunneling. I will close the issue and re-open it again with more information in case it happens again.

Thanks a lot for the work you've been doing!
