### ISSUE TITLE
Document playlist file in the Embed Documentation

### ISSUE THREAD

**Issue by ClundXIII** [owncast/owncast#1671]
Hello,

we are trying to embed a stream into an OpenSlides conference. Unfortunately OpenSlides does not simply use an iframe and instead tries to play the video by itself.
`VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media.`

https://support.openslides.com/help/en-gb/4-stream-liveconference/76-embed-a-stream-without-linked-video-conference

Is there any way this could be made compatible by owncast?

**Comment by ClundXIII** [comment]
Okay, I did found the solution. Correct me, if I am wrong, but 
`https://<url>/hls/stream.m3u8` should be the correct link to use.

**Comment by jeyemwey** [comment]
That's the correct link, I'm glad you could help yourself.

For all other users, it might be helpful to describe the stream master playlist in the Embed URL at https://owncast.online/docs/embed/ . Let me hijack your issue so someone can work on it.

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="/favicon.png" height="14"> Owncast</div><div><strong><a href="/docs/embed/">Embedding into your site</a></strong></div><div>You can easily embed your chat or video into another site.</div></blockquote>

**Comment by ClundXIII** [comment]
Another thing I noticed:

`/embed/video` does not report the CORS origin `*`, the url it redirects to (`/index-video-only.html`) however does have the correct header. This was really confusing when trying to add the header myself in nginx and suddenly ended up with 2 header.

(Should I open a new issue for that?)

**Comment by jeyemwey** [comment]
Yes, please open another issue for this. We will then be able to come back to it more easily.

**Comment by gabek** [comment]
0.0.11 no longer redirects to the HTML files, hopefully it's simplified for your particular use case.

**Comment by ClundXIII** [comment]
oups, just created the issue

https://github.com/owncast/owncast/issues/1672

I guess you can just close it in that case.
