### ISSUE TITLE
Make the reason for federation hindrance more visible

### ISSUE THREAD

**Issue by jeyemwey** [owncast/owncast#1673]
If my instance isn't published via SSL, I cannot activate federation. The switch is disabled -- so I cannot click on it -- but to an average user who doesn't read the documentation, that's a dead end.

![image](https://user-images.githubusercontent.com/2796271/149838355-35a61208-8138-4a24-9069-c2786c1c6b95.png)

A simple fix would be to have a status message indicating that Activity Pub requires SSL and maybe link to the documentation.

**Comment by gabek** [comment]
Moved things around and added a warning. It then hides this setting once you set it to discourage you from changing it. It should help.

![image](https://user-images.githubusercontent.com/414923/149868130-eb0e453a-4818-4c80-9fd5-8430a2d211e8.png)
