### ISSUE TITLE
Wording: Make more clear who "user" is

### ISSUE THREAD

**Issue by jeyemwey** [owncast/owncast#1674]
Just a small one for the Federation Activation prompt:

IMO "follower" is a better word here than "user" since it's not clear what a user is in this case (and I can only guess that it's about the user-account `something@some.host` on the fediverse?). It's less about the user not being here anymore and more about losing the followers that have followed the instance.

![image](https://user-images.githubusercontent.com/2796271/149839025-fa707983-4c91-48e6-9e35-81ed15e9d2bd.png)

**Comment by gabek** [comment]
"User" in this case means the Fediverse representation of the Owncast server. "Follower" to me means the other person, the human, not the server, so I guess it's confusing from both sides.

**Comment by nebunez** [comment]
I suggest changing the wording to

- You should not change your server name URL or social username once people begin following you, as ~you~ _your server_ will be seen as a completely different user on the Fediverse, and the old user will disappear

**Comment by gabek** [comment]
Works for me.
