### ISSUE TITLE
Outbound email notifications

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1685]
Email, while not a perfect way to contact people, exists, and it works for many.  Plus people get it anywhere they are, so my dream of "let me know when X starts streaming, even when I'm not at my computer" helps with this.

As a bonus, it would allow streamers to optionally send out newsletters or their schedule for the week.  Something I think would be very cool.

## Requirements

- We don't store the email addresses 
- A single newsletter provider with a free tier must be selected
- This provider must have a good API we can use
- This provider is GDPR compliant and handles opt-in and unsubscribe logic
- We add email support to the notify modal on the fronend

**Comment by gabek** [comment]
So I'm thinking I'll split this into two different things:

1. Add unopinionated generic SMTP settings with a target email address that Owncast can send an email to.
2. Add a specific service for the act of collecting email addresses to a list and a target email address that delivers to the emails that were added.

So if you have your own mailing list and SMTP server you can just use it and do whatever you want. Otherwise use the integration.

**Comment by gabek** [comment]
Because I'm allowing generic outbound email support I can no longer rely on an email provider to require double opt-in before adding to an email list. Mailjet, for example, does not. So I'm building it myself. Not a huge lift, since I already have outbound email via SMTP working. And with that I can sleep a little better knowing Owncast isn't being used to arbitrarily add people to notification lists without confirmation.

**Comment by quilime** [comment]
Really like this idea! I've been using [listmonk](https://listmonk.app/) alongside owncast to send out stream notifications. It works great. It would be so convenient to send updates without writing custom scripts/hooks.

**Comment by gabek** [comment]
The catch is _adding_ people to the lists. That's where the custom part comes in that you'll still have to manage in some way.

**Comment by gabek** [comment]
I'm having a hard time working through the logistics of email notifications.

I built it using Mailjet as an email list provider that will create email lists, handle unsubscribing, etc.  However, I know not everyone will want to use Mailjet, and that's fine, I have no preference.  So instead I abstracted email support out into basic SMTP delivery. You put in your email server, credentials, and email address of an email list, and Owncast will send it out.  I even built out double-opt in support because if Owncast is using some random SMTP server instead of an email list service it needs to take care of the opt-in verification.

But then the question is, how does the remote email list get populated?  When using Mailjet Owncast can use its APIs to add new people to a Mailjet email list, but if it's "generic email", there's no way to do that.

So I'm not really sure how to move forward. I can launch with Mailjet-only support, but I'm _sure_ that will upset people and make it look like I have some kind of partnership with them and nobody will use the feature.

**Comment by gabek** [comment]
For the record, my dream way this would work is:

1. UI pops up prompting for them to put in their email address.
2. Address is sent to the Owncast backend.
3. Backend hands it to some kind of plugin that's built specifically for whatever email system the streamer uses (Mailjet, Mailchimp, listmonk, majordomo, etc Owncast doesn't care).
4. That email system is now responsible for adding the email to a list and confirming it.
5. When Owncast wants to send out an email it sends a single email via standard SMTP to `list@provider`.

But there are drawbacks to this too.

1. Nobody is going to build plugins for mail providers.
2. Not all mail list providers support sending emails via SMTP, instead they require use of their proprietary API.

**Comment by gabek** [comment]
Removed this from the milestone and just going to table it, since I don't currently have answers for the above.

**Comment by gabek** [comment]
Closing this as I've been unable to resolve the above issues to make email notifications work. I'd really love to have them, but there's too many issues.
