### ISSUE TITLE
Hopin Classic Backstage

### ISSUE THREAD

**Issue by srees** [owncast/owncast#1693]
Well, not sure it is fair to have this as an issue since it is hard to test!

I can stream to my OwnCast server using OBS from a remote location, but cannot stream to it using a service called Hopin. Their 'simulcast' option is supposed to broadcast to an RTMP endpoint. Hopin works broadcasting to YouTube, but I see nothing in the logs when I point it to my OwnCast server.

**Comment by gabek** [comment]
It looks like Hopin and StreamYard are the same company, and while I'm not familiar with the Hopin product, I do know people have been using StreamYard to stream to Owncast without issues.

No errors on the Hopin side as well as the Owncast side?

**Comment by srees** [comment]
Well, Hopin incorporates Streamyard, but does not offer the RTMP integration with it. They only offer RTMP simulcast via their own backend. Owncast does not show any errors…still trying to get a tech who can check the logs on the Hopin side.

-Stephen

On Jan 21, 2022, at 14:34, Gabe Kangas ***@***.***> wrote:

﻿

It looks like Hopin and StreamYard are the same company, and while I'm not familiar with the Hopin product, I do know people have been using StreamYard to stream to Owncast without issues.

No errors on the Hopin side as well as the Owncast side?

—
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fowncast%2Fowncast%2Fissues%2F1693%23issuecomment-1018839577&data=04%7C01%7Cstephen.a.rees%40vanderbilt.edu%7C6e30d89ae6814bdaac7508d9dd1d66a0%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C637783940619253302%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=NVYTwRLfr%2B3EbX1HY1ak4oAr0exMYiLd6t1uLNo%2F%2B7Y%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAACIVAPSJ6SKTRCV6JB5O4TUXG7MXANCNFSM5MQLGNMA&data=04%7C01%7Cstephen.a.rees%40vanderbilt.edu%7C6e30d89ae6814bdaac7508d9dd1d66a0%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C637783940619253302%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=7znkhTubz9iRDIOlW12n56Odw1tIZOr8v5166DwHciY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cstephen.a.rees%40vanderbilt.edu%7C6e30d89ae6814bdaac7508d9dd1d66a0%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C637783940619253302%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=46wRzCXa7CzaNnpXntNvb5Qrea8aaJhXkJGclK9B880%3D&reserved=0> or Android<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cstephen.a.rees%40vanderbilt.edu%7C6e30d89ae6814bdaac7508d9dd1d66a0%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C637783940619253302%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3VXVCkjfPWFnjzDCiznpewN61U25BbiEyDC%2FTdzgLjo%3D&reserved=0>.

**Comment by srees** [comment]
Are any other ports utilized for this outside of 1935 and 8080?

**Comment by gabek** [comment]
No, but the ports are configurable, so make sure the ports are what you expect them to be in case you changed them.
