### ISSUE TITLE
Cant figure how to set up the ffmeg file path

### ISSUE THREAD

**Issue by timbowek** [owncast/owncast#1697]
level=fatal msg="Unable to determine path to ffmpeg. Please specify it in the config file.

**Comment by jeyemwey** [comment]
Hej! Do you have ffmpeg installed on your machine? Can you please check with `which ffmpeg`? You can tell Owncast your ffmpeg path in the admin interface:

![owncast admin screenshot](https://user-images.githubusercontent.com/2796271/150689182-6bdec96f-4047-492f-aeb9-65364d30db9f.png)

**Comment by timbowek** [comment]
I have this version of ffmpeg ¨_ffmpeg version 2022-01-19-git-dd17c86aa1-essentials_build-www.gyan.dev_¨

Sorry man in really in programming, but i try to get into the interface by typing ¨http://yourserver:808¨ chrome browser, but says it canot access the page  do i have to do it withno internet?

**Comment by gabek** [comment]
Do you mean port `8080`, not `808`?

**Comment by gabek** [comment]
Closing due to lack of response.
