### ISSUE TITLE
Unsupported CPU architecture armv6l

### ISSUE THREAD

**Issue by steko** [owncast/owncast#1714]
Hi, and thanks for creating owncasta! As instructed by the installer, I am reporting that it's impossible to install owncast on a raspberry pi 2.

```
$ curl -s https://owncast.online/install.sh | bash
Owncast Installer v0.0.10 

ERROR: Unsupported CPU architecture armv6lYour Owncast installation did not complete successfully.
Please report your issue at https://github.com/owncast/owncast/issues
```

**Comment by gabek** [comment]
Hi there,

This is the first time I've heard of somebody trying on that architecture, and I don't have a Raspberry Pi 2 to test on, but I fear that may be too old and too low powered to do any kind of video streaming from.  I don't want to add that architecture to our supported architectures if it's not going go work out.

If you're interested in building it yourself to see how it runs on your device, I'd love to hear back how it works for you.

**Comment by steko** [comment]
Thanks, I will try building it myself and will report back.
