### ISSUE TITLE
Allow providing HTML instead of a link for external actions

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1718]
Right now we allow people to point an external action button to any URL that we can open in a modal.  I believe this feature hasn't been fully adopted because people don't have custom HTML hosted anywhere, it's an additional step.

Instead we could allow people to paste in whatever raw HTML they want, and we can render it for them without an additional server being required.

While this wouldn't be totally useful for somebody building some new feature from scratch, if people just wanted to embed a 3rd party "embed code" copy/paste from another site it would work well here.

Examples:

- [Mailchimp signup form](https://mailchimp.com/help/add-a-signup-form-to-your-website/).
- [Paypal donation](https://www.paypal.com/us/smarthelp/article/how-do-i-add-a-paypal-payment-button-to-my-website-faq3629)

**Comment by xarantolus** [comment]
Hey, I'd be interested in working on this. I'll try adding an HTML field to the external action types and then use that if it's non-empty (otherwise use the URL) to display in the modal if that's OK :)

**Comment by gabek** [comment]
Yeah, totally go for it!

Maybe the UI could have a switch where you choose either a link or HTML. I only mention that because if you choose HTML we'd have to hide the "Open externally" checkbox, because that option wouldn't make sense in that context. But also open for other ideas that makes it clear what's going on.

Thanks for wanting to look at this!
