### ISSUE TITLE
Cert error on broadcast. and watch.

### ISSUE THREAD

**Issue by jeyemwey** [owncast/owncast#1722]
### Discussed in https://github.com/owncast/owncast/discussions/1720

<div type='discussions-op-text'>

<sup>Originally posted by **ralyodio** February  3, 2022</sup>
https://broadcast.owncast.online/</div>

I can reproduce this issue on Safari/iOS (but not on Chrome/Ubuntu), also on https://watch.owncast.online.

Maybe it's an instance of the [Let's Encrypt issue](https://www.theregister.com/2022/01/26/lets_encrypt_certificates/) that happened a couple of days ago? Regenerating some new certs should fix it, but @gabek needs to connect to the server for this.

**Comment by gabek** [comment]
It's fine for me, I wonder how long this issue has been happening for others.

![image](https://user-images.githubusercontent.com/414923/152350788-1e56f2ae-851a-4f99-80e3-8d5204626389.png)
![image](https://user-images.githubusercontent.com/414923/152350903-011a7005-17f4-4488-bba9-f953c65c6a29.png)

I'll try deleting the certs and regenerating them but I won't be able to see if it's fixed for you or not.

**Comment by jeyemwey** [comment]
Works now. Thanks for the quick help.
