### ISSUE TITLE
Parameter to disable username change

### ISSUE THREAD

**Issue by pengu-fr** [owncast/owncast#1723]
I have an owncast instance, which is private for a non-profit organization, allowing members to follow and participate (via the chat) to meetings remotly. But we need to be able to identify users with certainty in the chat. They should therefore not be able to change their username.

We use a Keycloak server as IDP, and the reverse proxy takes care of authenticating users, validates their authorization to access the owncast instance, and if everything is OK, transfers the request to Owncast , adding the user's full name in the X-Forwarded-User header, so it is set up as their initial username.
It works perfectly!
However, users can still modify their username via the interface.

Proposal:
Add a boolean option in "'Configuration / Chat": Allow the user to change his username.
When unchecked, users should not be able to change their username.

**Comment by gabek** [comment]
Would it be good enough for you to visually remove the ability on your single instance via CSS?  While I totally understand why it makes sense for you, as far as I know only you and one other person would ever use this.

**Comment by pengu-fr** [comment]
Hidding via CSS was my first quickfix option, and it will certainly be fine for now.

From what I've seen, the username is stored in the localstorage, and is sent to the backend at the initialization of the websocket connexion. So there is actualy nothing on the backend controling the username, right ? I guess it would be a big change to implement such control on the backend, using the X-Forwarded-User header.

**Comment by gabek** [comment]
Old versions of Owncast would store the name in localstorage and that's where the source of truth was

It's since changed to where the backend generates the name when the chat user is first registered, but an optional display name can be passed at registration as well, if you're upgrading from an old version of Owncast.  So it's the backend that completely controls the display name.
