### ISSUE TITLE
When shutting down my server I got a javascript error

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#174]
![image](https://user-images.githubusercontent.com/414923/93848471-7d727580-fc5e-11ea-9009-d17d8de8f5b8.png)

**Comment by gingervitis** [comment]
Oh yeah! I've been seeing that too. Forgot to put in a fix in the last PR. Let me see if it's a quick fix.

**Comment by gingervitis** [comment]
Oh ok, so looks like the function `disableChat()` does not exist anymore.
Did we want to do anything when the web socket disconnects? 
Originally we were disabling chat when the socket disconnects, in addition to responding to chat enable/disablement from the parent app container based on stream status. Do we not want to do that anymore?

**Comment by gabek** [comment]
I don't think anything changed, we still want to shut down chat on a chat disconnect.  I'm not sure what happaned to `disableChat` but there may have been an accidental removal somewhere along the line.

**Comment by gabek** [comment]
I'll take care of this, I just remembered this probably happened with the websocket refactor.  Chat disabling is being passed as a prop instead of its internal state now, if I remember properly.
