### ISSUE TITLE
Save volume settings

### ISSUE THREAD

**Issue by gingervitis** [owncast/owncast#175]
We should cookie or localStorage the last video volume setting that the user had.
It's pretty jarring to reload the page and have the video play at full volume every time.

**Comment by SoldierCorp** [comment]
Hi, 

I would like to help, can you assign it to me please?

**Comment by gabek** [comment]
Hi there!  Assigned!

**Comment by gingervitis** [comment]
Hi @SoldierCorp! Thank you for volunteering to pick this up! 
I imagine this would involve digging into VideoJS's api to see if we can do anything with their event handlers for volume and mute settings. But feel free to dig around and have fun!

**Comment by SoldierCorp** [comment]
Hi @gingervitis ,

I just started with this task but the stream is not working. It happens with Go or Docker when I stream locally with OBS.

It shows Stream online and 1 viewer but there is no video. 
![image](https://user-images.githubusercontent.com/1775881/94358158-a337ba00-0064-11eb-9352-441f1b283aad.png)

**Comment by gabek** [comment]
Is this on master?

**Comment by SoldierCorp** [comment]
Yes

**Comment by gabek** [comment]
1. Try using the test script and point it at a video file while owncast is running: ` ./test/ocTestStream.sh somevideofile.mp4 rtmp://localhost/live/yourstreamkey`
1. Run owncast with `go run main.go --enableDebugFeatures --enableVerboseLogging`
1. Take a look at `transcoder.log` to troubleshoot any issues.

Other people are running it ok, so there must be something specific to your environment.  From your error above it looks like no video is actually being processed.

**Comment by gabek** [comment]
@SoldierCorp Hey there.  We caught something today that probably fixes what you're seeing.  Let me know if you're still experiencing issues after pulling master.  Thanks!

**Comment by SoldierCorp** [comment]
@gabek It's working now, thank you!

**Comment by SoldierCorp** [comment]
Hi @gabek 

Before I submit my PR, could you please read the Update for the event please https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by gabek** [comment]
Thanks for the heads up!  I went ahead and added the `hacktoberfest` topic to our repository.
