### ISSUE TITLE
Add socket activation support

### ISSUE THREAD

**Issue by eriksjolund** [owncast/owncast#1750]
Add support for [socket activation](https://www.freedesktop.org/software/systemd/man/systemd.socket.html).
 
Container runtime support for _socket activation_ has improved lately.
[Podman](https://github.com/containers/podman/) version 3.4.0 (released September 2021)
supports running OCI containers (i.e. Docker containers) with _socket activation_.

I wrote a [minimal demo](https://github.com/eriksjolund/mariadb-podman-socket-activation/) for a MariaDB container. (That demo is not related to __owncast__ though).

Using _socket activation_ has some advantages

### Rationale

* If you have a containerized server that takes requests from the network via a listening TCP port, adding socket activation support opens up the possibility to run the container with the __--network=none__ command-line option. This will restrict the container from accessing the network except via the TCP socket it has been passed by systmed via Podman. Outgoing connections would not be allowed. Running the container with --network=none improves security. I'm not sure if this is relevant in the case of __owncast__ though.

* Having support for socket activation has the additional advantage that template systemd units can be used to create instances of the server with minimal configuration changes. Adding an additional instance of a TCP socket daemon would only require one extra file, a so called systemd drop-in configuration file. For instance https://github.com/eriksjolund/mariadb-podman-socket-activation/blob/main/mariadb-tcp@demo.socket.d/override.conf
    ```
    [Socket]
    ListenStream=127.0.0.1:8090
    ```
    When using UNIX sockets, it's even less preparations to do. No systemd drop-in file is needed as there is no TCP port number to specify. The file path for the UNIX socket could instead be computed by specifying the path with systemd specifier `%i` that will be expanded to the instance name (i.e. the text string between `@` and `.socket` when you activate the socket with `systemctl --user start servicename@instancename.socket`).
* Owncast would not be running at all before the first client connects to the listening sockets that systemd has created. Less compute resources would be used.
* One possibility for the future could be introducing new functionality in owncast for shutting down on inactivity. Owncast  could after shutting down be reactivated by systemd when a new client connects.

### Regarding the implementation

It would be cool if the implementation would support having both UNIX sockets and TCP sockets active at the same time.
For instance there could be one TCP socket and one UNIX socket both making use of the setting:

`FileDescriptorName=rtmp`

The owncast server would, in other words, be ready to receive RTMP requests on both the TCP socket and the UNIX socket.

**Comment by gabek** [comment]
HI there.

I really appreciate all the effort you put into describing what this is for, and the PR you authored to address it.

However, this is a _very_ specific use case.  And while I don't mean to be a jerk, or come off insensitive to your needs, I'd be willing to bet you're the only person this would be useful for.  Not only do you have to be using Podman instead of Docker, but you also have to be using a very specific systemd configuration.  I don't personally use this configuration, and when the day comes that you stop using Owncast there will be entire branches of logic in the major listener functions of the service that I won't know if it works anymore, and nobody will be using.

I'm sorry you put all this work in and it's not something I want to merge into the codebase, but I hope you keep a fork for yourself and Owncast can continue to be useful to you.

**Comment by eriksjolund** [comment]
Hi, thanks for the feedback. I see, I didn't convince you with the arguments I gave. After submitting this issue I discovered two more arguments for adding  _socket activation_ support. Let's see if these arguments could change your mind :) 

1. When using rootless Podman (i.e. running Podman from a non-root account) you get native network performance if the container supports _socket activation_. Normally network traffic passes through __slirp4netns__ which comes with a performance penalty. See https://github.com/containers/podman/blob/main/docs/tutorials/socket_activation.md#native-network-performance-over-the-socket-activated-socket  I don't have done any performance benchmark tests, though.

2. (This argument might not be relevant for owncast)  When writing a GitHub Actions workflow that tests a containerized server, it's often necessary to postpone the client test by adding an additional /usr/bin/sleep combined with a while-loop to first verify that the server has come online. There is no need for that when using a service that is socket-activated. I created an example:  https://github.com/eriksjolund/user-systemd-service-actions-workflow

<blockquote><img src="https://opengraph.githubassets.com/49b077e5f5ba8dc7fc310b0c6a174ba94d2f06df02f92f973357d88e48fb9401/containers/podman" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/containers/podman">podman/socket_activation.md at main · containers/podman</a></strong></div><div>Podman: A tool for managing OCI containers and pods. - podman/socket_activation.md at main · containers/podman</div></blockquote>
<blockquote><img src="https://opengraph.githubassets.com/448526ee9703f8209438c05d4faa87aab6b663f8a55d409b013058fb9ad0edc1/eriksjolund/user-systemd-service-actions-workflow" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/eriksjolund/user-systemd-service-actions-workflow">GitHub - eriksjolund/user-systemd-service-actions-workflow: GitHub Actions workflow that runs a socket-activated echo server with Podman in a user systemd service</a></strong></div><div>GitHub Actions workflow that runs a socket-activated echo server with Podman in a user systemd service - GitHub - eriksjolund/user-systemd-service-actions-workflow: GitHub Actions workflow that run...</div></blockquote>
