### ISSUE TITLE
External Storage Bug?

### ISSUE THREAD

**Issue by jeffreycarey-aon** [owncast/owncast#1753]
Hello,
My name is Jeffrey Carey.  I am trying to use storage with B2 cloud storage buckets.  

I am getting the following error:

Giving up on data/hls/1/stream.m3u8 RequestError: send request failed caused by: Put https://d49f512747133a3d75f0061a.3.us-west-002.backblazeb2.com/hls/1/stream.m3u8: dial tcp: lookup [d49f512747133a3d75f0061a.3.us-west-002.backblazeb2.com]
(http://d49f512747133a3d75f0061a.3.us-west-002.backblazeb2.com/) on 173.255.212.5:53: no such host

When I look at the url for the endpoint I find that the string deleted the "s" portion of the endpoint address: "3.us-west-002.backblazeb2.com/"

Any ideas?

**Comment by gabek** [comment]
Unfortunately I'm not sure what you're seeing here. I don't know why one random character would simply disappear from a string. Is it correct in the admin?

**Comment by jeffreycarey-aon** [comment]
False alarm.  My mistake.  Thank you for responding.  - Jeff
