### ISSUE TITLE
"invalid cross-device link" error when running on a different filesystem

### ISSUE THREAD

**Issue by lfuelling** [owncast/owncast#1768]
When restarting (stopping, waiting some time and then starting) a stream, weird error mesages appear in the log when the application is running from (or the data folder is stored on) a different filesystem/partition than the `/tmp` folder is on:

```
error | 12:30:42 PM 03/07/2022 | error moving temp playlist to overwrite existing one rename /tmp/tmp-stream-1.m3u8259145761 data/hls/1/stream.m3u8: invalid cross-device link
error | 12:30:42 PM 03/07/2022 | error moving temp playlist to overwrite existing one rename /tmp/tmp-stream-0.m3u81486992245 data/hls/0/stream.m3u8: invalid cross-device link
```

This seems to happen because a rename is done instead of a copy followed by a delete (which works across filesystems).

**Comment by HolgerHuo** [comment]
A temporary solution before the new release may be setting TMPDIR environment to /app/data/tmp so that they are on the same partitions

`-e TMPDIR=/app/data/tmp`

Don't forget to create the directory manually under your data volume and set correct permission.
