### ISSUE TITLE
Add timestamp of message as title attribute to chat messages

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#177]
While I don't want to see the timestamp directly in the UI, sometimes I'm curious how long ago somebody sent a message.  Hovering over this message to get a timestamp string would be a compromise and stay out of the way.

**Comment by ahmadkarlam** [comment]
Hi @gabek, Can i try it ? I am new to working on open-source projects

**Comment by gabek** [comment]
Hi @ahmadkarlam, absolutely!  This is a good, small starter change.  @gingervitis has been most involved with our web frontend, so feel free to ask us any questions you might have when working through it.  Enjoy!

**Comment by ahmadkarlam** [comment]
Where will the timestamp be shown? or when the mouse hover over the text a tooltip will appear like this? @gingervitis 
![rsz_screenshot_from_2020-09-30_15-37-15](https://user-images.githubusercontent.com/4019710/94662742-02cae980-0333-11eb-8a4a-d92720829a99.png)

**Comment by gingervitis** [comment]
Probably the easiest approach to this would just be to use the `title` attribute on the message div for the timestamp info. While there may be accessibility concerns using `title`, I think it'll be ok in this setting as it isn't terribly important info, and I also don't think most users would be interested in seeing it on mobile devices.

But if you want to get a little fancier and styling it a bit you could explore using data-* attributes on the div and using populating the timestamp content using CSS pseudo classes.

Either way, I think this could be done without using an JS event handlers and extra libraries.

**Comment by gingervitis** [comment]
You could also put it in another div or span somewhere in the message and have it display when you hover over the message?

It's up to you what you think will look good and make sense without too much overhead!

**Comment by ahmadkarlam** [comment]
Maybe it's better to use the title attribute because I saw Youtube and Twitch, they don't show the timestamp either.

**Comment by ghost** [comment]
This thread is old, but it appears this feature may not be working anymore. We have multiple owncast instances running 0.1.3 on different servers, and hovering over a message does not give the timestamp. Wondering if this was intended or if we are using it incorrectly. Thanks!

**Comment by gabek** [comment]
I think you're correct, I don't believe it was added when the web interface was completely rebuilt for v0.1.0. Please don't hesitate to file an issue if it's something you would like back. I believe you're the first person to mention it.
