### ISSUE TITLE
Azure Support for Video Scaling

### ISSUE THREAD

**Issue by argium** [owncast/owncast#1770]
What's the latest on Azure support? Is there a technical limitation or does it just need implementation?

**Comment by gabek** [comment]
I'm unfortunately not sure what you mean by "Azure support". If you spin up a Linux machine on Azure, or anywhere else, you should be good to go.

**Comment by argium** [comment]
> I'm unfortunately not sure what you mean by "Azure support". If you spin up a Linux machine on Azure, or anywhere else, you should be good to go.

Hi @gabek, I meant using Azure Storage in place of AWS for distributing video fragments to support a larger number of viewers.

**Comment by gabek** [comment]
We support every storage provider that uses the S3 standard, and I think Azure is the only one that doesn't. There's no plans for adding a specific storage provider's protocol.  https://github.com/owncast/owncast/issues/139
