### ISSUE TITLE
Page layout changes on mobile when keyboard is up

### ISSUE THREAD

**Issue by gingervitis** [owncast/owncast#178]
![Screenshot_20200922-134154.png](https://user-images.githubusercontent.com/9563255/93938204-c289bc80-fcdd-11ea-9ff9-4c2c583e2399.png)

This one rears its ugly head again. I thought I had fixed it, but I think it came back when I tried to fix something else.

**Comment by gingervitis** [comment]
<begin stream of consciousness notes as I think through this...>

Oh I remember now. I think I was trying to fix issues with landscape orientation on iOS. In landscape, the fixed video position will not move due to it thinking that's its in "single col" mode. (because iOS hates fixed pos, chrome is ok).


Why does `short-wide` layout exist?
The current css suggests that I wanted the video container to be shorter than the visible height, so that users could see that there was scrollable content below it, when chat was on.  This was not mobile-specific.
```
.short-wide.chat #video-container {
  height: calc(100vh - var(--header-height) - 3rem);
  min-height: auto;
}
```

What is `short-wide`?
Currently defined as `windowHeight < 500 && windowWidth > 730`.


What I really need to do..
- mobile landscape - need keep 2 col format, with short-wide video height. single col does not work.
- mobile landscape w/keyboard up - eww, why. go back to portrait please.

- mobile portrait - use single col mode
- mobile portrait w/ keyboard up - forces layout into 2 col format, yuck. I think it's because depending on device, width>height, so it qualifies for short-wide mode. **I need to prevent 2 col from happening.**  `screen.orientation` thinks it's still in portrait. I could do something with that. (is that true of all browsers?). So I could do:
```
if (orientation === portrait and width < 730) { use single col }; //?
```

- tablet - use desktop rules, but they might also succumb to orientation=portrait rules.
- small tablets w/keyboard up - ugh so many possibilities.  maybe they'll take on some mobile rules. 

I might be over thinking these scenarios. There might be an easier cleaner way to handle these cases with the layout we have?



</end stream of consciousness>

**Comment by gingervitis** [comment]
Pushed a fix for this. 
Logic goes: 
On touch devices, use `window.screen.orientation` on Chrome, because only that one will give an accurate orientation when keyboard is up. Safari does not support `window.screen.orientation`, but that's ok, using `window.matchMedia` will work. We can also use window.matchMedia for desktop, but we usually don't care about orientation on desktop (at least not for now).

So we'll display single col mode if window is less than a certain width && we're not short height (which excludes any touch screen in portrait mode).

```
    const isPortrait = this.hasTouchScreen && orientation === ORIENTATION_PORTRAIT;
    const shortHeight = windowHeight <= HEIGHT_SHORT_WIDE && !isPortrait;
    const singleColMode = windowWidth <= WIDTH_SINGLE_COL && !shortHeight;
```
🤯

**Comment by graywolf336** [comment]
You're awesome @gingervitis and doing a fantastic job!! 👏
