### ISSUE TITLE
Change cachebust param to random string to support CDNs

### ISSUE THREAD

**Issue by zerodytrash** [owncast/owncast#1781]
https://github.com/owncast/owncast/blob/d2fd6a95e963b6687ad74793f4be270a6a57d72a/webroot/js/components/player.js#L68
I'm not sure why a timestamp is used as a cachebust parameter. When I think about it, the following problem appears:
Assuming the HLS playlist is cached by the storage or CDN provider on server side, changing the URL parameters will bypass the cache. So far so good. However, all those who use the same cachebust timestamp will get the same version from the cache.

- When a viewer's system clock goes faster, the cache is filled with a version that everyone else gets later.
- When a viewer's system clock goes slower, the viewer constantly gets playlist files that are already older from the cache.

If the cachebust parameter is only intended to bypass client-side caching, then that's ok. Otherwise I would use a random string/number instead of a timestamp to bypass CDN caching.

**Comment by gabek** [comment]
> If the cachebust parameter is only intended to bypass client-side caching, then that's ok.

Yeah, that's why it was added, as additional precaution to make sure the browser is fetching fresh playlists.

**Comment by zerodytrash** [comment]
Okay, and it would not make sense to adjust the cachebust parameter to avoid server-side caching?

I ask because I encountered the described problem while using Cloudflare. 
Cloudflare CDN caches the video segments (which reduces the server load) and in the default setting also the playlist.

**Comment by gabek** [comment]
Sure, there's no downside to changing it. In theory none of this should be needed, and the cache control headers should be respected everywhere, but early on somebody was having issues with their browser cache so that's why this was added.

**Comment by gabek** [comment]
Alright, I went ahead and changed that to a random string.

**Comment by zerodytrash** [comment]
Perfect, thanks!
