### ISSUE TITLE
Share/embed/stream link view

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#179]
We have a couple pieces of info that would be useful to put in some kind of embed/info/detail view.  

1. HTML for embedding.  We have a first pass of what this could be in our not-yet-public [embed page on the docs site](https://owncast.online/docs/embed/).
1. HLS stream URL.  An easy way for people to copy/paste the stream URL into a player of their choice.  As a related example, I often will be on the [DNA Lounge live stream](https://www.dnalounge.com/webcast/video.html) and people want to put it on their AppleTV, or Chromecast or whatever but nobody knows the URL to put in their players (/hls/stream.m3u8 in our case, though we could make it more user friendly if needed).

I don't really see needing or wanting any specific "Share to social site X" options, since copying and pasting the URL works fine.

I don't know where this would go in the UI, or if anything else would be useful to surface that would allow additional ways to view the video.

Here's YouTube's version of this kind of thing.

![image](https://user-images.githubusercontent.com/414923/93945255-6af24d80-fceb-11ea-97e1-8fa1cb20302c.png)

**Comment by gingervitis** [comment]
Hmm, I wonder if videoJS has module that supports "share"..

**Comment by gabek** [comment]
It wouldn't know our embed code though :\

**Comment by gabek** [comment]
I don't see this being important or us getting to it, so I'm closing.
