### ISSUE TITLE
Chat - Emote Wire Protocol

### ISSUE THREAD

**Issue by jprjr** [owncast/owncast#1803]
Hi there! I noticed when emotes are sent, the HTML for an `<img>` tag is sent via websocket.

Thought I'd suggest sending the code/title (`:partyparrot:`) instead and have it updated/rendered server-side? As far as I can tell (and I'm just getting started, so apologies in advance if I'm mistaken) - for a bot to use a custom emote, it needs to also generate and send the HTML.

Being able to send the tag would simplify bot code a bit. Plus, for webhooks - `rawBody` could also just contain the tag, instead of the HTML. Would make it easier for bots to do things like, count how often emotes are used - right now they have to parse the HTML and extract the alt or title attribute.

**Comment by gabek** [comment]
I think that's fair, I could see how that would be helpful.

**Comment by gabek** [comment]
Since this will require frontend changes I'll wrap this up with the future frontend changes. It probably won't be soon, but it makes sense to hold off until then since it'll all have to be touched anyway.

**Comment by jprjr** [comment]
Hi there, now that the new UI is out, I wanted to volunteer to take a crack at implementing this. Just wanted to check-in and ensure 1) it's still desired and 2) nobody else has already started.

Here's my rough idea:

* change front-end to send emoji as text like `:partyparrot:` rather than HTML.
* sever-side, validate sent emoji and convert to HTML.
* keep plain-text version in `rawBody` and HTML-rendered version in `body` attributes of message object.

**Comment by gabek** [comment]
This sounds great, thank you for offering to work on it! Since the output will still end up being HTML it won't impact anybody using chat webhooks or the rendering of chat messages, so there's no downside here.

**Comment by jprjr** [comment]
Took a look and there's one behavior change I'd like to propose - basically for the emoji picker to just always put emoji at the end of the chatbox input, rather than where the caret position is. This is similar to how twitch chat works - it ignores your caret position.

There's a fundamental mis-match, at least in Firefox, between the caret position and the innerHTML content.

Right now, the caret position is being saved by taking the length of the innerHTML up to the caret. So if you have an emoji you're taking the length of `<img src=".... alt="emote">` - etc, and coming up with a high value for the caret position, say 30.

As far as the browser is concerned, if you have a single custom emote, the caret position is really just `1`. So when you go to re-set the caret position it's some invalid value.

If you change up the code to count images as 1 character and use that as the caret position - now you're able to restore the caret position in the browser. But, inserting an emote doesn't work, since you need to insert it in the text, and if you use that caret position of 1 - you're inserting in the middle of existing HTML.

I think it may be possible to restore the caret position, then insert a node at the caret position rather than edit the text content reference, but I haven't explored that far just yet.

If the picker is changed to just always append the emote, I think lot of things get simpler - you wouldn't have to find/save/restore the caret position at all.

Let me know, I can try the "create a node and insert it" approach too, but it may be worth changing to just always append and removing a good chunk of code around caret positioning/focus handling.

**Comment by jprjr** [comment]
On second thought, I think that's really tackling another issue, I'll limit my scope here to just changing how emotes are sent and find/file issues for everything else.

**Comment by gabek** [comment]
I made the append-only change when looking at #3120.

**Comment by jprjr** [comment]
Design/implementation question - as far as I can tell, whenever the emoji API endpoint is queried, the emoji directory is walked and all emoji loaded.

With the server replacing these short-codes with emoji server-side, should:

1) the server load the emoji list anytime it gets a message with a shortcode?
2) keep a cached list per-client-connection?
3) keep a cached list for the whole server?
4) something else?

For the cached list (whether per-connection or global), my idea is to check the emoji directory modification time and re-load as needed. Anytime a new emote is added to the folder, the folder modification time should change.

It may not be too much of a performance impact to just load the list every time, querying the filesystem *should* be pretty fast.

If I cache for the whole server, I'm guessing that would require introducing a global mutex which may not be ideal, but may be more ideal than having to reload the emoji list anytime a chat message with an emoji comes in?

Caching per-client-connection's main benefit is not having a global mutex but may introduce scaling issues. If you have a lot of clients, loading a new emote mid-stream may introduce a brief bottleneck while each client connection loads up the new emoji list. Also, I'd still need some other cache for say, API-injected messages.

I don't know how many emoji/clients you'd have to get to before any of this really becomes an issue, this may be a premature optimization on my part.

**Comment by gabek** [comment]
We used to have an emoji cache that only updated at initial launch, and that was fine because it was pretty rare for people to update their emoji collection, since you had to do it manually on the filesystem. But that was removed with the ability to upload via the admin. 

I think the directory modification time is a good compromise.

One other idea  is to have a cache, but if somebody does a `:unknown:` then it updates the cache assuming that `unknown` is a new image. It could be a totally invalid image still, but it would be a signal to update the cache.

**Comment by gabek** [comment]
I pasted the text from https://loremipsum.io/ into the chat box that starts with some italic. It renders as expected in the textbox, but it gets stripped when sending it:

![image](https://github.com/owncast/owncast/assets/414923/1dd5befb-38e3-4fa7-811f-e155b4e682cc)

![image](https://github.com/owncast/owncast/assets/414923/d6322b96-215b-4a8e-b3ea-29d7370e39c6)

However, when pasting example text from https://www.w3schools.com/html/html_formatting.asp the italic worked as expected. 

![image](https://github.com/owncast/owncast/assets/414923/c9717b6b-5877-4c60-9065-3fe7aa58f8e6)

I'm personally not overly concerned about keeping the rich text formatting, but I know one of your goals was to support that. I guess the biggest issue is the italic text that was completely stripped in the first example.
