### ISSUE TITLE
Chat Events - Colors

### ISSUE THREAD

**Issue by jprjr** [owncast/owncast#1804]
Hi there - I noticed Chat events come in with a `displayColor` attribute, but I'm unsure how to interpret the value. It seems to be an integer?

Would be great if events included the displayColor as a hex value, or just any value that communicates what the red, green, and blue values are.

**Comment by gabek** [comment]
Sorry for the confusion about that.  It's actually the `hue` value that comes across as the `displayColor`. The idea behind this is the server generates a root hue color for the user, but each client can determine the other values to make it fit in with that specific interface (make it lighter, less saturated, etc).  So while it's not hex, the hue alone should be enough for you to do what you'd like to do with it. 

You can see how we generate the chat bubbles with this value here: https://github.com/owncast/owncast/blob/00019bf86bf22d8e417eeb40290d12f20b09298f/webroot/js/utils/user-colors.js

<blockquote><img src="https://repository-images.githubusercontent.com/266445736/4f82fb80-a5b1-11ea-8f1c-69d316f861b5" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/owncast/owncast">owncast/user-colors.js at 00019bf86bf22d8e417eeb40290d12f20b09298f · owncast/owncast</a></strong></div><div>Take control over your live stream video by running it yourself.  Streaming + chat out of the box. - owncast/user-colors.js at 00019bf86bf22d8e417eeb40290d12f20b09298f · owncast/owncast</div></blockquote>

**Comment by jprjr** [comment]
That answers the question, thank you so much!
