### ISSUE TITLE
User selectable chat display colors

### ISSUE THREAD

**Issue by jprjr** [owncast/owncast#1805]
Feature request - for users to be able to customize their color in chat.

**Comment by gabek** [comment]
Are you thinking each individual chat user should be allowed to change their color, much like they can change their names, or were you thinking the server admin should be able to set a custom palette of colors to be used for users?

For some reference, the color right now can be used as an identifying piece of metadata for a user. So if a green "Bob" who created an account two months ago tries to be impersonated by blue "Bob" who created an account five minutes ago, you can visually see it's a completely different chat user. If people could change their own colors then this immutable piece of metadata would no longer be valid.

**Comment by jprjr** [comment]
I was thinking users could change their own color, like their names. I guess this would be dependent on having accounts/authentication (tagging #464).

**Comment by gabek** [comment]
While users are persistent already, and don't require auth to have this, I don't see adding this. It would require a new level of chat user settings that don't already exist, with very little benefit (I don't think most people care about the colors much).

**Comment by jprjr** [comment]
I'm going to (politely) challenge that a bit. The reason I opened the issue is because I had users ask. It's the kind of thing where you either don't care at all - or you care a whole lot. As a user, if you get assigned a color that you don't like, it can be enough to make you not participate. Like imagine if all your messages were in a color that, for whatever reason, you just can't stand - and there's nothing you can do.

**Comment by gabek** [comment]
That's cool. I'll reopen and let others chime in and if it gets some traction then maybe we can find a way to make it happen.

**Comment by Troyjan20072001** [comment]
I am one of those users that prefer Color Options while chatting with friends. It gives that personal feeling.

**Comment by anKerrigan** [comment]
I would also like to (politely) make the case for custom user colors. For me, it's an issue of accessibility. People recognize color before text and if, for example, my user color is the same as someone else's, I might accidentally skip over it, thinking it's mine, especially if chat's busy.

I also think it would be beneficial to color-blind people, so they can have more control over how their messages appear on-screen relative to others'. 

It's like @jprjr stated above; it might seem like a small or unnecessary change but it has more advantages than drawbacks, especially from people who would most benefit from the option.

**Comment by gabek** [comment]
We're working on a rewrite of the owncast user interface and custom colors per chat user is not in the plans. However, the admin will be able to override the available palette of colors with their own. So if they don't like the colors, they can define new ones. That should be a middle ground that hopefully works for most Owncast instances.

**Comment by jprjr** [comment]
Hi there, I'd like to re-open this and request users be able to choose a color from the palette in the upcoming, new UI.

In the past, my users would re-make accounts until they get a color they like. They want to use the new authentication options, but now some find themselves locked into a color they don't like.

**Comment by anKerrigan** [comment]
> be able to choose a color from the palette in the upcoming, new UI.

This is literally the one and only feature I want from Owncast. Just this one thing. Please just let me pick a color. I'd never ask for anything ever again. I'd volunteer to help get it done if I thought I'd be any use.

**Comment by nvrslep303** [comment]
In my case, having users being able to choose their chat color makes it easier to identify who is speaking, at least in my opinion. Our owncast stream that we are mainly referring to has a lot of daily viewers who interact a lot through the chat. Being able to distinguish who is speaking and being able to go through the fast moving chat ups the enjoyment factor. 

An issue we usually run into is people's name being the same color as the bot. The music request bot consists of half the posts in the chat and when there are people who have the same color as the bot, a lot of their messages get lost in the shuffle. There are others who also just want to differentiate themselves from the other users. 

Sorry, I don't mean to be long winded or add to your work load. I just think it would increase the enjoyment of the owncast stream, in our case anyways.

**Comment by gabek** [comment]
Hey there, thanks for sharing your thoughts. So the new approach to colors solves a couple problems but may make it harder to have a completely custom color in this case.

Right now colors are completely randomly generated, but because of that a lot of colors look similar, and some don't look great. Additionally admins have no control over how these look with their page. So people's pages are stuck with ugly colors that they don't even want.

With the new approach a pre-defined set of colors will be used instead, and those colors will be issued out to chat users. Admins will be able to change this color palette if they want to. Because of this pre-determined color palette it wouldn't be possible for a chat user to be able to select any color they want, because colors will be limited to ones that were decided would look good or are ones the admin prefers.

However, I don't see why we can't allow a user to change what color is assigned to them by picking a color from the available set of colors. And since new UI is often something that gets in the way of new features, in this case the chat name change is going to move to a modal instead of the tiny inline form thing, so there is a place to put it.

So hopefully this makes sense and this could work. The downside is from a user standpoint there may not be a color in that palette that you like, or that fits your needs. But it would still allow for some level of customization.

**Comment by jprjr** [comment]
> However, I don't see why we can't allow a user to change what color is assigned to them by picking a color from the available set of colors. And since new UI is often something that gets in the way of new features, in this case the chat name change is going to move to a modal instead of the tiny inline form thing, so there is a place to put it.

> So hopefully this makes sense and this could work. The downside is from a user standpoint there may not be a color in that palette that you like, or that fits your needs. But it would still allow for some level of customization.

I think that makes perfect sense! That allows streamers to have some control over branding while allowing users to choose colors more pleasing to them. And yeah, it may not be perfect, but it does make the form a lot simpler (basically a dropdown or some-such).

**Comment by gabek** [comment]
Everything is very much a work in progress but if you're at all curious the state of things:

- [Initial proposed user color palette](https://owncast.online/components/iframe.html?id=owncast-style-guide-colors--page&viewMode=story&args=#user-colors)
- [New chat message design](https://owncast.online/components/?path=%2Fdocs%2Fowncast-chat-messages-standard-user--from-authenticated-user)

**Comment by gabek** [comment]
Functionality is in.

![Image](https://user-images.githubusercontent.com/414923/183799653-c717d93d-3e66-48a6-92a5-1d2b0f853794.png)
