### ISSUE TITLE
Web interface redesign

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1808]
This is a placeholder for all of the work required for implementing the future redesign of the Owncast UI. This includes consolidating all the frontend and admin web apps to live together in `owncast/owncast`.

I've contracted a designer and been working with him on the final design.

**Comment by gabek** [comment]
[owncastredesign.pdf](https://github.com/owncast/owncast/files/8491806/owncastredesign.pdf)

**Comment by aaronpk** [comment]
Great writeup! Is it worth mentioning the eventual possibility of adding in playing back recordings? #102 I'm thinking about just making sure recording playback is being taken into account at the beginning of the redesign phase, but not necessarily actually doing the design for it just yet.

**Comment by gabek** [comment]
I thought about that, but there's a lot of unknowns there, and the specifics of what it should look like will come from how it works and what's available. So anything that was designed early on will likely be wrong by the time it's implemented. I figured it makes sense just to focus on those features when the time comes as opposed to having a designer add a new tab without specifics. But I haven't forgotten about it!

**Comment by aaronpk** [comment]
fair enough! I suppose if the plan is to put it in a tab that's about all I was thinking about at this stage anyway!

**Comment by gabek** [comment]
I'm not sure they'll appreciate it, but I'll share how you can follow the progress anyway. We build in public!

https://www.figma.com/file/B6ICOn1J3dyYeoZM5kPM2A/Owncast---Review?node-id=0%3A1

(Read the comments to know what things are being brought up)

<blockquote><img src="https://www.figma.com/file/B6ICOn1J3dyYeoZM5kPM2A/thumbnail?ver=thumbnails/8522953f-71c6-425a-b8f2-45dd8d36b9a3" width="48" align="right"><div><img src="https://static.figma.com/app/icon/1/favicon.svg" height="14"> Figma</div><div><strong><a href="https://www.figma.com/file/B6ICOn1J3dyYeoZM5kPM2A/Owncast-Review">Figma</a></strong></div><div>Created with Figma</div></blockquote>

**Comment by gabek** [comment]
Closing this in favor of the smaller, more actionable, items that have been filed for the work taking place.
