### ISSUE TITLE
Stream end video does not play

### ISSUE THREAD

**Issue by bmunger** [owncast/owncast#1817]
After updating the new latest docker image, there seems to be an issue with the stream ending video.  On the previous version, 0.0.10, when the stream ended, there would be an Owncast animation with sound and then the video playback would stop.  With version 0.0.11, when the stream ends, it shows the spinning circle and no end Owncast animation.  This was tested in both Firefox and Chrome.  I don't see any settings within the admin interface that would control this behavior.

The following was displayed at the console during a few attempts:
```owncast    | time="2022-04-08T02:07:37Z" level=info msg="Inbound stream connected."
owncast    | time="2022-04-08T02:07:37Z" level=info msg="Video transcoder started using x264 with 1 stream variants."
owncast    | time="2022-04-08T02:09:29Z" level=info msg="Inbound stream disconnected."
owncast    | time="2022-04-08T02:09:30Z" level=error msg="error moving temp playlist to overwrite existing one rename /tmp/tmp-stream-0.m3u83745450788 data/hls/0/stream.m3u8: invalid cross-device link"
owncast    | time="2022-04-08T02:13:32Z" level=info msg="Inbound stream connected."
owncast    | time="2022-04-08T02:13:32Z" level=info msg="Video transcoder started using x264 with 1 stream variants."
owncast    | time="2022-04-08T02:20:49Z" level=info msg="Inbound stream disconnected."
owncast    | time="2022-04-08T02:20:50Z" level=error msg="error moving temp playlist to overwrite existing one rename /tmp/tmp-stream-0.m3u82853742143 data/hls/0/stream.m3u8: invalid cross-device link"
owncast    | time="2022-04-08T02:25:50Z" level=info msg="Video transcoder started using x264 with 1 stream variants."
```

Thanks!

**Comment by gabek** [comment]
Sorry about that. That's an issue with using a `tmp` directory that's on a different filesystem. It's been fixed for the next release in #1768.
