### ISSUE TITLE
Feature Request: Sortable social media links

### ISSUE THREAD

**Issue by DrSkyfaR** [owncast/owncast#1818]
Hello all,
I think it could be a useful feature to make the social media links sortable with a little up and down function to move them back and forth. I noticed the problem when my friend and I added all our links randomly and found that they were displayed on the front page in the order they were created. So we had to remove all the links again and put them in the order we wanted them. I realize that this would be a pure usability feature but, if by chance there is time, maybe we could implement something like this.

**Comment by gabek** [comment]
Agreed, that'd be nice to have!

**Comment by DrSkyfaR** [comment]
Hello @gabek 
I thought of an addition to the feature request that could perhaps be included. Currently it is so that when you add custom domains to the social media list generically always receives this globe as an icon. Of course, this looks a bit unattractive, but of course it's better than nothing. 

However, to make this perhaps more aesthetically pleasing in the future, we can think of two ideas, namely:

1. when adding the custom domain, Owncast automatically pulls the favicon of the website as an icon for the social media link. 
2. in the future you might have the possibility to upload your own icon in the form of XXpx*XXpx as PNG or maybe SVG itself. 

This is of course a pure optical gimmick, but I could imagine that in the end perhaps a more rounded overall picture. You can tell me or the community what you think about it. 

Greetings SkyfaR

**Comment by pippo** [comment]
Just making sure... This issue is about this part of the admin UI, under `Configuration` > `General`, right?

<img width="383" alt="image" src="https://user-images.githubusercontent.com/47276/193679670-de6e6bb1-a079-491b-93f2-aaf57bcff08f.png">

**Comment by gabek** [comment]
Yeah, exactly!

**Comment by pippo** [comment]
I believe [my PR](https://github.com/owncast/owncast/pull/2168) addresses this feature request. Perhaps, the issue can be closed now.

**Comment by gabek** [comment]
Indeed! Thank you for working on that :1st_place_medal:
