### ISSUE TITLE
Serving ActivityPub objects

### ISSUE THREAD

**Issue by silverpill** [owncast/owncast#1827]
According to [ActivityPub spec](https://www.w3.org/TR/activitypub/#retrieving-objects), objects must be retrieved with an `Accept` header of `application/ld+json; profile="https://www.w3.org/ns/activitystreams"`:

>The client MUST specify an Accept header with the application/ld+json; profile="https://www.w3.org/ns/activitystreams" media type in order to retrieve the activity.

I've tried several Owncast instances, and it looks like they serve ActivityStreams object representation only in response to requests with `application/activity+json` and `application/json` media type in Accept header, but respond with HTML to requests that comply with the standard.

**Comment by gabek** [comment]
Done, thanks!
