### ISSUE TITLE
Document an example configuration price vs. aws IVS

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#183]
[Amazon IVS](https://aws.amazon.com/ivs/) has a "free tier" with lame limitations like:

> Five hours of live video input for a basic channel per month.  100 hours of SD live video output per month.

Can only stream 5hrs per **month**?

For a two hour event they use this as an example:

> The total cost of a two-hour event with Standard input at 1080p and delivered to 200 viewers from the US (100 viewers in 
> SD, 50 viewers in HD, and 50 viewers in Full HD) is $34.00.
>
> Live Video Input:
>
> Standard Channel = $2.00 per hour * 2 hours = $4.00
> 
> Live Video Output:
> SD output from North America = $0.0375 per hour * 2 hours * 100 viewers = $7.50
> HD output from North America = $0.0750 per hour * 2 hours * 50 viewers = $7.50
> Full HD output from North America = $0.1500 per hour * 2 hours * 50 viewers = $15.00
> 
> $4.00 + $7.50 + $7.50 + $15.00 = $34.00

**Comment by tuxinaut** [comment]
> Can only stream 5hrs per month?

Yep it AWS; many free tier services are per month like EC2 (750 hours on specific instance types)

Are you aware that the free tier for **Amazon Interactive Video** is only applicable for the first 12 months after signup?
