### ISSUE TITLE
Issue: chat unscrollabe on some resize operations

### ISSUE THREAD

**Issue by jprjr** [owncast/owncast#1830]
Hi there, noticed an issue (using Google Chrome, latest version, tested on MacOS and Windows):

If you shrink the browser's width enough to change layouts (from the horizontal layout, to the vertical layout), then expand it a little bit (so it stays in the vertical layout) - the chat becomes unscrollable.

Sometimes it's hard to reproduce. It seems like if the messages get reflowed while widening, everything is fine. But if you can widen just a bit and not have the reflow happen, you can no longer scroll with the mouse scroll wheel.

**Comment by gabek** [comment]
I was able to reproduce this and a small change seems to clear it up.

**Comment by gabek** [comment]
Apparently I fixed it on resize events, but now it's broken in natively-narrow screens (without resizing). If I open a narrow browser window and open Owncast it cuts off the chat.

![image](https://user-images.githubusercontent.com/414923/164359555-fb50442b-c635-4a1e-95db-ad871495c379.png)
