### ISSUE TITLE
Federation: Pleroma receives "Unhandled Activity" error when going live

### ISSUE THREAD

**Issue by jprjr** [owncast/owncast#1840]
(I'm also going to open an issue with Pleroma, I'm unsure if the error is in Owncast or Pleroma)

I noticed that when Owncast goes live and sends out the ActivityPub message to Pleroma instances, Pleroma responds "OK" to the update - but the update never shows in the user's timeline.

With debug logging enabled, Pleroma reports "Unhandled Activity".

What's interesting is, if I modify owncast to not include the Preview image - the activity is published correctly to users. So, I think this has something to do with the image attachment.

I tried modifying the code to do things like:

* Use the Document type instead of Image type (seems to be what mastodon does)
* add a mediaType attribute
* add width and height attributes

None of these seem to work. The only other thing that's striking to me is - I noticed most implementations seem to send the `attachment` property as an array, but it looks like the `go-fed` package serializes that to an object when there's only a single instance. From reading the activitypub specs, I'm 99% sure that's legal - which is why I'm going to also open a Pleroma bug and make sure it isn't a problem there.

So to recap, sending an ActivityPub JSON like this works with Pleroma (and Mastodon):

```
{
  "@context": [
    "https://www.w3.org/ns/activitystreams",
    "http://joinmastodon.org/ns"
  ],
  "actor": "https://owncast.localhost.localdomain/federation/user/streamer",
  "audience": "https://www.w3.org/ns/activitystreams#Public",
  "id": "https://owncast.localhost.localdomain/federation/h7S-lqU7gz",
  "object": {
    "attributedTo": "https://owncast.localhost.localdomain/federation/user/streamer",
    "audience": "https://www.w3.org/ns/activitystreams#Public",
    "content": "<p>I've gone live!</p><p></p><p><a class=\"hashtag\" href=\"https://directory.owncast.online/tags/owncast\">#owncast</a> <a class=\"hashtag\" href=\"https://directory.owncast.online/tags/streaming\">#streaming</a></p><a href=\"https://owncast.localhost.localdomain\">https://owncast.localhost.localdomain</a>",
    "id": "https://owncast.localhost.localdomain/federation/2nI-lqUnR",
    "published": "2022-04-17T15:30:21Z",
    "tag": [
      {
        "href": "https://directory.owncast.online/tags/owncast",
        "name": "#owncast",
        "type": "Hashtag"
      },
      {
        "href": "https://directory.owncast.online/tags/streaming",
        "name": "#streaming",
        "type": "Hashtag"
      },
      {
        "href": "https://directory.owncast.online/tags/owncast",
        "name": "#owncast",
        "type": "Hashtag"
      }
    ],
    "to": "https://www.w3.org/ns/activitystreams#Public",
    "type": "Note"
  },
  "to": "https://www.w3.org/ns/activitystreams#Public",
  "type": "Create"
}
```

However, sending one like this (with an image) does not work with Pleroma, but does work with Mastodon:

```
{
  "@context": [
    "https://www.w3.org/ns/activitystreams",
    "http://joinmastodon.org/ns"
  ],
  "actor": "https://owncast.localhost.localdomain/federation/user/streamer",
  "audience": "https://www.w3.org/ns/activitystreams#Public",
  "id": "https://owncast.localhost.localdomain/federation/KCfHuqU7Rz",
  "object": {
    "attachment": {
      "content": "Live stream preview",
      "type": "Image",
      "url": "https://owncast.localhost.localdomain/preview.gif?us=KjfNX387gm"
    },
    "attributedTo": "https://owncast.localhost.localdomain/federation/user/streamer",
    "audience": "https://www.w3.org/ns/activitystreams#Public",
    "content": "<p>I've gone live!</p><p></p><p><a class=\"hashtag\" href=\"https://directory.owncast.online/tags/owncast\">#owncast</a> <a class=\"hashtag\" href=\"https://directory.owncast.online/tags/streaming\">#streaming</a></p><a href=\"https://owncast.localhost.localdomain\">https://owncast.localhost.localdomain</a>",
    "id": "https://owncast.localhost.localdomain/federation/KjBNuq8ng",
    "published": "2022-04-17T15:42:03Z",
    "tag": [
      {
        "href": "https://directory.owncast.online/tags/owncast",
        "name": "#owncast",
        "type": "Hashtag"
      },
      {
        "href": "https://directory.owncast.online/tags/streaming",
        "name": "#streaming",
        "type": "Hashtag"
      },
      {
        "href": "https://directory.owncast.online/tags/owncast",
        "name": "#owncast",
        "type": "Hashtag"
      }
    ],
    "to": "https://www.w3.org/ns/activitystreams#Public",
    "type": "Note"
  },
  "to": "https://www.w3.org/ns/activitystreams#Public",
  "type": "Create"
}
```

**Comment by jprjr** [comment]
Pleroma issue, for reference https://git.pleroma.social/pleroma/pleroma/-/issues/2864

<blockquote><img src="https://git.pleroma.social/uploads/-/system/project/avatar/2/pleroma_be.png" width="48" align="right"><div>GitLab</div><div><strong><a href="https://git.pleroma.social/pleroma/pleroma/-/issues/2864">Unhandled Activity error on Note with Attachment (#2864) · Issues · Pleroma / pleroma</a></strong></div><div> Environment  Installation type (OTP or From Source): From Source Pleroma version (could be found in the "Version" tab...</div></blockquote>

**Comment by gabek** [comment]
That's unfortunate. And yeah, the single object vs. array of objects is legal across the spec, but this won't be the first time I've seen an implementation have an issue with it. I know I tested with Pleroma previously, but that was clearly without the image.

Thanks for filing that detailed issue with Pleroma, I'm curious what they'll say.

**Comment by gabek** [comment]
https://social.shadowfacts.net/objects/14cacd62-a0ce-4a08-bd92-ea902a9f256c suggests adding a media type:

> it looks like pleroma expects your attachment object to have a mediaType property: https://git.pleroma.social/pleroma/pleroma/-/blob/develop/lib/pleroma/web/activity_pub/object_validators/attachment_validator.ex#L49 and that probably means the description should be in the name field rather than content (since mediaType applies to content)

<blockquote><img src="https://social.shadowfacts.net/media/4b481afc591a8f3d11d0f5732e5cb320422dec72d7f223ebb5f35d5d0e821a9c.png?name=blob.png" width="48" align="right"><div><strong><a href="https://social.shadowfacts.net/notice/AIt9uTVtpv46HJVeeO">Dr. Glenn Pierce (@shadowfacts@social.shadowfacts.net)</a></strong></div><div>@owncast @gabek it looks like pleroma expects your attachment object to have a mediaType property: https://git.pleroma.social/pleroma/pleroma/-/blob/develop/lib/pleroma/web/activity_pub/object_vali...</div></blockquote>
<blockquote><img src="https://git.pleroma.social/uploads/-/system/project/avatar/2/pleroma_be.png" width="48" align="right"><div>GitLab</div><div><strong><a href="https://git.pleroma.social/pleroma/pleroma/-/blob/develop/lib/pleroma/web/activity_pub/object_validators/attachment_validator.ex">lib/pleroma/web/activity_pub/object_validators/attachment_validator.ex · develop · Pleroma / pleroma</a></strong></div><div>Pleroma backend</div></blockquote>

**Comment by gabek** [comment]
I just gave adding the `mediaType` a shot (and fixed the image description being set), and it didn't seem to make a difference. But it's good to have this anyway.

**Comment by gabek** [comment]
Did some back and forth troubleshooting with [Shadowfacts](https://social.shadowfacts.net/users/shadowfacts) and it works after he tweaked the Pleroma attachment code to accept single objects, per the spec. He commented on the Pleroma issue with the fix.

![image](https://user-images.githubusercontent.com/414923/165659919-8bacc345-d223-4d46-b795-27d9e673fece.png)

**Comment by gabek** [comment]
Still waiting on a PR to be merged by Pleroma.

**Comment by jprjr** [comment]
Hi there - I went through the Pleroma PRs, looks like they've merged a fix into the development branch: https://git.pleroma.social/pleroma/pleroma/-/merge_requests/3706

<blockquote><img src="https://git.pleroma.social/uploads/-/system/project/avatar/2/pleroma_be.png" width="48" align="right"><div>GitLab</div><div><strong><a href="https://git.pleroma.social/pleroma/pleroma/-/merge_requests/3706">Fix owncast (!3706) · Merge requests · Pleroma / pleroma · GitLab</a></strong></div><div>Super-seeds: !3666</div></blockquote>

**Comment by gabek** [comment]
Wohoo! :1st_place_medal: 

Thanks for checking in on it.

**Comment by gabek** [comment]
Last I checked this hasn't yet been released so I haven't seen the fix myself.

**Comment by gabek** [comment]
I think this has been released, but I haven't had a chance to upgrade my Pleroma instance. If anybody else can verify that'd be awesome.

**Comment by gabek** [comment]
Tested with Pleroma 2.5 and all works as expected. Closing.
