### ISSUE TITLE
Web UI v2: Decide on + setup state management

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1854]
It's possible we just use `Context`, but I want to investigate what other options out there. Something far more lightweight than Redux, though.

**Comment by gabek** [comment]
Recoil is working well.

**Comment by bingocaller** [comment]
These days a bit of `Context` and `useReducer` will get you a long way. If we need something more advanced that needs to talk to the back-end I can recommend [React Query](https://react-query.tanstack.com/).

**Comment by gabek** [comment]
Oh nice! I saw Recoil was the new kid in town so I've been experimenting with that. It seems to be pretty clean and easy to use, but if it's too much overhead for what's needed I'll pull it. I'm not familiar with React Query, I'll check that out. Thank you!

**Comment by bingocaller** [comment]
Yeah, I've also heard good things about Recoil but I've yet to try it. React Query isn't specifically for state management, but in a RESTful application it can sometimes fill that same gap that one would otherwise use Redux for.

**Comment by gabek** [comment]
This is currently what I've come up with.

- Recoil is used for global state. Not a lot of components require access to it, and it'd be nice to keep most "view" style components to be "dumb", only rendering values via props.
- The client config store is a central component that needs to know about the entire state of the app. Is chat available, is it connected, what is your chat display name, is video playing, etc.
- These different pieces of state are fed as events into `xstate` state machine and the current "state of the app" is built from that such as: loading, ready, online, offline, goodbye (that time between stream end and chat is shut down).
- Using Recoil selectors we expose boolean states to those that require it with the following simple interface:
```
interface AppStateOptions {
  chatAvailable: boolean;
  videoAvailable: boolean;
  appLoading: boolean;
}
```

It sounds more complicated than it is. I've found this approach to be easy to reason about. I'm sure this will evolve as more requirements come into play, but this is working pretty well right now.
