### ISSUE TITLE
Add documentation for Google Cloud Storage

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1856]
https://owncast.rocket.chat/channel/general?msg=xh2zZexsvEijGRd7Y

1. Go to "IAM & Admin" -> Service Account
2. Create new Service Account with role "Storage Admin - Full control of GCS resources."

Step B

1. Create a bucket in "Cloud Storage"
2. On your Bucket, click on "Permissions" tab
3. Add new permission by click on "Add"
4. New principals: allUsers and role: Storage Object Viewer (to allow public access)
5. On the left menu, click on "Settings"
6. Next, go to Interoperability
7. There will be the request endpoint for the s3 endpoint
8. Click on "Create A Key For A Service Account"
9. Select the account from Step A -> Create Key
10. The access key and secret will be shown
11. The region information is available on "Browser" tab (left menu)

and to setup the CORS: https://medium.com/wesionary-team/configure-cross-origin-resource-sharing-cors-on-a-google-cloud-storage-bucket-79abc2422f52

**Comment by ssentanoe** [comment]
:+1:

**Comment by ssentanoe** [comment]
additional -> change the ACL to fine-grained

And to disable index listing of the bucket, use Storage Legacy Object Reader instead of Storage Object Viewer
https://stackoverflow.com/questions/19124162/how-to-disable-google-cloud-storage-bucket-list-from-acl-control

**Comment by Sachin1939** [comment]
Hey @gabek, I would like to work on this issue. This would be an ideal start for my journey to the open source contribution. Can you please assign this issue to me?

**Comment by gabek** [comment]
Awesome, welcome! The documentation repository lives at https://github.com/owncast/owncast.github.io.

<blockquote><img src="https://opengraph.githubassets.com/33742153c94a597dec43c8ff14cf2aa346d5f31fa7a91893afeed4777a626fe3/owncast/owncast.github.io" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/owncast/owncast.github.io">GitHub - owncast/owncast.github.io: Owncast's public facing web site.  Documentation and info.</a></strong></div><div>Owncast's public facing web site.  Documentation and info. - GitHub - owncast/owncast.github.io: Owncast's public facing web site.  Documentation and info.</div></blockquote>

**Comment by Sachin1939** [comment]
Alright!
