### ISSUE TITLE
Docker-Compose for easy setup

### ISSUE THREAD

**Issue by geekgonecrazy** [owncast/owncast#186]
A docker compose file would be a great addition.  I would envision for now it having:
* owncast
* traefik or caddy.  

You should be able to quickly configure it by adjusting a couple of environment variables in the docker-compose.

Then `docker-compose up -d` has owncast sitting there with reverse proxy ready to go on hosts port 80 and 443.  The rtmp port should also be bound to the host port: 1935.

https://github.com/RocketChat/Rocket.Chat/blob/develop/docker-compose.yml - its commented out here.  But might be a good starting point

**Comment by zvikinoza** [comment]
I would like to contribute to the repo! 🤖

**Comment by gabek** [comment]
Hi zvikinoza, great to meet you!  Thanks for volunteering, we'd love to have you take a look at this!

**Comment by Deepeshac2890** [comment]
I would like to work on this repo . Please assign it to me too.

**Comment by gabek** [comment]
Hey @Deepeshac2890!  That would be awesome, thanks!  Let us know if you have any questions.

**Comment by gabek** [comment]
Hey @Deepeshac2890 Just letting you know, that @geekgonecrazy went ahead and put up a PR for this.
