### ISSUE TITLE
Web UI v2: Chat input autocomplete - chat display names

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1868]
Use tab key to autocomplete:

- Chat display names

How it works:

`@gab<tab>` should autocomplete `@gabek`.

**Comment by gabek** [comment]
I'm guessing we'll need to store emoji and known display names in global state so the text input field has access to them.

**Comment by gabek** [comment]
I'm thinking about pushing this off until a future release. I asked around and nobody replied when I asked if anybody uses this feature in the v1 UI.

**Comment by the-white-light** [comment]
I personally use this feature all the time as a watcher (I don't host the stream). Only downside is it doesn't add a space at the end.

**Comment by gabek** [comment]
I have this half completed, but to be honest I just want to move on from frontend things. So when somebody really says they're missing this it can be worked on in a future release.

**Comment by oxayotl** [comment]
@gabek On the Owncast instance I visit we really really miss that feature! If you could add it we would be so thankful!
