### ISSUE TITLE
Make video segment filename unique

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#187]
Right now if you were to run multiple copies of Owncast and point to the same external storage bucket there's a non-zero chance of having the same file names.

We should append some random identifier into `hls_segment_filename` in the Transcoder as a simple way to create unique segment names.

The solution right now would be to have different buckets for different instances, but it would be nice to not have to do that.

**Comment by anoopmsivadas** [comment]
@gabek  how about adding a timestamp

**Comment by gabek** [comment]
Unfortunately timestamps could collide if two streams were running at the same time.  It's probably _unlikely_ that a high resolution timestamp would collide, but it's certainly possible.

**Comment by anoopmsivadas** [comment]
so I should go with "math/rand" ?

**Comment by gabek** [comment]
You certainly could!  We're also using [`shortid`](https://github.com/dylang/shortid) in places to create identifiers that you can use with `shortid.MustGenerate()`.

**Comment by anoopmsivadas** [comment]
isn't that a node module?

**Comment by gabek** [comment]
Sorry, wrong googling: https://github.com/teris-io/shortid

**Comment by anoopmsivadas** [comment]
can you assign me to this one. 😁

**Comment by gabek** [comment]
Done!

**Comment by anoopmsivadas** [comment]
it seems like i gotta update the test too. can you guide me on how to modify the expected string

**Comment by gabek** [comment]
Sure!

The test will need to know what the segment filename template is going to be, so I'm thinking it would be good to model it after how we're doing `SetInput` and `SetOuput` with the `Transcoder`, and how the test uses that.

1. Add a `SetIdentifier()` to the `Transcoder` and store that value in the instance of the transcoder.  Use that value in `getString()` if it exists.  If it doesn't exist then create an identifier.
1. In `transcoder_test.go` create an identifier and pass it to `SetIdentifier()`.
1. In the test's `expected` you can update the string to where it specifies `hls_segment_filename` to use the new filename template you created, with the identifier you generated.

**Comment by anoopmsivadas** [comment]
Oh That's cool. I was thinking about exposing the identifier and using it with Sprintf(). I can use your solution instead
