### ISSUE TITLE
Forbidden username list does not parse commas.

### ISSUE THREAD

**Issue by funkyhippo** [owncast/owncast#1873]
I'm not sure if this is intended behaviour, so I figured I'd open an issue to discuss it.

Currently, the backend stores the forbidden names list as a comma-separated string. This means that the forbidden names list cannot contain commas as they get parsed as the delimiter when returning the forbidden names list. In addition, the frontend will display your input as-is:

<img width="82" alt="image" src="https://user-images.githubusercontent.com/52957110/164944636-ed4bfb9a-24ce-4af9-8570-1f4a099b6ace.png">

Until you refresh the page to trigger an API call to the forbidden names list as understood by the backend:

<img width="115" alt="image" src="https://user-images.githubusercontent.com/52957110/164944649-d4faa278-1273-461b-aa59-26f8befa898a.png">

My first thought was to change this to a newline delimited list, but I wanted to see if this was intended behaviour to allow admins to bulk-import forbidden names as a comma-separated list in the admin interface.

**Comment by gabek** [comment]
This is a side effect of how this configuration used to look. It used to be a simple text field where you just type names that were comma-separated, and then it got changed to the easier to use UI, but the backing data stayed the same. The best solution would be to treat this as an actual array. I can take care of that and migrate the old data over.
