### ISSUE TITLE
Add icon for authenticate menu item

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1879]
![image](https://user-images.githubusercontent.com/414923/164996351-c499721b-95dd-4539-b5a0-4ca8756fc566.png)

**Comment by t1enne** [comment]
Maybe a Key icon? https://heroicons.dev/?query=key

<blockquote><img src="https://heroicons.dev/static/social.png" width="48" align="right"><div><strong><a href="https://heroicons.dev">Heroicons – Free Open Source SVG Icon Library</a></strong></div><div>New MIT open source SVG icon library designed by Steve Schoger. Solid and stroke variants, one-click copy-paste, and Figma file. Built with Tailwind CSS.</div></blockquote>

**Comment by gabek** [comment]
I think that's a fine choice!
