### ISSUE TITLE
Follow from Friendica

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1880]
When performing a remote follow the following error is displayed in Friendica:

> The network type couldn't be detected. Contact can't be added.

**Comment by gabek** [comment]
See Friendica thread on the topic: https://github.com/friendica/friendica/issues/11442

**Comment by gabek** [comment]
Closing as I didn't get any response from the Friendica folks on the linked issue.

**Comment by Quix0r** [comment]
Does the Friendica instance cause some 404 responses, e.g. in `.well-known` path? I'm not so deeply involved into Friendica code but I can test for you. :-)

**Comment by gabek** [comment]
Unfortunately I don't know of any actual actionable errors that I can work on. The thread says Friendica says 

> "impossible to detect the network type. this contact cannot be aded".

Nobody shared what the root cause of that error was.
