### ISSUE TITLE
Admin UI: log viewer entries per page dropdown doesn't behave correctly.

### ISSUE THREAD

**Issue by funkyhippo** [owncast/owncast#1888]
The admin UI's `# / page` selector does not change the number of logs displayed per page.

<img width="365" alt="image" src="https://user-images.githubusercontent.com/52957110/165982221-1a4ee6c4-3154-4694-8338-4ccf85292f02.png">

## Reproducing

1. Navigate to the admin UI of owncast
2. Go to Utilities > Logs
3. Wait until there are multiple pages of logs, then try selecting a different `# / page` option in the dropdown at the bottom right

### Expected Behaviour

Selecting a different `# / page` should change the number of entries displayed per page.

### Actual Behaviour

The number of rows per page does not change.

### Further Information

I've only had the chance to reproduce this on Chrome 100.0.4896.127, and haven't further investigated the admin UI code. I can further look into it after the upcoming weekend when I have some time if you're not able to reproduce or deal with this.

**Comment by gabek** [comment]
I guess the table component now shows that by default. I'd normally just explicitly turn it off, but it sounds like you'd appreciate the customization so I'll fix it up so it works.

**Comment by gabek** [comment]
ah yup, at least I'm not going crazy.

>  Pagination show size changer by default when total > 50 since 4.1.0

It's fixed.

**Comment by funkyhippo** [comment]
Thanks for the quick fix!
