### ISSUE TITLE
Support for Dreamhost DreamObjects

### ISSUE THREAD

**Issue by roadriverrail** [owncast/owncast#1897]
Hey there!

My Owncast setup is just about complete except for the S3 storage.  I'm using Dreamhost and their cloud infra options, DreamCompute and DreamObjects, to do everything.  It's almost perfect except for the part where I turn on my S3 storage and point it at my DreamObjects bucket, which leads to me getting no video and only a still frame every 30 seconds or so.  The documentation recommended that I file an issue for my storage provider and y'all could help with testing it?  I'd love to know if there was something I missed.

**Comment by gabek** [comment]
If you mean Digital Ocean's Spaces, it's supported, since it's just S3 storage. Others have used it.  While things could change, the documentation should be helpful: https://owncast.online/docs/storage/digitalocean/

If that doesn't help feel free to share the actual errors you're seeing, as that usually points to where the issues are with people's S3 setups.

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="/favicon.png" height="14"> Owncast</div><div><strong><a href="/docs/storage/digitalocean/">Digital Ocean Spaces</a></strong></div><div>250 GB storage + 1 TB Outbound Transfer for $5/mo.</div></blockquote>

**Comment by roadriverrail** [comment]
Sorry, I should have been more clear.  It's DreamObjects, provided by Dreamhost (https://www.dreamhost.com).  They've been my hosting provider for like 25 years at this point, so I figured I'd try them before switching to Digital Ocean.

Anyway, they claim S3 compatibility.  I don't see any errors in my logs when I set things up the way I think they should be, but I also curiously don't see any objects in the bucket while or after streaming, suggesting to me they're not ending up there.

<blockquote><img src="https://www.dreamhost.com/assets/dreamhost_press-3f45d1518e341d4e64dc01e0f424d2193525008fe0f9399ac5690e4e71196628.png" width="48" align="right"><div><img src="/assets/favicons/favicon-f9ebe354d3e28f93ebaa6523488be0049829393ae313ab3b2e6497952c4f295d.ico" height="14"> DreamHost</div><div><strong><a href="https://www.dreamhost.com/">DreamHost | Web Hosting For Your Purpose</a></strong></div><div>Award Winning Web Hosting? Yes, but more importantly, we make sure our customer's websites load fast, stay secure & are up 100% of the time. We guarantee it.</div></blockquote>

**Comment by gabek** [comment]
Oh sorry I misread. You might want to try running Owncast with `--enableVerboseLogging` to see if it has any additional messages to help troubleshoot if nothing is showing up but you have it enabled.

**Comment by roadriverrail** [comment]
Thanks for the tip!  I tried that but I don't really see any errors showing up related to the use of the S3 storage:
```
TRAC[2022-05-06T01:21:25Z] RTMP 208.113.130.230:1935 184.72.5.93:60126 Connected 
INFO[2022-05-06T01:21:25Z] Inbound stream connected.                    
TRAC[2022-05-06T01:21:25Z] Setting up S3 for external storage of video... 
INFO[2022-05-06T01:21:25Z] Video transcoder started using x264 with 1 stream variants. 
TRAC[2022-05-06T01:21:25Z] Cleaning data/hls                            
TRAC[2022-05-06T01:21:26Z] [Type AMF0 Time 0 Len 403 Data ["@setDataFrame","onMetaData",{"duration":0,"fileSize":0,"width":1080,"height":720,"videocodecid":7,"videodatarate":1650,"framerate":30,"audiocodecid":10,"audiodatarate":160,"audiosamplerate":48000,"audiosamplesize":16,"audiochannels":2,"stereo":true,"2.1":false,"3.1":false,"4.0":false,"4.1":false,"5.1":false,"7.1":false,"encoder":"obs-output module (libobs version 27.2.4)"}] Header ] 
TRAC[2022-05-06T01:21:30Z] client closed: objective-trinity 2 184.72.5.93 
TRAC[2022-05-06T01:21:31Z] Adding client 3 total count: 1               
TRAC[2022-05-06T01:21:33Z] client closed: objective-trinity 3 184.72.5.93 
TRAC[2022-05-06T01:21:34Z] Adding client 4 total count: 1               
TRAC[2022-05-06T01:21:35Z] client closed: objective-trinity 4 184.72.5.93 
TRAC[2022-05-06T01:21:36Z] Adding client 5 total count: 1               
INFO[2022-05-06T01:21:55Z] Inbound stream disconnected.                 
TRAC[2022-05-06T01:21:55Z] Inbound stream disconnect requested.         
```

**Comment by roadriverrail** [comment]
Actually, I'm now able to confirm that there are files being stored in the S3 bucket, so I know they're at least getting there.  I've downloaded some of the .ts files out of there and they look just fine, can be downloaded from an incognito window, etc.  I'm not sure if this matters, but I notice the URL to download them is of the format:
https://objects-us-east-1.dream.io/<bucket>/hls/0/stream-lRs4S2l7g1651799768.ts

I did open up my Chrome developer console and noticed a bunch of this, though, which looks like it might be a problem:
```
Access to XMLHttpRequest at 'https://objects-us-east-1.dream.io/owncast/hls/0/stream.m3u8?cachebust=1651800532' from origin 'https://owncast.rhettaultman.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by gabek** [comment]
Good to hear it!  Hopefully you can just enable CORS with your storage provider and you should be good to go.  Looks like they have instructions specifically for that. https://help.dreamhost.com/hc/en-us/articles/216201557-Configuring-CORS-on-a-DreamObjects-bucket

<blockquote><div><strong><a href="https://help.dreamhost.com/hc/en-us/articles/216201557-Configuring-CORS-on-a-DreamObjects-bucket">Security check</a></strong></div></blockquote>

**Comment by roadriverrail** [comment]
Aha!  I really appreciate this.  I'm a kernel hacker who only fakes it in devops!

**Comment by roadriverrail** [comment]
Indeed, this was the only missing part here.  Would anyone on the team like my notes about how to set this all up on Dreamhost?

**Comment by jprjr** [comment]
You may wanna take a look at the doc repo - if you're able, you could open a pull request with a new page for DreamObjects - the area covering S3 providers is here: https://github.com/owncast/owncast.github.io/tree/master/content/docs/storage

Alternatively I'm happy to help write up documentation based on your notes

<blockquote><img src="https://opengraph.githubassets.com/4866fd955592701a686056b074d714664f96f978f02862e5f7637a24fd5f3545/owncast/owncast.github.io" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/owncast/owncast.github.io">owncast.github.io/content/docs/storage at master · owncast/owncast.github.io</a></strong></div><div>Owncast's public facing web site.  Documentation and info. - owncast.github.io/content/docs/storage at master · owncast/owncast.github.io</div></blockquote>

**Comment by roadriverrail** [comment]
Thanks again.  I'll close this issue at this point and I'll do what I can with a general-purpose write-up to get everything running on Dreamhost's DreamCompute and DreamObjects.
