### ISSUE TITLE
Document the API endpoints

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#190]
Would be useful for people to know about, and utilize the endpoints available if they'd like.  Matt had a good example of using the status API to hide the player on his wedding site when it wasn't live.

**Comment by jmhobbs** [comment]
What are you thinking for this?  Swagger/OpenAPI v3 interesting at all or something else?

**Comment by gabek** [comment]
Hey John!!  At first I simply thought just throwing together some Markdown, but I do think putting in a little extra effort to put structure around this with Swagger would pay off as the project grows.  Thanks for making me put some thought behind it 👍

**Comment by jmhobbs** [comment]
For sure! Mind if I knock something together? I’ve been meaning to try out the OpenAPI stuff.

**Comment by gabek** [comment]
I'd love that, that would be awesome!  Thank you!

**Comment by jmhobbs** [comment]
Ok, so I've been messing with it a bit.  Of all the tooling for output, I think (ReDoc)[https://github.com/Redocly/redoc] strikes a balance of customizability and easy rendering.  We should be able to make it blend in with the main site.

I've roughly documented some of the methods, and stuck it on Netlify for a preview.  The admin ones are the primary things too look at.  https://sharp-einstein-5dab8f.netlify.app/ the spec file is here: https://github.com/jmhobbs/owncast/blob/openapiv3-documentation/openapi.yaml

Take a peek, let me know what you think.  I'm going to look at customizing the ReDoc template a bit too.

**Comment by gabek** [comment]
This is so cool, John!  ReDoc looks like a great solution for spitting out that documentation.  Thank you for putting that together and marking up that openapi file!  That's a fantastic starting point to continue to add to.  Did you build the OpenAPI file by hand, or is there some tooling for passing responses through to get that output?

**Comment by jmhobbs** [comment]
I started with [the swagger builder/inspector thing](https://inspector.swagger.io/builder) and generated this [initial doc](https://app.swaggerhub.com/apis/jmhobbs/tinkering/0.1) to try it out.  It felt like I would spend as much time learning that tool as just reading the spec and looking at examples so I bailed on it and wrote the rest by hand.

**Comment by gabek** [comment]
I don't blame you, I'd probably end up doing the same!  Let me know when you've had enough with poking around, no need for you to have to go through, in detail, all the endpoints, I'm happy to take what you started with and run with it if you'd like.  You provided an awesome foundation, since I've never touched Swaggery stuff before.

**Comment by jmhobbs** [comment]
Cool 👍   I finished up the other ones I saw in the router, and pulled some component stuff out to DRY it up a bit.
