### ISSUE TITLE
LDAP integration?

### ISSUE THREAD

**Issue by PolynomialDivision** [owncast/owncast#1900]
Can you add an ldap integration?

**Comment by gabek** [comment]
You didn't even say what the integration would be or do. Stream keys? Admin login? Chat authentication? Lookup of stream details?

But no, I don't believe this would be something people would take advantage of. Something more enterprise focused might be a better fit for you.

**Comment by jeyemwey** [comment]
Hi, if you're looking for viewers authentication, please check if your TLS proxy can provide that. Owncast [will infer](https://owncast.online/docs/sslproxies/#inherit-display-name-from-reverse-proxy) the username from the `X-Forwarded-User` header which your proxy should set.
