### ISSUE TITLE
Minimal changes to the admin to fix styling

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1904]
Since the frontend web UI and the admin are now sharing styling, some colors and layout in the admin may have adjusted in the process.

Some minor tweaks will be needed to make sure things still work, but we're not looking to spend much time on it. Just fix styling and keep the admin how it's been.

**Comment by gabek** [comment]
I took a stab at a start of some of the colors for the admin. This time we need a dark mode and a light mode because people complained about it to me last time that it was too dark. So the light mode is the default colors from the web app and the dark mode colors still need to be set. I started with some of them. Any help picking and fixing elements that need to be set with a color would be appreciated.  See `public/styles/admin/main-layout.css` with the note on top "This is for the admin only!" when making these changes.

![image](https://user-images.githubusercontent.com/414923/210672659-b5d03dcb-40da-4314-bdbf-74aa441a0baf.png)

**Comment by gabek** [comment]
Scratch that: It has been determined that we're going light-mode only for the admin.

**Comment by gabek** [comment]
Ugh. The admin used to look so nice before, but with the shared styling it looks so bad now.

**Comment by gabek** [comment]
Closing this. While the admin doesn't look good, it looks cohesive. Any future issues can be filed and addressed individually.

**Comment by gabek** [comment]
Re-opening since it looks bad.

**Comment by thisprojects** [comment]
@gabek Can I be assigned to this one plz 👍

**Comment by gabek** [comment]
Absolutely, thank you!

**Comment by thisprojects** [comment]
@gabek 

Going to suggest we re-instate these borders - what do you think? I'm not sure about the colours though. Text colour deffo needs changing. 

![Screenshot 2023-03-10 at 22 29 50](https://user-images.githubusercontent.com/34570423/224440298-b65515f7-b843-46ee-a5bc-1bf4d8c2f16d.png)

**Comment by gabek** [comment]
Agreed! The borders certainly look better.

**Comment by thisprojects** [comment]
@gabek 
Admin homepage styling - all using theme colours. Thoughts? 

![Screenshot 2023-03-10 at 23 38 19](https://user-images.githubusercontent.com/34570423/224448426-e7021e77-179a-483c-b200-f8fe808867ff.png)

**Comment by gabek** [comment]
Seems alright! I'm not used to seeing that teal/greenish color in use places, but I'm totally up for giving it a spin. It's easy enough to change to something else if we decide it doesn't work out :)

**Comment by thisprojects** [comment]
I agree on the green, might need some more colours adding to the palette 🤔. The purple probably makes more sense, but it just seems too bright against the lighter background.
