### ISSUE TITLE
Remove unlicensed emoji and add in some freely licensed ones

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1916]
It was suggested we make sure we have the custom emoji people expect to see and want to use. So those who are knowledgeable about such things should help curate what we ship!

We ship some that are playing pretty loose with copyright, right now, so I'm not sure what the accepted standards on such things are.

**Comment by Suzie97** [comment]
Can you give me a list of the custom emoji needed?

**Comment by gabek** [comment]
I was told that "Owncast should have emoji that streamers expect", so I was hoping somebody who uses a lot of emoji both with Owncast and other platforms could chime in and help us curate what emoji they'd expect.  I'm certainly not an emoji person, I don't know what some of them mean and not a good judge of what we should have and what we shouldn't.

So I unfortunately don't have the answer.

**Comment by Suzie97** [comment]
Hmm, how about we do a little user research to analyse what emojis users want/use?

**Comment by gabek** [comment]
I'm totally on board, but true user research of Owncast users have been very difficult in the past given the anonymous nature of Owncast servers.

The only servers we know about are the people who choose to list themselves on the directory, and none of those servers have been active in discussions in the past.

So the project is limited to just guessing what people want. And the project has mostly been just me, so I just try my best.

**Comment by Suzie97** [comment]
> I'm totally on board, but true user research of Owncast users have been very difficult in the past given the anonymous nature of Owncast servers.
> 
> The only servers we know about are the people who choose to list themselves on the directory, and none of those servers have been active in discussions in the past.
> 
> So the project is limited to just guessing what people want. And the project has mostly been just me, so I just try my best. 

Oh yes we've discussed this before, my bad. Sorry I forgot that, but I think it we can still ask some people who don't necessarily use owncast. Their emoji needs should be similar no?

**Comment by gabek** [comment]
Not sure! I was hoping this would be really simple. I'd ask around for somebody who uses Owncast to share their opinions on what we should ship with, and then get those made so we can add them to Owncast. And the ones they say we should remove we'd remove.

The only person who answered me simply said he wouldn't help.

Things like this I'm doing because streamers ask for it, but when when I ask for more details or help they refuse to engage at all, so I'm just going to no longer worry about it as it's a lost cause.

**Comment by gabek** [comment]
Reopening this issue with new specifics.

- We should remove the Party Parrots due to the license generally being unknown and unproven. https://github.com/jmhobbs/cultofthepartyparrot.com/blob/main/LICENSE
- We should remove any copywritten images such as the Animal Crossing stuff.
- A person on the Fediverse posted some freely licensed images we could add. https://mastodon.art/@pollomostro/102708680170948576
- We should create a new document with the licenses for all the emoji we bundle and ship with.

<blockquote><img src="https://opengraph.githubassets.com/fc50aec9ca011366a4241d9c0682cb875a0f733ff344c665bc13e6df4d10614d/jmhobbs/cultofthepartyparrot.com" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/jmhobbs/cultofthepartyparrot.com">cultofthepartyparrot.com/LICENSE at main · jmhobbs/cultofthepartyparrot.com</a></strong></div><div>PARTY OR DIE. Contribute to jmhobbs/cultofthepartyparrot.com development by creating an account on GitHub.</div></blockquote>
<blockquote><img src="https://cdn.masto.host/mastodonart/media_attachments/files/003/645/956/original/7a27fc65ef079015.png" width="48" align="right"><div><img src="/packs/media/icons/favicon-48x48-c1197e9664ee6476d2715a1c4293bf61.png" height="14"> Mastodon.ART</div><div><strong><a href="https://mastodon.art/@pollomostro/102708680170948576">Pollomostro🐣 (@pollomostro@mastodon.art)</a></strong></div><div>Attached: 4 images

Pinned post for convenience.
All set under creative commons license. Patreon links but public posts.
Llama is the last one.

https://www.patreon.com/posts/26981786 Chick
https://www.patreon.com/posts/29579176 llama
https://www.patreon.com/posts/28969921 chipmunk
https://www.patreon.com/posts/26247246 Bunny animated
https://www.patreon.com/posts/25654254 Bunny
https://www.patreon.com/posts/25281178 Dog</div></blockquote>

**Comment by gabek** [comment]
Like I mentioned above, I'm no expert on what types of emoji we "should" have, but if we had some idea maybe we could commission this person above to make us some?

**Comment by MFTabriz** [comment]
If we get to the point of commissioning an artist to design emoji for Owncast, we can make a fedi post for it and ask @Curator@mastodon.art to boost it.

**Comment by gabek** [comment]
Just went through and removed unlicensed images. There are three remaining that are likely fine, but I don't know the license for them explicitly, so they may also have to be removed.

- alert
- banana dance (I think this one is ok?)
- thanks

**Comment by MFTabriz** [comment]
I did a quick search:
- alert: couldn’t find a source with license ❌ 
- banana dance: this is from [Peanut Butter Jelly Time]( https://knowyourmeme.com/memes/peanut-butter-jelly-time), created by Ryan Gancenia Etrata and Kevin Flynn. I have not seen a free license on it ❌ 
- thanks: Raster rendering of a font is not subject to copyright in the U.S. and therefore is in the public domain ✔️

**Comment by gabek** [comment]
I removed more emoji and made changes to support emoji subdirectories. I copied over two of the emoji collections from above. I'm trying to figure out how to donate to this artist without signing up for a monthly Patreon.

I'd really hate to only ship with "cutsey" emoji, however, as it makes it look like Owncast is only for a specific type of person streaming a specific type of content, so hopefully this can be resolved. I'd rather ship with zero custom emoji than to only ship with these.

If we keep these we should also rename them since they should be `dog001` or something because `img001` isn't helpful.

**Comment by MFTabriz** [comment]
what do you think about adding [Blob emojis](https://blobs.gg)? the official ones are released under the Apache License 2.0

**Comment by gabek** [comment]
Added!

**Comment by gabek** [comment]
Chatting with https://fosstodon.org/@FrugalGamer@snug.moe about a possible commission to possibly make a handful of custom images that work for most types of streams. 

<blockquote><img src="https://snug.moe/files/thumbnail-2981791f-2689-4f90-92f9-6973b4b3e959" width="48" align="right"><div><img src="https://snug.moe/files/c36be58c-b49e-41ef-8a0c-532df5ac8c08" height="14"> Snugly Moe Moe</div><div><strong><a href="https://snug.moe/@FrugalGamer">@FrugalGamer</a></strong></div><div>I'm owned by cats and I make things. I usually have some kind of creative project going on or another.

Http://thefrugalgamer.net

#Gaming #PixelArt #RetroWeb #RetroGaming #ILoveCats</div></blockquote>

**Comment by FrugalGamer** [comment]
> Chatting with https://fosstodon.org/@FrugalGamer@snug.moe about a possible commission to possibly make a handful of custom images that work for most types of streams.
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/564f5bbe87f96a9df0a6ffcc849522141d9f482aa6217bca1ee35e137fb8b536/68747470733a2f2f736e75672e6d6f652f66696c65732f7468756d626e61696c2d32393831373931662d323638392d346639302d393266392d363937336234623365393539"><img alt="" height="14" src="https://camo.githubusercontent.com/427f6d903f35f558529f388c2607c6f744ffe1cefe530a3266530a6260fdf2ba/68747470733a2f2f736e75672e6d6f652f66696c65732f63333662653538632d623439652d343165662d386130632d353332646635616338633038"> Snugly Moe Moe**[@FrugalGamer](https://snug.moe/@FrugalGamer)**I'm owned by cats and I make things. I usually have some kind of creative project going on or another.
> > [Http://thefrugalgamer.net](Http://thefrugalgamer.net)
> > #Gaming #PixelArt #RetroWeb #RetroGaming #ILoveCats

Hello there! Any idea of what format you're needing for these? I assumed SVG so that they'll scale well, but I always ask to make sure.

<blockquote><img src="https://snug.moe/files/thumbnail-2981791f-2689-4f90-92f9-6973b4b3e959" width="48" align="right"><div><img src="https://snug.moe/files/c36be58c-b49e-41ef-8a0c-532df5ac8c08" height="14"> Snugly Moe Moe</div><div><strong><a href="https://snug.moe/@FrugalGamer">@FrugalGamer</a></strong></div><div>I'm owned by cats and I make things. I usually have some kind of creative project going on or another.

Http://thefrugalgamer.net

#Gaming #PixelArt #RetroWeb #RetroGaming #ILoveCats</div></blockquote>

**Comment by gabek** [comment]
Yeah SVG would be great!

**Comment by FrugalGamer** [comment]
Ok, let me do some research and brainstorming real quick, and then I'll probably get back to you tomorrow--I'm in Central time zone, btw, so we're getting close to bedtime atm. Feel free to drop me a message if you need to before then!

**Comment by FrugalGamer** [comment]
Ok I'm back! I've been brainstorming some ideas for different "emotions" to depict, and I'd like to see which ones appeal to you the most. There are more than 10 here, and they might also help inspire a few of your own.
-Dancing
-Raid
-Hype
-Thank you
-Alert
-Over it
-Pride
-Please
-Party
-Applause
-Deal with it
-Devil horns
-Bob Ross
-Nyan
-DnD Wizard/Dice master
-Matrix code

I've also brainstormed a few characters. They're not colored yet, and they're all "generic," since I'm just trying to get an aidea of what you like. Let me know which you like the most and they we can move in that direction.
![mockups (1)](https://user-images.githubusercontent.com/120864187/208316474-229549b2-fc5c-419d-996c-b5c70cbdb97a.png)

**Comment by gabek** [comment]
Fantastic, thank you for collecting those! In looking at options through the lens of different kinds of streams (events, iptv, music, games, performance)  maybe these would be useful in many of those scenarios:

- thank you
- dancing
- Applause
- Alert
- Party

I love those characters! Especially the middle TV looking guy as that kind of points to video. And if we're going to do custom we might as well tailor it to Owncast. What do you think @MFTabriz?

**Comment by MFTabriz** [comment]
I think we should ask various streamers (and/or monitor their chat to see) which of the current emojis they use the most. IMO the important thing is to give them a replacement for the ones we have recently removed (mostly dancing parrots). Maybe a post on fedi can give us some hints on streamer’s favourite ones.

By the way, if we get a mascot for Owncast we can use it as the base for some of our designs.

**Comment by gabek** [comment]
I'm afraid if we had to ask others for their opinion nothing would ever get done. I've had little to no success ever getting anybody who uses Owncast to give feedback. See my frustration above on this topic.

I've been having to make my own decisions in the dark and hope they're good enough that people relatively agree with them. That's what needs to happen here, as well. I don't mean to come off negative, but I've done my fair share trying to engage with people on this project for a couple years now and I've mostly given up.

And while sure, a mascot would be cool, that's far out of scope here to rebrand the project.

**Comment by MFTabriz** [comment]
People are just people. Their priorities in life change over time. As more and more people use the Owncast, a community will grow around it based on their mutual needs. I know it’s frustrating but it is a chicken-and-egg problem and we must try engaging with them even if we get only a couple of feedback here and there.

Give me a few days to gather quick data on the emoji usage and report back here.

**Comment by MFTabriz** [comment]
I went around and asked all the Owncast streamers I knew and all the online streams in the directory I encountered. I got feedback from 12 streamers. 5 of them mostly use Unicode emoji or their own custom ones. Other 7 streamers' most used custom emojis are:

- [:moonparrot:](https://watch.owncast.online/img/emoji/moonparrot.gif)
- [:rotatingparrot:](https://watch.owncast.online/img/emoji/rotatingparrot.gif)
- [:sadparrot:](https://watch.owncast.online/img/emoji/sadparrot.gif)
- [:vikingparrot:](https://watch.owncast.online/img/emoji/vikingparrot.gif)
- [:pizzaparrot:](https://watch.owncast.online/img/emoji/pizzaparrot.gif)
- [:rythmicalparrot:](https://watch.owncast.online/img/emoji/rythmicalparrot.gif)
- [:everythingsfineparrot:](https://watch.owncast.online/img/emoji/everythingsfineparrot.gif)
- [:explodyparrot:](https://watch.owncast.online/img/emoji/explodyparrot.gif)
- [:headsetparrot:](https://watch.owncast.online/img/emoji/headsetparrot.gif)
- [:keanu_thanks:](https://watch.owncast.online/img/emoji/keanu_thanks.gif)
- [:bananadance:](https://watch.owncast.online/img/emoji/bananadance.gif)
- Star wars and also game related ones in general

And here’s a couple of notes from streamers:
- it’s nice to have a wide variety of options
- if possible, import some of https://mutant.revolt.chat emojis. Specially the "gender/relationship/sexuality" ones

<blockquote><img src="https://mutant.revolt.chat/assets/embed.png" width="48" align="right"><div><strong><a href="https://mutant.revolt.chat">Mutant Remix</a></strong></div><div>Mutant Remix brings a new twist to the good old emojis that have become a part of our daily conversations.</div></blockquote>

**Comment by gabek** [comment]
I guess if I had to convert that list into generic themes:

- Moon parrot: Something space related
- Rotating: I have no idea what this represents
- Sad: Sad - Covered by built-in unicode options
- Viking: I have no idea what this represents
- Rhythmical parrot: Dancing, music, fun
- Everything is fine: "Dumpster fire"
- Headset parrot: Dancing, music, fun
- Keanu thanks: Appreciation
- Banana dance: Dancing, music, fun

So if I had to create a list from this:

- Something representing dancing, music, fun
- Something representing "dumpster fire"
- Something representing appreciation

I was talking to @gingervitis the other day and was wondering since parody falls under fair use, what if we re-made unlicensed or proprietary licensed works as a parody? Would a "dancing cucumber" be allowed? What about Party Pigeon?

**Comment by gabek** [comment]
I'm going to remove this from the v0.1.0 milestone so it's not a blocker for the next release. This task will be complete when it's complete.

**Comment by gabek** [comment]
To have a clearer overview of what's currently being bundled I created a new Storybook story to reflect it:

https://owncast.online/components/?path=%2Fstory%2Fowncast-assets-emoji--page&globals=backgrounds.value%3A%21hex%28333333%29

**Comment by gabek** [comment]
Since there's nobody around who is opinionated about what emoji are supplied I'm going to close this issue. I don't feel comfortable just making up things that nobody would actually want.
