### ISSUE TITLE
Web UI v2: Adjustable chat width

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1918]
Sometimes I wish chat had more real estate, but sometimes I don't. It would be really cool if we could drag the width of the chat column to adjust the layout dynamically.

I haven't looked into what it would take to pull this off. It can get pushed out if it's too much for this rewrite, but it'd be a nice touch.

**Comment by t1enne** [comment]
we'd have to keep chat width inside our state, since the antd sider component (used in our chat) requires a fixed width value. Then we can just create a mouse event on the chat's left border, which will change said width. I'm not sure if it's really worth it, but it's doable!

**Comment by janWilejan** [comment]
#3113 replaces the antd sidebar component with a flex column. Chat width is no longer stored as state anywhere. Adjusting chat width is as simple as changing the width of `#chat-container`. It looks like it can be as small as about 200px or as big as half the page before the page starts looking funny.

Assign me this issue.

**Comment by gabek** [comment]
This would be a really neat addition, thanks for offering, Jan!
