### ISSUE TITLE
Username length should be validated server-side

### ISSUE THREAD

**Issue by pixeldesu** [owncast/owncast#1919]
Probably a low priority issue, but currently users can just adjust the `maxlength` attribute of the username field to get usernames longer than the 60 by default, and can cause text in the overlays to overflow. Not really critical, but maybe a small consideration to make.

(For the UI, something like `text-overflow: ellipsis` would suffice for usernames to prevent major breakage)

**Comment by gabek** [comment]
I don't think 60 was even an attempt to set name limits, it's not really something I've put any thought into. Something like 10 characters probably makes more sense.

**Comment by WPettersson** [comment]
I'm not sure if the 10 characters is for "usernames overflow at this point" or "maximum username length", but either way  10 seems very restrictive (unless it's something you would expect users to be able to edit easily). Most FirstnameSurname combinations would be over 10, as would things along the lines of BarryTheHorse. I'd suggest 32 for a sensible default.

**Comment by gabek** [comment]
I was thinking along the lines of IRC, where I think the max length is 9, but I don't actually have any preference. 32 is fine too.
