### ISSUE TITLE
Mobile testing

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1929]
Since I'm not in the habit of testing our new layout and components against mobile/narrow windows, we should have a way to automate this in some fashion.  Previously, for web ui v1, I had Puppeteer take automated screenshots of different sizes, but unless I went out of my way to go look at them, they were silently ignored.

Chromatic, the company that makes Storybook, suggests we use them for automated visual testing.  https://storybook.js.org/tutorials/visual-testing-handbook/react/en/automate/

I don't know, maybe we should use it and not think too much of it? We're already using Storybook so maybe it's worth just using the entire ecosystem to make testing easier.

**Comment by gabek** [comment]
I setup Chromatic just to see how it works and to see if it's useful to us. TBD on if it helps with this mobile testing use case or any other UI testing.

**Comment by gabek** [comment]
See #1926 for a general issue on testing, not mobile specific.

**Comment by gabek** [comment]
I started work on this, but due to churn in design I must stop because I cannot work on UI tests of the UI is going to be changing.

**Comment by juliana-mol** [comment]
Hi, it is not specifically related to this issue but to the project testing as the whole. I would like to measure the overall code coverage for this project a potentially contribute to increase that. Could you give me a hint how should I do that ? I have already taken a look at the test folder where tests are either load or automated but I do not know how can I measure the code coverage for the project as the whole. Do you also have some unit tests for this project ?

**Comment by gabek** [comment]
Hi there, would you mind opening a new issue specifically related to this topic you'd like to discuss just so things are organized? Thanks!
