### ISSUE TITLE
Chat Text field not visible in portrait mode/Android

### ISSUE THREAD

**Issue by ErAzOr2k** [owncast/owncast#1933]
Hi,

unfortunately the chat text field is not visible on Android in portrait mode.

I testet it with Chrome and Edge. I don't know how it behaves on iOS.

Regards v20220526-nightly-docker.

![Screenshot_2022-05-27-09-58-36-108_com android chrome](https://user-images.githubusercontent.com/8685648/170658153-b3e55125-4493-4d2a-aa20-ea2e247af12d.jpg)

**Comment by gabek** [comment]
Just a note: This was for web ui v1, but I'm keeping it open with the web ui v2 work just to make sure this issue does not persist in the new components.

**Comment by gabek** [comment]
Closing as this is resolved in the web rebuild. 

![image](https://user-images.githubusercontent.com/414923/198814429-22f6c86c-3e0e-4377-aff4-7a61775722d1.png)

**Comment by gabek** [comment]
Oh no. This has returned with all the mobile height work that has been taking place. 

![image](https://user-images.githubusercontent.com/414923/210037799-a0b951dd-8a47-4448-a103-ef90b107f854.png)

**Comment by gabek** [comment]
This looks to be connected to #2499 so this will likely be closed when that one is.

**Comment by gabek** [comment]
Closing this in favor of specific webv2 issues. https://github.com/owncast/owncast/issues/2595 has been filed.
