### ISSUE TITLE
Auto username generator

### ISSUE THREAD

**Issue by thefirst100yearsaredifficult** [owncast/owncast#1943]
Hey guys, I would like to know if there is a way to change the wordlist that the username generator uses and also where that file/function is located, if it exists ofc. 
![Screenshot_1](https://user-images.githubusercontent.com/57727089/172639176-17a90ea6-3d0e-4942-931d-52b50cbecb76.png)

Thank you for the help, very cool project.

**Comment by gabek** [comment]
You can change the names in the admin, under the chat configuration `Default usernames`. If you want to actually change the source instead you can edit https://github.com/owncast/owncast/blob/develop/utils/phraseGenerator.go.

<blockquote><img src="https://repository-images.githubusercontent.com/266445736/4f82fb80-a5b1-11ea-8f1c-69d316f861b5" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/owncast/owncast">owncast/phraseGenerator.go at develop · owncast/owncast</a></strong></div><div>Take control over your live stream video by running it yourself.  Streaming + chat out of the box. - owncast/phraseGenerator.go at develop · owncast/owncast</div></blockquote>

**Comment by jeyemwey** [comment]
Hi, the username is generated from an adjective and a name. You can find the code here: `utils/phraseGenerator.go`

If you have a defined list of "good" usernames, you can add those in the admin panel, and then only that list will be used.

Hope this helped. If you have any more questions, just go ahead :)
