### ISSUE TITLE
Video variant admin interface should start with the default setting values

### ISSUE THREAD

**Issue by aral** [owncast/owncast#1946]
The default video variant that installs with Owncast is 1.2Mbps@24fs

![Screenshot from 2022-06-13 11-46-01](https://user-images.githubusercontent.com/41798/173337976-a38859b0-3b1e-4942-a0e3-5309d5f8fa40.png)

However, if you go to add a new variant, it defaults to 800kbps.

![image](https://user-images.githubusercontent.com/41798/173337954-41dc7d25-c505-469d-a654-a4b89daf83e2.png)

It would be more consistent if it defaulted to 1200kbps @ 24fps. This would also make it easier for people to revert to the default should they have deleted/changed it.

And/or the interface could have a link to revert to the default settings.

## Use case

I had to do a fresh install to find out what the default video setting was when trying to revert to it.

**Comment by JacobWrenn** [comment]
Hi @gabek I would be happy to look at this if helpful?

**Comment by gabek** [comment]
Absolutely, thanks!

**Comment by JacobWrenn** [comment]
@gabek would it be sufficient to update the client `config-constants.tsx` to match the server defaults or would it be preferable to have the client query the server to get the default?

**Comment by gabek** [comment]
Yeah! I think updating the `DEFAULT_VARIANT_STATE` to match should be sufficient. Thanks for checking in!
