### ISSUE TITLE
Convert SVG logo to PNG automatically for fediverse use or allow upload of separate PNG logo

### ISSUE THREAD

**Issue by aral** [owncast/owncast#1947]
## Use case

I have an SVG logo with fine lines that works great in Owncast’s own interface and in embedded video players.

However, since that logo cannot be used for fediverse purposes (as apparently Mastodon doesn’t support SVG logos, at least), I’m faced with the option of:

 - Having a PNG logo that doesn’t scale well anywhere
 - Having the default Owncast logo for fediverse use

## Suggested feature

Ideally, of course, fediverse clients should accept SVGs for profile images.

Barring that, it would be great if Owncast could automatically convert uploaded SVGs into PNGs to use for fediverse purposes. I don’t know how much heft that would add in terms of a library to do this so, if the weight/value ratio is low, the option to upload a separate PNG logo for fediverse use only would be very useful.

**Comment by gabek** [comment]
Unfortunately you've been through the same through process I have, and the resulting solution was simply to stop supporting SVGs.

Starting in 0.0.12 we won't allow you to upload them anymore, but if you already have one saved it'll continue to be used.

It's disappointing, but it's exactly what you said: other platforms don't support them, and sharing Owncast links is increasingly important and everyone's links were looking bad. And the requirements to convert a SVG to a PNG on the fly would require either a library that supports "most" of SVGs features, making be believe people would be getting broken conversions, or bundling a copy of chrome into Owncast as a headless browser. A mess all around.

So if other platforms don't support SVGs then it makes sense for Owncast not to, either. And having two separate images I'm afraid would be confusing. So hopefully a PNG will do. Sorry about that!
