### ISSUE TITLE
Hide/disable “Upgrade to vN” link if version N of Owncast is already installed

### ISSUE THREAD

**Issue by aral** [owncast/owncast#1951]
The “Upgrade to vN” (e.g., “Upgrade to v0.0.11”) link in the admin interface displays even if that version of Owncast is already installed.

## Screenshot

![image](https://user-images.githubusercontent.com/41798/173893093-496835e5-6914-427f-bac5-33a147928be5.png)

**Comment by gabek** [comment]
It shouldn't be, I'll have to look into why that's no longer working.

**Comment by aral** [comment]
Not having looked at the code, wonder if it’s because the database update process that kicks in when Owncast runs doesn’t update the stored version (if the version is stored/read from somewhere under /data that is).

**Comment by gabek** [comment]
For whatever reason I'm not able to reproduce this.

**Comment by gabek** [comment]
Closing due to lack of reproducability.
