### ISSUE TITLE
is it available with mobile apps ?

### ISSUE THREAD

**Issue by Joseph-Nathan** [owncast/owncast#1954]
is it available with mobile apps ?

**Comment by gabek** [comment]
Owncast supports the HLS video standard and any mobile app that can play HLS video can watch an Owncast stream.

**Comment by Joseph-Nathan** [comment]
thanks for fast reply , 
is it available to start cast from mobile app ?
is there any doc, how to integration with flutter ?
is there any doc, how to integration with digital ocean server or any un famous server ?

**Comment by gabek** [comment]
These links might be able to help you:

- https://owncast.online/docs/watching-on-tvs/
- https://marketplace.digitalocean.com/apps/owncast

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="/favicon.png" height="14"> Owncast</div><div><strong><a href="/docs/watching-on-tvs/">Watching an Owncast Stream on Televisions</a></strong></div><div>The web isn't the only option for watching an Owncast stream.</div></blockquote>
<blockquote><img src="https://marketplace-assets.digitalocean.com/logos/owncast-10.svg" width="48" align="right"><div><img src="/static/favicon-16x16.png" height="14"> DigitalOcean</div><div><strong><a href="https://marketplace.digitalocean.com/apps/owncast">Owncast Hosting | DigitalOcean Marketplace 1-Click App</a></strong></div><div>Owncast is an open source, self-hosted live video and chat server for use with existing popular broadcasting software.</div></blockquote>

**Comment by gabek** [comment]
We now have a list of apps that might be useful for watching Owncast streams: https://owncast.online/docs/watching-streams/

<blockquote><img src="https://owncast.online/img/owncast-logo-1000x1000.png" width="48" align="right"><div><strong><a href="https://owncast.online/docs/watching-streams/">Watching on TVs and Devices | Owncast - Free and Open Source Livestreaming</a></strong></div><div>Overview of all supported devices and platforms for watching Owncast streams on televisions and streaming devices.</div></blockquote>
