### ISSUE TITLE
Restreamer By Datarhei

### ISSUE THREAD

**Issue by Restreamdev** [owncast/owncast#1958]
i cant live stream from restreamer to owncast because owncast protocol is rtmp
and restreamer have rtmps 
but i can stream from obs 
my question is how can i edit rtmp and replace rtmps

**Comment by gabek** [comment]
Owncast does not currently support rtmps. You should ask Restreamer to support rtmp, as it is a standard.

**Comment by Restreamdev** [comment]
> Owncast does not currently support rtmps. You should ask Restreamer to support rtmp, as it is a standard.

ok sir thanks you very much for reply
