### ISSUE TITLE
Fix API documentation "integrations/chat/updatemessagevisibility" -> /api/integrations/chat/messagevisibility

### ISSUE THREAD

**Issue by iamsajidjaved** [owncast/owncast#1966]
Hello, hope you're doing well!

I'm integrating the below API but I get the error 404. The base URL everything is correct because I'm using other APIs and the token has also admin privileges.

[https://owncast.online/api/latest/#tag/Integrations/paths/~1api~1integrations~1chat~1updatemessagevisibility/post](https://owncast.online/api/latest/#tag/Integrations/paths/~1api~1integrations~1chat~1updatemessagevisibility/post)

Waiting for your help.  Thanks

**Comment by gabek** [comment]
Looks like the documentation is wrong and it's actually `/api/integrations/chat/messagevisibility`. Let me know if that still doesn't work.

**Comment by iamsajidjaved** [comment]
It worked.
Also please update the swagger file. 

Thanks.
