### ISSUE TITLE
Issue with installer script on macOS

### ISSUE THREAD

**Issue by lecoyote418** [owncast/owncast#1968]
I'm trying to install on macos 10.15.17 with the curl/bash install script and I get:

`bash: line 32: conditional binary operator expected
Your Owncast installation did not complete successfully.
Please report your issue at https://github.com/owncast/owncast/issues`

I can't find the reason why the bash script fails at line 32. Is this a bug? thanks

**Comment by gabek** [comment]
Unfortunately I don't have access to a copy of macOS that is that old, so I'm unable to test it. The installer is working as expected on Linux, under bash, however.

**Comment by lecoyote418** [comment]
Thanks for the reply. I just tried in macOS 11.6.7 and 12.4 and I get the same error.

**Comment by gabek** [comment]
Looks like macOS bash doesn't support some things because it's super old. Hopefully this should fix it. Thanks for letting me know.
