### ISSUE TITLE
Sometimes I'm unable to connect and get the below errors in the logs

### ISSUE THREAD

**Issue by iamsajidjaved** [owncast/owncast#1980]
I can't connect for a while and see the below errors in the logs:

1. Consider increasing the value for the 'analyzeduration' and 'probesize' option
2. [flv @ 0x5f415c0] Could not find codec parameters for stream 0 (Video: h264, none, 3000 kb/s): unspecified size
3. Error marking filters as finished
4. Cannot determine format of input stream 0:0 after EOF
5. transcoding error. look at data/logs/transcoder.log to help debug. your copy of ffmpeg may not support your selected codec of libx264 https://owncast.online/docs/codecs/

Can anyone help me with these?

**Comment by gabek** [comment]
You say "sometimes" you can't stream. What differences are there between when you can and when you can't? Are there any settings that are different?  What software and settings are you using to stream?

I'd take a look at the Troubleshooting page.  Specifically https://owncast.online/docs/troubleshooting/#if-you-are-immediately-disconnected-and-your-stream-wont-begin.


<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="/favicon.png" height="14"> Owncast</div><div><strong><a href="/docs/troubleshooting/">Troubleshooting</a></strong></div><div>Some categories of issues you might run into and some next steps to help troubleshoot.</div></blockquote>

**Comment by iamsajidjaved** [comment]
All my streamers use this app https://play.google.com/store/apps/details?id=com.nabiapp.livenow&hl=en&gl=US. They all have the same configuration. But sometimes this issue appears. Like once a day when one streamer disconnects and another wants to connect.

**Comment by gabek** [comment]
Do you get the same errors with different broadcasting software as well?

**Comment by iamsajidjaved** [comment]
No I didn't try this with another app
