### ISSUE TITLE
No option to change default username

### ISSUE THREAD

**Issue by iamsajidjaved** [owncast/owncast#1982]
I'm struggling with changing the default username of the admin panel. But I can't see the option to change. And in the docs, I'm also unable to find the solution. 

Can anyone help me with changing the admin panel username?

**Comment by gabek** [comment]
This isn't something that is customizable outside of altering the source code. I'm guessing you want to give people the stream key but not allow them to log into the admin, and want to try security by obscurity by changing the username. Owncast is single tenant software and this isn't a use case that the project focuses on. You may be able to do any kind of customization via your reverse proxy, however, but this isn't a use case I've ever looked into.
