### ISSUE TITLE
Received report that backup file was unable to be restored

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1983]
I wasn't able to reproduce it with any of my local backup files, however.

- First backup file he received error: "No such table"
- Second backup file he received error: "unable to read backup file gzip: invalid header"

**Comment by ThomasChr** [comment]
Seems to me kind of pointless without having the backup file in question…

**Comment by gabek** [comment]
Thanks for the help.

**Comment by mattdsteele** [comment]
Edited - my original report was an issue on my side; I was using the wrong file.

I used the file in `data/backup/owncastdb.bak` and it migrated successfully.

**Comment by gabek** [comment]
If you want to try and gunzip it yourself, it should just be a plain text sql file that's gzipped.

**Comment by mattdsteele** [comment]
Yeah my issue was that I had earlier created a manual "backup" of the sqlite file with a `cp owncast.db owncast.db.bak`, and was trying to restore that. And the filename was *just* close enough to the documented process that no alarm bells went off.
