### ISSUE TITLE
Update URL to HTTPS

### ISSUE THREAD

**Issue by TotalCaesar659** [owncast/owncast#1994]
Please update this URL to HTTPS for security reasons.
![0](https://user-images.githubusercontent.com/14265316/178142235-735b3579-b6b7-47b7-aa07-067cfedba577.jpg)

**Comment by gabek** [comment]
I don't think I'm fully understanding your request. What is wrong with how it is? What are the "security reasons" that are currently a problem?

![image](https://user-images.githubusercontent.com/414923/178154453-8888427e-f26d-460a-b8b7-e004550a6c19.png)

**Comment by MFTabriz** [comment]
I think they are referring to the link on the github itself:

`<a title="http://owncast.online" role="link" target="_blank" rel="noopener noreferrer nofollow" class="text-bold" href="http://owncast.online">owncast.online</a>`

it should be to **https**://owncast.online not **http**://owncast.online

PS: in other words: sending people https://github.com > http://owncast.online > https://owncast.online is not a good idea!
