### ISSUE TITLE
Possible abuse of API to spam fedi accounts with auth feature

### ISSUE THREAD

**Issue by H3J0** [owncast/owncast#2000]
I'll make it quick. By re-sending the http post request to the API, it is possible to spam (any?) account on the fediverse with auth code messages.
<img width="604" alt="Screenshot 2022-07-13 at 21 21 31" src="https://user-images.githubusercontent.com/109244700/178818487-f6e10f85-fd64-43e5-88b0-f15e1c4833b4.png">

It is fairly simple. Open the owncast instance, open the network dev tool, get the http post request. You could simply modify and resend the request, or e.x. write simple bash scripts that modify the accounts and spam a ton of accounts. 

<img width="1411" alt="Screenshot 2022-07-13 at 21 22 01" src="https://user-images.githubusercontent.com/109244700/178819336-60f80a9d-7dd0-4786-868e-d9b8e96fd2da.png">

Possible consequences:

- spamming accounts
- getting the API key revoked
- getting the fedi account banned / flagged
- DOS?

I couldn't stress test this method, since I don't have a testing env. Not an API expert, but I thought it is worth mentioning.

**Comment by gabek** [comment]
Seems reasonable to limit this to one request per code expiration window.
