### ISSUE TITLE
Bug: chat embed missing new authentication options

### ISSUE THREAD

**Issue by jprjr** [owncast/owncast#2004]
Hi there - it looks like in v0.0.12, the readwrite chat embed hasn't been updated with the new authentication options

**Comment by gabek** [comment]
Auth is now available in the read/write chat embed for 0.1.0. https://owncast.online/components/?path=%2Fstory%2Fowncast-chat-embeds-read-write-chat--example.

<blockquote><div><strong><a href="https://owncast.online/components/?path=%2Fstory%2Fowncast-chat-embeds-read-write-chat--example">Webpack App</a></strong></div></blockquote>
