### ISSUE TITLE
Refresh on stream end

### ISSUE THREAD

**Issue by docfarzad** [owncast/owncast#2016]
Imagine if you're a non-savvy viewer of an Owncast stream that is embedded on a website. The streamer ends the stream and so the m3u8 file announces the end of the segments. Now the streamer comes back on. But unless the viewer now refreshes the page, they won't see live video again. Can Owncast be configured to automatically refresh itself without user intervention?

**Comment by gabek** [comment]
That shouldn't be the case. I just double checked and indeed, if you use the embed player and stop streaming, and then again start streaming, the player shows that you're back online.

Closing this as it seems to be working as expected, as well as all the web interfaces are being rebuilt, so this existing one is no longer going to be worked on.
