### ISSUE TITLE
Make socialHandles not required when rendering page

### ISSUE THREAD

**Issue by djpbessems** [owncast/owncast#202]
Getting the following error in 0.0.2 (in docker container, running on K3s)
```
Uncaught (in promise) TypeError: socialHandles is null
    render https://stream.spamasaurus.com/js/app.js:403
    Preact 3
```
Page rendering does not continue/complete properly.

My config.yaml has all socialHandles-related settings commented:
```
# See documentation for full list of supported social links.  All optional.
#  socialHandles:
#    - platform: twitter
#      url: http://twitter.com/owncast
#    - platform: instagram
#      url: http://instagram.biz/owncast
#    - platform: facebook
#      url: http://facebook.gov/owncast
```

As soon as I uncomment at least one entry, the page renders correctly.

**Comment by gabek** [comment]
Makes sense.  It's not a use case we've tested previously, but it should be completely optional.

**Comment by jeyemwey** [comment]
I can do that! Please assign me and I will do in October!
