### ISSUE TITLE
When using DynuWebRedirect,can't fullscreen 

### ISSUE THREAD

**Issue by LinusZhang5776** [owncast/owncast#2022]
When use WebRedirect to Mask Url.owncast web page can't fullscreen streaming video.

**Comment by LinusZhang5776** [comment]
website html output
`<button class="vjs-fullscreen-control vjs-control vjs-button vjs-disabled" type="button" title="Fullscreen" aria-disabled="true" disabled="disabled"><span class="vjs-icon-placeholder" aria-hidden="true"></span><span class="vjs-control-text" aria-live="polite">Fullscreen</span></button>`

**Comment by gabek** [comment]
What is DynuWebRedirect? What do you mean by "mask url"?

**Comment by LinusZhang5776** [comment]
> What is DynuWebRedirect? What do you mean by "mask url"?

is type UF DNS service.[https://www.dynu.com/Resources/Tutorials/DynamicDNS/Advancedfeatures/WebRedirect](url)
u can check this live. [http://live.linuszhang.asia/](url)

**Comment by gabek** [comment]
I'm guessing it has something to do with you embedding the entire Owncast interface into an iframe without stating that the iframe is allowed to have full screen features.

You should read the documentation on iframes and work out what needs to be set in order for the functionality you want. This isn't an Owncast issue, so unfortunately I can't help you work out these issues with your provider who's doing the weird embedding.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe

<blockquote><img src="https://developer.mozilla.org/mdn-social-share.cd6c4a5a.png" width="48" align="right"><div><strong><a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe"><iframe>: The Inline Frame element - HTML: HyperText Markup Language | MDN</a></strong></div><div>The <iframe> HTML element represents a nested browsing context, embedding another HTML page into the current one.</div></blockquote>
