### ISSUE TITLE
Feature request: Configurable webroot (and static?) paths

### ISSUE THREAD

**Issue by pbsds** [owncast/owncast#2023]
The `webroot` (and `static`?) folders are expected to be available in the current working directory.
My request is for these paths to be configurable, either at compile-time or at runtime via command line arguments or environment variables.

Currently the `webroot` is [somewhat configurable](https://github.com/owncast/owncast/blob/develop/config/constants.go#L8-L9) at compile-time, but [not all code seem to use this constant](https://github.com/owncast/owncast/blob/develop/controllers/embed.go).

As for the `static` directory unsure whether it is needed. [These lines](https://github.com/owncast/owncast/blob/develop/static/static.go#L10-L14) seem to indicate that they are embedded into the binary. Is this true?

**Comment by gabek** [comment]
This is actually going to be simplified in future releases as both web and static assets will no longer be required to live directly on the filesystem. All these assets will be bundled in the binary. So you won't have to know, or care, where these files are.

I don't know if that answers the root of your particular issue, but as for the specifics of it, moving forward it's not something that you'll need, or want to micromanage.
