### ISSUE TITLE
Multitude of externally loaded dependencies

### ISSUE THREAD

**Issue by djpbessems** [owncast/owncast#203]
The current webinterface relies on several externally hosted files. The first load is noticably slower because of this (probably because of extra DNS lookups), subsequent loads are less noticable (note the load times in below screenshot of a subsequent load).
![image](https://user-images.githubusercontent.com/23643312/94400438-71f4e200-0169-11eb-87da-98f1569dba7d.png)

Can these dependencies be moved to be present inside the docker container?

**Comment by gabek** [comment]
We agree.  Tracking this in #189.

**Comment by graywolf336** [comment]
@djpbessems any idea on how we should handle this?

**Comment by djpbessems** [comment]
I'm only barely familiar with javascript frameworks, but my guess would be to change all the lines in for instance `app.js`, `chat.js`, etc that contain external urls like
```
import { h, Component } from 'https://unpkg.com/preact?module';
import htm from 'https://unpkg.com/htm?module';
```
to point to local files.
I don't know if Preact works with `npm` or `yarn`, but I can imagine that tools like that can download dependencies during build?
