### ISSUE TITLE
after update from 0.10 to 0.12 I get /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./owncast)

### ISSUE THREAD

**Issue by tigexplorer** [owncast/owncast#2045]
Hi,

I'm on ubuntu server 18.04. Version 0.10 was running fine.

With 0.12 I get 
`/lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.28' not found (required by ./owncast)`

`ls -la /lib/x86_64-linux-gnu/libc.so.6` gives me `/lib/x86_64-linux-gnu/libc.so.6 -> libc-2.27.so`

I'm unsure, how and can I update to `GLIBC_2.28` without trouble for other software on the server.

Btw: The error message encloses `GLIBC_2.28` with a backtick at the begining and a quotation mark at the end. I think it should be quotation marks at the beginning and the end.

Thanx for working on this great stream server!

**Comment by gabek** [comment]
Hi there, sorry about that. That's true that it's required, but most recent operating systems should include it. I just looked and 2.28 was released four years ago. Future binaries will be statically linked, so hopefully this won't be an issue going forward. But right now you'll have to run on a recent OS that has a recent version of libc by updating your OS or opting to run in a container who's image is more up to date.
