### ISSUE TITLE
Fediverse auth treats usernames as case-sensitive

### ISSUE THREAD

**Issue by jprjr** [owncast/owncast#2048]
Hi there - I noticed that when performing fediverse-based authentication, the `token` value stored in the database is used in a case-sensitive manner. So if I type `Username@example.com` - that stores a different entry in the `auth` table than `username@example.com`. Meaning I can wind up restoring a different user. It's created some confusion with users - they go to auth, type in their fediverse username in a different case than before, and wind up not restoring the user they intended to.

I can't find a spec that states usernames are considered case-insensitive, but that seems to be the case for most fediverse-based apps. I think converting the token to lowercase could prevent the issue.

**Comment by gabek** [comment]
I would also assume that they're universally case insensitive, so that change makes sense.

**Comment by brokenintuition** [comment]
I can do this one - it looks pretty straightforward.

**Comment by gabek** [comment]
Awesome, thank you!
