### ISSUE TITLE
Thumbnail downloads flicker when they're loaded

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#205]
Every time a new preview thumbnail is downloaded into the web interface it causes a brief flicker, as it's resetting the image when it downloads.

Some ideas to fix this offhand:

**Easiest option:** Download the image via `new Image` and when it's complete, replace the DOM element with this new one.  I don't know if this would flicker, though, because we're still removing one element and replacing it.  But at least it would be downloaded already.  

**More complex, but nicer option:** Have something like a double buffer image component that doesn't remove the old image when the new one has completed loading in, but instead we transition between them.  This could never flicker since both images would be rendered at the same time and we'd visually swap them.

**Comment by gingervitis** [comment]
Yeah I think the common thing most "gallery" features do is the complex one, but it's not that complex. Yeah keep the old image there, overlay the new image. Set a css opacity transition on it onLoaded (optionally do the same on the current on to fade it out), then get rid of the old one.

**Comment by DevanshCodes** [comment]
Hey! Can I work on this?

**Comment by gabek** [comment]
Hey @DevanshCodes, absolutely!  Let us know if you have any questions.

**Comment by gabek** [comment]
Hi @DevanshCodes, just checking in!  Do you think you're still going to look at this?

**Comment by gabek** [comment]
FYI, I'm grabbing this.

**Comment by gingervitis** [comment]
wait wait, can I take it then?

**Comment by gabek** [comment]
If you'd like!  I spent a little time on it: 

https://github.com/owncast/owncast/commit/fd4849d3664045588f44a85868b44224a25f3116
