### ISSUE TITLE
pop out chat 

### ISSUE THREAD

**Issue by bigkitttty** [owncast/owncast#2053]
have an url to pop out chat for live steam

**Comment by gabek** [comment]
Is this what you're referring to? https://owncast.online/docs/embed/#embedding-standalone-chat

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="/favicon.png" height="14"> Owncast</div><div><strong><a href="/docs/embed/">Embedding into your site</a></strong></div><div>You can easily embed your chat or video into another site.</div></blockquote>

**Comment by nononymousse** [comment]
is it possible to add a button in the chat menu ? it will be *way* more user frendly this way

**Comment by gabek** [comment]
If you have a feature request please do feel free to open a new issue with a detailed explanation of what you're looking for and its use case. At the moment I don't really understand what exactly what the use case is here and what the button you're asking for is.
