### ISSUE TITLE
Discord webhooks

### ISSUE THREAD

**Issue by bigkitttty** [owncast/owncast#2064]
### Share your bug report, feature request, or comment.

Discord Webhooks do not work yet

**Comment by gabek** [comment]
Could you provide some detail? They've worked in the past.

**Comment by bigkitttty** [comment]
I made a Discord webhook and put it in to owncast and nothing happened on my discord server

**Comment by gabek** [comment]
I just tested it and it seems to be working fine.

![image](https://user-images.githubusercontent.com/414923/187016266-bb8105e8-a4a9-4459-bcb0-f584f5ff2070.png)

The only recommendations I have offhand are to make sure you have your server URL set and Discord notification text set.

**Comment by bigkitttty** [comment]
Yes i do on owncast but it did not post

**Comment by gabek** [comment]
See above, I verified it's working. You'll have to look elsewhere to see why Discord isn't working with it. You can see that my test works.

**Comment by lanerussell** [comment]
I just tested this on my instance. It seems to work intermittently for me. Of the 5 times I tried this afternoon, I got a message in Discord 2 times after 2 minutes. The other 3 attempts I considered failed 5 minutes after going live.

**Comment by bigkitttty** [comment]
for me all my attempts have failed when  going live thank you

**Comment by gabek** [comment]
Does it fail on all Discord channels? Or just specific ones?  Personally I've never seen it "fail", it just works when I test it. If you can track down any errors that are taking place or why a Discord message might fail it can be looked into.

**Comment by bigkitttty** [comment]
i have it on one and i do not see any info

**Comment by lanerussell** [comment]
Personally, I tried on 2 different servers and several different channels in each server. I'll see if I can sus out any errors. I'm not sure if I'll be able to find anything on Discord's side as it seems the POST just isn't getting that far. I see if I can get any logs out of Owncast, and may do some tinkering with calling the webhook in Postman.

**Comment by bigkitttty** [comment]
thank you that may help

**Comment by lanerussell** [comment]
So I hit my test webhook pretty hard from Postman, and everything went through cleanly with no delay. Just sending a simple body:
```
{
    "username": "pie",
    "content": "test"
}
```

I'm not sure if there's something weird with the json payload Owncast is sending, or something else. I didn't see any logerror messages from Owncast on success or failure.

From Postman, I also tried sending messages with the stream link to see if maybe Discord was blocking messages containing links, but that also worked fine from Postman.

**Comment by gabek** [comment]
Are the messages you're sending from Owncast always the same? If you just send "test" from Owncast does it make a difference?  For example my test of "This is a test Discord webhook notification." with the link always worked, but I never tried anything other than that.

**Comment by lanerussell** [comment]
I did try just sending "test" from Owncast in case something wasn't parsing spaces, characters, etc. correctly, but had the same intermittent behaviour.

**Comment by gabek** [comment]
Or maybe Discord doesn't like the username?  I'm just guessing here, I know next to nothing about Discord to be completely honest.

Can you contact Discord and ask why these events are failing?

**Comment by lanerussell** [comment]
I've tried mirroring the username in Postman too; no trouble there. The only thing that catches my eye is the avatar: https://github.com/owncast/owncast/blob/4a17f30da8ff0bcdb61a1e32e911cf774e98ba10/notifications/discord/discord.go#L35

I don't see where this is set in Owncast Admin, so I'm not sure how to validate that, but could be a source of trouble?

**Comment by gabek** [comment]
If it's actually intermittent issues then I don't know if the content can be to blame.

I'm able to send https://github.com/owncast/owncast/issues/2064#issuecomment-1229127428 as a test all the time. It was mentioned above that some messages send some of the time.

**Comment by lanerussell** [comment]
So I just ran a pcap on owncast, and it looks like it is owncast introducing the delay. Looking for traffic from owncast -> any port 443 in my first test, nothing is sent for the first 3 minutes or so. As soon as Owncast sends traffic to port 443, the post shows up in Discord.

**Comment by gabek** [comment]
That all sounds correct. Owncast sends out notifications 2 minutes after a stream has been live. This is so you don't send out a notification if you're testing or working on configuring OBS, for example.

I was under the impression that the notification was _never_ sending out. 2 minutes after a stream has been live is when it should go out from your server.

**Comment by lanerussell** [comment]
Gotcha, that helps me understand the delay. However, after some additional tests I do have a few occurrences where Owncast isn't sending anything out on 443 after 2 minutes. It's still intermittent for me.

**Comment by gabek** [comment]
Do browser notifications get fired when you expect them to?

**Comment by lanerussell** [comment]
Hm, I'm don't have those enabled.

**Comment by gabek** [comment]
Another thing I realized that probably isn't obvious, if you send a notification it won't send again for 10 minutes. This is for the same reasons as above. If you're messing around with your stream you don't want to flood your notification channels each time you restart your stream. If you're restarting Owncast completely, however, it will send each time since this value isn't persisted across launches.
