### ISSUE TITLE
UI fixes [collector]

### ISSUE THREAD

**Issue by jamescallumyoung** [owncast/owncast#2080]
### Share your bug report, feature request, or comment.

I'm collecting some UI fixes here. If you find others, add them below. We can split these out into other issues later.

1) String "Now is a great time to[learn about the Fediverse](https://owncast.online/join-fediverse)if it's new to you." is missing spaces around the link.

<img width="473" alt="Screenshot 2022-09-03 at 20 03 51" src="https://user-images.githubusercontent.com/9281383/188282958-3cded674-1820-4be1-9ef5-e625f1c33cfa.png">

2) Allow button text not visible in notification modal.

<img width="232" alt="Screenshot 2022-09-03 at 20 00 32" src="https://user-images.githubusercontent.com/9281383/188282824-55bec3f8-a094-414a-9a44-23ec2a1aee93.png">

3) Non-selected tab text has low contrast with background.

<img width="232" alt="Screenshot 2022-09-03 at 20 01 46" src="https://user-images.githubusercontent.com/9281383/188282894-5140814e-aed6-4b35-9846-d4849f4bfe99.png">

4) Footer not pinned to bottom of page.

<img width="521" alt="Screenshot 2022-09-03 at 20 02 50" src="https://user-images.githubusercontent.com/9281383/188282924-e749bb44-3443-48af-a5cb-dd50a4cc4ef7.png">

**Comment by gabek** [comment]
The global styling is still pretty new, so lots in flux and not completed as well as broken in general. So that's why you'll see buttons and text and things with colors, fonts, weights, etc that don't look right. A week ago everything had colors of 'green', 'red' and 'blue' :)

**Comment by jamescallumyoung** [comment]
No worries! Just though it a good idea to jot these down in one place.

**Comment by jamescallumyoung** [comment]
Selecting "block / always block" in the browser enable notifications dialogue shows a success message in the modal, when a failure / retry message should be shown.

Tested in Firefox

**Comment by aprilthepink** [comment]
theres a prompt for the notification enable in chrome(ium) but not in Firefox or LibreWolf

Edit: the browser side prompt. not the modal. when you click the modal for the browser side prompt to appear in firefox nothing happens.
