### ISSUE TITLE
Custom page content component needs a static size

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2092]
### Share your bug report, feature request, or comment.

I'm not sure what the size should be, however. @vwallen mentioned we should have a max-width for it across sizes.

![image](https://user-images.githubusercontent.com/414923/188758785-68828dee-b743-4b79-846f-da4df095742b.png)

**Comment by vwallen** [comment]
Here's some data on optimal line lengths for text, which is a good guide for accessibility and friendly eye-tracking: https://baymard.com/blog/line-length-readability. Recommended is 50-75 characters, but that's somewhat restrictive for `max-width` on a content block.

I'd recommend shooting for < 100 characters all-in (padding borders, etc.). For relative units, you can approximate that as `100ch` or `50em` (`ch` == the width of the "0" glyph in the font, so it's dependent on the text style of that block)

<blockquote><img src="https://cdn.baymard.com/research/media_files/attachments/61638/original/research-media-file-31ae4d447d874c5d76b71c81bd789b29.jpg" width="48" align="right"><div><img src="/favicon.ico" height="14"> Baymard Institute</div><div><strong><a href="https://baymard.com/blog/line-length-readability">Readability: The Optimal Line Length</a></strong></div><div>The length of text lines substantially impacts their readability — yet this is often overlooked in e-commerce. See our latest test findings on line length readability.</div></blockquote>
