### ISSUE TITLE
Change the color of the tab bar separator

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2099]
### Share your bug report, feature request, or comment.

I can't find out what class or variables to override.

![image](https://user-images.githubusercontent.com/414923/189507813-bc5f0091-735b-4b70-9a3e-82c24b4503a6.png)

**Comment by realtouseef** [comment]
Possible ways to fix: 

- Right click on the page and click on `inspect`, a sidebar will be opened and hit `Ctrl + Shift + C` on your keyboard. 
- After that, hover over the element to find out the HTML
- Skim through it and you will find the class
- You can also make changes inside your browser, there will be another tab with `styles`, you can make changes there. 

Hope this helps, if not, I highly encourage you to read a post or watch a video on how to debug HTML and CSS.
