### ISSUE TITLE
Video cut-off under the chat on Firefox

### ISSUE THREAD

**Issue by codecat** [owncast/owncast#210]
It seems to be due to the width of the bar below the video having 12px too much width, although I'm not sure where it comes from.

Hopefully the screenshot makes the problem visible:

![image](https://user-images.githubusercontent.com/136534/94726169-23a83480-035d-11eb-8484-dd3b94546a1c.png)

**Comment by gingervitis** [comment]
Ahh looks like a scrollbar issue. Interesting. Firefox is not hiding the scrollbar and is leading to inconsistent calculations. Thanks for finding this @codecat .

Do you happen to have your scrollbars set to "always show " in your OS settings?

Also, just wondering, if you add a lot of messages, does a 2nd set of scrollbars appear on the message panel?

**Comment by codecat** [comment]
I'm not sure about the OS settings, but it's worth mentioning that this is on Linux! (Archlinux, Cinnamon desktop)

Yes, there will be 2 scrollbars:

![image](https://user-images.githubusercontent.com/136534/94733760-83580d00-0368-11eb-9966-0debad59d7d7.png)

**Comment by gingervitis** [comment]
Thanks for confirming! We'll make a fix soon.

**Comment by gingervitis** [comment]
@codecat Just pushed a fix to this into `master`. Let me know if you still see any issues!
