### ISSUE TITLE
Make chat text input properly grow to fit

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2108]
### Share your bug report, feature request, or comment.

Since the text input is already at the bottom of the screen the content will have to push up for the text input to grow.

![image](https://user-images.githubusercontent.com/414923/190067245-d549ea56-7665-4ea7-af4f-badc1a1c19aa.png)

**Comment by t1enne** [comment]
I don't remember how it was before, but the text input grows upwards and the content gets shrinked after the work on the chat input.

https://owncast.online/components/?path=/story/owncast-chat-chat-messages-container--example

If there's something that I am missing I'll be happy to fix this.

<blockquote><div><strong><a href="https://owncast.online/components/?path=/story/owncast-chat-chat-messages-container--example">Webpack App</a></strong></div></blockquote>

**Comment by gabek** [comment]
Yup it's fixed now, thanks!
