### ISSUE TITLE
Update import and mod path

### ISSUE THREAD

**Issue by geekgonecrazy** [owncast/owncast#211]
https://github.com/owncast/owncast/blob/6a0e8deae3b9a9b550a8bb4c0d193bdb6e126b96/go.mod#L1

The import path and go mod path still points to the old repo.  I think github probably handles redirect when it tries to fetch.  But might be good to update it to prevent any problems

**Comment by graywolf336** [comment]
@gabek just in case you hadn't seen this one yet :)

**Comment by gabek** [comment]
Should be a trivial change, feel free to jump on it!
