### ISSUE TITLE
Manually authored social posts are always set to followers-only

### ISSUE THREAD

**Issue by aral** [owncast/owncast#2112]
### Share your bug report, feature request, or comment.

Just upgraded from 0.0.11 to 0.0.12 using the official upgrade instructions at https://owncast.online/releases/owncast-0.0.12/ and fediverse posts are now set to followers only.

The private setting is off (I also toggled it on and off again just to see if that would override an errant setting somewhere.)

![Screenshot from 2022-09-14 16-00-51](https://user-images.githubusercontent.com/41798/190192579-45835257-35d0-4cf9-b29f-312cbd4c51be.png)

## Logs following upgrade

```
info | 3:43:48 PM 09/14/2022 | Web server is listening on IP 0.0.0.0 port 8080.
-- | -- | --
info | 3:43:48 PM 09/14/2022 | The web admin interface is available at /admin.
info | 3:43:48 PM 09/14/2022 | Video transcoder started using x264 with 1 stream variants.
info | 3:43:48 PM 09/14/2022 | RTMP is accepting inbound streams on port 1935.
info | 3:43:48 PM 09/14/2022 | Migrating users. This may take time if you have lots of users...
info | 3:43:48 PM 09/14/2022 | Migrating database from version 3 to 5
info | 3:43:48 PM 09/14/2022 | Owncast v0.0.12-linux-64bit (2d44f8603577bf1eb125447b3894462fa1310960)
```

**Comment by aral** [comment]
I’m getting very odd output for `select * from datastore;` on owncast.db:

```
sqlite> select * from datastore;
stream_key|-
            |2022-02-15 18:38:10
http_port_number|2022-02-15 18:38:10
rtmp_port_number|2022-02-15 18:38:10
logo_path|

          |2022-02-15 18:38:10
server_metadata_tags|,
                      |2022-02-15 18:38:10
server_summary|W
                |2022-02-15 18:38:10
server_welcome_message|)
                        |2022-02-15 18:38:10
server_name|
            |2022-02-15 18:38:10
extra_page_content|��
                     |2022-02-15 18:38:10
����|2022-02-15 18:38:10
HAS_POPULATED_DEFAULTS||2022-02-15 18:38:10
peak_viewers_overall|2022-02-15 18:39:10
peak_viewers_session|2022-02-15 18:39:10
server_url| 
            |2022-02-15 18:41:45
directory_enabled||2022-02-15 18:42:10
����|2022-02-15 18:46:39ants|
directory_registration_key|
                           |2022-02-15 18:56:01
last_disconnect_time|*�NullTime��|2022-02-15 18:56:50
federation_go_live_message|
                           |2022-06-11 20:11:28
HAS_POPULATED_FEDERATION_DEFAULTS||2022-06-11 20:11:28
server_init_date|*�NullTime��|2022-06-11 20:11:28
private_key|��
              |2022-06-11 20:11:29
public_key|��
             |2022-06-11 20:11:29
federation_enabled||2022-06-11 20:12:31
federation_username|
                    |2022-06-11 20:14:25
federation_private||2022-06-11 21:03:11
custom_styles|��
                |2022-06-14 15:29:57
stream_title|
             |2022-07-21 09:41:10
DATA_STORE_VERSION|2022-09-14 14:43:48
browser_push_private_key|.
                          |2022-09-14 14:43:48
browser_push_public_key|Z
                         |2022-09-14 14:43:48
browser_push_configuration|L�� BrowserNotificationConfiguration��|2022-09-14 14:43:48
has_configured_initial_notifications||2022-09-14 14:43:48
blocked_usernames|
```

@gabek Does this look like what you’d expect? Is binary data being stored there?

**Comment by gabek** [comment]
I'l try and reproduce this and check it out. I did a quick glance on the Fediverse to see what other 0.0.12 instances were locked down, but but there were plenty that weren't.

And yes, values in that table are encoded so it's likely looking directly at them will look quite odd.

**Comment by aral** [comment]
@gabek Ah, k, thanks. I wonder if the migration from db version 3 → 5 could be culprit. Was there a version 4? (Should my 0.0.11 been on version 4?) This is the first time I’ve updated using the official update script (instead of simply reinstalling and copying the database over. I believe last time we spoke you’d said it would auto migrate on first run so it’s probably not that but in any case… :)

**Comment by gabek** [comment]
There is technically a version 4 that existed for a short time. Multiple schema versions can exist between actual releases of Owncast in order to support people running unreleased development builds or running from source.

**Comment by gabek** [comment]
Looks like your identity, as defined by ActivityPub on your Owncast server is set how you'd expect. 

```
$ curl -sH "Accept: application/activity+json" "https://owncast.small-web.org/federation/user/fedi" | jq .manuallyApprovesFollowers
false
```

And I was able to access the object directly without Owncast throwing an access error, meaning it's not stopping public requests for ActivityPub objects.

```
$ curl -sH "Accept: application/activity+json" "https://owncast.small-web.org/federation/zkk6eR74R" | jq .id
"https://owncast.small-web.org/federation/zkk6eR74R"
```

I'll look more into it in the future.

**Comment by aral** [comment]
Thanks for looking into it, @gabek – sorry I seem to have a knack for finding the gremlins :)

**Comment by aral** [comment]
@gabek Also, just send me your public key if you’d like ssh access to the server, if that’ll help.

**Comment by aral** [comment]
PS. I’m also seeing the correct values returned from the API calls in the browser.

![image](https://user-images.githubusercontent.com/41798/190366170-8e92504b-4f59-4d9b-82e8-524442e5c5dc.png)

Not sure if it’s related, but the paging in the Followers tab in admin also appears to be stuck on page 1.

**Comment by gabek** [comment]
The specific issue seems to be that manual, hand-written posts are for some reason being set as followers only. Automated "go live" posts are public.

![image](https://user-images.githubusercontent.com/414923/198815994-3b9a7906-98a6-42a1-9bed-51c0f30f9d25.png)

**Comment by gabek** [comment]
Fixed. 
![image](https://user-images.githubusercontent.com/414923/198817258-4d984476-10c2-4ea7-ac8f-f56d1a0996a8.png)

**Comment by aral** [comment]
Thank you 💕
