### ISSUE TITLE
Notification reminder popup is incorrectly colored

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2114]
### Share your bug report, feature request, or comment.

Previously it [was purple](https://owncast.online/components/static/media/notify-popup.7df1d4bb.png) and looked better, but now is just using the default background color of the page. 

Component: https://owncast.online/components/?path=/story/owncast-components-notify-reminder--active
Colors: https://owncast.online/components/?path=/story/owncast-style-guide-default-theme--page

Currently `theme-color-components-menu-background` is just the background of the page so we could either change that variable, or style this one particular popup to use a different color variable.

**Comment by drhitchcockco** [comment]
I’ll try setting up a local dev environment today and have a look at it.

**Comment by gabek** [comment]
Awesome!

**Comment by gabek** [comment]
@drhitchcocknz Hey there, just wanted to check in and see if you were still intending to look at this. I can unassign if you're not longer available.

**Comment by drhitchcockco** [comment]
Many apologies Gabe. Please reassign this one. I’ll pick up another next time I’m in the office.

Benet.

**Comment by unclebinary1001** [comment]
I would like to pick this up after I'm done with [Issue #2138](https://github.com/owncast/owncast/issues/2138)

**Comment by gabek** [comment]
Sounds good, thanks!

**Comment by unclebinary1001** [comment]
This is what I have for now. 
![image](https://user-images.githubusercontent.com/69122375/195698912-3ec9f546-35b8-422a-8d19-2c128dee1c59.png)

Is this okay?

**Comment by gabek** [comment]
Yeah! Looks good to me!

**Comment by unclebinary1001** [comment]
Raised pull request [here](https://github.com/owncast/owncast/pull/2209). Please let me know if I need to make any changes.

**Comment by gabek** [comment]
FYI I had to revert the attached PR since it broke the build.

**Comment by unclebinary1001** [comment]
I just opened a new PR #2224. I tried to build locally, and it works with
no errors.

I hope it builds this time. 🤞

**Comment by unclebinary1001** [comment]
Thank you for allowing me to work on this. I learned a whole lot :)
