### ISSUE TITLE
Remove dynamic values in log messages

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2117]
### Share your bug report, feature request, or comment.

![image](https://user-images.githubusercontent.com/414923/190330711-33c06789-c5e1-45c2-ba55-aacdea834568.png)

**Comment by brokenintuition** [comment]
I'd be interested in taking this. Are those the only instances the tool flags, or are there more to look for?

**Comment by gabek** [comment]
Those are the four that popped up in the CodeQL code scanning, so those should be it. Thanks so much for wanting to take part!
