### ISSUE TITLE
CORS issue on FediAuth

### ISSUE THREAD

**Issue by aral** [owncast/owncast#2118]
### Share your bug report, feature request, or comment.

Tried to authenticate my chat handle using FediAuth and got a CORS error: 

```
POST | https://owncast.small-web.org/api/auth/fediverse/verify?accessToken=<token>=
Status
403
Forbidden
Referrer Policystrict-origin-when-cross-origin
Request PriorityHighest
```

![Screenshot from 2022-09-15 10-26-35-obfuscated](https://user-images.githubusercontent.com/41798/190369283-169ef0a6-2900-4502-b31e-e260fd9396ea.png)

**Comment by gabek** [comment]
This has been a commonly used feature for people since 0.0.12 was released, so I'm not sure what's different here.

**Comment by gabek** [comment]
Just as a sanity check I tested to make sure it worked on [Nightly](https://nightly.owncast.tv/), and it did. So functionality is working. Is there something with your proxy that might be getting in the way?

**Comment by mdonoughe** [comment]
That doesn't look like a CORS issue. The page origin and the request origin are the same.
