### ISSUE TITLE
Frontend architecture: Atomic Design

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2119]
### Share your bug report, feature request, or comment.

We're looking to adhere to the [Atomic Design](https://bradfrost.com/blog/post/atomic-web-design/) methodology to build up a library of smaller components that can be used to build current and future features and interfaces for Owncast. It's a little bit of work now to save additional work later.

https://collab.owncast.tv/kanban/#/2/kanban/edit/omLI2N+LcnP+elmdT7qW9GHD/

> Atomic design gives us the ability to traverse from abstract to concrete. Because of this, we can create systems that promote consistency and scalability while simultaneously showing things in their final context. And by assembling rather than deconstructing, we’re crafting a system right out of the gate instead of cherry picking patterns after the fact.

This approach is new to the project, so please bear with us, especially as we begin the process.

- [Atoms](https://bradfrost.com/blog/post/atomic-web-design/#atoms) are our HTML tags, such as a form label, an input or a button.
- [Molecules](https://bradfrost.com/blog/post/atomic-web-design/#molecules) are groups of atoms bonded together and are the smallest fundamental units of a compound. These molecules take on their own properties and serve as the backbone of our design systems.
- [Organisms](https://bradfrost.com/blog/post/atomic-web-design/#organisms) are groups of molecules joined together to form a relatively complex, distinct section of an interface.

Templates and pages fall under larger layout-related things that will be handled separately. 

Some of our components barely need any work at all to convert the component into its atomic structure, and some need more work.

## How to help

[We have a board with a list of components](https://collab.owncast.tv/kanban/#/2/kanban/edit/omLI2N+LcnP+elmdT7qW9GHD/
). If you'd like to help:

Items are tagged as either an atom, molecule or organism based on what we think they should end up being, based on role, size and complexity.

1. Pick a component from the list.
2. Move it to "In progress".
3. If this component has smaller components within it and are listed in the board, move those to "In progress as well".
4. Split the component into small, standalone components such as the text input, button, etc.
5. If existing small components already exist then use those.
6. Create a PR with your changes.

## How to work on the Owncast frontend

Visit the [How to get started with the Owncast frontend](https://owncast.online/development/#how-to-start-with-frontend-development) document for details.

![image](https://user-images.githubusercontent.com/414923/190498322-ac2367ad-bd5f-4e63-9296-8d423d1660d7.png)

**Comment by jamescallumyoung** [comment]
Thanks for opening this issue @gabek . I've pushed a branch to my fork that's a good example of some simple atomic components based on our existing ones. It doesn't handle integration but it's a good example of the components themselves.

I'll link it here for anyone to use as a reference. Check the latest commits on this branch: https://github.com/jamescallumyoung/owncast-fork/commits/feature/example-atomic-elements

Also, I added some additional how-to info for creating components following our design patterns. The changes are in PR https://github.com/owncast/owncast/pull/2124. Linked here for reference too.

<blockquote><img src="https://opengraph.githubassets.com/a8d282facb4c173985d41e6ad816982ad6ff6d573ccc897bdd2425d341677cad/jamescallumyoung/owncast-fork" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/jamescallumyoung/owncast-fork">Commits · jamescallumyoung/owncast-fork</a></strong></div><div>Fork of owncast/owncast. Contribute to jamescallumyoung/owncast-fork development by creating an account on GitHub.</div></blockquote>

**Comment by gabek** [comment]
Perfect, now I feel less intimidated jumping on some of these since I can use your branch as a reference. Thank you!

**Comment by gabek** [comment]
Due to lack of clarity and to keep churn to a minimum, this is being abandoned.
