### ISSUE TITLE
Websockets

### ISSUE THREAD

**Issue by ma-karai** [owncast/owncast#2140]
### Share your bug report, feature request, or comment.

Using a reverse proxy caddy with a one line configuration

```
stream.blub.net {
        encode gzip
        reverse_proxy * 192.168.0.60:8080
}
```

error in ws connection in chrome browser

```
websocket.js:56 Uncaught (in promise) DOMException: Failed to construct 'WebSocket': The URL's scheme must be either 'ws' or 'wss'. 'https' is not allowed.
    at Websocket.createAndConnect (https://stream.blub.net/js/utils/websocket.js:56:16)
    at new Websocket (https://stream.blub.net/js/utils/websocket.js:49:10)
    at App.setupChatAuth (https://stream.blub.net/js/app.js:716:23)
    at App.setConfigData (https://stream.blub.net/js/app.js:292:12)
    at https://stream.blub.net/js/app.js:245:14
```

**Comment by gabek** [comment]
Does Owncast work without using the proxy?

**Comment by ma-karai** [comment]
![image](https://user-images.githubusercontent.com/17119942/192160926-3475dd83-03a2-4071-8fff-a3eec38e7a3e.png)


same error without the reverse proxy-

**Comment by gabek** [comment]
Have you performed any kind of customization or changes anywhere? I don't know why it would be trying to access a web socket over http.

**Comment by ma-karai** [comment]
mhh, not really I started playing around with owncast yesterday, for no reason, i am using the basic compose installation.

**Comment by gabek** [comment]
Very odd. Are you able to access other Owncast chats like https://watch.owncast.online ?

When I get back to my computer I'll see under what conditions something like this might happen, but I'm a little baffled at the moment.

<blockquote><img src="https://watch.owncast.online/thumbnail.jpg" width="48" align="right"><div><img src="/img/favicon/favicon-16x16.png" height="14"> Owncast TV</div><div><strong><a href="https://watch.owncast.online/">Owncast TV</a></strong></div><div>An example stream where you can learn more about Owncast, as well as other projects we want to share.</div></blockquote>

**Comment by ma-karai** [comment]
I get this in my console. 
![image](https://user-images.githubusercontent.com/17119942/192259943-d28cfc4d-419a-4d8d-a667-e3234d469391.png)

**Comment by ma-karai** [comment]
first one is chrome

this is in edge

![image](https://user-images.githubusercontent.com/17119942/192260145-37cfa9fe-43a5-4527-9354-75c6ab6cece0.png)

**Comment by gabek** [comment]
Since that's a publicly available server that works for others (including me just now) I'm guessing it must be something local to your setup. I'm not sure what, but it works for others but not you, something is different somewhere. Are you sure there's no proxies or extensions or something that might be doing something?

**Comment by ma-karai** [comment]
I mean, the videos play and the chat works, it still displays the error. Have you checked your console?

**Comment by gabek** [comment]
I was under the impression chat wasn't working for you based off your messages, I apologize. 

I won't be near a computer for a bit. Hopefully others can chime in. Maybe ask those in the chat.

**Comment by ma-karai** [comment]
totally fine, don't sweat it :D

**Comment by gabek** [comment]
And I'm back!

My console looks pretty clear on the demo server, so I'm really confused about what you're seeing.

![image](https://user-images.githubusercontent.com/414923/192409884-b774e3a8-320c-44f8-8176-586746c02a15.png)

I also opened it up in a private browsing window just so it would re-register the service worker, in case that was at all related.  Still looks good:

![image](https://user-images.githubusercontent.com/414923/192413120-3d48daf4-b7a5-45a3-bddb-a773649e56c5.png)
