### ISSUE TITLE
Test and Document using a CDN with Owncast

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2144]
This hasn't been something that has been exhaustively tested, documented, or paid much attention to. A setting for allowing the frontend to point at a specific websocket host, allowing for a CDN to be used, was added a while ago, but it was left at that.

- Pick a CDN provider.
- Use the "Server Setup" -> Advanced "Websocket host override" setting in the admin to point to the origin server to bypass the CDN.
- Test Owncast streaming + chat using the CDN's hostname.
- Document the steps and configuration for this CDN provider to share with others.

![image](https://user-images.githubusercontent.com/414923/192585147-3bd707bb-c188-4d66-aa58-faec54f5ccd2.png)

Potential CDN providers:

- [Bunny CDN](https://bunny.net/cdn/)
- [Fastly](https://www.fastly.com/)
- [AWS Cloudfront](https://aws.amazon.com/cloudfront/)
- [Key CDN](https://www.keycdn.com/)

**Comment by rmens** [comment]
I'll give Bunny CDN a spin this easter 🐰

**Comment by rmens** [comment]
Bunny CDN seem to work 'out of the box' for the streaming part:

### m3u8 files are not cached
```
rmens@iMac-van-rmens ~ % curl -I "https://owbtv.b-cdn.net/hls/stream.m3u8"
HTTP/2 200 
date: Sat, 08 Apr 2023 21:24:40 GMT
content-type: application/x-mpegURL
content-length: 328
vary: Accept-Encoding
server: BunnyCDN-DE1-874
cdn-pullzone: 1326243
cdn-uid: f5fd38d2-70f7-42fb-b333-f164d1f21969
cdn-requestcountrycode: NL
access-control-allow-origin: *
alt-svc: h3=":443"; ma=2592000
cache-control: no-store, must-revalidate, no-cache
expires: Thu, 01 Jan 1970 00:00:00 GMT
last-modified: Thu, 30 Mar 2023 01:45:30 GMT
cdn-proxyver: 1.03
cdn-requestpullsuccess: True
cdn-requestpullcode: 206
cdn-cachedat: 04/08/2023 21:24:40
cdn-edgestorageid: 863
cdn-status: 200
cdn-requestid: 412d68e7b2d670b4975fa2bda5e93a95
cdn-cache: MISS
accept-ranges: bytes
```

### Variant files are not cached too

```
rmens@iMac-van-rmens ~ % curl -I https://owbtv.b-cdn.net/hls/0/stream.m3u8
HTTP/2 200 
date: Sat, 08 Apr 2023 21:25:06 GMT
content-type: application/x-mpegURL
content-length: 898
vary: Accept-Encoding
server: BunnyCDN-DE1-1077
cdn-pullzone: 1326243
cdn-uid: f5fd38d2-70f7-42fb-b333-f164d1f21969
cdn-requestcountrycode: NL
access-control-allow-origin: *
alt-svc: h3=":443"; ma=2592000
cache-control: no-store, must-revalidate, no-cache
expires: Thu, 01 Jan 1970 00:00:00 GMT
last-modified: Sat, 08 Apr 2023 21:25:06 GMT
cdn-proxyver: 1.03
cdn-requestpullsuccess: True
cdn-requestpullcode: 206
cdn-cachedat: 04/08/2023 21:25:06
cdn-edgestorageid: 1047
cdn-status: 200
cdn-requestid: 982c6e9943aa2a14b2394272eaba4a9b
cdn-cache: MISS
accept-ranges: bytes
```
### .ts files are cached
```
rmens@iMac-van-rmens ~ % curl -I "https://owbtv.b-cdn.net/hls/2/stream-5EMdXlB4g-212114.ts"
HTTP/2 200 
date: Sat, 08 Apr 2023 21:26:37 GMT
content-type: text/vnd.qt.linguist; charset=utf-8
content-length: 1951816
server: BunnyCDN-DE1-865
cdn-pullzone: 1326243
cdn-uid: f5fd38d2-70f7-42fb-b333-f164d1f21969
cdn-requestcountrycode: NL
access-control-allow-origin: *
alt-svc: h3=":443"; ma=2592000
cache-control: public, max-age=31557600
last-modified: Sat, 08 Apr 2023 21:26:26 GMT
cdn-proxyver: 1.03
cdn-requestpullsuccess: True
cdn-requestpullcode: 206
cdn-cachedat: 04/08/2023 21:26:27
cdn-edgestorageid: 1081
cdn-status: 200
cdn-requestid: 4279111bedc8be1d746a7e81794d3e5e
cdn-cache: HIT
accept-ranges: bytes
```

Thumbnail refreshing works too, thanks to the cachebuster on them. I'll check out the chatting part tomorrow. So far everything seems to look good with default settings. 

I only find the `content-type` for the `.ts` files a bit strange, but it doesn't prevent the video from playing. EDIT: They seem to be that way without the CDN too. This might be a Caddy thing, not a Bunny thing.

**Comment by gabek** [comment]
Chat likely won't work prior to v0.1.0 due to the chat socket override, since these CDN services don't pass through the websocket. Or at least ones that I've seen. This is largely why I decided to add #2785, so only the video needs to be behind the CDN and the rest of the server doesn't need to deal with those added variables. But if you did want to put your entire server behind a CDN then you could use the websocket override.

**Comment by rmens** [comment]
Chat without specifying the websocket host override. "Chat is offline"

<img width="1497" alt="Schermafbeelding 2023-04-10 om 12 57 18" src="https://user-images.githubusercontent.com/6742496/230889311-82901cf8-28fe-48be-b9e2-bb9447af3065.png">

With the websocket host override filled in

<img width="1497" alt="Schermafbeelding 2023-04-10 om 13 00 12" src="https://user-images.githubusercontent.com/6742496/230889532-5e6a1d91-c4f9-4bde-bde9-e93ac1b559d8.png">

Whole chat disappears in front of and behind the CDN both

<img width="1199" alt="Schermafbeelding 2023-04-10 om 13 00 18" src="https://user-images.githubusercontent.com/6742496/230889518-a4fb3919-6970-467c-ad34-dde1306db21f.png">

This appears to be pretty broken in 0.0.13. Should I test v0.1.0 too @gabek?

**Comment by gabek** [comment]
I wouldn't waste time on it right now. I filed this under v0.1.1 because there's additional work required. #2785 needs to get done before all these scenarios will work.

**Comment by labthe3rd** [comment]
I found I had to type in ws://origin-server.com/ws to get the override to try to work. The problem I face now is that the CDN sends the websocket request with the token to the origin server.... but the origin server doesn't reply then I get a JSON error. It seems like the origin server doesn't know how to respond if the request comes from a different host?

For reference I am using stackpath after I couldn't get BunnyCDN to work. It looks like no CDN is going to work from the previous comments in this.

**Comment by gabek** [comment]
I'm not sure what version you're running or the specifics. But maybe this will help:

With v0.0.13 you can put a CDN in front of your storage provider. With v0.1.0 you'll be able to put a CDN in front of your entire Owncast instance and use the websocket override. With v0.1.1 you'll be able to put a CDN in front of just the video you serve yourself (without a storage provider).

I've been working on the documentation and it'll be ready for v0.1.0.

**Comment by labthe3rd** [comment]
Thank you, I’m using v0.0.13. After doing more debugging I found the issue was the /api/chat/registration was being sent to my CDN and not the Origin Server, so my chat token was not coming back as valid. I setup my vpn to redirect /api/ requests to the origin server and it’s almost working! Now I am getting in contact with my CDN provider to find out if they support redirecting PUT requests, since I see I need that for the chat registration API. Anywho I think the problem lies with Stackpath CDN. I’ll write out all the steps I took to configure it to work when I’m completeSent from my iPhoneOn May 14, 2023, at 2:56 PM, Gabe Kangas ***@***.***> wrote:﻿
I'm not sure what version you're running or the specifics. But maybe this will help:
With v0.0.13 you can put a CDN in front of your storage provider. With v0.1.0 you'll be able to put a CDN in front of your entire Owncast instance and use the websocket override. With v0.1.1 you'll be able to put a CDN in front of just the video you serve yourself (without a storage provider).
I've been working on the documentation and it'll be ready for v0.1.0.

**Comment by gabek** [comment]
As a data point, Fastly has been in front of the Owncast demo server for about a week now. https://watch.owncast.online.

I pushed up the first pass of CDN documentation that reflects how things are for v0.1.0.

<blockquote><img src="https://watch.owncast.online/thumbnail.jpg" width="48" align="right"><div><img src="/img/favicon/favicon-16x16.png" height="14"> Owncast TV</div><div><strong><a href="https://watch.owncast.online">Owncast TV</a></strong></div><div>An example stream where you can learn more about Owncast, as well as other projects we want to share.</div></blockquote>

**Comment by labthe3rd** [comment]
Thank you! That is super helpful! I haven't fully committed to stackpoint
yet, so I may go that route. I appreciate all the help, and also appreciate
the software, this is so cool to use!

**Comment by gabek** [comment]
I would hope that any CDN should work pretty similarly. If there's something that needs to change (different caching headers, etc) please let me know.

I can't think offhand of any uses of `PUT` for any APIs, however. Where were you running into issues with them?

**Comment by labthe3rd** [comment]
Thank you! I ran into an error when the link /api/chat/register is sent.
The CDN I'm using first tries to send the API with I think a username and a
token to itself, but I had added an edge rule to do a 301 redirect to the
origin server. This redirect on stackpath redirects it as a GET request and
drops the data it was trying to send.  Please note I am only running into
the challenges with the chat, and the video portion works as planned :D

What I'm seeing on the CDN in terms of the api is,
curl -X POST https://cdn.watch.havengers.com/api/chat/register
which gets redirected to
culr -i GET https://watch.avengers.com/api/chat/register

But I was trying to redirect it to the origin server as
curl -X POST https://watch.havengers.com/api/chat/register
 Sending me back the generated id,access token, and display name for the
chat. It may be a limitation with stackpath, but I think I need all the
chat api requests to go to the origin server to get the chat working.

**Comment by gabek** [comment]
In general, with CDNs, all requests should go through them, as they operate as a proxy. But it's up to the CDN to treat things like `POSTS` as a cache `MISS` and route that request to the origin server. I've never heard of having to wire up redirects at the CDN level to make sure that your requests make it to the origin server, so something feels a little odd here.

I'm not familiar with Stackpath myself, but maybe you can create rules at the CDN level to explicitly `MISS` or `PASS` all `POST` requests to the origin if it's not automatically doing so.

**Comment by labthe3rd** [comment]
That's what I would have thought too! However it looks like the provider
stack path changes the requests when you try to redirect them. They do not
have any finer controls to correct the redirect or any controls to let it
pass. There support just sent me back to the documentation I used to set up
the rules XD... so it looks like stack path may just be an inferior choice
for this application. I plan to try KeyCDN next but, will continue to see
if the stackpath support will help me setup the redirects/passes properly.
Thank you for all the help, I am glad to know this CDN seems unusual.

**Comment by gabek** [comment]
For v0.1.1 the documentation for CDN usage can discuss using the video serving endpoint.

**Comment by gabek** [comment]
Added CDN use case discussing the serving endpoint.
