### ISSUE TITLE
Update chat name change functionality

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#215]
Not something that needs to be focused on now, but in some point in the future we discussed changing up the name change functionality.

- [ ] Visual design of this new flow.

- [ ] Add configuration for enabling/disabling it.

- [ ] Move the existing "change name" form.

- [ ] Build name change prompt.

**Comment by gabek** [comment]
I never realized until today that Discord doesn't make you create an account and just prompts you for a name upfront.  Maybe we can model something off of that.

<img width="1789" alt="Screen Shot 2020-10-29 at 11 12 24 AM" src="https://user-images.githubusercontent.com/414923/97614930-d361d800-19d7-11eb-9019-696072830022.png">

**Comment by MFTabriz** [comment]
Together with the authentication option, it makes sense to have something similar to this. It also solves the #1339
