### ISSUE TITLE
Chat container story controls no longer working

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2150]
### Share your bug report, feature request, or comment.

Changing the controls no longer update the story's state. For example turning off "Show input" does not hide the input field, or turning on "isModerator" does not enable the moderation menu.

Story: https://owncast.online/components/?path=%2Fstory%2Fowncast-chat-chat-messages-container--example&args=isModerator%3Atrue%3BshowInput%3Afalse

![image](https://user-images.githubusercontent.com/414923/193312818-730dfc54-aa89-4d93-a94d-ca9ac9ed0c55.png)

**Comment by juliana-mol** [comment]
Can I work on this issue ?

**Comment by gabek** [comment]
Sure! Thank you! :D

**Comment by gabek** [comment]
@juliana-mol Hey there! Were you able to get the project running alright? Let me know if you have any questions.

**Comment by juliana-mol** [comment]
Hi, I am following instructions available at  **https://owncast.online/development/** for running the project and I will let you know if I encounter any problems. Thank you for asking :)

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="/favicon.png" height="14"> Owncast</div><div><strong><a href="/development/">How to work on Owncast</a></strong></div><div>The technical details for those wishing to take part in Owncast development.</div></blockquote>
