### ISSUE TITLE
Browser notifications modal: Enabled state with instructions how to disable

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2153]
### Share your bug report, feature request, or comment.

When browser notifications are enabled we need to show something in the modal saying:

- That they are enabled
- Point to using your browser settings to disable them.

There's currently no design for this, so if somebody could come up with something that'd be awesome!

![image](https://user-images.githubusercontent.com/414923/193353396-cfd46363-620f-4474-a94b-7108c498b016.png)

How to turn them off:

![image](https://user-images.githubusercontent.com/414923/193353642-e2471c01-c90d-4197-922b-2d4fe10f50a0.png)

Component: https://owncast.online/components/?path=%2Fstory%2Fowncast-modals-browser-notifications--basic

**Comment by aprilthepink** [comment]
I'd like to implement this! ^^

**Comment by gabek** [comment]
Awesome!  It's yours, thank you!

**Comment by aprilthepink** [comment]
@gabek which version of chrome do you use?
The notification permission thingy is for me a drop down thingy. Has it changed in newer versions of chrome?
![image](https://user-images.githubusercontent.com/30842467/193428563-61b697c7-0057-4ebc-9964-670ec2050991.png)

**Comment by gabek** [comment]
I use Brave. And you're right, it'll probably look different between browsers. But just saying "disable notifications through your browser" or something should probably translate to all browsers regardless of the UI. But feel free to experiment!
