### ISSUE TITLE
Fix superfluous response.WriteHeader call error

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2157]
### Share your bug report, feature request, or comment.

It's likely an error code is being returned as well as an error response, making for a duplicate header being sent back to the browser.

```
2022/10/02 11:09:22 http: superfluous response.WriteHeader call from github.com/owncast/owncast/controllers/auth/fediverse.VerifyFediverseOTPRequest (fediverse.go:101)
```

**Comment by brokenintuition** [comment]
I can take this one - sorry, forgot to comment here before opening the PR
