### ISSUE TITLE
Admin only allows selecting 24fps or 120fps, nothing inbetween

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2159]
### Share your bug report, feature request, or comment.

Something must have changed with the slider component, as it no longer is allowing selection of any framerates aside from the first option and the last option.

![image](https://user-images.githubusercontent.com/414923/193475940-f43793aa-c37a-4b5b-a857-ce4bcfffa174.png)

**Comment by pippo** [comment]
Please, assign this to me ✋ I've got a working fix for the issue.
