### ISSUE TITLE
Web page needs to set the title

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2161]
### Share your bug report, feature request, or comment.

Currently there is no title tag set. It should be set with the name of the server in `Main.tsx`.

![image](https://user-images.githubusercontent.com/414923/193476408-db01644c-b729-4fd9-acfd-f9136d0c8a86.png)

**Comment by Kundan1804** [comment]
Hey @gabek  I am a frond end developer and would love to contribute in this issue an you please assign this to me.

**Comment by gabek** [comment]
Thank you!

**Comment by siddhant7666** [comment]
Hey @gabek if this issue is not yet resolved, can you please assign this to me. I will solve it as soon as possible.
Thanks

**Comment by gabek** [comment]
Hi there! Did you have any questions about this or have any issues?

**Comment by Kundan1804** [comment]
I have identified the problem which is preventing us from setting title, but i am not yet able to solve it i am working on it.

**Comment by gabek** [comment]
Just to clarify, there's no problem to be fixed, we simply haven't added a title yet.

**Comment by gabek** [comment]
Hi there. Let me know if you're no longer looking at this and I'll take care of it.

**Comment by Kundan1804** [comment]
Sorry I was busy with my exams will get back to it now,  I'll finish it till 21st if I am unable to do so then you may unassign me, sorry for the delay hope it's alright.

**Comment by Kundan1804** [comment]
I am sorry @gabek i tired my best but i am unable to solve this issue, you may please unassign me.
