### ISSUE TITLE
List of donors only shows one person on the web site

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2187]
### Share your bug report, feature request, or comment.

Not sure why this is happening.

![image](https://user-images.githubusercontent.com/414923/194787289-caa125bc-bf76-40a2-87b3-3bae09f1a5d2.png)

**Comment by heller** [comment]
This means the bottom of the main page of owncast.online, right? Looks like it's fixed now.

**Comment by gabek** [comment]
Yup! I think it comes and goes. Very weird.

**Comment by gabek** [comment]
I'll keep an eye on it, but I'll close it since it's no longer occurring.

**Comment by gabek** [comment]
It has returned!

![image](https://user-images.githubusercontent.com/414923/197369815-9a230166-4dd5-4ef7-acd2-663d8dc45b33.png)

**Comment by gabek** [comment]
The `select(.role==\"BACKER\")` seems to be the problem. Removing it fixes the parsing.

```
$ curl https://opencollective.com/owncast/members/all.json | jq 'map(.) | .[] | select(.role==\"BACKER\") | {login: .name, avatar_url: .image, html_url: .profile}'
jq: error: syntax error, unexpected INVALID_CHARACTER (Unix shell quoting issues?) at <top-level>, line 1:
map(.) | .[] | select(.role==\"BACKER\") | {login: .name, avatar_url: .image, html_url: .profile}
jq: 1 compile error
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 18 27073   18  4876    0     0  27322      0 --:--:-- --:--:-- --:--:-- 27393
curl: (23) Failure writing output to destination
```

**Comment by heller** [comment]
In a zsh session, that command seems to work if I drop the escape characters and just use `.role=="BACKER"`. Not sure where this code lives or I would take a look in context.

**Comment by gabek** [comment]
Oh yeah you're right, I didn't look too closely. It's escaped because it's all passed in as a string here:
https://github.com/owncast/owncast.github.io/blob/master/.github/workflows/main.yml#L42

**Comment by heller** [comment]
Ah okay. The list on the site looks to be working again, so the quotes may be a red herring.

**Comment by gabek** [comment]
Still happening.

**Comment by gabek** [comment]
I haven't seen this occur in some time.
