### ISSUE TITLE
Footer isn't on the bottom of the page

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2188]
### Share your bug report, feature request, or comment.

There is a gap between the bottom of the screen and the footer.

![image](https://user-images.githubusercontent.com/414923/194790218-9f1793c7-a070-4bba-9b3e-bdce48a9d1f6.png)

**Comment by gabek** [comment]
With the additional content in the empty state of the followers tab the footer now gets pushed down to the accurate place. So I'm just going to close this.

**Comment by gabek** [comment]
Nope, still a problem.

**Comment by Pranav2612000** [comment]
@gabek I've created a PR for this feel free to take a look

**Comment by gabek** [comment]
This issue has returned due to other UI changes that have taken place.

![image](https://user-images.githubusercontent.com/414923/210158147-6ee34879-1f9a-42da-96d8-2bd0e0c02834.png)

**Comment by gabek** [comment]
This issue is back when the "about" section is short.

![image](https://user-images.githubusercontent.com/414923/215366027-589b9cf5-487c-44ac-a898-72f881c588cb.png)
