### ISSUE TITLE
Header does not fill full width on narrow windows/mobile layouts

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2189]
### Share your bug report, feature request, or comment.

![image](https://user-images.githubusercontent.com/414923/194807488-c1b30f1b-c95a-469d-859b-19fc37992888.png)

**Comment by Pranav2612000** [comment]
Oh. Just found out the reason for this. It's an interesting issue. Creating a  PR

**Comment by gabek** [comment]
So unfortunately this issue is still occurring. It certainly seems to depend on what the title of the instance is. The default "Owncast" doesn't cause the issue, but the "Owncast web v2" does.

![image](https://user-images.githubusercontent.com/414923/196607607-ee9505e9-3660-4c70-86e2-ae6ba4df418d.png)

**Comment by Pranav2612000** [comment]
Must be something similar. I'll take a look.

**Comment by t1enne** [comment]
This is fixed with my last commit! Sorry, didn't notice we had an open issue.

**Comment by gabek** [comment]
Yes, fixed! Thanks for the update @t1enne. Closing.
