### ISSUE TITLE
Major components need a clear, user-overridable class name

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2193]
### Share your bug report, feature request, or comment.

Because we use CSS modules everywhere the CSS class names cannot be used to override styles.

We need to make sure that the major components have an additional clear, unchanging name, so people can target those classes with their own custom CSS.

These class names should be documented so people know what they are.

For example then if they wanted to change the header font size they could simply write

```
.header { font-size: 2rem; }
```

Whereas now the class name would be `Header_header__U4Ro1` and change over time.

Here are a list of components I feel need these names so they can be targeted with CSS:

- [x] Header
- [x] Footer
- [x] Chat container
- [x] Custom page content
- [x] Modal
- [x] Offline banner
- [x] User chat message
- [x] System chat message
- [x] Social chat event
- [x] Single follower

... More can get added as they are brought up.

**Comment by suyash1397** [comment]
hii author i am suyash i will be glad if i get this issue but i am not understanding what change i have to make plzz help

**Comment by suyash1397** [comment]
!assign

**Comment by gabek** [comment]
Hello! The TODO is simply to add a plain text additional class name to components so they can be targeted with CSS.

**Comment by gabek** [comment]
I'm going to reclaim this and just work on this at the same time that I work on UI tests.

**Comment by t1enne** [comment]
We could prepend clear class names before the `Header_header__U4Ro1` put in by next. 
I'd suggest having a clear prefix in front of all customizable components. Like `customizable__header`. 
This way it's clearer where we have to use variables for styling, instead of fixed values, from the code.

**Comment by gabek** [comment]
I was actually thinking of giving these components IDs instead of additional class names. Is there any downside to IDs vs classes in this case? I figure since the point is to target specific components that IDs make sense. I'm also using these to target elements for automated UI testing.

**Comment by t1enne** [comment]
The ID is unique, so it would work for a header, but not for buttons (or any other non-unique UI component)
