### ISSUE TITLE
Player grows larger than the placeholder

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2204]
### Share your bug report, feature request, or comment.

The player area should stay the same size before it's playing and when it's playing.

Video placeholder before player is playing. Correct size:

![image](https://user-images.githubusercontent.com/414923/195477225-972a7603-eb61-4917-afd1-dd3f6ae62125.png)

Video when player is playing. Incorrect size (too large):

![image](https://user-images.githubusercontent.com/414923/195477302-68c40b81-4eeb-47df-b8c6-e7efdb454b06.png)

**Comment by gabek** [comment]
https://videojs.com/guides/layout/

<blockquote><img src="/favicon.ico" width="48" align="right"><div><strong><a href="https://videojs.com/guides/layout/">Layout | Video.js</a></strong></div><div>Layout and repsonsiveness options for Video.js players.</div></blockquote>

**Comment by unclebinary1001** [comment]
I would like to take this up

**Comment by gabek** [comment]
Great, thank you!

**Comment by unclebinary1001** [comment]
So I started to look at this. Its seems the seek bar takes up extra space (about 0.4em when I measured it using chrome dev tool ruler) when viewers clicks play button. 

I hope to figure out how to either manipulate `VideoPoster` to expand with this extra space or prevent `VideoJS` player seek from increasing video content height.

**Comment by gabek** [comment]
I'm not sure if I made this worse or better, but I noticed some change made the player not render anymore, so I made some changes to fix it. Now it lays out differently.

**Comment by gabek** [comment]
When looking at #2303 I made some changes I think move that and this in the right direction. But there's still some layout issues with the player. I'm going to close these two issues and open up a more specific one.
