### ISSUE TITLE
Followers should be left aligned, not centered.

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2207]
### Share your bug report, feature request, or comment.

![image](https://user-images.githubusercontent.com/414923/195491604-6a7ef2a5-aa6f-45a5-be42-4fdca22ddc45.png)

**Comment by Pranav2612000** [comment]
Hey @gabek
I'll like to work on this issue.

**Comment by gabek** [comment]
Awesome, thank you!

**Comment by Pranav2612000** [comment]
I was able to get the project set up. Do you have any tips on how I can add a mock follower to reproduce this bug?
Will try to have a PR ready in a day

**Comment by Pranav2612000** [comment]
@gabek ~~Has this been fixed? I am unable to reproduce it on nightly ( https://nightly.owncast.tv/ ) and even the storybook shows the follower correctly positioned to the left~~ Able to reproduce this here - https://webv2.owncast.tv/. How can I reproduce this error in my local setup?

![image](https://user-images.githubusercontent.com/20909078/195989486-e4a323cc-d143-4b23-8600-d22393fe95b1.png)


<blockquote><img src="https://nightly.owncast.tv/logo/external" width="48" align="right"><div><img src="/img/favicon/favicon-16x16.png" height="14"> Owncast Nightly</div><div><strong><a href="https://nightly.owncast.tv/">Owncast Nightly</a></strong></div><div>This is a server running the nightly build of Owncast.</div></blockquote>
