### ISSUE TITLE
Chat sidebar is no longer correctly positioned

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2236]
### Share your bug report, feature request, or comment.

The sidebar is taller than the viewport and the input textbox is off screen.

![image](https://user-images.githubusercontent.com/414923/197087719-7aea4d6c-1bbd-4aee-9398-ace70e8212e6.png)

**Comment by t1enne** [comment]
Fixed with 917248fc5b26c5911459e34cb7b418fd8efcb057
