### ISSUE TITLE
should minimum go version increase to version 1.17?

### ISSUE THREAD

**Issue by jahway603** [owncast/owncast#2238]
### Share your bug report, feature request, or comment.

I'll preface this first with this compiled perfectly fine on my Arch system with go1.19.2.

This issue I'm filing occurred with an Ubuntu 20.04 VPS using the minimum in the README of go1.16.

```
$ go version
go version go1.16 linux/amd64
$ cd owncast/
$ go run main.go
go: github.com/prometheus/procfs@v0.8.0 requires
	golang.org/x/sync@v0.0.0-20220601150217-0de741cfad7f: missing go.sum entry; to add it:
	go mod download golang.org/x/sync
```

I then ran `go mod download golang.org/x/sync`, which modified the go.sum file.

Then I tried running owncast again and got this error.

```
$ go run main.go
# golang.org/x/sys/unix
../.gvm/pkgsets/go1.16/global/pkg/mod/golang.org/x/sys@v0.0.0-20221010170243-090e33056c14/unix/syscall.go:83:16: undefined: unsafe.Slice
../.gvm/pkgsets/go1.16/global/pkg/mod/golang.org/x/sys@v0.0.0-20221010170243-090e33056c14/unix/syscall_linux.go:2255:9: undefined: unsafe.Slice
../.gvm/pkgsets/go1.16/global/pkg/mod/golang.org/x/sys@v0.0.0-20221010170243-090e33056c14/unix/syscall_unix.go:118:7: undefined: unsafe.Slice
../.gvm/pkgsets/go1.16/global/pkg/mod/golang.org/x/sys@v0.0.0-20221010170243-090e33056c14/unix/sysvshm_unix.go:33:7: undefined: unsafe.Slice
note: module requires Go 1.17
```

So I installed and set go1.17 to default. It was only then that Owncast started up and ran fine without any of the above errors. I was also able to get to its admin page.

**Comment by gabek** [comment]
That's correct, Go 1.17 is currently the minimum version set in `go.mod.`: https://github.com/owncast/owncast/blob/develop/go.mod#L3. I'm guessing there's some incorrect documentation somewhere.

I'm hoping at some point in the future we can move to 1.19 #2185, probably after this next big release.

<blockquote><img src="https://repository-images.githubusercontent.com/266445736/4f82fb80-a5b1-11ea-8f1c-69d316f861b5" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/owncast/owncast">owncast/go.mod at develop · owncast/owncast</a></strong></div><div>Take control over your live stream video by running it yourself.  Streaming + chat out of the box. - owncast/go.mod at develop · owncast/owncast</div></blockquote>
