### ISSUE TITLE
Reduce the shipping size of TailwindCSS

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#224]
@mattdsteele made a suggestion in #220 that we reduce the size of Tailwind, since it's quite large at its full size.

**Comment by mattdsteele** [comment]
The general approach is outlined here: https://tailwindcss.com/docs/controlling-file-size

Essentially, point the `tailwindcss` CLI at our components (or anywhere else we're referencing Tailwind classes) and it'll generate a stylesheet with only the styles we're using.

The tricky part will be how we can do this without breaking dev workflow; once we purge unused styles, it'll be hard to work with the trimmed file. We may end up needing a "development mode" which links against the unpurged file. Open to ideas!

**Comment by gabek** [comment]
This seems totally doable.  I think we can just, as a part of the release build process, can run this CLI and overwrite the full version of tailwind with the pruned version.  That means we'd always be using the full version in development and the smaller version in production, so we'd have to make sure to test the smaller version in development so the first time it's used wouldn't be production.  So that dev story of making sure the pruned version isn't breaking anything might need to be fleshed out a bit.

**Comment by gabek** [comment]
lol I think I have some work to do still.

```
gabek:video-stream/ (master✗) $ ls -alh webroot/js/web_modules/tailwindcss/dist/tailwind.min.css                                             
-rw-r--r--  1 gabek  staff   1.9M Oct 21 23:41 webroot/js/web_modules/tailwindcss/dist/tailwind.min.css

./build/javascript/node_modules/.bin/tailwind build > ./webroot/js/web_modules/tailwindcss/dist/tailwind.min.css > ./webroot/js/web_modules/tailwindcss/dist/tailwind.min.css
gabek:video-stream/ (master✗) $ ls -alh webroot/js/web_modules/tailwindcss/dist/tailwind.min.css                                             
-rw-r--r--  1 gabek  staff   2.3M Oct 21 23:41 webroot/js/web_modules/tailwindcss/dist/tailwind.min.css
```

1.9M before purging and 2.3M after.  I'll eventually figure it out :)

**Comment by gabek** [comment]
Made progress.  Need to figure out where this step needs to happen in the build process stil.

```
$ NODE_ENV="production" ./node_modules/.bin/tailwind build | ./node_modules/.bin/postcss > test.css
$ ls -alh test.css
-rw-r--r--  1 gabek  staff   6.3K Oct 24 16:32 test.css
```
