### ISSUE TITLE
Do not show Followers tab if social/federation features are not enabled

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2244]
### Share your bug report, feature request, or comment.

This tab has been hard-coded to be displayed to make it easier for people to work on the Owncast web frontend, but at some point we'll want to re-hide it if the feature is not enabled.

We can do this later, but filing this now so it's not forgotten.

**Comment by agremi** [comment]
Hi, can you assign me this issue?

**Comment by gabek** [comment]
Unfortunately we probably don't want to do this quite yet because we haven't finished work on the Follow tab, and after we hide it it'll be more difficult for people to access it, since they'll have to setup the additional functionality.

**Comment by agremi** [comment]
Ok,no problem

**Comment by gabek** [comment]
In the next steps to push forward, disabled social/fediverse features are no longer displayed by default and must be enabled if you want to test them.
