### ISSUE TITLE
Page content header is using the mobile layout instead of desktop

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2245]
### Share your bug report, feature request, or comment.

It currently looks like 
![image](https://user-images.githubusercontent.com/414923/197351310-2dc3bdd6-9dba-4fd4-bcdd-a4949f426015.png)

But it should look like
![image](https://user-images.githubusercontent.com/414923/197351666-834a3b32-0568-48ef-9bd1-86d8170b04fd.png)

**Comment by t1enne** [comment]
fixed by b7795f275ce3711ac14dc803800a3a9dff54d0e7
