### ISSUE TITLE
Do not show Follow button if follow feature is not enabled

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2252]
### Share your bug report, feature request, or comment.

This has been hard-coded to be shown to make development easier for everyone, but at some point it should be hidden when not enabled when we're done working on it.

**Comment by dorj222** [comment]
Hi there! May I claim this issue? :)

**Comment by gabek** [comment]
Hi there! Unfortunately we're not ready for this yet, it's set to be completed when development for v0.1.0 is complete. If we were to hide this feature now it would make working on it more difficult so I'd prefer it to be done once all the development around features is complete.

If you're still interested you can certainly work on it now and put in a PR, but it won't be merged in until all the other work is complete, and there is a possibility of conflicts between now and then due to the active development happening. So while I wouldn't necessarily recommend it, it would be up to you. Let me know what you think!

See https://github.com/orgs/owncast/projects/1 for the scheduling of all the tasks in the project.

**Comment by dorj222** [comment]
Ah, I see. Thanks for the response!

**Comment by gabek** [comment]
In the next steps to push forward, disabled social/fediverse features are no longer displayed by default and must be enabled if you want to test them.
