### ISSUE TITLE
Storybook: Name change modal story no longer displays

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2255]
### Share your bug report, feature request, or comment.

The name change modal no longer renders in Storybook.

Story: https://owncast.online/components/?path=%2Fdocs%2Fowncast-modals-name-change--basic

**Comment by Lz-01** [comment]
please assign this issue to me

**Comment by gabek** [comment]
Of course, thank you!

**Comment by gabek** [comment]
I fixed a similar issue with another modal. You might be able to model the fix for this one off of the other.

https://github.com/owncast/owncast/commit/e0b7ae5b3a7ed648dc1dba1db6feec5e77f075e7

**Comment by gabek** [comment]
Hi there @Lz-01 How are things going? Do you still intend to look at this?

**Comment by gabek** [comment]
I went ahead and took care of this.
