### ISSUE TITLE
Authentication modal doesn't layout properly when mobile

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2262]
### Share your bug report, feature request, or comment.

![image](https://user-images.githubusercontent.com/414923/197661071-3659901d-6f85-4f3e-93c4-cd1ab2b72293.png)

**Comment by heller** [comment]
Trying to reproduce this. Seems ok in Safari in iPhone 8 and SE/5 sizes.

<img width="540" alt="image" src="https://user-images.githubusercontent.com/32307/197836718-bf21d538-96e8-42d7-8b59-34fdfc540acd.png">

<img width="552" alt="image" src="https://user-images.githubusercontent.com/32307/197836874-a24f7fe9-37aa-4bcf-ba47-acc822d63463.png">
