### ISSUE TITLE
Content header on mobile is not using the mobile layout.

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2263]
It used to have the logo on top and centered. It looks like mobile might be using the desktop layout now. 

Now:

![image](https://user-images.githubusercontent.com/414923/197672526-331509a4-6140-44d1-bc62-604eccead210.png)

Used to be:
![image](https://user-images.githubusercontent.com/414923/197672895-f9ffba11-c9b7-4ae2-8648-84d1d99cf988.jpeg)

**Comment by Lz-01** [comment]
Can you assign this issue to me?

**Comment by gabek** [comment]
Sure!

**Comment by gabek** [comment]
Hi there! Just checking in to see if everything is going ok, or if there's anything I can help with.

**Comment by gabek** [comment]
I'm going to go ahead and unassign just because this needs to be done. If you happen to still want to work on it, feel free to chime back in.

**Comment by gabek** [comment]
Should we center the title for mobile, as well?
