### ISSUE TITLE
Add a custom scrollbar

### ISSUE THREAD

**Issue by Vanshiii203** [owncast/owncast#2264]

**Comment by gabek** [comment]
Care to elaborate? What do you mean? What are you trying to do?

**Comment by Vanshiii203** [comment]
> Care to elaborate? What do you mean? What are you trying to do?

I would like to add scrollbar. I've attached an image below for your reference
![Screenshot_2022-10-25-11-56-01-87_680d03679600f7af0b4c700c6b270fe7~2](https://user-images.githubusercontent.com/94471189/197698699-80e7e330-c337-4933-a642-a5f9771d5da3.jpg)

**Comment by gabek** [comment]
Any kind of custom styling you can do through CSS. You can add your own custom CSS via the admin:

https://owncast.online/docs/website/#custom-styles-via-css

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="/favicon.png" height="14"> Owncast</div><div><strong><a href="/docs/website/">Web Site + Chat</a></strong></div><div>Customize your Owncast web page by adding additional content and links.</div></blockquote>

**Comment by gabek** [comment]
Hi there. Is this a solution for your needs?
