### ISSUE TITLE
Restream to other RTMP sources

### ISSUE THREAD

**Issue by valerio-bozzolan** [owncast/owncast#2286]
It could be nice to have an easy way to send an RTMP source to multiple platforms.

Example (all the arrows are RTMP connections):

![Restream OwnCast proposal. There is an RTMP source sent to OwnCast, and then OwnCast sending the same RTMP signal to Facebook, PeerTube and YouTube, and to another OwnCast](https://user-images.githubusercontent.com/6052909/199004250-811b04c3-3bf2-4d58-86fb-488a62950182.png)

Note: this is a killer feature for easy streaming federation and load balancing.

Requirements:

* an interruption of one output (e.g. Facebook) must not interrupt all the others (e.g. PeerTube and YouTube)

**Comment by gabek** [comment]
Owncast is its own streaming destination and its [goal](https://github.com/owncast/owncast/blob/develop/docs/product-definition.md) is to provide you a live video streaming and chat server. The functionality you asked for does not align with that goal.

I understand it would be convenient for you to throw random features into Owncast that would make your life easier, but putting as much random stuff into Owncast as possible isn't the point. There are other tools for streaming to multiple destinations at the same time who can focus on that functionality.

**Comment by valerio-bozzolan** [comment]
@gabek OK but can you be so kind to mention at least 1 of the other tools for streaming to multiple destinations?

AFAIK there aren't web Open tools for that.

**Comment by gabek** [comment]
https://github.com/muesli/prism

<blockquote><img src="https://opengraph.githubassets.com/e8f686d435b934c2eb56413aed2472f32ab649db701419a0826c0a5562b90dbe/muesli/prism" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/muesli/prism">GitHub - muesli/prism: An RTMP stream recaster / splitter</a></strong></div><div>An RTMP stream recaster / splitter. Contribute to muesli/prism development by creating an account on GitHub.</div></blockquote>

**Comment by aaronpk** [comment]
You can also do it with nginx and the nginx RTMP module:

* https://github.com/theonemule/nginx-rtmp
* https://github.com/arut/nginx-rtmp-module
* https://arstech.net/how-to-setup-nginx-rtmp-server/


<blockquote><img src="https://opengraph.githubassets.com/faf27174842c8a6aaa170f791488e1a097d0002a59014b2fc86b6f80615c609c/theonemule/nginx-rtmp" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/theonemule/nginx-rtmp">GitHub - theonemule/nginx-rtmp: A containerize NGINX server with the RTMP plugin to allow live streams to multiple providers such as Twitch, Facebook, or YouTube simultaneously from a single source.</a></strong></div><div>A containerize NGINX server with the RTMP plugin to allow live streams to multiple providers such as Twitch, Facebook, or YouTube simultaneously from a single source. - GitHub - theonemule/nginx-rt...</div></blockquote>
<blockquote><img src="https://opengraph.githubassets.com/af668c2aaeba5d4f9c1c68e5b602aeb04eeedea5571c84f58dc0f417142025e6/arut/nginx-rtmp-module" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/arut/nginx-rtmp-module">GitHub - arut/nginx-rtmp-module: NGINX-based Media Streaming Server</a></strong></div><div>NGINX-based Media Streaming Server. Contribute to arut/nginx-rtmp-module development by creating an account on GitHub.</div></blockquote>
<blockquote><img src="https://arstech.net/wp-content/uploads/2020/05/nginx-rtmp-server-streaming.png" width="48" align="right"><div><img src="https://i0.wp.com/arstech.net/wp-content/uploads/2019/08/cropped-logo.jpg?fit=192%2C192&ssl=1" height="14"> Computer How To</div><div><strong><a href="https://arstech.net/how-to-setup-nginx-rtmp-server/">How To Setup NGINX RTMP Server and Re-stream to Twitch, YouTube, ... -</a></strong></div><div>In this article you will learn how to setup NGINX RTMP Server and Re-stream to Twitch, YouTube, Facebook or any other streaming platform. Step by step</div></blockquote>

**Comment by aaronpk** [comment]
Since this keeps coming up, I just wrote up some more complete instructions for how to do this with the nginx RTMP module:

https://aaronparecki.com/2022/11/14/9/raspberry-pi-restream

<blockquote><div>Aaron Parecki</div><div><strong><a href="https://aaronparecki.com/2022/11/14/9/raspberry-pi-restream">How to Build a Restreaming Server with a Raspberry Pi</a></strong></div><div>First of all, what is a restreaming server? Sometimes you want to livestream video from a device like an ATEM Mini or OBS to multiple destinations. Many devices and software like this will let you push video to just one RTMP destination ...</div></blockquote>

**Comment by gabek** [comment]
That's very cool, Aaron, thank you! I'm sure a lot of people will find this useful.
