### ISSUE TITLE
Logo images don't size to fit

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#230]
If you specify a logo image in your config file with a background color it shows that it doesn't stretch and fill the logo image circle.
 
![image](https://user-images.githubusercontent.com/414923/95417630-5f597600-08ea-11eb-9024-d3072e701042.png)

**Comment by gabek** [comment]
@ginger Can I remove this sizing that's making the image smaller than its container?

![image](https://user-images.githubusercontent.com/414923/95425195-c2520980-08f8-11eb-8f93-0de2fa4694a5.png)

**Comment by gingervitis** [comment]
I suppose you can remove the `-1em`
