### ISSUE TITLE
cannot find module / first days of novembre 2022

### ISSUE THREAD

**Issue by interbr** [owncast/owncast#2300]
### Share your bug report, feature request, or comment.

Dear madam or sir,
the current possibility to install owncast is not possible with message
`build github.com/owncast/owncast: cannot find module for path crypto/ed25519`

Is it possible to install owncast this morning CEWT?
Sincerely
Felix Longolius (interbr)

**Comment by gabek** [comment]
What version of Go are you using?

**Comment by interbr** [comment]
Thank you. I propably had a problem with go from source not overwriting the version i primarily installed from the package manager. I am certain it will work then and apologise for my strange communication style. When I now look "go version" it gives 1.11.6 instead of the latest from source that I ... that I installed in advance to asking for help here. So some kind of a slip on my side.
