### ISSUE TITLE
Make streaming key and admin password different values

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2320]
While the initial goal of Owncast is to be single-tenant software (one user per instance) I do think it's reasonable to share an instance with others. But I fear there will be significant downsides to having a streamer without access to the admin. They won't know about stream performance, errors, logs, etc.

My concern is seeing issues like "It's fine when I stream but when my friend streams there's problems" and I ask what the problems are and they say "I don't know, they can't access the admin".

It's just something to think about. But since enough people have mentioned it, I do think it's reasonable to make this change and add a new feature where streaming keys can be added and deleted decoupled from the admin password.

I anticipate being able to get this around version 0.2.0 after the major rebuild of the web interface is launched.

### Discussed in https://github.com/owncast/owncast/discussions/2319

<div type='discussions-op-text'>

<sup>Originally posted by **DidierMalenfant** November 11, 2022</sup>
Hey everyone,

Just starting to dip my toes in the owncast ocean and I have a server up and running on Digital Ocean to replace my Mixcloud account.

I have what may be a noob question (sorry if it is), can you separate the admin passwd from the stream key? If I want to share the stream key with other so they can stream on my server but I don't want them to administrate the server.

Thanks for all the hard work on all this btw, this is really really awesome...</div>

**Comment by DidierMalenfant** [comment]
I think those are valid concerns and I imagine that maybe eventually something like multiple users with different roles would cater for all use cases.

This could be a stepping stone toward that though.

I'm obviously not familiar enough with the the code base or architecture involved but it seems like other stepping stones could be:
- Allowing the admin account name to be changed (see https://github.com/owncast/owncast/discussions/1740)
- Adding a stats public page to the server (myserver/stats) which could be enabled in the configuration and would only display the stream/hardware stats pages.

Just thoughts...

<blockquote><img src="https://opengraph.githubassets.com/6fdfef89a42612fd3cded9ea168d9959e57b5dcbbde1525c73589e3078d6328f/owncast/owncast/discussions/1740" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/owncast/owncast/discussions/1740">How can I change the default 'admin' username to another one? · Discussion #1740 · owncast/owncast</a></strong></div><div>I&#39;d like to change the default &#39;admin&#39; username to something else. An additionally welcome thing would be having a different password from the streamkey. Is there a way to change these ...</div></blockquote>

**Comment by gabek** [comment]
Nevermind. I felt like working on it, so it'll be in for v0.1.0.

**Comment by LittleFox94** [comment]
> While the initial goal of Owncast is to be single-tenant software (one user per instance) I do think it's reasonable to share an instance with others. But I fear there will be significant downsides to having a streamer without access to the admin. They won't know about stream performance, errors, logs, etc.

What about a streaming key gives read-only access to the admin area - that way they can still see performance, errors and co while not being able to change anything or access sensitive information (e.g. S3 credentials)?

Not sure this is the best place for discussion, but since the point was raised here, it feels like the best :sweat_smile: 

(and I realize I'm really late with this - only got the notification from the discussion and did not see this issue before)
