### ISSUE TITLE
Overall code coverage

### ISSUE THREAD

**Issue by juliana-mol** [owncast/owncast#2341]
### Share your bug report, feature request, or comment.

I would like to measure the overall code coverage for this project a potentially contribute to increase that. Could you give me a hint how should I do that ? I have already taken a look at the test folder where tests are either load or automated but I do not know how can I measure the code coverage for the project as the whole. Do you also have some unit tests for this project ?

**Comment by gabek** [comment]
Hi there!

What kind of tests are you thinking about? Backend unit tests, frontend unit tests, browser testing, load tests, or integration tests? 

Each type is built and run differently with different goals. All of them could be improved, but you'd kind of need to pick a specific goal and work towards that.

Unit tests for the backend are located in the same package as the code.

Here's some links that might be useful:

- Backend unit tests: https://pkg.go.dev/testing
- Cypress automated browser tests (in the `webv2` branch): https://docs.cypress.io/
- API integration tests: https://github.com/owncast/owncast/tree/develop/test/automated/api

<blockquote><img src="/static/shared/icon/favicon.ico" width="48" align="right"><div><strong><a href="https://pkg.go.dev/testing">testing package - testing - Go Packages</a></strong></div><div>Package testing provides support for automated testing of Go packages.</div></blockquote>
<blockquote><img src="https://docs.cypress.io/img/real-world-app.png" width="48" align="right"><div><img src="/favicon.svg" height="14"> Cypress Documentation</div><div><strong><a href="https://docs.cypress.io/guides/overview/why-cypress">Why Cypress? | Cypress Documentation</a></strong></div><div>What you'll learn What Cypress is and why you should use it Our mission, and what we believe in Key Cypress features Types of tests Cypress is designed</div></blockquote>
<blockquote><img src="https://repository-images.githubusercontent.com/266445736/4f82fb80-a5b1-11ea-8f1c-69d316f861b5" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/owncast/owncast">owncast/test/automated/api at develop · owncast/owncast</a></strong></div><div>Take control over your live stream video by running it yourself.  Streaming + chat out of the box. - owncast/test/automated/api at develop · owncast/owncast</div></blockquote>

**Comment by gabek** [comment]
Hey @juliana-mol! Did my comments above help answer your questions and help point you in the direction that you might be interested in helping with?

**Comment by juliana-mol** [comment]
Hi, I would like to write some frontend unit tests or api tests (something like these here: https://github.com/owncast/owncast/tree/develop/test/automated/api). I have looked into the links that you suggested, but I am still unable to get the current code coverage so that after adding new tests I would see if it has been increased. I have locally configured cypress with plugin @cypress/code-coverage but I have trouble with code instrumentation (https://docs.cypress.io/guides/tooling/code-coverage#Instrumenting-code this is not really working for me) so the generated report I am getting is currently empty.

<blockquote><img src="https://repository-images.githubusercontent.com/266445736/4f82fb80-a5b1-11ea-8f1c-69d316f861b5" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/owncast/owncast">owncast/test/automated/api at develop · owncast/owncast</a></strong></div><div>Take control over your live stream video by running it yourself.  Streaming + chat out of the box. - owncast/test/automated/api at develop · owncast/owncast</div></blockquote>
<blockquote><img src="https://docs.cypress.io/img/real-world-app.png" width="48" align="right"><div><img src="/favicon.svg" height="14"> Cypress Documentation</div><div><strong><a href="https://docs.cypress.io/guides/tooling/code-coverage">Code Coverage | Cypress Documentation</a></strong></div><div>What you'll learn How to instrument your application code How to save the coverage information collected during end-to-end and unit tests How to use the</div></blockquote>

**Comment by gabek** [comment]
Hi there! Maybe I can clarify the different types of tests a bit.

By **frontend** unit tests do you mean **Javascript** unit tests? The automated Cypress frontend tests aren't unit tests, they're automated browser tests. And automated browser tests I'm not sure how you'd be able to determine "coverage" for that because you're not testing code, like you would for a unit test, you're automating the browser experience.

We don't currently have any Javascript unit tests. To start with that you wouldn't use Cypress, but you'd start writing them with Jest: https://jestjs.io/

The automated API tests are another example of something that aren't unit tests, so there's no way to get a number determining coverage from it like you were looking to do.

If you're looking to determine the code coverage of unit tests the options are:

1. Go code unit tests
2. Javascript code unit tests (there are none)
