### ISSUE TITLE
Fix deprecation warning with NotifyReminderPopup

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2345]
### Share your bug report, feature request, or comment.

![image](https://user-images.githubusercontent.com/414923/201569682-e0a0facb-e14a-407e-b667-667f8f75582a.png)

Component: https://owncast.online/components/?path=%2Fstory%2Fowncast-components-notify-reminder--active

**Comment by gabek** [comment]
Looks like this won't be resolved with Ant Design until v5. 

https://github.com/ant-design/ant-design/issues/26136

**Comment by dorj222** [comment]
if no one is working on this, may I work on this issue? :)

**Comment by gabek** [comment]
I'm not sure there's anything we can do until we update to Ant Design v5: https://github.com/ant-design/ant-design/issues/26136. Not quite ready to do all the work that will be required to pull off that major update yet, though.

**Comment by dorj222** [comment]
ah, I see. Thanks for your response!
