### ISSUE TITLE
Notify reminder popup can show up in odd places

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2358]
### Share your bug report, feature request, or comment.

In this case it didn't even scroll with the rest of the page.

![image](https://user-images.githubusercontent.com/414923/202831106-279429a6-ed83-4e1f-9d0f-e41004aecf40.png)

**Comment by dorj222** [comment]
Hey there! May I claim this issue and work on it? :)

**Comment by gabek** [comment]
Sure! Just as a heads up this popup will appear after visiting the page three times. So if you're not seeing it right a way, that's why. Thanks for looking at this!

**Comment by gabek** [comment]
I made some progress!

By adding
```
    ⋮ 74 │        getPopupContainer={node => node}
```
to the `Popover` component in `NotifyReminderPopup` it fixes the scrolling problem!

But the downside is it reduces the size of the actual popup and makes it look weird.

![image](https://user-images.githubusercontent.com/414923/209608903-54e940ff-164a-4843-9053-1ef5ec8cb88a.png)

**Comment by dorj222** [comment]
That's wonderful! Thanks a lot for this progress! I will work on the UI issue of the popup. :)
