### ISSUE TITLE
Player should fill the full with of the container, but content should keep aspect ratio

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2360]
### Share your bug report, feature request, or comment.

Recent changes have fixed #2204 and #2303, but now a side effect is the player no longer fills the width of the container.

What we need is:

1. The player and thumbnail to fill the full width of the 16/9 aspect-ratio container.
2. But the player _content_ should fit itself without resizing the container.

So in this screenshot the content size is correct, but we want the bottom player bar to be able to fill the entire width.

![image](https://user-images.githubusercontent.com/414923/202872576-8aaef2c4-94e3-4555-b0cd-efff1e3954bb.png)

**Comment by dorj222** [comment]
Hey there! May I claim and work on this issue?

**Comment by gabek** [comment]
For sure, thank you!

**Comment by gabek** [comment]
Hi there, have you been able to take a look at this?

**Comment by gabek** [comment]
I'm going to unassign this since I know you're working on a couple other things as well, but feel free to ping again if you happen to be working on this!

**Comment by dorj222** [comment]
Hey there! I was a bit busy lately and wasn't able to work on this issue. I will let you know if I decide to work on this issue again. :)

**Comment by Rengkat** [comment]
If you are busy, i can help. thanks

**Comment by gabek** [comment]
That would be awesome, thank you! Feel free to chime in if you have any questions or clarifications.

**Comment by gabek** [comment]
@Rengkat Hi there! Just checking in, are you still looking at this?

**Comment by gabek** [comment]
I sat down to take a look at this and got the desired result. It starts to look a little weird as the viewport gets more narrow but that can be fixed. Assigning it to myself.

![image](https://user-images.githubusercontent.com/414923/213886612-991014e2-351c-475c-88ce-3795e6c13b5c.png)

**Comment by gabek** [comment]
Current status. Desktop and phone looks fine but tablet doesn't.

Desktop: 
![image](https://user-images.githubusercontent.com/414923/214225026-97967b27-8d8f-4092-bd44-4af86c9687ef.png)

Tablet portrait:
![image](https://user-images.githubusercontent.com/414923/214225214-706562be-72e0-4d4d-971e-44a178ebae13.png)

Tablet landscape: 
![image](https://user-images.githubusercontent.com/414923/214225307-4d9b8b48-6182-463e-83e1-c1b244b81686.png)

Mobile:
![image](https://user-images.githubusercontent.com/414923/214225423-2456b88c-61bd-4479-856c-e183a5fddbcc.png)

**Comment by gabek** [comment]
Thought it was fixed. It was not.

![image](https://user-images.githubusercontent.com/414923/215366251-5131b65c-3f28-48ea-b6bc-528d03f5f4e3.png)
