### ISSUE TITLE
Remove deprecated Go linters

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2367]
### Share your bug report, feature request, or comment.

```
WARN [runner] The linter 'deadcode' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused.
WARN [runner] The linter 'varcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused.
```

**Comment by MFTabriz** [comment]
is this issue already solved? I don't see it on recent runs (for example: [1](https://github.com/owncast/owncast/actions/runs/3718464546/jobs/6306686703))

**Comment by gabek** [comment]
I don't recall fixing it but I also no longer see the warning.
