### ISSUE TITLE
Add Misskey and Pleroma plateform in "Your Social Handles"

### ISSUE THREAD

**Issue by kazukyakayashi** [owncast/owncast#2376]
### Share your bug report, feature request, or comment.

Can you add the logos for the Misskey and Pleroma platforms to the list for links to social networks ?

**Comment by gabek** [comment]
The next release will have a "Fediverse" logo to cover most things. I probably made a mistake by adding Mastodon in the first place, as Mastodon isn't a platform, it's an implementation. I feel the same way about Misskey and Pleroma, they are just Fediverse implementations. If somebody feels strongly about adding these, I wouldn't turn it down, though.

**Comment by kazukyakayashi** [comment]
It's true, but on the other hand these 3 platforms don't have the same options nor the same visual ... I don't think it's a mistake, it allows you to know which one you're going to get, but yes I understand your point of view, besides it's probably better.
