### ISSUE TITLE
Allow uploading custom emoji through the admin

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2378]
### Share your bug report, feature request, or comment.

It would be useful for people to have a way to manage custom emoji images through the admin instead of through the filesystem of the machine Owncast is running on.

- Upload new images
- Delete unwanted ones

Note: Starting with`webv2` emoji images are pulled from `data/emoji` and no longer the old `webroot`.

**Comment by xarantolus** [comment]
Hey, I'd be interested in working on this. I think it would make sense to put this setting under "Chat & Users" as a new category and then create a menu similar to the external actions table.
One question on this: The emoji listing should show both emojis from `data/emoji` and `static/img/emoji`, right? When a user deletes one of the static ones, should we delete it from the file system or somehow mark it as unused in the database?
Also, should it be enforced that the image is square (and should we limit the size/automatically downscale to prevent a single emoji from being too large)?

**Comment by gabek** [comment]
Awesome, thank you! And these are all good questions!

> The emoji listing should show both emojis from data/emoji and static/img/emoji, right?

So as it stands, if you create your own custom emoji directory in `data/emoji` then it overrides the emoji that are bundled into the application. Because the bundled emoji are literally built into the application there's no way to delete them. So unless we changed how that whole process works it's "100% custom" or "100% built-in". We could merge custom and built-in, but it might be weird that you'd be able to delete some of them (the custom ones) but no the built-in ones.

We could also do something completely different like on first launch copy the built-in emoji into `data/emoji` and then allow people to delete them and add their own.

> Also, should it be enforced that the image is square (and should we limit the size/automatically downscale to prevent a single emoji from being too large)?

I don't think we should be concerned too much with that. Let people do what they want to do. Besides, if they just copy a directory of custom emoji to `data/emoji` then there wouldn't be any way for us to inspect them anyway.
