### ISSUE TITLE
Auto-move custom emoji location when upgrading to v0.1.0

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2379]
### Share your bug report, feature request, or comment.

Otherwise people will probably be confused why their custom emoji files are not available until they look into the changelog (that they may or not read).

`webroot/emoji` -> `data/emoji`

**Comment by MFTabriz** [comment]
I think I will add this to the script too

**Comment by gabek** [comment]
This can't be done in the installer script because not everyone uses the script. It needs to be run as some sort of migration step in the codebase itself.

**Comment by MFTabriz** [comment]
😅 you are right!
