### ISSUE TITLE
Fediverse logo image is broken in the admin

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2380]
### Share your bug report, feature request, or comment.

On webv2.
![image](https://user-images.githubusercontent.com/414923/203860576-34f77229-6042-41cd-9f5b-53eaf61cf302.png)

**Comment by AlexVCS** [comment]
Hi, I'd like to work on this issue. Can you assign it to me please?

**Comment by gabek** [comment]
Absolutely, thank you! 😁

**Comment by gabek** [comment]
Hi there! Just checking in to see if you're still working on this.

**Comment by gabek** [comment]
I went ahead and took care of this so it could be closed out.
