### ISSUE TITLE
Logo upload not replacing logo

### ISSUE THREAD

**Issue by roadriverrail** [owncast/owncast#2387]
### Share your bug report, feature request, or comment.

Back again...this is again from a cloud computing instance (on Dreamcompute) that I have cloned.  I'm trying to change the logo through the web frontend.  I upload the new file, the logo changes, and it says "success!" but the old logo remains and refreshing the page reverts it to the previous one.

journalctl doesn't show any helpful logging for this.

**Comment by gabek** [comment]
The old logo is likely cached in your browser as reported in this issue: https://github.com/owncast/owncast/issues/2130

**Comment by roadriverrail** [comment]
Correct.  This is a dupe.
