### ISSUE TITLE
Install script upgrade: Remove backup of web directory

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2389]
### Share your bug report, feature request, or comment.

As a part of the installer script upgrade step it backs up the web directory. This will no longer be possible or needed as of v0.1.0, so this should be removed from the script.

**Comment by MFTabriz** [comment]
you mean in [this script](https://github.com/owncast/owncast.github.io/blob/master/static/install.sh)?

**Comment by gabek** [comment]
Yup, that's the one!

**Comment by gabek** [comment]
Merged into `v0.1.0` branch.
