### ISSUE TITLE
Default modal width is too narrow

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2395]
### Share your bug report, feature request, or comment.

![image](https://user-images.githubusercontent.com/414923/204711730-a2a7f12f-8d1b-475f-9f79-7de2e6becf80.png)

**Comment by americobarros** [comment]
Hey, could I take this ticket?

**Comment by gabek** [comment]
Of course, thank you!

**Comment by americobarros** [comment]
@gabek Just to be clear, this ticket is to fix the second scroll bar that appears in the modal, not to set a default height to the model, correct?

**Comment by gabek** [comment]
I had originally filed it because I thought the width of these modals by default was too narrow. Especially when it's showing external content like in the screenshot.  So I thought it should be wider.

There's also, that second scroll bar, and if you could look at that too, that would be awesome! That's pretty annoying :)

![image](https://user-images.githubusercontent.com/414923/205760561-91d3434b-7afb-4dc5-9b11-556fadd650f9.png)
