### ISSUE TITLE
malformed module path "embed": missing dot in first path element

### ISSUE THREAD

**Issue by KyleMaas** [owncast/owncast#2400]
### Share your bug report, feature request, or comment.

When attempting to build current webv2 branch (commit 9de0f00ad4cba48de71e6571704f83043f5dc103), I get the following error:

```
build command-line-arguments: cannot load embed: malformed module path "embed": missing dot in first path element
```

Are there other steps which need to be run to build now other than what's documented?

**Comment by gabek** [comment]
It looks like you might have an old version of Go installed. 1.17 is required to have `embed`.

**Comment by KyleMaas** [comment]
Yep, that did it.  Sorry for bothering you with something so simple!
