### ISSUE TITLE
CI tests for webv2 branch

### ISSUE THREAD

**Issue by KyleMaas** [owncast/owncast#2401]
### Share your bug report, feature request, or comment.

Any possibility of integrating some CI testing into the project, specifically for the webv2 branch, to make sure that it at least builds correctly?

**Comment by gabek** [comment]
There's a bunch of tests that get fired via CI on the `webv2` branch. You can check them out here: https://github.com/owncast/owncast/tree/webv2/.github/workflows

<blockquote><img src="https://repository-images.githubusercontent.com/266445736/4f82fb80-a5b1-11ea-8f1c-69d316f861b5" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/owncast/owncast">owncast/.github/workflows at webv2 · owncast/owncast</a></strong></div><div>Take control over your live stream video by running it yourself.  Streaming + chat out of the box. - owncast/.github/workflows at webv2 · owncast/owncast</div></blockquote>

**Comment by KyleMaas** [comment]
Huh.  Are they not running on each commit?  Because I can see test results for the `develop` branch but I don't see them for the most recent `webv2` commit.

Looking at the commit history on `webv2`, I can see some of the commits have test results, though.

**Comment by gabek** [comment]
Correct, if you push up 10 commits they won't run for each commit that you pushed. They're run on the act of a push and when PRs are created.

**Comment by KyleMaas** [comment]
That makes sense.  Thank you!
