### ISSUE TITLE
Chatbox can't be used on Chrome, android device 

### ISSUE THREAD

**Issue by elaur** [owncast/owncast#2403]
Hi just want to say the chat box looks hidden on my phone. I'm using Google chrome, Android 13 on Google Pixel 7

**Comment by elaur** [comment]
![Screenshot_20221204-130758](https://user-images.githubusercontent.com/1698121/205492597-a20096ac-417a-46ef-b830-cab86d0c4ce1.png)

**Comment by gabek** [comment]
This is resolved in new web interface. Closing since the old UI will no longer be receiving any updates.

**Comment by elaur** [comment]
Update demo page to new UI.
