### ISSUE TITLE
Ability to manipulate the number of viewers !

### ISSUE THREAD

**Issue by adim-att** [owncast/owncast#2409]
### Share your bug report, feature request, or comment.

Shouldn't there be a feature in the settings, that allow you to change the displayed number of how many people are watching ?

**Comment by gabek** [comment]
What would the use case of that be?

**Comment by adim-att** [comment]
> What would the use case of that be?

To tell others that they are streaming in different places as well.

**Comment by gabek** [comment]
Could you give a concrete example? I'm afraid I still don't understand your use case.

**Comment by adim-att** [comment]
If I am streaming my platform using other tools, even maybe using another Owncast server with a different link.
I would want to change my viewer count. to display whatever viewers we think are actually watching us.

If you don't get it, just never mind and excuse me.

**Comment by gabek** [comment]
I do see what you're saying now. But you'd have to manually type in the number of viewers every time somebody starts or stops watching your stream. And there's no events to alert you to when somebody is tuning in or stopping the stream, so there's nothing to prompt you to add or remove one from your total.

I'm afraid this might be a niche request without a good direction on how to accomplish it.
