### ISSUE TITLE
I get an error about 40 seconds into launching the server --> "panic: runtime error: index out of range [0] with length 0"

### ISSUE THREAD

**Issue by driftywinds** [owncast/owncast#2423]
### This is the error I get: - 
```
panic: runtime error: index out of range [0] with length 0
```
I run an aarch64 ubuntu-server machine and everything works fine for a while until it doesn't and pops this error, shutting down the server.

**Comment by driftywinds** [comment]
I believe it is because it is not able to measure the CPU, GPU and memory metrics. How do I turn this monitoring off?

**Comment by gabek** [comment]
It cannot be turned off without removing it in the source and rebuilding yourself. Could you provide the details you used to determine it's hardware monitoring so I can look into it? As an aside there is no GPU monitoring.

**Comment by driftywinds** [comment]
My bad, I should've provided these in the beginning, here is what it says in its entirety before it shuts down: -
```
panic: runtime error: index out of range [0] with length 0

goroutine 84 [running]:
github.com/owncast/owncast/metrics.collectCPUUtilization()
        /go/src/github.com/owncast/owncast/metrics/hardware.go:27 +0x208
github.com/owncast/owncast/metrics.handlePolling()
        /go/src/github.com/owncast/owncast/metrics/metrics.go:89 +0xbc
github.com/owncast/owncast/metrics.Start.func1()
        /go/src/github.com/owncast/owncast/metrics/metrics.go:73 +0x48
created by github.com/owncast/owncast/metrics.Start
        /go/src/github.com/owncast/owncast/metrics/metrics.go:71 +0x1cc
```

**Comment by gabek** [comment]
Thank you!

**Comment by MFTabriz** [comment]
@gabek Is this a bug in [gopsutil](https://github.com/shirou/gopsutil)? `cpu.Percent()` should return an error if it cannot report anything.

**Comment by gabek** [comment]
Likely. It probably throws an error if it can't see any CPUs, but this case seems to be "I see CPUs but can't read values from them". I didn't dig into it, though.

**Comment by driftywinds** [comment]
Don't mean to rush you at all, but i wanted to know when you plan to release builds with this change incorporated?

**Comment by gabek** [comment]
Unfortunately I don't have an answer for you. There's no plan for a release before v0.1.0 but just like v0.0.13, if it takes longer than expected perhaps an additional patch release can be made.
