### ISSUE TITLE
API to get a thumbnail for the stream

### ISSUE THREAD

**Issue by KyleMaas** [owncast/owncast#2425]
### Share your bug report, feature request, or comment.

Is there an API to call to get a thumbnail for the stream?  Basically the static image that's shown in the player before the user clicks the play button?

An embed endpoint like this would be ideal:

`/embed/video/thumbnail.jpg`

**Comment by MFTabriz** [comment]
I think `/thumbnail.jpg` should be the one you're looking for. For example: https://watch.owncast.online/thumbnail.jpg

**Comment by KyleMaas** [comment]
Perfect.  Exactly what I was looking for.  Is this mentioned anywhere in the docs where I could have RTFM'd it?

**Comment by gabek** [comment]
The OpenAPI spec is severely lacking due to it needing to be manually written by hand. It's so error prone, and many things aren't listed in there that maybe should be. It's so incorrect and so labor intensive I kind of think about killing it instead of it being wrong.

**Comment by KyleMaas** [comment]
No problem.  Just didn't want to keep bothering y'all about simple stuff like this if there was somewhere I should be reading about it.  Thanks!
