### ISSUE TITLE
Accessibility: Page should contain a level-one heading

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2446]
## Page should contain a level-one heading

https://axe.deque.com/issues/a5f7b758-fc67-4ede-8393-7f2efa99e436

> Ensure that the page, or at least one of its frames contains a level-one heading
>
>To solve this problem, you need to...
> Fix the following:
> Page must have a level-one heading

![image](https://user-images.githubusercontent.com/414923/207454407-d4f0f533-813d-4b43-8acb-5766133234b6.png)

Re: #1826

**Comment by silksow** [comment]
Pls assign

**Comment by gabek** [comment]
Thank you!
