### ISSUE TITLE
Unable to add XMPP social link

### ISSUE THREAD

**Issue by deadtom76** [owncast/owncast#2449]
### Share your bug report, feature request, or comment.

I upgraded to 0.13 today, and I tried to add my XMPP address to my social links. I select XMPP from the drop-down list, but the only way that the "OK" button becomes active is if I put "http://" or "https://" in front of my XMPP address.

Am I missing something?

**Comment by gabek** [comment]
Nope, not missing anything.

**Comment by deadtom76** [comment]
> Nope, not missing anything.

That doesn't create a useable link, or take anyone to anything that displays my XMPP address.

**Comment by gabek** [comment]
Yeah, it's not currently configured to support anything but validating web URLs. It's on the docket to support other protocols. As it stands you can only put web URLs in there.

**Comment by gabek** [comment]
There's actually a [PR](https://github.com/owncast/owncast/pull/2047/files) up to work on this, but it comes off a bit too fragile, so I'll just file this issue as a TODO to find a simpler solution for it.

**Comment by gabek** [comment]
Could you give me an example XMPP account that you would normally try and add?

**Comment by deadtom76** [comment]
My XMPP account is deadtom@deadtom.me.

**Comment by gabek** [comment]
Got it! I didn't know if it was supposed to be prefixed with `xmpp:` or anything. Thank you!

**Comment by deadtom76** [comment]
Oh, sorry. Yeah, I believe it is supposed to be prefixed with xmpp: when embedding a link in a webpage, and that will open your default XMPP client when you click on it, however, I can't seem to find any clear documentation about it.

**Comment by gabek** [comment]
Added some specific validations for xmpp and matrix.
