### ISSUE TITLE
Change "Toggle chat" to "Hide chat" or "Show chat"

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2454]
### Share your bug report, feature request, or comment.

"Toggle chat" in the menu might not be clear what it's really going to do, so we should change it to "Show chat" and "Hide chat" just to be explicit.

![image](https://user-images.githubusercontent.com/414923/207781611-c15895d1-49e0-4b3d-9346-266362e5b2fc.png)

**Comment by mintbomb27** [comment]
Can I take this up?
