### ISSUE TITLE
Fix platform image link image warnings

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2472]
### Share your bug report, feature request, or comment.

> Image with src "/img/platformlogos/github.svg" has either width or height modified, but not the other. If you use CSS to change the size of your image, also include the styles 'width: "auto"' or 'height: "auto"' to maintain the aspect ratio.

![image](https://user-images.githubusercontent.com/414923/208803114-8185d76f-a324-40da-8978-eaccca90fcbc.png)

**Comment by Rishav1707** [comment]
Shall I work on this issues? @gabek

**Comment by MFTabriz** [comment]
@Rishav1707 I assigned it to you.

**Comment by Rishav1707** [comment]
Sorry, @MFTabriz I am unable to run the backend of this repo.
Please assign this issue to someone
