### ISSUE TITLE
Header title: Do not wrap

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2474]
### Share your bug report, feature request, or comment.

Make header title to be limited to online line and truncated.

![image](https://user-images.githubusercontent.com/414923/208826735-d0d3943e-b95a-441e-b162-530c92f33001.png)

**Comment by Rishav1707** [comment]
Could you please explain your issue once again @gabek

**Comment by Rishav1707** [comment]
I am not able to understand your issues
