### ISSUE TITLE
Limit logo file size on upload

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2480]
### Share your bug report, feature request, or comment.

Somebody tried to upload an updated logo but it was rejected server-side as being too large and as far as I can tell it didn't even fire the Owncast upload controller because it was rejected somewhere else along the way.

The client should check for a reasonable file size and throw a client-side error rejecting it so an upload doesn't even get attempted for a image that is determined to be too large.

https://owncast.rocket.chat/channel/general?msg=7GSNLKvfWkSr2ZDSd

**Comment by andrew-secret** [comment]
I can take a look at this one 🙂. Just let me know which file size it should have. I think that's a quick one (just adding a size attribute to the input element). But let's see 🫣

**Comment by gabek** [comment]
Thank you! How about 2 megs? I can't see any use case where your logo needs to be any larger than that, even that would be big in my opinion.
