### ISSUE TITLE
Longer title breaks mobile layout

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2497]
### Share your bug report, feature request, or comment.

It pushes the entire page to the left.

![image](https://user-images.githubusercontent.com/414923/209457331-8aca4c04-9ced-410e-b159-0794d988fc09.png)

**Comment by andrew-secret** [comment]
I could take a look at this one. Which solution is preferred here?
- should the text break into a new line
- truncate the content of the select box

If we think of a better UX here than truncate is not a perfect solution, but from design perspective it looks better.

**Comment by gabek** [comment]
This is actually a side effect of a previous issue where the header title broke into two lines, so I made it fit in one line, but now it's doing this.

So I think it should stay as one line, but the title could maybe truncate with ellipsis? We could also hide the text in the menu button and just leave the icon on mobile. Hopefully that could buy us enough room to fit things in the header.

Thanks for offering to look at it!

**Comment by andrew-secret** [comment]
Yeah, I think removing the name in the select box is a good soltuion:

<img width="408" alt="image" src="https://user-images.githubusercontent.com/13103896/209580303-e13e8454-426f-4622-afdb-6c426f2ada3b.png">
