### ISSUE TITLE
Mobile content height is often incorrect

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2498]
### Share your bug report, feature request, or comment.

The full player should show and the rest of the page should be the tabbed content. The player should not scroll.

![image](https://user-images.githubusercontent.com/414923/209457344-e36cb0c9-8e90-4a15-93a9-d08a975697fb.png)

**Comment by andrew-secret** [comment]
I think that issue should be resolved by https://github.com/owncast/owncast/pull/2509
