### ISSUE TITLE
On new messages chat does not scroll to the very bottom

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2500]
### Share your bug report, feature request, or comment.

When new messages come in the chat container does not scroll to the very bottom.

![image](https://user-images.githubusercontent.com/414923/209457603-2d29ad78-27b5-4b3c-b489-420984ee50c0.png)

**Comment by ShashwatAgrawal20** [comment]
Would like to work on this

**Comment by gabek** [comment]
Thank you!

**Comment by ShashwatAgrawal20** [comment]
@gabek quick question 
how can I get this chat feature in the development environment

**Comment by gabek** [comment]
You'll want to start a test stream. You can point any streaming software you'd like at your local Owncast instance. https://owncast.online/development/#run-a-development-stream

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="/favicon.png" height="14"> Owncast</div><div><strong><a href="/development/">How to work on Owncast</a></strong></div><div>The technical details for those wishing to take part in Owncast development.</div></blockquote>

**Comment by ShashwatAgrawal20** [comment]
@gabek the new messages are scrolling to the bottom by default. It doesn't scroll to the very bottom if the user has scrolled up, I think it's a good option to keep it as it is.

**Comment by gabek** [comment]
I started making some changes to work on this the other day, so I'll go ahead and assign to myself.

**Comment by gabek** [comment]
I don't believe this has actually been improved.

![image](https://github.com/owncast/owncast/assets/414923/6263259e-6faf-4106-937e-94ec48a2c714)

**Comment by gabek** [comment]
Closing this since chat has been rebuilt, and other issues around chat have been filed.
