### ISSUE TITLE
Create new development test stream option

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2502]
### Share your bug report, feature request, or comment.

A handful of people have had problems running `ocTestStream.sh`, and given it's mentioned in some of the development documentation it probably creates a bad first impression when trying to contribute to Owncast.

This script isn't required to work on Owncast, but I personally find it to be the fastest way to get a test stream running. However when it doesn't work then people are lost.

We need a more robust test stream option that probably combines `ocTestStream.sh` and [`testContent.sh`](https://github.com/owncast/owncast/blob/webv2/test/testContent.sh) to allow people to quickly get a stream up and running.

My initial thought is if you provide the path to a video file it streams it (like ocTestStream does) and if you don't it'll generate test content (like testContent does).

**Comment by MFTabriz** [comment]
@gabek what do you think about using the [test video](https://github.com/owncast/owncast/blob/webv2/test/automated/test.mp4) we already have, if no file is specified?

**Comment by gabek** [comment]
I was actually thinking about removing that test video file since `testContent.sh` can replace it. That test video is purposefully super overly compressed because it was there for automated tests that people wouldn't be visually looking at, I just needed something that was technically a video and something super small that wouldn't increase the size of our repository or hit any kind of max size limits. I kind of fear if people were to stream it and look at it they'd think something was wrong.

But I think we could have a default test video _and_ not rely on something that has to be kept in the repo.

We could have a test video that's not excessively compressed and put it up on a web server and the test script could download that video if required. Then file size wouldn't matter. It could also download ffmpeg if needed, since that seems to be a sticking point for people trying to run the test script.

**Comment by aaronpk** [comment]
One thing that occurs to me is that a lot of development of Owncast has nothing to do with the actual video pipeline, and is just about the UI around the live video, like how the chat only appears when a video is live. What about adding a development flag that simulates a live video without actually using the video streaming part of owncast? Basically something that could toggle the video player playing a short static clip from the web server so that the streaming UI loads. But not actually using any of the transcoding pipeline. Just a thought, feel free to ignore.

**Comment by gabek** [comment]
It's a valid suggestion for sure. Unfortunately there's a lot of things that derive state from the existence of the inbound stream itself. It would requite a lot of `if inTesting` logic to fake state in the backend and changing up the frontend player  to know about test state so it can update its config to point at something else.

But in general I think we can do better with this part of the development process. Admittedly it hasn't been something that's come up until recently, but it does seem to be a sticking point. Not requiring a video to be on hand could go a long way and we can just generate colored bars to meet the streaming requirements and make things "online".

**Comment by 4censord** [comment]
> But I think we could have a default test video and not rely on something that has to be kept in the repo.

It may be worth thinking about using git lfs for bigger testfiles.
That would solve the repo size problems, but might add another step for contributors.

**Comment by gabek** [comment]
It's an option, but like you said, adding more steps for contributors would be a major downside. We have plenty of places we can have files publicly available for download. We already do that for a couple things, so I don't think we have to limit ourselves to using the repo and LFS. As long as we can automate the download process I think it'll be a better approach in the end.

**Comment by gabek** [comment]
This was improved by @MFTabriz a while ago. Closed.
