### ISSUE TITLE
Footer wraps on narrow desktop layouts (like iPad)

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2504]
On narrow desktop layouts the footer wraps and looks odd. Maybe it needs to decrease the font size more as the viewport narrows to fit it all.

![image](https://user-images.githubusercontent.com/414923/209498126-ac00e1ec-de5f-432e-a374-5407ec3b0063.png)

**Comment by Rishav1707** [comment]
How's this on a narrow desktop layout ( like iPad )

![owncast](https://user-images.githubusercontent.com/97666287/209530361-6153d119-d365-4b1d-ac65-d5fbf21a70f7.png)

**Comment by Rishav1707** [comment]
> On narrow desktop layouts the footer wraps and looks odd. Maybe it needs to decrease the font size more as the viewport narrows to fit it all.
> 
> ![image](https://user-images.githubusercontent.com/414923/209498126-ac00e1ec-de5f-432e-a374-5407ec3b0063.png)


Shall I work on this issue? @gabek

**Comment by gabek** [comment]
Yeah! That looks great. Thanks for jumping on this!
