### ISSUE TITLE
Admin appearance page does not immediately show the correct colors

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2505]
### Share your bug report, feature request, or comment.

/admin/config/appearance/

It sets the default colors, but not the customized colors. Eventually, if you sit and wait, the correct colors show up in the color pickers.

Defaults

![image](https://user-images.githubusercontent.com/414923/209498918-d8918584-8d36-4fe3-9708-cc661f00e96c.png)

Should be showing the customized override colors

![image](https://user-images.githubusercontent.com/414923/209498951-81c77c6b-7119-47b7-b85c-c0d76824bcee.png)

**Comment by ShashwatAgrawal20** [comment]
@gabek would like to work on this, do you have any recommendations from where can I get started

**Comment by gabek** [comment]
I'm actually looking at this as we speak, sorry for the confusion!

**Comment by andrew-secret** [comment]
I'm curious about the fix for that one. Fingers crossed it's just a small thing!

**Comment by gabek** [comment]
Alright, hopefully this is now resolved!  Just a bunch of reworking some React hooks.
