### ISSUE TITLE
Followers list should be centered in mobile layouts

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2515]
### Share your bug report, feature request, or comment.

It looks funny being left aligned.

![image](https://user-images.githubusercontent.com/414923/209612583-b2840713-2e35-4528-96a8-27349334dc3d.png)

**Comment by ShashwatAgrawal20** [comment]
Hey, I would like to work on this issue

**Comment by gabek** [comment]
Awesome, thank you!

**Comment by ShashwatAgrawal20** [comment]
@gabek do we have a testing  Fediverse account that we can follow from the development environment, as I am unable to follow anyone from it

**Comment by gabek** [comment]
You'd need to use your own Fediverse account for testing. Another, probably simpler, option, is to just view the component in Storybook. `npm run storybook` https://owncast.online/components/?path=%2Fstory%2Fowncast-components-followers-single-follower--example

<blockquote><div><strong><a href="https://owncast.online/components/?path=%2Fstory%2Fowncast-components-followers-single-follower--example">Webpack App</a></strong></div></blockquote>

**Comment by gabek** [comment]
Testing on my phone and it seems to be not centered as it was on the desktop with a narrow viewport. Guess I should have tested with an actual phone before. ![image](https://user-images.githubusercontent.com/414923/210037950-4bf286a1-5cf5-40f4-be0a-228796ee0526.png)

**Comment by ShashwatAgrawal20** [comment]
It might be possible haven't tested it on mobile, but I will fix it

**Comment by gabek** [comment]
Hey there @ShashwatAgrawal20! Are you still looking at this?

**Comment by ShashwatAgrawal20** [comment]
Yea, just not getting that much time as I have my semester exam going on.

**Comment by gabek** [comment]
Great! Let me know if you don't think you'll have time to work on it.

**Comment by gabek** [comment]
I was working on some other followers stuff so I went ahead and took care of this while I was in there.
