### ISSUE TITLE
Admin logo upload UI sending empty payloads

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2524]
### Share your bug report, feature request, or comment.

I found when testing #2522 that the web frontend is sometimes sending empty payloads to the backend when trying to upload an image. It feels random. Sometimes it works, sometimes it doesn't. It may be due to types of file, or name, or permissions or something but it doesn't seem like it's related to the backend.

![image](https://user-images.githubusercontent.com/414923/209883936-dd80637a-ca01-49fa-a7b2-87340f22723d.png)

**Comment by andrew-secret** [comment]
I can take a look at this 😇

**Comment by gabek** [comment]
Nice!
