### ISSUE TITLE
Add minimum stream key + password complexity rules

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2528]
### Share your bug report, feature request, or comment.

The server functions that adds new stream keys and modify the admin panel password are in file controllers/admin/config.go: SetAdminPassword at line 201 and SetStreamKeys at line 772.

SetAdminPassword

```go
// SetAdminPassword will handle the web config request to set the server admin password.
func SetAdminPassword(w http.ResponseWriter, r *http.Request) {
	if !requirePOST(w, r) {
		return
	}

	configValue, success := getValueFromRequest(w, r)
	if !success {
		return
	}

	if err := data.SetAdminPassword(configValue.Value.(string)); err != nil {
		controllers.WriteSimpleResponse(w, false, err.Error())
		return
	}

	controllers.WriteSimpleResponse(w, true, "changed")
}
```

SetStreamKeys

```go
// SetStreamKeys will set the valid stream keys.
func SetStreamKeys(w http.ResponseWriter, r *http.Request) {
	if !requirePOST(w, r) {
		return
	}

	type streamKeysRequest struct {
		Value []models.StreamKey `json:"value"`
	}

	decoder := json.NewDecoder(r.Body)
	var streamKeys streamKeysRequest
	if err := decoder.Decode(&streamKeys); err != nil {
		controllers.WriteSimpleResponse(w, false, "unable to update stream keys with provided values")
		return
	}

	if err := data.SetStreamKeys(streamKeys.Value); err != nil {
		controllers.WriteSimpleResponse(w, false, err.Error())
		return
	}

	controllers.WriteSimpleResponse(w, true, "changed")
}
```

These two functions do not enforce any password complexity and will update the current value with any value submitted by the admin.
If no requirements are set it could be likely that weak password are used by the administrator, and this could create an opportunity for a guessing or brute force attack against the admin panel basic HTTP authentication.

## Impact

An attacker could guess the admin panel password or a stream key using a list of common password, obtaining access to the application controls.

This scenario requires that the legitimate admin of the application set a weak password or did not change the default one.

## Recommendation

Enforce the following requirements on the credentials, when they can be applied:

1. Enforcement of a minimum and maximum length
1. Complex passwords requiring mixed character sets (alpha, numeric, special, mixed case)

Add a warning in the admin UI when the admin panel password and stream key are the default one (abc123), suggesting to change them explaining the security risk (e.g. anyone could log in the admin panel and takeover the stream).

**Comment by dorj222** [comment]
Hi there! I'd like to work on this issue. Would you please assign it to me?

**Comment by gabek** [comment]
Sure! How were you were thinking about tackling this? Just a client-side notice if it's not complex enough, or were you going to enforce them at the API level as well?

**Comment by dorj222** [comment]
Thanks for assigning this issue to me! I am thinking about a client-side notice and password validations. Do you recommend the API level enforcement as well?

**Comment by gabek** [comment]
Originally I was, but I understand that's duplicated logic and more code. But since the APIs exist it is saying that using APIs to set these values are a legitimate option, so if the rules aren't checked there as well it would feel like an oversight.

The compromise would be to only do the validation server-side and return an error to the client if it doesn't adhere to the complexity rules but that's not as good of a user experience.

**Comment by dorj222** [comment]
I see. In that case, I think it would make sense to implement both client-side and back-end/API level validations, even though it would yield duplicated logic and more code. What do you think?

**Comment by gabek** [comment]
Yeah, I do think that would be the most correct way to go about it.

**Comment by dorj222** [comment]
Sure, I will implement that way then.

**Comment by dorj222** [comment]
Hello, @gabek! I created a [draft PR](https://github.com/owncast/owncast/pull/2619) for this issue. The client-side input validations have been implemented in this draft PR. I am getting one specific post request error whenever I try to change the admin password. What could cause this error? It seems like I am doing something wrong when I try to change the admin password 🤔.  

The error that I am getting:

<img width="591" alt="Screen Shot 2023-01-24 at 3 14 32 PM" src="https://user-images.githubusercontent.com/26856199/214317991-c296de6d-0503-4561-bed0-50a9d9d7b778.png">

**Comment by gabek** [comment]
I must have updated the tests but not that request. The admin password endpoint should be `/api/admin/config/adminpass`. That would explain it!

**Comment by gabek** [comment]
Reopened due to #2619 needing to be reverted.

**Comment by gabek** [comment]
I went ahead and fixed the circular dependency import and the build is now successful. It's merged back in.
