### ISSUE TITLE
make web builds reproducible

### ISSUE THREAD

**Issue by MFTabriz** [owncast/owncast#2541]
Bundle web workflow `.github/workflows/bundle-web.yml` is building the web app (using ` build/web/bundleWeb.sh`) and committing it to the git. Even if nothing has changed in the output, due to the change of “buildId” the resulting files are treated as different output and are committed to git repository.

Building the web app multiple times or building the same input files from different git commits must produce identical result.

**Comment by xarantolus** [comment]
One can configure a function that generates a build id that either does not change or only changes when relevant files are modified, as detailed [here](https://nextjs.org/docs/api-reference/next.config.js/configuring-the-build-id). I think just using a constant ID would make sense, but it *might* lead to users loading outdated resources from an older release if aggressive caching headers were used. Git commit hashes also change every time, which would defeat the point, so using the current version number seems to make the most sense.
I just tested this and it seems to work as expected, so I could submit a PR if you want :)

**Comment by MFTabriz** [comment]
@xarantolus If we’re trying to prevent loading of outdated resources, using the owncast version will not solve the issue for people who are using/testing the development version. 
We can use a fixed buildId, calculate the hash of the [combined] resulted files, and finally replace that fixed buildId in all files with this hash.

**Comment by gabek** [comment]
What are the goals here? I know what's wanted, but for what purpose? It sounds like making any of these changes will create more negatives than positives if the only thing we're looking to address is to limit the number of files that are changed on a build.

The caching issue is a real one, and the development issue is a real one. We don't have either of those problems right now.
