### ISSUE TITLE
Add content to the landing page for browsers without JS support

### ISSUE THREAD

**Issue by MFTabriz** [owncast/owncast#2543]
Owncast page in `webv2` branch with browsers without JS support currently looks like [this](https://user-images.githubusercontent.com/39205857/210184282-18e57f63-17a4-41a1-bafd-ee7215495744.png). Its content should get updated based on the [main branch](https://user-images.githubusercontent.com/39205857/210184415-6728935b-a3cc-4a6c-a29f-a710ffff2a7f.png) ([source](https://github.com/owncast/owncast/blob/a5e5037f5c09e9deedad6558ea9a7ea8a0e486de/webroot/index.html#L220-L259)).

**Comment by LBBO** [comment]
I'd be happy to work on this!
