### ISSUE TITLE
Restrict twitter notification save if the required fields are empty.

### ISSUE THREAD

**Issue by hsingh124** [owncast/owncast#2546]
### Share your bug report, feature request, or comment.

When twitter notification is enabled, we can save even if the required fields are empty. This further causes an issue where the save button disappears when the toggle is changed. 

Below is a recording of the replication:

https://user-images.githubusercontent.com/44574494/210255266-d0b7b6f1-0246-4bfc-b987-252cd7fdf9da.mov

**Comment by hsingh124** [comment]
Can I pick this one? I have a potential fix ready.

**Comment by gabek** [comment]
Absolutely, thanks!

**Comment by hsingh124** [comment]
I've added a fix here https://github.com/owncast/owncast/pull/2548 with a demo. Can I get some reviews.
