### ISSUE TITLE
Can we make the live stream playable when the browser is idle (minimized), for mobile ?

### ISSUE THREAD

**Issue by adim-att** [owncast/owncast#2547]

**Comment by gabek** [comment]
Could you explain further what you're thinking of?

**Comment by adim-att** [comment]
When you switch away the Chrome or Firefox browser while playing a podcast or soundcloud for example, you can still have the audio playing. You get player controls in the notification bar. That's because the browser is still open.

With owncast, that wasn't possible, once I open another window for another app the audio stops.

**Comment by gabek** [comment]
What operating system are you referring to? And do you know what needs to be added in order to add this functionality you're referring to? I feel like we've gone down this road with iOS+Safari and there wasn't a way to keep the browser playing a video in the background after switching away from it. But I could be wrong. Do you have any examples?

**Comment by aaronpk** [comment]
In Chrome on MacOS Ventura, when I switch to another tab or another app, this icon appears in the Owncast tab and the video keeps playing

<img width="138" alt="image" src="https://user-images.githubusercontent.com/113001/210646303-3f6447a3-8b00-4617-bea8-065348e4ce14.png">

I also see this in the notification bar showing me that it's playing

<img width="319" alt="image" src="https://user-images.githubusercontent.com/113001/210646464-d6158583-9d3f-44d3-816f-1bc0e24f41b6.png">

On Chrome iOS, if I first click the "full screen" icon in Owncast, then switch to another app, Owncast appears in the picture-in-picture player on top of whatever other apps I am running.

![image](https://user-images.githubusercontent.com/113001/210646887-284d4975-6f11-4d5f-86c8-dfb5f8bc27ab.png)

**Comment by gabek** [comment]
Ah ha, I've never tried backgrounding a video outside of Safari on iOS. Good to know Chrome supports it via PiP.

**Comment by adim-att** [comment]
> What operating system are you referring to? And do you know what needs to be added in order to add this functionality you're referring to? I feel like we've gone down this road with iOS+Safari and there wasn't a way to keep the browser playing a video in the background after switching away from it. But I could be wrong. Do you have any examples?

I was on MIUI which is Xiaomi Redmi. Aww.. I think I know what's going on.. I was streaming from my site page that has the iframe embedded, so maybe that's why. But still, I think it could be possible. I don't know I just wanted to put that out there. 

You can close this if you want.  Of course in Desktop, it's all good, I can switch and still hear the audio.

**Comment by gabek** [comment]
Feel free to comment again if you feel there's something specific that we can make better!
