### ISSUE TITLE
Using the updated Docker image creates permission issues and won't start

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2561]
### Share your bug report, feature request, or comment.

If you're already using our Docker image and you move to he image post- #2496 Owncast will no longer load due to permissions issues recreating the `data/tmp` directory. Temporarily disabled running under the `owncast` user in e1c6ea9e21eeeb58356c22e6df6fb04a7fb4f64d.

```
$ kubectl logs webv2-76df9fd74f-7lqqd
time="2023-01-08T22:53:22Z" level=fatal msg="Unable to remove temp dir! Check permissions. ./data/tmp openfdat ./data/tmp: permission denied"
```

**Comment by MFTabriz** [comment]
The only solution I can think of right now is to have root as user in the dockerfile but modify the entrypoint to give the ownership of `data/` to the owncast user and then run the app as that user (owncast).

**Comment by gabek** [comment]
Since the change has been reverted this is running the same way it always has been and is not currently broken, I'm removing it as a required item in v0.1.0. It'll be addressed whenever it's addressed.
