### ISSUE TITLE
Super fast tutorial video

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#257]
Thought it would be cool post-0.0.4 to have a tutorial video that's like 1 minute long where it shows running Owncast from scratch.

While one minute is aggressive, I bet we could do the following with a little rehearsal and preparation.   It would totally show off how fast and easy it can be to start using Owncast with your existing software.

1. Run install script. (15 seconds)
1. Running the service. (5 seconds)
1. Pointing OBS at the server. (10 seconds)
1. Visit the admin page and to show the home page w/ stream overview. (10 seconds)
1. Starting a live stream and viewing playback. (20 seconds)

**Comment by gabek** [comment]
I think we should actually do this for the release of 0.0.3 since we'll have the new fancy install script and changing the key isn't that interesting anyway.

@gingervitis Would you be interested in being the face and voice of a ~1min video when we release 0.0.3? :)

**Comment by gingervitis** [comment]
Oh I see, we're pulling the Diversity card here aren't we? :trollface: 

Yeah ok, I'll see what I can do. 😇

**Comment by gabek** [comment]
Update: @gingervitis and I plan on working together on this next week.  We haven't worked out the specifics, so if anybody has anything that they think we should hit on in a video like this, let us know.

**Comment by gabek** [comment]
Done!
