### ISSUE TITLE
Owncast + Firefox on Linux throws error with lite-youtube

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#258]
With Firefox on Linux the web UI to Owncast does not load at all.  It seems to be a web components compatibility thing.

```ReferenceError: customElements is not defined```

If we can just disable youtube embeds on platforms that don't support web components that's probably fine.

**Comment by mattdsteele** [comment]
What version of Firefox is that by chance? Web components have been supported on FF since v63: https://www.caniuse.com/custom-elementsv1

But yeah it probably makes sense to feature detect it with something like:

```js
if (window.customElements) {
  // load the library
}
```

**Comment by gabek** [comment]
I guess I was on an old version.  I'm on Firefox 81.0.2 now and all is fine.  No problem, nothing to see here!
