### ISSUE TITLE
[SOLVED] "Error Fetching User" when I attempt to follow my Owncast user

### ISSUE THREAD

**Issue by masstransithonchkrow** [owncast/owncast#2581]
### Share your bug report, feature request, or comment.

I run an Owncast instance at https://glass.krowverse.net, and I am trying to follow that user from https://federation.ninetiesmysteri.es, an instance running Pleroma 2.5.0.

![image](https://user-images.githubusercontent.com/10548400/212490868-3300fdcb-f802-4d44-89df-6a6a70c6e1dc.png)

But I get the following error when I try to Follow:
![image](https://user-images.githubusercontent.com/10548400/212490927-c0e5d9eb-9854-4145-9fff-093fccb45124.png)

I wanted to note that the content type on my Pleroma instance is application/json but on the Owncast instance it is application/activity+json. 

Headers from the Owncast instance via /api/v1/instance:
![image](https://user-images.githubusercontent.com/10548400/212491003-593c1427-2d28-4e99-a5ce-7277f1d2ec66.png)

Headers from the connecting instance via /api/v1/instance:
![image](https://user-images.githubusercontent.com/10548400/212491068-cf8a48b2-6f76-4dc5-b24a-a4904804e4ea.png)

Please let me know if you need more details.

**Comment by gabek** [comment]
I tried following from a Mastodon server and I received a SSL error for your Owncast server. I can't speak to if there's actually an SSL error, but if your Pleroma server and the random Mastodon server both won't talk to your Owncast server it might be the first thing to look at.

![image](https://user-images.githubusercontent.com/414923/212491460-789e671a-27dd-4d6e-9567-fda38635f1bc.png)

**Comment by masstransithonchkrow** [comment]
It's an Let's Encrypt certificate, but I didn't specify TLS 1.3 in the conf file. On Chrome, I get an error 500 rather than the banner I pictured.

**Comment by gabek** [comment]
Did you ever figure out the SSL error?

**Comment by masstransithonchkrow** [comment]
Not yet. Thanks for following up.

**Comment by masstransithonchkrow** [comment]
I discovered that disabling TLSv1.2 and running multiple services over port 80 on the same server affected my ability to federate. For context:

glass.krowverse.net is running alongside two concurrent Pleroma instances. When you run mutiple instances on the SAME IP, you CANNOT use port 80 on any of them, nor can you use 301 redirects, because they will bump into each other, which was malforming the follow requests, causing them to redirect to another instance on the same IP.

I always try to add context when an issue is solved because that isn't done enough here.

Krowverse Glass Federation now federates.

**Comment by gabek** [comment]
That's great news you were able to track it down, thanks for the update!
