### ISSUE TITLE
Configure Ant Design components to use date-fns instead of moment

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2582]
### Share your bug report, feature request, or comment.

See https://4x.ant.design/docs/react/replace-moment

**Comment by gabek** [comment]
I can't find any instances where we use the three components that would be impacted by this:

1. DatePicker
2. Calendar
3. TimePicker

**Comment by LBBO** [comment]
Me neither. Does this mean there's nothing to do here?

**Comment by gabek** [comment]
See https://github.com/owncast/owncast/issues/2167 for the background on this. I'm not sure if there's something to be done or not yet.

**Comment by gabek** [comment]
Closing. While the initial problem of moment being imported is still a problem, it's not going to be fixed by altering the components because we're not actually using them.
