### ISSUE TITLE
Remove Twitter notification support

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2597]
### Share your bug report, feature request, or comment.

They're pulling people's API access, so it won't work anymore.

**Comment by LBBO** [comment]
Does this just involve deleting the corresponding code or do you want it to be replaced with something? And should documentation for this be added somewhere? Perhaps [this part of the docs](https://owncast.online/docs/notifications/#twitter) could be updated to explain that support for Twitter was dropped.

If this ticket can be worked on without a lot of experience in Go, I'd love to give it a shot.

**Comment by gabek** [comment]
Yup, just a bunch of deleting from the Go backend and the Admin frontend. You should be able to start looking in our `notifications` package and remove references to Twitter, the API path in the router, and then in the Admin UI it would be need to be removed from the Notifications page. Hopefully it's clear what's going on, but feel free let me know if you have any questions.
