### ISSUE TITLE
is there any plan to support HEVC?

### ISSUE THREAD

**Issue by sneak** [owncast/owncast#2602]
First off, this is a dupe of #2107 .

Is there any plan to support x265/HEVC?  A ton of modern devices support hardware decoding, a lot of modern devices support hardware *encoding*, and it is way better and more efficient per-mbps than x264.

I was quite surprised to see a bunch of ffmpeg errors in the logs when I attempted a 1080p24 passthrough hardware-encoded HEVC stream from OBS.  I sort of assumed HEVC would be supported.

**Comment by gabek** [comment]
I'm not opposed to it some day, but being universally playable is more important than codec efficiency in the short term.

The documentation doesn't encourage use of passthrough, and it doesn't say we support HEVC, so while I'm sorry you were surprised to see those errors, it's just not something that is supported.

**Comment by sneak** [comment]
I figured if it were passing through, and the client supported HEVC, it would just work fine.  I may look into the code to see about submitting a PR.
