### ISSUE TITLE
Logo upload generates JSON error and fails

### ISSUE THREAD

**Issue by stevepi68** [owncast/owncast#2603]
### Share your bug report, feature request, or comment.

On https://DOMAIN.ORG/admin/config-public-details/
CONFIG -> GENERAL -> Configure Instance Details -> LOGO
Trying to upload new logo generates JSON error
Screen shot attached
![OwnCastIssue](https://user-images.githubusercontent.com/5993946/213290110-a785c66b-c458-4f31-9127-f23290bd29c4.png)

**Comment by gabek** [comment]
Hi there.

If you open your browser dev tools, under the network tab, when you upload the logo can you provide what the actual response is?

Some other things to make sure of:

- Make sure it's not an SVG file
- Make sure it's not too large
- Try with a different file to see if some files are working and some aren't (maybe naming?)

**Comment by gabek** [comment]
Also check your server logs to see if any errors were reported (permissions, etc).

**Comment by stevepi68** [comment]
A smaller file worked for the upload, however there is no SAVE button- how do I get to update the change?

**Comment by gabek** [comment]
You shouldn't need to save, it'll save it when you upload. You might see the old logo cached in your browser for a brief time, but if you don't want to wait you can hard refresh your browser it'll force it to show the updated one.

**Comment by stevepi68** [comment]
Ok - that worked.
Issue closed.
Thanks

**Comment by gabek** [comment]
Big fan of your venue by the way, keep up the good work.

**Comment by stevepi68** [comment]
Could I ask what your role is at OwnCast?
Our Executive Director might want to connect to ask a few things about your system - or who wol dbe a good person to talk to?

Thanks,
-Steve
Venue Manager, Gray Area

**Comment by gabek** [comment]
I'd be the person. I'm the project maintainer and primary developer of Owncast. Feel free to email me at gabek@real-ity.com.

**Comment by stevepi68** [comment]
I sent you an email from my GA account with Barry, our ED on it.
He'll take it form there.

Thanks for all your help,
-Steve
