### ISSUE TITLE
Replace /img/logo256.png with a higher resolution image

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#261]
The "large" image isn't large enough.

**Comment by jeyemwey** [comment]
We should really use an svg vector image for the logo.

**Comment by gabek** [comment]
Yeah, you're right.  The only reason we don't have it is because the cheesy logo generator I found online that I used to create the image makes me pay to get an SVG version :P.  But I think I'll just pay what they ask and get the vector.

**Comment by jeyemwey** [comment]
Or `$someone` creates a real logo 🙊

**Comment by gabek** [comment]
Maybe in the future we can go through a real "branding".  But that takes too much thought for now.  So generated logo it is!  I went ahead and copied all the copies of it into https://github.com/owncast/owncast-infra/tree/main/design in case anybody needs anything.
