### ISSUE TITLE
Stream quality in admin interface not reflected in ffmpeg settings

### ISSUE THREAD

**Issue by rmens** [owncast/owncast#2610]
### Bugreport

In the admin interface I set all my stream outputs to maximal cpu usage and use libx264:

<img width="568" alt="Schermafbeelding 2023-01-22 om 20 04 24" src="https://user-images.githubusercontent.com/6742496/213934825-fde452c2-04ea-47ee-ae2f-ae1cb924a3a5.png">

According to https://github.com/owncast/owncast/blob/develop/core/transcoder/codecs.go#L79 it should set the ffmpeg preset to `fast` 

But when looking at the running ffmpeg command. It runs with `superfast` which equals the quality setting low.

<img width="438" alt="Schermafbeelding 2023-01-22 om 20 08 03" src="https://user-images.githubusercontent.com/6742496/213934933-23439221-0346-46dc-a625-0ccb34df562f.png">

I'm running owncast 0.0.13 on Ubuntu 22.04 x86_64.

**Comment by gabek** [comment]
Thanks for reporting!
