### ISSUE TITLE
Admin "Upgrade to vx.x.x" link is incorrect

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2612]
### Share your bug report, feature request, or comment.

It currently links to `/upgrade` and not `/admin/upgrade`.

**Comment by Kasambx** [comment]
Hey can I get more context to the issue above?

**Comment by gabek** [comment]
Sure! There's a link in the admin sidebar that shows up when an upgrade is available and it points to the wrong location.

**Comment by Kasambx** [comment]
The solution is to replace  with the correct link i suppose or how do I carry on from here?

**Comment by gabek** [comment]
Yup, simply change the link from pointing to `/upgrade` to `/admin/upgrade`. No code changes, just a few characters added to the link.

**Comment by Kasambx** [comment]
Can you please provide me with to the file direction to the link?

**Comment by gabek** [comment]
No offense but if I'm going to go in and look for it I'll just make the quick change myself. It should be trivial to search for that link.

**Comment by Kasambx** [comment]
Ok let me search for it then.
