### ISSUE TITLE
Support a single line curl install

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#262]
I know some people don't like these because of possible security implications, but I've certainly used these to install things I trust.

Running

`curl -s https://owncast.online/install.sh | bash`

Could:
1. Verify `ffmpeg` is in the path.
1. Create an install directory.
1. Download the zip of the most recent release from Github.
1. Unzip it.
1. Print out the default port and key with a message saying how to change it.
1. Tell the user they're ready to go and can run the binary.

We could make this single line prominent on our documentation page and under the quick start instructions. 

What do you think?  @graywolf336 @geekgonecrazy @mattdsteele @jeyemwey

**Comment by mattdsteele** [comment]
I think this would be cool!

Along those lines, do you think the end goal should be to get Owncast in package managers (homebrew, apt, and the like) for ease of install?

**Comment by gabek** [comment]
Yeah, for sure!  We had a little bit of discussion around that here: https://github.com/owncast/owncast/issues/143

To go that route we'd have to think what owncast as a global, system install would look like.  If you install via a package manager it would go into `/usr/local/bin` (or wherever), but where does the HTML, database, etc live?  But I think these are all solved problems that other similar services have figured out.

The shell script might be a good first step into jumping into this.

**Comment by gabek** [comment]
Did some experimentation and threw this in the `owncast-infra` repo to iterate on.

![install](https://user-images.githubusercontent.com/414923/96329422-76424b80-1001-11eb-9002-f14d762c63aa.gif)

**Comment by gabek** [comment]
If ffmpeg isn't available on their system we should prompt to download a pre-built binary for them.

**Comment by gabek** [comment]
I have the first pass of it in and works well.  We can continue to iterate on it as needed.  I figure we can hold off updating documentation until 0.0.3.  Though if somebody thinks we should post this now we can do that.

`curl -s https://owncast.online/install.sh |bash`

![image](https://user-images.githubusercontent.com/414923/96828669-eb8c9280-13ec-11eb-9ccf-1051f93a9cf3.png)
