### ISSUE TITLE
v0.0.3 release notes

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#263]
Wanted to file something to keep notes about what we need to call out in the 0.0.3 release.

- Delete `chat.db` when upgrading.
- If you're using the default logos change to `/img/logo.svg` in your config file, as we have removed the non-svg logos.

**Comment by gabek** [comment]
At build time of a release we should create a static OpenAPI spec document that we can refer people to for the APIs of a specific version.  Right now our `/api` documentation points to the state of `master`, and that's not really helpful for people using a release build.

**Comment by gabek** [comment]
We should mention that `offlineContent` is no longer used in the config file.

**Comment by gabek** [comment]
`chatDatabase` command line flag is moved to `database`.  `chatDatabaseFile` in config changed to `databaseFile`.  Default location is now in `data`.

**Comment by jmhobbs** [comment]
> At build time of a release we should create a static OpenAPI spec document that we can refer people to for the APIs of a specific version. Right now our /api documentation points to the state of master, and that's not really helpful for people using a release build.

What do you think about versioning that, like k8s does? `https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/`

Could do `/api/<version>`, and then have some links, like `/api/latest` which redirects to whatever version is most recent.  Maybe an `/api/development` that tracks the master branch too?

**Comment by gabek** [comment]
That's a great idea!  Simple enough to do and would be really useful.

**Comment by gabek** [comment]
Current state of release notes:

0.0.3 Release notes
========================

### Breaking changes

- `chat.db` has been renamed to `owncast.db` and moved to the `data` directory.  You should delete your old `chat.db` file.
- The default logos have been moved to `/img/logo.svg`, so if you have been using the default logo images in your config file, point to this new file instead otherwise your logo will be empty on the web page.
- `content.md` has moved to to `/data`.
- `stats.json` has moved to `/data`.
### Owncast Admin

0.0.3 has a new web admin page so you can view the configuration, logs, stats, hardware, and status of your Owncast server.  Visit `/admin` and login with `admin` as the username and your stream key as the password.

We will continue to add functionality to this over time, so please [let us know how it works for you and if you have any feedback](https://github.com/owncast/owncast/discussions).

### Web UI

- Avatars have been removed from chat.

### Installer

There's now a installer script you can use to quickly install Owncast on your machine.  Simply run
```
curl -s https://owncast.online/install.sh | bash
```

**Comment by gabek** [comment]
Updated to refer to the logo changes in #373.

**Comment by gabek** [comment]
I'm probably making the home page look janky by adding too much stuff to it.  If anybody wants to tweak the 0.0.3 branch on the web site repo please do.  Mostly looking at @jeyemwey and @gingervitis :)

**Comment by jeyemwey** [comment]
We should maybe add a new image of the Owncast screenshot since the existing one is quite old (e.g. chat images). Also, I'm not sure what the admin screenshot should tell the visitor. Maybe, we can document the admin page on a separate documentation page?

**Comment by gabek** [comment]
Yeah absolutely, we should swap screenshot out.

I thought about adding a page for the admin, but all we can say about it is "it exists".  So a screenshot is just a way to show that feature without writing "and we have an admin" somewhere.  I can't think of any detail that's required.

**Comment by jeyemwey** [comment]
The asciinema player has issues with overflowing and only shows some part of the video:

![image](https://user-images.githubusercontent.com/2796271/99787279-d5730e80-2b1f-11eb-8909-4c1388842e27.png)

**Comment by jeyemwey** [comment]
I have moved the admin screenshot off the index page. With my commit, it is included in the quickstart guide and the screenshot was added to the 0.0.3 release blog post.

**Comment by gabek** [comment]
Oh weird, thanks for looking at that.  I'll look into what the deal with that asciinema problem is.  I also plan on re-doing it since testing it out we've tweaked the text you see when you launch the app.

**Comment by gabek** [comment]
Updated the asciicast in the 0.0.3 branch.  Hopefully it's better.
