### ISSUE TITLE
Auto-generate a complex, stream key when adding

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2631]
### Share your bug report, feature request, or comment.

As a continuation of #2619, when a user creates a new stream key we should auto-populate it with a key that matches our complexity rules. The user can obviously remove it and type their own, but since the key is just going to be copied/pasted most of the time we might as well just make it easy for them and generate one automatically.

**Comment by dorj222** [comment]
Hi there! I'd like to work on this issue :)

**Comment by gabek** [comment]
Awesome, thank you!

**Comment by gabek** [comment]
I was already working on #2683 so I went ahead and just moved the old password generator to be the stream key generator when you add a new key, so that closes this.

**Comment by dorj222** [comment]
Hi @gabek! Thanks for letting me know this. I actually realized that the way the current random stream key generator doesn't always generate a random string that follows the password complexity rules that are being implemented. I created a small random stream key generator that always generates a string that follows the password complexity rules. Please let me know if you think I need to create a PR for this.

![Screen Shot 2023-02-07 at 10 42 20 PM](https://user-images.githubusercontent.com/26856199/217372949-71b23595-f933-4577-b37d-1e8dc5dde42c.png)

**Comment by gabek** [comment]
Oh sure! If you just want to overwrite the existing one with this one that fits the rules that would work. Thanks for bringing this up!
