### ISSUE TITLE
Cleanup of old stream segments in S3 bucket

### ISSUE THREAD

**Issue by flo333** [owncast/owncast#2646]
### Share your bug report, feature request, or comment.

Most cloud providers' expiration policies only allow for a minimum of one day before files are deleted, leaving the segments of each stream available in a public bucket for 24 hours. While this isn't a huge problem - or might even be useful to some - I'd love the option to have the bucket purged automatically at the end of the stream.

**Comment by gabek** [comment]
There was a PR for this a while back but it never went anywhere. Maybe in the future it can get picked back up. https://github.com/owncast/owncast/pull/1500

**Comment by gabek** [comment]
Just for some feature clarification, it probably shouldn't clean up when the stream is finished, but instead clean up just like with local file distribution, on a timer. Otherwise cleanup for 24/7 streams using object storage would never get fired.
