### ISSUE TITLE
Status bar says 1 minutes (plural) instead of minute

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2649]
### Share your bug report, feature request, or comment.

Minute should be singular when it's only 1 minute.

![image](https://user-images.githubusercontent.com/414923/215622439-2ac17b8d-07e4-4cdb-822a-5f8849a5cfdd.png)

**Comment by elonyavist** [comment]
Hi @gabek, I'd like to contribute trying to fix this issue.

Looking at the codebase, the function involved is `makeDurationString`. If I'm not wrong, I think this fix should be done also for `days`, `hours` and `seconds`.

**Comment by gabek** [comment]
Awesome! And yeah, you're absolutely right, it should be fixed for those other units as well. Good catch!
