### ISSUE TITLE
Chat & Users admin sidebar item is always highlighted

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2651]
### Share your bug report, feature request, or comment.

It should only be highlighted when you actually are on that menu item.

![image](https://user-images.githubusercontent.com/414923/215631280-6c517512-72d2-4d53-81ac-b25592376f71.png)

**Comment by Princeyadav05** [comment]
Hi @gabek ,

I wanted to take a dig at the issue but I'm currently facing some problems while running the project locally.

1. I ran FE by executing `npm install` followed by `npm run dev`. However, this just keeps on loading in the browser with nothing being rendered.
2. Figured that I also need to run BE using `go run main.go` command. This started installing the dependies, however it got stuck on ffmpeg and I got the following error.
```
Unable to determine path to ffmpeg. Please specify it in the admin or place a copy in the Owncast directory. 
exit status 1
```

Can you help running thee project please?

**Comment by gabek** [comment]
> I ran FE by executing npm install followed by npm run dev. However, this just keeps on loading in the browser with nothing being rendered.

How long did you wait for the web app to build the first time? After you run `npm run dev` and load the page let it continue loading if you see it loading.

And yup, you will need a copy of `ffmpeg` installed on your machine. If you use macOS I recommend using [Homebrew](https://formulae.brew.sh/formula/ffmpeg) and if you're on Linux then install it using your package manager. Otherwise you can just download a [binary](https://ffmpeg.org/download.html) of ffmpeg and put it in the same directory as Owncast.

**Comment by gabek** [comment]
Hi @Princeyadav05, were you able to get things running?

**Comment by gabek** [comment]
Hey @Princeyadav05, just checking in to see if you were able to get your dev environment working.
