### ISSUE TITLE
Make Follower contents fit

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2662]
### Share your bug report, feature request, or comment.

It should be two single lines, no wrapping, each truncating with ellipsis.
![image](https://user-images.githubusercontent.com/414923/216147676-d4b21a3c-674c-410c-b9ca-5f453e7878c7.png)

Story: https://owncast.online/components/?path=%2Fstory%2Fowncast-components-followers-followers-collection--example

**Comment by prachurjya15** [comment]
Hi, So if I understand correctly, ThatOneCalculator :cal will turn into kind of this : ThatOneCalculator... and contained in the box after the fix, if so I can  give it a shot, can you pls assign it to me.

**Comment by gabek** [comment]
I'm not exactly sure what character it would truncate at, but I think you have it right, when it hits the overflow it will truncate the ellipsis on that single line. Thank you!
