### ISSUE TITLE
Chat message highlighting is no longer working

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2669]
### Share your bug report, feature request, or comment.

"message" should be highlighted in this example:
![image](https://user-images.githubusercontent.com/414923/216470833-7952ae77-85eb-40f1-8a08-f9a49b204e6e.png)

Story: https://owncast.online/components/?path=%2Fstory%2Fowncast-chat-messages-standard-user--with-string-highlighted

**Comment by elonyavist** [comment]
Hi @gabek, I'd like to work on it.
"Highlighted" means in bold format, or should the string have the same color as the title?

**Comment by elonyavist** [comment]
Oh sorry, I didn't see the assignee :)

**Comment by gabek** [comment]
No problem, thanks for offering though! I found the problem and am doing some reworking of the chat message.
