### ISSUE TITLE
Local file distribution confusion

### ISSUE THREAD

**Issue by bandicootdancing** [owncast/owncast#268]
The [readme](https://github.com/owncast/owncast#local-file-distribution) mentions using local storage out of the box for video but I don't see any other mention of how to configure and serve files from local storage. Can videos be added in the config or is it expected to use ffmpeg to owncast?

**Comment by jeyemwey** [comment]
We meant that the generated hls files are stored on your local hard drive and served from there.

You can run [a little test script](https://github.com/owncast/owncast/blob/master/test/ocTestStream.sh) to send files to Owncast:

`$ ./ocTestStream.sh ~/Videos/*.mp4 rtmp://localhost/live/abc123`

**Comment by gabek** [comment]
Yeah, it's live streaming only.  If you want to stream your prerecorded content, like @jeyemwey said, it will totally work, and you can use any piece of software that will output rtmp.

**Comment by bandicootdancing** [comment]
Thanks for the clarification. I'm not able to get that script to work but I'll probably stick to another tool for prerecorded content and use owncast for live.

**Comment by gabek** [comment]
This adds an interesting use case when we do add the ability to support recordings: Being able to upload a pre-recorded video and convert it to an Owncast recording.
