### ISSUE TITLE
Followers: If user doesn't have a name then use the account name

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2680]
### Share your bug report, feature request, or comment.

Not all Fediverse accounts set a friendly name, so in that case we can just use the account as the name.

![image](https://user-images.githubusercontent.com/414923/216802169-11b50b37-e76c-4466-a8ff-5567a28c4357.png)

**Comment by Yasir761** [comment]
I want to work on this.

**Comment by gabek** [comment]
Awesome, thank you!

**Comment by Yasir761** [comment]
Can you provide me more information regarding this issue?

**Comment by gabek** [comment]
Sure. There's two pieces of text, and if the top one is missing then just use the value for the bottom one as the top one. The story exists here: https://owncast.online/components/?path=%2Fstory%2Fowncast-components-followers-followers-collection--example

<blockquote><div><strong><a href="https://owncast.online/components/?path=%2Fstory%2Fowncast-components-followers-followers-collection--example">Webpack App</a></strong></div></blockquote>
