### ISSUE TITLE
Option to prevent Google indexing of Owncast pages

### ISSUE THREAD

**Issue by rmens** [owncast/owncast#2684]
### Feature request

An experimental instance of mine got indexed by Google. Currently the web interface doesn't prevent indexing by search engines. 

I propose a checkbox in the admin interface that reads "Prevent search engines from indexing this Owncast instance". It could be unchecked by default. When it's checked, the following could be placed in the `<head>` of the public web app.

`<meta name="robots" content="noindex, nofollow">`

If the checkbox is not checked, the following could be placed:

`<meta name="robots" content="index, nofollow">`

#### Making the case for nofollow
Since most Owncast interfaces provide a chat interface that let's the public enter anything, it's good practice to tell search engines to not follow external links on the page. Because nofollow links do not pass PageRank they don't impact search engine rankings and this prevents spammers for trying to boost their SEO juice via popular Owncast instances.

**Comment by gabek** [comment]
Sounds reasonable. While in the past I've heard people wanting to be indexed more and to get their instance surfaced more, I do understand there are times when you'd want the opposite.

**Comment by rmens** [comment]
Thanks. Providing clear directives to search engines that say "do index me" could also help getting indexed more. Currently there are no robots directives. So this should help in both scenarios.

**Comment by gabek** [comment]
In the mean time you can create your own `robots.txt` and put any requests to search engines not to index in there, as well.
