### ISSUE TITLE
Standardize tab content to use a single background

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2685]
### Share your bug report, feature request, or comment.

Right now each tab draws its own background and it's not standardized. It would probably be better if there was a single background behind all the tab content so these kind of discrepancies can't occur. 

About tab:

![image](https://user-images.githubusercontent.com/414923/216885888-c05d0c11-827f-4190-b579-b8d3406009b6.png)

Followers tab:

![image](https://user-images.githubusercontent.com/414923/216885940-0466bc52-52da-4f55-9306-d395bb521e77.png)

**Comment by dorj222** [comment]
may I claim and work on this issue?

**Comment by gabek** [comment]
Absolutely, thank you!

**Comment by dorj222** [comment]
I am having a little bit hard time finding these tabs. How may I open these two tabs?

**Comment by gabek** [comment]
The tab bar only shows if you have both tabs to show. You'll want to turn on the social features so the "Followers" tab will show up. You can see that in action on the nightly build: https://nightly.owncast.tv

<blockquote><img src="https://nightly.owncast.tv//thumbnail" width="48" align="right"><div><img src="/img/favicon/favicon-16x16.png" height="14"> Owncast Nightly</div><div><strong><a href="https://nightly.owncast.tv/">Owncast Nightly</a></strong></div><div>This is a server running the nightly build of Owncast.</div></blockquote>

**Comment by dorj222** [comment]
I managed to find them. Thanks a lot!

**Comment by dorj222** [comment]
Is it possible to follow my own stream without a legitimate Server URL? I provided http://localhost:3000/ as my Server URL and tried to follow myself; unfortunately, it does not work.

**Comment by gabek** [comment]
You need to have a public server accessible on the Fediverse for you to be able to follow it. Localhost won't be accessible from other servers.

**Comment by gabek** [comment]
@dorj222 Just checking in to see if you're still looking at this, otherwise I can take care of it. Thanks!

**Comment by dorj222** [comment]
Hi there! I wasn't able to get a public server accessible on the Fediverse. If it is possible, would you please take care of it? I sincerely apologize for not completing this issue.

**Comment by gabek** [comment]
No problem!
