### ISSUE TITLE
Replace github.com/nanmu42/gzip + support brotli encoding

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2697]
### Share your bug report, feature request, or comment.

We use github.com/nanmu42/gzip as gzip middleware, but it's importing the entire Gin web framework. This dependency should replaced with something thinner.

https://github.com/owncast/owncast/blob/develop/router/router.go#L8

**Comment by Pranav2612000** [comment]
Hi @gabek 
I'll like to work on this issue.

**Comment by gabek** [comment]
Hi there! What are you thinking about replacing this dependency with?

**Comment by Pranav2612000** [comment]
There were a couple of options. We can use the official [package](https://pkg.go.dev/compress/gzip). Another options is https://github.com/klauspost/compress/tree/master/gzhttp

Although I'm not sure how I can test whether the new package works correctly. Can you help with it? How can I do this?

<blockquote><img src="https://opengraph.githubassets.com/1eb66c44b07397664fb83f51f0a8c863aa014b4069cdb755b6d073c249c1b3a2/klauspost/compress" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/klauspost/compress">compress/gzhttp at master · klauspost/compress</a></strong></div><div>Optimized Go Compression Packages. Contribute to klauspost/compress development by creating an account on GitHub.</div></blockquote>

**Comment by gabek** [comment]
I suppose you'd swap out the middleware that's currently in use with something else, and then verify Owncast still functions the same.

**Comment by Pranav2612000** [comment]
Understood. I'll give this a try and have a PR ready sometime this week.

**Comment by gabek** [comment]
I haven't looked deeply into this, but it seems this supports brotli as well. https://github.com/CAFxX/httpcompression

<blockquote><img src="https://opengraph.githubassets.com/6801e84a361f438d68281c752d16891ed5cb23975c792d958d772c6c01075963/CAFxX/httpcompression" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/CAFxX/httpcompression">GitHub - CAFxX/httpcompression: Go middleware to compress HTTP responses with Gzip, Deflate, Brotli, and Zstandard.</a></strong></div><div>Go middleware to compress HTTP responses with Gzip, Deflate, Brotli, and Zstandard. - GitHub - CAFxX/httpcompression: Go middleware to compress HTTP responses with Gzip, Deflate, Brotli, and Zstand...</div></blockquote>

**Comment by Pranav2612000** [comment]
Do you suggest we use brotli instead of gzip?
