### ISSUE TITLE
Synchronize web_modules when package.json updates

### ISSUE THREAD

**Issue by mattdsteele** [owncast/owncast#270]
When Dependabot commits (or other commits) update `package.json`, we want to synchronize the vendor assets in `web_modules`, by regenerating them in Snowpack (using `npm run build`) and committing any differences.

I think this can be done with GitHub Actions.

An action can be triggered to only run on changes to a file using the `on.paths` flag https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths

And new commits can be triggered from a GH Action; such as with https://github.com/marketplace/actions/add-commit or https://github.com/marketplace/actions/git-auto-commit

**Comment by gabek** [comment]
I took a stab at it.  After a few failed attempts, I think it's working now?  https://github.com/owncast/owncast/blob/master/.github/workflows/javascript-packages.yaml

**Comment by gabek** [comment]
I take it back, it's erroring out.  https://github.com/owncast/owncast/runs/1279145478.  I'll look at it some more tomorrow.

**Comment by gabek** [comment]
Ack it kept adding `node_modules` to the repo, I had to remove the workflow completely for now until I can find a way to test it offline.
