### ISSUE TITLE
Favicon points to an invalid image

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2701]
### Share your bug report, feature request, or comment.

Example: 
![image](https://user-images.githubusercontent.com/414923/218338485-18087350-eac3-48e7-9c2b-31c204ec769e.png)

**Comment by mehrdadbn9** [comment]
hi 
i would like to contribute can you assign me 
and if possible give more info if it's  possible

**Comment by gabek** [comment]
Sure, thanks! So it looks like what's happening is somewhere there's a favicon being pointed to via the relative path of `/img/favicon/favicon-16x16.png` making sites not load it properly. It should use the absolute URL with full domain name if the full domain name is set. If it's not set then the current relative path will have to do.

**Comment by mehrdadbn9** [comment]
i've found it in index's file of html and js i think they have written like other and the path for favicon is:
/img/favicon/favicon-16x16.png

**Comment by gabek** [comment]
Correct, but it's not using the absolute URL of the image.

**Comment by mehrdadbn9** [comment]
so i will change them to absolute one in both of them

**Comment by gabek** [comment]
Looking at this it seems like maybe that screenshot above is due to cached data. So I'm going to say this can be tabled and not need to be looked into unless something else comes up.
