### ISSUE TITLE
Set stream title in video tag for iframe embed of owncast streaming url

### ISSUE THREAD

**Issue by JoanLP** [owncast/owncast#2702]
### Share your bug report, feature request, or comment.

Please a create a title attribute in the video tag when the the owncast url is embedded in an iframe as seen below. This allows for example, on iphone, the title of the stream to be displayed when the screen is locked.

<video class="vjs-tech" id="video_html5_api" preload="auto" playsinline="playsinline" tabindex="-1" src="/hls/stream.m3u8" title="hello viewers"></video>

Thanks

**Comment by JacobWrenn** [comment]
Hi @JoanLP, please could you provide some more detail on how to replicate this? I think you may have meant to attach an image that isn't showing?

**Comment by gabek** [comment]
I'm guessing what is being asked for here is adding the `title` attribute, with the stream name, to our video player.

**Comment by JoanLP** [comment]
Yes exactly that. Player when embed it says undefined when on mobile device
as seen in the screenshot. Can artist info be added in addition to title?

**Comment by gabek** [comment]
Could you clarify what you mean by the "artist" in this case?

**Comment by JoanLP** [comment]
Please see attachment. This is a YouTube live stream. It has title of the
stream and name of the creator

Are you able to see the attachment?

**Comment by gabek** [comment]
Nope! No attachment.

**Comment by JoanLP** [comment]
Please check this link it should be active for a few days.

https://ibb.co/Y2G3Lv8

It has video title and creator name. With yours it just says undefined for
title and nothing for creator.

Let me know if this helps?

**Comment by gabek** [comment]
Moving the image here for easier reference.

![image](https://github.com/owncast/owncast/assets/414923/0c6101fb-31db-493f-86fb-69837d9ee2b0)

**Comment by AsherHounsell** [comment]
Hello I am part of the University of Toronto group, we were wondering on if we could work on this issue.

Team members: @jhimanish @EthanZheng11, @AsherHounsell, @TashanManiyalaghan

**Comment by JoanLP** [comment]
I’m in!Sent from my iPhoneOn Dec 6, 2023, at 12:02 AM, AsherHounsell ***@***.***> wrote:﻿
Hello I am part of the University of Toronto group, we were wondering on if we could work on this issue.
Team members: @jhimanish @EthanZheng11, @AsherHounsell, @TashanManiyalaghan

**Comment by gabek** [comment]
Sure! Please don't hesitate to ask any questions or need clarification. Hopefully, the above thread will be helpful.

> Hello I am part of the University of Toronto group, we were wondering on if we could work on this issue.
> 
> Team members: @jhimanish @EthanZheng11, @AsherHounsell, @TashanManiyalaghan

**Comment by mahmed2000** [comment]
Afaik, this isn't strictly an iframe thing. Its the [Media Session API](https://developer.mozilla.org/en-US/docs/Web/API/Media_Session_API) that allows customization of notification information. MediaSession already has good enough defaults for controls so only need to touch the MediaMetadata.

title -> Stream title
artist -> ~~Streamer name?~~ federation only, maybe just server name or omit
album -> null
artwork -> server logo

Not quite sure where to set this all though.

**Comment by gabek** [comment]
Luckily the answer seems to be easy on how to set it: 
``
navigator.mediaSession.metadata = new MediaMetadata(metadata);``

As to where to set that in the Owncast web frontend, we could do it in the player, or create a new small component that all it does is set metadata just like how we have one that sets the browser title. Or even expand the responsibility of [TitleNotifier](https://github.com/owncast/owncast/blob/develop/web/components/TitleNotifier/TitleNotifier.tsx) to be more of a `StatusNotifier` and add this to that.
