### ISSUE TITLE
"Undefined constant" when using h264_nvenc to reencode

### ISSUE THREAD

**Issue by rosegayming** [owncast/owncast#2703]
### Share your bug report, feature request, or comment.

Getting  these errors when using h264_nvenc
```
[h264_nvenc @ 0x75e000] [Eval @ 0x7fffacd2c080] Undefined constant or missing '(' in 'p1'
[h264_nvenc @ 0x75e000] Unable to parse option value "p1"
[h264_nvenc @ 0x75e000] Error setting option preset to value p1.
```

I get the same error using 4 and 5 (I saw in some other issues that 5 made some syntax changes). 

This [transcoder.log](https://github.com/owncast/owncast/files/10718104/transcoder.log) was made with ffmpeg 5.1.2, on nixos-unstable, running owncast 0.0.13

**Comment by gabek** [comment]
~~I know you said you've tried with both ffmpeg 4 and 5 but ffmpeg 5 with nvenc is not yet supported. See #2071 for more details. Please test again using ffmpeg 4 and provide that log along with any specifics about your configuration.~~

Sorry, that was incorrect. I was thinking of va-api, not nvenc. Ignore.

**Comment by gabek** [comment]
Could you provide a detailed copy of your owncast video configuration so I could try and reproduce it?

**Comment by rosegayming** [comment]
1280x720 60fps 2100kbps for my output stream. 
1920x1080 60fps 6000kbps for my input.
(I realise this is a weird setup, I had other output streams I removed to simplify testing)

I can give other info if needed.

**Comment by gabek** [comment]
Does this match exactly what you have? If so, I can't seem to reproduce it, it's working ok for me. Can you find any differences? Have you tried with other builds of ffmpeg? And I don't have any experience with nixos, nor do I have access to a nixos machine, so unfortunately I can't say if that is related at all.

```
INFO[2023-02-12T22:35:09-08:00] Video transcoder started using nvidia nvenc with 2 stream variants.
```

![image](https://user-images.githubusercontent.com/414923/218387704-b688285c-c139-4452-8beb-ad734644d5d9.png)
![image](https://user-images.githubusercontent.com/414923/218387835-24db6e2b-5d4e-4e3b-b115-5cb3bd08488a.png)
![image](https://user-images.githubusercontent.com/414923/218387879-cec9cd24-84d9-4938-ac29-5a3d411f7836.png)

Copy of ffmpeg:
```
ffmpeg version N-99925-g96443ab4b0 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
```

**Comment by rosegayming** [comment]
The 1080p stream is what I'm sending to owncast from obs, the only stream in the video tab is the 720p one, which is correct.

**Comment by gabek** [comment]
A different question that might help me narrow things down: Is there any configuration that works for you? What if you don't use nvenc, does that fix it, or are you unable to stream regardless of the configuration in Owncast? What if you don't change the size of the output? I'm curious if this is the same issue as #2682.

**Comment by rosegayming** [comment]
It is specifically a nvenc issue, it works fine when using libx264
I've tried changing the resolution, same issues

**Comment by hagn** [comment]
I'm pretty sure it's the same issue I had previously.
The ffmpeg version you're using was probably built with an older version of the NVIDIA Video Codec SDK (V9 or earlier). This version doesn't yet recognize the P1, P2, etc. quality preset names as they were only introduced a few years ago: https://developer.nvidia.com/blog/introducing-video-codec-sdk-10-presets/
I had to built ffmpeg on my own as the Ubuntu package didn't have the correct version yet.

<blockquote><img src="https://developer-blogs.nvidia.com/wp-content/uploads/2020/07/geforce-now-platform.png" width="48" align="right"><div>NVIDIA Technical Blog</div><div><strong><a href="https://developer.nvidia.com/blog/introducing-video-codec-sdk-10-presets/">Introducing NVIDIA Video Codec SDK 10 Presets | NVIDIA Technical Blog</a></strong></div><div>All NVIDIA GPUs starting with the Kepler generation support fully accelerated hardware video encoding, and all GPUs starting with the Fermi generation support fully accelerated hardware video decoding…</div></blockquote>

**Comment by rosegayming** [comment]
Thanks! I'm currently in school but I'll try this once I get home.

**Comment by gabek** [comment]
Thank you for chiming in @hagn! This could very well explain things. In my nvenc setup I built everything myself, as well and I hadn't had issues, so that makes sense. If this fixes it for you we should update the Owncast documentation to explicitly call out the requirements for nvenc support.

You've probably already seen this page, but here's some links to building ffmpeg with nvenc support: https://owncast.online/docs/codecs/#nvidia-encoder-nvenc

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="/favicon.png" height="14"> Owncast</div><div><strong><a href="/docs/codecs/">Codecs & Hardware Acceleration</a></strong></div><div>If you have direct access to specific hardware you may be able to increase the performance of your server by using a compatible codec.</div></blockquote>

**Comment by rmens** [comment]
> A different question that might help me narrow things down: Is there any configuration that works for you? What if you don't use nvenc, does that fix it, or are you unable to stream regardless of the configuration in Owncast? What if you don't change the size of the output? I'm curious if this is the same issue as #2682.

Saw this mention of the issue that I opened, so looked into it. Pretty sure these are unrelated.
