### ISSUE TITLE
Remove usage of the PropTypes dependency

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2710]
### Share your bug report, feature request, or comment.

All our components should be using the `FC` Functional Components props without the use of an added dependency.  I think there's probably only about five components that need to be changed so this can be removed. Search for `prop-types` to see where it's imported in the web app.

See https://owncast.online/components/?path=%2Fdocs%2Fowncast-documentation-building-frontend-components--page

**Comment by dhanusaputra** [comment]
hi, would like to help this task. is it ok to assign this to me? thank you

**Comment by gabek** [comment]
Absolutely, thank you! :+1:
