### ISSUE TITLE
Name change chat action has wrong text color

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2718]
### Share your bug report, feature request, or comment.

It should be using the chat text color.

![image](https://user-images.githubusercontent.com/414923/219922514-63340e1e-ff07-4bd5-9ff3-a5cb88c56a2e.png)

**Comment by Rishav1707** [comment]
Can you share a little bit more information about this issue??

**Comment by gabek** [comment]
If you look at the screenshot above the black text should not be black, it should be using `theme-color-components-chat-text` as seen here: https://owncast.online/components/?path=%2Fdocs%2Fowncast-styles-colors-components--page
