### ISSUE TITLE
When live & there's a stream title set, show it in the header

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2720]
### Share your bug report, feature request, or comment.

When the stream is live and the stream title is set:

1. The header should show the stream title.
2. Do not show the stream title in the content header, show the actual server description.

![image](https://user-images.githubusercontent.com/414923/219922806-084d8d1e-6fd7-4dc3-a8b2-a79a13fbbbee.png)

**Comment by Ritikkhulbe** [comment]
Hey @gabek, i would like to work on this issue , im new to git and i didn't understand what needs to be done clearly, so if you could let me know, please do ?

**Comment by gabek** [comment]
Unfortunately this probably isn't the place to learn how to use Git from scratch. I would, however, recommend going through this brief tutorial to learn the Git basics: https://github.com/firstcontributions/first-contributions/blob/main/README.md.

If after you feel more comfortable making contributions through a Git workflow, please do feel free to come back here!

<blockquote><img src="https://repository-images.githubusercontent.com/68720867/e42fb180-ff32-11ea-9869-ba8195705621" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/firstcontributions/first-contributions">first-contributions/README.md at main · firstcontributions/first-contributions</a></strong></div><div>🚀✨ Help beginners to contribute to open source projects - first-contributions/README.md at main · firstcontributions/first-contributions</div></blockquote>

**Comment by Ritikkhulbe** [comment]
@gabek yes I know the git basics and how to make contributions but I didn't understand the issue , or i could start working on what i understood, i would like to do that

**Comment by gabek** [comment]
Oh got it, you mentioned you were new to Git.

Here's a bit more detail:

When an Owncast stream goes live it should show the `streamTitle` value (as seen in the `ClientConfigStore`) in the header. It should not be showing instead of the description in the `ContentHeader` like it is now.

See https://owncast.online/development for details around how to get the project, frontend and backend, up and running.

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="https://owncast.online/favicon.png" height="14"> Owncast</div><div><strong><a href="/development/">How to work on Owncast</a></strong></div><div>The technical details for those wishing to take part in Owncast development.</div></blockquote>

**Comment by Ritikkhulbe** [comment]
@gabek thank you, on it

**Comment by gabek** [comment]
Hi @Ritikkhulbe, just checking in to see if you had any other questions and if everything makes sense.

**Comment by gabek** [comment]
I'm working on some header adjacent stuff, so I'm just going to go ahead and take care of this while I'm at it.
