### ISSUE TITLE
Windows edge: Test + investigate

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2731]
### Share your bug report, feature request, or comment.

The automated screenshots show Microsoft Edge not working with Owncast.

https://owncast.online/components/?path=%2Fdocs%2Fowncast-screenshots-windows-edge--online

![image](https://user-images.githubusercontent.com/414923/221152364-ff472d9b-ba44-428a-9382-523d0299601f.png)

**Comment by gabek** [comment]
I don't have access to a Windows machine at the moment, but testing on Browserstack seems to be ok. Hopefully we can get some sanity tests from some real Windows users.

![image](https://user-images.githubusercontent.com/414923/221323212-19b5ca56-2520-48da-a30e-e591700cea2a.png)

**Comment by edmael** [comment]
![immagine](https://user-images.githubusercontent.com/1659050/221350385-6ad3b70c-5f00-4347-9af6-878a8e592056.png)

It works pretty fine here: Windows 11 with Edge Version 110.0.1587.50 (Official build) (64-bit)

**Comment by rmens** [comment]
The broken layout might be shown in the legacy Microsoft Edge browser with the EdgeHTML rendering engine. That was shipped with Windows before Microsoft Edge switched to Chromium as render engine.

I tried to find some old computers at our TV station to see if any computer has this browser installed still. It seems that Microsoft has done a proper job of cleaning it up. Even the Windows 7 computers that are there for specific tasks and only get their updates installed once in a while have the Edge Chromium based browser installed. They are flashing a warning that the browser is no longer supported, but Owncast Nightly works.

I'm downloading a VM with the legacy EdgeHTML rendering engine in it now. But it's very slow. To be continued, but in the meantime here are the Edge Chromium tests.

## Windows 7 - Edge Chromium 109.0.1518.78 (official build) (64-bits) [latest supported version]

<img width="1618" alt="Schermafbeelding 2023-02-25 om 13 50 48" src="https://user-images.githubusercontent.com/6742496/221357799-d403be86-821a-46af-ae89-84801e013aa5.png">

## Windows 10 - Edge Chromium 110.0.1587.56 (official build) (64-bits)

1280x1024

<img width="708" alt="Schermafbeelding 2023-02-25 om 13 15 41" src="https://user-images.githubusercontent.com/6742496/221356418-56a86929-5441-42ca-b027-2ea758c814eb.png">

1920x1080
<img width="1028" alt="Schermafbeelding 2023-02-25 om 13 16 05" src="https://user-images.githubusercontent.com/6742496/221356430-2b960e95-3d55-4c5d-83a2-54b979606451.png">

Odd resolution (vertical screen)
<img width="1028" alt="Schermafbeelding 2023-02-25 om 13 16 32" src="https://user-images.githubusercontent.com/6742496/221356440-d8b082fa-9fc8-46fc-bc24-26157118bf22.png">

Doesn't look broken. But I would't mind the footer always at the very bottom.

**Comment by rmens** [comment]
Bingo! It's Microsoft Edge with the EdgeHTML rendering engine that causes problems. 

## Windows 10 Edge 42.17134.1.0 (EdgeHTML)

<img width="1627" alt="Schermafbeelding 2023-02-25 om 17 10 52" src="https://user-images.githubusercontent.com/6742496/221367414-0e054f87-d215-4a00-a47d-84fe1e1037a2.png">

Like I already said, I would be surprised if there is anyone using this any more since even Windows 7 was upgraded to Edge Chromium. Can you choose between render engine in the auto screenshotter and put that on Edge Chromium instead of EdgeHTML @gabek?

**Comment by gabek** [comment]
Thank you for tracking that down, now it makes a lot more sense! The tool I put together for generating screenshots uses devices on Browserstack, and they have up to Edge version 18 on Windows 10, so that's the version I'm using. Since it sounds like that's quite old I agree it's probably not a valid test target. Probably nothing more to worry about here. Thanks again!
