### ISSUE TITLE
CPU usage description needs additional spacing

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2733]
### Share your bug report, feature request, or comment.

![image](https://user-images.githubusercontent.com/414923/221274299-90f16225-5e15-4305-a478-02146801ca3c.png)

**Comment by emday4prez** [comment]
hello, I believe I can resolve this issue.

**Comment by gabek** [comment]
Great, thank you!

**Comment by emday4prez** [comment]
nevermind, when trying to `go run main.go` i keep receiving the error ' Unable to determine path to ffmpeg. Please specify it in the admin or place a copy in the Owncast directory.' ...  I placed a copy in the owncast dir with no luck.

**Comment by dhanusaputra** [comment]
hi gabek, let me try replicate and try this if ok, thank you

**Comment by gabek** [comment]
Great, thank you!
