### ISSUE TITLE
Selected emoji are populating input twice

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2734]
### Share your bug report, feature request, or comment.

Select an emoji once, and it shows up twice.

![image](https://user-images.githubusercontent.com/414923/221322321-a9f24b73-0238-49b2-85c4-14f3b168aba1.png)

**Comment by bennett1412** [comment]
Hey, can i work on this issue?

**Comment by gabek** [comment]
Absolutely! I think it's intermittent and feels kind of messy so another set of eyes would be great.  It's not reproducible (currently) in the [story](https://owncast.online/components/?path=%2Fdocs%2Fowncast-chat-input-text-field--example) but was in the production build.

**Comment by bennett1412** [comment]
oh okay, ill start with reproducing it in the dev build. thanks

**Comment by gabek** [comment]
I take it back! I tested it in Storybook before I sent that message, and then I tested it again after. I was 100% able to reproduce the problem in Storybook the second time, but not the first:

![image](https://user-images.githubusercontent.com/414923/221395142-6fbca6ce-ca6d-4108-ab5c-e587a3cc00fb.png)

**Comment by bennett1412** [comment]
oh okay even better, ill get right to it 👍

**Comment by gabek** [comment]
For some added detail, the text input box is using a component called [Slatejs](https://www.slatejs.org), an overly complicated text component because I had issues building my own `contentEditable` solution with React. I think this overly complicated component is the source of the problems and if there was a more obvious solution that allowed rendering images within an input box it might be worth moving to it.

**Comment by bennett1412** [comment]
maybe checkout [tiptap.js](https://tiptap.dev/)? it's a pretty good alternative to slate.js and does allow[ rendering images](https://tiptap.dev/api/nodes/image) as well
also, i cannot reproduce the issue in the storybook, it's working as intended for me, could you let me know which browser you're using?

**Comment by gabek** [comment]
I think it's very intermittent. Like I mentioned the first time I tried it in Storybook it was fine, and then I tried it again and the problem occurred each time I selected a custom emoji. I'm using a Chromium based browser, Brave.  It doesn't look like tiptap is natively a React component, and that would have to be worked around. I wonder if that's worth it or if trying to shoehorn it into React would just cause its own issues.

In the UI v1 of Owncast (not React) we had our own `contentEditable` div and it worked great, but React makes it more complex in this particular case.

**Comment by bennett1412** [comment]
yeah, tiptap is framework agnostic but i have used it with react and it didn't give me issues as such, very compatible with react
since im not able to reproduce the issue in storybook, ill try to reproduce it locally, sorry to keep bugging you like this 😅

**Comment by bennett1412** [comment]
hey, i have fixed the issue 
The problem was that the insertImage function was inserting the custom emoji image twice, i have made it a bit more simpler and reduced it to just one call.
