### ISSUE TITLE
Slider anchor points not visible with stream quality steps

### ISSUE THREAD

**Issue by rmens** [owncast/owncast#2750]
### Bug report

The old Owncast interface has clear anchor points for CPU usage and stream bitrate.

<img width="844" alt="Schermafbeelding 2023-02-27 om 23 50 11" src="https://user-images.githubusercontent.com/6742496/221704992-85493734-586b-4f86-93d3-cb23f5d4821e.png">

The interface in 0.1.0 has them missing from CPU usage, but they are there in the stream bitrate slider.

<img width="882" alt="Schermafbeelding 2023-02-27 om 23 48 09" src="https://user-images.githubusercontent.com/6742496/221705426-afc8d20a-a097-4c9f-9242-05f5e747c418.png">

**Comment by Fa2112** [comment]
I would like to help with this :)

**Comment by gabek** [comment]
Awesome, thanks so much!

**Comment by gabek** [comment]
@Fa2112 Hi there! Are you still looking at this?

**Comment by gabek** [comment]
I'm going to go ahead and unassign, but feel free to chime in if you're working on this.
