### ISSUE TITLE
Confirmation mark needs a bit of padding

### ISSUE THREAD

**Issue by rmens** [owncast/owncast#2751]
### Bug report

Owncast 0.1.0.

Spotted this when changing page content:

<img width="374" alt="Schermafbeelding 2023-02-28 om 00 00 46" src="https://user-images.githubusercontent.com/6742496/221708883-4ccdc700-5b47-4317-a306-a855de45bc6d.png">

And video settings:

<img width="547" alt="Schermafbeelding 2023-02-28 om 00 01 41" src="https://user-images.githubusercontent.com/6742496/221708953-31622b16-ccae-4050-818d-797dbfecfa24.png">

It would look better if it had a bit more padding.

**Comment by kaushikc44** [comment]
Can you please point out to the files that it is in and the techstacks , also if your using Tailwind or something else.

**Comment by gabek** [comment]
@kaushikc44 The comment above points to [this page](https://owncast.online/development/) that details how to get started working on Owncast.

**Comment by thisprojects** [comment]
Heya @gabek - this should be a quick one, can I work on this? 😺

**Comment by thisprojects** [comment]
Have raised https://github.com/owncast/owncast/pull/2808 for this one
