### ISSUE TITLE
Hide custom page content section if it is empty.

### ISSUE THREAD

**Issue by rmens** [owncast/owncast#2752]
### Share your bug report, feature request, or comment.

Owncast 0.1.0

I emptied this section in the admin

<img width="593" alt="Schermafbeelding 2023-02-28 om 00 27 06" src="https://user-images.githubusercontent.com/6742496/221712569-1134c6e8-fecc-4b1d-bce5-87fd40bfab98.png">

And now there's an empty box here

<img width="896" alt="Schermafbeelding 2023-02-28 om 00 24 27" src="https://user-images.githubusercontent.com/6742496/221712605-3f441eff-2fa6-4c5b-a272-dce0c213161f.png">

It looks a bit strange. Should it be hidden if there's nothing in it?

**Comment by gabek** [comment]
Probably not, let's hide it.

**Comment by gabek** [comment]
Layout: https://owncast.online/components/?path=%2Fstory%2Fowncast-layout-main--offline-desktop

<blockquote><div><strong><a href="https://owncast.online/components/?path=%2Fstory%2Fowncast-layout-main--offline-desktop">Webpack App</a></strong></div></blockquote>
