### ISSUE TITLE
Bottom half of page infinitely loading after refreshing page

### ISSUE THREAD

**Issue by rmens** [owncast/owncast#2753]
### Share your bug report, feature request, or comment.

Owncast 0.1.0. Could reproduce this on my own testing server and nightly.owncast.tv. 

- Open Owncast Nightly in a private tab in Safari
- Wait a bit and refresh the page
- The bottom part of the screen will be gone. It keeps loading. The stream does play however. 

![A35973DC-2972-4818-B77F-300D87010CB9](https://user-images.githubusercontent.com/6742496/221718157-8904d74e-2e07-485c-ab09-31a32d777e20.png)

Browser: Safari 16.3 on iOS.

**Comment by gabek** [comment]
Does this only occur on iOS? How long do you have to wait before it occurs? I haven't been able to reproduce this myself so far.

**Comment by rmens** [comment]
Here's it on the public nightly.owncast.tv:

https://user-images.githubusercontent.com/6742496/221803343-8794ce84-8a61-4aca-aab8-26f4a592b55b.MP4

And on my own nightly build:

https://user-images.githubusercontent.com/6742496/221803877-f36439c2-d363-4bea-a451-cee37da9e5fc.mov

I couldn't reproduce it on desktop and don't have an Android mobile device handy right now.

**Comment by gabek** [comment]
I was able to reproduce it on the server in your example even using a desktop browser using the mobile layout. But I haven't been able to reproduce it elsewhere. But at least that points me in the right direction that it might be layout related, not browser related.

**Comment by t1enne** [comment]
Can't reproduce it on nightly.owncast.tv from desktop firefox on  a 375w window. @gabek have you tried on something other than Safari by chance?

**Comment by gabek** [comment]
On mobile I've only tried it with Safari. Did you try it with that server in @rmens example?  That's how I was able to reproduce it in a narrow window.

**Comment by rmens** [comment]
I'm back at home with my Mac available now. Did some testing.

**Firefox 110.0.1 (64-bits - macOS desktop)**

<img width="562" alt="Schermafbeelding 2023-03-03 om 21 53 10" src="https://user-images.githubusercontent.com/6742496/222827243-e0cd411d-fbdb-43d7-ace6-5456dcbacd79.png">

**Chrome 110.0.5481.177 (64-bits - macOS desktop)**

<img width="612" alt="Schermafbeelding 2023-03-03 om 21 53 48" src="https://user-images.githubusercontent.com/6742496/222827456-a9502391-a6eb-49c4-ab17-2af211f6ee2b.png">

Seems to be more of an issue with narrow windows and not iOS only. Not sure what triggers this in my specific instance.

**Comment by gabek** [comment]
One difference of note, https://owncast.zuidwesttv.nl/ has empty custom page content on the bottom of the page, so maybe the layout is doing something incorrectly because of that.

<blockquote><img src="/thumbnail.jpg" width="48" align="right"><div><img src="/img/favicon/favicon-16x16.png" height="14"> New Owncast Server</div><div><strong><a href="https://owncast.zuidwesttv.nl/">New Owncast Server</a></strong></div><div>This is a new live video streaming server powered by Owncast.</div></blockquote>

**Comment by gabek** [comment]
Disabling chat I was able to reproduce this locally using the mobile layout.
