### ISSUE TITLE
User moderator chat details modal throws exception

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2755]
### Share your bug report, feature request, or comment.

1. Become a moderator
2. Select moderator menu of a chat message from the primary chat web interface
3. Choose "More info"

![image](https://user-images.githubusercontent.com/414923/221741107-15ac7abc-0a44-41a7-95e4-77de8baf533e.png)

**Comment by thisprojects** [comment]
@gabek Hmmm - seems to work for me 🤷 - are there any other specific details I need to consider? Im starting a local stream with OBS, have made myself moderator from the /admin panel. Then followed instructions in the description.

Am clicking on the 3 dots next to a chat msg and selecting more info - a modal appears as in the image below.

![Screenshot 2023-03-10 at 22 10 04](https://user-images.githubusercontent.com/34570423/224437736-9acdbbba-7269-4f24-9885-eb95b8af88f9.png)

**Comment by gabek** [comment]
That's good to know! Maybe it was related to something else that has been fixed, or maybe my steps above were unrelated to the error and was a red herring. I'll try to reproduce it again. Thank you for looking!

**Comment by rmens** [comment]
Can reproduce this on my Owncast Nightly. 

https://user-images.githubusercontent.com/6742496/224442351-fbae8ed3-c868-468f-b936-5aa9f24f3006.mov

It only happens if you click on someone else's message as moderator. Not on your own message. Try connecting as another user in a private tab to simulate multiple users.

**Comment by thisprojects** [comment]
@gabek 

Heya Gabe -  I think its the case that standard users (IE randomers who connected to watch the stream) don't have a `scope`. If i do `more info` on my moderator user, it shows me as having a scope of `moderator`. The scope variable for a standard user is `undefined`. 

We can work around this by doing a check on the `scope` variable in `ChatModerationDetailsModal` Eg 

`     {scopes?.map(scope => (
        <Tag key={scope}>{scope}</Tag>
      ))}`

I'll raise a PR for this change - let me know if you'd like this tackled in another way, should standard user have a scope assigned to them?

**Comment by gabek** [comment]
I added this to the list of components that should have an error boundary to gracefully handle uncaught exceptions such at this. https://github.com/owncast/owncast/issues/2811
