### ISSUE TITLE
Download button missing on viewers and CPU usage graph

### ISSUE THREAD

**Issue by rmens** [owncast/owncast#2758]
### Share your bug report, feature request, or comment.

Owncast 0.1.0

In the old Owncast interface, there was a download button to download a graph on the CPU usage page and on the viewers page.

![Schermafbeelding 2023-02-28 om 10 34 00](https://user-images.githubusercontent.com/6742496/221812501-6bcec98b-aa0b-4cb5-8a79-7afe3dfe031b.png)

It doesn't show up in the Owncast 0.1.0 nightly.

![Schermafbeelding 2023-02-28 om 10 34 43](https://user-images.githubusercontent.com/6742496/221812813-87fc4f2f-6e86-441d-942e-cd0ba61d12a5.png)

This is probably a lesser used function. I used it one time to save a graph of a record amount of viewers we had, so it's a nice to have.

**Comment by gabek** [comment]
I'm not sure if this graph component supports adding a way to download the graph itself offhand, but hopefully it's easy to find out.

**Comment by bennett1412** [comment]
hello, 
so i checked this component, one solution that i thought of was, since the graph is a canvas element, we can use the dataUrl method of the canvas (chart) and have a button to download the image. This can be done using [vanilla js](https://stackoverflow.com/a/50300880).
but it would only be able to download the chart not the pie graphs, not sure if those are needed

**Comment by gabek** [comment]
Only the charts were downloadable before, so that works. Great find! Are you interested in adding a download link in these charts? It doesn't need to look exactly like it did before in the old component.

**Comment by bennett1412** [comment]
yeah sure, feel free to assign the issue to me

**Comment by gabek** [comment]
Awesome, thank you!

**Comment by bennett1412** [comment]
Hey,
I have created a pr to resolve this issue. https://github.com/owncast/owncast/pull/2914
