### ISSUE TITLE
Add video quality consumption graph to stream health overview

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2759]
It could be useful to not only see what network speeds the viewers are downloading video at like we do now, but also see specifically what qualities they're explicitly consuming.

It answers pretty much the same question of "What speeds are necessary to provide a stable stream for my viewers?" but the other side of it, "What qualities are being viewed currently given the viewers' network speeds?"

**Comment by JacobWrenn** [comment]
Hi @gabek I don't have too much experience with Go but would like to have the opportunity to learn more through trying to complete a task. Do you think this issue would be feasible?

**Comment by gabek** [comment]
Hi Jacob!

This is a rather large addition that requires ample additions to the video player as well, so I'm not sure I'd recommend it to somebody new to the project or new to Go.

Do you have any familiarity with S3 providers? There's a couple issues filed that are self-contained and might be good issues to start with: #2771 #2646

**Comment by JacobWrenn** [comment]
Thanks, I've had a look and I think I could #2771 a go as long as you don't need it completed too urgently?

**Comment by gabek** [comment]
Yeah, no huge rush! Feel free to go over to that issue and comment on it and I can assign it to you. If you happen to require any S3-compatible credentials for testing purposes feel free to message me in our [chat](https://owncast.rocket.chat/channel/general) and I can set you up.

**Comment by gabek** [comment]
Closing this, as the current details in the stream health page mostly can answer this question at a high level.
