### ISSUE TITLE
Chat join message for users with moderator flag is misaligned

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2763]
### Share your bug report, feature request, or comment.

The flag should be after the username, all on one line. "joined the chat" should be on the same line.
![image](https://user-images.githubusercontent.com/414923/222307533-447a37e8-86af-4539-acc1-2c0b1626849e.png)

Story: https://owncast.online/components/?path=%2Fstory%2Fowncast-chat-messages-chat-join--moderator

**Comment by dhanusaputra** [comment]
hi gabek, may i help with this task? thank you

**Comment by gabek** [comment]
Absolutely, thank you for your help! :)
