### ISSUE TITLE
If chat user is banned an empty chat sidebar displays

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2764]
### Share your bug report, feature request, or comment.

If chat is not valid and connected the empty chat area should not be visible. The "chat visible" selector in the client config store should probably return false if not successfully connected to chat.

![image](https://user-images.githubusercontent.com/414923/222308923-a1e56405-508d-43ef-a906-8496f705d509.png)

**Comment by Fa2112** [comment]
Hi! I would like to help if this is still unassigned :)

**Comment by gabek** [comment]
Hi @Fa2112! Thanks for volunteering to look at this, but I actually started looking it it, whoops!  Do feel free to look at other items [for this milestone](https://github.com/owncast/owncast/milestone/18) that are similar, though. Would love your help!
