### ISSUE TITLE
S3 integration fully missing in Owncast 0.1.0

### ISSUE THREAD

**Issue by rmens** [owncast/owncast#2767]
### Share your bug report, feature request, or comment.

Thought this was a front-end issue, but the url '/config-storage/' results in a `404 page not found`

<img width="984" alt="Schermafbeelding 2023-03-03 om 19 40 00" src="https://user-images.githubusercontent.com/6742496/222801370-5c40d848-1bcb-428a-8f5d-b996e14c7ea4.png">

**Comment by gabek** [comment]
Sorry about that, I thought that was added to the release notes but I don't see where it was that I wrote that down.

But a handful of things have been consolidated, so this can be found at `/admin/config/server/`.
