### ISSUE TITLE
Inconsistent hover colors in admin menu

### ISSUE THREAD

**Issue by rmens** [owncast/owncast#2770]
### Share your bug report, feature request, or comment.

Owncast 0.1.0

The admin menu has some inconsistent hover colors. There is a difference between drop down menu's and single menu items. This looks a bit weird. 

![hover](https://user-images.githubusercontent.com/6742496/222842687-5ca253f6-8cd4-4486-b552-a6c9c5b97549.gif)

**Comment by gabek** [comment]
There's an overarching umbrella issue to make the admin look less ugly in #1904 but please feel free to continue to file specific issues.

**Comment by Pranav2612000** [comment]
Working on this and having a PR ready in some time.
