### ISSUE TITLE
Set correct content-type and cache-control for S3 uploads

### ISSUE THREAD

**Issue by rmens** [owncast/owncast#2771]
### Share your bug report, feature request, or comment.

Bumped into this when figuring out why using Cloudflare R2 isn't working as it should as S3 storage.

For `.m3u8` playlists locally served, the headers are set like this:

```
cache-control: no-cache, no-store, must-revalidate
content-type: application/x-mpegURL
```

For `.m3u8` playlists served over S3, the headers are set like this:
```
cache-control: max-age=0
```
And `content-type` is not set at all. Some S3 providers like Backblaze B2 seem to guess the correct `content-type` based on the file extension, but not all do. For example Cloudflare R2 doesn't.

The `s3manager` for Go does support setting these values. I suggest making them universal for playlists and chunks served locally or over S3.

**Comment by JacobWrenn** [comment]
Hi @gabek please assign me. I will be sure to message you on the chat if I need the testing credentials.

**Comment by gabek** [comment]
Awesome, thanks!
