### ISSUE TITLE
Chat user details modal in the admin has incorrect white text

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2772]
### Share your bug report, feature request, or comment.

It should be black text like everything else.

![image](https://user-images.githubusercontent.com/414923/222874300-1bc77453-8e81-4ad1-9b31-72a65290a494.png)

**Comment by SamantaTarun** [comment]
I would like to work on this issue.

**Comment by gabek** [comment]
Awesome, thanks so much!

**Comment by SamantaTarun** [comment]
@gabek how to preview the pull request changes. Could you please send me a screenshot of the latest pr?

**Comment by gabek** [comment]
To run the admin you should follow the steps at https://owncast.online/development/ as mentioned above.

1. Run the backend `go run main.go`.
2. Run frontend `npm run dev`.
3. Visit `/admin` to see the admin.

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="https://owncast.online/favicon.png" height="14"> Owncast</div><div><strong><a href="/development/">How to work on Owncast</a></strong></div><div>The technical details for those wishing to take part in Owncast development.</div></blockquote>

**Comment by SamantaTarun** [comment]
@gabek i have tried but i managed to make it online but no user details is visible.

**Comment by SamantaTarun** [comment]
@gabek under Connected(1) but no user details is visible.

**Comment by SamantaTarun** [comment]
@gabek Do you have ntlify like preview screen of PR?

**Comment by gabek** [comment]
I'm afraid I'm not familiar with what a ntlify preview screen is. It sounds like you have it running if you're able to see the chat user count.

**Comment by SamantaTarun** [comment]
@gabek is there any other way to preview Commit after pushing?

**Comment by SamantaTarun** [comment]
@gabek count is showing 1 but no user details is visible.

**Comment by gabek** [comment]
> @gabek is there any other way to preview Commit after pushing?

You don't want to test your changes after you push them, you'll want to test them beforehand. 

I can't say I'm aware of any issue where the chat users tab isn't showing anything. If you've discovered a bug could you look into what errors are occurring for you?

**Comment by jackgris** [comment]
I think changing the color of user-details in chat.css from --theme-color-palette-4 to --theme-color-palette-0 can fix that.
I can work on that.

**Comment by SamantaTarun** [comment]
> I think changing the color of user-details in chat.css from --theme-color-palette-4 to --theme-color-palette-0 can fix that. I can work on that.

@gabek i took this issue. You can't work on it. I have been working on it since last week.

**Comment by jackgris** [comment]
Sorry, I saw that the assignment state change some hours ago, my apologies. It's true I didn't wait to be assigned. I thought you will no longer work in that. I apologize again.

**Comment by gabek** [comment]
@tarunsamanta2k20 I unassigned you since I hadn't heard anything and you seemed confused about how to test your changes. How are things going?
