### ISSUE TITLE
Strip trailing slash of S3 config serving endpoint if it's set

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2779]
### Share your bug report, feature request, or comment.

See #2138 for more details.

**Comment by thisprojects** [comment]
Hello!

Can I get this assigned to me plz?

**Comment by thisprojects** [comment]
Hmm tried to raise a PR for this on owncast/admin and got the following response "This repository has been archived by the owner on Jul 13, 2022. It is now read-only." 🤔

**Comment by rmens** [comment]
This repository is the whole of Owncast. There is no more separate admin.

**Comment by thisprojects** [comment]
Ahhh cool - tnx. Have created this PR for the issue - https://github.com/owncast/owncast/pull/2788.
Hopefully this is what was expected 😄.
