### ISSUE TITLE
Corner radius slider no longer slides

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2781]
### Share your bug report, feature request, or comment.

It just stays in the same place when trying to move it.

This is under General -> Appearance in the admin.

![image](https://user-images.githubusercontent.com/414923/223336620-9cd032f7-f28d-444b-a150-a730ae9f4d4c.png)

**Comment by dhanusaputra** [comment]
hi gabek, may i help with this? thanks

**Comment by gabek** [comment]
Absolutely, thanks so much!
