### ISSUE TITLE
Dragging color selector automatically closes selector

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2782]
### Share your bug report, feature request, or comment.

Each time you move the color selector it closes the color picker entirely and doesn't let you continue dragging to pick your desired color.

This can be found under General -> Appearance

![image](https://user-images.githubusercontent.com/414923/223337263-465c952f-38fd-437f-a485-6ea860102d49.png)

**Comment by Pranav2612000** [comment]
Working on this. Will have a PR soon.
