### ISSUE TITLE
Admin interface renders before authentication

### ISSUE THREAD

**Issue by rmens** [owncast/owncast#2789]
### Share your bug report, feature request, or comment.

When opening the Owncast `/admin/` page I noticed that the whole interface is rendering before authentication. If I cancel on the authentication prompt, it goes to show an error.

I don't think any data is exposed, but it is strange. I could reproduce this in Safari, Chrome and Firefox. In a private window, to make sure there is nothing cached.

![owncast admin 2023-03-10 19_32_27](https://user-images.githubusercontent.com/6742496/224396527-eb97f481-7ac1-4251-a23b-2e37246b2e71.gif)

Owncast v20230310-nightly

**Comment by gabek** [comment]
Is it actually rendering current data, or is that just cached old content in your browser? If you open the admin a private browsing tab does it do the same thing?

**Comment by rmens** [comment]
I specifically tried this in private browsing tabs in different browsers. It's also in my screen recording, but that's in Dutch so maybe it wasn't clear.

**Comment by gabek** [comment]
Super odd, the opposite is for me. What browser? Thanks for filing.

![image](https://user-images.githubusercontent.com/414923/224403388-e79142a2-60e2-4ef8-bb24-2eb0cbb5e4d0.png)

**Comment by gabek** [comment]
As an additional data point I tried with Firefox as well and it seems to function as expected.

![image](https://user-images.githubusercontent.com/414923/224404881-53e25e4b-fb8e-4182-9ab2-4006ac81c068.png)

**Comment by rmens** [comment]
This is strange. I can't reproduce this on watch.owncast.online in Safari, Chrome and Firefox on macOS. All in private tabs. But can reproduce it on my instance. That's Owncast Nightly running in Docker and Caddy outside of docker.

Can you try the instance in my screen recording?

**Comment by gabek** [comment]
I dug a little deeper, and specifically only with webv2/v0.1.0 if you access /admin/stream-health/ (but probably other pages that aren't just /admin) it will try to load it before throwing a client error.
