### ISSUE TITLE
Typo in disable viewer count toggle

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2792]
### Share your bug report, feature request, or comment.

Should say "viewer count on the web page".

![image](https://user-images.githubusercontent.com/414923/224464377-47fc0019-7cd8-4240-a620-13f5c5020386.png)

**Comment by Rehan-stack** [comment]
hi, i am interested to work on this issue.

**Comment by Rehan-stack** [comment]
I am willing to work on this isue. Plz Assign this issue to me.
