### ISSUE TITLE
Webhook for stream title change

### ISSUE THREAD

**Issue by Chippit** [owncast/owncast#2795]
### Share your bug report, feature request, or comment.

Currently there is no webhook able to respond to stream title changes. This information is included in the webhooks for starting and ending a stream, but if the title changes while a stream is running, a third party app has no way of knowing.

**Comment by gabek** [comment]
Seems like a reasonable thing to add.

**Comment by Pranav2612000** [comment]
Hey @gabek I'll like to work on this issue.
I'm guessing we already have webhooks for starting and ending the stream, I can refer those on how the webhook is to be created right? Any other docs or code you think is relevant?

**Comment by gabek** [comment]
Awesome, thank you! And yeah, there's a handful of webhooks that already exist.  [Here](https://github.com/owncast/owncast/blob/develop/core/webhooks/stream.go#L17-L26) is the stream status webhook that already sends along the stream title and [here's](https://github.com/owncast/owncast.github.io/blob/master/content/thirdparty/webhooks.md) the documentation around the webhooks that already exist and would need to be updated with a new one.

**Comment by luckydonald** [comment]
Probably they should be fired for [`streamTitle` and `summary`](https://github.com/owncast/owncast.github.io/blob/master/content/thirdparty/webhooks.md#stream_started) changes as well.

**Comment by gabek** [comment]
This is for the stream title. I don't think it should be fired for summary, that's not a value that's seen as an attribute of the current stream, that's just the description of the server itself. A separate server metadata webhook could be created, but that's not what this is.
