### ISSUE TITLE
Additional CSS IDs needed for elements

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2797]
### Share your bug report, feature request, or comment.

IDs need to be added in order to select specific elements for customization via CSS.

- Bottom page content
- Status bar
- Chat message

(Will grow as I discover other elements)

**Comment by thisprojects** [comment]
Heya @gabek I'd like to work on this one, can I get assigned plz? 😃

**Comment by gabek** [comment]
Absolutely! I was planning on adding to this list however, since right now there's only one element that I added. I was planning on going through and finding additional major components that would need to be customized by users and make sure they have IDs assigned. Right now the list of IDs available for CSS overrides are here:

https://github.com/owncast/owncast.github.io/pull/107/files#diff-44d3e4bc62f490fade80e188d5f93638cb70e2671ef5831fdd8eb017a669100a

<blockquote><img src="https://avatars.githubusercontent.com/u/414923?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/owncast/owncast.github.io/pull/107">Release v0.1.0 by gabek · Pull Request #107 · owncast/owncast.github.io</a></strong></div><div>To be merged in when v0.1.0 is released.
owncast/owncast#2431</div></blockquote>

**Comment by thisprojects** [comment]
Thanks Gabe 👍

**Comment by gabek** [comment]
I was hoping more people would try customizing the v0.1.0 UI and there'd be feedback like "I want to change the color of X but it doesn't have an ID" but I don't think people are trying that, so I haven't heard anything back. This list hasn't grown like I expected it to. I'm going to remove it out of this milestone since it doesn't seem to be a blocker if it's not blocking anybody.

**Comment by valvin1** [comment]
oh i was on something like this while testing embed chat in OBS with nightly version. css provided [here](https://owncast.online/docs/embed/#using-obs) is not working.

i tried with low css skill to find the good one but only succeed in solving background-color, font-size doesn't apply:

```
#chat-container {
   margin: 0px;
   padding: 20px;
  background-color: rgba(0,0,0,0.5);
   font-size: 24px;
   }
```

**Comment by gabek** [comment]
Hey there. You mentioned the chat container font size isn't changing, but I'm a little confused because the container is just a container, it doesn't have any text in it. Are you trying to change the font size of the chat messages themselves? Did you try adding CSS for the messages?

If I'm interpreting your issue incorrectly I apologize, feel free to add more detail.

**Comment by valvin1** [comment]
i was trying to embed chat in my stream using OBS. so I followed the documentation. Initial css doesn't change anything because it is:

```css
   html {
   margin: 0px;
   padding: 20px;
   background-color: rgba(0,0,0,0.5);
   font-size: 24px;
   }
```

so after digging in firefox I saw it was because css was now different and found to change background-color I had to target the container `#chat-container`.

then after I tried to increased font-size. It didn't work on container level. I saw it was in a div.div.div.span using a generated class which I think is changing regularely. but as I'm really bad at css things I give-up.

so maybe it misses a css ID to target the text span directly ?

**Comment by gabek** [comment]
Added chat message to the list.

**Comment by anniepauline** [comment]
Willing  to work on the issue!

**Comment by gabek** [comment]
Thanks for chiming in! I'm actually going to close this issue, since I'm not sure if there are any additions that still need to be made, and if they need to be, I'll open indidivual issues.
