### ISSUE TITLE
automatic installion problem

### ISSUE THREAD

**Issue by doggies45** [owncast/owncast#2798]
### Share your bug report, feature request, or comment.

everytime i try to do the automatic install this error happens for me

nzip: cannot find or open /tmp/tmp.AbB7L2EQxB/[owncast-0.0.13-linux-64bit.zip](http://owncast-0.0.13-linux-64bit.zip/), /tmp/tmp.AbB7L2EQxB/[owncast-0.0.13-linux-64bit.zip.zip](http://owncast-0.0.13-linux-64bit.zip.zip/) or /tmp/tmp.AbB7L2EQxB/[owncast-0.0.13-linux-64bit.zip.ZIP](http://owncast-0.0.13-linux-64bit.zip.zip/).
Your Owncast installation did not complete successfully.
Please report your issue at https://github.com/owncast/owncast/issues

**Comment by gabek** [comment]
I was just able to verify that the installer is working as expected. Could you provide any details about why it may not be working specifically for you? Perhaps something in your environment that may be different?

**Comment by doggies45** [comment]
Do you think my Thinkpad Laptop might be a 32bit laptop then, that might be causing the automatic installer not to work then, so is there anyway you make a 32bit automatic installer then?

**Comment by gabek** [comment]
The installer detects 32 bit architectures.

**Comment by doggies45** [comment]
i tried everything to make the automatic installer work for me on thinkpad laptop, i installed ffmpeg on it and i updated everything else on it, and it still goes to that unzip error when i do the automatic installer

**Comment by doggies45** [comment]
it keeps on saying that can't find those files anywhere on that automatic installer script

**Comment by doggies45** [comment]
i tried everything to make this work

**Comment by doggies45** [comment]
it worked fine for me on virtualbox but not on my thinkpad laptop

**Comment by doggies45** [comment]
all i wanted was a safe place for me to stream on my own

**Comment by doggies45** [comment]
I got owncast installed now, but i do not know how to make my owncast work on my acer laptop as well how can i make my owncast seen on my acer laptop from my thinkpad laptop
