### ISSUE TITLE
Nitpicky detail: resolution placeholders aren't 16x9

### ISSUE THREAD

**Issue by rmens** [owncast/owncast#2799]
### Share your bug report, feature request, or comment.

In the admin screen: Video > Resolution > Add new variant > Advanced > Resolution

The placeholder suggests 1080x720. That's 3x2. Not a normal video aspect ratio. I suggest making it 1280x720, which is 16x9.

<img width="430" alt="Schermafbeelding 2023-03-11 om 23 50 31" src="https://user-images.githubusercontent.com/6742496/224514911-1082fffc-f376-4cf3-b506-87ba06264902.png">

**Comment by Rehan-stack** [comment]
hi, i am interested to work on this issue. Plz assign this to me.

**Comment by gabek** [comment]
Thanks!
