### ISSUE TITLE
Loose div in Utilities > Stream health screen

### ISSUE THREAD

**Issue by rmens** [owncast/owncast#2804]
### Share your bug report, feature request, or comment.

Not sure what this one's doing here

<img width="1554" alt="Schermafbeelding 2023-03-12 om 14 16 14" src="https://user-images.githubusercontent.com/6742496/224547122-48cd3820-b51f-4cb4-9f1e-44217a889015.png">

**Comment by gabek** [comment]
I had originally pushed this off until v0.1.1 but given some bigger issues for v0.1.0 are still blockers there's probably still time to get smaller things in without pushing out the milestone.

**Comment by dhanusaputra** [comment]
hi, can i help with this please, thank you

**Comment by gabek** [comment]
Of course, thank you!
