### ISSUE TITLE
Viewer graph should always use 0 as minimal value

### ISSUE THREAD

**Issue by rmens** [owncast/owncast#2806]
### Share your bug report, feature request, or comment.

When there haven't been any viewer yet, the graph shown in the admin at the Viewer Info screen allows for negative values. There can't be -1 viewers.

<img width="1483" alt="Schermafbeelding 2023-03-12 om 14 23 59" src="https://user-images.githubusercontent.com/6742496/224547741-f7bee4f1-114b-4ccf-8e42-a84fa202b0a6.png">

This seems to correct itself after there has been a viewer. 

<img width="1226" alt="Schermafbeelding 2023-03-12 om 14 25 43" src="https://user-images.githubusercontent.com/6742496/224547770-fe376b0b-0037-45be-b711-11f333ed0dca.png">

It would be better to always only show 0 at the bottom of the graph. Even after there haven't been any viewers yet.

**Comment by gabek** [comment]
I had originally pushed this off until v0.1.1 but given some bigger issues for v0.1.0 are still blockers there's probably still time to get smaller things in without pushing out the milestone.

**Comment by gabek** [comment]
The reason this hasn't been done before is because I thought it looked weird with the bottom being the _very_ bottom, making it possible for line to almost be hidden since there's nothing underneath it. However if this is less confusing than it is now I'll make the change.

![image](https://user-images.githubusercontent.com/414923/224849028-f0afaec2-eb3a-4406-a013-f2e022b6bfd9.png)

**Comment by rmens** [comment]
It looked like an error at first. But actually starting with 0 at the very bottom looks like even more of an error 🤔

**Comment by jackgris** [comment]
Maybe adding `clip: false` in the options added in Chart.tsx? 
```javascript 
  const options = {
    responsive: true,

    scales: {
      y: {
        type: yLogarithmic ? ('logarithmic' as const) : ('linear' as const),
        reverse: yFlipped,
				min: minYValue,
				ticks: {
					stepSize: yStepSize,
				},
        title: {
          display: true,
          text: unit,
        },
      },
    },
		clip: false,
  };
```
With that, looks like this:
![owncast Screenshot_20230313_204254](https://user-images.githubusercontent.com/2231462/224856720-9348f0f5-e20d-4191-945f-a2dbc5239984.png)

That's the only thing I added to the code you shared.

And this is with one viewer:

![owncast Screenshot_20230313_205631](https://user-images.githubusercontent.com/2231462/224857751-aa73f6e5-b716-4572-ba37-2c1c16212aaa.png)

**Comment by gabek** [comment]
That looks much better and is easily visible! I'll throw that in there quick, thanks for the suggestion!
