### ISSUE TITLE
Menu state in admin not saved after page refresh

### ISSUE THREAD

**Issue by rmens** [owncast/owncast#2807]
### Share your bug report, feature request, or comment.

Open a page that's behind a drop down menu. For example Hardware info and refresh the page in your browser. All the menu's are collapsed and you current place in Owncast is no longer highlighted.

![owncast-menu](https://user-images.githubusercontent.com/6742496/224548116-f769f6db-43a6-42a1-b043-ad2b12dcc42e.gif)

**Comment by gabek** [comment]
This is probably more effort than it's worth, but if somebody wants to look at it please do! The menu collapse state would probably have to be pushed into URL query parameters and then be read when rendering the sidebar to determine if certain sections are open or closed. The highlight state of menu items can probably be derived from the URL path itself.

Maybe there's an easier approach, though!

**Comment by dhanusaputra** [comment]
hi, can I help with this? thanks

**Comment by gabek** [comment]
Absolutely, thank you! :)
