### ISSUE TITLE
Windows: when I run owncast code I got this error

### ISSUE THREAD

**Issue by henish1400** [owncast/owncast#2814]
### Share your bug report, feature request, or comment.

![image](https://user-images.githubusercontent.com/102351385/224629690-50c2a0b0-3c17-4c54-8148-dc5234759efc.png)

**Comment by gabek** [comment]
I'm not familiar with your environment, but that error says that cgo is disabled. cgo is required for Owncast to run.

**Comment by henish1400** [comment]
so how can I enable cgo?

**Comment by gabek** [comment]
What research did you do on the topic? I don't use Windows, I won't be able to answer your questions about Windows-specific build issues.

**Comment by gabek** [comment]
Closing since this is not an Owncast issue.
