### ISSUE TITLE
reduce latencey question

### ISSUE THREAD

**Issue by doggies45** [owncast/owncast#2816]
How can i reduce the Latencey and the delay on owncast by only 2 or seconds

**Comment by rmens** [comment]
I wouldn't expect anything below 6 seconds. Have you tried bringing the latency buffer all the way down in the admin interface? Also read this: https://owncast.online/docs/video/#latency-buffer

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="https://owncast.online/favicon.png" height="14"> Owncast</div><div><strong><a href="/docs/video/">Video</a></strong></div><div>Configure your video to manage the quality and hardware performance.</div></blockquote>

**Comment by gabek** [comment]
You can also optionally experiment with the low latency player mode that's in the player settings menu. It's not supported for all browsers and the viewer needs to have fast access to the video. But Owncast isn't built for sub-second latency for a number of reasons.
