### ISSUE TITLE
I got this issue, when i run code

### ISSUE THREAD

**Issue by henish1400** [owncast/owncast#2822]
### Share your bug report, feature request, or comment.

![image](https://user-images.githubusercontent.com/102351385/225007528-1c1a4342-9152-42d3-a039-4b197609bda3.png)

**Comment by rmens** [comment]
Run `whereis ffmpeg` and tell us the output please.

**Comment by henish1400** [comment]
![image](https://user-images.githubusercontent.com/102351385/225008285-70d88df1-2690-4a19-aacd-94cd9e55675c.png)

**Comment by henish1400** [comment]
what dose I next?

**Comment by rmens** [comment]
You don't have ffmpeg installed. Which is required for Owncast.

Do you have [homebrew](https://brew.sh/) installed? If you have, it's as simple as `brew install ffmpeg`

**Comment by henish1400** [comment]
no i don't have homebrew.

**Comment by henish1400** [comment]
![image](https://user-images.githubusercontent.com/102351385/225009433-5dc686c9-f027-4d6e-be4b-a019b6c4501a.png)

**Comment by rmens** [comment]
You should consider installing homebrew. It's a great tool for developers on Mac. There are instruction on the hombrew website.

If you don't want homebrew, you need to install ffmpeg on your Mac manually. I just do it via Homebrew so can't help you with the manual install of ffmpeg on Mac.

**Comment by henish1400** [comment]
how can I install homebrew?

**Comment by rmens** [comment]
Follow the instruction on https://brew.sh

<blockquote><img src="https://brew.sh/assets/img/homebrew-social-card.png" width="48" align="right"><div><img src="/assets/img/favicon.ico" height="14"> Homebrew</div><div><strong><a href="https://brew.sh/">Homebrew</a></strong></div><div>The Missing Package Manager for macOS (or Linux).</div></blockquote>

**Comment by henish1400** [comment]
![image](https://user-images.githubusercontent.com/102351385/225010768-d2a68c0a-6c91-4701-948a-93e8aea74864.png)


when i install homebrew I got this error.

**Comment by henish1400** [comment]
any buddy there?

**Comment by gabek** [comment]
Have you looked into "how to install ffmpeg on a mac"?  There are a ton of search results. It's an exceptionally common tool to have installed. The Owncast installer will download a copy for you, but if you're running the source code manually it's up to you to make sure you have dependencies met. https://github.com/owncast/owncast#backend

<blockquote><img src="https://repository-images.githubusercontent.com/266445736/4f82fb80-a5b1-11ea-8f1c-69d316f861b5" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/owncast/owncast">GitHub - owncast/owncast: Take control over your live stream video by running it yourself.  Streaming + chat out of the box.</a></strong></div><div>Take control over your live stream video by running it yourself.  Streaming + chat out of the box. - GitHub - owncast/owncast: Take control over your live stream video by running it yourself.  Stre...</div></blockquote>
