### ISSUE TITLE
Hey, guys, i found broken link in Docs, fix please

### ISSUE THREAD

**Issue by jahlib** [owncast/owncast#2827]
### Share your bug report, feature request, or comment.

Here: https://owncast.online/docs/systemservice/

This link is broken and shows github 404 page:
https://github.com/owncast/owncast/blob/master/examples/owncast-sample.service

**Comment by gabek** [comment]
There's an example in https://github.com/owncast/owncast/tree/develop/contrib but I'm not sure it should be linked directly to our documentation as the `contrib` directory isn't supported or endorsed, it's just examples.

<blockquote><img src="https://repository-images.githubusercontent.com/266445736/4f82fb80-a5b1-11ea-8f1c-69d316f861b5" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/owncast/owncast">owncast/contrib at develop · owncast/owncast</a></strong></div><div>Take control over your live stream video by running it yourself.  Streaming + chat out of the box. - owncast/contrib at develop · owncast/owncast</div></blockquote>

**Comment by rmens** [comment]
There was a lot more removed. Not just the broken link but also the example. This doc now doesn’t make a whole lot of sense.

**Comment by gabek** [comment]
I'm not sure how to have an example without supporting the example. I left a couple lines but the entire example should probably be removed.
