### ISSUE TITLE
Install bash script: Figure out actual linux + architecture ffmpeg binary to download

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#283]
If ffmpeg is not found on the machine the script will download a binary for you.  Right now it's hardcoded to `linux-x64`.  That's probably accurate for _most_ people, but I'm not sure about ARM-based machines and the like.

https://github.com/owncast/owncast.github.io/blob/master/static/install.sh#L43

Once this is fixed the script is probably usable for most people.

@geekgonecrazy @jmhobbs Do you have ideas on what the most accurate way to determine the architecture for linux binaries from the shell might be?  I've seen some approaches, but they either seem to differ based on distribution or feel brittle.

Also, as an aside, I kind of just threw together this script without putting a lot of thought into structure.  If anybody wants to improve on it, go for it!

**Comment by geekgonecrazy** [comment]
I was hoping I had some prewritten examples.  But closest I could find was distro detection.

https://github.com/RocketChat/install.sh/blob/master/rocketchatctl#L207

https://github.com/RocketChat/Rocket.Chat/blob/develop/.snapcraft/resources/preparemongo#L3 - uname is the only other that comes to mind

**Comment by jmhobbs** [comment]
Yeah, my experience has always been using `uname`.

**Comment by jmhobbs** [comment]
@gabek I got poking at this and think I have a working version I can PR in.  However the 0.0.2 linux release of Owncast is x86-64.  Can you attach a build on there for 32 bit?  If there is a predictable filename pattern for architecture I can add that in too.

**Comment by gabek** [comment]
You have a good point, why am I so concerned about downloading the correct version of ffmpeg if we don't have a build of Owncast for it haha.

But yeah, we should totally support linux 32 bit if that makes sense.  I've been using xgo for cross-compilation and it [supports all the expected architectures](https://github.com/karalabe/xgo#limit-build-targets) so I'll go ahead and [update our build script](https://github.com/owncast/owncast/blob/master/scripts/build.sh#L8).

The filename pattern of `owncast-platform-arch` probably makes sense.

Right now we just have `owncast-linux-0.0.2.zip` but we can extend that to `owncast-linux-386-0.0.2.zip` or `owncast-linux-amd64-0.0.2.zip`.  And while we probably don't need to support 32 bit macOS we can still specify `owncast-macOS-amd64-0.0.2.zip`.  Let me know if there's something clearer.

**Comment by gabek** [comment]
Added 32 bit builds for linux.  I figured saying "32bit" and "64bit" was nicer than "amd64" and "386".

```
owncast-0.0.3-linux-32bit.zip owncast-0.0.3-linux-64bit.zip owncast-0.0.3-macOS-64bit.zip
```

**Comment by gabek** [comment]
@jmhobbs made a bunch of nice updates and it's ready to go when 0.0.3 is ready!  https://github.com/owncast/owncast.github.io/pull/7

Closing this since there's nothing more to do.
