### ISSUE TITLE
Follower pagination does not work

### ISSUE THREAD

**Issue by ghost** [owncast/owncast#2835]
### Share your bug report, feature request, or comment.

Unfortunately, clicking the buttons does not switch to the next page of followers.
So, it only shows the first page

<img width="286" alt="Screenshot 2023-03-16 at 14 40 45" src="https://user-images.githubusercontent.com/115697763/225653097-4bf791cd-e1b5-4878-97d8-47a549ff74af.png">

**Comment by gabek** [comment]
Well that's unfortunate, something changed there. Thanks for letting me know!

**Comment by ghost** [comment]
Thanks for the quick fix.
But there seems to be still something broken with the follower view.

1. It only shows 25 of 49 total followers
2. On page 3, it shows the "no followers" page and removes the pagination tabs

Guess the 1st one causes the 2nd issue because the page count could be correct if all of the followers would actually show up.


https://user-images.githubusercontent.com/115697763/226108650-9f5b04e0-fca2-4450-a622-0547a3d1a840.mov

**Comment by ghost** [comment]
Or to put it in other words,
there is an offset of one page

**Comment by gabek** [comment]
Hopefully it's fixed up now. Let me know if you're still running into pagination issues.
