### ISSUE TITLE
Support outbound account migration requests

### ISSUE THREAD

**Issue by ghost** [owncast/owncast#2846]
### Share your bug report, feature request, or comment.

It would be great to have a migration feature for your owncast instance.

So, you can migrate your followers whenever you change the domain or move to a different instance/installation.

**Comment by gabek** [comment]
You can move your data to another server by simply copying your `data` directory to your new server.

**Comment by ghost** [comment]
@gabek I talk about the fediverse integration.
When you move your installation to a different domain, you can move your data folder for sure.

But your followers do not know about that. They still follow the old domain.

**Comment by gabek** [comment]
I'm sure there's circumstances where you want to keep your server but change your domain, but that's not something I'm looking to support. It's not like Mastodon where you are moving to another person's server. Your owncast server is your server.
