### ISSUE TITLE
pop-out chat button

### ISSUE THREAD

**Issue by nononymousse** [owncast/owncast#2848]
It will be nice to have a pop-up chat button on the stream page

I know pop-up chat already exist in the form of the embed read-write chat but putting a button at the bottom of the chat or on the rolling menu at the top on the stream page is way more user-frendly (and as a user, you don't have to go dig into the documentation to even know it is possible to have one. And even then, it's not really user-frendly imo to modify the URL to have that function)

like as a user, i use it a lot on twitch to put the chat on another screen and have the video feed in fullscreen on another screen

**Comment by gabek** [comment]
What would be in this new chat interface? What do you mean by the "rolling menu"?

**Comment by nononymousse** [comment]
this new chat interface could be the embed read-write chat that already exist but in a single windows like on this image [01]. And by the rolling menu i mean the menu on the top left of the stream page, where you can change your nickname and login.

[01]
![image](https://user-images.githubusercontent.com/32956707/226146546-8185cacb-85be-445c-af23-83141d21e7a0.png)

**Comment by nononymousse** [comment]
Also a really good use case too : one screen and i'm able to have the chat, watch the stream (pop-up video player of Firefox) and something else on the screen. Really good use of screen real estate
![image](https://user-images.githubusercontent.com/32956707/226378655-f103faba-ae3b-4f1a-a5ad-81c8a0f1f135.png)

**Comment by gabek** [comment]
Is this different than the chat embed interface?

**Comment by nononymousse** [comment]
nope but like i said in the first message, it's about being more frendly than digging into the doc to see that this function exist and that you have to custom the URL for that

the button can detect the instance it's on and "generate" the URL to open a new small window with the embed read/write chat in it

**Comment by janWilejan** [comment]
assign me this please
