### ISSUE TITLE
Cannot start stream

### ISSUE THREAD

**Issue by anegadian** [owncast/owncast#2849]
### Share your bug report, feature request, or comment.

Everything was working fine for a while. Then, with no configuration changes. Then, for some reason, the input stream was disconnected.

When I attempt to restart the stream, I get the following messages in the log:
_Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options_
and
_[flv @ 0x5591479f1d00] Could not find codec parameters for stream 1 (Video: h264, none, 100000 kb/s): unspecified size_

**Comment by gabek** [comment]
I know you mentioned nothing changed, but it seems like something did. When you say "fine for a while", how long is a while? Minutes or months? Are you able to fix it by making any configuration changes? Does a default configuration work? Any detail you could provide would be helpful.

**Comment by anegadian** [comment]
Thanks for your quick response. 

I changed nothing, waited a while, and was able to start the stream. I'm
thinking it is an issue with the software that is pushing to my owncast
server. I am using Agent DVR to transcode from the RTSP camera stream to
the RTMP stream. It seems to be buggy. 

Close this issue for me - I don't think it is a problem with owncast.
owncast seems to be rock solid. 

On 2023/03/19 17:15, Gabe Kangas wrote:

> I know you mentioned nothing changed, but it seems like something did. When you say "fine for a while", how long is a while? Minutes or months? Are you able to fix it by making any configuration changes? Does a default configuration work? Any detail you could provide would be helpful. 
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
> You are receiving this because you authored the thread.Message ID: ***@***.***>

 

Links:
------
[1]
https://github.com/owncast/owncast/issues/2849#issuecomment-1475399470
[2]

**Comment by gabek** [comment]
Will do, hope you're able to track it down!
