### ISSUE TITLE
[feature request] log hits to api endpoints

### ISSUE THREAD

**Issue by compufox** [owncast/owncast#2857]
currently owncast does not provide access logs whenever web routes are hit, not even when "verbose logging" OR "debug features" are enabled. 

this could be hidden behind another command line flag, but i think this would be extra helpful for devs trying to build stuff on top of owncast.

**Comment by gabek** [comment]
What would the use case of this be? It seems like if you're building external tooling it would be easier for you to log the requests you're making than to log *every* request that Owncast receives.

**Comment by compufox** [comment]
this would be more for local debugging/testing than for use in some production environment.

**Comment by rmens** [comment]
This might be something a reverse proxy is better equipped to handle imho. With the current resourcing this doesn't feel like something that belongs in Owncast core.
