### ISSUE TITLE
In some layouts the header bar logo disappears, but leaves a gap

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2858]
### Share your bug report, feature request, or comment.

![image](https://user-images.githubusercontent.com/414923/226955267-0cbfe14c-2675-438d-97a1-f92748911c4f.png)

https://owncast.online/components/?path=%2Fdocs%2Fowncast-layout-main--offline-mobile

**Comment by gabek** [comment]
This seems to happen when you have a layout, make it narrower, and then restore to the original layout.

**Comment by dhanusaputra** [comment]
it seems only happens in storybook? after move to `Canvas` and get back to `Docs`
svg is not loaded
it's ok again after refresh the storybook
[vid](https://user-images.githubusercontent.com/35093673/227860653-8266755a-fcfd-42d9-891a-253c2f205878.webm)


not able to replicate on website

**Comment by gabek** [comment]
Good catch! I was testing in storybook when I filed this. Thanks for looking!
