### ISSUE TITLE
Storybook layout stories try to make websocket connections

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2862]
### Share your bug report, feature request, or comment.

Obviously there's no server to connect to.

![image](https://user-images.githubusercontent.com/414923/227051634-c8caaca5-d8f2-4e73-a37a-2a6b6b84640c.png)

**Comment by Pranav2612000** [comment]
I can give this a go. We would need to create a mock of the websocket-service.ts and use it in the Main.stories component. Right?
Similar to the way it's been done for other mocks on the page like chatService

**Comment by gabek** [comment]
Nice, thank you!

I'd prefer we didn't have to add mocks since they add a ton of complexity by requiring the rearchitecting of the components and wrapping them in new services. There's no additional functionality here that we're trying fake, so mock services would just be an extra maintenance burden into the future. That being said, I haven't looked into it, so I don't know the answer offhand. Fewer things is always better, though. It would be nice if it could be as easy as just not bringing int the `ClientConfigStore` component, since it is what connects to the websocket, not the layout.
