### ISSUE TITLE
Update Owncast developer documentation to mention Windows

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2864]
### Share your bug report, feature request, or comment.

A few Windows users have asked how to work on Owncast recently and I've been unable to answer the question, since I haven't touched Windows in a very long time.

I believe people are using the Windows Subsystem for Linux to do development, but I don't know the specifics and haven't used it myself.

I'd love if somebody who *does* use Windows and has a development environment for Owncast could add a section to our [README](https://github.com/owncast/owncast/blob/develop/README.md) and [developer doc](https://owncast.online/development/) for working on the frontend and backend of the project.

Thanks for any help somebody could provide!

**Comment by dev265545** [comment]
Hi! I would like to work on this issue. I have installed and used Owncast using WSL.

**Comment by gabek** [comment]
Awesome, thank you!
