### ISSUE TITLE
[feature request] include moderator status in "user" json structure

### ISSUE THREAD

**Issue by compufox** [owncast/owncast#2865]
currently the "user" data structure sent via webhook includes if the user is a bot, or if the user is authenticated but there's nothing to indicate if the user is a moderator.

**Comment by gabek** [comment]
You'll find it under the "scopes" property, that holds attributes about the user.

```
{"type":"USER_JOINED","eventData":{"id":"3ckcyOBVR","timestamp":"2023-03-23T12:28:42.910140429-07:00","user":{"id":"xUpDsdf4g","displayName":"flamboyant-hawking","displayColor":1,"createdAt":"2023-03-23T12:27:17.266410489-07:00","previousNames":["flamboyant-hawking"],"nameChangedAt":"0001-01-01T00:00:00Z","scopes":["MODERATOR"],"isBot":false,"authenticated":false}}}
```

**Comment by compufox** [comment]
Ah okay. the [webhook documentation page](https://owncast.online/thirdparty/webhooks/) does not reflect this.
