### ISSUE TITLE
Channel logo is used as placeholder avatar

### ISSUE THREAD

**Issue by ghost** [owncast/owncast#2869]
### Share your bug report, feature request, or comment.

For followers who do not have an avatar image, the channel logo is displayed as an avatar.

I am not sure if this is a bug or a feature.
I think it's a bit irritating to see my own avatar image, which I uploaded as a custom logo, on other users.

In the old version, the owncast logo was used as a placeholder, not the custom logo.
I would suggest doing the same again or alternatively using another placeholder image.

**Comment by gabek** [comment]
It had recently been changed to just a letter. https://owncast.online/components/?path=%2Fdocs%2Fowncast-components-followers-followers-collection--no-followers

<blockquote><div><strong><a href="https://owncast.online/components/?path=%2Fdocs%2Fowncast-components-followers-followers-collection--no-followers">Webpack App</a></strong></div></blockquote>
