### ISSUE TITLE
Cannot save auto-generated stream keys

### ISSUE THREAD

**Issue by Puddinghat** [owncast/owncast#2874]
### Share your bug report, feature request, or comment.

Hello,

I wanted to try out the new release a bit before release and thus compiled the current develop-branch with an empty state (brand new container).

I noticed that when trying to add a new stream-key, a random one gets generated for you. On the latest Chrome (on Mac), if you use this key without changing it at all, it appearantly does not get saved or maybe saves an empty key. Clicking on "copy" just copies either stars or nothing. Clicking on the eye just makes the row vanish.

Otherwise, thank you for a very nice looking release candidate so far :)

**Comment by gabek** [comment]
Thanks for reporting!
