### ISSUE TITLE
Add new webhook STREAM_TITLE_UPDATED to documentation

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2879]
### Share your bug report, feature request, or comment.

Update https://owncast.online/thirdparty/webhooks/ to included the new webhook `STREAM_TITLE_UPDATED`.

Re: https://github.com/owncast/owncast/pull/2823

**Comment by dev265545** [comment]
Hey, Can I work on this issue ?

**Comment by gabek** [comment]
Absolutely, thank you! :)
