### ISSUE TITLE
Current stream status in webhooks

### ISSUE THREAD

**Issue by Chippit** [owncast/owncast#2881]
Related to a change recently made by #2823, it would be useful for webhook-consuming applications to get the authoritative stream status from the server as part of webhook messages not related to the stream starting/ending, as it is would be more reliable than requiring these applications to maintain their own state based on stream start/end webhooks.

_Originally posted by @Chippit in https://github.com/owncast/owncast/issues/2823#issuecomment-1487440337_

**Comment by gabek** [comment]
Could you provide a list of what webhooks you think should have have stream status?

**Comment by Chippit** [comment]
I think this is probably the only one. As I look through the list, this is the only one really relating to the stream itself (that isn't the start/stop webhook, which already tells you the state). The rest are all for chat.

FWIW I don't use chat on my instance so I don't know whether it's possible to send messages when the stream is offline. I guess if it is, then the chat ones make sense too.

**Comment by gabek** [comment]
What one is "this one"? There are a bunch of different webhooks, what one are you talking about?

**Comment by Chippit** [comment]
Oh! Right, sorry, that context is all in the linked ticket. I mean the 'stream title changed' webhook.

**Comment by gabek** [comment]
Got it. While I totally don't see any problem adding to any particular webhook, I do think it's a slippery slope once you start adding data that doesn't have anything to do with the webhook event itself. Technically the only information applicable to a "stream title changed" is the new stream title. And it's not a huge deal to say "ok, let's give the detail about the stream itself", but there's nothing stopping people from thinking the entire config should also get sent since we're already adding random things for convenience.

Anybody have any thoughts?

**Comment by Chippit** [comment]
I, for one, have no strong counterargument, you make valid points. If we assume perfect network conditions, then an application would have the necessary state it needs to make informed decisions given the arrival of other webhooks.

I might only make the somewhat weak point that I think the stream status _is_ relevant to the title changed webhook only because I anticipate applications that might want to notify people that the title has changed only while a stream is running, and not that it has changed in preparation of a stream that is about to start (where, for example, the stream title would not be visible in the web interface either). But once again, the other webhooks could provide the necessary information, or hitting some other formal API.

Given that, I'm happy to consider the ticket obsolete if nobody else has any other points to make.
