### ISSUE TITLE
Admin custom CSS area forces entire page to scroll

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2886]
### Share your bug report, feature request, or comment.

I think the code editor itself should be allowed to scroll horizontally, but not force the entire page to overflow and force horizontal scrolling.

![image](https://user-images.githubusercontent.com/414923/229259567-78a7a2af-9ae8-4527-98a9-b2e7efdf9092.png)

**Comment by dev265545** [comment]
hey, can work on this issue ?

**Comment by gabek** [comment]
Absolutely, thank you!
