### ISSUE TITLE
Admin appearance page has one differently colored collapsible area

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2893]
### Share your bug report, feature request, or comment.

They should all look the same.

![image](https://user-images.githubusercontent.com/414923/229301448-ff3e033b-4b00-4732-8561-fc4e8c223eae.png)

**Comment by ArslanYM** [comment]
Can i fix this ?

**Comment by gabek** [comment]
Absolutely, thanks so much!

**Comment by ArslanYM** [comment]
On it

**Comment by dev265545** [comment]
@ArslanYM  you can look at `static\web\styles\admin\home.css` and `public\web\styles\admin\home.css` where you will find 
`.ant-collapse > .ant-collapse-item:last-child,
.ant-collapse > .ant-collapse-item:last-child > .ant-collapse-header  
`
This is where the background color is coming from. You can correct this if it does not change any other thing.

**Comment by ArslanYM** [comment]
@dev265545   I am not able to run the server to check if my changes are working on the admin panel. I followed the documentation but still am facing this issue.
![this](https://user-images.githubusercontent.com/104521101/229733949-56ed3fa3-f018-447a-9e3f-15b687df066f.png)

Can you assist me in setting up the server so that i could see if my code changes work or not?

**Comment by dev265545** [comment]
are you running on windows or linux based os ?

**Comment by ArslanYM** [comment]
> are you running on windows or linux based os ?

Windows.

**Comment by dev265545** [comment]
you will have to use windows subsystem for linux WSL2 to make it run on windows or use linux based os, you can check owncast_for_windows doc it is mentioned in the readme

**Comment by dev265545** [comment]
if you face any problems you can contact me at https://owncast.rocket.chat/home

<blockquote><img src="assets/favicon_512.png" width="48" align="right"><div><strong><a href="https://owncast.rocket.chat/home">Owncast</a></strong></div></blockquote>

**Comment by gabek** [comment]
@ArslanYM I went ahead and assigned this to Dev since it didn't seem like there was any movement on this. Hope all is well!

**Comment by ArslanYM** [comment]
Yes great. I was having  a hard time setting this on windows. Sorry for the inconvenience.
