### ISSUE TITLE
Admin: "Copy" button for stream keys copy asterisks if key is hidden

### ISSUE THREAD

**Issue by taintedcypher** [owncast/owncast#2897]
In the admin web ui for stream keys (/admin/config/server/ > "Stream keys"), if you click the "copy" button while the key is hidden ("********"), the placeholder asterisks are copied to the clipboard instead of the key.

Tested on Firefox 111 (Linux), Ungoogled Chromium 111 (Linux)

**Comment by dev265545** [comment]
I can take up this issue

**Comment by gabek** [comment]
Thanks, Dev!
