### ISSUE TITLE
Chat: words containing one or more dots are turned into links

### ISSUE THREAD

**Issue by taintedcypher** [owncast/owncast#2898]
### Share your bug report, feature request, or comment.

In chat messages, words containing one or more dots (e.g. "A.B", "a.b.c") are turned into clickable links.
Numbers don't seem affected (eg. "123.45").

**Comment by gabek** [comment]
This is probably due to TLD validation being disabled. I originally turned it off because it wasn't detecting the `.online` TLD.

**Comment by dev265545** [comment]
I can take up this issue
