### ISSUE TITLE
Access tokens: deleted tokens are not invalidated

### ISSUE THREAD

**Issue by taintedcypher** [owncast/owncast#2902]
### Share your bug report, feature request, or comment.

Access tokens deleted from `/admin/access-tokens/` can still be used to send chat messages.

How to reproduce:
1. Create an access token for "Can send chat messages on behalf of the owner of this token."
2. Verify that it works (it works!)
3. Delete the token using the web UI
4. Try using the deleted token to post a message (the token still works)

Tested on Firefox 111 (Linux), Ungoogled Chromium 111 (Linux)

**Comment by gabek** [comment]
Thanks for reporting this!
