### ISSUE TITLE
Admin: stream key warning still mentions admin lockout

### ISSUE THREAD

**Issue by taintedcypher** [owncast/owncast#2905]
### Share your bug report, feature request, or comment.

In /admin/config/server/ > "stream Keys" tab, the warning message still says that changing the stream key will lock you out of the admin ui:

> Changing your stream key will log you out of the admin and block you from streaming until you change the key in your broadcasting software.

**Comment by gabek** [comment]
Thanks! As a part of this it should be checked if the admin password change is showing the correct warning that is accidentally showing with the stream keys.

**Comment by taintedcypher** [comment]
For clarification, after using the ui a bit more.
Looks like adding a stream key *does not* trigger the warning. It was probably still showing after an earlier Admin password change from the other tab on the page. (but the issue is still valid)
