### ISSUE TITLE
Improve design for offline video embed

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2917]
### Share your bug report, feature request, or comment.

Right now it just shows the offline banner. It looks pretty odd by itself in an iframe surrounded by emptiness. I'm thinking some additional actions should be there. Because it's inside an iframe we will be limited with functionality, but there's bound to be something better than this.

![image](https://user-images.githubusercontent.com/414923/231935565-a15ac3e5-0c0d-42e7-a9ae-1998dd13234d.png)

---

## Plan

- [x] Build new embed offline view with no fancy functionality
- [x] Build optional "Follow" functionality into new embed offline view
- [ ] Use custom action color (see below) to customize the appearance of the view

**Comment by gabek** [comment]
Ideas:

- Server logo
- Link to server/encourage them to go to the main server page to learn more
- Encourage them to follow?

**Comment by gabek** [comment]
As always I'm on the lookout for design help, and this would be a great design task to help out on since it's small and self contained. https://owncast.online/components/?path=%2Fstory%2Fowncast-documentation-design--page

**Comment by gabek** [comment]
Removing this from the milestone since we don't have anybody to help with design.

**Comment by gabek** [comment]
This is a better example of how it currently looks.

![image](https://github.com/owncast/owncast/assets/414923/9652c518-685b-4151-b98e-4b5751a48112)

**Comment by freenandes** [comment]
What assets (images, svg, etc) does a channel typically have? What's the minimum of assets and what's the maximum? We could use those materials to start having an idea of what we can use to at least fill in the space.

Can Owncast be promoted? Like a lateral logo?

A visual link to the channel would be great, yes

**Comment by gabek** [comment]
> What assets (images, svg, etc) does a channel typically have? What's the minimum of assets and what's the maximum?

They can upload a custom logo, but that's it. Owncast servers can also have any number of external links, and each one of those is an image. Some have a bunch, some have zero, depending on how many external destinations they want to promote. [Here's the list of linked images](https://owncast.online/components/?path=/docs/owncast-frontend-assets-social-platform-images--docs).

There are also things called ["Action buttons"](https://owncast.online/components/?path=/story/owncast-components-action-buttons-buttons-row--example-1). It has a generic name because they can literally fire any kind of action. These can have a custom icon. You can configure them to show a modal within the web interface, or link somebody to an external page. They're pretty cool.

> Can Owncast be promoted? Like a lateral logo?

Over time, I've seen more, and more people really dislike having Owncast branding, and many people go out of their way to remove it. So with v0.1.0 I removed most of any kind of Owncast references from the interface, and people appear to be much happier after I did that. Now all that's left is [the footer](https://owncast.online/components/?path=/story/owncast-layout-footer--example) of the main interface.

In general, I focus on "what can I do to make this streamer more successful in some way?" and that often is at odds with highlighting Owncast as a project. I'm not opposed to it, but this is just what I've learned from users, and my own experience over time.

There's probably a balance that can be found, but if the Owncast promotion is even a little bit too obvious, people get upset and start asking how they can remove it.

**Comment by freenandes** [comment]
Does this sound like the right elements to include?
<img width="1330" alt="shapes at 23-12-11 17 35 45" src="https://github.com/owncast/owncast/assets/42041153/24793eb0-6b58-4499-be04-dec7b83132a3">

I am not sure if it's a good idea or not to add the links. It depends on the finalized experience. So the preview needs testing. Is the default link always present on the channel, is it a required?

I'd include the credit as a small text and under testing. We could ask several users what they think, just to get a sense. The channel's logo will likely dominate. It's a small tradeoff, having a small footnote, but we can see about this

**Comment by gabek** [comment]
I think that makes a lot of sense! That's a great way to visualize it.

I'm not totally sold on the links either, but if asking: "If the stream is offline, what would I want somebody who sees this view to be able to do instead?" To me, the answer is probably offering some next steps/action items. You can't watch the stream since it's not live, but you can be routed to other things via links, or encourage them to follow/get notified later.

There might be a better way of thinking about it, though. 

> I'd include the credit as a small text and under testing. We could ask several users what they think, just to get a sense.

Another challenge with the project has been getting quality feedback from users. I've tried a handful of ways, but like everything else, asking people to go out of their way for the project doesn't result in anything. While this isn't optimal, it's good to know. I've wasted a lot of time in the past trying to discuss with users and not getting anywhere, so it's not something I focus on anymore.

I'd like to say I hear back when people don't like something, but even that's not true. When people don't like something, they just find a way to work around it and never mention it.

**Comment by freenandes** [comment]
OK, let's simplify like this
<img width="1311" alt="shapes at 23-12-11 20 52 50" src="https://github.com/owncast/owncast/assets/42041153/6fb5681c-6796-42f2-8c8a-1861c3afc2f7">
A little potential vision for the future, if we allow the channel to have a cover, we'll use it to brand the embed a little bit, so that avid followers know who's that empty embed is from. For now, we have to do our best with the Owncast brackground.

Then, we may want to be able to entice users to do the following
<img width="1283" alt="shapes at 23-12-11 21 05 00" src="https://github.com/owncast/owncast/assets/42041153/0ecf9e1d-b5be-4376-a09d-f7f843aa3b10">
I am not sure how this works, mechanically. So, users must be logged in to follow? Or do they provide an email, if so, then we have to open up a form to submit it?

**Comment by freenandes** [comment]
Oh, i think it's this
![CleanShot 2023-12-11 at 21 15 56@2x](https://github.com/owncast/owncast/assets/42041153/a87a9a97-ea6b-4fec-b295-f3f148957640)

So, one must have fediverse creds. Does this have to open in another window/page or can this be done on the embed?

**Comment by gabek** [comment]
> A little potential vision for the future, if we allow the channel to have a cover, we'll use it to brand the embed a little bit

It's not a bad idea. I do try to use the 80/20 rule with most things. In this case, the background image would only be used in an embed, something that not everyone cares about. I also am pretty sensitive about adding more and more settings to the Owncast admin. People already think live-streaming is complex, so I really try to keep the cognitive overhead of the admin as low as possible. I'm not sure adding a setting for an image that isn't useful for everyone, and used in a very specific use case, is worth adding another setting to the admin we have to try and explain. But maybe we could come up with some middle ground. Is there a default style we might be able to create that will work for most use cases, and those that are power users can use CSS to style it further?

> So, one must have fediverse creds. Does this have to open in another window/page or can this be done on the embed?

Because an embed is really just an iframe, and iframes have pretty locked down security these days, there are some limitations. In this case, I think it's no problem to _show_ that modal (since it's just UI in the web app), but once they click "Follow" it will need to open a new tab to complete the flow.

**Comment by gabek** [comment]
Another variable is that not everyone will have the "Follow" or "Notify" functionality enabled. So there are multiple different variations of the "offline banner". The different versions of it can be seen [here](https://owncast.online/components/?path=/story/owncast-layout-offline-banner--example-default-with-notifications). So 5A and 5B might not exist for some people, and they'd stop at step 3, just like they do now.

**Comment by freenandes** [comment]
The background doesn't seem like a priority for now. Let's have that avenue for customization later on. Let's assume a default Owncast bg.

Modal inside an iframe it's usually a no-go in UX. Too fiddly. It's preferable to have said button, user clicks, goes into app/new window.

Now, we already have the banner built. All it's missing is the channel logo, a more explicit background, maybe optional in the component. Probably the wording could be improved, not sure. Is "offline" the right word?

[Where else is this component used](https://owncast.online/components/?path=/story/owncast-layout-offline-banner--example-default-with-notifications&args=showsHeader:!true)?

OK, so the channel can choose not to have follow/notify-ability for the users. Still, we do display their avatar, name. Do we need actions at all for these users? If they display links, we can display them too. Maybe these channels prefer to be following from another social account, other verses, bluesky, dunno. So we could display the links... But then, those with the notify/follow won't have their links in it. But seems also too much having it all.

We need to list all the variants, not sure if i've seen all in storybook

**Comment by gabek** [comment]
No modals in an iframe makes complete sense to me. The reason you can't currently follow, or register for notifications from the embed, is because I was concerned about the bad user experience. I'm pretty sure you can't register for browser notifications from within an iframe at all (maybe you can though, it's not something I've tried), and for the follow flow I guess it would open a new window, send you to the full Owncast UI, and _then_ automatically open the follow modal? Functionally, that all works, but none of it feels right to me. So the result was the basic embed that is there now.

> Where else is this component used?

It's on the top of every Owncast server page when the live stream is not active. But it sounds like the version in the embed, and the version on the actual page, are becoming two different things, and that's totally fine. So it might make sense to split them off, but it's not super important either way.

The version of the offline banner that's shown on the actual page can also be customized, but not the embedded version. I didn't use the customized text in the embed because I figured an embed that says, "Come back later!" or something doesn't make sense because the person who is seeing that didn't actually go there in the first place. The lack of context felt like it would be confusing to somebody who saw it.

![image](https://github.com/owncast/owncast/assets/414923/dff7322c-4d21-42ae-b57c-854fafbffac1)

> We need to list all the variants, not sure if i've seen all in storybook

Storybook should have all the current variants, but none of the new ideas we're talking about (links, follow, notify) aren't currently in the embed.

> So we could display the links... But then, those with the notify/follow won't have their links in it. But seems also too much having it all.

Agreed. And I'm not attached to showing the links. I'm just trying to put myself in a streamer's shoes, and I would think they'd want to get _something_ out of an offline state. Even if it's just a follow on LinkedIn, or whatever. But there might be better ways to think about this.

**Comment by gabek** [comment]
As an aside, thanks so much for wanting to put thought into this. These kinds of conversations are essential and it's really nice to have them with somebody!

**Comment by freenandes** [comment]
I guess it's better to go more generic and just incite the user to visit the page, while giving a scent of what they can do there, but some channels have absolutely nothing on their page! Not even a link in the description...

<img width="1808" alt="shapes at 23-12-12 09 09 55" src="https://github.com/owncast/owncast/assets/42041153/04733bc8-3317-459c-bc8b-71fddc0fccca">

These are some ideas of hierarchy of info. The sauce of this component is in the background, it needs to have some inspiration

**Comment by gabek** [comment]
Some background there. Originally, that's how I built the offline banner, with the "Follow" button, but it was weird showing the Follow button, and then the Follow button a second time just under it. So my compromise was to turn the word "Follow" into a link that performed the same action as the button, without showing that second button.

But now if we're going to split up the regular Offline Banner, and the Embed Offline Banner, we can do whatever we want without that concern. I'm glad to be able to bring the button back!

I'm still not sure of the flow when you hit the follow button in the embed. I know we don't want to show a modal, but what do you think about the view just swapping to the "Follow" view if you hit the follow button? It's not a modal, just a state change.

**Comment by freenandes** [comment]
> the view just swapping to the "Follow" view if you hit the follow button

How feasible is that in the many fediverse flavors? Does the following mechanism always work? Are users always logged in?

**Comment by freenandes** [comment]
Here are some potential ways to do it, but we need to be certain about missing scenarios here. Can you list them?

<img width="3020" alt="shapes at 23-12-12 21 34 01" src="https://github.com/owncast/owncast/assets/42041153/eb9b89a9-e979-4b07-abad-7e2c2cd6b828">

I believe having the flow B is better due to the slow digestion of info. Flow A seems more rushed

**Comment by gabek** [comment]
I agree with B, but there are a few more steps in the follow process, so it's probably worth spelling them out just so it's clear what the actual flow looks like.

B1: Offline embed state
B2: Click "Follow this channel" button
B3: State changes to allow typing in your Fediverse account
B4: Click "Follow" button
B5: New tab opens up with your Fediverse instance
B6: Accept the prompt asking if you want to follow this user.
B7: Close new tab?
B8: Maybe the embed changed back to the offline state from the follow state after executing B4?

We'd need some different button text for B1 since nobody really calls their stream a "channel". But there also isn't any standardized name. "Server" I guess is as close as people get? But that's probably not great to put in a button.

**Comment by freenandes** [comment]
What if before step 5 you're already in your fediverse instance? Does it change?

**Comment by freenandes** [comment]
It seems that this is all we can do in this flow, right?

<img width="2730" alt="shapes at 23-12-13 09 27 45" src="https://github.com/owncast/owncast/assets/42041153/af276717-ff77-4ca2-8c8b-32e4fec29d8c">

We don't have control on the other server, so we hope the user returns. Any way of allowing to follow directly on the embed without extra steps?

**Comment by gabek** [comment]
> It seems that this is all we can do in this flow, right?

That looks right!

> What if before step 5 you're already in your fediverse instance? Does it change?

Good question. Because the Fediverse is decentralized, there's no way for server A to know that you're logged into server B. And even if you were, you still have to approve the follow. For example:

![image](https://github.com/owncast/owncast/assets/414923/0f0b67d6-b75b-4283-8774-15b13b189f31)

> We don't have control on the other server, so we hope the user returns. 

Currently, the way Owncast kind of gets around this is it opens a new tab, so the user doesn't actual leave the first one. And if they abort the follow flow by closing that new tab, they'll just be right back to where they were. So that's how I anticipate it working with an embed follow flow as well. So that would tweak the flow diagram a bit, where it wouldn't require them to come back, they'd just close the new tab when they're done.

> Any way of allowing to follow directly on the embed without extra steps?

Unfortunately not, it's the decentralized nature of the Fediverse. You can't tell an arbitrary Fediverse server to perform an action.

**Comment by freenandes** [comment]
> So that would tweak the flow diagram a bit, where it wouldn't require them to come back, they'd just close the new tab when they're done.

The user may want to return to read its feed, so they do, they will see that the embed will not ask you to follow anymore. It will show that you're already following the server. So, the last state is still needed?

On another topic, the embed will have a UI style that is always different from the wrapper UI the user is in. The most basic example is, if the user is reading the feed in a dark mode UI, then the embed will be styled the way we left it, not honoring the dark mode, right?

**Comment by gabek** [comment]
> The user may want to return to read its feed, so they do, they will see that the embed will not ask you to follow anymore. It will show that you're already following the server. So, the last state is still needed?

I feel like I keep throwing wrenches in the conversation :), But in this case, the embed will not know that a successful follow happened on Fediverse server B. So it can't actually change to a state that says, "You are now following". There's no connection between you (the person, using a browser, viewing the feed, looking at an embed) and the follower (the identity that Owncast knows has previously performed a follow).

I guess that's confusing, but luckily, I haven't heard any concerns about it. In the main Owncast web UI, after you follow it, since there's no way to change to an "Unfollow" or "You are now following" state, it just shows the same UI. If somebody were to try to go through the follow flow a second time, when they get sent to their Fediverse server it would say "You say you want to follow this account, but you already are". But all that has to happen on the individual's Fediverse server, Owncast unfortunately has no knowledge of that because there's no centralized authority to ask "Is X following Y?"

There might be a better solution to this, but I'm just not currently aware of one with how things currently work. I'll do some brainstorming for long-term improvements with regard to things like identity and identity state.

**Comment by freenandes** [comment]
Yeah, it's a bit clunky. Just tried in Mastodon too... Never noticed the previous server about it. I guess the user is not interested at that point, the objective and motivation is just to see the "Following" state on their own server. That's visible, right?

So, let's work with what we have. We just politely inform the user that they already tried to follow. In case they didn't finish, we have to force some change so they don't lose their minds think "did i?". What do you think?

<img width="2731" alt="shapes at 23-12-15 15 50 30" src="https://github.com/owncast/owncast/assets/42041153/6ad90d33-c86c-4c0f-9292-69db7a593eb3">

**Comment by gabek** [comment]
The only catch there is there's a specific URL we have to send somebody to in order to start the Follow flow, and we won't hav ethat URL at the "This stream has ended... you can reopen it here again" state. So we would just have to show the "Follow" button again so they can type in their account and restart the flow.

But hopefully that's not a deal breaker!

**Comment by freenandes** [comment]
Here's an idea for the UI. What do you think?
![Board](https://github.com/owncast/owncast/assets/42041153/3e0f8257-60c9-4c63-80a0-4edcafd6c3ff)

**Comment by freenandes** [comment]
I could maybe try the messaging on the left hand side with the "profile card" on the right for wider containers 🤔

**Comment by gabek** [comment]
I think that's fantastic! It catches your eye and has a clear call to action, that absolutely is a million times better! 

I'm not sure if it's being too clever, but we might even be able to customize the gradient to use the custom action (button, link) color that they have set for their server. But that might give too much of an opportunity to ruin your design.

**Comment by freenandes** [comment]
Yeah, let's contemplate the customization. Can you show me all the  variables on the user side? I want to have an idea of what they can do to their pages (besides probably the ability to also customize the CSS?)

I'll also render the other states soon

**Comment by gabek** [comment]
Sure! You can see all the different color variables here: https://owncast.online/components/?path=/docs/owncast-styles-colors-palette--docs

As far as appearance customization, everything is CSS-based. I'm going to message you a login to an Owncast server, since it seems like you don't currently have access to one.

<blockquote><div><strong><a href="https://owncast.online/components/?path=/docs/owncast-styles-colors-palette--docs">@storybook/cli - Storybook</a></strong></div></blockquote>

**Comment by freenandes** [comment]
An idea for the customization

![Customization options](https://github.com/owncast/owncast/assets/42041153/271de3c2-4e3c-4b61-84a7-9af2146290a6)

The main color of the gradient could come from the Action color. I assume this is the style that the users want to see as the dominant accent color in their page. So whenever they change the buttons and links colors, they'd change one of the gradient stops.

Then to complement the gradient i'm not certain about what could be more useful aside from creating a new token entirely just for that or for more in the future. I could see this gradient being recycled for more use cases and then that secondary color of the gradient could be called something like "alternative", "secondary", "complementary", whatever (as long as it's somehow obvious)

**Comment by freenandes** [comment]
The states for this component i guess we are reduced to just 2: the offline state and the _submit handle_ state

![Component Draft](https://github.com/owncast/owncast/assets/42041153/9984262b-9be4-4c0f-9c9e-1f278feffbad)

When the user wants to follow, the in-between state is to 2) submit the handle, then 3) view new tab/window. Once the new window pops up, the state of the embed resets to the "offline"

**Comment by freenandes** [comment]
Maybe apply a max-width there on the form to make it look better when the embed is too wide

![CleanShot 2024-01-02 at 17 13 12](https://github.com/owncast/owncast/assets/42041153/612a61d6-e48e-4415-9ca8-e4a626a52f87)

**Comment by gabek** [comment]
> Then to complement the gradient i'm not certain about what could be more useful aside from creating a new token entirely just for that or for more in the future.

If we don't already have a color that's available for this, I'd be hesitant to add one _just_ for it. But like you said, if we had other uses for it, maybe that would make sense. There's already so many color customizations, and it already feels like too many. I know when I look at it, my eyes glaze over, and I get confused and a little overwhelmed. So adding even more to it just for this color tweak that isn't functionally adding anything is a rough tradeoff. When I envisioned customizing colors, I hoped you could set four or five colors, so what we have now I see as a failure that you have to do so much work and understand so many things. I know I don't even understand all off those colors.

I'm not really sure how to fix that problem. I'd hate for us to keep adding more and more of these color customizations and end up with 100 of them in a couple of years just because we keep adding new features.

**Comment by gabek** [comment]
> When the user wants to follow, the in-between state is to 2) submit the handle, then 3) view new tab/window. Once the new window pops up, the state of the embed resets to the "offline"

Yeah! With the limited options we have around knowing what's going on with the new window/tab and the whole "remote follow" thing, I think this is the best bet.

Instinctually, you'd think it would confuse people, but the Owncast UI itself has worked similarly (with a "Follow" button, not an "Unfollow" button, even if you're even already following them, for example) and not a single person has ever shown confusion from that. So I guess it's more ok than I thought.

**Comment by freenandes** [comment]
i see... We could make something like this, where the second color for the gradient is auto-generated from the user defined token "action", for example.

![CleanShot 2024-01-03 at 17 07 43](https://github.com/owncast/owncast/assets/42041153/78e23040-bef4-4cff-a87e-176b75f98a55)

We just need the original token and make a hue shift and lightness shift. This keeps it consistent and this technique can help us in more areas, like for example, neutral colors like grays. You just need the user to define 1 text color. We can make up everything else using hue shifts and lightness adjustments. I'll explain this bit a bit better in the chat to preserve this issue clean from other topics

**Comment by freenandes** [comment]
Or we can drop it entirely for the sake of keeping it clean for users but having the whole spice up for ourselves

![Customization options 3(2)](https://github.com/owncast/owncast/assets/42041153/f9e9ac59-cb8d-4280-ae84-2bf2c84375e1)

**Comment by gabek** [comment]
Reference example for mixing colors: https://codepen.io/caraya/embed/LYjwLEe?default-tab=result

**Comment by gabek** [comment]
Right now, the Offline Banner that we use in the actual web app, and the one we use in embeds is exactly the same. With the above change, we're looking to split the two up, and create a new embed offline state with this new design. 

[This link](https://design.penpot.app/#/view/af8aaf7c-05e6-8124-8003-9f92b17cbf0a?page-id=af8aaf7c-05e6-8124-8003-9f92b17cbf0b&section=interactions&index=0&share-id=75aa5258-9a82-8002-8003-b9936863afc0) will give you access to the design and stuff like the CSS and color values, etc. Press "Code" to see that.

Press the `i` key on your keyboard to enter inspect mode to see the component properties.

Thanks to all of @freenandes hard work, this is the first time we're using PenPot in the way that it's supposed to be used, so this is exciting!

![image](https://github.com/owncast/owncast/assets/414923/76ee8935-b4b7-4071-b9f3-3cfc468ca4f5)

**Comment by gabek** [comment]
Also, since this embed has a handful of "Follow" functionality, if somebody wanted to work on just the design, I'd be happy to do the functionality if somebody didn't want to have to dig into the rest of it. But they're totally welcome to go as deep as they'd like!

**Comment by gabek** [comment]
Hey @freenandes, one question! Maybe it's something we discussed but never made it anywhere so it might have got lost. What should it say if the server does not have following enabled?

In this case it wouldn't say "Follow this server..." and the "Follow server" wouldn't appear. 

![image](https://github.com/owncast/owncast/assets/414923/54379711-d497-4e1a-a3f9-3a245d6b6920)

**Comment by gabek** [comment]
Additionally, @freenandes, I just want to mention how nice it is to be able to go into PenPot, select a component, copy the CSS, and just use it. Normally, I'd be spending hours tweaking CSS values and still not get it right. This is absolutely wonderful. Thank you so much for doing this.

**Comment by freenandes** [comment]
Hey! I think we ended up with just having a link to the server's public page. And yeah, penpot is great! A bit buggy but 2.0 will be out soon and probably improve a lot of stuff
