### ISSUE TITLE
autogenerated streaming key  contains bad characters

### ISSUE THREAD

**Issue by valvin1** [owncast/owncast#2919]
### Share your bug report, feature request, or comment.

on nightly version v20230410-nightly

while testing new feature of multiple stream keys I had some trouble.

it appears some characters are not compatible, for example this key `OFDIZcapUVR!0IL8ovX8O2WG3%XjjU`

I suppose it is related to `%`. I've tested other generated keys without any issue.

**Comment by gabek** [comment]
Interesting. Broadcasting software must not be escaping the the percent. Probably easiest just to not use that character. Thanks!

**Comment by dev265545** [comment]
Can I take this issue ?

**Comment by gabek** [comment]
Absolutely, thanks, Dev!
