### ISSUE TITLE
Change offline banner message to support markdown

### ISSUE THREAD

**Issue by valvin1** [owncast/owncast#2921]
### Share your bug report, feature request, or comment.

on nighlty v20230410-nightly

Setting up a multiline "About" or "Offline Message" doesn't apply.

![image](https://user-images.githubusercontent.com/1267915/232148341-df05855c-ca55-423e-bc06-4fde60ae83aa.png)

![image](https://user-images.githubusercontent.com/1267915/232148387-4cba233a-1457-42e0-8323-7ac43409726a.png)

It is maybe desired. If yes maybe it should be indicated in admin input ?

**Comment by gabek** [comment]
It can be changed to support markdown, with the markdown editor we use in the admin to give more flexibility.

**Comment by dev265545** [comment]
Hey I would like to work on this issue.

**Comment by gabek** [comment]
Sure! There is a `RenderPageContentMarkdown` in `utils` that you can pass the offline message through, and the text input can be swapped out for the markdown editor.
