### ISSUE TITLE
Tabs: Jump to content when selecting tab

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2936]
I'm not 100% this is a thing that should be done, but it _feels_ like it would be nice.

Currently on smaller screens there's a scenario (such as the iPad example) where you see the tab bar, so you select the tab you want to see, and then you have to scroll around to see that content.

It feels like it would be nice when you select a tab, because it's obvious you want to view that content, to auto-scroll down so that content is in view.

What would others think?

https://user-images.githubusercontent.com/414923/233722977-ea1f4415-d975-43a6-8bf1-e7f3795213c7.MOV

**Comment by Pranav2612000** [comment]
I can pick this up. The idea is to scroll the 'About' secition into view once the 'about' section is clicked. Right?

**Comment by gabek** [comment]
Yeah, what do you think? Should it? I'm not 100% convinced, but when I kind of find myself wishing that it did when I was clicking on the tab. I guess we could try it and remove it if it doesn't feel right.

**Comment by Pranav2612000** [comment]
> Yeah, what do you think? Should it? I'm not 100% convinced
Yeah. Me too. 

I'll have a PR ready. We can test it and see how it feels and discard it if it feels weird.
