### ISSUE TITLE
Password change and normal login panel for admin!

### ISSUE THREAD

**Issue by p6002** [owncast/owncast#2937]
### Share your bug report, feature request, or comment.

When can I expect the option to change my password with abc123? :)  I don't know about others, but I would like to share the stream outside the local network.

Also, it would be good if a normal login panel would appear so that my password manager could remember it. 

Whenever I want to log in I always enter all my passwords, only to be reminded at the end that it is abc123....

**Comment by gabek** [comment]
> When can I expect the option to change my password with abc123?

As of v0.0.13 your password and stream key is the same. There's nothing stopping you from changing it. It's highly encouraged that you change it immediately and never leave the default.
