### ISSUE TITLE
Layout: Player gets cut off vertically on some screens

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2954]
### Share your bug report, feature request, or comment.

There seems to be one layout issue with regards to the player where the height seems too short. The `develop` branch correctly sizes it as a 16:9 aspect ratio. This was tested on a desktop browser.

After PR #2863: 

![image](https://user-images.githubusercontent.com/414923/234707239-b33774a6-4dbf-4e6d-9735-2ee6a8c55e02.png)

Previous to PR in the `develop` branch for comparison:

![image](https://user-images.githubusercontent.com/414923/234707502-9e4abdc1-1830-4ade-8744-14d56d640e1c.png)

**Comment by gabek** [comment]
Going to wait until #2966 is closed first, since some refactoring is taking place there.

**Comment by gabek** [comment]
@thisprojects I tracked down what's causing this, but I'm not sure exactly _why_, and I thought maybe you'd have the answer :)

It seems like the Ant row where the player is sitting is sitting in a weird spot. It's a bit too high and causing the page header to cover it. Do you know why this ant row is slightly off like that?  I'm able to hack together a solution by adding some top padding to that row, but if the width of the page changes then that top padding changes, so that's not the real answer.

Here's some examples:

In this screenshot I drew a green border around the ant row.
![image](https://user-images.githubusercontent.com/414923/236334952-57d8afc8-c2c9-4610-8c9a-13bade316545.png)

And in this screenshot I highlighted it in the dev tools. You can see how it's underneath the header.
![image](https://user-images.githubusercontent.com/414923/236334993-0bfbdfa5-8b21-4efe-b1ba-d828c31c5799.png)

If I reduce the height of the header so you can see the entire row (the green border), it fixes that issue, but it creates a gap above the chat:

![image](https://user-images.githubusercontent.com/414923/236335527-e780ef42-c8a8-4ff5-9fb4-4d5cb7e20e7d.png)

**Comment by thisprojects** [comment]
Have raised https://github.com/owncast/owncast/pull/2987 

Looks like the header needed a fixed height, as its "fixed" now we need to apply margin to the layout so content doesn't "disappear" behind it. Looks ok to me on the main view ports in both online and offline modes, does it fix the problem your side?
