### ISSUE TITLE
Tablet layout: Portrait layout makes action buttons wrap

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2957]
See #2863 for layout PR.

![image](https://user-images.githubusercontent.com/414923/234714198-e85ea515-4ccb-4eaa-b441-975ea6e5b590.png)

**Comment by gabek** [comment]
I made a change to help things a bit by making the spacing dynamic, but this can still occur.

**Comment by thisprojects** [comment]
I'm wondering if we should add a new screen size boolean, just for the action buttons, and deliver the mobile burger menu action buttons when desktop screens are under a certain width?

**Comment by gabek** [comment]
Maybe. A bunch of booleans starts to fall into unmaintainability, however. I wish it could just be handled with CSS, since that's what media queries are for, but we're doing media queries **and** "is mobile" stuff now, making a bit of a mess. If we add another "is tablet" or "is narrow screen" then there's three different ways the page handles viewport sizes. Plus we wouldn't want this portrait tablet layout to be using the mobile layout, that would look funny, so we'd need a third layout I guess? I'm really not sure.

**Comment by thisprojects** [comment]
Actually, now ActionButtons are in their own component, the solution can be 100% CSS. Have raised a PR here - https://github.com/owncast/owncast/pull/2965

The media queries may need tweaking, depending on what width you are experiencing the problem at. How can I go about getting those custom action menu buttons for testing?
