### ISSUE TITLE
Add margin under the page content

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2963]
### Share your bug report, feature request, or comment.

So it doesn't sit right up against the footer.

![image](https://user-images.githubusercontent.com/414923/235054992-d37995f8-9870-4eb5-9e95-7e15f4daea77.png)

**Comment by bonapartbon** [comment]
@gabek i want to contribute to this issue, can i work on it?

**Comment by gabek** [comment]
Of course, thanks @bonapartbon!

**Comment by VaibhavKambar7** [comment]
hey @gabek , can pls elaborate the issue, like what needs to be done
i think the content in the footer needs some margin , which will increase the size of the footer, right?
thanks

**Comment by gabek** [comment]
It would be the page content that needs additional spacing, not the footer itself. Please don't increase the size of the footer.

**Comment by gijsdb** [comment]
Let me know if this does not get completed and want me to do it :)

**Comment by VaibhavKambar7** [comment]
i will try to complete this by today.

**Comment by VaibhavKambar7** [comment]
Made a PR , please check.

**Comment by gabek** [comment]
@bonapartbon This originally had been assigned to you, I just want to check in since @VaibhavKambar7 looks to be working on a PR, but since you were the first to show your interest I wanted to make sure you had a chance to look at it.

**Comment by gabek** [comment]
I hope you don't mind, but I went ahead and took care of this quick while I was looking at some other things just to take care of it. Sorry about that!
