### ISSUE TITLE
Automate Screenshot from streamed video

### ISSUE THREAD

**Issue by razzaghi** [owncast/owncast#2969]
### Share your bug report, feature request, or comment.

Hi,

Screenshot from streamed video can be a good feature for data generating and other task on them.

**Feature Request:**

**Screenshot configuration:**
- Enable/Disable getting screenshot
- Define screenshot API address to send screenshots to it.
- Or, Define an storage to save screenshots(Like S3)
- Screen shot interval (It means to take a picture and send it every few seconds)

**Feature Usage:**
- Data Collection / Processing
- Image Captioning
- Image AI Tasks
- ...

**Comment by gabek** [comment]
Could you go into further detail what you mean by a screenshot? Is this different than the existing thumbnail that gets generated?

**Comment by razzaghi** [comment]
Yes is different, I mean extracting images(original quality) from video and store in a directory or send to an API. and extracting time be configurable(every 2|3|4|5 sec).

For now, I write a python script with opencv to extract images from hls output and store in a directory.

**Comment by gabek** [comment]
Got it. I believe that is out of scope of what Owncast is built for. The focus here is streaming, so if you need to pull static frames from your video that's a different scenario. For best quality you should be capturing these images at the broadcasting end.
