### ISSUE TITLE
Admin: Custom emoji page layout

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2979]
### Share your bug report, feature request, or comment.

Right now it's one very long list that takes a lot to scroll through. Changing this to a grid would make it easier to browse through your emoji collection.

![image](https://user-images.githubusercontent.com/414923/235756348-a6dc36bc-fade-4739-a339-c50a4584678d.png)

**Comment by dev265545** [comment]
Hey! I can take this issue

**Comment by gabek** [comment]
Awesome, thanks Dev! :+1:
