### ISSUE TITLE
Public web page: Support versioned API documentation

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#298]
@jmhobbs made a good suggestion that we version our API documentation, and I think that's a good idea for anybody who either wants to work on Owncast itself, or use the APIs for their own uses.  https://github.com/owncast/owncast/issues/263#issuecomment-717395712

For clarity we'd want `/api/latest` to map to `/api/0.0.x` (whatever the most recent version is).
And then we'd want the current `master` (development) API documentation to live in `/api/development`.

So two things need to be done:

- [x] Add a Github action that on a [schedule](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onschedule) (once a day or whatever) have the public web site download [index.html](https://github.com/owncast/owncast/raw/master/doc/api/index.html) to `/static/api/development`, commit the result and perform a Hugo build.
- [ ] Figure out how to redirect `/api/latest` to a specific version like `/api/0.0.3`.  I'm not sure offhand how to do this with Hugo builds, because these aren't markdown files (just a static HTML file), but I'm sure it's doable without having to need two copies (in `/api/latest` AND `/api/0.0.3`).

@jeyemwey Would you be interested in taking a look at this since you did the original setup of the Hugo site?

**Comment by jeyemwey** [comment]
i'm not sure if I am the most helpful person on this topic, but this is what I have right now:

```bash
#/bin/bash

# First, get the repository and find the latest tag
git clone --quiet https://github.com/owncast/owncast source
cd source
TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
cd ..

# Always copy the api in the source repo to the development page
cp "source/doc/api/index.html" "static/api/development.html"

# check wether the newest tag is present in the api folder
if [ -f "static/api/$TAG.html" ];
then
	# There is nothing to do here
	echo "Docs with the latest tag $TAG exists already"
else
	# If 
	echo "Copying $TAG and marking it as the latest"
	cp "source/doc/api/index.html" "static/api/$TAG.html"
	ln -s "$TAG.html" "static/api/latest.html" 
fi

# Remove the source folder
rm -rf source
```

Hugo seems to work with symlinks, so a `static/api` folder like this:

```bash
$ ls -la
drwxrwxr-x 2 jannik jannik    4096 Okt 27 21:13 .
drwxrwxr-x 4 jannik jannik    4096 Okt 27 21:07 ..
-rw-rw-r-- 1 jannik jannik 1119221 Okt 27 21:13 development.html
lrwxrwxrwx 1 jannik jannik      11 Okt 27 21:13 latest.html -> v0.0.2.html
-rw-rw-r-- 1 jannik jannik 1119221 Okt 27 21:13 v0.0.2.html
```

would return the generate a `latest` and `v.0.0.2.html` file with the same content.

One problem that the script above has, is that the v0.0.2 release is significantly behind the current HEAD. The current generated api docs are mistakenly taken for "v0.0.2".

**Comment by jmhobbs** [comment]
Perhaps we should use `latest` for `HEAD` and `stable` to link to the most recent release?  Maybe `/api` could have a release list or something.  I'm happy to pitch in if theres something I can help on.

**Comment by gabek** [comment]
Oh wow, that's more thought than I put into it! :)  I was literally thinking when we make a release we just manually copy the file over into a new `/static/api/0.0.x` directory, since we don't have to do it that often.  Automated is obviously better, though!  But I think simple is fine for now.  While you should totally run with it if you'd like, I do think we can add more automated hooks  later if we're doing more releases.  The only thing that needs to be automated every once in a while is getting the current doc from github to the web site `/static/api/development`, and that will always be on `master` in the repo, so that simplifies things.

**Comment by jeyemwey** [comment]
I would favor manually pushing changes to the page, so there is no real use for this.

Maybe, we can just change the webhook that fetches the collaborators to also fetch the latest `development` state?

Also, how do we make sure that the generated version in `owncast/owncast` is inline with the state of the application? Is the Docs generation triggered manually?

**Comment by jeyemwey** [comment]
Please add your changes to https://github.com/owncast/owncast.github.io/tree/api-reference . I don't expect to merge this branch before the `v0.0.3` release.

**Comment by gabek** [comment]
I just pushed a workflow update to your branch for every six hours to pull in the dev api documentation, run a build, and commit the updates.

https://github.com/owncast/owncast.github.io/commit/b0739cca4027f54411d715cc278c240ca18970e9

For each release we can just manually copy the documentation to `/api/0.0.x`.  And we can link to these in the release notes both on Github and the web site https://owncast.online/posts/.  So then we don't have to list every release on the apis page, since every release is already documented.

I also just learned that if you put a file in `public/` and it's html Hugo will render it within the site template.  Crazy, I didn't know that.  If you pull the branch and go to `http://localhost:1313/api/development/` you'll see it.  It's not exactly what we want, though, so I'm looking to see if we can turn that off somehow :)

**Comment by gabek** [comment]
Ok to fix that I put the rendered api `index.html` in `/api/` but the page with the instructions in `/docs/api`.  So I think that's fine.

Take a look and feel free to make any changes that you like.  We probably don't need to wait until 0.0.3 to be released if we don't want to, since we'll update it then anyway to have the final version and can just have the dev api doc until now.

**Comment by gabek** [comment]
Also relevant: the release checklist.

https://github.com/owncast/owncast/blob/master/.github/ISSUE_TEMPLATE/owncast-release-checklist.md

**Comment by gabek** [comment]
I went ahead and merged it in to push it live.  I think we're good to go.  If we find we want to automate pushing release documentation at some point we can revisit that.  Thanks, everyone!

https://owncast.online/docs/api/
