### ISSUE TITLE
Page scrolls with empty space under the footer

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2983]
### Share your bug report, feature request, or comment.

There looks to maybe be a minimum height somewhere causing the page to add extra space underneath the footer.

![image](https://user-images.githubusercontent.com/414923/236107228-14d9967d-57d1-4e98-9c0d-febdcd37dac0.png)

**Comment by sospeterkedogo** [comment]
Can you assign this issue to me, please?

**Comment by gabek** [comment]
Absolutely, thanks!

**Comment by sospeterkedogo** [comment]
Where do I find the specific file to make changes to?

**Comment by gabek** [comment]
I'm afraid I can't answer that without troubleshooting and fixing it myself. You'll have to look into why this is occurring and then make the changes required if you're interested in working on it.

In general, however, all the web files are in the `web` directory, and we use CSS modules, so you'll find corresponding `.module.scss` files for most React components.

**Comment by sospeterkedogo** [comment]
Thanks, this will help me narrow down to the problem

**Comment by gabek** [comment]
@SospeterKe Hey there! Any luck looking at this?

**Comment by sospeterkedogo** [comment]
@gabek I tried to run it on my local server but it wouldn't run, so I pretty much didn't have any luck.

**Comment by gabek** [comment]
Feel free to reach out if you'd like to fix whatever issues you're running into. It shouldn't be too difficult to get a development environment up and running.

**Comment by sospeterkedogo** [comment]
So I managed to run it locally and the page seems to be fine. The margin under the footer is no longer there.

**Comment by sospeterkedogo** [comment]
How can I setup the username and password so that I can login to the admin?

**Comment by gabek** [comment]
The default username is `admin` and the default password is `abc123`.

I don't know when it happens and when it doesn't. For example if I visit https://nightly.owncast.tv the problem is there.

![image](https://user-images.githubusercontent.com/414923/236864640-3fe5e865-1ea3-4ec7-9fd0-ecbad2f60af3.png)


<blockquote><img src="https://nightly.owncast.tv//thumbnail.jpg" width="48" align="right"><div><img src="/img/favicon/favicon-16x16.png" height="14"> Owncast Nightly</div><div><strong><a href="https://nightly.owncast.tv/">Owncast Nightly</a></strong></div><div>This is a server running the nightly build of Owncast.</div></blockquote>

**Comment by thisprojects** [comment]
I think this has something to do with the followers tab content setting the screen height. If you view the followers tab, does the footer behave correctly (sits at bottom)? 

I can resolve this on develop by removing "height: 100%" from the body.... is still a large gap if I do the same with dev tools on the nightly though.

Only immediate fix I can think of is to make the footer "fixed" at the bottom of page. 🤔

**Comment by gabek** [comment]
Haha I was looking at it and found the fixed footer was a solution as well, but I wasn't sure what people would think of that. I'm not completely opposed to it. What do you think, is that annoying?

**Comment by thisprojects** [comment]
I think it's fine, fixed footers are quite common. Optionally, we could fade the fixed footer in when the user scrolls to the bottom of the page and fade out when they scroll back up.

**Comment by gabek** [comment]
@thisprojects I'm intrigued by this fading fixed footer idea, but I'm having a hard time imagining it. Would you be interested in taking a stab at it?

**Comment by thisprojects** [comment]
Sure - assign this one to me.

**Comment by thisprojects** [comment]
Have created this PR for the floating footer - https://github.com/owncast/owncast/pull/3008

If you like it, we should prob extract the scroll listener and fading logic into it's own component so its tidier and can be reused.
