### ISSUE TITLE
Delete FediAuth DM

### ISSUE THREAD

**Issue by DeveloppeurPascal** [owncast/owncast#2994]
### Share your bug report, feature request, or comment.

Hi

If a user authenticate with FediAuth process, he receives a one shot DM. Depending on the instance and software he can remove the conversation, but it should be stored on the instance database.

Perhaps it's a good way to remove DM after an successful authentication.

And of course removing non used codes and DM messages after a delay could be a good thing too.

**Comment by gabek** [comment]
What would the benefits of automatically deleting outgoing messages be?

**Comment by DeveloppeurPascal** [comment]
Cleaning timelines and DM for people how don't know they can remove senders messages.
And in case of someone using the system to attack one or more users by flooding, it could be a solution to avoid blacklist.
