### ISSUE TITLE
Support custom iOS home screen icons

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2995]
### Share your bug report, feature request, or comment.

Right now we ship with the Owncast icon of different sizes that are hard-coded as the Apple home screen icon. It would be great to use the stream's custom logo as the icon instead.

The downside of this is either we'd have to build in a bunch of image resizing logic, or only set one icon size, point it to `/logo/external`, and hope iOS is ok with that.

A bonus would be that we can remove all those additional Owncast logo icons from https://github.com/owncast/owncast/tree/develop/web/public/img/favicon

**Comment by ghost** [comment]
Plz sir I need this

**Comment by gabek** [comment]
As far as I can tell, almost nobody adds Owncast as a PWA to their Home Screen. So at this time I won't be putting any additional work or features into that functionality. However, if somebody felt passionately about this particular feature, go for it!

**Comment by gabek** [comment]
Putting additional work into the PWA probably isn't worthwhile. Closing.
