### ISSUE TITLE
Mobile: Action menu button should be inline with tabs

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2996]
It used to be inline with the tabs, but for some reason it now renders above it and takes up extra vertical space. 

![image](https://user-images.githubusercontent.com/414923/236740457-e96c3c52-b1a8-4469-8402-ea898a1c6ce1.png)

**Comment by gabek** [comment]
I remember why this is probably happening. The button used to be a part of the mobile tab component, but then it got pulled out and it probably never re-positioned to be in the right place.

**Comment by ksharma20** [comment]
Can I pick this one up?

**Comment by gabek** [comment]
Absolutely, thanks!

**Comment by gabek** [comment]
This was fixed in the layout updates in #3022. Closed.
