### ISSUE TITLE
Header logo image not filling circle properly

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3000]
### Share your bug report, feature request, or comment.

Only noticed this once the demo server got updated. https://watch.owncast.online

![image](https://user-images.githubusercontent.com/414923/236954258-8e56966e-567d-40b3-859b-eb9bc466368c.png)

**Comment by dev265545** [comment]
I can take this up.

**Comment by gabek** [comment]
Awesome, thanks! I hadn't looked into if it's an issue across the board or there's something up with just this one image.

**Comment by dev265545** [comment]
I am not able to locate this issue, can you point where the bug is ?
Because it looks okay to me.

**Comment by gabek** [comment]
I simply saw it looking not correct so I took a screenshot and filed this issue.  See the above screenshot where the top and left sides are squared off. I haven't looked into it so I'm not sure where the issue lies.

**Comment by gabek** [comment]
I was able to track it down. Changing from a `border` to an `outline` fixed it.
