### ISSUE TITLE
Different fonts make images align to text differently in chat

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3009]
### Share your bug report, feature request, or comment.

Notice the left people image and right star image are not vertically centered with the text with this font. These should be center aligned regardless of the font used.

![image](https://github.com/owncast/owncast/assets/414923/b878e10a-4967-43e5-aa61-631c94d4f168)

**Comment by dev265545** [comment]
I can take this issue.

**Comment by gabek** [comment]
Awesome, thanks Dev! I'm guessing it's just a flexbox alignment thing. Maybe? :)

**Comment by gabek** [comment]
It still doesn't look centered.  For example, here's the same icon vertically centered with a display name in a chat message. See how the star is vertically centered with the text:

![image](https://github.com/owncast/owncast/assets/414923/f8442a93-40f6-4b32-a1ce-51f01c97d8ae)


However in the join message, the star is not vertically centered with the text, and looks more baseline aligned:

![image](https://github.com/owncast/owncast/assets/414923/90345968-d9f0-4667-a9d0-ea167614abe3)
