### ISSUE TITLE
Moderation info modal should set text colors

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3010]
### Share your bug report, feature request, or comment.

If you use a dark background color for your site theme this modal renders with black on dark text.

To access this modal:

- Give yourself moderator privileges
- Send a chat message
- Press the moderation menu button when hovering over the message
- Click "More info"

![image](https://github.com/owncast/owncast/assets/414923/9b7b5235-9fd7-4659-af0c-abdb7247a8de)

**Comment by Asanim** [comment]
Hey I'm a little new to this but thought I'd pick this PR up. Joined the slack channel yesterday but wanted to reproduce the issue before I started.
