### ISSUE TITLE
chat not working

### ISSUE THREAD

**Issue by lxnrmoon** [owncast/owncast#3011]

**Comment by gabek** [comment]
Would you mind elaborating?

**Comment by JeremyMahieu** [comment]
Using the docker v0.1.0, chat just never starts, always displays "Chat is offline" even when a stream is live.

**Comment by JeremyMahieu** [comment]
Could it be because websockets are not working? If websockets are not working, due to bad reverse proxy configuration for example, there is no indication except for lots of errors in the dev console.
