### ISSUE TITLE
The layout problems will never end. The web needs to burn.

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3012]
### Share your bug report, feature request, or comment.

Is it too late to build Owncast's frontend as a native iOS app? These layout problems are really taking a toll on my sanity and they're impossible to fix without breaking everything else.

![image](https://github.com/owncast/owncast/assets/414923/2017bbc9-f893-4fb9-9fb8-a6fc19a64b8f)

**Comment by gabek** [comment]
Obviously I'm joking about the iOS app thing. But I'm not joking about all the web layout problems. It feels like this release will never be release ready, all the mobile crap is so buggy.

**Comment by amrinder1189** [comment]
Hi, I am working on this

**Comment by thisprojects** [comment]
I think this may have been introduced when we changed the offline banner from absolute to relative positioning. We might be able to fix the offline-banner using flex basis and flex grow, if not it will prob have to be absolute positioned again.

Regarding the app idea - we could port some of the mobile components into a React-Native app, would prob be quicker than starting from scratch with pure iOS or Android (and would work on both). I've no experience with publishing react-native apps though.

**Comment by gabek** [comment]
> Regarding the app idea - we could port some of the mobile components into a React-Native app, would prob be quicker than starting from scratch with pure iOS or Android (and would work on both). I've no experience with publishing react-native apps though.

I was just joking about an app, since I'm really frustrated and sad right now with working on the web.

But since you mentioned it, I do have experience releasing React Native apps and they're just absolutely the worst. It's all the worst parts of the web and none of the great things about native mobile development. It tries to do cross platform UI development, and that's the wrong thing to try and do. Every mobile environment is unique and should use it's native toolkit. Shared business logic makes a ton of sense though, just not UI.

**Comment by gingervitis** [comment]
I'll try to address these issues that I've noticed:
- odd offline spacing issues (too much space at the top)
- mobile chat spacing issues (too much space at the top)
- odd footer issues (doesn't show up if window is tall enough)

**Comment by gabek** [comment]
Closing since #3022 was merged in, and I'm filing smaller issues that can be looked at individually.
