### ISSUE TITLE
Admin S3 configuration form - Change secret input to be a password type

### ISSUE THREAD

**Issue by valvin1** [owncast/owncast#3013]
### Share your bug report, feature request, or comment.

On current nightly `2023-05-13`, in admin interface, `Configuration / Server Setup / S3 object storage`.

Field `Secret key` is a standard text input. So when I open this tab the secret key is visible attached to all of information related to the bucket. I think it'll be better if it is hidden maybe like the stream keys.

**Comment by gabek** [comment]
Sure, I don't think there's a downside to treating that value as a password.
