### ISSUE TITLE
Unauthenticated Blind SSRF

### ISSUE THREAD

**Issue by oxeye-daniel** [owncast/owncast#3014]
Hello, I've sent an email regarding an Unauthenticated Blind SSRF vulnerability in owncast.

**Comment by gabek** [comment]
Responded!

**Comment by oxeye-daniel** [comment]
Hi @gabek, as a fix was added in - https://github.com/owncast/owncast/commit/f40135, we kindly request you open a Github advisory for this vulnerability. Thanks
