### ISSUE TITLE
Do not show the latency statistic in the admin if it is 0

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3015]
### Share your bug report, feature request, or comment.

You can find this in the Utilities / Stream Health page. Zero just means it has no data to calculate, so it simply shouldn't show it.

![image](https://github.com/owncast/owncast/assets/414923/98a57f26-af44-49ef-8a67-39bab6fb8409)

**Comment by abhipanorian** [comment]
hey @gabek, I would like to pick this. Looks like a simple case of conditional rendering. Can you help me how to access the admin panel? What is the username and password going to be? I have made the fix but want to check how it looks.

**Comment by gabek** [comment]
> hey @gabek, I would like to pick this. Looks like a simple case of conditional rendering. Can you help me how to access the admin panel? What is the username and password going to be? I have made the fix but want to check how it looks.

Hey there! You can find the admin at port 3000 `/admin`. It should auto log you in, but the default username and password is `admin` and `abc123`.
