### ISSUE TITLE
support closed captions

### ISSUE THREAD

**Issue by KiaraGrouwstra** [owncast/owncast#3024]
### Share your bug report, feature request, or comment.

RTMP streams may include closed captions as well. it would be nice if owncast could handle these as well for viewers.

**Comment by gabek** [comment]
What specific functionality would you like to see? What does handling them and supporting them mean to you?

**Comment by KiaraGrouwstra** [comment]
i have RTMP streams of live events, with embedded closed caption data transcribing what is happening. this makes the events more accessible for our remote viewers that might be hard of hearing, or might otherwise prefer to view the content by reading along rather than using the audio, e.g. when in a noisy environment.

this would improve over the present scenario where one would need to burn the captions into the actual video. in that particular scenario, the streamer would need an additional rendering step for this, viewers could no longer disable the captions, while it would also become more involved to add additional languages or allow viewers to from their end configure how big they would like to view such captions.

**Comment by YohannLYD** [comment]
Seconding this feature request.

I just discovered [Web Captioner](https://webcaptioner.com/) which is a service that transcibes the audio/microphone input on the go as @KiaraGrouwstra mentioned.

It can be integrated to obs so viewers can toggle the captions if the streaming service supports it. Everything is described on this page : https://webcaptioner.com/help/integrations/obs

<blockquote><img src="https://webcaptioner.com/static/og-image.jpg" width="48" align="right"><div><strong><a href="https://webcaptioner.com/help/integrations/obs">Add live captions in OBS Studio - Web Captioner Help</a></strong></div><div>Free, real-time captioning for your event.</div></blockquote>

**Comment by gabek** [comment]
Could you detail exactly what it is you're looking for Owncast to do that it doesn't do? Currently if captions are supplied in your RTMP broadcast they get passed through. I've seen a couple streamers execute real time captioning this way. It seems to be pretty flaky, given the real-time nature of it all, but I've seen it work without making any changes to Owncast.

If you're looking for Owncast to actually do the transcription, or tie into a 3rd party to transcribe, that's not something that Owncast will be able to provide you.

**Comment by KiaraGrouwstra** [comment]
ah, great to hear - thanks for confirming!
