### ISSUE TITLE
Mobile chat modal button is showing up on non-mobile layout

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3041]
### Share your bug report, feature request, or comment.

1. Start stream
2. Stop stream
3. In the 5 minutes between chat shuts down the button will show.
4. Button will disappear 5 minutes later.

![image](https://github.com/owncast/owncast/assets/414923/b86e7674-9aa1-46dc-bd2e-a4be05e574a6)

**Comment by gingervitis** [comment]
Hm, do we just need to wrap the  modal and button render with an `isMobile` check around here https://github.com/owncast/owncast/blob/develop/web/components/ui/Content/Content.tsx#L306? 

<blockquote><img src="https://repository-images.githubusercontent.com/266445736/4f82fb80-a5b1-11ea-8f1c-69d316f861b5" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/owncast/owncast">owncast/Content.tsx at develop · owncast/owncast</a></strong></div><div>Take control over your live stream video by running it yourself.  Streaming + chat out of the box. - owncast/Content.tsx at develop · owncast/owncast</div></blockquote>

**Comment by gabek** [comment]
I think so! Or a media query I guess. A simple thing I overlooked.

**Comment by gingervitis** [comment]
Wait, so what are the exact requirements again, in the 5mins right after the stream has stopped?

Basically should chat, or any chat indicator be present at all during this time? (both desktop and mobile)

**Comment by gabek** [comment]
For 5 minutes after a stream ends the chat should continue to be active. This all works. But I didn't handle the button to not show on desktop.

**Comment by gingervitis** [comment]
> For 5 minutes after a stream ends the chat should continue to be active. This all works. 

That doesn't seem to be the case according to this line?
https://github.com/owncast/owncast/blob/develop/web/components/ui/Content/Content.tsx#LL194C9-L194C25


At any rate, I put up a PR! https://github.com/owncast/owncast/pull/3042

<blockquote><img src="https://repository-images.githubusercontent.com/266445736/4f82fb80-a5b1-11ea-8f1c-69d316f861b5" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/owncast/owncast">owncast/Content.tsx at develop · owncast/owncast</a></strong></div><div>Take control over your live stream video by running it yourself.  Streaming + chat out of the box. - owncast/Content.tsx at develop · owncast/owncast</div></blockquote>

**Comment by gabek** [comment]
Closed in #3042.
