### ISSUE TITLE
Add a user flag for bot accounts

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3046]
### Share your bug report, feature request, or comment.

Currently there is no badge/flag identification for bot accounts. For when `isBot` on a user is `true`.

**Comment by devrajgadhvi** [comment]
I would like to address this issue can you let me know what exactly needs to be done? And what kind of badge we are looking for here and where exactly that should be added?

**Comment by gabek** [comment]
If you look at https://owncast.online/components/?path=%2Fdocs%2Fowncast-chat-messages-user-flag--authenticated you'll see the bot user flag already exists, but it's just not being displayed yet.

<blockquote><div><strong><a href="https://owncast.online/components/?path=%2Fdocs%2Fowncast-chat-messages-user-flag--authenticated">Webpack App</a></strong></div></blockquote>

**Comment by devrajgadhvi** [comment]
In this page there is a badge available for bot right? Here is the same
![image](https://github.com/owncast/owncast/assets/32088637/cf0df459-7aba-4f60-ba6b-7501879aedc7)

In which screen/page it's not getting displayed can you let me know? So that I can add it there

**Comment by gabek** [comment]
This is for the chat account display name on chat messages. Just like there's already an "authenticated" and "moderator" badge for chat messages, the bot one was never previously added.

**Comment by devrajgadhvi** [comment]
I went through the code in **owncast/web/components/chat/ChatUserMessage/ChatUserMessage.tsx** and relevant other files I could find but it looks like the bot badge is added however it's strange that it's not getting displayed. Can you please direct me to the specific file if you know.

**Comment by gabek** [comment]
I'm not sure exactly what might be the issue. I filed this because I was doing some testing and I noticed the bot icon didn't show up for bots. So maybe the problem exists further down if it's all wired up properly in the view layer.
