### ISSUE TITLE
Deprecation warning of antd dropdown 

### ISSUE THREAD

**Issue by yk-jp** [owncast/owncast#3052]
### Share your bug report, feature request, or comment.

I get the warning when localhost:3000 is open on the `develop` branch.

STR:
follow `run the web project`
https://owncast.online/development/#run-the-web-project

<img width="905" alt="Screenshot 2023-05-27 at 4 29 34 PM" src="https://github.com/owncast/owncast/assets/69574727/818ff483-0c5c-4a13-b956-fdee1639a0f1">

**Comment by janWilejan** [comment]
Fixing this looks fairly straightforward: https://4x.ant.design/components/dropdown/

I'll fix it

<blockquote><img src="https://gw.alipayobjects.com/zos/rmsportal/rlpTLlbMzTNYuZGGCVYM.png" width="48" align="right"><div><strong><a href="https://4x.ant.design/components/dropdown/"> Dropdown - Ant Design</a></strong></div><div>A dropdown list.</div></blockquote>
