### ISSUE TITLE
Try to officially support video passthrough

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#306]
We've purposefully not supported the config option of video passthrough due to video compatibility issues in the past.  There's been a couple scenarios where different broadcast sources would send something, we'd pass it through, and the player would die trying to play it.

Transcoding is "the great equalizer" when it comes to video compatibility because regardless of whatever kind of particulars are in the RTMP stream sent to us we always crank through it and something playable comes out the other end.  But if we simply just demux the stream and segment the results then sometimes what comes out the other end (for whatever reason) isn't as compatible.

But we do have more details about inbound RTMP streams now, so I believe it's possible to perform a sanity check on inbound streams and if we deem it to be something that isn't compatible with passthough, we can reject it and tell them to not use passthrough.  And better yet, if we can figure out the specifics of what is wrong with these incompatible streams maybe we can fix it.

I believe the sanity check and warn approach would give most people back the ability to use this feature and increase quality while decreasing CPU usage.

Reference issues: #305 #269

**Comment by gabek** [comment]
If people were to try using passthrough it was breaking things and also wouldn't display properly in the admin.  So I put in a fix for those two things.  I don't want people to try it, but if they were to, at least it won't die anymore.  I still plan on taking a deeper dive on trying to support it officially.

**Comment by cablebox** [comment]
FWIW, OBS just [added support for native HLS encoding](https://github.com/obsproject/obs-studio/pull/3114), which could remove the RTMP step.

That being said, I don't know where to go as far as the ability to take that HLS source and re-encode down to other bitrates for adaptive streaming support.

**Comment by gabek** [comment]
While I agree that RTMP is dated, the real work of a server isn't the ingestion process, it's the transcoding process.  So if you ingest via HLS segments, neat, but if you still need to transcode them afterward then you're not really gaining much other than not having to deal with RTMP.  And like it or not RTMP is supported by pretty much everything, so I don't see it going away anytime soon.

**Comment by VladimirAkopyan** [comment]
I think you should add a flag to enable this somehow, and call it "not recommended" option or whatever. 
This is a self-hosted product, the streamer and server admin are often one and the same person.  I feel that folks that want to muck about with incompatible OBS settings just so that they can save some pennies on the VPC should be allowed to do so.

**Comment by gabek** [comment]
Sadly we've had bad experiences with exactly what you're describing, people turning it on and then reporting back that "nothing works".  Due to the nature of people it's often hard for them to describe what changes they've made, and it can take hours of troubleshooting before they tell us they're using passthrough.  Turning it off fixes things.  However, if you want to take the risk, create a new video variant with just `videoPassthrough: true`.

**Comment by VladimirAkopyan** [comment]
Thank you for letting me know! I can understand your reluctance, but I think a bit of documentation would go a long way -> both in terms of providing some 'safe' settings, and in terms of putting a big red warning on that if you do this, you are on your own.

**Comment by aaronpk** [comment]
FWIW the ATEM Mini Pro works fantastic with passthrough mode! There's no load on the system and the video plays just fine. +1 for at least documenting that flag cause I had to dig up this issue to remember how to turn it on!

**Comment by VladimirAkopyan** [comment]
@aaronpk what settings/codec do you use to broadcast? When I was streaming with OBS, sometimes it worked, sometimes it didn't, and I went back to re-encoding because I got tired of trial-and-error

**Comment by aaronpk** [comment]
I just used the ATEM Mini Pro's "Streaming High" setting, whatever it's doing works great without transcoding. I don't really use OBS so I'm not sure what you'd have to select there to make it work. The admin dashboard says the ATEM is pushing:

> avc1 @ 6000 kbps
> 29.97003 fps
> 1920 x 1080
> mp4a, 64 kbps

**Comment by pierreozoux** [comment]
We used jibri (jitsi) with owncast passthough without problems (well we had some, but not the player :) )

**Comment by gabek** [comment]
Looks like we're slipping this in as a last minute addition to 0.0.6.

**Comment by gabek** [comment]
First step is in, you can enable it.  There's some warning messages around it and some added documentation in the 0.0.6 docs.  As far as detecting if/when it won't for for people, we'll have to do that later.  But this is a start.

**Comment by aaronpk** [comment]
I will upgrade mine to 0.0.6 and give this a try!

**Comment by gabek** [comment]
Closing this, as passthrough is available, and we have some next steps to try and troubleshoot why it doesn't work for some people in https://github.com/owncast/owncast/issues/955.
