### ISSUE TITLE
Support "days" in stream length

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#307]
Probably not something _most_ people will see, but who knows.  If somebody is live streaming their fish or something, then it'd be going 24/7 just like our demo server.

![image](https://user-images.githubusercontent.com/414923/97512352-8e419580-1946-11eb-96fa-05b824ccb4e1.png)

**Comment by bgildson** [comment]
hey @gabek, could I pick this issue?

**Comment by gabek** [comment]
Absolutely, thanks!
