### ISSUE TITLE
Bottom content on mobile does not span full width in some cases

### ISSUE THREAD

**Issue by TOWUK** [owncast/owncast#3073]
### Share your bug report, feature request, or comment.

![image](https://github.com/owncast/owncast/assets/28830162/dc43b1d8-8fcc-443a-a088-d8c36f77e6e5)

desc on fill height or width

**Comment by TOWUK** [comment]
its owncast used only on local machine without onen ports

**Comment by AniketSaraswat112** [comment]
HI @TOWUK I would like to work on this issue, please assign this to me.

**Comment by gabek** [comment]
Thanks @AniketSaraswat112!

**Comment by AniketSaraswat112** [comment]
Hi @gabek getting the following error when running front-end locally:

<img width="834" alt="image" src="https://github.com/owncast/owncast/assets/56517011/c92c7f80-bdc2-4db8-ae66-bcb29d4fa89d">

pls help me resolve this.

**Comment by gabek** [comment]
Is the backend also running for the frontend to connect to?

**Comment by AniketSaraswat112** [comment]
I tried running backend but getting the following error in console on running command "go run main.go" :

<img width="725" alt="image" src="https://github.com/owncast/owncast/assets/56517011/30de1202-a90c-4c97-a3f4-9cd8d6844bd6">

I have installed ffmpeg folder from "https://github.com/BtbN/FFmpeg-Builds/releases" and placed the bin folder in the same directory as Owncast.

I have also tried running ffmpeg.exe from the bin folder so as to install it globally, but still the above error occurs.

**Comment by gabek** [comment]
Oh are you running on Windows? If so maybe this can help: https://github.com/owncast/owncast/blob/develop/contrib/owncast_for_windows.md

<blockquote><img src="https://repository-images.githubusercontent.com/266445736/4f82fb80-a5b1-11ea-8f1c-69d316f861b5" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/owncast/owncast">owncast/owncast_for_windows.md at develop · owncast/owncast</a></strong></div><div>Take control over your live stream video by running it yourself.  Streaming + chat out of the box. - owncast/owncast_for_windows.md at develop · owncast/owncast</div></blockquote>

**Comment by gabek** [comment]
@AniketSaraswat112 Were you able to get your development environment working ok?

**Comment by gabek** [comment]
I'm going to go ahead and grab this and look at it since I'm not sure if it's still being looked at.

**Comment by gabek** [comment]
Still doesn't look great with such little content, but at least it's fixed now. 
![image](https://github.com/owncast/owncast/assets/414923/b19e20b6-1a61-492d-a8d4-22b8983947b9)
