### ISSUE TITLE
Image opengraph tag has double slashes creating an error

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3075]
### Share your bug report, feature request, or comment.

`og:image` and `og:image:alt` both have the issue.

Example:

![image](https://github.com/owncast/owncast/assets/414923/deaee2aa-516c-4580-9351-65fdc7bfdff0)
https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fnightly.owncast.tv

**Comment by yk-jp** [comment]
@gabek  Hi, let me try to resolve the bug please.

**Comment by gabek** [comment]
Great, thank you!
