### ISSUE TITLE
Add username for each chat message in html

### ISSUE THREAD

**Issue by taintedcypher** [owncast/owncast#3077]
### Share your bug report, feature request, or comment.

Hi!
I have written a CSS theme for Owncast which I've seen a few people use over the months. I wanted to port it to the new Owncast 0.1.0 but the HTML for the chat is not suitable for it: Right now, the username is only included once for every "block" of messages. 

I'd like to be able to display the name of the author before each message. 

That's why I would request that the `.ChatUserMessage_user__` div be added to each `.ChatUserMessage_root`. 
If you can set it to `display:none` to hide it for subsequent messages (as to mimick the current look), it would enable us to set it to `display:block`if we want to.

Not sure if I'm expressing this right, feel free to ask for clarification!

**Comment by gabek** [comment]
I get it. I don't recall offhand how the layout of that component is laid out, but I'm assuming it should be possible to make these changes without impacting things significantly. Feel free to put in a PR if you want to get it in sooner than later.

**Comment by janWilejan** [comment]
fixed by #3101

users who want to show repeat usernames can inject the following CSS: `[class^="ChatUserMessage_repeatUser"]{display:flex !important;}`

**Comment by taintedcypher** [comment]
Hi, I just wanted to thank you for adding this back in. I just spent a couple of hours theming the nightly version, and thanks to this change I was able to do what I wanted! :heart:
