### ISSUE TITLE
Chat name change modal should auto-close after changing name

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3083]
### Share your bug report, feature request, or comment.

I left it to stay open to allow people to also change their color without having to go back into the modal, but too many people think it doesn't work because it stays open.

![image](https://github.com/owncast/owncast/assets/414923/60072707-a835-46ba-b763-8c151d95953a)

**Comment by mohibkay** [comment]
Hey, @gabek, could you please assign this issue to me?
I would like to work on this.

**Comment by gabek** [comment]
Great, thank you @mohibkay!
