### ISSUE TITLE
Remove animation of chat sidebar

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3089]
### Share your bug report, feature request, or comment.

The Ant Design sidebar component is animating in when the page first loads and chat is active. This shows a flash of empty space and a broken feeling. We should completely remove this transition so it doesn't slowly move into place.

In my initial attempts I have not figured out how to remove this.

1. Start stream
2. Load page
3. Watch sidebar slide in from the right

**Comment by dev265545** [comment]
I can take up this issue

**Comment by gabek** [comment]
Awesome, thanks so much Dev!
