### ISSUE TITLE
Android + Firefox results in duplicated characters when typing in chat

### ISSUE THREAD

**Issue by Talon1024** [owncast/owncast#3094]
### Share your bug report, feature request, or comment.

When I try to write something in the chat box using Android's on-screen keyboard under Firefox, the text input is duplicated and repeated. For example, when I try to enter the word "Hello", it goes like this:

Press "H":
H
Press "e":
HHe
Press "l":
HHeHHel
Press "l":
HHeHHelHHeHHell
Press "o":
HHeHHelHHeHHellHHeHHelHHeHHello

This happens with Owncast v0.1.0. The browser is Firefox 114.1.1 (Firefox for Android), and the Android version is Android 13 (One UI 5.1).

**Comment by gabek** [comment]
Could you share some screenshots?

**Comment by Talon1024** [comment]
![Screenshot_20230616_133653_Firefox](https://github.com/owncast/owncast/assets/6550500/42193ff7-19ca-48b1-9786-c7d9256fd228)

That's after (trying to) write "Hello" in the chat box.

**Comment by gabek** [comment]
Just did a little testing and indeed, specifically on Android + Firefox this issue occurs. On all other Android browsers I tested it's fine. So at least that narrows it down.

**Comment by gabek** [comment]
Might be related to https://github.com/ianstormtaylor/slate/issues/5130.

**Comment by gabek** [comment]
This might be the catalyst to write something custom for the chat input. Slatejs is bulky and difficult to use, and apparently buggy. But I really don't want to start over with the chat input. The custom emoji rendering in the input field is really a pain.
