### ISSUE TITLE
Bug owncast with Firefox 

### ISSUE THREAD

**Issue by MadyChain** [owncast/owncast#3099]

**Comment by gabek** [comment]
Oh come on. You have to at least put in the bare minimum effort of saying what **what the bug is**. I'm going to assume you're a troll because this can't possibly be a real issue. Closing until you can prove otherwise.

**Comment by MadyChain** [comment]
No, I'm not a troll.
Best regards, Maria Catena

Contatti: +39 333 52 12 891
mailto: ***@***.***


Il sab 24 giu 2023, 00:23 Gabe Kangas ***@***.***> ha scritto:
