### ISSUE TITLE
Video Embed: /embed/video introduces scrolling

### ISSUE THREAD

**Issue by jprjr** [owncast/owncast#3104]
### Share your bug report, feature request, or comment.

It appears that when emedding video with the `/embed/video` URL - the `#player` div has its height set to `100vh`. The containing div is using `96vh`.

Since the player is the entire viewport height, the status bar that appears afterward pushes the total size to > 100% of the viewport height and scrolling is introduced.

Usually for an embed - I want to view everything without introducing scrolling, I think setting the player div's height to 96vh would fix the issue. Not sure if the status bar should also have `max-height` set to something like `4vh` to ensure it's always == 100 total?

**Comment by gabek** [comment]
Makes sense to me!
