### ISSUE TITLE
Can't update default admin password

### ISSUE THREAD

**Issue by arisu0** [owncast/owncast#3105]
### Share your bug report, feature request, or comment.

![image](https://github.com/owncast/owncast/assets/39315312/5a7e5086-b943-41e8-9ac1-81aef22719c7)
As seen on the picture, using an example password that meets the requirements, the admin panel shows the update button but is not enabled.
Owncast self hosted using the docker image.

**Comment by gabek** [comment]
Does it ever work for you in any circumstance? What browser are you using? Any browser errors?

**Comment by arisu0** [comment]
Happened both in qutebrowser and firefox, no type of error or output I could see

**Comment by gabek** [comment]
So it fails 100% of the time for you, and it's never worked? Or is there just a specific circumstance where it doesn't work?

I ask because it's working for others. If people couldn't change their password at all that'd be a real problem. So I'm trying to figure out what's different with your scenario.

![image](https://github.com/owncast/owncast/assets/414923/ee36203e-d5a3-4d24-98e8-a8a0b82d2041)

**Comment by arisu0** [comment]
Right. I'm not really sure either. And yes it fails 100% of the time the button will never enable. I'm using the latest docker image on ubuntu server. 

I'm gonna try reinstalling and trying random things to see if I can figure someething out.

**Comment by arisu0** [comment]
Okay, so figured it out, the problem I was using a dash which was not allowed. It'd remove the warning about needing a symbol, but wouldn't say anything about it not being a valid symbol.

Should be an easy fix. Thank you for the support.

**Comment by AE720** [comment]
I wanted to say thank you for making this as that was my problem too. I know back in version 0.7 or so, it was allowed. Strange.

**Comment by dj-sf** [comment]
should be updated with a validation message stating that - is not an allowed character

**Comment by germainelee** [comment]
Thanks @larcher!
