### ISSUE TITLE
Chat is creating links for invalid TLDs

### ISSUE THREAD

**Issue by jprjr** [owncast/owncast#3107]
### Share your bug report, feature request, or comment.

Discovered in the current release (0.1.0) - if a user types a message saying "example.png" - that is turned into a link.

Ideally, the top-level domain part would be validated first, and the text only made into a link if it contains a valid TLD.

Also: feature idea - allow admins to specify a list of blocked TLDs. For example, the entire .zip domain is used almost exclusively to host malware, even though it's a valid TLD, I don't want it appearing in chat as a link.

**Comment by gabek** [comment]
The TLD detection for autolinking has already been changed in the next release.
