### ISSUE TITLE
Scrolling: scrolling down on chat can cause video to scroll

### ISSUE THREAD

**Issue by jprjr** [owncast/owncast#3109]
### Share your bug report, feature request, or comment.

I *think* this one has been an issue for a minute but figure I should open it.

Occasionally I'll scroll back up through the chat (using a mouse and mousewheel). When I scroll down, I'll hit the latest message in the chat, and instead of ignoring my attempt to scroll past the last message - the video portion of the page will scroll down instead.

I then have to bring my mouse back to the video portion of the page and scroll up to get the video back in to view.

As far as I can tell, the way to trigger this is to have the video page be the more "active" target (I'm not sure if this is the right phrasing). If I do something like say, click in the chat - the scroll input seems limited to the chat area.

But if I've clicked in the video player area (which I'll probably have done to start the video), then just mouseover the chat and scroll up and down - the scroll seems to apply to the chat until it hits bottom, then the video player area scrolls.

**Comment by gabek** [comment]
I'm pretty sure this is default browser behavior. Once you can't scroll some inner element it starts scrolling the entire document. I know what you're talking about with targeting specific elements for scrolling though, and I really don't know what the browser logic is behind that. As far as I know there's no such thing as the "active" element, but it does function that way. Hopefully this can be improved.

**Comment by jprjr** [comment]
One workaround - the setting the `overscroll-behavior: contain` CSS property on the `<div id="virtuoso">` element. I just did a quick test adding that with devtools at runtime and it makes scrolling the chat behave as expected

**Comment by gabek** [comment]
That's fantastic, thank you!
