### ISSUE TITLE
Cloudflare stream support

### ISSUE THREAD

**Issue by ESMALL-Project** [owncast/owncast#3112]
### Share your bug report, feature request, or comment.

Hello.  I've been looking for a good CDN to use with my instance of Owncast and I stumbled on [Cloudflare stream](https://developers.cloudflare.com/stream/stream-live/start-stream-live/).  It appears to be an offering that one could use in place of Owncast, but it does not have any of the bells and whistles (so to speak) of Owncast.  I am wondering if this would be usable with Owncast as, like an s3 storage solution or add on (as a serving endpoint).   Any thoughts?

**Comment by gabek** [comment]
If Cloudflare is offering their own live streaming service then it would be completely separate from Owncast. Owncast is a self-hosted live streaming server, it does not use external streaming service providers. However, like you mentioned, you can use S3 object storage with Owncast if that's something you require. But that's different than what you're talking about.
