### ISSUE TITLE
Handle null values for external actions

### ISSUE THREAD

**Issue by Juniteevee** [owncast/owncast#3116]
### Share your bug report, feature request, or comment.

Attempted to upgrade my docker image to 0.1.0 this morning and am getting an error. I pulled the new latest and used my existing docker compose

> version: '3'
services:
  app:
    image: 'gabekangas/owncast:latest'
    restart: unless-stopped
    ports:
      - '8484:8080'
      - '1935:1935'
    volumes:
      - ./data:/app/data
      - ./emoji:/app/webroot/img/emoji

I see this log on docker compose up

> [+] Running 1/0
 ✔ Container owncast-app-1  Recreated                                      0.1s
Attaching to owncast-app-1
owncast-app-1  | time="2023-06-27T14:44:14Z" level=info msg="Moving custom emoji directory from webroot/img/emoji to data/emoji"
owncast-app-1  | time="2023-06-27T14:44:14Z" level=warning msg="Moving with os.Rename failed, falling back to copy and delete! rename webroot/img/emoji data/emoji: invalid cross-device link"
owncast-app-1  | time="2023-06-27T14:44:14Z" level=error msg="error moving custom emoji directory Writing to output file failed: write data/emoji: copy_file_range: is a directory"
owncast-app-1  | time="2023-06-27T14:44:14Z" level=info msg="Owncast vv0.1.0-linux-64bit (ee799e76234079712a840d500aeeadd290ff3fee)"
owncast-app-1  | time="2023-06-27T14:44:14Z" level=info msg="Migrating database from version 6 to 7"
owncast-app-1  | time="2023-06-27T14:44:14Z" level=info msg="Migrating users. This may take time if you have lots of users..."
owncast-app-1  | time="2023-06-27T14:44:14Z" level=info msg="Migration datastore values from 1 to 2\n"
owncast-app-1  | time="2023-06-27T14:44:14Z" level=info msg="Video transcoder started using x264 with 1 stream variants."
owncast-app-1  | time="2023-06-27T14:44:14Z" level=info msg="RTMP is accepting inbound streams on port 1935."
owncast-app-1  | time="2023-06-27T14:44:14Z" level=info msg="Web server is listening on IP 0.0.0.0 port 8080."
owncast-app-1  | time="2023-06-27T14:44:14Z" level=info msg="The web admin interface is available at /admin."

My Admin screen appears to be working fine but my main page errors out and is just a black screen with the text

> Application error: a client-side exception has occurred (see the browser console for more information).

and console logging

> framework-ce84985cd166733a.js:9 TypeError: Cannot read properties of null (reading 'map')
    at V (index-7fb59854e855b9c8.js:1:20756)
    at ab (framework-ce84985cd166733a.js:9:60917)
    at ud (framework-ce84985cd166733a.js:9:72803)
    at i (framework-ce84985cd166733a.js:9:120372)
    at oO (framework-ce84985cd166733a.js:9:99114)
    at framework-ce84985cd166733a.js:9:98981
    at oF (framework-ce84985cd166733a.js:9:98988)
    at ox (framework-ce84985cd166733a.js:9:95740)
    at oC (framework-ce84985cd166733a.js:9:96129)
    at r4 (framework-ce84985cd166733a.js:9:44778)
a5 @ framework-ce84985cd166733a.js:9
a.componentDidCatch.t.callback @ framework-ce84985cd166733a.js:9
lH @ framework-ce84985cd166733a.js:9
uY @ framework-ce84985cd166733a.js:9
e @ framework-ce84985cd166733a.js:9
(anonymous) @ framework-ce84985cd166733a.js:9
oI @ framework-ce84985cd166733a.js:9
oC @ framework-ce84985cd166733a.js:9
r4 @ framework-ce84985cd166733a.js:9
oU @ framework-ce84985cd166733a.js:9
o @ framework-ce84985cd166733a.js:9
x @ framework-ce84985cd166733a.js:33
T @ framework-ce84985cd166733a.js:33
main-09b6eb672dcf3256.js:1 TypeError: Cannot read properties of null (reading 'map')
    at V (index-7fb59854e855b9c8.js:1:20756)
    at ab (framework-ce84985cd166733a.js:9:60917)
    at ud (framework-ce84985cd166733a.js:9:72803)
    at i (framework-ce84985cd166733a.js:9:120372)
    at oO (framework-ce84985cd166733a.js:9:99114)
    at framework-ce84985cd166733a.js:9:98981
    at oF (framework-ce84985cd166733a.js:9:98988)
    at ox (framework-ce84985cd166733a.js:9:95740)
    at oC (framework-ce84985cd166733a.js:9:96129)
    at r4 (framework-ce84985cd166733a.js:9:44778)
Q @ main-09b6eb672dcf3256.js:1
fn @ main-09b6eb672dcf3256.js:1
componentDidCatch @ main-09b6eb672dcf3256.js:1
a.componentDidCatch.t.callback @ framework-ce84985cd166733a.js:9
lH @ framework-ce84985cd166733a.js:9
uY @ framework-ce84985cd166733a.js:9
e @ framework-ce84985cd166733a.js:9
(anonymous) @ framework-ce84985cd166733a.js:9
oI @ framework-ce84985cd166733a.js:9
oC @ framework-ce84985cd166733a.js:9
r4 @ framework-ce84985cd166733a.js:9
oU @ framework-ce84985cd166733a.js:9
o @ framework-ce84985cd166733a.js:9
x @ framework-ce84985cd166733a.js:33
T @ framework-ce84985cd166733a.js:33
main-09b6eb672dcf3256.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred

I additionally tried running this without the emotes binding and also only copying over the database and still had the same errors occur. If remove the data folder and emoji folder and do a fresh run it starts a new instance fine. I'd really like to maintain my metrics and userdb as I have a bot that makes use of the userIds but Its not the biggest deal to restart. Just frustraiting.

**Comment by gabek** [comment]
Unfortunately there's not a lot to go by there. Could you provide the output of `/api/config`? Is there anything weird or unusual about your Owncast configuration that may be a hint of where I could look?

**Comment by Juniteevee** [comment]
heres my /config response

> {
    "name": "Juni Tube",
    "summary": "Buncat trapped in a video game console. Come hangout!\nBe Gay, Stream Crimes!",
    "offlineMessage": "",
    "logo": "/logo",
    "tags": [
        "vTuber",
        "ENvTuber",
        "LGBTQ+",
        "Cozy",
        "Gaming",
        "tech"
    ],
    "version": "Owncast vv0.1.0-linux-64bit (ee799e76234079712a840d500aeeadd290ff3fee)",
    "nsfw": false,
    "extraPageContent": "",
    "streamTitle": "Space Girl and Buncat play with robits",
    "socialHandles": [
        {
            "platform": "mastodon",
            "url": "https://vt.social/@juni",
            "icon": "/img/platformlogos/mastodon.svg"
        },
        {
            "platform": "twitch",
            "url": "https://twitch.tv/juniteevee",
            "icon": "/img/platformlogos/twitch.svg"
        },
        {
            "platform": "twitter",
            "url": "https://twitter.com/bunhunfun",
            "icon": "/img/platformlogos/twitter.svg"
        },
        {
            "platform": "discord",
            "url": "https://discord.gg/YXpgNAcKMG",
            "icon": "/img/platformlogos/discord.svg"
        },
        {
            "platform": "youtube",
            "url": "https://www.youtube.com/channel/UCSwJWjQhvHLZPk4XKrcxJWg",
            "icon": "/img/platformlogos/youtube.svg"
        },
        {
            "platform": "kofi",
            "url": "https://ko-fi.com/bunhunfun",
            "icon": "/img/platformlogos/ko-fi.svg"
        }
    ],
    "chatDisabled": false,
    "externalActions": null,
    "customStyles": "",
    "appearanceVariables": {},
    "maxSocketPayloadSize": 2048,
    "federation": {
        "enabled": true,
        "account": "juni@juni.tube",
        "followerCount": 9
    },
    "notifications": {
        "browser": {
            "enabled": true,
            "publicKey": "BDa04HQD9ENPMWP1S98Vc5TelHX-WrEgEjSjdNGhyMbKouoVUdQJaC6NADN31lZ0qbTklg-WA8XEtJh2M2qpCq8"
        }
    },
    "authentication": {
        "indieAuthEnabled": true
    },
    "hideViewerCount": false
}

**Comment by gabek** [comment]
Not sure if it's to blame, but at first glance it seems that the external actions property is null and for me it's an empty array.

**Comment by Juniteevee** [comment]
just noticed that as well testing to see if maybe I can get it to become an empty array with the admin page by putting something in and removing it

**Comment by Juniteevee** [comment]
Thats it. I added an external action via the admin interface and now its loading.
Thank you so much for the help!

**Comment by gabek** [comment]
The external actions bar should also be wrapped in an error boundary component to catch any possible future errors and not crash the entire web application.

**Comment by Juniteevee** [comment]
Of note, if I delete my temporary External Action the error does come back.
