### ISSUE TITLE
Emoji picker: Showing/Hiding

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3118]
### Share your bug report, feature request, or comment.

There is something flaky about how we're showing and hiding the emoji picker. Often times when it hides you'll see it pop back up momentarily and disappear again.

We're putting the picker in a popover, and showing and hiding that popover, but it's possible some show/hide bool state is not doing the correct thing and leading to these weird effects.

**Comment by gabek** [comment]
It's pretty smooth in Storybook. https://owncast.online/components/?path=%2Fdocs%2Fowncast-chat-input-text-field--example

<blockquote><div><strong><a href="https://owncast.online/components/?path=%2Fdocs%2Fowncast-chat-input-text-field--example">Webpack App</a></strong></div></blockquote>

**Comment by dev265545** [comment]
Hi,
Was looking in this issue, was not able to recreate this error.
But found two more  issues in the chat. I am putting a new issue for that.

**Comment by gabek** [comment]
I simplified the showing/hiding logic of the popover in the text field, so hopefully it'll smooth things out.
