### ISSUE TITLE
ChatBox Error -  SelectAll + Delete does not work if input is text + emoji

### ISSUE THREAD

**Issue by dev265545** [owncast/owncast#3121]
### Share your bug report, feature request, or comment.

ChatBox Error -  SelectAll + Delete does not work if input is text + emoji
If we have an emoji and some text or all emojis  then doing select all and backspace/delete does not work.
Only one char/emoji gets deleted per click.
Works fine if input is only text

**Comment by gabek** [comment]
I think this might be a tricky one! I'm starting to miss slatejs now.

**Comment by jprjr** [comment]
I think this may have to do with saving/restoring the caret position, custom key handling and the change handler? Now that emoji are also appended to the end of the message, you could simplify a few things and rely more on the default browser behavior.

Caret positioning, not sure what the default browser behavior is if focus is lost and restored but, it just may not be necessary. It seems like the caret is jumping around a lot more than I expect with the current implementation. I bet removing all of that would reduce the caret jumping around and allow the browser to behave more natively/naturally.

In the handleChange callback, the text property is always replaced with the sanitized version, which triggers another change I think and makes things like ctrl+a not really work (as soon as I ctrl+a everything gets deselected). Doing something like:

```js
if(text.current !== sanitized) text.current = sanitized;
```

May limit how often things are updated.

Key handling could probably be changed to something like:

```js
if(e.defaultPrevented) return;

if(message_length > max_message_length) {
  switch(e.key) {
    case 'a': {
        if(e.ctrlKey || e.metaKey) return;
        break;
    }
    /* allow navigation keys */
    case 'ArrowLeft':
    case 'ArrowRight':
    case 'ArrowUp':
    case 'ArrowDown':
    case 'End':
    case 'Home':
    case 'PageUp':
    case 'PageDown':
    case 'Escape':
    /* allow deletes */
    case 'Backspace':
    case 'Delete': {
      return;
    }
    default: break;
  }
  /* everything else, prevent */
  e.preventDefault();
  return;
}

if(e.key === 'Enter' && ! (e.shiftKey || e.metaKey || e.ctrlKey || e.altKey)) {
      e.preventDefault();
      sendMessage();
      return;
}
```

The idea being to avoid making calls that change any state in the keydown event. Check character counts in the change handler, text-appending function for the emoji picker, etc.

Or alternatively, things could get really simplified if you allow messages to go over the max and just prevent sending when over the max. That really reduces the number of keys to check: the entire keydown function basically becomes:

```js
if(e.key === 'Enter' && ! (e.shiftKey || e.metaKey || e.ctrlKey || e.altKey)) {
      e.preventDefault();
      if(message_length > 0 && message_length <= max_message_length) sendMessage();
      return;
}
```

(and of course in these examples things like `message_length` and `max_message_length` should be replaced by the actual call to get the message length, I'm just trying to show the rough idea).

Going that route may be simpler and less error-prone. Like, for all I know there's systems out there where selecting all doesn't come through as ctrl+a, and checking for ctrl+a breaks their UX? I honestly don't know, I figure keeping browser behavior as default as possible reduces the odds of breaking UX.
