### ISSUE TITLE
When the action buttons wrap there should be spacing between the rows

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3122]
### Share your bug report, feature request, or comment.

This isn't great when they wrap, but in the case that they do, they should have spacing between them.

![image](https://github.com/owncast/owncast/assets/414923/b0530511-6a02-4904-a5da-dd63ebc491c8)

**Comment by dev265545** [comment]
I can take this issue

**Comment by gabek** [comment]
Thanks, Dev! :+1:

**Comment by Akash1965** [comment]
Hi @gabek can I work on this issue if it hasn't been resolved yet??

**Comment by gabek** [comment]
@dev265545 is currently working on it, but thank you for offering!
