### ISSUE TITLE
Admin message page have oddly shaped emoji images

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3126]
### Share your bug report, feature request, or comment.

Custom emoji images are squished. It probably needs a proper `emoji` class with proper sizing.  `/admin/chat/messages/`

![image](https://github.com/owncast/owncast/assets/414923/d4ef95ab-bdfb-45e5-8315-588c45206394)

**Comment by AmitT98** [comment]
Hi @gabek I would like to work on the issue. Can you please assign it to me?

**Comment by gabek** [comment]
Awesome, thanks so much, Amit!

**Comment by AmitT98** [comment]
Hello @gabek I have a doubt. I have setup the project locally and located file owncast/static/web/admin/chat/messages/index.html (I believe this is where problem is). Now how can I reproduce the issue of improper emoji rendering at my end?

**Comment by gabek** [comment]
The chat message admin page is: https://github.com/owncast/owncast/blob/develop/web/pages/admin/chat/messages.tsx

`owncast/static/web` should not be edited.

You will want to start a stream, send a chat message, and then it will show up in the admin. If you haven't yet, read the development document on how to do this: https://owncast.online/development


<blockquote><img src="https://repository-images.githubusercontent.com/266445736/4f82fb80-a5b1-11ea-8f1c-69d316f861b5" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/owncast/owncast">owncast/web/pages/admin/chat/messages.tsx at develop · owncast/owncast</a></strong></div><div>Take control over your live stream video by running it yourself.  Streaming + chat out of the box. - owncast/web/pages/admin/chat/messages.tsx at develop · owncast/owncast</div></blockquote>
<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="https://owncast.online/favicon.png" height="14"> Owncast</div><div><strong><a href="/development/">How to work on Owncast</a></strong></div><div>The technical details for those wishing to take part in Owncast development.</div></blockquote>

**Comment by AmitT98** [comment]
Thanks for the pointing me to directory @gabek . Sorry I got involved in some other work. I will still be working on the issue but not actively,  feel free to assign to someone who comes and shows interest in the issue.
