### ISSUE TITLE
External actions no longer receive username url params from 0.1.0 frontend

### ISSUE THREAD

**Issue by Michcioperz** [owncast/owncast#3130]
### Share your bug report, feature request, or comment.

I installed v0.1.0 last weekend and I added [tlapbot](https://github.com/SleepyLili/tlapbot) as an external action, but it seems that it's not receiving the instance and username parameters in the frame URL. It's not making it impossible to use, but the action was using the username parameter to display the number of points collected by the viewer.

I've compared the /api/config of my server and of two v0.0.13 servers I know to be using tlapbot and my action config doesn't stand out as different. So while I haven't had time to investigate the frontend code I'm assuming that's where the responsibility for adding the parameters lies.

For reference this functionality is mentioned [in the public docs](https://owncast.online/thirdparty/actions/) Best practices point 4 and 5

Thanks for making Owncast!

**Comment by gabek** [comment]
Thanks!
