### ISSUE TITLE
Chat: current edit messes with the caret (and more)

### ISSUE THREAD

**Issue by jprjr** [owncast/owncast#3131]
### Share your bug report, feature request, or comment.

Hi there, so while implementing chat-related updates, I've noticed a few things about react-contenteditable:

* It seems to override when it should render and does so at strange times
* it messes with the caret position
* it gets updated by overriding innerHTML
* it doesn't seem to fire change events when expected

For example, setting the current character count for the message length is somewhat strange. What would make the most sense to me is to have an onchange callback, and make that the sole place to recalculate the length of the current message. So when the emoji picker picks an emoji - append it and let the onchange handler update the count.

But - it seems like the onchange handler is delayed, so the character count is instead updated in the emoji picker callback. So now there's a few places where the character count is updated.

I'm not a react expert, but my gut says a more ideal implementation would do less blocking of rendering, and maybe avoid overwriting innerHTML and instead use DOM-based methods to append images and emoji. I'd imagine that's more efficient since you're no longer parsing the html, rendering to virtual DOM, then updating the real DOM, but instead updating the virtual DOM and (probably) applying changes to the real DOM immediately

This issue is to just explore the idea replacing the dependency, either with another module or writing a custom one. I think it may be possible to write a simpler implementation that allows the browser to behave more naturally.

**Comment by gabek** [comment]
It is janky. Content editable as a concept doesn't play nicely with React in the first place, but I honestly don't know how the zillion other platforms that render images inline within a text box do it without building out a full rich text editor from scratch or using a super bulky premade component. Neither of those things I'm particularly interested in doing.

Hopefully it can be good enough for a while, because I'm burned out on frontend stuff and I just don't want to work on chat anymore. Unless something is completely broken and unusable I'd prefer to backlog this for something new down the road.

**Comment by jprjr** [comment]
Oh! To clarify my intent was for me to explore it and track things here, since I've been poking around there anyway. I wouldn't mind at all to (try to) take this on, I've been enjoying working on the other chat stuff.

**Comment by gabek** [comment]
Even better, I appreciate it!

**Comment by jprjr** [comment]
I found [this example](https://stackoverflow.com/a/47148938) on stackoverflow of basically taking React out of the picture and using a MutationObserver. A few changes to CSS to make sure images aren't inserted as block objects (changing them to inline-block) and to change whitespace handling, and now I'm able to insert images, copy-paste, etc, and everything behaves about as expected, especially firing the change handlers. Branch here: https://github.com/jprjr/owncast/tree/chatbox-experiment

Everything about CI is probably failing because I'm just saving my work. I've only tested on Firefox and would have to test across a lot of other browsers but so far it seems pretty promising. Definitely some clean-up to do around formatting and type definitions.

<blockquote><img src="https://opengraph.githubassets.com/1664049dbb52d0bc953f58aec9968d5b874b39fb0bcab476c63ef49fc709f10e/jprjr/owncast" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/jprjr/owncast">GitHub - jprjr/owncast at chatbox-experiment</a></strong></div><div>Take control over your live stream video by running it yourself.  Streaming + chat out of the box. - GitHub - jprjr/owncast at chatbox-experiment</div></blockquote>

**Comment by jprjr** [comment]
Rebased on develop, fixed the CI issues (pretty sure, anyway) and pushed up some changes.

I haven't tested on anything besides Firefox and Chrome on desktop but so far:

* The cursor position is left alone.
* Inserting custom emotes doesn't insert random line breaks.
* Change events fire when expected.
* HTML sanitizing is moved into an onPaste handler. I figure that's where rogue HTML would enter the picture anyway, plus once you're handling it in an onchange handler, it's already been rendered. Doing it in a paste allows to sanitize before rendering.

@gabek if you could check this out and provide any feedback, I think this may be ready for a PR? It's probably not very react-y, but everything I've read about contenteditables in react seems like it's hard to really take advantage of react concepts. It's pretty much just a MutationObserver that fires callbacks when it detects the innerHTML has changed.

UPDATE: pushed up another round of changes that builds in production mode

**Comment by gabek** [comment]
Would you mind pushing this up as a PR?  It's just easier to test that way.

**Comment by jprjr** [comment]
Done! See #3146 

I wound up keeping the "update by overwriting innerHTML" aspect, even though I thought that may be an issue in my original comment. It seems like that concept is fine, I think the bigger issue was react-contenteditable deciding when to render
