### ISSUE TITLE
p2p streams

### ISSUE THREAD

**Issue by Pantyhose-X** [owncast/owncast#3134]
### Share your bug report, feature request, or comment.

Live streaming traffic will not have any data passing through owncast

All owncast users need to do is
1 Add Cover 
2 Add streaming address [hypercore://](https://github.com/holepunchto)
3 Click Finish Show cover on owncast
4 Click on the cover and the browser opens a new Tab, Watch Live

hyper protocols are good https://github.com/holepunchto

**Comment by janWilejan** [comment]
I've never heard of hypervision or dat before, but it looks like you want us to add support for a new protocol that's only supported by the now-defunct Beaker browser?

This seems wildly out of scope for Owncast.
