### ISSUE TITLE
Channel Points & Reward System

### ISSUE THREAD

**Issue by voidedmain** [owncast/owncast#3136]
### Share your bug report, feature request, or comment.

Hello,
coming from Twitch I really enjoyed the option to engage with my community, allowing them to trigger specific actions and creating a sense of participation.
The channel point & reward system is an excellent approach to this (imho), and I was wondering if such a feature is planned or would possibly get implemented in the future?

I did find [a project](https://github.com/SleepyLili/tlapbot) that aims to do this, but it's quite difficult to set up and from my understanding doesn't seem to be well integrated into the chat itself.

**Comment by gabek** [comment]
These types of features are outside the scope of Owncast, as it's only the infrastructure for you to build upon. Maybe you could talk to the person who runs that other project and help improve it together.
