### ISSUE TITLE
Add message removal feature in admin

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#314]
At some point post-0.0.4 we should think about adding chat moderating to the admin.

----
Edit: 12/16

- Add new chat page to admin that lists the chat messages.
- Add API for toggling the existing `visible` flag of messages.
- Create new websocket `UPDATE` event and send updated messages.
- Client should update its existing copy of these messages with the updated ones and re-render, filtering on `visible`.

**Comment by aaronpk** [comment]
frankly having a chat that's not behind any sort of authentication needs chat moderation yesterday. even just the ability to delete individual messages would be better than nothing.

**Comment by Gargron** [comment]
I'm assuming no moderation can be done until #321. I do wonder what's possible with no user accounts. I'm guessing any kind of kick, ban, or timeout would have to be IP-based.

**Comment by gabek** [comment]
Yeah, the wheels are turning, including adding a more robust identity for chat so we have both the IP address and a pseudo-user we can manage: https://github.com/owncast/owncast/discussions/440.  It's still being fleshed out, though.

0.0.3 is the first version with a web admin of any sort, so now we can start building management tools.

**Comment by aaronpk** [comment]
Fancier moderation and account stuff is great and all but please consider shipping a "delete message" feature ASAP before worrying about account/identity/etc stuff.

**Comment by shirt-dev** [comment]
There should also be an option to disable the chat completely.

**Comment by gingervitis** [comment]
I'll start looking into creating a UI to delete messages in the Admin sometime this week.

**Comment by gabek** [comment]
First pass at moderation is in master for the next release.
