### ISSUE TITLE
UI crashes when no codecs are found.

### ISSUE THREAD

**Issue by janWilejan** [owncast/owncast#3141]
### Share your bug report, feature request, or comment.

On a fresh install of chromium with no video codes enabled, this error pops up:

```rs
Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'on')

  103 | this.supportsDetailedMetrics = !!tech;
  104 | 
> 105 | tech.on('usage', e => {
      |     ^
  106 |   if (e.name === 'vhs-unknown-waiting') {
  107 |     this.setIsBuffering(true);
  108 |   }
```

A more user-friendly error message should show up: "No video codecs found. Please enable the h264 codec in your browser." (or whatever other codecs the server uses)

**Comment by gabek** [comment]
Is this from the playback metrics? If so it's not directly tied to the actual playback, it should probably just fail silently since it's just metrics. The player itself should deal with any playback errors.

**Comment by janWilejan** [comment]
Oh. You're right. Closing the error popup I see another message "No compatible source was found for this media." which is user-friendly enough imo. Assign me this.

**Comment by gabek** [comment]
Thanks for discovering this and looking at it! A browser without the codec enabled would have never crossed my mind.
