### ISSUE TITLE
GeoIP is broken after upgrading to v0.1.0

### ISSUE THREAD

**Issue by TinFoilFox** [owncast/owncast#3149]
### Environment
Docker
### Owncast Version
v0.1.0-linux-arm64
### Owncast Log File
[owncast.log](https://github.com/owncast/owncast/files/11984185/owncast.log)
### Expected Behavior
When viewers join a stream their approximate region should appear in the admin dashboard.
### Current Behavior
When viewers join a stream, no location data is shown. When checking the logs various entries of
`level=warning msg="IP passed to Lookup cannot be nil"`
can be seen.
### Steps to Reproduce
1. Download latest GeoIP database and add it to the owncast folder.
2. Start a steam and have viewers watch your stream.
3. Check the admin dashboard.
### Additional Info
This started happening after I upgraded to Owncast v0.1.0 from Owncast v0.0.13. GeoIP was working correctly before updating. I thought at first that maybe my database was out of date so I updated to the latest version but it didn't seem to do anything? Did GeoIP change at all in the v0.1.0 release?

**Comment by gabek** [comment]
I don't recall anything changing with it, but I'll take a look and report back. I've always wanted to write tests around this since it doesn't get looked at often, but I can't bundle the database in with the code, so it's always been a fuzzy area about how I could pull this off.

**Comment by gabek** [comment]
It seems to be working ok in my testing. Is there anything different in your setup you might think of? Are you using the `GeoLite2 City (GeoIP2 Binary .mmdb)` database?

![image](https://github.com/owncast/owncast/assets/414923/f9f8a886-7226-4956-802c-05a6213e9e7d)

![image](https://github.com/owncast/owncast/assets/414923/5939742b-f4af-4054-b3d9-631a8db42b7c)

**Comment by TinFoilFox** [comment]
This is how I have my data folder laid out.
```bash
ubuntu@oracle-vm-1:~/.docker/owncast$ ls -l
total 72180
-rw-rw-r--   1 root root 71034851 Jul 15 22:27 GeoLite2-City.mmdb
drwxrwxr-x   2 root root     4096 Jun  2 13:03 backup
drwxr-x---   6 root root     4096 Jun  2 13:03 emoji
drwxr-x---   5 root root     4096 Jul  7 22:13 hls
-rw-rw-r--   1 root root   178920 Jul  7 12:07 logo.jpeg
-rw-rw-r--   1 root root  1671141 Sep  9  2022 logo.png
-rw-rw-r--   1 root root    98859 Jun  8  2022 logo.svg
drwx------   2 root root     4096 Jul  7 13:36 logs
drwxr-xr-x 327 root root    20480 Jul 15 22:00 metrics
-rw-rw-r--   1 root root   172032 Jul  7 13:36 owncast.db
-rw-rw-r--   1 root root    32768 Jul  7 22:08 owncast.db-shm
-rw-rw-r--   1 root root   675712 Jul  7 22:08 owncast.db-wal
drwx------   2 root root     4096 Jul  7 22:13 tmp
```
I enabled the `-enableVerboseLogging` flag to see if it would reveal anything but it didn't seem to give any new info.

[verboseLog.log](https://github.com/owncast/owncast/files/12063274/verboseLog.log)

I download and replaced the `GeoLite2-City.mmdb` today to see if it made a difference but I still get `IP passed to Lookup cannot be nil` errors. I made sure to chown the file to root just in case it was permission issues somehow but that didn't make a difference.

![image](https://github.com/owncast/owncast/assets/15332259/5e516098-947b-4716-a3dd-ca422831da2c)
![image](https://github.com/owncast/owncast/assets/15332259/2bf3cd2d-b4fd-40e2-b440-455fad8f5e01)

**Comment by gabek** [comment]
Is this for both viewer data and chat users?

**Comment by TinFoilFox** [comment]
Ah I figured out the problem, you'd probably never have guessed it but it was actually user error on my part.

Around the same time I upgraded to v0.1.0 I also enabled cloudflare on my instance. I am using S3 to deliver the video so I figured it would be fine, since the video chunks wouldn't be going through the cloudflare proxy. Disabling cloudflare solves the my issue and I'll make sure to close it.

As a side note, some things that should have tipped me off were:
1. Viewer IPs couldn't be looked up.
2. Viewer numbers were wonky and often inflated. Each viewer would count as two viewers.

Thank you for your time :)

**Comment by gabek** [comment]
Oh yeah, I hope to improve viewer counting with CDNs, but there's no perfect answer for all scenarios. I filed this in case you're interested in following along: https://github.com/owncast/owncast/issues/2627

**Comment by rafalohaki** [comment]
have the same problem, using proxy behind cloudflare

**Comment by gabek** [comment]
There's not much you can do in that case. If the viewer doesn't actually get to your Owncast server, then there's no way for Owncast to give you proper details about the viewer. You'd have to get that information from Cloudflare.
