### ISSUE TITLE
[docker] 0.1.0 doesn't know what to do with /data from 0.0.13

### ISSUE THREAD

**Issue by working-name** [owncast/owncast#3150]
### Share your bug report, feature request, or comment.

Hello there,

Trying to upgrade to 0.1.0 but keep the prior settings and users. When I leave `./data` in place, I get an empty reply when I start the container. I tried manually overwriting just the owncast.db and leave the rest alone, still no go.

Also, I am unable to see where `-streamkey` and `-adminpassword` startup flags are documented. I found the first flag in some other issue and I guessed the second one. 😬 

Is there an upgrade procedure that I'm missing?

Thanks for your help!

**Comment by gabek** [comment]
Nope, there's no upgrade procedure. Keep your `data` directory where it is and just run the new Owncast binary.

I can't say I know what's going on there. What do you mean by "empty reply"? Are there any logs? Something must be happening. If the container is literally not starting at all then it sounds like a larger problem. If you get a shell into your container and run owncast manually, what happens?

And if you run `./owncast --help` you'll see all the CLI flags.

**Comment by working-name** [comment]
Nothing logged on the problem, and it doesn't complain about migration steps. Anything else I can pull?

https://github.com/owncast/owncast/assets/16505052/147394cf-022d-422c-9ce7-efdd21cc6308

Running this with `-enableDebugFeatures` just gives some more `.go` debug info about workers being started but no other logged events outside of that.

If I load the page in the browser the same thing is said - empty response. /admin included.

**Comment by gabek** [comment]
Oh you mean an empty response in the browser, not the container. So the container looks like it is starting properly? Then it sounds like a networking thing if it's running but you can't access it.

Did you mean to start Owncast listening on port `18080` and not 8081?

**Comment by working-name** [comment]
The `18080` is a typo probably - old config from old `./data` or your startup script? 
(There's also a typo in the version - two vv: `[vv0.1.0](main.go:72 main.main() Owncast vv0.1.0-linux-arm64)`)

My command has `-p 8081:8080` which is what I intended. There's nothing listening on port 18080 on my system at the moment:

```py
% lsof -i :8081 && if ! lsof -i :18080; then echo "Nothing listening on 18080"; fi
COMMAND    PID   USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
com.docke 3062 zeeman  279u  IPv6 0xfe74cb6a0c391271      0t0  TCP *:sunproxyadmin (LISTEN)
Nothing listening on 18080
```

I am not sure it's a networking thing, since I can just run the same container without `./data` in place and it's able to generate a fresh install copy and everything loads fine - both streaming and admin interfaces.

**Comment by gabek** [comment]
I mean it shows Owncast is listening on port `18080`, not your host machine. If you made a typo once and saved the new port then Owncast will save it and keep using it. Set a new port through the CLI flags if you need to change it.

![image](https://github.com/owncast/owncast/assets/414923/04367d30-1db1-480f-9213-538d84672a35)

**Comment by working-name** [comment]
Yes!!! You smart, smart person. Thank you. I just swapped `-p 8081:18080` and it's loading fine. Glad it was just me. Great job on the new interface, it's so sleek!

Thank you for your time!
