### ISSUE TITLE
DisplayName Unicode Handling

### ISSUE THREAD

**Issue by jprjr** [owncast/owncast#3159]
## Current situation

Using unicode in the displayname is a bit broken. In my explanations I'm using emoji, just because I know they're Unicode characters that can take up several codepoints, but this all applies to Unicode text characters as well.

The input box enforces a maximum character length, and I'll be honest, I'm not sure how that's being measured, it's not really accurate when you get into more complex emoji clusters like 🫱🏿‍🫲🏻 - that takes up 9 UTF-16 code points, and 19 bytes in utf-8. The name change box reports the length as 5. And doing things like pasting past the character limit causes the emoji to be broken up.

Assuming the dialogue box determines the string is an acceptable length - the server-side processing caps the string based on the number of bytes, and can then send back broken Unicode if it removes the final bytes of a UTF-8 sequence.

## Proposal

I did some quick prototyping and would like to propose a few changes:

Client-side:

* remove the maxCount property from the name change field to prevent breaking/splitting input.
* replace the "showCount" with a custom implementation that counts grapheme clusters (so things like "🫱🏿‍🫲🏻" count as 1).
* allow username input to go over the max characters but disable sending once over, similar to the current chat box.

Server-side:

* Update MakeSafeStringOfLength to count the length using [uniseg](https://github.com/rivo/uniseg), and remove whole grapheme clusters rather than bytes, which ensures no broken Unicode is sent back.

If this all sounds good, assign me the issue and I'll get everything cleaned up and get a PR going!

**Comment by janWilejan** [comment]
There's no need to rewrite the character counter. "🫱🏿‍🫲🏻" should be counted as 5 characters (hand emoji, skin color, ZWJ, hand emoji, skin color), not 1 grapheme. If that puts too strict a limit on usernames, we can increase the maximum character length of a username.

Likewise on the server, MakeSafeStringOfLength should convert from string to rune[], truncate to N characters, and convert back to string (at least that's how I'd do it in rust; I don't know go). This may break up graphemes in edge cases, but will never result in invalid unicode codepoints. 

I agree with the UI changes you propose

**Comment by jprjr** [comment]
> There's no need to rewrite the character counter. "🫱🏿‍🫲🏻" should be counted as 5 characters (hand emoji, skin color, ZWJ, hand emoji, skin color), not 1 grapheme.

I don't think most users are aware of how their emoji are composed. The reason I looked into this and opened the issue was due to a user adding an emoji to their username and not understanding why it counted as more characters, and why it came back broken, etc. For them it was very confusing, and their reaction was generally "why isn't owncast handling my emoji properly?" I'll be blunt - they just plain don't care about the technical details behind 1 emoji counting as 5 characters.

So with that background/UX perspective, I'd like to politely ask: why it should count as 5 and not 1? And how does that get communicated to users?

I understand from a database perspective, not wanting to blow the storage size up with crazy, 4kb grapheme clusters. And maybe that could result in a different error?

**Comment by janWilejan** [comment]
A user never needs to know the length of their username; they only need to know if it's too long. We should not display the username length limit until the limit is reached. The only way users would be confused by this is if our username length limit is too low (which perhaps it is, currently) and a seemingly "normal"-length username gets rejected.

Counting length in unicode codepoints is the simplest way to make sure it's being counted the same on the client and the server. If you want to use graphemer in JS and uniseg in go, you're going to need to make them agree on grapheme length: it looks like latest graphemer uses unicode 15 while latest uniseg uses unicode 14.

**Comment by jprjr** [comment]
> We should not display the username length limit until the limit is reached.

Oh there's an idea - if you overwrite the showCount function, you can have it return any arbitrary text. So maybe instead of showing the count, it would only return some text when the name is too long? (Along with the other hints of the button going into the disabled state)

**Comment by gabek** [comment]
I think that's a great idea. Most people's names probably aren't that long anyway, so showing the count is just another data point most people won't care about, and then it doesn't matter how we count characters.

Thanks for the productive discussion around this, it would be a nice improvement for sure.
