### ISSUE TITLE
Monitor HLS content and warn if it's not updating

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#316]
If HLS playlists are not being updated with new segments after `(segmentLengthSeconds * 3)` seconds then log out a warning.

We should be able to keep track of this and warn from the `HLSHandler`.

**Comment by jmhobbs** [comment]
Can I give this one a try?

**Comment by gabek** [comment]
Yeah, absolutely!  The HLS pipeline was reworked since 0.0.2 so let me know if you run into anything weird or something isn't looking as you'd expect.

**Comment by jmhobbs** [comment]
Is there a known way to trigger this condition?  I think I have a working monitor, but I've yet to find a way to introduce delay in the write events.

I suppose I could synthetically lag those in `core/ffmpeg/fileWriterReceiverService.go`?

**Comment by gabek** [comment]
Unfortunately I can't think of anything that would trigger it offhand, so a certain amount of fakery is probably needed.  

Maybe decrease the duration between checks?  Like if segments are being written every 4 seconds, then if you hard code it to check every 1 second then it should fail.  Otherwise maybe testing it externally of the real flow is fine.  Maybe hardcode the path it's monitoring to a file you can control externally or something?

Thanks for looking at this!  HLS alert on these non-updating playlist states, so alerting on it server-side too will be a big help to know if something is wrong.  And with the admin these types of errors should start to be more visible.

**Comment by jeyemwey** [comment]
I'm not sure if you can emulate this, but would this be triggered if the hard drive is running full and thus, new files cannot be written to disk?

**Comment by jmhobbs** [comment]
That’s a thought. I’ll implement a synthetic test in Go, and then tinker with Fuse for fun 😄 

Second question, should it discern between writes to variants and track them individually? How about the master list, that is just written at the initial setup right? It never contains segment information anyway, just variants?  Sorry for all the questions!

**Comment by gabek** [comment]
Good questions!  For variants, I think it's most likely that whatever would cause a single variant to break would be happening across the board at the transcoder level.  So I think it's fair, either way that makes sense to you.  I can't think of a case where only one variant would die but not another.

There's a (pretty simplistic, in `performanceTimer.go`) warning already that alerts if the duration between two variant segments being generated is seen to have taken a long time, but that's more of a scenario where everything is working fine and generating video, but it's taking longer than maybe it should be.  If video isn't being generated at all (for whatever reason) then that falls into this different warning scenario.

It's kind of weird dealing entirely with hypotheticals, because alerts like this I don't have concrete examples for.  More of a "if something were to go wrong, here's a side effect of it".  To add some context, the other day `watch.owncast.online` was "live", but was repeating the same segment over and over again.  It was the first time I had seen something like that, after it was running non-stop for weeks.  So I don't know why it happened, or what was happening, but I do know the result of it was the server still being seen as everything working fine, but the content just not updating.  So that's when I thought this would be a good addition.  If it happens again hopefully I can catch it and try and track it down.

As for the master playlist, that's exactly right.  It gets created once and then won't update again.  So no need to worry about that one.

**Comment by jmhobbs** [comment]
Sorry, been out of the loop, not enough bandwidth and too much going on.  Is this still a valid concern?  If so I can get the PR fixed up.

**Comment by gabek** [comment]
Oh crap! Sorry you said something before and it slipped under the radar.  Since some time passed and any initial concerns around this problem seem to have not manifested itself, we can probably just let this go, but I'll come back to it if the need arises.  Sorry you put work into this and it never got in.
