### ISSUE TITLE
Hidden messages are not hidden unless the page is refreshed

### ISSUE THREAD

**Issue by janWilejan** [owncast/owncast#3166]
### Share your bug report, feature request, or comment.

1. Type a message in chat
2. Hide that message using moderator tools or via /admin/chat/messages
3. The message should be hidden on all clients

Currently the message does not get hidden unless the client refreshes the page

**Comment by gabek** [comment]
That's a bug, they're supposed to hide automatically. I'll check it out. Thanks!
