### ISSUE TITLE
Heads-up: admin error with swc and the @lezer/markdown package

### ISSUE THREAD

**Issue by jprjr** [owncast/owncast#3168]
### Share your bug report, feature request, or comment.

I downloaded the latest commit and saw when I went into the /admin general config, the javascript console had an error about an invalid left-hand assignment - the minified code was trying to assign a value to zero. As a result, I can't really change any settings in the general config.

I tracked it down to this issue here: https://github.com/swc-project/swc/issues/7640

Just wanted to give a heads-up, in case anybody else hits that same issue.

**Comment by jprjr** [comment]
One temporary work-around would be to disable swc minification by setting `swcMinify` to false https://github.com/owncast/owncast/blob/47368731d6b8e87f48ac368091b9a02b7a554444/web/next.config.js#L35

Verified that building with that change causes everything to work again. Unsure how it affects module sizes and whatnot.

**Comment by janWilejan** [comment]
It looks like this has been fixed upstream

**Comment by gabek** [comment]
Thanks guys!

**Comment by jprjr** [comment]
It's been fixed in swc - but it seems like nextjs distributes their own bundle, has it been fixed there? Last I tried I couldn't use the production build of the admin interface.

**Comment by janWilejan** [comment]
Sorry. I closed this prematurely, thinking it would be fixed automatically by the renovate bot. I manually bumped the version of nextjs in #3177
