### ISSUE TITLE
Appearance Settings resetting after page reload

### ISSUE THREAD

**Issue by SylvanRover** [owncast/owncast#3170]
### Share your bug report, feature request, or comment.

After setting a custom colour scheme for the Section Colours and Chat User Colours the UI resets it back to the default palettes. The changes I made and saved are still present on my stream page, however, if I want to customise one item again, I have to redo all the colours as they've been set back to default.

**Comment by gabek** [comment]
Could you add some steps on how to reproduce this?

**Comment by SylvanRover** [comment]
Apologies, I should have added that in description. Though it wasn't anything too complicated.
1. Change the colours and save.
2. Check the website and notice the colour changes (huzzah!)
3. Go back to the admin panel but load a different page
4. Go to the General settings Customize Apperance and notice the colours in the settings UI are back to the default. (colours on the site are still fine)

That being said, I've now gone back to the page and it seems to be my updated colour palettes again but I hadn't touched anything. So I'm not sure what happened. Maybe I had two tabs open and had changed it in one and the other page had the old info. But I did do a page refresh just to make sure.

**Comment by gabek** [comment]
Thank you!
