### ISSUE TITLE
Don't IP ban localhost

### ISSUE THREAD

**Issue by janWilejan** [owncast/owncast#3172]
### Share your bug report, feature request, or comment.

to reproduce:
1. Connect to an Owncast server running locally and make this account moderator.
2. Connect again using a separate browser or container tab.
3. Ban the second user.
4. Both users are banned.

Owncast makes IP bans by default, but we never need to ban localhost (127.0.0.1 or ::1).
Banning local users is sometimes useful for testing, but it shouldn't IP ban all local users.

**Comment by mrsoong** [comment]
Hi there. I'm new to open source and owncast. Can I work on this issue?

**Comment by janWilejan** [comment]
Sure thing! Let me know if you have any questions.

**Comment by mrsoong** [comment]
@janWilejan Thanks for letting me work on this issue! I just looked into the code, and it seems that owncast is effectively banning all local users when it tried to ban the second local user with the IP address ::1 here: https://github.com/owncast/owncast/blob/bc96f198c4bf8a0ee1f7e4257d500d364e6819f1/controllers/admin/chat.go#L171

Is the desired behavior to differentiate between local users using their ports when bans are saved and enforced?

**Comment by janWilejan** [comment]
There's no need to look at ports. The user account still gets banned (chat.go line 133). Just wrap the calls to `BanIPAddress` with an if statement looking for 127.0.0.1 on ipv4 and ::1 on ipv6.

**Comment by mrsoong** [comment]
Right, so we just have to enforce the User Ban, but not the IP ban for local users. Thanks for pointing that out.
