### ISSUE TITLE
Add config setting for enable/disable version upgrade checks

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#318]
With the admin we'll have the real estate to display messages for the first time that don't get in the way as if we were to spam the console with things.

One useful message is to mention when a new release is available, so they know they can upgrade.  We could simply use the [Github releases API](https://developer.github.com/v3/repos/releases/#get-the-latest-release) and offer the change log/release notes to tell them what's new.

The downside of this would be that I don't want the impression that we're "phoning home" for anything.  This would purely be so people know about new releases so new features can get out into the wild faster.

I guess we could have a button somewhere that says "check for update" and no call is made unless you press it.

What are your thoughts?

**Comment by gabek** [comment]
It only took me a couple minutes to throw it together to see if it's useful or not.  Can always remove it or put it behind something or another.

![image](https://user-images.githubusercontent.com/414923/97945332-0ee40580-1d3c-11eb-9adc-5446ef1c1f44.png)

**Comment by gingervitis** [comment]
Is it possible to know what release you're currently using?

**Comment by gabek** [comment]
Yup, I'm only showing it if the available release is newer than your current release.  But that still requires making an API call that could come off as "phoning home".

**Comment by geekgonecrazy** [comment]
I’d say as long as can turn it off this is an acceptable thing.

**Comment by geekgonecrazy** [comment]
Part of me wonders though if there is a way that GitHub will tell you some how unique checks for updates.  Cause seeing how many copy’s spin up would be a very interesting metric.

Honestly one I’m typically ok with for projects to do as long as they aren’t sending my personal info.  It’s a good way for a project maintainer to see their project is actually being used.

**Comment by gabek** [comment]
I think that makes sense.  On by default, but easy to turn off.  The opposite of the YP API pings that are off by default.

I don't think we can get any count of API requests from GitHub.  One thing I've had in mind is the directory being one way for people to publicly say they want us, and everyone else, to know they're running an instance.  But that's different than us knowing in aggregate the number of installs.

We could proxy the GitHub API request through something to count, but I feel like that's somehow different, from a privacy aspect, than going directly to GitHub.  Though in practice it doesn't matter because people won't know or care, probably, where that call is going.  They either are ok with it or they aren't.

We can get a number of asset downloads from GitHub, and number of pulls from Dockerhub, but that only answers the question of how many downloads.

**Comment by gabek** [comment]
Done.
