### ISSUE TITLE
Showing number of viewers

### ISSUE THREAD

**Issue by athavale-anant** [owncast/owncast#3190]
### Share your bug report, feature request, or comment.

Hello,

I have set up this new version and used it in the Intranet environment successfully. 

I have 2 requirements.

1. If I use the embed video option, it won't show the number of viewers.  It used to show in earlier versions.  But, it will show, if I view the entire site with port 8080.  Is it possible to add in some other way, the number of viewers along with embedded video?

2. If it is not possible to show the number of viewers along with embedded video, I will use the entire website with port 8080.  But, I would like to hide Powered by owncast and links for documents etc as it is hosted in Intranet and none of the links will work.

**Comment by gabek** [comment]
Does it not show, or is it not visible? I'm guessing you're seeing #3104 where it renders the status bar outside of the frame's viewport.

As far as changing the UI, you're able to hide or modify anything you like with CSS. Read more in our documentation: https://owncast.online/docs/appearance/

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="https://owncast.online/favicon.png" height="14"> Owncast</div><div><strong><a href="/docs/appearance/">Customizing appearance</a></strong></div><div>Customize the appearance of your Owncast instance.</div></blockquote>
