### ISSUE TITLE
URL is broken on calkey / firefish

### ISSUE THREAD

**Issue by janWilejan** [owncast/owncast#3195]
### Share your bug report, feature request, or comment.

The last hashtag and url in the "going live" notification posts are mashed together on calkey/firefish and probably other forks of misskey.

```c
#retrogaminghttps://live.vencabot.com
#experimentalMusichttps://stream.gravitons.org
#splatoonhttps://live.kemonomimifan.club
```

**Comment by gabek** [comment]
I wonder why. Do you have the HTML it's trying to render?

**Comment by janWilejan** [comment]
It looks like it translates into Misskey Flavoured Markdown and back into HTML?
I don't have my own *key server to test with, so idk what the intermediate steps are, but the input is: activitypub/outbox/outbox.go:63

```go
<p>%s</p>%s<p>%s</p><a href=\"%s\">%s</a>
```
and the output replaces the `</p><p>` with `<br><br>`
