### ISSUE TITLE
Reduce idle resource usage - Don't run ffmpeg while not streaming.

### ISSUE THREAD

**Issue by janWilejan** [owncast/owncast#3209]
### Share your bug report, feature request, or comment.

1. run owncast with `go build && flamegraph -- ./owncast`
2. wait a minute or so. don't stream anything.
3. ffmpeg is running in 72% of the samples (2000 samples taken).
![image](https://github.com/owncast/owncast/assets/119548498/88133d03-29a3-498e-b3a6-68a0786df89e)

Ideally, ffmpeg should not run when the server is not streaming. Owncast should listen on rtmp port 1935, wait for incoming connections, and when stream starts, it starts ffmpeg and pipes the stream as usual. When the stream ends, ffmpeg is killed.

**Comment by gabek** [comment]
How you expected it to work is how it should be working now. As a sanity check I started a stream, stopped the stream, and 

```
$ ps aux |grep ffmpeg
gabek     513019  0.0  0.0  18880  2424 pts/0    S+   15:55   0:00 grep --color=auto ffmpeg
```

ffmpeg is not running. Are you sure you don't have some other process that might be taking advantage of it for something? What is the actual execution of ffmpeg do you see? What's it doing?

**Comment by janWilejan** [comment]
Yeah. Looking at the code, it seems it *should* be working as I expect, but flamegraph disagrees?

Looking at the output of `strace -f ./owncast`, I see that it *is* running ffmpeg, even though a stream hasn't started.

```go
[pid 28279] execve("/usr/bin/ffmpeg", ["/usr/bin/ffmpeg", "-hide_banner", "-loglevel", "warning", "-fflags", "+genpts", "-flags", "+cgop", "-i", "./data/tmp/offline.ts2544222468", "-map", "v:0", "-c:v:0", "libx264", "-b:v:0", "208k", "-maxrate:v:0", "224k", "-g:v:0", "120", "-keyint_min:v:0", "120", "-r:v:0", "24", "-x264-params:v:0", "scenecut=0:open_gop=0", "-bufsize:v:0", "224k", "-profile:v:0", "high", "-map", "a:0?", ...], 0x56d459b3b3d0 /* 54 vars */ <unfinished ...>
```

Since it's being run with `execve`, it would show up as just another ./owncast thread in ps or top. My `ps aux | grep ffmpeg` shows the same as yours.

**Comment by gabek** [comment]
The handling of that offline segment, as it looks like in that log above, takes place 5 minutes (I think?) after the stream ends. So that is something that happens after a stream is completed, but it's a very short operation to change the stream over from the previous live stream to completely offline.

**Comment by janWilejan** [comment]
Oh. Yup, That's what this is. The offline.tscilp is being transcoded when the server starts up. If I attach flamegraph to owncast after that, flamegraph shows it spending all its time sleeping and polling for network requests, as expected.

Sorry for bothering you with this. I was barking up the wrong tree here 😅.
