### ISSUE TITLE
Limit who can connect to the chat websocket

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#321]
Our websocket is currently completely open.  Anybody, from anywhere, can connect to it and send messages if they know the simple JSON payload that would allow them to send fake system messages, flood the UI with automated junk, or send invalid payloads to break the UI.

This should be locked down where only Owncast web clients can be allowed in, but with the ability to allow specific 3rd party clients (such as any automated scripts we are running in our own infrastructure or if somebody wants to build their own chat UI).

I'm sure this is a solved problem with some simple solutions out there, but I've yet to do any research.  Please chime in if you have thoughts!

**Comment by shirt-dev** [comment]
This could be fixed by adding user based authentication and simple moderation features.

**Comment by gabek** [comment]
> This could be fixed by adding user based authentication and simple moderation features.

Hi @shirt-dev!  That's a bit of a different topic.  This is more from the websocket connectivity standpoint, to make sure external clients aren't connecting.  Not about the act of chatting or the content of payloads.

**Comment by shirt-dev** [comment]
Oh, I meant that with authentication, Authorization headers could be added.

**Comment by gabek** [comment]
Removing this from the chat moderation milestone since we don't want to hold up releasing that feature for this.

**Comment by gabek** [comment]
I'm going to hold off on this until we have our 3rd party in/out APIs available.  I know some people are tying into the chat for scripts and stuff, and if we locked it down then their stuff would break.  So it's best just to build looking to the future and offer those new options at the same time as securing the socket.

**Comment by gabek** [comment]
In discussing #887 it might just make sense to pass along the new access token (generated when a user is created) as a part of the initial websocket connection using the `protocol` field.  We already take advantage of this place to put a bool to state if a connection should not be counted as a viewer.  Any connection without a valid access token gets dropped.
