### ISSUE TITLE
Feature Request: log IP address when stream key is rejected

### ISSUE THREAD

**Issue by jprjr** [owncast/owncast#3212]
### Share your bug report, feature request, or comment.

The idea being, if I start seeing unexplained entries in some logs for failed streaming attempts, I can take an action - block an IP address, report abuse to a network, etc.

**Comment by gabek** [comment]
Good idea!

**Comment by jprjr** [comment]
You know it might be a good idea to log it either way.

That way, if your stream key gets leaked or something, in addition to resetting the keys you can block the IP as well.
