### ISSUE TITLE
Z-Index problems in mobile web layout

### ISSUE THREAD

**Issue by janWilejan** [owncast/owncast#3215]
### Share your bug report, feature request, or comment.

The `.Content_mobileActionButtons` is hidden behind the header and overlaps with the `#user-menu`.

The `#mobile-chat-button` is hidden behind the statusbar (this only happens on squarish resolutions like 700x600)

**Comment by janWilejan** [comment]
I'm not quite sure where the ideal place for these buttons is, but perhaps we could put them all in the header? Breif mockup:

![image](https://github.com/owncast/owncast/assets/119548498/ea0605e0-b441-4207-b84b-6a5c43b196a1)

**Comment by gabek** [comment]
The mobile chat button already just kind of floats there at an arbitrary position, we could move it any direction to make it work specifically on these rarer resolutions and leave it alone for everything else, since it seems to work for "normal" devices.

The header wouldn't work simply because if the title is even a little bit long it would run out of room. Plus I don't think it looks that great.

We could also just remove things for really rare resolutions. If almost nobody has a device that it would impact anyway, then it's probably not a huge loss to remove the buttons all together.

**Comment by janWilejan** [comment]
> The header wouldn't work simply because if the title is even a little bit long it would run out of room. Plus I don't think it looks that great.

We could reduce the font size a little on mobile. The title has `text-overflow: elipsis` already. We could make it look nice.
> We could also just remove things for really rare resolutions. If almost nobody has a device that it would impact anyway, then it's probably not a huge loss to remove the buttons all together.

The big problem here is that the mobile action buttons are totally hidden at all times on mobile at all resolutions. That means you can't follow the stream on mobile. 

Technically this is 2 issues, but I lumped them into 1 because they could probably be solved together.

**Comment by gabek** [comment]
Ugh, the mobile action button menu is broken again? It's supposed to be in the upper right of the info section.  I wonder what happened. This mobile layout has been a real problem for many months to make it work right, and it sucks that even after it came to a pretty ok place it's not working correctly. 

At least this should be an easy fix to put the menu button where it should be.

![image](https://github.com/owncast/owncast/assets/414923/4a4ae224-8515-4d62-a503-eec1ad5a154f)

**Comment by gabek** [comment]
I'll be fixing the bigger issue here, the action menu button, this afternoon and I'll probably split these two issues out so the rarer issue doesn't block us from getting things out.

**Comment by gabek** [comment]
Action button menu addressed in #3217.

**Comment by anniepauline** [comment]
Open to work on it!

**Comment by gabek** [comment]
@anniepauline Fantastic, thank you!

**Comment by anniepauline** [comment]
Hey @gabek!!

Is it necessary to get the backend prerequisites installed in order to work on the front end?

I just installed the frontend dependencies and, it ran into 3 errors. 
<img width="701" alt="image" src="https://github.com/owncast/owncast/assets/58879804/39580f22-1cf2-437b-8943-a7eea1aa7079">

**Comment by gabek** [comment]
Hi, @anniepauline. Yes, if you run the full web application, then it needs to be able to talk to the backend.

However, we also use `Storybook`, a way to build isolated UI components without a backend. However, not everything is testable in Storybook. That mostly makes sense for standalone components, you can't test full functionality. This particular layout I don't believe would be in Storybook, but I could be wrong.

There's more detail about the development specifics at: https://owncast.online/development/

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="https://owncast.online/favicon.png" height="14"> Owncast</div><div><strong><a href="/development/">How to work on Owncast</a></strong></div><div>The technical details for those wishing to take part in Owncast development.</div></blockquote>

**Comment by anniepauline** [comment]
@gabek I see the action menu overlapping on the chat button for 700*600 dimensions. As the screen is pushed up, the chat button disappears behind the video section.
Is this what I must work on?
<img width="446" alt="image" src="https://github.com/owncast/owncast/assets/58879804/8bd36183-4b00-44c6-91df-4f8f8209b0ff">

**Comment by gabek** [comment]
Yup! It should move with the page and be in that upper right of the bottom content. In-line with tabs when tabs are visible, but in that same spot even if there are no tabs.

![image](https://github.com/owncast/owncast/assets/414923/fbb3e500-3554-497d-9dab-28fadbf885d0)

**Comment by gabek** [comment]
I believe this is an old issue that is no longer relevant.
