### ISSUE TITLE
Windows installers so owncase can be distributed by certain windows repositories

### ISSUE THREAD

**Issue by luzpaz** [owncast/owncast#3218]
### Share your bug report, feature request, or comment.

Would it be possible for owncast to be available with an installer like .msi or NSIS (instead of being zipped in to an archive?)

Reason: (this is winget https://github.com/microsoft/winget-pkgs)
![Screenshot_20230728_191242](https://github.com/owncast/owncast/assets/4140247/2828d685-435a-4a1c-a5ed-a8c0616967ea)

**Comment by gabek** [comment]
Currently Owncast isn't compatible with Windows at all, so it's unlikely a Windows installer will be built unless we had official support.

If you wish to use Owncast under Windows right now the best bet is to follow these instructions using WSL2: 

https://github.com/owncast/owncast/blob/develop/contrib/owncast_for_windows.md

Maybe some day if we had somebody who wanted to spearhead Windows support it could change. Sorry about that!
