### ISSUE TITLE
Logo doesn't change 

### ISSUE THREAD

**Issue by ossloom** [owncast/owncast#3219]
### Share your bug report, feature request, or comment.

Hi,
I am using ubuntu server with casaos 
i installed owncast with docker and every time i try to change my logo is says success and i can see it in the folder that i installed owncast in 
but after refreshing the page it disappears and return to the default logo 
is there any fix for that ?
![bug owncast](https://github.com/owncast/owncast/assets/87249965/4408601e-e6ed-45c1-bcfb-924e976e605b)

**Comment by gabek** [comment]
Your old one is probably cached. Either wait for your browser cache to expire, manually clear your cache and/or force-refresh your browse and see if that helps.

**Comment by ossloom** [comment]
![own 2](https://github.com/owncast/owncast/assets/87249965/2cb542c8-6263-4e62-8a4e-793bbcdb446c)

**Comment by ossloom** [comment]
![own 2](https://github.com/owncast/owncast/assets/87249965/58911436-2c7a-4e63-80f8-a85176a65d4e)

**Comment by ossloom** [comment]
i even tested that with docker desktop on windows and its the same

**Comment by gabek** [comment]
Did you try what I suggested? I'm not sure I understand what Docker has to do with your logo.

**Comment by 10leej** [comment]
Can confirm it's likely a cache issue.

**Comment by flo333** [comment]
Had the same problem - it's the browser cache.

**Comment by techniker** [comment]
Same problem here..

**Comment by gabek** [comment]
@techniker Solution is detailed above regarding your browser cache.
