### ISSUE TITLE
The issues here I have is the app insite on how to work on platform 

### ISSUE THREAD

**Issue by Kpaayesamuel** [owncast/owncast#3227]
I really love these platform and will like to learn more

**Comment by gabek** [comment]
Do you have any specific questions? If you'd like to learn more about developing Owncast perhaps this is helpful: https://owncast.online/development/

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="https://owncast.online/favicon.png" height="14"> Owncast</div><div><strong><a href="/development/">How to work on Owncast</a></strong></div><div>The technical details for those wishing to take part in Owncast development.</div></blockquote>
