### ISSUE TITLE
Updating server details are not reflected in the UI when social features are enabled

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3229]
### Share your bug report, feature request, or comment.

It was mentioned to me that the flow for adding/managing tags in the admin isn't a great experience and doesn't provide feedback.

**Comment by gabek** [comment]
I was unable to reproduce any issues here. I'll have to get more information. @silksow can you help provide details?

This is what I see in my testing of tags:

1. Click on the tag input text box
2. Type in a tag string
3. Hit enter
4. The tag shows up in the list
5. "Tags updated" success message shows.

**Comment by silksow** [comment]
In Firefox and (flatpak) Brave on Fedora Silverblue, I can reach step 4 on reloading the page although it can take multiple tries, but I don't get the message in step 5 in either browser since 0.1.1

**Comment by gabek** [comment]
Are there any messages in your error console?

**Comment by silksow** [comment]
No, I'm afraid not.

**Comment by gabek** [comment]
If anybody else sees this, I'd love if you could report back if you're having issues with tag management as well, since in my testing I haven't been able to reproduce this.

**Comment by germainelee** [comment]
This is what I do and see when testing tags in admin:

**Add tags:**
1. Navigate to Configuration -> General
2. Click on the tag input text box
3. Type in a tag string
4. Hit enter once
5. Nothing happen
6. Hit enter multiple times and nothing happens
7. Reloads page
8. The tag shows up in the list
9. "Tags updated" success message did not show

Not sure if this message in inspect console is normal.
![image](https://github.com/owncast/owncast/assets/118464031/491892ca-7985-49cb-a23f-acb66daf4ae7)

Note: it doesn't work on mobile but that's not the main focus here
<hr>
Environment: Brave browser on windows

**Comment by gabek** [comment]
For reference, `workbox` isn't related to tags, it's a background service worker that downloads assets, but it does have the ability to block the main thread. So it could possibly be indirectly connected, or not at all connected.

I'm not able to reproduce this. Are you running a production build or a dev server? I'm assuming it's a production build because I don't think we run workbox in dev.

**Comment by germainelee** [comment]
Where can I see / find if it is production build or a dev server? at the bottom it says Owncast v20240617-nightly

**Comment by gabek** [comment]
Ohh you're looking at nightly. Any server that's actively running publicly is a production build. If you're running the web app source code locally, then the web app is running under a dev server to allow for development.

**Comment by germainelee** [comment]
Is nightly a production or dev build?

**Comment by gabek** [comment]
It's a production build. Development builds are only run when developing, usually on your local computer.

**Comment by germainelee** [comment]
Maybe issue might occur because of the browser? Is testing needed on all kinds of browser to verify assumption?

**Comment by gabek** [comment]
I see what's happening. Like you said above, it is actually saving successfully. Type in a new tag, press enter, and refresh the page. You'll see the new tag there. But type in a new tag, press enter, and do nothing, it won't show. So that's why it seems like it's working, because it is, but the UI just isn't reflecting it.

I can only guess that a Antd change effected this? I don't think this has been touched in a long time.

**Comment by germainelee** [comment]
Something is up with Configuration -> General page specifically. The tag management in other pages works fine.

**Comment by mahmed2000** [comment]
@germainelee did you test this on a publicly deployed server, or was it just local testing?

**Comment by germainelee** [comment]
> @germainelee did you test this on a publicly deployed server, or was it just local testing?

https://github.com/owncast/owncast/issues/3229#issuecomment-2175385549 @mahmed2000

**Comment by mahmed2000** [comment]
I meant more as in if it was on a running public server with federation enabled, or if it also happens on a fresh install with nothing configured. I had a hunch I wanted to check.

If you don't mind testing, does changing the "Name" and "About" values on the General page also fail to show the success status message on submit? The value should still be fine on a refresh, its specifically the status message that I want to check.

**Comment by germainelee** [comment]
> I meant more as in if it was on a running public server with federation enabled, or if it also happens on a fresh install with nothing configured.

It's running publicly. With federation ig. @gabek correct me if im wrong regarding Owncast nightly. 
<hr>

@mahmed2000 Success message shows for those... though it could take a few seconds to appear.

![Image](https://github.com/user-attachments/assets/37210cf3-243b-4349-937a-7448fa1d08da)

![Image](https://github.com/user-attachments/assets/58e3bbb6-f4c1-4575-a7e9-0198d5d82f3b)

**Comment by gabek** [comment]
~~Oddly enough it seems like nightly stopped running the nightly build.~~

> Powered by [Owncast v20240905-nightly](https://owncast.online/)

Actually it seems like it's the image that's not updating, the instance is probably fine. Another CI job that's failing I'm sure.

**Comment by gabek** [comment]
Ok, that should be fixed starting tonight.

**Comment by mahmed2000** [comment]
> Success message shows for those... though it could take a few seconds to appear.

Probably not what I was thinking then. There's one more thing to check if you can use your browser's devtools. Monitoring the network log when you update either the tags or social links for the "tags" and "socialhandles" endpoints should narrow some things down further. If it's still not updating the tag list properly even with 200 OK responses, I can try to test it locally for what triggers it.

Thanks regardless for the info.

> Actually it seems like it's the image that's not updating, the instance is probably fine. Another CI job that's failing I'm sure.

If that's the "Build development container" then its the same problem as the nightly screenshots workflow. Checkout only looks for pull or push events, but the trigger is a schedule.

**Comment by germainelee** [comment]
It's updating the "tags" and "socialhandles" properly after about 8 seconds or so. It took longer to update when deleting compared to adding.

![Image](https://github.com/user-attachments/assets/b5b67341-d56a-4941-ae67-d88f4e94d875)

![Image](https://github.com/user-attachments/assets/3960bce8-66a6-4405-a109-ea9667dfd15d)

**Comment by mahmed2000** [comment]
Its a backend issue then. Its not that the UI doesn't reflect the updated tags, it just gets delayed very long with no feedback to the user. Those 4 fields will send an update to all followers after saving the changes. Reloading will fetch the updated values, but the message only shows up after the API request is returned, same with the tag-list update. There's handling for that API call being a success or error, but nothing for it just taking a while.

The handling for federating updates is async, but the channels are unbuffered. Which means an update can only be queued if there's a worker free to take on the request. If there's n workers, and at least n+1 followers are from servers with some federation problems, n updates get queued and keep waiting for a response. The last request has nowhere to go and holds up the API response from being returned. Worst case is those servers simply never send back a response and the delay becomes indefinite. It compounds with the amount of followers, and getting backed up from other federating requests in general. Like with your example, I don't think its deleting specifically that takes longer, but something from previous requests is holding up a worker and slowing down processing as a result.

An easy band-aid is to just bump up the workerpool channel to buffer more requests. Ideally the queuing also becomes async, but at minimum the UI would need some "In progress" status indicator. Maybe a shorter timeout for the workers making http requests as well?

**Comment by gabek** [comment]
With the most recent changes, I've verified this specific issue has been resolved when testing on `nightly`.
