### ISSUE TITLE
[Bug Report] Using s3 storage duplicates data to local hls directory

### ISSUE THREAD

**Issue by jprjr** [owncast/owncast#3230]
### Share your bug report, feature request, or comment.

Hi there - I noticed in Owncast 0.1.1, when I enable s3 object storage - video chunks are written to the HLS directory as well! For my long-running stream, this causes me to eventually to run out of disk space.

EDIT: Checked out v0.1.0 and ran a test stream with s3 storage, confirmed that old video segments are deleted eventually, so it's a new bug to v0.1.1.

**Comment by jprjr** [comment]
It looks like in #2876 - the cleanup functionality was moved into storage handlers, but s3 storage's cleanup method neglects the fact that files are written to-disk before being uploaded to s3, and need to be removed as well.

Don't know if the right path forward is to just delete video segments right after uploading, or for s3 to mimic the old behavior (scan the folder for files and delete old ones).

As far as I know, if your s3 config is incorrect and you're unable to upload video segments, there's no fallback-to-local storage logic, so it may make sense to delete the video segments after the upload attempt, regardless of passing or failing.

**Comment by gabek** [comment]
> As far as I know, if your s3 config is incorrect and you're unable to upload video segments, there's no fallback-to-local storage logic, so it may make sense to delete the video segments after the upload attempt, regardless of passing or failing.

Yeah I agree with this. I'll get this fixed up and get out a release sooner than later since this can impact people.
