### ISSUE TITLE
Mobile: Hitting enter is not sending chat message

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3238]
### Share your bug report, feature request, or comment.

I don't know if this is a regression, but I don't think it was happening previously. Hitting enter is adding a new line, not sending the chat message.

![image](https://github.com/owncast/owncast/assets/414923/3ba2b8bd-1f27-4ed6-96c6-07dc118993c0)

**Comment by gabek** [comment]
It seems this is only an issue with the mobile testing platform. So I'm not sure if there's actually any real issue. I'll remove this from the milestone but keep it open for the time being.

**Comment by mdonoughe** [comment]
Is this just for iOS? I don't have the same problem with Firefox or Chrome or even Samsung Internet on Android.

**Comment by gabek** [comment]
Good question. Looks like above I determined it was probably just an issue with the testing platform, so that's likely it. I should re-test again on iOS and close this.
