### ISSUE TITLE
Not showing in directory on a Cloudflare "argo" tunnel

### ISSUE THREAD

**Issue by mindspies** [owncast/owncast#3239]
### Share your bug report, feature request, or comment.

I'm trying to show up in the official Owncast directory.
I use a Cloudflare tunnel because I'm streaming from my home computer.
I've tried re-connecting the stream, repairing the directory connection but nothing seems to work. I even reinstalled my server from scratch.
Is it possible that my domain has been flagged as "unwanted" or "problematic" because of too much failed attempts?
My URL is:
https://owncast.hifiradio.lol
Any advice would be greatly appreciated.
William

**Comment by gabek** [comment]
Your server was certainly live on the directory last night and this morning, I only know this because I noticed it and tuned in for a while because I liked the music. 

If it since stopped showing as live, did anything change between when it was working and when it stopped working? After you reinstalled from scratch, did you restore your original database? There's a key that gets generated between the directory and your instance that if you lost might show up as a mismatch going forward.

Is there anything in your Owncast server logs?

**Comment by mindspies** [comment]
I was playing around with the SSL configuration, trying different options like HAPROXY, APACHE and NGINX to be able to show up in the directory, to realise that Cloudflared itself was a reverse proxy. That's why I restarted from scratch.

When I rebuilt it from scratch I made the mistake to put "http://localhost" as address so there was an error there:
YP Ping error returned from service: Error accessing http://localhost/ or treating it as an Owncast server. Are you sure that is an Owncast server and not another site? Get "http://localhost/api/yp": dial tcp [::1]:80: connect: connection refused

The two other errors in log were:
1 - (error) [h264 @ 0x664dcc0] Increasing reorder buffer to 2
2 - (info) unable to write image.

I really appreciate your quick answer and the fact you liked the music.

Thanks.

**Comment by gabek** [comment]
Ok, I just deleted you from the directory. If you make sure your server is identifying itself as https://owncast.hifiradio.lol/ and restart your stream in 5 minutes or so it should re-register from scratch. Let me know if that doesn't work.

<blockquote><img src="htts://owncast.hifiradio.lol/thumbnail.jpg" width="48" align="right"><div><img src="/img/favicon/favicon-16x16.png" height="14"> HiFiRadio's Owncast</div><div><strong><a href="htts://owncast.hifiradio.lol/">HiFiRadio's Owncast</a></strong></div><div>PSYCHILL music with visuals.</div></blockquote>

**Comment by mindspies** [comment]
I stopped the stream and re-launched it and it doesn't seem to help. Should I also "untick" and "retick" the "show up in directory" option after I stop the stream and before I relaunch it?
Thanks again for your help!

**Comment by gabek** [comment]
That shouldn't make any difference. Any log messages?

**Comment by mindspies** [comment]
(error) [h264 @ 0x75e3ec0] Increasing reorder buffer to 2
(info) unable to write image.

**Comment by mindspies** [comment]
One thing I must mention I use the "passthrough" option, and in the beginning I wasn't able to stream from OBS, the server was saying "unable to write image" and I had the message "stream not supported" in my browser when trying to watch the channel.
I managed to be able to stream with the "passthrough" option by using a plugin for OBS studio I know for a while, obs-multi-rtmp, which is basically able to stream to multiple rtmp target at once... It offers the option of "NVENC (mpeg)" which is not available in OBS by default... I tought it might be of interest to you to know that.

**Comment by mindspies** [comment]
OK I must say I'm a little SHY I wrote "htts" instead of "https" in the address.
Now the log says "Pinging YP as:  HiFiRadio's Owncast with key"
I hope it works.
I keep you in touch.

**Comment by mindspies** [comment]
OK I must say I'm a little SHY I wrote "htts" instead of "https" in the address.
Now the log says "Pinging YP as:  HiFiRadio's Owncast with key"
I hope it works.
I keep you in touch.

**Comment by mindspies** [comment]
First I was redirecting port 8080 directly on the Cloudflare side, so I tought it was my problem "not be able to appear on the directory". So I managed to import my certificate in Apache for my SSL signature to be correct, using Apache as a "reverse proxy". So now I could redirect port 443 on the Cloudflare side to my loopback. But still not able to show up in the Owncast directory.

**Comment by gabek** [comment]
@mindspies What's the current status of this issue?
