### ISSUE TITLE
Avoid deletion of files from S3

### ISSUE THREAD

**Issue by ElFDA** [owncast/owncast#3246]
### Share your bug report, feature request, or comment.

OS: Debian 11
Owncast: 0.1.1

Hello!
from the latest version of Owncast the stream sent to an S3 server is automatically deleted during streaming, since I used it to generate VODs would it be possible to insert an option to enable or not  this feature?

Thank you :)

**Comment by gabek** [comment]
When support for stream replays is shipped with Owncast all the settings will be available to enable that. In the meantime, however, there's no way to turn this off. It's all coming, however.
