### ISSUE TITLE
User badges need spacing between them

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3247]
### Share your bug report, feature request, or comment.

They used to look ok, but it seems like the spacing disappeared. 

![image](https://github.com/owncast/owncast/assets/414923/b58bcd70-71e9-4df8-8038-6c16cf32f28e)

**Comment by DineshDhanji** [comment]
I would like to do it.

**Comment by Lakshvyas007** [comment]
Assign it to me

**Comment by gabek** [comment]
@DineshDhanji jumped in first, thanks to both of you for wanting to contribute!

**Comment by DineshDhanji** [comment]
It's done.

**Comment by DineshDhanji** [comment]
It's done.
