### ISSUE TITLE
`http: superfluous response.WriteHeader call`

### ISSUE THREAD

**Issue by LittleFox94** [owncast/owncast#3252]
Hi,

I run owncast in a Kubernetes cluster and have the pod configured to do liveness+readiness checks using HTTP GET requests on /. This gives regular log messages like those:

```
2023/08/11 17:11:07 http: superfluous response.WriteHeader call from github.com/owncast/owncast/controllers.renderIndexHtml (index.go:93)
2023/08/11 17:11:07 http: superfluous response.WriteHeader call from github.com/owncast/owncast/controllers.renderIndexHtml (index.go:93)
2023/08/11 17:11:17 http: superfluous response.WriteHeader call from github.com/owncast/owncast/controllers.renderIndexHtml (index.go:93)
2023/08/11 17:11:17 http: superfluous response.WriteHeader call from github.com/owncast/owncast/controllers.renderIndexHtml (index.go:93)
2023/08/11 17:11:27 http: superfluous response.WriteHeader call from github.com/owncast/owncast/controllers.renderIndexHtml (index.go:93)
2023/08/11 17:11:27 http: superfluous response.WriteHeader call from github.com/owncast/owncast/controllers.renderIndexHtml (index.go:93)
2023/08/11 17:11:37 http: superfluous response.WriteHeader call from github.com/owncast/owncast/controllers.renderIndexHtml (index.go:93)
2023/08/11 17:11:37 http: superfluous response.WriteHeader call from github.com/owncast/owncast/controllers.renderIndexHtml (index.go:93)
2023/08/11 17:11:47 http: superfluous response.WriteHeader call from github.com/owncast/owncast/controllers.renderIndexHtml (index.go:93)
2023/08/11 17:11:47 http: superfluous response.WriteHeader call from github.com/owncast/owncast/controllers.renderIndexHtml (index.go:93)
2023/08/11 17:11:57 http: superfluous response.WriteHeader call from github.com/owncast/owncast/controllers.renderIndexHtml (index.go:93)
2023/08/11 17:11:57 http: superfluous response.WriteHeader call from github.com/owncast/owncast/controllers.renderIndexHtml (index.go:93)
```

It references this line, which is rendering an error if the template could not be executed for whatever reason: https://github.com/owncast/owncast/blob/103d1684ca329cbffdaa66bc5a17b064a20c5942/controllers/index.go#L93

The problem is those connections being apparently closed right after the HTTP status was sent - kubelet does not need any other information after all. This results in the template execution failing due to a closed connection. I was able to reproduce the error using curl with a very short timeout, you'll have to balance it between "response started being delivered" and "response fully delivered": `curl --max-time 0.1 http://172.20.231.147/`

There are certainly other situations where this would log non-helpful errors, like clients with slow connections which are then aborted or something. Proper handling of this is a bit annoying though, as every `http.Error` call would have to be augmented with a check if any part of the response was actually sent - it can happen on any route after all..

Maybe it's not worthwhile to fix this everywhere, but if so, could a `/healthz` route be added, that checks some things and returns 200 only if everything is ok?

**Comment by gabek** [comment]
Thanks for reporting this.

> There are certainly other situations where this would log non-helpful errors, like clients with slow connections which are then aborted or something. Proper handling of this is a bit annoying though, as every `http.Error` call would have to be augmented with a check if any part of the response was actually sent - it can happen on any route after all..

Maybe not. I'm curious how this is actually being logged out. Since I don't see any errors being printed to the log. Maybe `http.Error` just spews stuff out to the console, but that's dumb. I'd be fine logging it under a `verbose` log level or something, since it's not harmful, but not to the general console. I'll look into it.

> 
> Maybe it's not worthwhile to fix this everywhere, but if so, could a `/healthz` route be added, that checks some things and returns 200 only if everything is ok?

Does `/api/status` serve your needs? That would basically allow you to verify the service is up and responding, and if you wanted to go deeper you could verify it's live (if that's something you were expecting).

**Comment by LittleFox94** [comment]
`/api/status` seems like a way better path to check than `/`, thanks for that - using that now :)

As for how this message is logged, that's in the `net/http` package, whenever you have multiple calls to `net/http.ResponseWriter.WriteHeader` - and `net/http.Error` calls that as well: https://cs.opensource.google/go/go/+/master:src/net/http/server.go;l=1151

**Comment by gabek** [comment]
Yeah, I guess this isn't something that needs to be addressed. It doesn't impact the actual user, it's just an annoying log message that happens for a corner case.  It'd be nice if Go was smarter about this, but I don't think it's worth working around.
