### ISSUE TITLE
Admin scrolls horizontally in a weird way on narrower screens

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3260]
### Share your bug report, feature request, or comment.

I don't have the largest laptop screen in the world, and when I open a sidebar it makes the admin scroll in a very odd way. It should dynamically adjust spacing to allow more to fit instead of just cutting it off.

![image](https://github.com/owncast/owncast/assets/414923/d2a4fb31-f29e-4a69-ab0c-91e632cdcf6f)

**Comment by AMalfez** [comment]
Hi
I'm Alfez mansuri, new to open source but not development.
can you assign this issue to me?
I will try my best...

**Comment by anniepauline** [comment]
I can work on it. Assign the task

**Comment by gabek** [comment]
@anniepauline Great, thanks! Let me know if you have any questions getting up and running.

**Comment by gabek** [comment]
@AMalfez Sorry I missed your message up there and I assigned it to somebody else first. Feel free to look at the other [good first issues](https://github.com/owncast/owncast/labels/good%20first%20issue) if you'd still like to contribute! :)

**Comment by gabek** [comment]
Hi @anniepauline. Have you had any luck looking into this?

**Comment by anniepauline** [comment]
@gabek I am running into am error while running the application. I tried running the FE and the BE. It's the same error that I mentioned earlier. I am not sure why I'm getting the it. tried debugging it. Didn't work. I followed the documentation on how to run it. Still didn't help.

**Comment by gabek** [comment]
@anniepauline Could you repeat the issue here? There doesn't seem to be any mention of it in this thread.

**Comment by anniepauline** [comment]
@gabek!! Sorry, the error was on another issue. But the error is the same for both. 
I've mentioned the error here - https://github.com/owncast/owncast/issues/3215#issuecomment-1715812859

**Comment by gabek** [comment]
That error is usally seen when the backend isn't running. How are you running the backend? Can you access it on port `8080`?

**Comment by anniepauline** [comment]
@gabek For the backend - I've installed ffmpeg, gcc compiler,go toolchain and ran the command 'go run main.go' which runs into this error. 
![image](https://github.com/owncast/owncast/assets/58879804/6b5cebc6-8a8e-4fd6-be6e-f198257c136d)


The frontend - I cd into the web directory, installed all the packages, and ran "npm run dev" which also ran into an error:
![image](https://github.com/owncast/owncast/assets/58879804/66a7ec1c-9c90-4864-a4f5-b4b2b6696653)

**Comment by gabek** [comment]
You're not running on Windows are you?  Just double checking, as that's the only thing that comes to mind that could be an issue.

**Comment by anniepauline** [comment]
@gabek I am running it on windows

**Comment by gabek** [comment]
That explains it. This should help in that case. 

https://github.com/owncast/owncast/blob/develop/contrib/owncast_for_windows.md

**Comment by anniepauline** [comment]
Hey @gabek!!

I am able to run it now. But I have access to just this page 
![image](https://github.com/owncast/owncast/assets/58879804/735c2866-8727-45e1-bac8-7b8c1b58af81)
I am able to access localhost:3000/admin and  I am unsure how to go about the next steps.

**Comment by gabek** [comment]
Hi there. What else do you need? It sounds like you're good to go, so that's great news! If you can access the admin you should be able to look into the original issue in the first message of this thread. See the menu to navigate to the correct page.

**Comment by anniepauline** [comment]
@gabek I am working on this issue. I have a vague understanding of the problem statement. Please elaborate on this issue, so that I can gain a clear insight on it. I am unsure if the left navbar must have a bigger width based on the viewport or a resizable navigation pane.

**Comment by gabek** [comment]
Hi there!  If you go to the admin and navigate to the "General" settings page with a narrow browser window you'll see the page doesn't lay out in a way where everything fits, and instead cuts off the page content on the right, like in the screenshot. Thanks for wanting to contribute!

**Comment by anniepauline** [comment]
Okay!! I see it. I have a clarity on the issue. Thanks for the speedy response

**Comment by anniepauline** [comment]
@gabek I've looked into the designs and made a couple of changes to the designs. 
This is what the fixed design looks like. 

https://github.com/owncast/owncast/assets/58879804/34e38497-122e-422f-b50d-cf2869cd2f7a

**Comment by gabek** [comment]
That looks great to me. Thanks for working on it! I'll give it a spin when you put up a PR.

**Comment by anniepauline** [comment]
Also, The configure instance div is not responsive. I'd like to create a new issue and work on it. 
Should I follow any documentation to make a PR?

**Comment by gabek** [comment]
That would be awesome. No real process for the PR, but thank you for asking!

**Comment by anniepauline** [comment]
Hello, @gabek !! Apologies, I was a little caught up with other things the past week, so I couldn't work on the issue!!

So I have a small problem. The code changes I made on my editor locally do not reflect any changes on the browser.
The previous time I worked on this issue, I had no problem. Any idea how I could fix this?

**Comment by gabek** [comment]
hmmm. Maybe double check you're hitting port `3000` (your local web development server) and not `8080` (the Owncast backend). When web changes go in they get compiled into the backend, but you won't see your development changes on the backend until that happens.

Just a guess! Hopefully it's as easy as that.

**Comment by anniepauline** [comment]
I am using port 3000. The changes made I locally,  
![image](https://github.com/owncast/owncast/assets/58879804/68d9b779-584a-429c-a929-b8fc642d2c41)

The code here, that's running on the web
![image](https://github.com/owncast/owncast/assets/58879804/e8d3a1f8-3869-41da-a58b-618c8feb579a)


are totally different(I mean they don't get updated when I make changes)
I emptied my cache and did a hard reload. Still not sure why my code does get updated in the browser

**Comment by gabek** [comment]
I just looked again at your screenshot, and it looks like you're editing the compiled/distributed web app, not the web app source code. Instead of `static` you'll want to look under `web`.

**Comment by anniepauline** [comment]
Oh yes!! You are right!! I was working on the wrong directory this whole time.😐
