### ISSUE TITLE
Admin: Don't let people set private IP addresses as public url

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3268]
### Share your bug report, feature request, or comment.

I've noticed a few times people set an internal (192.168.x.x 10.0.0.x) IP address as their public hostname, and then try to register to the directory. This obviously gets rejected at the directory, but we shouldn't let people set these values in the first place. The users probably think it's fine and wonder why it's not working.

**Comment by shreyass-ranganatha** [comment]
Hii, I'd like to work on this if it's still up for grabs

**Comment by gabek** [comment]
@shreyass-ranganatha For sure, thanks for wanting to be involved! :) Let me know if you have any questions.
