### ISSUE TITLE
Mobile action menu button does not scroll

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3271]
As you scroll the page the button stays in the same location. 

![image](https://github.com/owncast/owncast/assets/414923/5f665fc3-125a-4047-8330-efd6906dfaa5)

**Comment by devasherr** [comment]
hey can i have a shot at it?

**Comment by TayzCodes** [comment]
Hello
I can also work on this. Please assign so I can start

**Comment by gabek** [comment]
HI @TayzCodes! Sure, thank you! Please let me know if you have any problems getting running.

**Comment by gabek** [comment]
Oh whoops, sorry I only saw the last message from Tayz and didn't realize the Asher commented right beforehand. Sorry about that, Asher! If you're still interested, there's a couple other smaller web issues: #3260, #3268.

**Comment by TayzCodes** [comment]
Thanks @gabek

**Comment by TayzCodes** [comment]
> HI @TayzCodes! Sure, thank you! Please let me know if you have any problems getting running.

Sure, and Thanks

**Comment by TayzCodes** [comment]
> HI @TayzCodes! Sure, thank you! Please let me know if you have any problems getting running.

Hello Gabe,
I was trying to set the dev environment from local.
In order for the UI to get its data I tried to run the backend as well. 
My system is windows 11
I have installed all prerequisites yet I still get the below error

```
owncast>go run main.go
time="2023-08-26T06:42:48+05:30" level=info msg="Owncast v0.1.2-dev (20230826)"
time="2023-08-26T06:42:48+05:30" level=fatal msg="Unable to locate ffmpeg. Either install it globally on your system or put the ffmpeg binary in the same directory as Owncast. The binary must be named ffmpeg."
exit status 1
go: remove C:\Users\Tayyaba\AppData\Local\Temp\go-build1290356040\b001\exe\main.exe: The process cannot access the file because it is being used by another process.
```

Can I get some help?

**Comment by gabek** [comment]
Hi there. It looks like you're trying to run Owncast on Windows. Owncast doesn't natively support Windows, but if you look through this document you can still get it up and running:

https://github.com/owncast/owncast/blob/develop/contrib/owncast_for_windows.md

**Comment by TayzCodes** [comment]
Excellent thanks !

**Comment by anniepauline** [comment]
Is this issue still open?
If yes, I will get started working on it

**Comment by gabek** [comment]
Hi @TayzCodes, are you still looking at this? Thanks for any update!

**Comment by TayzCodes** [comment]
Hey @gabek
Yes
Give me this weekend I shall be raising the PR

Thanks & Regards,
Tayyaba

**Comment by gabek** [comment]
Hey @TayzCodes! Any luck looking at this?

**Comment by TayzCodes** [comment]
Hello Gabe,
I am really sorry for the delay. I got caught up in a personal thing. i
shall raise the PR by tomorrow evening if that's fine with you?

Thanks,
TayzCodes

**Comment by Pranav2612000** [comment]
Hey @gabek Can I work on this issue?

**Comment by gabek** [comment]
@Pranav2612000 For sure, thanks so much!
