### ISSUE TITLE
Incorrect artifact timestamps on builds

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3282]
Fix: https://github.com/earthly/earthly/issues/2663

---

### Discussed in https://github.com/owncast/owncast/discussions/3281

<div type='discussions-op-text'>

<sup>Originally posted by **Epy** August 27, 2023</sup>
Hello
I didn't make an issue because I'm not sure of what's happening, it could be nothing as I don't know much about Go applications.

I downloaded the latest release on this page: https://github.com/owncast/owncast/releases v0.1.1, amd64 version.
When I unzippped the file on the server, the binary says it's from April 2020

Tried on my computer, it's the same date: 
![Owncast zipped](https://github.com/owncast/owncast/assets/450856/c96a8f11-074d-43c3-a995-71b40ddb917f)

Is that normal ? I would have thought the date would be the date of the last compilation of the binary, so "July 28th" of this year

Thanks</div>

**Comment by glenn-horton-smith** [comment]
The same problem is still present in the 0.1.3 release (2024-04-07). The "owncast" binary is dated 2020-04-16 00:70:

```console
$ unzip -v ~/Downloads/owncast-0.1.3-linux-64bit.zip 
Archive:  /home/gahs/Downloads/owncast-0.1.3-linux-64bit.zip
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
17824660  Defl:X 17824919   0% 2020-04-16 07:00 ab5effe5  owncast
--------          -------  ---                            -------
17824660         17824919   0%                            1 file

$ unzip  ~/Downloads/owncast-0.1.3-linux-64bit.zip 
Archive:  /home/gahs/Downloads/owncast-0.1.3-linux-64bit.zip
  inflating: owncast                 

$ ls -lt owncast 
-rwxr-xr-x 1 gahs gahs 17824660 Apr 16  2020 owncast
```

**Comment by mahmed2000** [comment]
Currently the `keep-ts` only runs in the `package` target's command and only saves the timestamp for the zip file. The actual binary gets pulled in from the `build` target and keeps the 16-Apr timestamp. `build`'s `SAVE ARTIFACT` needs a `--keep-ts` as well as any `COPY` pulling that artifact. In theory that should fix it, but need to test to check.

**Comment by gabek** [comment]
Yup, I'm sure that'll fix it. It was previously only changed for the archive, and when I saw that timestamp was correct, I didn't look at the binary.
