### ISSUE TITLE
Owncast 0.1.1: Unable to generate thumbnail: exit status 139 -fix?

### ISSUE THREAD

**Issue by AtlasCentaurus** [owncast/owncast#3289]
### Discussed in https://github.com/owncast/owncast/discussions/3288

<div type='discussions-op-text'>

<sup>Originally posted by **AtlasCentaurus** August 30, 2023</sup>
Hi to everyone 

Today after doing a stream, i got the following errors:

**Segmentation faul** (only 1 time)
**Unable to generate thumbnail: exit status 139** (everytime)

Like an extra data: Today my Ubuntu version was upgraded from 22.04.3 LTS (Jammy Jellyfish) to  23.04 (Lunar Lobster)  and then I installed the ngix to get the ssl thing. The streams works very good, however it can not generate the thumbnail, does anyone knows how to fix this?

Thanks in advance

</div>

**Comment by gabek** [comment]
A discussion has already been opened with this exact same question. See https://github.com/owncast/owncast/discussions/3288

<blockquote><img src="https://opengraph.githubassets.com/da32a552a07e08672e78a268e15fdcfbe76d14fc22df1c08e69bcf96164fac71/owncast/owncast/discussions/3288" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/owncast/owncast/discussions/3288">Owncast 0.1.1: Unable to generate thumbnail: exit status 139 -fix? · owncast/owncast · Discussion #3288</a></strong></div><div>Hi to everyone Today after doing a stream, i got the following errors: Segmentation faul (only 1 time) Unable to generate thumbnail: exit status 139 (everytime) Like an extra data: Today my Ubuntu ...</div></blockquote>
