### ISSUE TITLE
rel-me link verification support

### ISSUE THREAD

**Issue by glyphscribe** [owncast/owncast#3290]
### Feature Request

If possible, it would be nice to have a location / mechanism to configure rel=me link verification into an owncast instance, whether in the head or in the body.

For sites which support it (in my case, Mastodon), rel-me verification does not work correctly because all user-provided HTML is part of the hydration and thus not available at verification time.

Mastodon documentation: https://docs.joinmastodon.org/user/profile/#verification
Microformats documentation: https://microformats.org/wiki/rel-me

**Comment by gabek** [comment]
There is some server-rendered HTML that happens with the current version, that's how you can paste a link places and it will populate oembed and opengraph data.

![image](https://github.com/owncast/owncast/assets/414923/a6847d45-7f72-4e37-9795-b4847f38f5a6)

However, with v0.1.2 I'm going back to the simpler server-rendered bot/scraper page. For your particular case, it should be easy to add additional links or attributes if you want to put up a PR with whatever you're looking for.

https://github.com/owncast/owncast/blob/develop/static/metadata.html.tmpl

**Comment by glyphscribe** [comment]
I did read up on the current and in-progress templates prior to putting the feature request in, but solving this in a straightforward way in a docker environment was a little bit more involved than I think a typical user might want or be able to hack through.

Might put my money where my mouth is and submit a PR for it if you're OK with that. Just need to find some time :)
