### ISSUE TITLE
Serving Endpoint not used without an S3 backend

### ISSUE THREAD

**Issue by alyx161** [owncast/owncast#3292]
### Share your bug report, feature request, or comment.

When you define a custom URL as a serving endpoint in the web interface, it has no affect.

<img width="881" alt="Screenshot 2023-09-04 at 12 05 04" src="https://github.com/owncast/owncast/assets/140521532/72c5f40f-a229-4758-be55-daf223cc7540">
<img width="937" alt="Screenshot 2023-09-04 at 12 05 21" src="https://github.com/owncast/owncast/assets/140521532/f925364c-7a3e-416c-a50e-7a1a0cd29a92">

Using the latest stable version 0.1.1 running on Docker

**Comment by gabek** [comment]
It was originally a feature that was only for object storage support, and it looks like it's still only supporting object storage. If you're not using an S3 provider, it's ignored, but seems to still work if you are using one. Thanks for bringing this up.
