### ISSUE TITLE
Handle people trying to save invalid URLs in the admin

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3297]
### Share your bug report, feature request, or comment.

The backend will reject any invalid (private) URLs that people try to save in the admin. However, the frontend is unable to handle these errors.

When an error is received, we should display it to the user.

![image](https://github.com/owncast/owncast/assets/414923/1d00bd8c-d992-49c5-aa33-9601bbefe6f0)

See #3295

![image](https://github.com/owncast/owncast/assets/414923/5d81677a-bf19-4e14-a37a-de2fcf794f1d)

**Comment by t1ff4ny** [comment]
You can assign this issue to me. Thanks :)
