### ISSUE TITLE
How Reponsive For Embedding ?

### ISSUE THREAD

**Issue by obaviet** [owncast/owncast#3298]

**Comment by gabek** [comment]
Could you elaborate on your question?

**Comment by obaviet** [comment]
It means how well the mobile device can be displayed when you embedding. The most common example is wordpress. I have tried the instructions online but it doesn't seem to work with owncast

**Comment by gabek** [comment]
I'm afraid you're going to have to give more detail than that. What does "doesn't seem to work with Owncast" mean?

Please read the embedding documentation for details: https://owncast.online/docs/embed/. I unfortuantely can't speak to how you should be configuring Wordpress for your goals.

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="https://owncast.online/favicon.png" height="14"> Owncast</div><div><strong><a href="/docs/embed/">Embedding into your site</a></strong></div><div>You can easily embed your chat or video into another site.</div></blockquote>

**Comment by jacobgkau** [comment]
The generic iframe generator at https://embedresponsively.com/ works perfectly fine with the example iframe in Owncast's documentation (after removing the hardcoded size values).

<blockquote><div><strong><a href="https://embedresponsively.com/">embedresponsively.com</a></strong></div></blockquote>
