### ISSUE TITLE
Owncast passthrough + OBS NVENC with NV12 results in unplayable video 

### ISSUE THREAD

**Issue by Koli0842** [owncast/owncast#3306]
### Share your bug report, feature request, or comment.

Hi,

I have been running owncast on and off for some time, mostly as a higher bitrate alternative to sharing stuff with friends on Discord. I have it installed on Arch with the package manager, used it first at around 0.4. This issue some time before 1.0 and still persists. I can start my stream just fine, and the first viewer to join can see the stream, but every other client afterwards gets these errors (I copied from Firefox console)
```
Media resource blob:https://my-domain.eu/68fa24b4-f8d6-4b80-914b-654f6d6f0354 could not be decoded. my-domain.eu
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. 
Object { code: 4, message: "The media could not be loaded, either because the server or network failed or because the format is not supported." }
d6e1aeb5-053445a7f4335efe.js:1:1680
VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) video append of 12976260b failed for segment #7 in playlist 0-0/stream.m3u8 
Object { code: 3, message: "video append of 12976260b failed for segment #7 in playlist 0-0/stream.m3u8" }
```
It does not recover until restarting the owncast backend, just stopping and starting on the client side doesn't help. After restarting the service, the first viewer can again see the stream just fine, while the error is shown to everyone else. We tried with like 5 different friends, different browsers, phone and PC to no avail. I am streaming in "source" quality to avoid load on my server, h264 encoding with around 20 mbps bitrate, from OBS. Backend does not show logs (except being unable to generate thumbnail, I never bothered to fix that).

Any ideas where should I look?

**Comment by gabek** [comment]
My suggestion, though you won't like it, is to turn off passthrough. Whatever you're sending Owncast right now is being directly sent to your viewers, and they're not able to play it.

https://owncast.online/docs/video/#video-passthrough

The "unable to generate thumbnail" is actually connected. Owncast is trying to generate a thumbnail from your video, and it can't because it can't read your video, just like your viewers can't.

Even temporarily, turn off passthrough. It'll probably take a lot of CPU to crunch down your 20mbps to something smaller, so you might also want to reduce your broadcasting bitrate while troubleshooting and match it within Owncast. If it starts working for your viewers then, you'll know the problem exists with what you're sending Owncast, and you can start looking there. If it still occurs, then at least you know it's not your inbound video that's to blame.

I also suggest putting your stream URL into https://hlsanalyzer.com to get some additional details around potential issues.


<blockquote><img src="/static/image/fav/favicon.ico?v=0.2" width="48" align="right"><div><strong><a href="https://hlsanalyzer.com/">HLSAnalyzer.com | An Online HLS Monitoring and Analysis Service</a></strong></div><div>HLSAnalyzer.com is an online HLS monitoring service for analyzing and validating live HLS (HTTP Live Streaming) streams and SCTE-35 cues.</div></blockquote>

**Comment by rAcHekLoS** [comment]
@Koli0842 Koli0842Do you use NVENC HW Encoding with colorformat NV12 in OBS?

**Comment by Koli0842** [comment]
Hi @rAcHekLoS, Correct, I am using these exact settings.

I have tested the suggestions from the last comment too, but I ran into hlsanalyzer free limits before having anything conclusive, then forgot about it. With higher latency settings in OwnCast, passthrough seems to work with 20000 kbps cbr for 2-3 clients. It's strange to me that changing the latency mode was the fix. Unfortunately my CPU could not take reencoding for a combination of settings, so for the time being I'll be sticking with passthrough

**Comment by gabek** [comment]
When using passthrough Owncast won't have control over the keyframes, and keyframes are directly connected to segmenting of video, and segmenting of video is what is controlled by the latency settings. So this all does kind of make sense. The latency setting that you found to fix the issue probably is creating segment boundaries that are compatible with the keyframes you're setting from your broadcasting software.

**Comment by rAcHekLoS** [comment]
@Koli0842 This is a Problem since OBS 28.0.0 with coloformat NV12 in the combination with FFMPEG (4,5,6) and HLS output. Owncast use ffmpeg for the HLS mux and don't can fix this problem. You can test it with another colorformat e.g. I420.

See OBS issue: https://github.com/obsproject/obs-studio/issues/7954

**Comment by Koli0842** [comment]
Thanks both of you for the insight! I'm not very well versed in video encoding tech.

It seems the issue is closeable then, I believe the most OwnCast could do is put out a bigger warning so less people miss it! I guess we don't have much control over the client doing the playback, nor does the owncast backend process the HLS stream in passthrough mode to only allow segmenting parameters that the stream remains playable. I'm guessing there's no metadata about this encoded in the stream itself, nor is it very deterministic.

**Comment by gabek** [comment]
I updated the title so anybody else with this specific issue might be able to find it and see the status of the discussion.

**Comment by ViRb3** [comment]
Hi @gabek, I just ran into the same issue. Sadly, it makes owncast almost unusable on Raspberry Pi 5 which lacks any hardware support for h264. However, I played around with [restreamer](https://github.com/datarhei/restreamer) and it's able to play the exact same source with passthrough and virtually zero CPU usage on any browser I threw at it. It seems like it should be possible to do the muxing on owncast's side and still passthrough without re-encoding. I'm not sure how hard it would be, but maybe this issue can be reopened?

**Comment by gabek** [comment]
I guess I'm a little confused. If you have video passthrough enabled, then Owncast is out of the picture. You're telling Owncast to not do any work. So I'm not sure what you're asking it to do in this case if you're both asking it to not do anything, but also do something at the same time. It's doing the segmenting of what you're sending it, but that's it. That's all it can do.

As an aside, somebody dropped by the other day and mentioned they were using a Raspberry Pi 5 fine, so I'm not sure what the difference is there.

I'm sorry, I'm a little confused :\

**Comment by gabek** [comment]
As for Raspberry Pi 5 hardware acceleration, this is what's stopping it: https://github.com/owncast/owncast/issues/1379

**Comment by ViRb3** [comment]
Sorry for the confusion, let me try to elaborate.

Raspberry Pi 4 supports both h264 hardware encoding and decoding, but the Raspberry Pi 5 only supports hardware h265 decode and no encode at all. My input stream is h264, so the Pi has to do both decode and encode in software, which at least at 1920x1080@60, does not cope.

As far as I understand, with video passthrough enabled, Owncast will not do any re-encoding, but it will still convert (mux?) the RTMP stream into HLS for consumption by browsers. With this setup, my NVENC h264 input stream does not play in the browser, as described in this issue. However, the exact same workflow with restreamer in the place of Owncast yields a working HLS stream that can be played in any browser. Therefore, it was my assumption that maybe there is something cheap that can be done on Owncast's side to make passthrough yield working HLS streams with NVENC h264 input stream.

**Comment by gabek** [comment]
What are your keyframes set to?

**Comment by ViRb3** [comment]
I have everything set to default. I think this means 0 (auto) for keyframes. Is there a specific configuration I need?

**Comment by gabek** [comment]
Unfortunately, I don't know what the value of "default" is, so I'm not sure if this is helpful at all, I'm just spitballing. https://owncast.online/docs/broadcasting/#keyframe-interval

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="https://owncast.online/favicon.png" height="14"> Owncast</div><div><strong><a href="/docs/broadcasting/">Broadcasting Software</a></strong></div><div>How you configure your broadcasting software can impact the quality and performance of your stream</div></blockquote>

**Comment by ViRb3** [comment]
Here are my settings:

![Screenshot 2024-01-07 at 03 09 37](https://github.com/owncast/owncast/assets/2650170/372b15ed-6b7d-4230-86fe-0d7e9bd28bb5)

Keyframes set to 2 does not help, this is the error in browser:

![Screenshot 2024-01-07 at 03 10 01](https://github.com/owncast/owncast/assets/2650170/83f6d956-8f48-4a19-81ff-3d8720aaf49b)

**Comment by ViRb3** [comment]
Some more useful logs from browser console:

![Screenshot 2024-01-07 at 03 11 28](https://github.com/owncast/owncast/assets/2650170/b5036911-9114-462f-8802-50582d85f288)

**Comment by gabek** [comment]
I'm going to be pretty honest with you, with all the other things I have to work on, trying to improve video passthrough cannot be a priority for me. And I do apologize for that. I generally tell everyone "You shouldn't ever try it, but if you do, and it doesn't work, turn it off immediately and move on". I understand you've used other software that works differently, and they have something called passthrough as well, but I don't know what they're doing, or if it's even similar in any way. I made up the name "passthrough" for Owncast, it's not an industry term or anything I was going by, and it's not something I was modeling off of anything else. So I can't compare.

If somebody wanted to work on Owncast and focus on just passthrough, I'd be more than welcome their contributions, but unfortunately, it can't be my personal focus. I'm sure there's a configuration from your broadcasting side that would make it work, but I don't know what it would be, and OBS settings aren't something I'm much help with either, I'm afraid. I do assume there are OBS experts out there, though. And I don't know if you've run your stream through HLS Analyzer yet, but that might get you some additional data that could point you in the right direction. I'm sorry I can't be more help.

**Comment by ViRb3** [comment]
Please do not apologize, I completely understand you and truly appreciate your time and answers. This is not a dealbreaker for most users and I'm sure there are workarounds if somebody is desperate enough. I was only messing around and experimenting; this can stay on the backlog for as long as it needs :)

Edit: Might still want to re-open ticket though, just so it doesn't get lost and helps others find it more easily.

**Comment by rAcHekLoS** [comment]
@ViRb3 Please set the Color Format to I420 and try again.

![grafik](https://github.com/owncast/owncast/assets/42749713/3ade82f9-980a-4a83-ad60-9df82facaa9d)

**Comment by rAcHekLoS** [comment]
with obs 30, all other colour formats also no longer work in combination with NVIDIA NVENC. An update to ffmpeg 7.01 solves the problem and NV12 works correctly again.

**Comment by gabek** [comment]
@rAcHekLoS Running Owncast with ffmpeg 7.01 you mean?

**Comment by gabek** [comment]
Going to put a link here to the issue tracking the support of ffmpeg 5+, as there are some challenges that have stopped us from making it a default. https://github.com/owncast/owncast/issues/2071
