### ISSUE TITLE
Deep links in Admin UI 404

### ISSUE THREAD

**Issue by mattdsteele** [owncast/owncast#331]
If you navigate to a child route in the Admin UI, such as `/admin/logs` and refresh the browser, it results in a 404.

I'm not really sure how to resolve this. Most SPAs recommend configuring the server to return a specific `index.html` page when it hits a 404, e.g. https://gkedge.gitbooks.io/react-router-in-the-real/content/apache.html

But it looks like Next has its own routing conventions, which I'm not real familiar with. And I'm not sure how a static export affects what gets generated.

**Comment by gabek** [comment]
Yeah, it's kind of an odd choice on Next's part, but for some reason when you export as a static site it renders each entry point as a file named of the entry point, so if you go to `/admin/hardware-info.html` it should work fine, but not `/admin/hardware-info` even though that's what the SPA is using.  Very weird.  I'm assuming there's some config for exporting Next apps that will let us do `/hardware-info/index.html` instead.

**Comment by gabek** [comment]
This sounds like it might be the answer!  https://nextjs.org/docs/api-reference/next.config.js/exportPathMap
