### ISSUE TITLE
Link embeds of my instance renders with my old profile picture

### ISSUE THREAD

**Issue by CaptainCalliope** [owncast/owncast#3316]
### Share your bug report, feature request, or comment.

I updated my profile photo in owncast with a new one (same face, different background) but when I put the embed on my website or post on the fediverse, the image pulled from the server is still the old one.

![image](https://github.com/owncast/owncast/assets/50292/f49fab54-464f-4099-adc6-1099d218e3b7)

![image](https://github.com/owncast/owncast/assets/50292/f0958d49-29b7-4c08-bb77-1b5c6572b71b)

![image](https://github.com/owncast/owncast/assets/50292/894bf111-4ed7-4866-9063-8e1ba51eaff4)

**Comment by CaptainCalliope** [comment]
Wow that screenshot went big.

**Comment by gabek** [comment]
It's likely cached in different places. For example, when I look at it from fosstodon it shows it loading this URL:

https://cdn.fosstodon.org/cache/preview_cards/images/018/590/920/original/6076841f51edf9d4.jpg

Hopefully the cached image will expire at some point and grab the updated one.
