### ISSUE TITLE
Danmaku

### ISSUE THREAD

**Issue by dudt** [owncast/owncast#3328]
### Share your bug report, feature request, or comment.

Can real-time caption comments be added to the chat?

**Comment by gabek** [comment]
I'm sorry, but that's out of scope to be built into Owncast. It would require using a 3rd party audio to speech implementation.

You could build your own, however, that consumes the video, does whatever magic to determine what text needs to be sent, and then send chat messages with that text.

**Comment by dudt** [comment]
> I'm sorry, but that's out of scope to be built into Owncast. It would require using a 3rd party audio to speech implementation.
> 
> You could build your own, however, that consumes the video, does whatever magic to determine what text needs to be sent, and then send chat messages with that text.

Sorry, my English is not very good.
What I mean is text bullet screens similar to emojis like https://smol.stream/emojiwall.😅

**Comment by gabek** [comment]
You can use that emojiwall that you linked to. What specifically do you need additionally that we can help you with?
