### ISSUE TITLE
Remove Matrix URL validation, allowing any URL

### ISSUE THREAD

**Issue by alyssais** [owncast/owncast#3329]
### Share your bug report, feature request, or comment.

OwnCast expects Matrix URLs to start with "matrix:", like XMPP URLs start with "xmpp:", but I don't think this is correct for Matrix.  Many people use Matrix through web clients, so usual way to link to Matrix is using the matrix.to web service, not a different protocol, e.g. https://matrix.to/#/@qyliss:fairydust.space.  This format is not accepted by OwnCast, I assume because it's too long?

**Comment by Abd-Elhadi** [comment]
Hi there!

I'm excited to contribute to Owncast and I'd like to work on this "Good First Issue." It looks like a great opportunity to get started with the project. I've reviewed the issue description, and I believe I can make the necessary changes.

I will begin by setting up my development environment as per the project's "getting started" guidelines. If there are any specific details or instructions I should be aware of, please let me know. 

I'll also be joining the community chat for real-time discussions in case there are any questions or additional context I need.

Looking forward to working on this and being a part of the Owncast community!

Best regards,
Abdelhadi

**Comment by gabek** [comment]
Fantastic, thanks so much! Feel free to reach out if you have any questions.

**Comment by alyssais** [comment]
I think the ideal behaviour here really would be to accept a Matrix/XMPP address, and turn it into the appropriate URL.  It's quite unintuitive that you're even supposed to put a URL in the first place, since you've already filled in what kind of address it is in the UI.

**Comment by gabek** [comment]
The entire point of the social links feature are to add URLs to link to.  While we tried to do the "right" thing for Matrix and XMPP it's clear there is no single answer that will make everyone happy, so standardizing on web URLs makes sense.

If somebody felt strongly that they wanted to build some kind of special interface for handling Matrix and XMPP then I'd certainly be up for it, but right now they are the less common link types and I can't dedicate time myself to continuing to update them with new logic each time somebody has a new preference of how they should work.

You think it should be an account, but somebody else will try to put in a URL, somebody else will try something else. If there's not one single answer, then we need to standardize on something.

**Comment by gabek** [comment]
Hi there @Abd-Elhadi! I'm just checking in to see if you're still looking at this, and if you have any questions. Let me know!
