### ISSUE TITLE
Geo details in viewer list is not populated when using a CDN

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3349]
### Share your bug report, feature request, or comment.

When going through a CDN, the list of viewers has a string with two IP addresses when listing those clients. One of the IPs is the CDN, the other is the actual client.

I'm thinking that the entire string (with the two addresses, and the comma) is being passed to the geo resolver and failing.

![image](https://github.com/owncast/owncast/assets/414923/29c1b377-738c-4bbf-85c7-38cb07b236cd)

I'm assuming this log message is being reported when that doesn't work:

![image](https://github.com/owncast/owncast/assets/414923/ff465809-eeff-43dc-a071-403ab3304da6)

**Comment by armadi1809** [comment]
Hello team! May I take this as my first contribution?

**Comment by gabek** [comment]
@armadi1809 Hey there! I just want to clarify that this would require changes on the backend to resolve how the (multiple) IP addresses are handled and wouldn't require any frontend work. If you're up for working on the Go codebase, we'd love to have you!

**Comment by armadi1809** [comment]
@gabek Yes, I know and I would love to take a shot at it. Also, is there some sort of discord/slack channel that I can join to seek help/clarification if needed or should that be done here in the comments section? Thanks!

**Comment by gabek** [comment]
Awesome! We have a community chat at https://owncast.rocket.chat/ that you're free to drop by any time. It's usually pretty quiet, but I can get back to you eventually if nobody else is around. You're also welcome to just comment here with any questions.

<blockquote><div><strong><a href="https://owncast.rocket.chat/">Owncast</a></strong></div></blockquote>

**Comment by gabek** [comment]
Here's the documentation on how to setup geo functionality, since it doesn't get shipped with it enabled by default:

https://owncast.online/docs/viewers/

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="https://owncast.online/favicon.png" height="14"> Owncast</div><div><strong><a href="/docs/viewers/">Viewer details</a></strong></div><div>Owncast can display high-level geographic information about your current viewers if you enable it in your instance.
Your server can optionally use the MaxMind GeoLite2 Database. If you provide your own free copy of the database it will be used. Perform the following in order to add this feature.
 Create a free account with MaxMind. Wait for an email and follow the link to your account. Under Database Products and Subscriptions click Download Databases.</div></blockquote>

**Comment by armadi1809** [comment]
Hey, @gabek! can you tell me where were you able to get the first screenshot in the issue description? i.e how do I see that information about the stream viewers? Thanks

**Comment by gabek** [comment]
Sure, that's the `/api/admin/viewers` API that's used to populate the `/admin/viewer-info/` page in the admin.

**Comment by armadi1809** [comment]
Hello @gabek, I want to test if my solution to this problem work. Is there any docs on how I can simulate going through a CDN when running owncast locally? The only CDN related ressource I found in the docs is this.

**Comment by gabek** [comment]
There's no simple way to emulate this, unfortunately. The easiest option might be to hardcode the IP address to match the weird IP string that's seen above.

**Comment by armadi1809** [comment]
Yeah I think that would work. One last question, which one of the two addresses above is the actual client address?

**Comment by gabek** [comment]
In this particular instance, the first is the actual client, and the second is the CDN. But I'm not sure if that's always the case or not. Nor am I sure why the IP address would be formatted in this way in the first place. I'm guessing [`X-FORWARDED-FOR`](https://github.com/owncast/owncast/blob/5fd37d8efa1ecd5351a863fd803c1dd97547898e/utils/clientId.go#L25) isn't standardized or something.

![image](https://github.com/owncast/owncast/assets/414923/fa9b3277-4e5f-406a-942d-9e7be0d2faee)

**Comment by armadi1809** [comment]
Looks like the first one is always the original client in `X-FORWARDED-FOR` as per this Wiki [article](https://en.wikipedia.org/wiki/X-Forwarded-For#:~:text=where%20the%20value%20is%20a,not%20shown%20in%20the%20header).) 

What happens is that each proxy will add the IP address of where it got the request from.

**Comment by gabek** [comment]
Nice! I never thought to look into it, great find! That's good to know it can be relied upon to be standardized.

**Comment by armadi1809** [comment]
@gabek  Thank you for your help clarifying this issue! Looking forward to your feedback on the PR.
