### ISSUE TITLE
Support multiple codecs

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#336]
This is now the issue tracking support for multiple codec support in Owncast.

- h264_omx
- nvenc
- vaapi

While adding support for these in Owncast is work that is required, that only gets people half way there.  In my testing both nvenc and QuickSync requires quite a bit of additional libraries, headers, sdks and vendor-specific support installed on your machine.  And to top it off you'll obviously need a specific build of ffmpeg to utilize that.

It sounds like `omx` is the exception and as long as your version of ffmpeg supports it, it can be a drop-in without changes to Owncast.  But I don't have the hardware at hand right now to test it.  It's also being deprecated in favor of, I believe, vaapi.

So half of getting this to work for people will be the significant documentation required to teach people how to install all the specific support libraries and compile their own copy of ffmpeg.  We'll need a "super advanced settings, you probably don't ever want to touch this, I doubt you know what you're doing, but here you go" section both in documentation and the admin.

---
Original post about NVENC:

Something I've only recently discovered is that NVIDIA has a hardware accelerated encoder called NVENC that seems to be a huge help in the transcoding process.  https://developer.nvidia.com/nvidia-video-codec-sdk

While this isn't terribly useful when supporting small, cheap, VPS installations running Owncast, this could be a game changer if we're trying to scale transcoders for hosting purposes.  I'm not sure how we'd get our hands on affordable GPU-powered machines, but we can cross that bridge if we get there.

In the short term I'm using this as an excuse to build a little home server with a GPU because paying for a VPS with a GPU just isn't cost effective for development purposes.  Hopefully I can test, update and verify Owncast on a NVENC-capable machine and document the results.  But it looks like [everything we need is generally already supported](https://developer.nvidia.com/blog/nvidia-ffmpeg-transcoding-guide/) as long as we use a compatible build of ffmpeg and the correct incantation when utilizing it.

@geekgonecrazy You might be interested in this since I know you've gone bare metal in your k8s deployments in the past.

![image](https://user-images.githubusercontent.com/414923/98750907-eaa7aa80-2373-11eb-8a90-68fab9accf06.png)

**Comment by kinghat** [comment]
i think using intel quick sync which is baked into iGPUs already would be a nice option. can handle many 1080p or 4k streams w/o breaking a sweat: https://blog.ktz.me/passthrough-intel-igpu-with-gvt-g-to-a-vm-and-use-it-with-plex/ some of that article is out of scope but shows the power of quick sync which many people already have in everyday PCs.

**Comment by VladimirAkopyan** [comment]
I have been testing out owncast on a home-server, i3-8100, and x264 encode is very taxing for this potato - I have to keep only 1 stream quality if i want low-ish latency
However using quicksync would actually allow this machine to have several streams

**Comment by gabek** [comment]
@VladimirAkopyan @kinghat  If you're at all interested in testing, we're working on getting this functionality out the door.  Please drop by our Rocket.Chat if you have some time to see if it works with your hardware.

Here's the in progress documentation: https://github.com/owncast/owncast.github.io/blob/0.0.7/content/docs/codecs.md

<blockquote><img src="https://avatars.githubusercontent.com/u/69942503?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/owncast/owncast.github.io">owncast/owncast.github.io</a></strong></div><div>Owncast's public facing web site.  Documentation and info. - owncast/owncast.github.io</div></blockquote>

**Comment by VladimirAkopyan** [comment]
@gabek Hello, I am happy to test it but I need a docker file, because I use a bare-metal K8s, and I was having a quick look - couldn't find the docker file to build the 0.7 version. Am I missing something?

**Comment by gabek** [comment]
> @gabek Hello, I am happy to test it but I need a docker file, because I use a bare-metal K8s, and I was having a quick look - couldn't find the docker file to build the 0.7 version. Am I missing something?

Hey there @VladimirAkopyan !  Feel free to grab our nightly Docker image: https://github.com/orgs/owncast/packages/container/package/owncast.  It's from the `develop` branch, so still a work in progress, but it's a good way to test.  Though admittedly I don't know how well Docker + GPUs work together.  I'd love to hear how it works for you.  This image isn't built to support any specific hardware.

<blockquote><img src="https://github.githubassets.com/images/modules/open_graph/github-logo.png" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com">Build software better, together</a></strong></div><div>GitHub is where people build software. More than 56 million people use GitHub to discover, fork, and contribute to over 100 million projects.</div></blockquote>
