### ISSUE TITLE
Code formatting not running when it should under CI

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3360]
### Share your bug report, feature request, or comment.

When pushing Javascript code, it should be linting and formatting the code. It's getting skipped for some reason. It might be an issue with how we're using the ["changed files" action](https://github.com/owncast/owncast/blob/develop/.github/workflows/javascript-format-build.yml#L39), it might be returning zero changed files.

![image](https://github.com/owncast/owncast/assets/414923/0c2cb7b8-72a0-4ef4-95dd-a525a34b99bc)

**Comment by A-5ingh** [comment]
I would like to contribute to it. Can you please assign this to me?

**Comment by gabek** [comment]
Of course, thank you!
