### ISSUE TITLE
Not selectable items in quality settings menu

### ISSUE THREAD

**Issue by SpectreZ64** [owncast/owncast#3368]
On touch devices items in quality settings menu is unselectable. They change color to white when I tap on it, but select action is not firing. I try to fix this issue in web/components/video/settings-menu.ts by some changes:

```
let clickevent;
if ('onpointerdown' in window) {
    clickevent = 'pointerdown';
} else if ('ontouchstart' in window) {
    clickevent = 'touchstart';
} else {
    clickevent = 'click';
}

...

item.on(clickevent, () => { ...
```

It's work fine on Android Phones and Windows Tablet, but not working at IOS devices.
![1](https://github.com/owncast/owncast/assets/15089861/157d10c0-2653-4355-82eb-5c1a2f131055)

**Comment by varungujarathi9** [comment]
Hi @gabek 
I can take this up next, I don't have an iPhone, but I think I can leverage BrowserStack to test it.

Let me know if it is feasible!

**Comment by gabek** [comment]
Definitely, thank you, @varungujarathi9!
