### ISSUE TITLE
"missing port in address" error after IP address parsing change

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3371]
### Share your bug report, feature request, or comment.

Re #3359 @armadi1809 

From the looks of this error message, it looks like there is an issue with the IP/port split.

![image](https://github.com/owncast/owncast/assets/414923/a8255a64-729b-4479-8f40-549c2d762bdc)

**Comment by armadi1809** [comment]
I just realized that the `net.SplitHostPort` will return that error we see in those logs if a port is not present. I will update the code accordingly.
