### ISSUE TITLE
Create a homebrew cask for owncast 

### ISSUE THREAD

**Issue by luzpaz** [owncast/owncast#3374]
### Share your bug report, feature request, or comment.

Add owncast to hombrew cask[^1] (a macOS repo for distributing the binaries).

[^1]: https://github.com/Homebrew/homebrew-cask

**Comment by gabek** [comment]
As a tiny project, we don't really have the resources to be doing packaging for all the different package managers. Plus, I don't think that many people use a mac to run Owncast in production, anyway. But if somebody wanted to take the responsibility of packaging Owncast for Homebrew, they absolutely should.

**Comment by luzpaz** [comment]
Clarrification: 'homebrew cask' is different than 'homebrew'. It solely distributes binaries. So there is no package maintenance needed. they have a auto-update script that tracks releases and will auto-update the cask when necessary. Since owncast does generate macOS builds, then this should be a one time thing.
