### ISSUE TITLE
Owncast website: Detect broken links

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3377]
### Share your bug report, feature request, or comment.

This is for the owncast.online https://github.com/owncast/owncast.github.io site.

It's natural for links to become incorrect over time as things move around, but it would be great to detect this in an automated fashion, so they can be fixed.

I'm assuming there's some way to go through a statically generated site and test if all the links are still valid, perhaps in our CI pipeline.

**Comment by 0scvr** [comment]
I'd like to work on this please.

**Comment by gabek** [comment]
Absolutely! Let me know if you have any questions or want to discuss.

**Comment by 0scvr** [comment]
> Absolutely! Let me know if you have any questions or want to discuss.

Unfortunately I have other things going on right now, so I won't be able to work on this issue. I've found some ready-made github actions that check for broken links. Could be good enough for this issue.

- https://github.com/marketplace/actions/broken-link-checker-action
- https://github.com/marketplace/actions/broken-link-check

<blockquote><img src="https://avatars.githubusercontent.com/u/39912269?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/marketplace/actions/broken-link-checker-action">Broken Link Checker Action - GitHub Marketplace</a></strong></div><div>GitHub Actions to check broken links and create issues</div></blockquote>
<blockquote><img src="https://avatars.githubusercontent.com/u/1300935?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/marketplace/actions/broken-link-check">broken-link-check - GitHub Marketplace</a></strong></div><div>Find broken links, missing images, etc within your HTML</div></blockquote>

**Comment by Pranav2612000** [comment]
Hey @gabek I'll like to work on this issue.

**Comment by gabek** [comment]
Awesome, thank you @Pranav2612000!
