### ISSUE TITLE
Phone going to sleep when watching

### ISSUE THREAD

**Issue by livevideosolutions** [owncast/owncast#3382]
### Share your bug report, feature request, or comment.

When I watch a livestream from my server on my iPhone, the phone goes to sleep while watching. This is while watching on the Owncast served watch page in full screen. Any suggestions on how to fix this or is this a known issue. BTW loving the product!

**Comment by rmens** [comment]
This sounds like a job for the Screen Wake Lock API. Most modern browsers support this, including Safari on iOS.

**Comment by gabek** [comment]
Thanks, @rmens for mentioning that API. I hadn't been familiar with it.

For reference, here's the documentation: https://developer.mozilla.org/en-US/docs/Web/API/Screen_Wake_Lock_API

Should the screen not go to sleep only when full screen, or any time the video is playing?

**Comment by rmens** [comment]
This is weird. I just tried streaming https://live.retrostrange.com/ on an iPhone 15 Pro with iOS 17.0.3 and both in windowed mode and full screen the phone didn’t go to sleep. 

What phone and iOS version are you using @livevideosolutions? And after how many minutes does this occur? I tested both modes for 15min.

**Comment by gabek** [comment]
> This is weird. I just tried streaming https://live.retrostrange.com/ on an iPhone 15 Pro with iOS 17.0.3 and both in windowed mode and full screen the phone didn’t go to sleep.

I figured it was possible it wasn't working as expected, but I was surprised to hear it wasn't. This makes sense, that it is doing the right thing.

<blockquote><img src="https://live.retrostrange.com/thumbnail.jpg" width="48" align="right"><div><img src="/img/favicon/favicon-16x16.png" height="14"> RetroStrange TV</div><div><strong><a href="https://live.retrostrange.com/">RetroStrange TV</a></strong></div><div>A community-supported 24/7 streaming TV channel based on public domain media and original content. Support us at http://patreon.com/philnelson</div></blockquote>

**Comment by livevideosolutions** [comment]
Well, that's how technology sometimes works, did the test again today. Already had 2 phones at the ready to test but it worked like expected. Screen stayed on.

Thanks for the quick replies everyone, and happy that all is working as expected 👍
Problem solved!
