### ISSUE TITLE
Mobile actions button not showing for some phones

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3390]
### Share your bug report, feature request, or comment.

In this test, it's showing the desktop layout (with the full row of buttons) instead of the mobile button that shows a menu of action options.

The resolutions of these two iPhone test cases are very similar, so I'm not sure why one is correct, and the other isn't. My personal iPhone 40 Pro on iOS 17 is working as it sound, so I'm not sure if it's an issue with the test environment or there's actually an issue.

Some additional sanity checking would be worthwhile.

Not correct:
![image](https://github.com/owncast/owncast/assets/414923/9b64f7e8-a5e4-409f-9a40-19b849d0cc0f)

Correct:
![image](https://github.com/owncast/owncast/assets/414923/87fe55ff-852b-4d5f-bdcf-5afdc75266bf)

**Comment by gabek** [comment]
This isn't the end of the world, so I'm not going to block 0.1.2 with it.

**Comment by jhimanish** [comment]
Hello, 
We are a group of 4 students from the University of Toronto. We're currently looking to contribute to an Open-Source project and are looking for our first few issues. 

We were wondering if you could assign this issue to us. 
Thanks!

Team members: @jhimanish @EthanZheng11, @asherhounsell, @TashanManiyalaghan

**Comment by gabek** [comment]
Of course, thank you! Unfortunately, I can only assign to you, since you're the only person who's commented on it. But if you want me to add the rest of your team, have them comment here, and then I can add them.

**Comment by jhimanish** [comment]
Thank you so much for assigning it to us. We look forward to working and contributing to this project! 

I think it's okay if the assignee is set only to me. When we create our PR, we intend all of our members to push commits to the PR so they will show up on the PR contribution side.

Thanks again.

**Comment by TashanManiyalaghan** [comment]
Hi, I'm one of @jhimanish 's team members. We have tried to recreate the issue using Lambda Test browser and can't seem to replicate the issue on the iPhone 13 as you did. Is there any addition information we should know to try and recreate it? Here is an image of the mobile action button working correctly on the iPhone 13: 
![image](https://github.com/owncast/owncast/assets/64664596/a278c45f-6ab2-4bfe-a680-c2d8376a5ad5)

**Comment by gabek** [comment]
It may have very well been an issue with the test environment I was using because I haven't seen it elsewhere. And since you're unable to reproduce, it feels like it is not an actual issue, after all. Thanks for checking and reporting back, it's much appreciated! 💯

**Comment by TashanManiyalaghan** [comment]
Hey, we ended up testing with BrowserStack and it seems like we are able to recreate the issue. This could be something to do with BrowserStack specifically, but also Lambda Test is only doing a browser test whereas BrowserStack seems to emulate a real iPhone device. Do you think that this issue still exists or is it an artifact of BrowserStack? Here is an image of Owncast running on a BrowserStack iPhone: 
![image](https://github.com/owncast/owncast/assets/64664596/14ee0ea4-1c04-4a2f-8d9e-2afcb9b050c5)

**Comment by gabek** [comment]
Thanks for double-checking!  I think since it's not obvious if there's anything to fix, it's fine to leave it and see if it ever pops up again, in real-world usage. No need to go chasing down something if there's not actually an issue, or if there is an issue that it doesn't seem like anybody can actually reproduce in the wild.
