### ISSUE TITLE
fix /api/admin/config/streamkeys documentation

### ISSUE THREAD

**Issue by MFTabriz** [owncast/owncast#3391]
Sample payload in the [API documentation ](https://owncast.online/api/latest/#tag/Admin/paths/~1api~1admin~1config~1streamkeys/post) is 

```json
[
  {
    "id": "yklw5Imng",
    "comment": "Used by Tim."
  }
]
```

but using it, the server returns:

```json
{
  "message": "unable to update stream keys with provided values",
  "success": false
}
```

 I think according to [the source](https://github.com/owncast/owncast/blob/cff180b30510fcec8090c0bc74c1e21270d0d7c8/controllers/admin/config.go#L846), it should be:

```json
{
  "value": [
    {
      "key": "yklw5Imng",
      "comment": "Used by Tim."
    }
  ]
}
```

**Comment by gabek** [comment]
Most of the API documentation is wrong at this point. If you're curious to read more: #3086 #3302
