### ISSUE TITLE
Can't post message on chat

### ISSUE THREAD

**Issue by justine-dequidt** [owncast/owncast#3394]
### Share your bug report, feature request, or comment.

I have a owncast application that turn on a aws ec2 with systemctl. 
My owncast is online since 3 week, it's work god. But since yesterday I have a problem with the chat, we can see the chat but we can't post message. When we try to write a message and click in send button, nothing happens. 
I have an average of 300 users connected in the live but no one can post message. 

When a restart my server with systemctl restart and I relaunch a test live, I can post message but when all the users come to the live the problem come back. 

I not have error on owncast logs but I have this type of warning every time a new user comme to the live : 

warning | 10:29:33 AM 10/26/2023 | Client 10 Marie Therese_Borgoo has exceeded the messaging rate limiting thresholds and messages are being rejected temporarily.
-- | -- | --

I not logs error when I try to post a message. 

For more informations my server is ec2 instance type : 

c5.2xlarge
vCPU : 8
Gio : 16
Gbit/s : Up to 10
Mbit/s : Up to 4,750

I don't no where to look for fix this error, can you help me for this. 

Thankyou

Cordially,
Justine

**Comment by gabek** [comment]
The message you posted is a valid message when somebody sends too many messages quickly. Is that person you? Or somebody else? If it's somebody else it looks like somebody is trying to flood your server with chat messages? I'm just guessing here, I don't really have any idea. But if that's true you should ban that user you posted above.

Anything interesting in your browser console logs?
