### ISSUE TITLE
kein Chat bei https

### ISSUE THREAD

**Issue by Bambam11699** [owncast/owncast#3416]
### Discussed in https://github.com/owncast/owncast/discussions/3415

<div type='discussions-op-text'>

<sup>Originally posted by **Bambam11699** November  5, 2023</sup>
Ich habe das Problem, daß der chat nur ohne TLS (https) verschlüsselung funktioniert (http). Owncast läuft auf Ubuntu 22 mit NGINX und dieser configuration. 

https://hoerli.net/owncast-der-eigene-livestream-server/

```
server {
    listen 80;
    listen [::]:80;
    access_log  /var/log/nginx/owncast.domain.com.access.log;
    error_log   /var/log/nginx/owncast.domain.com.error.log;
    server_name owncast.domain.com;
    # enforce https
    return 301 https://$server_name$request_uri;
}
 
server {
    listen 443 ssl http2;
    server_name owncast.domain.com;
 
    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_pass http://127.0.0.1:8080;
    }
 
        ssl_certificate /etc/letsencrypt/live/domain.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/domain.com/privkey.pem;
 
}
```</div>

**Comment by gabek** [comment]
Make sure you are properly handling websockets in your proxy. 

https://owncast.online/docs/troubleshooting/#chat-is-disabled

https://owncast.online/docs/sslproxies/

![image](https://github.com/owncast/owncast/assets/414923/d6e154e9-56aa-4dc7-9fff-5b8ee0181a98)

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="https://owncast.online/favicon.png" height="14"> Owncast</div><div><strong><a href="/docs/troubleshooting/">Troubleshooting</a></strong></div><div>Some categories of issues you might run into and some next steps to help troubleshoot.</div></blockquote>
<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="https://owncast.online/favicon.png" height="14"> Owncast</div><div><strong><a href="/docs/sslproxies/">SSL & HTTP Proxies</a></strong></div><div>Put your Owncast server behind a proxy to enable SSL.</div></blockquote>

**Comment by rmens** [comment]
My pro tip would be: just use Caddy. It's way easier to configure than nginx and doesn't have any problems with websockets for chat.

**Comment by Bambam11699** [comment]
Thanks, i would test it.

**Comment by Bambam11699** [comment]
Thx is Fixed
