### ISSUE TITLE
Bug: "Error: too many colons in address"

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3419]
### Share your bug report, feature request, or comment.

```
ERRO[2023-11-08T17:59:12-08:00] address ::ffff:127.0.0.1: too many colons in address
```

I'm able to reproduce this by accessing localhost. My guess is this is another issue from the changes in #3349.

**Comment by LittleFox94** [comment]
I just saw this warning and remembered this changelog entry, so maybe it's not fixed yet?

<details>
<summary>logs</summary>

(address obfuscated slightly, assume just some hex digits replaced with `xxxx`)

```
littlefox@LF-DebPC:~ $ kubectl -n owncast logs -f owncast-6df665d74b-qqcj5
time="2023-11-25T16:25:55Z" level=info msg="Owncast v0.1.2-linux-64bit (b2c0ab46621ed7832b3cead594fb24cf21c395c5)"
time="2023-11-25T16:25:55Z" level=info msg="Web server is listening on port 8080."
time="2023-11-25T16:25:55Z" level=info msg="Configure this server by visiting /admin."
time="2023-11-25T16:25:56Z" level=error msg="remove data/hls/0/stream.m3u8: no such file or directory"
time="2023-11-25T16:26:12Z" level=error msg="address 2001:9e8:xxxx:4201:xxxx:7dff:fe53:xxxx: too many colons in address"
time="2023-11-25T16:26:12Z" level=error msg="address 2001:9e8:xxxx:4201:xxxx:7dff:fe53:xxxx: too many colons in address"
```

**Comment by armadi1809** [comment]
@gabek I just saw this. I can definitely take a look since it's something I worked on in the past.

**Comment by gabek** [comment]
@armadi1809 Awesome! And yeah, different versions of this keep popping up haha. Thank you!

**Comment by armadi1809** [comment]
@gabek  I think I found the issue happening here. The `SplitHostPort` function does not deal with long IP addresses like the one above very well. One thing we could do here is find add a "[" to the beginning of the address and a "]" to the position right before the last index of the ":" in the ip provided. So what we pass to the `SplitHostPort` will look like "[Host]:Port" which should work no matter how long the host is.

**Comment by gabek** [comment]
If you want to give that a try, and write some tests around all the different versions of IP address formatting (ipv4, ipv6, with port, without port, etc), let's try it!
