### ISSUE TITLE
Authentication/ Admin: Do not always log auth fails

### ISSUE THREAD

**Issue by jeyemwey** [owncast/owncast#342]
Browsers do automatically send `GET /admin` requests with bad credentials (speak "no credentials") on their first request. While it's technically true that this is a bad login, I would not expect to see it logged. Users might not realize that it was them, and might be worried that they did something wrong or are under attack.

This is what it looks like when you log in to the admin page after a fresh clone and without bad logins:

![image](https://user-images.githubusercontent.com/2796271/98907344-f6ec4e80-24be-11eb-93b8-74d414f224fa.png)

_tldr_: Do not always log bad logins, only if the request contains a username or password.

**Comment by gabek** [comment]
I wonder if we should be logging auth at all.  All it does is make people paranoid, but there's nothing really they can do about it.  Maybe we should just put them behind verbose logging.  If anything logging _successful_ logins is probably more useful so you could see if somebody else got in.

**Comment by jeyemwey** [comment]
Maybe, we can log all login requests on a lower level than WARNING? Like info or debug? It might be useful sometimes, but not always.

**Comment by gabek** [comment]
Yeah that's what I'm thinking too.  I'll take care of that.
