### ISSUE TITLE
Cannot persist admin pass change via command 

### ISSUE THREAD

**Issue by nobicycle** [owncast/owncast#3426]
### Share your bug report, feature request, or comment.

owmcast 0.1.1

```
sudo -u owncast bash -c "cd;/usr/bin/owncast -webserverport $OWNCAST_PORT -webserverip $OWNCAST_IP  -adminpassword '$PASS' "

NFO[2023-11-14T16:31:53+08:00] Admin password changed                       
INFO[2023-11-14T16:31:53+08:00] Saving new web server port number to 8095    
INFO[2023-11-14T16:31:53+08:00] Saving new web server listen IP address to 192.168.1.100 
INFO[2023-11-14T16:31:53+08:00] Web server is listening at 192.168.1.100:8095. 
INFO[2023-11-14T16:31:53+08:00] Configure this server by visiting /admin.    
```
login is OK  with '$PASS

However to stop the _sudo -u owncast bash_   process I must CTRL-C
After owncast restart the password reverts to the default password.

**Comment by gabek** [comment]
I'm not able to reproduce this.

This is what I did:

1. Ran owncast with the `--adminpassword` flag and specified a new password
2. Killed owncast
3. Restarted owncast without the `--adminpassword` flag
4. Accessed the admin with the new password. It worked.
5. Accessed the admin with the old password. It did not work.

![image](https://github.com/owncast/owncast/assets/414923/e89c6945-eab8-4e4a-a0e7-efe76ae41093)
