### ISSUE TITLE
extraUserInfoFileName does not exist

### ISSUE THREAD

**Issue by muesli** [owncast/owncast#344]
`extraUserInfoFileName` as mentioned on https://owncast.online/docs/configuration/ does not seem to exist anymore.

**Comment by gabek** [comment]
It's totally confusing, but that documentation is actually for the most recent release `0.0.2`, and `master` doesn't currently have any documentation.  So changes like that get are confusing when setting up master but following the previous documentation.  In this case the path to `content.md` has moved to `data`.  Sorry about that!

**Comment by muesli** [comment]
Oh, that absolutely makes sense! Not too uncommon with fresh projects, could have probably figured that out myself :smile:

Shall we keep this issue open or is it a common task before releases to update/check the docs?

**Comment by gabek** [comment]
It'll be a part of the 0.0.3 changelog.  In case it's helpful, here's the other breaking changes from that that list:

- `chat.db` has been renamed to `owncast.db` and moved to the `data` directory.
- The default logos have been moved to `/img/logo.svg`, so if you have been using the default logo images in your config file, point to this new file instead.
-  `content.md` now lives in `/data`.
