### ISSUE TITLE
Chat background is not affected by background-color in custom css 

### ISSUE THREAD

**Issue by DidierMalenfant** [owncast/owncast#3454]
### Share your bug report, feature request, or comment.

I'm trying to integrate chat into my stream in OBS. I'm following the instructions found [here](https://owncast.online/docs/embed/#using-obs) and I've set the custom CSS to:
```
html {
   margin: 0px;
   background-color: rgba(0,0,0,0.5);
   font-size: 30px;
   }
```
which I expected to make the background semi transparent. It looks like this is not the case:
<img width="975" alt="Screenshot 2023-11-29 at 11 52 12" src="https://github.com/owncast/owncast/assets/98774335/a71608b4-1281-49ca-a592-efe2655f6420">

Am I going wrong somewhere?

**Comment by gabek** [comment]
Selecting `html` probably does set the document's background color, but there's likely a more specific selector for chat background that overrides that.

Try
```css
#chat-container {
  background-color: orange;
}
```

![image](https://github.com/owncast/owncast/assets/414923/bdc694c6-e579-4cff-b79b-01a83ec3f552)

**Comment by DidierMalenfant** [comment]
Thanks! That definitely did the trick.

If you're trying to make the chat background transparent you'll also need to add:
```
body {
   background-color: rgba(0, 0, 0, 0);
   }
```

otherwise there is another background rendering underneath it.

Should I update the documentation that mentions OBS integration with this info?

**Comment by gabek** [comment]
That'd be great, thanks so much!

**Comment by DidierMalenfant** [comment]
PR is submitted https://github.com/owncast/owncast.github.io/pull/133
