### ISSUE TITLE
[REQUEST] - Dynamic Stream Title (Based on input file)

### ISSUE THREAD

**Issue by tokenwizard** [owncast/owncast#3466]
### Share your bug report, feature request, or comment.

This may already be possible and I've just missed documentation on how to do this. Apologies if that is the case. 

I plan to occasionally stream "playlists" or multiple video files I have locally. I can script ffmpeg to send the files in sequence to my Owncast streaming server and that works pretty well. What I would like to do is have a way for the Stream Title to update dynamically, based on the file name I'm sending to Owncast or some other method. 

How could I achieve this? 

TIA!

**Comment by gabek** [comment]
There's not really a concept of "file names". I'm sure there could be a way to embed the file name into the RTMP metadata, but Owncast wouldn't do anything with that.

The solution would be to use the Owncast API to set the stream title each time you change files on the broadcasting side. How you'd detect the file change is something you'd need to figure out with ffmpeg, however.

Here's the API you'd want to use. It requires an access token. https://owncast.online/api/latest/#tag/Integrations/paths/~1api~1integrations~1streamtitle/post

<blockquote><div><strong><a href="https://owncast.online/api/latest/#tag/Integrations/paths/~1api~1integrations~1streamtitle/post">Owncast</a></strong></div></blockquote>

**Comment by tokenwizard** [comment]
Ok, thanks for that. I think I can make that work. 
Looking at the API docs, it looks like I need this application/json format and the "value" key. I've tried POSTing this to my server but I get "unauthorized" response. 

`curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer <<access token>>" -d '{"value": "Testing Stream Title!"}' http://192.168.12.50:8080/api/integrations/streamtitle`


UPDATE: I figured it out. I had to create an access token that had admin access. All good now. Thanks!

**Comment by tokenwizard** [comment]
For anyone who might stumble on this an want to know my solution. I am just using a for loop to first set the Stream Title to the filename and then send the file via ffmpeg. This will cycle through each mkv file in the current folder and stream it in turn, first setting the Stream Title. 
```
#!/bin/bash
# set the file extension of your media
file_ext='mkv'

# set your server IP and Port
server_ip=<your_ip>
server_port=<your_port>
rtmp_port=<your_rtmp_port>

# set your stream key
stream_key='<your_stream_key>'

# iterate through each media file and replace spaces with underscores for the Stream Title (NOTE: change <your_access_token> to yours that you created)
for file in *.${file_ext}; do 
        title=$(echo $file | tr ' ' '_'); 
        curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer <your_access_token>" -d '{"value": "'$title'"}' http://${server_ip}:${server_port}/api/integrations/streamtitle; ffmpeg -re -i "$file" -c:v copy -c:a copy -f flv rtmp://${server_ip}:${rtmp_port}/live/"$stream_key";
done

```

**Comment by gabek** [comment]
Very cool!
