### ISSUE TITLE
Videojs error "The media playback was aborted due to a corruption problem..."

### ISSUE THREAD

**Issue by SpectreZ64** [owncast/owncast#3471]
Sometimes my viewers has an error `VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) The media playback was aborted due to a corruption problem or because the media used features your browser did not support`. In Owncast log `time="2023-12-07T07:52:52Z" level=error msg="exit status 1"`. My viewers can only restart stream page and connect to stream again. This error occured about every half hour. 
My server quite powerful and configured for using S3 Storage (Backblaze). Owncast ran via Docker container with autorestart on fail feature. I tryed to modify video configuration, but it's not help me with this trouble.
How I can inspect this error more informative? Maybe I can configufe log for writing some detail information?

**Comment by rmens** [comment]
Are you using passthrough mode?

**Comment by SpectreZ64** [comment]
No, I have 4 output settings without passthrough mode.

**Comment by gabek** [comment]
Sounds like this is a new case I hadn't added to the [Troubleshooting page](https://owncast.online/troubleshoot).

Would you mind putting your stream through [HLS Analyzer](https://hlsanalyzer.com/) to see what it's reporting back?

**Comment by SpectreZ64** [comment]
@gabek thank you for your response.
HLS Analyzer has found two errors with my low quality stream settings:

`1702393783: ERROR EC-2001: The ratio of measured peak bitrate (462.23 kbps) to specified bitrate (369.60 kbps) is 125.06%, which exceeds recommended 125% maximum. (29 seconds ago)`

`1702393783: ERROR EC-2001: The ratio of measured peak bitrate (1599.75 kbps) to specified bitrate (1249.60 kbps) is 128.02%, which exceeds recommended 125% maximum. (1 minute, 2 seconds ago)`

**Comment by gabek** [comment]
That wouldn't be connected.

One thought, are you sure you have the video codec installed on your playback device? Have you tried other browsers?

**Comment by SpectreZ64** [comment]
This errors fired in some different devices randomly with different browsers and OS.

I have try some other tests in HLS Analyzer and collected this errors with similar contents:

```
1702901948: ERROR EC-2002: Could not download segment https://s3.eu-central-003.backblazeb2.com/ambdoc/hls/3/stream-EZHazzdIg-1572.ts (1 minute, 8 seconds ago)
1702901948: Timeout condition: (28, 'Operation timed out after 4502 milliseconds with 0 bytes received')

1702903071: ERROR EC-2002: Could not download segment https://s3.eu-central-003.backblazeb2.com/ambdoc/hls/1/stream-EZHazzdIg-1947.ts (51 seconds ago)
1702903071: Timeout condition: (28, 'Operation timed out after 4500 milliseconds with 0 bytes received')

1702910300: ERROR EC-2002: Could not download segment https://s3.eu-central-003.backblazeb2.com/ambdoc/hls/2/stream-EZHazzdIg-4358.ts (4 minutes, 33 seconds ago)
1702910300: Timeout condition: (28, 'Operation timed out after 4501 milliseconds with 0 bytes received')
```

I suspect it's may be because my server location in Russia and cloud storage in Europe. I will try to use another cloud storage (Yandex Object Storage), if I can configure integration.

**Comment by gabek** [comment]
I would test not using object storage at all, to make sure things are working without additional settings.
