### ISSUE TITLE
Do not send a join chat event if that user is already in the chat

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3487]
### Share your bug report, feature request, or comment.

![image](https://github.com/owncast/owncast/assets/414923/1ae7ff01-13eb-41bd-aff3-323ec18fbff6)

**Comment by dev265545** [comment]
I would like to take this issue

**Comment by gabek** [comment]
Awesome, thanks @dev265545!

**Comment by gabek** [comment]
Hi @dev265545, just wanted to check in. Are you still looking at this? Thanks!

**Comment by varungujarathi9** [comment]
Hi @gabek I would like to work on this!

**Comment by gabek** [comment]
Awesome, thanks @varungujarathi9!
