### ISSUE TITLE
Thumbnails do not generate when using S3 path prefix

### ISSUE THREAD

**Issue by rmens** [owncast/owncast#3518]
### Share your bug report, feature request, or comment.

I'm using one bucket to serve 2 streams from separate Owncast servers, so i set the s3 endpoints to:
- https://xxxxx.r2.cloudflarestorage.com/1
- https://xxxxx.r2.cloudflarestorage.com/2

The files are uploaded correctly and streaming works. However the clean-up of old segments fails with the error code:

 `Unable to fetch list of items in bucket for cleanup: NoSuchKey: The specified key does not exist. status code: 404, request id: , host id:`

This might be a case that was never tested.

<img width="1249" alt="Scherm­afbeelding 2024-01-13 om 00 43 20" src="https://github.com/owncast/owncast/assets/6742496/cc80927f-2790-4763-ab9d-65691bc752e9">

Owncast v0.1.2-linux-arm64 (b2c0ab46621ed7832b3cead594fb24cf21c395c5)

**Comment by gabek** [comment]
That's not a supported use case, and I'm surprised it didn't completely break. Though I guess it kind of totally broke. But I'm surprised it worked at all!

However, with v0.1.2 path prefixes went in. It seems to be just what you're looking for, except it's supported and hopefully works. Though, I don't think anybody has used it, so you'll be an early adopter. 

Remove `/2/` from your thing above and put it in the thing below.

![image](https://github.com/owncast/owncast/assets/414923/8104950c-3d09-4f35-9dbf-35cbaff190d6)

**Comment by rmens** [comment]
Oops! I’ll give the correct way a spin and will report back with the results.

**Comment by rmens** [comment]
Seems to go OK-ish. I enabled verbose logging and am seeing these errors quite a lot. They don't seem to affect streaming much and the bucket do gets cleaned.

```
time="2024-01-15T14:59:26+01:00" level=trace msg="Removing chat messages older than 2 hours"
time="2024-01-15T14:59:40+01:00" level=debug msg="Deleting 60 objects from S3 bucket: zwtv"
time="2024-01-15T15:00:20+01:00" level=debug msg="data/hls/0/stream.m3u8 does not yet exist locally when trying to upload to S3 storage."
time="2024-01-15T15:00:23+01:00" level=error msg="remove data/hls/0/stream.m3u8: no such file or directory"
time="2024-01-15T15:00:41+01:00" level=debug msg="Deleting 60 objects from S3 bucket: zwtv"
time="2024-01-15T15:01:41+01:00" level=debug msg="Deleting 63 objects from S3 bucket: zwtv"
```

I did notice the thumbnail not getting updated (its 40mins old now) and there is a mysterious `exit status 1` in the logs. Maybe the thumnailer crashed.

```
time="2024-01-15T14:17:42+01:00" level=debug msg="Deleting 60 objects from S3 bucket: zwtv"
time="2024-01-15T14:18:41+01:00" level=debug msg="Deleting 60 objects from S3 bucket: zwtv"
time="2024-01-15T14:19:26+01:00" level=trace msg="Removing chat messages older than 2 hours"
time="2024-01-15T14:19:40+01:00" level=debug msg="Deleting 60 objects from S3 bucket: zwtv"
time="2024-01-15T14:20:21+01:00" level=error msg="exit status 1"
time="2024-01-15T14:20:24+01:00" level=error msg="remove data/hls/1/stream.m3u8: no such file or directory"
time="2024-01-15T14:20:41+01:00" level=debug msg="Deleting 60 objects from S3 bucket: zwtv"
time="2024-01-15T14:21:41+01:00" level=debug msg="Deleting 60 objects from S3 bucket: zwtv"
time="2024-01-15T14:22:41+01:00" level=debug msg="Deleting 60 objects from S3 bucket: zwtv"
time="2024-01-15T14:23:41+01:00" level=debug msg="Deleting 60 objects from S3 bucket: zwtv"
```

@gabek Would `-enableDebugOptions` give me more clarity about the thumbs?

**Comment by gabek** [comment]
It certainly can't hurt!

**Comment by rmens** [comment]
This doesn't only occur when using a path prefix. I'll make a new ticket and close this one https://github.com/owncast/owncast/issues/3522
