### ISSUE TITLE
mobile-chat-button is displayed for mobile users when chat is disabled.

### ISSUE THREAD

**Issue by FireTime** [owncast/owncast#3535]
### Share your bug report, feature request, or comment.

Small issue, even with chat disabled for Owncast a non functional chat button is displayed on the mobile UI. 

My Current work around is hiding the button with the custom CSS
`#mobile-chat-button{
  display:none;
}`

Screen shot on phone and narrow desktop browser.
<img width="340" alt="button" src="https://github.com/owncast/owncast/assets/8028436/81df8456-62fd-43fc-b809-b4d42c3b993e">

**Comment by armadi1809** [comment]
I can take this @gabek

**Comment by gabek** [comment]
Awesome, thanks @armadi1809!

**Comment by gabek** [comment]
Hi there @armadi1809! Just checking in to see if you're still looking at this, or if I could answer any questions. Thanks!

**Comment by armadi1809** [comment]
@gabek Yes! Sorry, totally forgot about it. I will have something in the next couple of days.

**Comment by gabek** [comment]
I'll jump on this sometime this week just to get it closed out for the next release. If you're working on it, feel free to continue!
