### ISSUE TITLE
Listening Stream via RTMP

### ISSUE THREAD

**Issue by NerdySoftPaw** [owncast/owncast#3538]
### Share your bug report, feature request, or comment.

It would bee great if the Stream is reachable to listen via RTMP (localhost only is ok), in some cases a RTMP Source is more stable then an HLS Source.

**Comment by gabek** [comment]
Owncast's goal is to have a scalable, adaptable, highly compatible stream that can be played by the most number of players, and supporting RTMP playback wouldn't work towards that goal. There's nothing inherently unstable about HLS playback, but I understand it can take additional effort to find the right settings for your particular use case.

Thank you for the suggestion!
