### ISSUE TITLE
Documentation broken link: https://is.gd/ZvSdpo

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3558]
# Broken link found in Owncast documentation

Please fix or remove the broken link https://is.gd/ZvSdpo from content/docs/codecs.md.
You can find the Owncast documentation site repository at https://github.com/owncast/owncast.github.io, and that is where you would make any fixes to broken links, or documentation in general. Thank you for helping improve our documentation!
        
- Failed: Network error 

        
        
- bad protocol version

**Comment by edmael** [comment]
The link is healty and correct: it's a redirect to https://lmddgtfy.net/?q=install%20libva-mesa-driver%20linux and works just fine.

<blockquote><div><strong><a href="https://lmddgtfy.net/?q=install%20libva-mesa-driver%20linux">Let Me DuckDuckGo That For You - LMDDGTFY</a></strong></div></blockquote>

**Comment by gabek** [comment]
Great, thanks for looking!
