### ISSUE TITLE
Documentation broken link: https://owncast.online/website

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3560]
# Broken link found in Owncast documentation

Please fix or remove the broken link https://owncast.online/website from https://owncast.online/docs.
You can find the Owncast documentation site repository at https://github.com/owncast/owncast.github.io, and that is where you would make any fixes to broken links, or documentation in general. Thank you for helping improve our documentation!
        
- Failed: Network error 404

        
- Status: 404

**Comment by varungujarathi9** [comment]
Hi @gabek 
Couldn't find [https://owncast.online/website](https://owncast.online/website) linked anywhere on the docs homepage, I think this one is a false negative

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="https://owncast.online/favicon.png" height="14"> Owncast</div><div><strong><a href="/404.html">404 Page not found</a></strong></div><div>Owncast is a free and open source live video and web chat server for use with existing broadcasting software. Point your live stream at a Owncast server you personally control and regain ownership over your content.</div></blockquote>

**Comment by gabek** [comment]
Thank you!
