### ISSUE TITLE
Documentation broken link: https://owncast.online/encoding

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3561]
# Broken link found in Owncast documentation

Please fix or remove the broken link https://owncast.online/encoding from https://owncast.online/docs.
You can find the Owncast documentation site repository at https://github.com/owncast/owncast.github.io, and that is where you would make any fixes to broken links, or documentation in general. Thank you for helping improve our documentation!
        
- Failed: Network error 404

        
- Status: 404

**Comment by edmael** [comment]
I think this is already fixed: I can't find any sign of the standalone encoding page in the documentation.

**Comment by gabek** [comment]
Thanks for looking!
