### ISSUE TITLE
Documentation broken link: https://blog.rtrace.io/posts/hosting-owncast/

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3562]
# Broken link found in Owncast documentation

Please fix or remove the broken link https://blog.rtrace.io/posts/hosting-owncast/ from content/examples/blogs-tutorials.md.
You can find the Owncast documentation site repository at https://github.com/owncast/owncast.github.io, and that is where you would make any fixes to broken links, or documentation in general. Thank you for helping improve our documentation!
        
- Failed: Network error 

        
        
- bad protocol version

**Comment by unclearParadigm** [comment]
Hey @gabek - the Link is working. The site is served through TLS v1.3 only though. Could it be that the Link Checker used to generate these cannot handle TLS v1.3 properly?

**Comment by gabek** [comment]
Very likely! Thanks for checking in!

**Comment by unclearParadigm** [comment]
Which tool/script/"black magic" generated these "Documentation Missing Link"-issues? If that's something "as-code" I could have a look on how to enable TLSv1.3 accordingly
