### ISSUE TITLE
Documentation broken link: https://jit.org/

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3571]
# Broken link found in Owncast documentation

Please fix or remove the broken link https://jit.org/ from content/docs/broadcasting/jitsi.md.
You can find the Owncast documentation site repository at https://github.com/owncast/owncast.github.io, and that is where you would make any fixes to broken links, or documentation in general. Thank you for helping improve our documentation!
        
- Timeout

**Comment by edmael** [comment]
Pull request created: https://github.com/owncast/owncast.github.io/pull/166
