### ISSUE TITLE
Documentation broken link: https://developer.apple.com/documentation/http_live_streaming/understanding_the_http_live_streaming_architecture

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3580]
# Broken link found in Owncast documentation

Please fix or remove the broken link https://developer.apple.com/documentation/http_live_streaming/understanding_the_http_live_streaming_architecture from [content/docs/video.md](https://github.com/owncast/owncast.github.io/tree/master/content/docs/video.md).

You can find the Owncast documentation site repository at https://github.com/owncast/owncast.github.io, and that is where you would make any fixes to broken links, or documentation in general. Thank you for helping improve our documentation!

[Open documentation repository in editor](https://github.dev/owncast/owncast.github.io/tree/master/content/docs/video.md)

Source file: https://github.com/owncast/owncast.github.io/tree/master/content/docs/video.md
        
- Failed: Network error 404

        
- Status: 404

**Comment by brendenehlers** [comment]
Anyone opposed to me picking up this issue? Seems like a simple fix

**Comment by brendenehlers** [comment]
Went ahead and made a PR on the docs repo: https://github.com/owncast/owncast.github.io/pull/165

Updated the link to the new Apple Developer docs for HTTP Live Streaming
https://developer.apple.com/documentation/http-live-streaming

<blockquote><img src="https://docs.developer.apple.com/tutorials/developer-og.jpg" width="48" align="right"><div><img src="/favicon.ico" height="14"> Apple Developer Documentation</div><div><strong><a href="https://docs.developer.apple.com/documentation/http-live-streaming">HTTP Live Streaming | Apple Developer Documentation</a></strong></div><div>Send audio and video to iOS, tvOS, and macOS devices.</div></blockquote>

**Comment by gabek** [comment]
Awesome, thank you!
