### ISSUE TITLE
 invalid streaming key？

### ISSUE THREAD

**Issue by jackymaxzzz** [owncast/owncast#3595]
### Share your bug report, feature request, or comment.

My rtmp software does not support Stream Keys to auth. Can I add authentication information to rtmpURL, for example: rtmp://xxx.xxx.xxx:1935/live?authkey=abcxxxxxx

Thank U for Ask

**Comment by gabek** [comment]
https://owncast.online/quickstart/startstreaming/

> If your software doesn’t have a way to specify a stream key simply use the url rtmp://yourserver/live/streamkey and use your specific stream key instead.

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="https://owncast.online/favicon.png" height="14"> Owncast</div><div><strong><a href="/quickstart/startstreaming/">Start Streaming</a></strong></div><div>Point your broadcasting software at your new server using rtmp://yourserver/live and the stream key you set above and start your stream.</div></blockquote>

**Comment by jackymaxzzz** [comment]
rtmp://yourserver/live/streamkeyabc123456 or  rtmp://yourserver/live/streamkey=123456 or  rtmp://yourserver/live/streamkey?123456

**Comment by gabek** [comment]
Please read above. It says: `rtmp://yourserver/live/streamkey`
