### ISSUE TITLE
How to edit the index.html??

### ISSUE THREAD

**Issue by jackymaxzzz** [owncast/owncast#3597]
### Share your bug report, feature request, or comment.

I installed owncast with Docker, but I want to edit the index.html file. How should I do it?
I searched all disks but couldn't find the index.html file.

**Comment by jackymaxzzz** [comment]
I searched all disks but couldn't find the index.html file.

**Comment by gabek** [comment]
There is no index.html file you can edit, as Owncast is not just a bunch of web pages. If you wish to modify your copy of Owncast outside of the appearance and customization options provided, you must pull down the source code, make your changes, and create a build for yourself.
