### ISSUE TITLE
Replace unsupported Picmo emoji picker with something else

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3598]
### Share your bug report, feature request, or comment.

Unfortunately, our emoji picker, [Picmo](https://github.com/joeattardi/picmo), is no longer supported. While Picmo isn't going to stop working out of nowhere immediately, it may stop working due to changes in React or some other dependency at some point down the road. I'd rather us remove this library on our schedule instead of somebody else's schedule.

See [EmojiPicker.tsx](https://github.com/owncast/owncast/blob/develop/web/components/chat/ChatTextField/EmojiPicker.tsx) for our implementation of the emoji picker.

I don't have a preference on what we replace it with, but if anybody has recommendations, feel free to suggest them here!

**Comment by dev265545** [comment]
You can look at Emoji-mart -> https://github.com/missive/emoji-mart

<blockquote><img src="https://repository-images.githubusercontent.com/63091815/e0e2b113-1c2c-4dd9-b12b-ab8111d68c9d" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/missive/emoji-mart">GitHub - missive/emoji-mart: 🏪 One component to pick them all</a></strong></div><div>🏪 One component to pick them all. Contribute to missive/emoji-mart development by creating an account on GitHub.</div></blockquote>

**Comment by DarkFalc0n** [comment]
Is this issue being addressed currently? I was going through emoji mart earlier, and I think I can handle this migration.

**Comment by gabek** [comment]
@DarkFalc0n It's not yet! I truly appreciate you offering to look into it! I'm not sure how emoji mart handles custom emoji, but feel free to throw out any thoughts if you run into anything there. Thank you so much!

**Comment by DarkFalc0n** [comment]
Hey @gabek sorry for the late update, 
I tried emojimart on a test project and it works well. Also the way to add custom emojis is pretty straightforward,
the `<Picker />` element can take a custom prop, which is declared as follows:
```ts
const custom = [
  {
    id: "github",
    name: "GitHub",
    emojis: [
      {
        id: "octocat",
        name: "Octocat",
        keywords: ["github"],
        skins: [
          {
            src: "https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png",
          },
        ],
      },
    ],
  },
];
```

**Comment by gabek** [comment]
See #3867 for a discussion about mobile emoji picking when this is worked on.
