### ISSUE TITLE
No -webserverip setting on admin UI?

### ISSUE THREAD

**Issue by ozgurkazancci** [owncast/owncast#3602]
Hi, first of all, thanks very much for owncast!

According to #981, -webserverip was implemented few years ago. However, I still cannot find such setting on admin UI? Am I missing something? I'm going to set nginx reverse proxy with TLS termination for my owncast instance and I need to set my owncast webserver to only bind on; 127.0.0.1.

OS: FreeBSD
Owncast version: v0.0.13 (installed through the FreeBSD pkg repository)

Regards.

**Comment by gabek** [comment]
Run `owncast` with `--help` to see all the command line flags. One of them is the IP flag you're looking for. It is not a part of the admin.

**Comment by ozgurkazancci** [comment]
Thanks @gabek for your reply, I was aware of the switches after owncast command in terminal, however it's impossible to use both web admin UI and terminal switches all together, it just gets messed up.

As a feature request; would you wish to add it on admin UI as well?

Regards.

**Comment by gabek** [comment]
How would you be able to access the admin at all if owncast isn't listening on your required IP address or interface? That's not something you'd be able to change in the admin. That's why it's a command line flag, it must be set upfront, otherwise you'd be dead in the water with a completely inaccessible service.

This isn't something I plan to change, as it's built this way to solve a very specific problem for people, and it should work for you as well. If it's not working, however, then it should be fixed.

**Comment by ozgurkazancci** [comment]
I managed to set owncast listen only on 127.0.0.1, so that having nginx reverse proxy with TLS termination would be worth.

My overall aim was, to prevent people access;

http://ip.addr.of.myvps/hls/stream.m3u8

and only make this one accessible;
httpS://live.mydomain.com/hls/stream.m3u8

And this was achieved with "-webserverip 127.0.0.1" switch, and "proxy_pass http://127.0.0.1" parameter of nginx.

Thanks.

**Comment by jeremiaspt** [comment]
> I managed to set owncast listen only on 127.0.0.1, so that having nginx reverse proxy with TLS termination would be worth.
> 
> My overall aim was, to prevent people access;
> 
> http://ip.addr.of.myvps/hls/stream.m3u8
> 
> and only make this one accessible; [httpS://live.mydomain.com/hls/stream.m3u8](httpS://live.mydomain.com/hls/stream.m3u8)
> 
> And this was achieved with "-webserverip 127.0.0.1" switch, and "proxy_pass http://127.0.0.1" parameter of nginx.
> 
> Thanks.

can this be done using nginx-proxy-manager?
