### ISSUE TITLE
ffmpeg will add a ending video that says live is ended and its owncast logo

### ISSUE THREAD

**Issue by moonshadowrev** [owncast/owncast#3618]
### Share your bug report, feature request, or comment.

when stream finishes , users when viewing live , ffmpeg will add a ending video that says live is ended and its owncast logo

**Comment by gabek** [comment]
Owncast does it, but you are correct. If you have a request, or you are opening a bug, please open an issue with details.

**Comment by moonshadowrev** [comment]
is there any way that you can call another offline.tsclip for your stream manually or in admin dashboard?

**Comment by gabek** [comment]
See https://github.com/owncast/owncast/issues/1965 for details.
