### ISSUE TITLE
/admin url protection?

### ISSUE THREAD

**Issue by ozgurkazancci** [owncast/owncast#3625]
Hey all.

Is there any option to change the /admin URL with a customized name?

Alternatively, by the help of nginx (using it as Reverse SSL Proxy for owncast), it's possible to limit /admin to a list of IPs and I can do this, though, would love to know if that would hurt the stability of owncast?

Regards.

**Comment by gabek** [comment]
You would want to try to do this all with your proxy. I've never tried it myself, however. Owncast's paths are what they are, but if you wanted to try doing some url rewrites in your proxy that might be a solution to what you're looking for. Same thing with limiting IPs to the admin path.

Owncast works as a standard web server, so anything you'd normally do with web infrastructure to lock it down, in any way you choose, you should be able to do with Owncast.

**Comment by rmens** [comment]
I recommend doing this with Caddy webserver instead of nginx. It's way simpler. Something like this for your `Caddyfile` should work. Typed it without checking but you get the idea

```
owncast.example.org {
  @adminAccess {
    path /admin*
    remote_ip 1.2.3.4
  }

  handle @adminAccess {
    reverse_proxy 127.0.0.1:8080
  }

  handle {
    reverse_proxy 127.0.0.1:8080
    encode gzip
  }

  tls admin@example.org
}
```

**Comment by ozgurkazancci** [comment]
I did it a while ago with nginx, like;

```
server {
server_name mystream.mysite.com;

....

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_pass http://127.0.0.1:8080;
    }

location ^~ /admin {
allow 1.2.3.4;
deny all;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_pass http://127.0.0.1:8080/admin;

}

}

```

Hopefully it's a good one.

**Comment by rmens** [comment]
That works too! 

Just a small tip. Have you considered moving all your variables up a block so they are not redundant? something like this

```
server {
    server_name mystream.mysite.com;

    # Common proxy settings
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Server $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade"; 
    
    location / {
        proxy_pass http://127.0.0.1:8080;
    }

    location ^~ /admin {
        allow 1.2.3.4;
        deny all;
        proxy_pass http://127.0.0.1:8080/admin;
    }
}
```

**Comment by ozgurkazancci** [comment]
Good idea, I've just tried the one above, however nginx gives Gateway Error with the configuration **both** above and for the following one;

```
   location / {
        include vhosts/proxy.conf;
        proxy_pass http://127.0.0.1:8080;
    }

    location ^~ /admin {
        allow 1.2.3.4;
        deny all;
        include vhosts/proxy.conf;
        proxy_pass http://127.0.0.1:8080/admin;
    }


# cat proxy.conf
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Server $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;

```

So, back to my original conf.

**Comment by ozgurkazancci** [comment]
One more good one - thank you! It works.

Any reason you set "_proxy_set_header Connection $upgrade;_"
instead of "_proxy_set_header Connection $connection_upgrade;_"?

**Comment by ozgurkazancci** [comment]
And while we're at it, @rmens what do you think about these directives, to use with owncast?

```
proxy_buffering           off;
proxy_ignore_client_abort on;
```
Regarding proxy_ignore_client_abort, Maxim Dounin says;

"Switching proxy_ignore_client_abort to on may be needed in the
following cases I'm aware of:

- you need to maintain compatibility with clients that half-close
connections after sending a request;

- your backend doesn't check if a connection is closed while
generating a response (and hence closing the connection by nginx
will not abort the request processing on the backend), and at the
same time you want nginx to maintain limit_conn numbers mostly
matching actual resources used on the backend;

- your backend does check if a connection is closed, but you don't
want this to happen as you code can't really cope with it."

https://forum.nginx.org/read.php?2,253026,253029#msg-253029

And the last comment on this page, regarding this directive and HLS:
https://trac.ffmpeg.org/ticket/8647#comment:2

**Comment by rmens** [comment]
> One more good one - thank you! It works.
> 
> Any reason you set "_proxy_set_header Connection $upgrade;_" instead of "_proxy_set_header Connection $connection_upgrade;_"?

It was a shortcut to save you one more variable/configuration. But it's not recommended according to the Owncast documentation (https://owncast.online/docs/sslproxies/nginx/). I would stick to that and ignore my shortcut since it was a bit short sighted.

About `proxy_buffering`: you really don't want any buffering of your livestream. Keep that off. I'm not sure if `proxy_ignore_client_abort` actually matters a lot. Keeping it on might reduce the error rate you see in Owncast when you are serving a viewer with an unstable connection. But it probably doesn't matter a lot if you don't have thousands of concurrent connections.

**Comment by ozgurkazancci** [comment]
> About `proxy_buffering`: you really don't want any buffering of your livestream. Keep that off.

But in nginx, the default is;
proxy_buffering on;

So, in addition to the directives above (and on the documentation as well),
_proxy_buffering off;_ also needs to be added?
The documentation does not mention it at all.

Regards.
