### ISSUE TITLE
Documentation broken link: https://golangci-lint.run/usage/install/#local-installation

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3633]
# Broken link found in Owncast documentation

First, **please verify that this link or asset is actually broken** by testing the correct page that is in production at https://owncast.online. Then you can fix or remove the broken link https://golangci-lint.run/usage/install/#local-installation from [content/development.md](https://github.com/owncast/owncast.github.io/tree/master/content/development.md).

You can find the Owncast documentation site repository at https://github.com/owncast/owncast.github.io, and that is where you would make any fixes to broken links, or documentation in general. Thank you for helping improve our documentation!

[Open documentation repository in editor](https://github.dev/owncast/owncast.github.io/tree/master/content/development.md)

Source file: https://github.com/owncast/owncast.github.io/tree/master/content/development.md
        
- Failed: Network error 404

        
- Status: 404

**Comment by Jayanth-Parthsarathy** [comment]
Hi @gabek. I would like to work on this. Please assign this to me

**Comment by gabek** [comment]
Thank you!
