### ISSUE TITLE
How to create multiple livestream

### ISSUE THREAD

**Issue by mdsohelmia** [owncast/owncast#3642]

**Comment by rmens** [comment]
One Owncast instance supports one stream.

You can spin up multiple Owncast instances, all on different ports. Put them behind a web proxy like Caddy with a different hostname per stream and proxy the Owncast ports on one server. I would keep in mind cpu usage in this scenario. If you spin up multiple instances and do hefty transcoding on that, it will cost a lot of CPU.

**Comment by gaby** [comment]
Is there still no built-in way of creating multiple streams?

**Comment by rmens** [comment]
> One Owncast instance supports one stream.
> 
> You can spin up multiple Owncast instances, all on different ports. Put them behind a web proxy like Caddy with a different hostname per stream and proxy the Owncast ports on one server. I would keep in mind cpu usage in this scenario. If you spin up multiple instances and do hefty transcoding on that, it will cost a lot of CPU.

Correct. This still stands.

**Comment by gaby** [comment]
> > One Owncast instance supports one stream.
> > You can spin up multiple Owncast instances, all on different ports. Put them behind a web proxy like Caddy with a different hostname per stream and proxy the Owncast ports on one server. I would keep in mind cpu usage in this scenario. If you spin up multiple instances and do hefty transcoding on that, it will cost a lot of CPU.
> 
> Correct. This still stands.

Thanks!

**Comment by gaby** [comment]
@rmens Is there a way to preconfigure `owncast` ? If i have to run multiple instances, I dont want to be manually setting up things via a UI, having a config file or way of predefining things would be great.

Looking through issues here in GH seems the `yaml` config file was removed in favor of a database.

**Comment by rmens** [comment]
@gaby I use these command line flags.

`-backupdir $OWNCAST_DIR/backup -database $OWNCAST_DIR/database -logdir /var/log/owncast -webserverport $APP_PORT -rtmpport $RTMP_PORT -streamkey $STREAM_KEY -adminpassword $ADMIN_PASSWORD`
