### ISSUE TITLE
Feature request: show viewers according to their stream variants

### ISSUE THREAD

**Issue by ozgurkazancci** [owncast/owncast#3649]
### Share your bug report, feature request, or comment.

The viewers panel in owncast is really cool thing, however would you mind adding opportunity to show the current viewers according to their connected stream output variant?

Let's say, in "Video configuration" we have 2 streaming variant;
1- 1500 kbps
2- 2500 kbps

It'd be great to see which one is preferred most by the viewers' devices, so that we could remove unused variants.

Regards.

**Comment by gabek** [comment]
This kind of already exists, in a way. If you go to the "Stream Health" page, under "Player Network Speed" you'll see all your different stream variants drawn on the graph, and the min/max/median download speeds. If the speed values are all much higher than your lowest configured quality, for example, then maybe your lowest is too low and not really benefiting anybody.
