### ISSUE TITLE
Can't stream vertical video

### ISSUE THREAD

**Issue by seltzdesign** [owncast/owncast#3651]
### Share your bug report, feature request, or comment.

I am trying to stream 16:9 vertical video and not having any luck. As soon as I switch OBS to output a vertical resolution I get a message that the format is not supported. As soon as I switch back to horizontal aspect ratio it works fine.

It also seems the embedded player has a fixed aspect ratio and if I change the size in the embed code to anything but 16:9, it simply stays at 16:9.

**Comment by seltzdesign** [comment]
Sorry, correction, I could get the vertical stream to work in the end, but the viewer cannot change aspect ratio, as the ratio is fixed in CSS:

![image](https://github.com/owncast/owncast/assets/6575829/ea30e1d2-f096-412c-b270-675faa79bf71)

**Comment by gabek** [comment]
Could you elaborate a bit? You said you get a message that the format is not supported. Where do you see that message? Could you share it?

**Comment by seltzdesign** [comment]
> Could you elaborate a bit? You said you get a message that the format is not supported. Where do you see that message? Could you share it?

Sorry, it was one of those coincidences. I changed the resolution in OBS and kept getting a warning that "the format is not supported" in the embedded viewer. But it turns out it must have been something else, probably because I was using passthrough and after a few Ctrl-Shift-R in the browser it was working.

What still is not working is changing the aspect ratio of the viewer, which I would say is a bug. You can specify the width and height of it and it should work with any aspect ratio. Hard-coding the 16:9 aspect ratio in the CSS is wrong in my opinion. There is no reason it should only work in that aspect ratio other than it being a workaround to not have to deal with some kind of responsiveness in the player.

**Comment by gabek** [comment]
The container holding the video player should be 16:9, but the player should not be forcing a resolution. Could you share what it looks like? Is it the same with the full web application vs. just the embed?

**Comment by lhupyn** [comment]
Hi everyone,

Regarding this issue about the video container, I wanted to share an idea on how its aspect ratio could be calculated and maintained fluidly. I based this on a technique explained at [https://faq.dailymotion.com/hc/en-us/articles/360022841393-How-to-preserve-the-player-aspect-ratio-on-a-responsive-page](https://faq.dailymotion.com/hc/en-us/articles/360022841393-How-to-preserve-the-player-aspect-ratio-on-a-responsive-page)

The common technique for this is using a 'padding hack' in CSS. The idea is to set the container's height relative to its width using `padding-top` or `padding-bottom` as a percentage.

**How to calculate the ratio for the padding:**

1.  Determine the desired aspect ratio (e.g., 16:9, 4:3).
2.  Calculate the percentage by dividing the height by the width and multiplying by 100.

    * **For 16:9:** `(9 / 16) * 100% = 56.25%`
    * **For 4:3:** `(3 / 4) * 100% = 75%`
    * **General formula:** `(height / width) * 100%`

**CSS Implementation:**

Then, you would apply this percentage to the `padding-bottom` (or `padding-top`) of the parent container, ensuring its `height` is `0` and it has `position: relative`. The child element (the `<iframe>` or `<video>`) is positioned absolutely to fill the container.

```css
.video-container {
  position: relative;
  width: 100%; /* Or the width you need */
  height: 0;
  padding-bottom: 56.25%; /* Example for 16:9 */
  overflow: hidden; /* Optional, to prevent overflows */
}

.video-container iframe,
.video-container video {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  border: 0; /* For iframes */
}

**Comment by lhupyn** [comment]
Attached are screenshots using a smartphone as a video source.

![Image](https://github.com/user-attachments/assets/b9241ccc-0053-4497-8b0b-eca9e0d51dfd)

![Image](https://github.com/user-attachments/assets/f059edbd-02b9-461e-8b5a-6128ca76d614)

The first screenshot is configured with a resolution of 1280x720 (landscape) and the second with a resolution of 720x1280 (portrait).

Could this be a possible solution for having a 'dynamic' ratio in the player container?
https://faq.dailymotion.com/hc/en-us/articles/360022841393-How-to-preserve-the-player-aspect-ratio-on-a-responsive-page


<blockquote><div><strong><a href="https://faq.dailymotion.com/hc/en-us/articles/360022841393-How-to-preserve-the-player-aspect-ratio-on-a-responsive-page">Just a moment...</a></strong></div></blockquote>

**Comment by gabek** [comment]
> Could this be a possible solution for having a 'dynamic' ratio in the player container?

Do you want to put up a PR with your suggestions?

**Comment by lhupyn** [comment]
> > Could this be a possible solution for having a 'dynamic' ratio in the player container?
> 
> Do you want to put up a PR with your suggestions?

I'd like to, but I'm not skilled enough to do it right now.
