### ISSUE TITLE
In the viewer minutes are sometimes shown as "undefined"

### ISSUE THREAD

**Issue by seltzdesign** [owncast/owncast#3652]
### Share your bug report, feature request, or comment.

I noticed in the normal embeddable viewer, when the stream starts it will say "undefined minutes 15 seconds" as an example. Only when it has run for more than a minute it will show "1 minutes 1 seconds".

I also just had it when the stream had run for more than 2 hours it is showing as "2 hours and undefined minutes".

![image](https://github.com/owncast/owncast/assets/6575829/33ee02fa-cc62-4f06-9375-a089f0f7d7b7)

**Comment by gabek** [comment]
Something certainly broke here, this never used to be a problem. Thanks for filing it.

**Comment by germainelee** [comment]
I just found undefined on [watch.owncast.online](https://watch.owncast.online/). 

![image](https://github.com/user-attachments/assets/42b0005f-ec5f-423e-9e47-18809fbae135)
