### ISSUE TITLE
An incorrect message is shown when the stream is live, but chat is disabled

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3657]
### Share your bug report, feature request, or comment.

When chat is purposefully disabled, but the stream is live, the "Chat is offline" message says "Chat will be available when chat stream is live". This is incorrect. This upper right chat notice should not be displayed at all if chat is not enabled on the server, if the stream is live or not. No need to notify a user about a service that isn't enabled, especially incorrectly.

![Selection_024](https://github.com/owncast/owncast/assets/414923/0cb26b10-b1c8-4f59-b24d-8a375f4f6de8)

**Comment by BreakTos** [comment]
Hello, Can i be assigned this one ?

**Comment by gabek** [comment]
Absolutely, thanks so much @BreakTos!

**Comment by gabek** [comment]
Even though I saw this in the wild, I was unable to reproduce myself. Closing.
