### ISSUE TITLE
New offline embed state not handling HTML

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3682]
### Share your bug report, feature request, or comment.

![image](https://github.com/owncast/owncast/assets/414923/b6bb0082-c944-4718-9150-32365eaff895)

**Comment by Jeetch8** [comment]
Hii, I would like to resolve this issue. Can you please assign it to me?
Thank u

**Comment by gabek** [comment]
Thanks so much, @Jeetch8!

**Comment by Jeetch8** [comment]
Hi, i have resolved the issue. Here is the pr raised #3684 .
Thank you for assigning the issue to me.
