### ISSUE TITLE
Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub

### ISSUE THREAD

**Issue by skitvandarken** [owncast/owncast#3717]

**Comment by gabek** [comment]
What is your question?

**Comment by mahmed2000** [comment]
Building owncast with `CGO_ENABLED=0` or without a C compiler installed, results in a binary that just prints that exact statement. Safe to close, unless you want to add that clarification somewhere in the docs.

**Comment by gabek** [comment]
Yeah, I'm just not sure what the question is about. It could be anything. We shouldn't update the docs for something we don't know what the question is. And in this case, we don't have documentation about how to compile Go programs, that's kind of out of scope. I just usually leave these open until they close themselves from lack of response.

**Comment by skitvandarken** [comment]
> Building owncast with `CGO_ENABLED=0` or without a C compiler installed, results in a binary that just prints that exact statement. Safe to close, unless you want to add that clarification somewhere in the docs.

Very clarifying. This is what I was missing. Thanks
