### ISSUE TITLE
Live streams that are between 24 and 25 hours display the time as "Live for 1 day undefined hours"

### ISSUE THREAD

**Issue by caldwell** [owncast/owncast#3727]
### Share your bug report, feature request, or comment.

I set up a long streaming instance of owncast and after 24 hours the time shown under the window says

> Live for 1 day undefined hours

There are no sourcemaps with the release container image but I did find the raw react code that renders it and the object it's using to render the time is:

```javascript
{ days: 1, minutes: 41, seconds: 11 }
```

I think it is the [`makeDurationString()`](https://github.com/owncast/owncast/blob/b583fa67e1fed697a81547960cf69e23336d4699/web/components/ui/Statusbar/Statusbar.tsx#L22) function.

After 25 hours [`intervalToDuration()`](https://github.com/date-fns/date-fns/blob/fa8046575c30cd255c41a38eab88701159013680/src/intervalToDuration/index.ts#L33) starts returning the hours again and the web page shows:

> Live for 1 day 1 hour

**Comment by gabek** [comment]
Thanks for reporting this. We should probably just use `date-fns` to calculate and format the diff.

**Comment by mahmed2000** [comment]
Commenting to be assigned https://github.com/owncast/owncast/pull/3729#issuecomment-2092076541
