### ISSUE TITLE
Documentation broken link: Internal link: /content/docs/website

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3736]
# Broken link found in Owncast documentation

First, **please verify that this link or asset is actually broken** by testing the correct page that is in production at https://owncast.online. Then you can fix or remove the broken link Internal link: /content/docs/website from [content/docs/_index.md](https://github.com/owncast/owncast.github.io/tree/master/content/docs/_index.md).

However, this is a link internal to the site. So make sure you understand how the site is organized using [Hugo](https://gohugo.io/content-management/organization/), our [static site generator](https://jamstack.org/glossary/ssg/).

You can find the Owncast documentation site repository at https://github.com/owncast/owncast.github.io, and that is where you would make any fixes to broken links, or documentation in general. Thank you for helping improve our documentation!

[Open documentation repository in editor](https://github.dev/owncast/owncast.github.io/tree/master/content/docs/_index.md)

Source file: https://github.com/owncast/owncast.github.io/tree/master/content/docs/_index.md
        
- Failed: Cannot find file

**Comment by vvu11** [comment]
Hi I would like to work on this issue, please assign to me

**Comment by vvu11** [comment]
actually, it seems as though the links are all working on the website. It does show an error on github when I attempted to click on them on content/docs/_index.md

**Comment by gabek** [comment]
Thanks for looking! This process is automated and opens these when a check fails, so it's always important to check it first. Thanks for doing so!
