### ISSUE TITLE
While trying to authenticate from desktop after doing so on mobile

### ISSUE THREAD

**Issue by aral** [owncast/owncast#3741]
### Share your bug report, feature request, or comment.

Wouldn’t let me issue another authentication request saying one was already pending.

When I used the same code as before, got this error.

![image](https://github.com/owncast/owncast/assets/41798/7d5b0be8-033a-442f-a11a-9d4a85be6ba3)

**Comment by gabek** [comment]
Well that's not great, I haven't seen that one before. If you can think of any way to reproduce this, that would be really helpful. I'm also curious if this fixes itself when the "pending" request expires. But if you never requested the first request in the first place, I'm confused what it's referring to.
