### ISSUE TITLE
Large gap in sentence in modal on Mobile

### ISSUE THREAD

**Issue by germainelee** [owncast/owncast#3748]
### Share your bug report, feature request, or comment.

When Browser Notifications modal pops up in mobile, there is a large gap between "Learn more" and "about Owncast browser notifications". 

The sentence should not a huge gap like in the desktop view.

![Screenshot_20240529_002403_Chrome](https://github.com/owncast/owncast/assets/118464031/5428be89-45a6-4c06-87d9-f63cb3dffd17)

**Comment by bruno-keiko** [comment]
I want to take this issue!

**Comment by gabek** [comment]
@begench-g Thanks so much! Let me know if you have any questions :)

**Comment by germainelee** [comment]
Closing, as pull request is merged.
