### ISSUE TITLE
Chat - Long Username is clipped when chat is narrow

### ISSUE THREAD

**Issue by germainelee** [owncast/owncast#3749]
## Current behaviour:
The username, which does not have any space in between, will be clipped when I resize the chatbox width.

This is the full username, "truesuperheroeswaerkiltsnocape"
![image](https://github.com/owncast/owncast/assets/118464031/38689d6c-f321-4ae1-9143-c1a4498a02ad)

## Steps to replicate:
1. Change username to truesuperheroeswaerkiltsnocape
2. Make chatbox to be narrow with drag handle at the bottom left corner
3. Observe the characters of the username is "missing" (see image below)

![image](https://github.com/owncast/owncast/assets/118464031/dba96fee-41c0-48f4-97a2-09410502478d)
![image](https://github.com/user-attachments/assets/fa367002-ac03-4a5c-8142-a9a25c11a69e)

## Expected behaviour:
When chatbox reaches its min width, long usernames should be truncated by showing 18 characters and adding the ellipsis (…) behind. Don't wrap the ellipsis to another line so that they are kept to 1 line.
![image](https://github.com/user-attachments/assets/9d5ee7b3-91e2-4ea4-a556-306490b57cf9)

**Comment by gabek** [comment]
That top example looks like an extremely narrow width, given the text box can't even render properly. I think in this case, the username should truncate instead of wrap. Otherwise, it could wrap to multiple lines in such a very narrow space, and use up half the viewport with just a long username.

**Comment by germainelee** [comment]
That is a very good point. Let's go with truncated username as the solution

**Comment by s-vamshi** [comment]
Hey @gabek @germainelee I would like to work on this issue, can you please assign this to me?

**Comment by gabek** [comment]
Of course, thank you @s-vamshi!

**Comment by s-vamshi** [comment]
hey @gabek , created pr please review it in your free time and let me know if I have any inputs
