### ISSUE TITLE
Browser Notifications Modal Message is incorrect on browser

### ISSUE THREAD

**Issue by germainelee** [owncast/owncast#3752]
### Share your bug report, feature request, or comment.

When I choose Block in browser notification settings, it tells me that Notifications are enabled. This shouldn't be the case and it should say that notifications are blocked.

**Steps to replicate:**

1. Visit a stream that has Follow button such as [https://owncast.funcube.space/](https://owncast.funcube.space/)
2. Click Follow button
3. Click Allow in the "Browser Notifications" modal
4. When prompted by browser, choose **Block**
![image](https://github.com/owncast/owncast/assets/118464031/57c0cbf1-b4dc-41f1-9b02-c8a8617bf2e4)
5. Success message is shown
![image](https://github.com/owncast/owncast/assets/118464031/afafedbf-05d8-4150-9227-7e396050e5ea)

**Expected behavior:**
Sentence should be different, something along the lines of-

**Notifications are blocked on your device**
To enable push notifications from <stream.url> access your browser permissions for this site and turn on notifications. Then, reload this page to apply your updated settings on this site. 

![image](https://github.com/owncast/owncast/assets/118464031/d29efb0c-88fd-43ad-b364-8c2d831072e0)

**Comment by gabek** [comment]
@germainelee Thanks for discovering this!
