### ISSUE TITLE
A Link broken at Owncast docs page

### ISSUE THREAD

**Issue by germainelee** [owncast/owncast#3768]
### Share your bug report, feature request, or comment.
Navigate to Owncast docs > Broadcasting Software > Compatible hardware. Then, Clicking on TriCaster Mini at https://owncast.online/docs/broadcasting/hardware/ brings me to 403 Forbidden screen:
![image](https://github.com/owncast/owncast/assets/118464031/f9ed5016-d94a-4b78-8623-ce1214eb73eb)

**Comment by mahmed2000** [comment]
Newtek seems to have been acquired by Vizrt. This should be the new correct link: https://www.vizrt.com/tricaster/mini/ or https://www.vizrt.com/products/tricaster/mini-qsg/

<blockquote><img src="https://www.vizrt.com/wp-content/uploads/2023/10/TriCaster-icon.png" width="48" align="right"><div><img src="https://www.vizrt.com/wp-content/uploads/2023/05/favicon-32x32-1.png?w=32" height="14"> Vizrt</div><div><strong><a href="https://www.vizrt.com/products/tricaster/mini-qsg/">TriCaster® Mini-Quick Start Guide</a></strong></div><div>Vizrt TriCaster® Mini Quick Start Guide</div></blockquote>
<blockquote><img src="https://www.vizrt.com/wp-content/uploads/2023/10/TriCaster-icon.png" width="48" align="right"><div><img src="https://www.vizrt.com/wp-content/uploads/2023/05/favicon-32x32-1.png?w=32" height="14"> Vizrt</div><div><strong><a href="https://www.vizrt.com/products/tricaster/mini-qsg/">TriCaster® Mini-Quick Start Guide</a></strong></div><div>Vizrt TriCaster® Mini Quick Start Guide</div></blockquote>
