### ISSUE TITLE
Owncast Docs: APIs & Access Tokens Enpoint Column points to Page not found

### ISSUE THREAD

**Issue by germainelee** [owncast/owncast#3769]
### Share your bug report, feature request, or comment.

On [APIs & Access Tokens page](https://owncast.online/thirdparty/apis/), clicking on the content in Endpoint column brings me to page not found:
![image](https://github.com/owncast/owncast/assets/118464031/86c76be9-b9b9-45fe-a55e-9a52455ca782)

**Comment by gabek** [comment]
Fixed.

**Comment by germainelee** [comment]
"Standard chat message" and "system message to client" refreshed the page APIs & Access Tokens page. should it open a link like the others?

**Comment by gabek** [comment]
That's probably the case. If those links aren't working, then it's likely they never worked, since it doesn't sound like a content problem.
