### ISSUE TITLE
Research and possibly implement a collaboration platform

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3779]
### Share your bug report, feature request, or comment.

See https://github.com/owncast/owncast/issues/150 for the initial discussion.

**Comment by germainelee** [comment]
You are more resourceful than me OTL

> I think GitBook would require people to check in documents to a repository to deploy them just like we do for the web site, so that's pretty high levels of friction if somebody wanted to write something. So I'd rather not go the static site generator route.

I agree the PRs for documentation in [Gitbook](https://www.gitbook.com/solutions/git-sync) is a little overkill. We can set up to automatically accept the pull requests, though it sounds a bit dangerous. One idea I had in mind was that the PR will automatically be accepted if you're the author of that page. But not sure if it's possible and makes sense.

**Comment by gabek** [comment]
Also, nobody would do it. If I asked "hey could you add that bit to the X doc" it would absolutely not happen for a casual contributor. It needs to be super easy and very low friction.

**Comment by gabek** [comment]
I wouldn't be opposed to actually paying for something, either. But it gets really difficult when you don't know how many people need accounts. For example, [Affine](https://affine.pro/pricing) is only $6.75 a month for 10 team members. But if we create accounts for everyone who contributes, those 10 will go fast. And then how do you decide whom to delete? There's no way to know if a contributor is coming back or not.

All the other ones, it seems, you pay per user, and that would be impossible for us.

**Comment by germainelee** [comment]
> https://standardnotes.com is another option.

_Originally posted by @gabek in https://github.com/owncast/owncast/issues/150#issuecomment-2159506170_

You'll need to pay to create table / Spreadsheet. Not sure if it is worth the price if 2-5 members are using it frequently.

<blockquote><img src="https://assets.standardnotes.com/media/SN-Icon-500.png" width="48" align="right"><div><strong><a href="https://standardnotes.com/">Standard Notes | End-To-End Encrypted Notes App</a></strong></div><div>Standard Notes helps you gain control in a world that often feels out of control. Protect your life's work with end-to-end encryption, advanced security measures, and unmatched privacy controls.</div></blockquote>

**Comment by gabek** [comment]
For all of these I'm talking about self-hosting. https://github.com/standardnotes/server

I only mentioned paying above to state that if there was an appropriate option, I wouldn't be against it. But there isn't any.

<blockquote><img src="https://opengraph.githubassets.com/c4523fb28a2b7ec904cd2bc0dde468de4ce0cfd813a94d714906ad00c043daad/standardnotes/server" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/standardnotes/server">GitHub - standardnotes/server: Server ecosystem for Standard Notes; fully self-hostable.</a></strong></div><div>Server ecosystem for Standard Notes; fully self-hostable. - standardnotes/server</div></blockquote>

**Comment by germainelee** [comment]
Based on reddit discussions, it seems only plaintext files are supported and require a subscription to the remaining majority of features. 

I'm probably not on the right track, There's [Joplin](https://joplinapp.org/) and [Trilium](https://github.com/zadam/trilium?tab=readme-ov-file) as alternatives. KIV [Anytype](https://doc.anytype.io/anytype-docs/intro/get-the-app) as you can self-host your own network, but all editors must install the app because no browser version of the app.

**Comment by gabek** [comment]
Trilium is single-user only.
Joplin doesn't have a self-hosted hosted option.
And yeah, anything that requires anybody to install an application won't work.

**Comment by germainelee** [comment]
> The downside of self-hosting any of these is it's one more thing the project has to maintain. Upgrades, security patches, random outages, etc etc. That's not exactly something I want to be doing. But aside from the GitHub wiki, there are really no other options.

I'm confused about your preference. Do you prefer self-hosting or not?
<hr>
<a href="https://coda.io/pricing">Coda</a> looks interesting. Not sure if it is considered as a high friction point for people as they would need to create an account using their personal Google / Microsoft to edit a page.

Looking at the [pricing modal](https://coda.io/pricing), you can be the Doc Maker and everyone else (by invitation) is the editor. So how I see the process work if we're using the Free plan is: 

1. they'd have to ask you to create a blank page -> wait for you to create a page -> they edit the page
2. they document in whatever software -> pass you the file / url -> you create the page -> copy and paste the content

**Comment by gabek** [comment]
I'm open to absolutely all options. But self-hosting is, so far, the only way for us to move forward due to how companies price their products. But no, I don't *want* to self-host, but I'll *have* to. I'm certainly not looking for more things to manage.

Google and Microsoft accounts would be a problem, as many people don't have them. I fall into that category. That's why Outline won't work as well, it requires third-party authentication.

I'm beginning to think there might not be any suitable solution for a project like ours that needs to be super flexible on adding users and super easy for new users to use. I guess that's why most open source projects just use wikis.

**Comment by gabek** [comment]
I put out a call to try to crowdsource some answers. https://social.gabekangas.com/notice/Aip9cjJ05fDmlXfP96

<blockquote><img src="https://social.gabekangas.com/media/fc155e4c9588b36e1c131067264a73c4db532514300005c23092c283eb1014b0.blob" width="48" align="right"><div><strong><a href="https://social.gabekangas.com/notice/Aip9cjJ05fDmlXfP96">Gabe Kangas (@gabek@social.gabekangas.com)</a></strong></div><div>I know there’s literally 8.2 billion answers to this question, but maybe you can point me at answers you’ve used or seen and not at just things you’ve heard of.  Owncast has never had a (good) cent...</div></blockquote>

**Comment by germainelee** [comment]
And I'll try asking in reddit community if moderators don't auto delete my post.

**Comment by germainelee** [comment]
https://huly.io/

I know it has a lot of fancy Project Management stuff, but waddya think? 
Check out Huly Github in regards to [self-hosting](https://github.com/hcengineering/platform)

<blockquote><img src="/_astro/project-management.MMl0i4lf_Z1W7Xxo.webp" width="48" align="right"><div><strong><a href="https://huly.io/">Open Source All-in-One Project Management Platform</a></strong></div><div>Huly by Hardcore Engineering Inc</div></blockquote>

**Comment by gabek** [comment]
I wonder if there's a way to turn off all the project management features. Probably not, since it is project management software, after all. The documents feature does look to be what we need, but it looks like that's not really what it's built for.

**Comment by germainelee** [comment]
Looks like we can just toggle the others off! Even if setting it to not visible is good enough 🤩
![image](https://github.com/owncast/owncast/assets/118464031/cb6fa091-db7f-4feb-95d8-b0df7026647c)

**Comment by gabek** [comment]
Very cool!  That looks great. I'll look into what it takes to run it.

**Comment by germainelee** [comment]
Stumbled across this list and putting here in case above doesn't work out.
https://github.com/awesome-selfhosted/awesome-selfhosted?tab=readme-ov-file#wikis

The list has more options to choose from compared to [https://selfh.st/apps/?tag=Wiki](https://selfh.st/apps/?tag=Wiki)

<blockquote><img src="https://opengraph.githubassets.com/a0c4c122d9fd0efe596b0f13ed34e08dd03d34266a078825553951925a7853de/awesome-selfhosted/awesome-selfhosted" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/awesome-selfhosted/awesome-selfhosted">GitHub - awesome-selfhosted/awesome-selfhosted: A list of Free Software network services and web applications which can be hosted on your own servers</a></strong></div><div>A list of Free Software network services and web applications which can be hosted on your own servers - awesome-selfhosted/awesome-selfhosted</div></blockquote>

**Comment by germainelee** [comment]
> TODO: Link to a feature document with all of the details for this feature.

_Originally posted by @gabek in https://github.com/owncast/owncast/issues/2871#issue-1639975069_


Moving forward, I agree that it would be good practice to document information for upcoming product features.

**Comment by gabek** [comment]
Huly has a free hosted version, I don't know if it's just as a demo, or we're allowed to use it going forward.
But at the very least, for testing, I created an Owncast workspace to do testing, anybody can join: https://huly.app/login/join?inviteId=666a2354f71af4631c26e145

<blockquote><img src="/huly/favicon.ico" width="48" align="right"><div><strong><a href="https://huly.app/login/join?inviteId=666a2354f71af4631c26e145">Huly</a></strong></div></blockquote>

**Comment by germainelee** [comment]
You may ask the developers questions on [slack](https://join.slack.com/t/hulycommunity/shared_invite/zt-29kl7zmwz-2b3RRVTiWhhtAwzHjBm3Wg). I'm in there

**Comment by gabek** [comment]
As an aside, just in case, I did reach out to Notion sales and explained our situation, asking if there was a way to have a plan that would meet our requirements. I have not heard back.

**Comment by germainelee** [comment]
Huly is working on their pricing plan. Will we be affected? 
 https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjZkOWQxZTMwMzYyYTY0OWM3OGNkOTciLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIiwicHJvZHVjdElkIjoiIn0.EGchL-sx7_GXWRLKfjzmcCYWe6s-ijMFzT8dhKFa_iQ

<blockquote><img src="/huly/favicon.ico" width="48" align="right"><div><strong><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjZkOWQxZTMwMzYyYTY0OWM3OGNkOTciLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIiwicHJvZHVjdElkIjoiIn0.EGchL-sx7_GXWRLKfjzmcCYWe6s-ijMFzT8dhKFa_iQ">Huly</a></strong></div></blockquote>

**Comment by gabek** [comment]
@germainelee It seems like we might be able to use a Notion free plan and publish documents publicly for people to read, and allow a limited number of people to edit. I sent you an invite to the Owncast workspace in Notion. We can compare this approach to what is available to us in Huly.

The public page for reading these documents then is available as:
https://owncast.notion.site/6198db58e1d74b51a1e8175abb566b82?v=43472b9654c04bf291cf19932a88a0a3

<blockquote><img src="https://www.notion.so/images/meta/default.png" width="48" align="right"><div>Notion</div><div><strong><a href="https://www.notion.so">Notion – The all-in-one workspace for your notes, tasks, wikis, and databases.</a></strong></div><div>A new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team</div></blockquote>

**Comment by gabek** [comment]
I guess we can close this since it looks like we can move forward with Notion.

**Comment by gabek** [comment]
Ugh. I'm contacting them again to see if there's any way I can pay them. I'm really stuck. I don't really know how to move forward.

![image](https://github.com/owncast/owncast/assets/414923/3da4a8dd-10a6-489f-a4e1-80d56d6722ed)

**Comment by gabek** [comment]
Here's the response from Notion. I guess I'll have to upgrade my personal account to a `Plus` account. And then if somebody wants to contribute by writing within the Owncast Notion workspace:

1. I need to add them as a guest.
2. I need to manually provide them with access to the page they would like to work on.
3. Unless they're going to work broadly on more things, then I'll have to manually add them, individually, to each page in the workspace.
4. If they want to create a new document, then they'll have to ask me to create it first, and then I'll have to give them access to it.

![image](https://github.com/owncast/owncast/assets/414923/e2079ff4-58a8-4ee3-a39e-27208f43456d)

**Comment by germainelee** [comment]
Looks like it to primarily use the Unlimited blocks.

![image](https://github.com/owncast/owncast/assets/118464031/c2e59d78-83f6-4c2a-bdf2-078e3968ea3e)
[Image Source](https://www.notion.so/pricing)

Not so good solution: remove members who have not contributed for a long time if you wanna stick to free plan.

**Comment by gabek** [comment]
Yes, it's the blocks that are the problem. We've almost run out. Removing members won't help there unless, like I mentioned, everyone gets removed and everyone gets added as guests only.

**Comment by germainelee** [comment]
We can try out guests. I don't mind being "guest" and it also protects those pages that's not supposed to be edited.
