### ISSUE TITLE
Following an Owncast server from another local Fediverse instance

### ISSUE THREAD

**Issue by genius6** [owncast/owncast#3783]
### Share your bug report, feature request, or comment.

Hello,

I have just installed an Owncast server, and loving it so far! While I was testing the various options, I did encounter an error and I am wondering if it's the desired result or if I messed up my config.

Currently, I have on the same server a Friendica instance and an Owncast instance. Both are using a different address (Friendica is "example.com", and Owncast is "owncast.example.com"). When I try to use the "Follow" button on the Owncast page using my Friendica account, I receive an error stating that Owncast was "unable to use provided host as a valid fediverse server". A similar error happens when I try to Authenticate through FediAuth in the chat with my Friendica account, stating "Could not send code to fediverse: unable to get webfinger links when sending private message: unable to use provided host as a valid fediverse server".

I did try to dig up the cause, but since I am definitely not an expert, please take the rest of this post with a grain of salt.

Following the error message, in both cases I got to the "webfinger.go" file, where a check is done to verify if the hostname of the targeted server is internal using the IsHostnameInternal() function. If it is, the function returns an error. However, I am guessing this could be why I can't follow my Owncast instance using an account located on the same server, although on a different instance? Is there any setup I should have done to avoid this error in the first place?

Thank you in advance for your help!
![Screen_Follow](https://github.com/owncast/owncast/assets/18177531/ac35ae72-90c1-4378-bb26-8a6615fa9cf8)
![Screen_Fediauth](https://github.com/owncast/owncast/assets/18177531/94138d58-3278-4a5b-8dfe-60915a4b24f3)

**Comment by gabek** [comment]
It looks like it's having a hard time using your Fediverse server to look up your user via WebFinger. There might be something specific to your server that Owncast doesn't like. You can try looking up your user on https://webfinger.net/ and see what it returns.

<blockquote><img src="/images/WebFinger-16x16.ico" width="48" align="right"><div><strong><a href="https://webfinger.net/">WebFinger</a></strong></div></blockquote>

**Comment by genius6** [comment]
Thanks for the tip!

I tried running my Friendica user & a random Friendica user from another instance I don't own, simply to make sure that my setup was Okay, and both queries returned with the same JSON data structure (although with different values, of course). No errors as well.

Out of curiosity I also ran my Owncast user, and it didn't get any errors as well, with the same JSON structure than another Owncast v0.1.3 server's user I looked at... So I'm not sure what would block my Owncast instance to see my Friendica instance...

**Comment by mahmed2000** [comment]
> Following the error message, in both cases I got to the "webfinger.go" file, where a check is done to verify if the hostname of the targeted server is internal using the IsHostnameInternal() function. If it is, the function returns an error. However, I am guessing this could be why I can't follow my Owncast instance using an account located on the same server, although on a different instance? Is there any setup I should have done to avoid this error in the first place?

That seems right. yeah. The only way for that exact error string to show up is if `IsHostnameInternal` returns true. Which only happens if the address from a DNS lookup matches non-public ips. Which only happens when there's a custom rule in /etc/hosts or something similar in the DNS resolution.

Does a DNS lookup on your server with nslookup/dig/resolvectl etc return a loopback or private address?

**Comment by genius6** [comment]
> That seems right. yeah. The only way for that exact error string to show up is if `IsHostnameInternal` returns true. Which only happens if the address from a DNS lookup matches non-public ips. Which only happens when there's a custom rule in /etc/hosts or something similar in the DNS resolution.

You were right! I indeed had the server address in /etc/hosts. Everything worked back to normal once I removed it. Thanks a lot and sorry for anyone who lost time on my issue! Ah Ah
