### ISSUE TITLE
Admin video passthrough banner: Low contrast between the text color and the background

### ISSUE THREAD

**Issue by germainelee** [owncast/owncast#3798]
### Share your bug report, feature request, or comment.

I have poor eyesight and the red text on grey background causes eye strain as I try to decipher the words. It seems like an important note, but the low-contrast element decrease legibility. See image below.

### Steps to replicate:

1. Log in to admin
2. Navigate to configuration > Video
3. Add a new variant in stream output
4. Toggle "Use Video Passthrough?" to ON
5. Click "Yes" when prompted
6. Scroll up and observe the note

![image](https://github.com/owncast/owncast/assets/118464031/2fe9008d-1d6b-4f90-9e95-c937b951730b)

### Expected behvior:
In order to meet the guidelines at Level AAA, element should be White text `color: var(--theme-color-palette-4);` on dark background using theme color `background-color: var(--theme-color-palette-1)`, shown image below

![image](https://github.com/owncast/owncast/assets/118464031/c28b8d67-95fe-490a-a24a-a69bf1c749d8)

**Comment by gabek** [comment]
I think it was originally red to catch people's attention, since video passthrough is a place where people get tripped up.

**Comment by germainelee** [comment]
Then, we'll maintain the red and use a darker background.

**Comment by gabek** [comment]
Oh the red isn't required, whatever is best. I'm not particular about it.
