### ISSUE TITLE
Admin Follower Sorting shows no data

### ISSUE THREAD

**Issue by germainelee** [owncast/owncast#3799]
## Steps to replicate

1. log in as admin
2. navigate to followers
3. Notice that there are N number of followers
4. Click on "Added" table header to cycle the Sort
5. Observe the table returns no data for all sorting

![image](https://github.com/owncast/owncast/assets/118464031/8d821781-e9d3-4aa8-82e9-9491e01005ec)

## Expected outcome
Sort followers by date added either ascending / descending accordingly. Default is sorted in descending order

**Comment by dev265545** [comment]
I can take up this issue

**Comment by gabek** [comment]
Thanks so much, @dev265545!

**Comment by Alcamara** [comment]
Hey @gabek is @dev265545 still working on this issue? if not, I would like to take this issue.

**Comment by gabek** [comment]
HI there @Alcamara! I'm guessing not, so have at it! Let me know if you have any questions :)

**Comment by SufyaanKhateeb** [comment]
@Alcamara Are you still working on this? I can take this up if you are okay with it.

**Comment by Alcamara** [comment]
Yes, I am

**Comment by Alcamara** [comment]
@SufyaanKhateeb Yes I am

**Comment by mahmed2000** [comment]
Tried to test this a bit. Trying to sort the follower table for some reason kicks off a second request to /api/admin/followers with the offset set to 25. If there's less than 25 total followers, the request returns an empty array so no followers get displayed.

![Image](https://github.com/user-attachments/assets/4179acfd-1db0-4b57-b6ee-17c62bbdd934)

**Comment by gabek** [comment]
@Alcamara Are you still looking at this?
