### ISSUE TITLE
Admin checkbox item selected has poor legibility

### ISSUE THREAD

**Issue by germainelee** [owncast/owncast#3800]
## Steps to replicate
1. log in to admin
2. navigate to Chat & Users > Messages
3. Click on Filter icon
4. Select any checkbox
5. Move mouse away OR click Ok and reopen filter
6. Observe that black text on purple background has poor legibility
![image](https://github.com/owncast/owncast/assets/118464031/092bf229-3de3-4be5-8ed4-496ba85a5fc2)
![image](https://github.com/owncast/owncast/assets/118464031/c4d80caf-3432-4f64-a350-dd09953c0489)

## Expected outcome
Selected item should have a light purple background `background-color: #f5f0ff;` in pages with checkboxes such as the following pages:

- Chat & Users > Messages
- Utilities > Logs

![image](https://github.com/owncast/owncast/assets/118464031/dd2fae9c-d551-4034-9d3b-ddf5f0c772a4)

**Comment by joras-droid** [comment]
assign me please anyone :)

**Comment by gabek** [comment]
Hi there, thanks for wanting to contribute! Let me know if you have any questions or issues getting the project up and running for development.

**Comment by joras-droid** [comment]
thank you for your response.

**Comment by joras-droid** [comment]
is it okay?

https://github.com/owncast/owncast/assets/65585311/7c0f5ab4-4b25-4360-832b-9956740d9af9

please confirm it.

**Comment by germainelee** [comment]
@Nirajan1-droid Looks great. 

Can you share how it looks like in Utilities > Logs filter too? Thanks so much.

Currently it looks like this:
![image](https://github.com/owncast/owncast/assets/118464031/7f037626-fab2-46fd-adca-8007896eee03)

**Comment by joras-droid** [comment]
https://github.com/owncast/owncast/assets/65585311/c7ae74d8-14f1-49bf-a691-067070c5397c

yup here it is

**Comment by joras-droid** [comment]
is it ready for merge?

**Comment by joras-droid** [comment]
the problem with linting issue have appeared.
reason: it is expected declaration or statement in .css files.
solution: we should ignore .css files as it doesnot have declaration or statements like .jsx or .tsx files.
am i suppose to add this in this commit or, should i have to open new issue?
>web>.eslintrc.js:
ignorePatterns: ['!./storybook/**',"**/*.css","**/*.scss"],
it solves the problem.
problem screenshot:
![image](https://github.com/owncast/owncast/assets/65585311/9f1bdb26-bdb0-40bb-a1d1-8ec058bbe09e)
![image](https://github.com/owncast/owncast/assets/65585311/63fa973c-da6e-47f7-bac3-15c65c898b3b)

**Comment by joras-droid** [comment]
@germainelee @gabek ppease respond to my above message

**Comment by germainelee** [comment]
the color is also used as background in alert box.
![image](https://github.com/owncast/owncast/assets/118464031/5b92d6a7-9f9c-418e-ad1a-a3cbce6b78f2)

![image](https://github.com/owncast/owncast/assets/118464031/a1b790eb-3e88-4cb6-a358-d1a3fa61dde1)

so im not sure why it won't allow for selected. Maybe @gabek can advise.

**Comment by gabek** [comment]
> the problem with linting issue have appeared.

I'm not sure why it's appeared after having no problems until now. Please give me some time to fix it. We do want to lint css files, so we can't just turn it off completely for them.

**Comment by joras-droid** [comment]
hmm ok.
let me know after finding the problem.

**Comment by joras-droid** [comment]
> the color is also used as background in alert box. ![image](https://private-user-images.githubusercontent.com/118464031/347900860-5b92d6a7-9f9c-418e-ad1a-a3cbce6b78f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NjgwMTAsIm5iZiI6MTcyMDg2NzcxMCwicGF0aCI6Ii8xMTg0NjQwMzEvMzQ3OTAwODYwLTViOTJkNmE3LTlmOWMtNDE4ZS1hZDFhLWEzY2JjZTZiNzhmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxM1QxMDQ4MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NDYyZmQ0MWFlNGM0NzUxZmU1YTEzYThiOTRiMDlmY2FjMzJjNzBkNjIwZDcxYzQ5YzVmODU2MGRkZGUwZDQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nrBrLVtfRJKglbNOgv3Oabv8l1TPJ3Iih8S6QLW18DE)
> 
> ![image](https://private-user-images.githubusercontent.com/118464031/347900781-a1b790eb-3e88-4cb6-a358-d1a3fa61dde1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NjgwMTAsIm5iZiI6MTcyMDg2NzcxMCwicGF0aCI6Ii8xMTg0NjQwMzEvMzQ3OTAwNzgxLWExYjc5MGViLTNlODgtNGNiNi1hMzU4LWQxYTNmYTYxZGRlMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxM1QxMDQ4MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMDg4N2Q4ODljMTFlZWE2NzY4OGZjZDgwMGE0YWI3MTY0Mzk1Y2FiOWMwMWNjMzY2MWRmNzU5MzBiNDdjNjA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.92GWKUyJ3A6qSzkgDi8iACtSaikFHWXeXAg4wPfGxSs)
> 
> so im not sure why it won't allow for selected. Maybe @gabek can advise.

@germainelee i have rechecked it but, the color of alert box was white before.
it didn't changed due to my pull request.
do i have to change the color of the alert box as well?
if that's so, please provide me which color to use for the alert box

**Comment by germainelee** [comment]
@Nirajan1-droid there's no need to change the colour of alert box.

Thank you for your efforts in this issue.
