### ISSUE TITLE
Filtering Admin Logs shows no data

### ISSUE THREAD

**Issue by germainelee** [owncast/owncast#3813]
### Share your bug report, feature request, or comment.

Only works when I filter 'info' level, does not work when I filter by 'Error'. Unable to test the filter by 'Warning'. Have not tried filtering with combinations.
![image](https://github.com/owncast/owncast/assets/118464031/282fe643-3029-42b2-a636-30395bda0b81)

## Steps to replicate

1. log in as admin
2. navigate to Utilities -> Logs
3. Notice that the table is not empty
![image](https://github.com/owncast/owncast/assets/118464031/5dc76bbf-219a-4d5c-9404-cad367bfd6f7)
4. Click on Filter icon and select 'Error'
5. Observe the table returns no data
![image](https://github.com/owncast/owncast/assets/118464031/ea356ac9-bb7b-464d-ac35-52861a0c9d7d)

## Expected outcome
Returns data according to filtered value.
<hr>
Ask @gabek for advice regarding development-related questions.

**Comment by mahmed2000** [comment]
https://github.com/owncast/owncast/blob/b35b139fbca2039008c2ee93e9442bba0addd6df/web/components/admin/LogTable.tsx#L45-L56

Its a typo on L56. The json response has `error` as the level. The table checks for a value of `Error`. Warnings filter correctly as is.

**Comment by germainelee** [comment]
thanks to OP (self) for finding this bug in the first place.

**Comment by gabek** [comment]
You are excellent at finding bugs!
