### ISSUE TITLE
Update the label of stupid 𝕏 to X 🙄

### ISSUE THREAD

**Issue by germainelee** [owncast/owncast#3817]
### Share your bug report, feature request, or comment.

Continuation from #3427 

I like that the label is still Twitter and not X. But the change has to happen at some point.
![image](https://github.com/owncast/owncast/assets/118464031/c43a9884-1b58-4845-95ce-0af15c2f2487)

## Expected Outcome
![image](https://github.com/owncast/owncast/assets/118464031/83754bf7-7a88-4810-a0a3-dc1ad395d19e)

**Comment by unclebinary1001** [comment]
can i take this up?

**Comment by gabek** [comment]
Of course, thank you @unclebinary1001!

**Comment by unclebinary1001** [comment]
i will have an update on this next week. i have to work on my computer this weekend.

**Comment by unclebinary1001** [comment]
then, do we want to change references of Twitter to X? like twitter.com to x.com, twitter.svg to x.svg?

**Comment by gabek** [comment]
I don't remember, but there might be a couple places that might have to be touched to change the image name. But might as well change it, thanks!
