### ISSUE TITLE
Admin Configuration small typo

### ISSUE THREAD

**Issue by germainelee** [owncast/owncast#3827]
### Share your bug report, feature request, or comment.

In the admin Configuration > General, "to" word is typed twice.

## Current output
Observe the Disable search engine indexing field tip has duplicate "to" (as shown highlighted in image below)
![image](https://github.com/owncast/owncast/assets/118464031/477ee877-a15d-48a9-9434-5180fd604c0e)

## Expected output
Remove additional "to". Change text from: "Turn this ON to to tell search engines not to index this site." -> Turn this ON to tell search engines not to index this site.
![image](https://github.com/owncast/owncast/assets/118464031/d0da3452-9a91-4ee7-8c3a-b0d4549420dd)

**Comment by samwherever** [comment]
Hey, I think can do this! I'll try it. If i need to wait for it to be assigned, i will wait.

**Comment by gabek** [comment]
Awesome, thanks so much @samwherever! Let me know if you have any questions!

**Comment by samwherever** [comment]
alright @gabek, [filed a PR here](https://github.com/owncast/owncast/pull/3835), hopefully this does the trick...

**Comment by germainelee** [comment]
Thank you for taking the initiative to propose an improved sentence and it works well. The sentence can be improved further by removing "not". I propose:
Turn this ON to prevent search engines from indexing this site.

**Comment by samwherever** [comment]
@germainelee Yuh! The only reason I phrased it the way I did is because if I recall correctly, you can _ask_ search engines to not index something, but there is never any guarantee they will respect your wishes.
