### ISSUE TITLE
owncast_instance_active_viewer_count for prometheus doesn't reset to 0 at the end of the stream

### ISSUE THREAD

**Issue by etranger7** [owncast/owncast#3830]
### Share your bug report, feature request, or comment.

Even after the stream goes offline, the value of owncast_instance_active_viewer_count stays stuck at the last value before the stream went offline.

The accurate number not being properly displayed makes it impractical to set alerts.

I doubt this is the expected behavior.

version: 0.1.3

**Comment by gabek** [comment]
As far as I've heard, you're the only person who has used this functionality, so thanks for reporting back on it.

**Comment by etranger7** [comment]
No problem :) Thanks for looking into it. I think it's great that this information can be exposed so that it can be tracked.
