### ISSUE TITLE
Chat - Join/leave messages layout breaks on narrow chat viewports

### ISSUE THREAD

**Issue by germainelee** [owncast/owncast#3842]
## Current behaviour

I noticed that the join/leave messages looks like 2 columns when chat size is at min width. Nothing critical, but strange
![image](https://github.com/user-attachments/assets/c792f6c1-1440-417e-9bd3-9f95329dbc16)

It looks like this on default chat width size
![image](https://github.com/user-attachments/assets/b34f3a78-bf32-4d77-a1e8-01467c865758)

### another example of chat:
default width
![image](https://github.com/user-attachments/assets/563ef123-4beb-4907-8143-489d58deb7b2)

narrow width. notice some characters are not fully visible.
![image](https://github.com/user-attachments/assets/59b82010-818c-4e7e-bc71-d5045ddb6339)

## Expected Result 
- join/leave message for long usernames should flow smoothly like a sentence.
- join/leave message is responsive on narrow chat width 
- Look similar to images below
![Image](https://github.com/user-attachments/assets/387da17c-ffdc-449b-bdf6-79b686d13e4e)
![Image](https://github.com/user-attachments/assets/a70a1003-611f-4a44-8b6e-b43c3c0dc887)

## Proposed Solution
Possible to do it like this for long usernames, shown in image below?
![image](https://github.com/user-attachments/assets/eb2ad4ca-1916-44a0-8528-14c6570e7405)

<hr>

### Notes
Use display name: truesuperheroeswearkiltsnocape

Note to OP: To look at name change notification messages.

### Additional information
Web browser
Owncast v0.1.3

**Comment by nekojanai** [comment]
I'd like to take this on and I'd implement is as follows:
- add `nowrap` to the username and make the following join message wrap

**Comment by gabek** [comment]
@nekojanai Awesome, thank you!
