### ISSUE TITLE
Offline message renders raw html

### ISSUE THREAD

**Issue by popey** [owncast/owncast#3853]
### Share your bug report, feature request, or comment.

In /admin/config/general/ I have set offline message to the following text, no tags, just this raw text.
```text
Sometimes, I step away from the computer.
This may be one of those occasions.

Treasure it.
```

When I'm offline, it renders at https://owncast.popey.com/ as 

```text
Sometimes, I step away from the computer. This may be one of those occasions.

Treasure it.
```

However, at the embed url: https://owncast.popey.com/embed/video it renders like this (with the tags in chevrons).

```text
<p>Sometimes, I step away from the computer. This may be one of those occasions.</p> <p>Treasure it.</p>
```

I don't think the HTML tags should be there.

**Comment by gabek** [comment]
This is fixed in the next release.

**Comment by popey** [comment]
Awesome, thanks!
