### ISSUE TITLE
Elestio logo not loading on Documentation site

### ISSUE THREAD

**Issue by germainelee** [owncast/owncast#3858]
### Share your bug report, feature request, or comment.

On [https://owncast.online/quickstart/providers/](https://owncast.online/quickstart/providers/) page, Elestio logo image path is broken as shown in image below.

Source file: https://github.com/owncast/owncast.github.io/tree/master/content/quickstart/providers.md

![image](https://github.com/user-attachments/assets/cd82da7d-acbe-4104-b5ed-0044ba3b7ee8)

When I change the image source from `src="./elestio/Elestio.png"` to `src="/quickstart/elestio/Elestio.png"`, it appears kinda big compared to the other logos, like this:

![image](https://github.com/user-attachments/assets/51310194-dc40-4098-9b88-8ecb8393b182)

To ensure the logos visually look the same size, would probably need to update the img width too from default `width="50%"` to `width="10%"`
![image](https://github.com/user-attachments/assets/123c9f80-a591-41ab-ad0d-d22d3c903187)

**Comment by gabek** [comment]
I filed #3859 to discuss how to deal with these in general.
