### ISSUE TITLE
Remove broadcast.owncast.online reference from demo page

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3860]
### Discussed in https://github.com/owncast/owncast/discussions/3856

<div type='discussions-op-text'>

<sup>Originally posted by **Iliya5digital** July 29, 2024</sup>
Hi! Your address [broadcast.owncast.online](http://broadcast.owncast.online/) is not working! Please resolve.</div>

**Comment by germainelee** [comment]
I have a couple of questions on what the revised content should be:
- [broadcast.owncast.online](http://broadcast.owncast.online/) is mentioned 3 times in the [page](https://owncast.online/demo/). Can the content in the red box be deleted entirely?
- Since that broadcast server was decommissioned, I'm thinking of revising the following sentence to be changed from "We provide **two** public Owncast servers for you to see how it works. **One for streaming to** and one for just watching." to `We provide a public Owncast server for you to see how it works.`

Let me know what you think.
![image](https://github.com/user-attachments/assets/19070891-58ce-47a0-96ac-869fe36d6329)

**Comment by gabek** [comment]
Yup. All references about having two servers and one of them being the broadcast server, and how to use the broadcast server. Including:

"Read more about..." should be deleted.
"Some limitations..." and all of its bullets should be deleted.

**Comment by germainelee** [comment]
Great! Thanks for clarification!

**Comment by germainelee** [comment]
The page looks kinda empty with broadcast gone. So I'm thinking of putting Directory as people might have found the Demo page via the footer.
![image](https://github.com/user-attachments/assets/6020ef15-685c-41e2-8dc6-85fe89fa5901)

As Directory is a child item of Demo, is it a good idea to introduce it?

![image](https://github.com/user-attachments/assets/73fe13a1-f3e6-486d-8cb2-f6b920f41846)

I'm thinking to reuse the entire chunk of text from "About Directory", starting from "Owncast Directory..." all the way to "Learn more about..."

![image](https://github.com/user-attachments/assets/a27a5b49-55ba-42e7-b879-5f7209d3ccef)

**Comment by gabek** [comment]
Honestly, I don't know if we need the page at all. It's not directly linked to from anywhere obvious. I'm not sure what pages do link to it. And since most of the value was the instructions on how to use the broadcast server, I'm not sure this page has much of a purpose anymore.

**Comment by germainelee** [comment]
Demo page is a good place that helps people explore more about Owncast. It's more of a brief description of what Directory is and showcase the features, which you covered it well for "Watch a test live stream".

**Comment by gabek** [comment]
We already have documentation about the directory. The directory and the demo server aren't connected, so it wouldn't make sense to combine them in a page just to keep the page.

https://owncast.online/docs/directory/

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="https://owncast.online/favicon.png" height="14"> Owncast</div><div><strong><a href="/docs/directory/">The Directory</a></strong></div><div>The Owncast Directory is a centralized list of streams for people to discover.</div></blockquote>

**Comment by germainelee** [comment]
If we remove the page / unlink it, then "About" and "Contact" should not be linked to a page too. So Demo, About, Contact acts as a header only. 

My suggestion: https://owncast.online/about/ will be a an "About us" link in About
https://owncast.online/contact/ and https://owncast.online/demo/ still exists if they can figure out the url. But it wont be explicitly linked in the footer

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="https://owncast.online/favicon.png" height="14"> Owncast</div><div><strong><a href="/about/">About the Owncast Project</a></strong></div><div>Owncast is a free and open source streaming and chat server for use with popular broadcasting software.</div></blockquote>
<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="https://owncast.online/favicon.png" height="14"> Owncast</div><div><strong><a href="/contact/">Contact</a></strong></div><div>Get in touch with the project, get help, or report problems.</div></blockquote>
<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="https://owncast.online/favicon.png" height="14"> Owncast</div><div><strong><a href="/demo/">Owncast Demo Servers</a></strong></div><div>We provide two public Owncast servers for you to see how it works. One for streaming to and one for just watching.
Stream your content to broadcast.owncast.online You can point your own software and content at broadcast.owncast.online to test live streaming with Owncast. Go there and find the current key in the description and chat messages.
Read more about how to configure your software by reading the broadcasting software documentation.</div></blockquote>

**Comment by gabek** [comment]
> If we remove the page / unlink it, then "About" and "Contact" should not be linked to a page too. 

Why? Those pages are valid and have nothing to do with the demo page. I'm not sure why this needs to be complicated. We used to have a need for a page, and now we don't. It doesn't impact other pages.

**Comment by germainelee** [comment]
> Why? Those pages are valid and have nothing to do with the demo page

Consistency. Having a non-clickable Demo footer header of the other clickable ones could lead to confusion and frustration.

I agree About and Contact pages are still valid, hence my proposal (rephrased):
Referring to the footer, 
https://owncast.online/about/ will be an "About us" link under About header.
https://owncast.online/contact/ will be a "Contact us" link under the Contact header. It could be called Support if preferred. 

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="https://owncast.online/favicon.png" height="14"> Owncast</div><div><strong><a href="/about/">About the Owncast Project</a></strong></div><div>Owncast is a free and open source streaming and chat server for use with popular broadcasting software.</div></blockquote>
<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="https://owncast.online/favicon.png" height="14"> Owncast</div><div><strong><a href="/contact/">Contact</a></strong></div><div>Get in touch with the project, get help, or report problems.</div></blockquote>

**Comment by gabek** [comment]
I think I get what you're saying, you're talking about the column called "Demo" in the footer, not the demo page. Let's just remove the column. No big deal. There's already plenty of references to the directory elsewhere on the site, including in the header. But if we really needed it in the footer too, then we can add it to the "About" column.

1. Delete demo page.
2. Remove the "Demo" column from the footer.

That should be it.
