### ISSUE TITLE
Remove Raspberry Pi + OMX references from codec documentation

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3866]
### Share your bug report, feature request, or comment.

It's been left there long enough. Raspberry Pi unfortunately has not supported OMX for some time, so it's time to remove the documentation.

https://owncast.online/docs/codecs/

**Comment by germainelee** [comment]
If I understood correctly, do you mean deleting this entire section?
![image](https://github.com/user-attachments/assets/970b0712-b971-4009-8fc2-455078828cf3)

And delete the highlighted sentence?
![image](https://github.com/user-attachments/assets/2a88092c-cc40-45a3-98d6-9d271a89881f)

**Comment by gabek** [comment]
The entire Raspberry Pi section needs to be removed as well, not just the line about OMX.
