### ISSUE TITLE
Feature request: enable word wrap on the Markdown editor

### ISSUE THREAD

**Issue by fluffy-critter** [owncast/owncast#3870]
### Share your bug report, feature request, or comment.

The Markdown editor used for things like the offline message and the custom page content can be incredibly difficult to work with due to the lack of word wrapping. It would be really nice if I could actually see all of what I'm writing on a longer paragraph.

<img width="986" alt="image" src="https://github.com/user-attachments/assets/469e5c25-af2d-4add-9015-5020ead4aefe">

**Comment by zockicookie** [comment]
Hi, I would love to look at this as my first OS-contribution. Would someone please assign this to me?

**Comment by gabek** [comment]
Sure, thank you @zockicookie!

**Comment by zockicookie** [comment]
Hi, thank you for your trust @gabek. I've submitted a pull request regarding this issue -> #3908
