### ISSUE TITLE
Feature request: Icons for custom social links

### ISSUE THREAD

**Issue by fluffy-critter** [owncast/owncast#3871]
### Share your bug report, feature request, or comment.

It would be really nice if a custom icon could be provided for custom social links, rather than using the default wireframe globe image. For example, a musician might want to put branded links to their own site or to the various streaming and purchase services (Spotify, Mirlo, etc.)

**Comment by gabek** [comment]
If it's helpful at all, you could probably do this with CSS, and swap out these images for anything you like.

**Comment by fluffy-critter** [comment]
That seems like a reasonable way to do it, sure. Is there a way to have owncast host the icon resources themselves or is that something I need to host externally? (No big deal if external hosting is necessary.)

**Comment by gabek** [comment]
Yup! https://owncast.online/docs/custom-assets/

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="https://owncast.online/favicon.png" height="14"> Owncast</div><div><strong><a href="/docs/custom-assets/">Host public assets</a></strong></div><div>Make your own files publicly available.</div></blockquote>

**Comment by fluffy-critter** [comment]
Thanks! Also is there a recommended way to write the CSS selectors? I've been using `img[alt="whatever"]` but that feels a little fragile, but less fragile than using `a[href="whatever"] img` :)

**Comment by gabek** [comment]
I'm honestly not sure! There may not be a great solution, since there doesn't seem to be any classes explicitly set for this. So I think what you came up with might be as good as you'll get. It might be nice to find a better solution for this.
