### ISSUE TITLE
Create automated browser-based testing

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#388]
Suggested by @mattdsteele in https://github.com/owncast/owncast/pull/384#issuecomment-731433136.

We can use the same appraoch as the API-based testing but instead of firing off Jest it can run Puppeteer tests.  This can live in a Github workflow in the same way.

I like Matt's suggestions of some top level things to test:

1. Make sure there's no console errors.
1. Make sure the page renders.
1. Save a screenshot for review.
1. Make sure some obvious components exist.

I could see us also wanting to test the chat because it's one of the few actions a user takes.
1. Send a test chat message.
2. Make sure that chat message is visually rendered.

**Comment by mattdsteele** [comment]
I just ran across this extension, which might be a good starting point for creating the Puppeteer script:

https://chrome.google.com/webstore/detail/headless-recorder/djeegiggegleadkkbgopoonhjimgehda/related

**Comment by gabek** [comment]
A couple weeks ago, just on a whim, I thought I'd see how difficult it would be to get puppeteer working and take a simple screenshot of Owncast.  Was super easy and worked right out of the box!  I know @gingervitis was curious about this too, so she'd probably be interested in that extension.

**Comment by gabek** [comment]
Bumping this up.  As we continue to iterate on chat, having a way to do automated browser tests would make this a lot easier.  If anybody is interested in digging into something new, and owning it, I'd love some help!

https://www.youtube.com/watch?v=lhZOFUY1weo&t=431s

**Comment by gabek** [comment]
With the standalone web and video web pages [breaking and it not being caught](https://github.com/owncast/owncast/pull/1413) I think we've run out of time of not having browser testing.  So I'll be taking the time to focus on this as a priority so this can't happen again.

**Comment by gabek** [comment]
A pass at checking these pages to not be broken have been added.
