### ISSUE TITLE
Documentation broken link: https://www.nvidia.com/drivers

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3883]
# Broken link found in Owncast documentation

First, **please verify that this link or asset is actually broken** by testing the correct page that is in production at https://owncast.online. Then you can fix or remove the broken link https://www.nvidia.com/drivers from [content/docs/codecs.md](https://github.com/owncast/owncast.github.io/tree/master/content/docs/codecs.md).

You can find the Owncast documentation site repository at https://github.com/owncast/owncast.github.io, and that is where you would make any fixes to broken links, or documentation in general. Thank you for helping improve our documentation!

[Open documentation repository in editor](https://github.dev/owncast/owncast.github.io/tree/master/content/docs/codecs.md)

Source file: https://github.com/owncast/owncast.github.io/tree/master/content/docs/codecs.md
        
- Failed: Network error 404

        
- Status: 404

**Comment by TheInvincibleRalph** [comment]
I'd like to work on this, @gabek

**Comment by gabek** [comment]
Thanks so much, @TheInvincibleRalph! Feel free to reach out if you have any questions.

**Comment by TheInvincibleRalph** [comment]
What should I replace the link with, @gabek? That should be the correct page link already in production, I think.

**Comment by gabek** [comment]
https://www.nvidia.com/drivers/ certainly does not work. They must have changed the path to that page to something else. Hopefully you can track it down.

<blockquote><div><strong><a href="https://www.nvidia.com/drivers/">Page Not Found | NVIDIA</a></strong></div><div>Page Not Found</div></blockquote>

**Comment by TheInvincibleRalph** [comment]
On it

**Comment by TheInvincibleRalph** [comment]
Found the new page. I have submitted a PR.
