### ISSUE TITLE
embed metadata works in http, fails in HTTPS

### ISSUE THREAD

**Issue by Rho-9-Official** [owncast/owncast#3889]
### Share your bug report, feature request, or comment.

So, I *am* running it through a TLS tunnel with localxpose set up with my dedicated hosting machine, everything but the metadata works. noncritical, it just means no embeds on discord and other sites, when you post the link.

small bug, no real impact other than the link looks sus af,lol.

**Comment by gabek** [comment]
Could you give an example of what you're reporting? I'm not sure what you mean by embed metadata. When you embed your stream, it's just an iframe. It's also not clear how you're embedding on Discord, so any clarification would be appreciated.

**Comment by Rho-9-Official** [comment]
here's from when I didn't have https set up yet:
<img width="451" alt="image" src="https://github.com/user-attachments/assets/98250703-4ce4-47e7-9d89-0d190a32389a">

VS now
<img width="302" alt="image" src="https://github.com/user-attachments/assets/5e64c22a-5c8f-4fc0-99cf-dbfd3e150de9">
pardon me if I'm not using the correct terms, I don't normally host stuff quite like this, but I'm trying to learn.

**Comment by gabek** [comment]
Oh got it, you're just sharing a link.

So Owncast is a web server that exposes a HTTP service, not HTTPS. However, most people put a reverse proxy in front of their Owncast server to support SSL.

This means if you're seeing some kind of difference between HTTP and HTTPS, it's likely not an issue with Owncast because Owncast does not support HTTPS.

Perhaps your proxy is blocking these requests or there's some kind of routing rule? I'm just throwing out ideas, however.

If you can point to an issue with Owncast in this scenario, I'd be happy to dig deeper. But if it's working with HTTP, then Owncast is working.

**Comment by Rho-9-Official** [comment]
> Oh got it, you're just sharing a link.
> 
> So Owncast is a web server that exposes a HTTP service, not HTTPS. However, most people put a reverse proxy in front of their Owncast server to support SSL.
> 
> This means if you're seeing some kind of difference between HTTP and HTTPS, it's likely not an issue with Owncast because Owncast does not support HTTPS.
> 
> Perhaps your proxy is blocking these requests or there's some kind of routing rule? I'm just throwing out ideas, however.
> 
> If you can point to an issue with Owncast in this scenario, I'd be happy to dig deeper. But if it's working with HTTP, then Owncast is working.

hmm, fair, I am using an nginx reverse proxy, and honestly, given my lack of nginx experience means I am 100% doing something wrong. Perhapse, since this is honestly the only thing not working, I know someone who's interested in trying to maybe get owncast fully on HTTPS, and if things go well, we might look into figuring it out the right way, and maybe try making a setup script.

But for now, HTTPS works great, all of the actually important things seem to be working, and now, I get to see how much abuse an old HP Stream laptop with a dual core pentium can handle, and learn a bit more about Ubuntu systems.

**Comment by gabek** [comment]
One thing to try is to visit the opengraph share debugger, and seeing what comes up for your URL. For example: 

https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fwatch.owncast.online

<blockquote><img src="https://static.xx.fbcdn.net/rsrc.php/v3/y1/r/xGN4CvUH3Nz.png" width="48" align="right"><div><img src="https://static.xx.fbcdn.net/rsrc.php/yv/r/B8BxsscfVBr.ico" height="14"> Meta for Developers</div><div><strong><a href="https://developers.facebook.com/tools/debug/">Sharing Debugger - Meta for Developers</a></strong></div></blockquote>
