### ISSUE TITLE
Feature: standalone chat page

### ISSUE THREAD

**Issue by ZiTAL** [owncast/owncast#3910]
Standalone chat page like twitch:

https://www.twitch.tv/popout/zitalko/chat

![Screenshot_2024-09-04_17-57-42](https://github.com/user-attachments/assets/33705a16-8246-43d6-bf42-cd8be7228210)

**Comment by germainelee** [comment]
@ZiTAL Owncast has standalone chat. See docs for more details https://owncast.online/docs/embed/#embedding-chat

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="https://owncast.online/favicon.png" height="14"> Owncast</div><div><strong><a href="/docs/embed/">Embedding into your site</a></strong></div><div>You can easily embed your chat or video into another site.</div></blockquote>
