### ISSUE TITLE
Changing the currently playing stream on the Owncast directory

### ISSUE THREAD

**Issue by neunenak** [owncast/owncast#3915]
### Share your bug report, feature request, or comment.

It seems like the Directory website at https://directory.owncast.online/ only plays a single stream, namely whatever happens to be the first video in the "What's Streaming Now" section. At least, I can't seem to find any control on the page that switches that stream to one of the other ones on the page. Clicking anywhere on any of the streams just opens that stream's own owncast instance in a new tab.

It would be nice if I could "channel-surf" the existing streams by clicking a button to move one of them to the currently-playing window.

**Comment by gabek** [comment]
That's correct. The currently live streams get ordered in a specific way based on a number of factors, and the one that is highest in that order gets featured. It's not meant to be a way for you to watch different streams or flip through them.

You can browse the directory, however, with any number of applications. The documentation around that is at https://owncast.online/docs/watching-on-tvs/#browsing-the-directory.

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="https://owncast.online/favicon.png" height="14"> Owncast</div><div><strong><a href="/docs/watching-on-tvs/">Watching an Owncast Stream on Televisions</a></strong></div><div>The web isn't the only option for watching an Owncast stream.</div></blockquote>
