### ISSUE TITLE
Can't upload icon

### ISSUE THREAD

**Issue by SpiderD555** [owncast/owncast#3933]
### Share your bug report, feature request, or comment.

I am trying to upload the png icon to my owncast instance via admin webpage. The page even shows success on upload, but when I refresh the page, then it still shows the old logo

**Comment by gabek** [comment]
The old image is likely cached in your browser. Clear your cache, or force-refresh the page.

**Comment by SpiderD555** [comment]
You are completely right. Just opened it up in a different browser and the logo is correct. Thanks for the tip.
