### ISSUE TITLE
[Feature] Disable password option or setup proper OIDC authetntication for /admin endpoint

### ISSUE THREAD

**Issue by SpiderD555** [owncast/owncast#3940]
Hi,
I would like to have a "disable-password" option for the admin page. The rationale behind it is that I have setup a working OIDC IDP provider along with oauth2-proxy, so whenever I visit /admin url then I need to authenticate with my IDP.
It all works great, I use my strong FIDO2 (or OTP) authentication, and can proceed. However the whole flow is broken because I (or any other user that I allow to access on the IDP) still need to put the static login/password credentials. The best way obviously would be to have native OIDC functionality in the Owncast.
I am not familiar with GO, so I don't know how to contribute to the code there, but I can provide example working haproxy and oauth2-proxy configuration snippets if needed.

**Comment by gabek** [comment]
That is a pretty specific use case, so I don't think adding support for disabling authentication would be a great move for the software as a whole.

The HTTP Basic auth has been a good compromise without adding a lot of complexity for people who are trying to set up Owncast. Forcing them to understand, and configure, OIDC before they can use their Owncast server would be a non-starter.

In cases like this, where it's a very specific request for just you, I recommend making a small change to the code if you need it to do something, like removing admin authentication, and having your own build.

**Comment by SpiderD555** [comment]
> The HTTP Basic auth has been a good compromise without adding a lot of complexity for people who are trying to set up Owncast. Forcing them to understand, and configure, OIDC before they can use their Owncast server would be a non-starter.

All the software I know use OIDC as an option, not enforce it. Take [paperless](https://github.com/paperless-ngx/paperless-ngx) as an example. They have recently added support for OIDC auth (but not enabled it by default), and yet didn't enforce the removal of regular password authentication. Having an optional function is not something that will increase complexity for regular user, yet power users will be thankful.

Think of it from the perspective of why people move away from commercial streaming platforms. One of the reasons is a wide freedom that opensource software like Owncast provides. No restrains, just possibilities.
At some point a lot of such people decide to host those apps themselves, and to **avoid** insecure setups where you need a ton of passwords (one for each app), they decide to establish IDP provider - one place that rules them all. Usually such place already enforces strong authentication schemes which you don't need to take care of on the application level. For example 2FA or certificate-based authentication. Sure it's not for everybody, but there is a lot of people doing just that because they want to gain freedom - see the very recent [selfhosted reddit conversation](https://old.reddit.com/r/selfhosted/comments/1fiq9fv/lets_start_a_megathread_of_self_hosted/) about it or [yet another one](https://old.reddit.com/r/selfhosted/comments/1fnn6fp/what_are_people_using_for_authentication_in_late/).
