### ISSUE TITLE
Stream to owncast from anywhere

### ISSUE THREAD

**Issue by dinosaur23** [owncast/owncast#3957]
### Share your bug report, feature request, or comment.

I use owncast to stream onto my website and the only problem I have is that I can only stream from my Home (where the owncast server is) to my website. I tried tunneling the rtmp port but it won't work

![Image](https://github.com/user-attachments/assets/f2c9e66d-cce7-4d94-b076-b99f334ca3c7)

**Comment by gabek** [comment]
Owncast doesn't care where you're streaming from. Local network, or remote network, it's all the same. It sounds like there's something wrong at your network level with your proxy, your port forwarding, or perhaps there's a firewall actively blocking port 1935 somewhere?

**Comment by dinosaur23** [comment]
I checked my routers firewall and it isn't blocking 1935. I think it's a problem with cloud flare

**Comment by gabek** [comment]
Ahh yes. You didn't mention cloudflare. Anytime anybody has an issue and uses cloudflare it's related to cloudflare.

**Comment by dinosaur23** [comment]
Is there a service like cloudflare tunnels that works with rtmp

**Comment by gabek** [comment]
I've never used Cloudflare tunnels, so I can't say I'm knowledgeable about it.

**Comment by dinosaur23** [comment]
so is their no way for me to make the rtmp port public?

**Comment by gabek** [comment]
You would make it public the same way you make any other service public. I don't know what your environment is, but if you install it on a machine that's publicly accessible, and you don't have a firewall blocking the port, then it's public. If you install it on a machine that's on an internal network that is not publicly accessible from the internet, then you have to forward a port to your Owncast installation. Nothing special from any other service.

**Comment by dinosaur23** [comment]
so if I have the rtmp server at 192.168.0.100:1935 it's already public? I don't know what you're saying

**Comment by gabek** [comment]
That's an internal IP address. I recommend you do some research on port forwarding, and how it's accomplished with your specific environment. This is a general networking thing and not related to Owncast. If you want to run public services from your home, you'll want to learn how this stuff works.
