### ISSUE TITLE
Issues when running on airgap environment

### ISSUE THREAD

**Issue by gaby** [owncast/owncast#3991]
### Share your bug report, feature request, or comment.

I'm currently testing `owncast` on a server with no internet access, where LAN users will be able to see the stream.

One thing we noticed is the default "Stream Offline" page is trying to reach `owncast` website to render a video in a thumbnail.

Second issue is during a stream the emojis menu timeouts because its trying to reach CDN resources.

**Comment by gabek** [comment]
Owncast is completely self-contained. All the assets are available within Owncast itself. The page content has an embedded video as an example of what you can do with it. It's meant for you to remove and add your own content.

I'll need more detail about what this CDN is that you're referring to. Owncast does not point to a CDN.

**Comment by gaby** [comment]
@gabek owncast doesn't make the requests to the internet, but npm dependencies do. Here are the requests happening on the background when opening the `emoji` menu within a chat. These are caused by `picmo` which is deprecated: https://www.npmjs.com/package/picmo

![Image](https://github.com/user-attachments/assets/b68c2a97-5edf-45c1-a4b5-0a357f105fac)

The documentation for `picmo` has a fix for using local data, that is documented here https://github.com/joeattardi/picmo/blob/main/docs/docs/02%20-%20usage/06%20-%20emoji-data.md#provided-static-data

**Comment by gabek** [comment]
I'm afraid I'm not able to reproduce this.

![Image](https://github.com/user-attachments/assets/7159befa-c822-41da-9c62-427b423dafc8)

**Comment by gaby** [comment]
@gabek This only happens during a stream, disconnect the host from the internet and open the Emoji Picker. Here is the code where `picmo` uses CDN urls: https://github.com/joeattardi/picmo/blob/main/packages/picmo/src/data/emojiData.ts#L13

<blockquote><img src="https://opengraph.githubassets.com/19d41837846f449a5f6d9ec3c647cff6ea065e7fa6625fdf985bdef669deeab8/joeattardi/picmo" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/joeattardi/picmo/blob/main/packages/picmo/src/data/emojiData.ts">picmo/packages/picmo/src/data/emojiData.ts at main · joeattardi/picmo</a></strong></div><div>JavaScript emoji picker. Any app, any framework. Contribute to joeattardi/picmo development by creating an account on GitHub.</div></blockquote>

**Comment by gaby** [comment]
Just in case, I'm running owncast using this: 

```yaml
services:
  owncast:
    image: owncast/owncast:latest
    ports:
      - "8080:8080"
      - "1935:1935"
    volumes:
      - ./data:/app/data
```

**Comment by gaby** [comment]
@gabek This was fixed by #4001 is there a timeline of when is the next owncast release?

**Comment by gabek** [comment]
There is not. It's when everything is closed out and there's enough testing performed on it.

**Comment by gaby** [comment]
Thanks! 💪
