### ISSUE TITLE
Bug : logo won't save

### ISSUE THREAD

**Issue by teckdan** [owncast/owncast#3995]
### Share your bug report, feature request, or comment.

The logo won't save, even though it is displaying success, pressing refresh returns to default logo. Image size is 224X226, JPG format![Image](https://github.com/user-attachments/assets/676ed8b2-e618-4953-8fb4-8c3b13d3afb2)

**Comment by gabek** [comment]
Your old logo is probably still cached in your browser.

**Comment by teckdan** [comment]
Gotcha. tried with another browser and it works.
