### ISSUE TITLE
Owncast transcoder dies when there is no audio in the stream

### ISSUE THREAD

**Issue by markusressel** [owncast/owncast#400]
Hi there, awesome project!

I have a problem with broadcasting a webcam to owncast using ffmpeg.
This is the command I am using:
```
ffmpeg -input_format h264 -f video4linux2 -s 1920x1080 -r 30 -i /dev/video0 -c:v copy -an -f flv rtmp://192.168.2.11:1935/live/abc123
```
This sends an rtmp stream to an NGINX proxy, which pushes the stream to another instance, which runs owncast. I have also tested this without the NGINX proxy, so I am quite confident that it is not the issue (therefore not in the title of this issue).
**I am able to watch the stream using VLC** and the `rtmp://192.168.2.11:1935/live/abc123` url.
When starting the stream, owncast logs the connection, but the website is still offline. When stopping and restarting the ffmpeg stream, errors are shown.

```
> docker run -p 8080:8080 -p 1935:1935 -it gabekangas/owncast:0.0.2
INFO[2020-11-30T01:10:55Z] Owncast v0.0.2-docker (ef3796a033b32a312ebf5b334851cbf9959e7ecb) 
INFO[2020-11-30T01:10:55Z] Web server running on port: 8080             
INFO[2020-11-30T01:10:55Z] RTMP server is listening for incoming stream on port: 1935 
INFO[2020-11-30T01:10:56Z] Incoming RTMP connected.                     
ERRO[2020-11-30T01:12:04Z] stream already running; can not overtake an existing stream 
ERRO[2020-11-30T01:12:07Z] stream already running; can not overtake an existing stream 
ERRO[2020-11-30T01:12:10Z] stream already running; can not overtake an existing stream 
ERRO[2020-11-30T01:12:13Z] stream already running; can not overtake an existing stream 
ERRO[2020-11-30T01:12:16Z] stream already running; can not overtake an existing stream 
```

I am using the docker variant in version 0.0.2.

**Comment by gabek** [comment]
Thanks for letting us know!  I haven't specifically tried this scenario, but I know somebody else was using a video capture device under Linux and broadcasting with Owncast.  He blogged his specifics here: https://blog.fluxcoil.net/posts/2020/11/linux-hdmi-grabber-2/

I think I'll plug in a webcam to my Linux machine and see if I can debug with your setup.

In the meantime:

I know you're running under docker, but if you could grab the `transcoder.log` I'm curious what that has to tell us.  Also if you could shell into your Docker machine and run Owncast manually with `./owncast --enableVerboseLogging --enableDebugFeatures` that might help troubleshoot as well.

Thanks again, and hopefully we can get this tracked down for you!

**Comment by markusressel** [comment]
This is the `transcoder.log` output:
```
[live_flv @ 0x7f2144e8a1c0] decoding for stream 0 failed
Input #0, live_flv, from 'pipe:':
  Metadata:
    profile         : 
    Server          : NGINX RTMP (github.com/sergey-dryabzhinsky/nginx-rtmp-module)
    displayWidth    : 1920
    displayHeight   : 1080
    fps             : 30
    level           : 
  Duration: 00:00:00.00, start: 2253.185000, bitrate: N/A
    Stream #0:0: Video: h264 (Constrained Baseline), yuvj420p(pc, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 30 fps, 30 tbr, 1k tbn, 60 tbc
Stream map 'a:0' matches no streams.
To ignore this, add a trailing '?' to the map.
```

**Comment by gabek** [comment]
Ah ha!  It isn't liking that there's no audio stream being sent to it.  Never thought of that before.  Thank you for sending that along.  We're going to get the 0.0.3 release out soon (within a week or so?), but I'll get a fix in for this into master before that.  It should be straightforward now that I know what's going on.

**Comment by markusressel** [comment]
Ah, glad you were able to determine the cause so quick!
I already read that the audio might be an issue previously :facepalm:

The problem can also be worked around by providing an empty audio track, for my example in the first post this would be:
```
ffmpeg -input_format h264 -f video4linux2 -s 1920x1080 -r 30 -i /dev/video0 -f lavfi -i anullsrc -c:v copy -c:a aac -shortest -f flv rtmp://192.168.2.11:1935/live/abc123
```

**Comment by gabek** [comment]
I'm afraid this might be an issue again with a revert I made in https://github.com/owncast/owncast/issues/432 to fix a Restream issue.  I'm reopening this until I can test to see what the status is.

**Comment by gabek** [comment]
Removing it from the milestone since I want to keep core changes to a minimum until we make the release and only fix show stoppers.  This is a pretty edge case scenario.

**Comment by gabek** [comment]
Yeah unfortunately the fix for Restream brought back this issue.

The previous fix was to wait until we can parse the RTMP metadata before we start the transcoder, so we can use the RTMP metadata to know if there's audio or not.  But Restream-based content was upset that we weren't sending those initial packets to the transcoder.

So given the two options right now I'd venture to guess not many people are doing non-audio streams.  Plus there is the above work around.

This is fixable, but I don't feel comfortable digging into the core video pipeline right before we release and changing things around.  I'll get this supported for 0.0.4.

**Comment by markusressel** [comment]
I really appreciate the effort, but honestly, I would just put this (including an example ffmpeg call) into the docs and call it a day until someone has a problem with this again which NEEDS fixing.

**Comment by gabek** [comment]
Good call, I'll do that.  Thanks!
