### ISSUE TITLE
New emoji picker is not showing the custom emoji

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#4010]
### Share your bug report, feature request, or comment.

This worked fine when I tested the PR #4001, but now that it's deployed to a couple servers, that option isn't there.

![Image](https://github.com/user-attachments/assets/083b4a27-dc0b-4763-af8a-9c819ea39abb)

**Comment by mahmed2000** [comment]
https://github.com/owncast/owncast/commit/7830b3765a0f30bb4f41244842e97a2b177bbfe5 bruh.

Its the custom category sorting. Its a listed issue in the emoji-mart repo https://github.com/missive/emoji-mart/issues/951. Broke with 5.3 and later so I manually set it to ~5.2.2. Renovate had other plans I guess. Until that is fixed upstream, can either keep the older version or allow the custom categories to be last in the order.

**Comment by gabek** [comment]
Fixed by hardcoding it to `5.2.2`. Renovate should leave it alone now.

**Comment by mahmed2000** [comment]
Happened again: 4c7ccdbbf94c0dfe861a33d7250aa2c93c25360f. Renovate is going to need an ignore rule I think.

**Comment by gabek** [comment]
I pushed a config change to hopefully force it to do what I expected it to do in the first place.

**Comment by gabek** [comment]
Nope, that didn't work either. There has to be an option between automatically update without giving anybody a choice, and completely never updating ever again.

**Comment by mahmed2000** [comment]
Might just be an invalid regex? The slashes are missing.

> This field also supports Regular Expressions which must begin and end with /.

https://docs.renovatebot.com/configuration-options/#matchcurrentversion

<blockquote><div><strong><a href="https://docs.renovatebot.com/configuration-options/#matchcurrentversion">Configuration Options - Renovate Docs</a></strong></div><div>Configuration Options usable in renovate.json or package.json</div></blockquote>

**Comment by gabek** [comment]
Nice catch, I just pushed a change. Let's see if it helps. If not, I'll just ignore it completely in the config.

**Comment by mahmed2000** [comment]
Happened again a month ago, 6f8e9f9.
