### ISSUE TITLE
Federation enabled state does not respect the "Enable Social Features" modal cancellation

### ISSUE THREAD

**Issue by mahmed2000** [owncast/owncast#4021]
The fediverse enabled state only cares about the toggle switch in the admin. Enabling the switch prompts a modal. Cancelling or closing said modal only updates the UI for the toggle. On reloading the page, it will flip to an enabled state. The `enable` API call gets sent on toggling, which means federation is enabled before the modal even opens.

### Repro steps
 
- Create a server and configure it to have a server URL.
- Config -> Social
  - Disable social features if they have been enabled.
- Toggle the "Enable Social Features" switch and wait for the modal.
  - The "Compose Post" button also shows up at this point.
- On the "Enable Social Features" modal, either click "Do not enable" or close the modal.
  - The toggle flips off, but the "Compose Post" button is still visible.
- Reload the page.
  - The toggle is on now, and the main stream page shows the Follow button. Federation is enabled even though the modal's disclaimer was not agreed to.

**Comment by varungujarathi9** [comment]
Hi @gabek 
I can work on this

**Comment by gabek** [comment]
That would be fantastic, thank you, @varungujarathi9!
