### ISSUE TITLE
Datastore migration infinite loop after config repository was implemented

### ISSUE THREAD

**Issue by flexiondotorg** [owncast/owncast#4025]
### Share your bug report, feature request, or comment.

**EDIT:**

~~I migrated from 0.1.3 to 0.2.0-pre and saw that the database was migrated. Although owncast runs the user entry page and /admin/ URL returns 502s.~~

~~I was able to get a working owncast 0.2.0-dev by reverting this commit: https://github.com/owncast/owncast/commit/0b5d7c8a4dc1d542d306b93133e9f18f3167919c~~

While migrating from 0.1.3 to 0.2.0, I saw log messages stating that the database was migrating datastore values from 3 to 4. The migration took many minutes, and the message was logged millions of times, during which Owncast was unresponsive.

- See for more detail: https://github.com/owncast/owncast/issues/4025#issuecomment-2497820116

**Comment by gabek** [comment]
Thanks for reporting this. I'm not able to reproduce, so I'm curious what you're seeing. What do you see in the application logs?

**Comment by flexiondotorg** [comment]
This happened on my production instance, but I don't have a 0.1.3 database backup to reproduce with 🤦 

I'll try and reproduce using a 0.1.3 database from one of my test instances.

**Comment by gabek** [comment]
If you just copy your entire `data` directory and move that to another server, in most cases that should spin up a complete copy of your server. Unless it's maybe a different architecture, or some other reason the database is completely not compatible.

**Comment by mahmed2000** [comment]
From a fresh v0.1.3 data dir, trying to start a v0.2.0-dev server results in an endless flood of "Migration datastore values from 3 to 4" for me. @flexiondotorg does your log file happen to have this message and/or be incredibly large? Running it for a second or two ballooned it to ~7MB with the same message.

As a sanity test, I also tried to go from v0.1.0 (datastore v2) to v0.2.0-dev. Same error, but from 2 to 3 instead.

I don't think owncast can return 502s, that's probably the reverse proxy I think. Because owncast is getting stuck there, the http server doesn't start and the port is closed, hence a bad gateway.

**Comment by flexiondotorg** [comment]
Good catch @mahmed2000 👍 

I saw `time="2024-11-21T11:50:12Z" level=info msg="Migration datastore values from 3 to 4\n"` in my logs. That log message is written to the `owncast.log` file ~4,350,000 times! Per minute!! 👈 @gabek

I let owncast complete the migration, and my `owncast.log` has grown to 6162MB.

- The first *Migration datastore values from 3 to 4* was at `2024-11-21T11:50:12Z`
- The last  *Migration datastore values from 3 to 4* was at `2024-11-21T12:07:48Z`

The migration took 17 minutes and 36 seconds, resulting in 75,131,486 log entries.

**Comment by mahmed2000** [comment]
There's an infinite recursion in the configRepository migration functions.

https://github.com/owncast/owncast/blob/d578f01348bc46153174155758d162792567d5c1/persistence/configrepository/configMigrations.go#L84-L85

All 3 migration functions start with this `Get` function:

https://github.com/owncast/owncast/blob/d578f01348bc46153174155758d162792567d5c1/persistence/configrepository/sqlconfigrepository.go#L27-L32

If the `temporaryGlobablInstance` is `nil` (such as pre-migration to the new config repository), `New` gets called.:

https://github.com/owncast/owncast/blob/d578f01348bc46153174155758d162792567d5c1/persistence/configrepository/sqlconfigrepository.go#L36-L41

which runs `migrateDatastoreValues` again which logs the line:

https://github.com/owncast/owncast/blob/d578f01348bc46153174155758d162792567d5c1/persistence/configrepository/configMigrations.go#L16-L32

**Comment by gabek** [comment]
Thanks for reporting this and looking at it! Migrations clearly aren't something I must have tried with all the changes yet. I really appreciate the help!
