### ISSUE TITLE
Dead URL Link in storybook

### ISSUE THREAD

**Issue by teckdan** [owncast/owncast#4043]
### Share your bug report, feature request, or comment.

CSS Variables
You can override the values assigned to CSS variables manually by setting them in the CSS editor in the admin. You can find a list of variable names you can override.

**The following URL is dead:**
https://owncast.online/components/?path=%2Fdocs%2Fowncast-styles-colors--default-theme

Link Preview

[@storybook/core - Storybook](https://owncast.online/components/?path=%2Fdocs%2Fowncast-styles-colors--default-theme)

Couldn't find story matching 'owncast-styles-colors--default-theme'.
The component failed to render properly, likely due to a configuration issue in Storybook. Here are some common causes and how you can address them:

Missing Context/Providers: You can use decorators to supply specific contexts or providers, which are sometimes necessary for components to render correctly. For detailed instructions on using decorators, please visit the Decorators documentation.
Misconfigured Webpack or Vite: Verify that Storybook picks up all necessary settings for loaders, plugins, and other relevant parameters. You can find step-by-step guides for configuring Webpack or Vite with Storybook.
Missing Environment Variables: Your Storybook may require specific environment variables to function as intended. You can set up custom environment variables as outlined in the Environment Variables documentation.
Are you sure a story with that id exists?
Please check your stories field of your main.js config.
Also check the browser console and terminal for error messages.

**Comment by gabek** [comment]
@teckdan What page was this broken link on?

It should be replaced with https://owncast.online/components/?path=/docs/owncast-styles-colors-palette--docs

<blockquote><div><strong><a href="https://owncast.online/components/?path=/docs/owncast-styles-colors-palette--docs">@storybook/core - Storybook</a></strong></div></blockquote>

**Comment by teckdan** [comment]
https://owncast.online/docs/appearance/#css-variables

**Comment by teckdan** [comment]
You can find a list of [variable names](https://owncast.online/components/?path=%2Fdocs%2Fowncast-styles-colors--default-theme) you can override.

**Comment by teckdan** [comment]
@gabek The correct link you supplied is not the one that should be in that place.

**Comment by gabek** [comment]
Ok, what should it be replaced with if it shouldn't be the page with the list of CSS variables?

**Comment by teckdan** [comment]
> [@teckdan](https://github.com/teckdan) What page was this broken link on?
> 
> ### It should be replaced with https://owncast.online/components/?path=/docs/owncast-styles-colors-palette--docs
> 
> > **[@storybook/core - Storybook](https://owncast.online/components/?path=/docs/owncast-styles-colors-palette--docs)**

@gabek You mentioned that it should be replaced with a link that seem to relate to color palettes... I was replying to this saying that your link is not relevant to CSS variables.

<blockquote><div><strong><a href="https://owncast.online/components/?path=/docs/owncast-styles-colors-palette--docs">@storybook/core - Storybook</a></strong></div></blockquote>

**Comment by gabek** [comment]
It's literally the list of CSS variables. I'm not sure how it's not relevant. 

![Image](https://github.com/user-attachments/assets/eb88e90b-ca32-4ec7-a4eb-19d91455d2a8)

**Comment by teckdan** [comment]
You're the judge. But in my view, aren't CSS variable much broader than just being limited to colors? What about header, footer, fonts, layout, backgrounds, buttons and click behaviors and so on?

I clicked on that link to see what's **really** possible to work with inside the custom CSS page. But if you limit to only colors, then, I won't know what else I can work with inside Owncast.

**Comment by gabek** [comment]
This issue is to fix a broken documentation link called `owncast-styles-colors--default-theme`, meaning it was a document about the colors in the default theme. That's all. The scope of fixing a broken link is not to rewrite how CSS variables work within Owncast. We've never had CSS variables for things like click behaviors, layouts, etc. But as always, if there's something you'd like to see, please file a specific feature request with what you're looking to do.

Fixing a broken link called `owncast-styles-colors--default-theme` with a page called `owncast-styles-colors-palette--docs` so people get the list of CSS variables for the colors makes sense to me.

**Comment by teckdan** [comment]
I'm interested in knowing what the full breadth of CSS variables are available for me to use, which is beyond colors, but if your system is only limited to color palettes, then I now understand its limitations.
