### ISSUE TITLE
Scroll bar on top is not scrollable

### ISSUE THREAD

**Issue by RobertEcker** [owncast/owncast#4046]
How can the scroll bar on top be scrolled to the right in a more obvious way?

![Image](https://github.com/user-attachments/assets/59d2ed0d-d90d-40b6-b659-f8c8940928b9)

**Comment by gabek** [comment]
Personally, I scroll it simply by using the scroll gesture on my trackpad like I would be scrolling anything else. Are you not able to scroll it at all?

**Comment by RobertEcker** [comment]
@gabek Thank you for your comment
If you click on it + cursor - yes, that works
not sure if this is a good solution, a visual horizontal scroll bar would make more sense IMHO (which is easier to use and faster)

maybe a tag search would be also not bad

**Comment by germainelee** [comment]
This issue sounds similar to #3753

**Comment by gabek** [comment]
Yup! I updated the title of #3753 to reflect both of these issues, since there's already a discussion there.
