### ISSUE TITLE
Streaming from phone camera live

### ISSUE THREAD

**Issue by Carreker** [owncast/owncast#4047]
I am able to get owncast working and streaming to my website and phone locally.  When I stream using my phone and an app called manycam for android I am able to use my phones camera to live stream using the rtmp stream url locally.  The issue is when I leave my house and try to stream from my phone it does not work with the private local IP address and when I use the subdomain (example.domain.com) it also does not work?  I am using nginix reverse proxy manager installed on a raspberry pi 5 with ubuntu server 24.04 installed.  I also have ssl certificates for the subdoamin for owncast.  For some reason on my desktop PC the url that only works is the one with the local ip address 10.0.0.158:1935/live the subdomain url does not work.  Please help

**Comment by gabek** [comment]
Hi there. Did you set up port forwarding for your network so you can access your private network from the internet? This is something you would need to do to run any public service from your private networking.

Usually, you'll be able to search for the brand of router you run at home and find its instructions for "port forwarding". You would want to enable forwarding of ports 8080 for the Owncast web server, and 1935 for the Owncast RTMP server.

Here's a quick overview I found that might be helpful. https://homenetworkgeek.com/port-forwarding/

<blockquote><img src="https://homenetworkgeek.com/wp-content/uploads/2020/02/Port-Forwarding-e1589005365482.jpg" width="48" align="right"><div><img src="https://homenetworkgeek.com/wp-content/uploads/2020/08/cropped-YouTube-Channel-Icon-192x192.jpg" height="14"> Home Network Geek</div><div><strong><a href="https://homenetworkgeek.com/port-forwarding/">Port Forwarding: What It Is and How to Set It Up - Home Network Geek</a></strong></div><div>Port forwarding provides a way of making a device on your home network accessible to others on the Internet. Here is a tutorial on how to set it up.</div></blockquote>

**Comment by Carreker** [comment]
Yes I forwarded ports 443 and 8080 on the nginix reverse proxy and the
created a proxy host for the owncast server.  Is there something special I
need to do?  This revese proxy is new for me.

**Comment by Carreker** [comment]
here is my website https://squirrellycoin.com/index.php/test/

**Comment by gabek** [comment]
>  Is there something special I need to do? This revese proxy is new for me.

Owncast itself doesn't have any settings that are specific to running behind a proxy. 

I'm afraid I don't know anything about nginx proxy manager, so I can't tell you step by step how to configure it. But if nginx proxy manager is proxying 1935 as a web service, that might be the problem. RTMP/1935 is not a web service, it's RTMP. So it should not go through a web proxy. You should port forward it directly, unless there's some type of setting you have that can do raw TCP proxying.

**Comment by Carreker** [comment]
ok great thank you!!

**Comment by Carreker** [comment]
Thank you so much Gabe!  That did the trick!  How can I give you a donation
to show you how much that I appreciate your time?!

**Comment by gabek** [comment]
Glad you were able to figure it out! We accept donations to the project at https://opencollective.com/owncast, thank you for the support!

<blockquote><img src="https://images.opencollective.com/owncast/bc577d9/background.png" width="48" align="right"><div><strong><a href="https://opencollective.com/owncast">Owncast - Open Collective</a></strong></div><div>Your self-hosted live streaming solution.</div></blockquote>

**Comment by Carreker** [comment]
This donation is because of you Gabe!

**Comment by flixyudh** [comment]
@Carreker could you share how do you handle `rtmp` on Nginx proxy manager web UI?

**Comment by Carreker** [comment]
I opened port 1935 on the router.
