### ISSUE TITLE
Too many packets buffered for output stream, Conversion failed!

### ISSUE THREAD

**Issue by markusressel** [owncast/owncast#406]
Hi there,

after experimenting some more, i ran into the following issue:

transcoder.log
```
/app # cat transcoder.log 
Input #0, live_flv, from 'pipe:':
  Metadata:
    profile         : 
    Server          : NGINX RTMP (github.com/sergey-dryabzhinsky/nginx-rtmp-module)
    displayWidth    : 1920
    displayHeight   : 1080
    fps             : 30
    level           : 
  Duration: 00:00:00.00, start: 0.302000, bitrate: N/A
    Stream #0:0: Audio: aac (LC), 44100 Hz, stereo, fltp, 128 kb/s
    Stream #0:1: Video: h264 (Constrained Baseline), yuvj420p(pc, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 30 fps, 29.97 tbr, 1k tbn, 60 tbc
Stream mapping:
  Stream #0:1 -> #0:0 (h264 (native) -> h264 (libx264))
  Stream #0:0 -> #0:1 (copy)
Too many packets buffered for output stream 0:1.32:22.77 bitrate=N/A speed=N/A    
Conversion failed!
```

The setup:
I have a local machine thats running an RTMP stream using ffmpeg:
```
/usr/bin/ffmpeg -loglevel warning -input_format h264 -f video4linux2 -s 1920x1080 -r 30 -i /dev/video0 -f lavfi -i anullsrc -c:v copy -c:a aac -shortest -f flv rtmp://192.168.2.11:1935/live/abc
```
This stream is sent to an NGINX proxy, which pushes it to a cloud server.
The cloud server is running owncast:0.0.2 in a docker container.

For testing I also ran a local instance of owncast, and instructed the NGINX proxy to push the stream to both the cloud and the local instance. Interestingly I do **not** get the error on the local owncast instance. It plays the stream just fine, while the cloud instance fails.

I tried adding `-max_muxing_queue_size 9999` to the ffmpeg command of the initial streaming machine, [as I have read about it here](https://stackoverflow.com/questions/49686244/ffmpeg-too-many-packets-buffered-for-output-stream-01) (and other places), but that did not fix the issue. Maybe this needs to be added to the owncast instance instead?

**Comment by gabek** [comment]
For your local instance, is it also running under Docker?  I'm curious if the two versions of `ffmpeg` are the same.

**Comment by markusressel** [comment]
Yes, both docker v0.0.2, using the same config.

**Comment by gabek** [comment]
We do set a `max_muxing_queue_size`, but not the arbitrary 9999.  https://github.com/owncast/owncast/blob/master/core/ffmpeg/transcoder.go#L157

What you're seeing is slightly baffling, as the environment within that container should be the same between the two scenarios.

All I can suggest is try to simplify and see what might be the culprit from the broadcasting side.  What if you didn't change the framerate?  What if you didn't set a resolution?

As a side note, I wasn't able to get my integrated webcam to work on linux using your invocation of ffmpeg, I guess because mine doesn't support h264 in hardware, so I had to pull raw and then use libx264 on the way to Owncast.  But It's worked fine just doing this:

```
ffmpeg -re -input_format yuyv422 -f v4l2 -i /dev/video0 -c:v libx264 -f flv rtmp://127.0.0.1/live/abc123
```

**Comment by gabek** [comment]
It looks like there's been some movement on this front: https://github.com/FFmpeg/FFmpeg/commit/453b2f3c154f6b83221940ad411599ded91f7413

**Comment by markusressel** [comment]
> We do set a `max_muxing_queue_size`, but not the arbitrary 9999. https://github.com/owncast/owncast/blob/master/core/ffmpeg/transcoder.go#L157
Interesting :thinking: 

> What you're seeing is slightly baffling, as the environment within that container should be the same between the two scenarios.

That was also my thought, which is why I set up the exact same thing again on a local machine (I initially tested locally, moved to cloud, and then used both again to test this).

> All I can suggest is try to simplify and see what might be the culprit from the broadcasting side. What if you didn't change the framerate? What if you didn't set a resolution?

I get what you're saying, but just to be clear: I am not trying to change the original camera input in any way. In fact, that is the whole reason I am using ffmpeg directly, since it seems like it is the only program that is capable of streaming the original h264 stream provided by the camera in an RTMP format, without requiring an undesirable amount of CPU resources. Since I am trying to stream from a Raspberry Pi, realtime transcoding is not really an option. The parameters I supply to ffmpeg are jut there to select the desired original stream format.

> As a side note, I wasn't able to get my integrated webcam to work on linux using your invocation of ffmpeg, I guess because mine doesn't support h264 in hardware, so I had to pull raw and then use libx264 on the way to Owncast. But It's worked fine just doing this:
> 
> ```
> ffmpeg -re -input_format yuyv422 -f v4l2 -i /dev/video0 -c:v libx264 -f flv rtmp://127.0.0.1/live/abc123
> ```

As mentioned above, a transcoding step is the last thing I am willing to do to fix this. And based on the fact that it works in a local (docker) environment I hope it is not necessary. I will try it out though and post again.

**Comment by markusressel** [comment]
This is the command I use on both the local and the cloud instance:
```
docker run \
     -v ~/owncast.yaml:/app/config.yaml  \
     --name owncast \
     -p 8080:8080 \
     -p 1935:1935 \
     gabekangas/owncast:0.0.2
```
I also tried `--network host`, it made no difference.

This is the config:
```
# See https://owncast.online/docs/configuration/ for more details

instanceDetails:
  name: 3D Printer
  title: 3D Printer
  summary: "something"

  logo:
    small: /img/logo128.png
    large: /img/logo256.png

  tags:
    - 3dprinting
    - streaming

  # https://owncast.online/docs/configuration/#external-links
  # for full list of supported social links.  All optional.
  socialHandles:
    - platform: github
      url: http://github.com/markusressel

videoSettings:
  # Change this value and keep it secure.  Treat it like a password to your live stream.
  streamingKey: W2zMQUcMfhgS5y46CJ7YJqouE
```

This is the command that includes transcoding which I used to test:
```
ffmpeg -re -input_format yuyv422 -f v4l2 -i /dev/video0 -c:v libx264 -f flv rtmp://192.168.2.11:1935/live/W2zMQUcMfhgS5y46CJ7YJqouE
```

This is the local website, showing both "online" (with a time) and the "offline" video:
![image](https://user-images.githubusercontent.com/14024504/101055083-e5f89f80-3589-11eb-9f43-ef87e0ba9635.png)

Also, instead of on my desktop PC, I ran the "local" docker setup on my laptop, which resulted in the same behavior as the cloud node. So apparently my desktop PC is the only one which can handle the stream :thinking: 

The transcoder.log on my laptop:
```
/app # cat transcoder.log 
[h264 @ 0x7f58436ea6c0] co located POCs unavailable
[h264 @ 0x7f58436ea6c0] mmco: unref short failure
Input #0, live_flv, from 'pipe:':
  Metadata:
    profile         : 
    Server          : NGINX RTMP (github.com/sergey-dryabzhinsky/nginx-rtmp-module)
    displayWidth    : 1920
    displayHeight   : 1080
    fps             : 5
    level           : 
  Duration: 00:00:00.00, start: 88.800000, bitrate: N/A
    Stream #0:0: Video: h264 (High 4:2:2), yuv422p(progressive), 1920x1080, 5 fps, 5 tbr, 1k tbn, 10 tbc
Stream map 'a:0' matches no streams.
To ignore this, add a trailing '?' to the map.
frame=  176 fps=0.0 q=0.0 size=N/A time=00:00:08.04 bitrate[hls @ 0x7f7990490080] Opening 'webroot/hls/0/stream-1607011445.ts.tmp' for writing
[hls @ 0x7f7990490080] Opening 'webroot/hls/0/stream.m3u8.tmp' for writing
[hls @ 0x7f7990490080] Opening 'webroot/hls/stream.m3u8.tmp' for writing
frame=  193 fps=0.0 q=0.0 Lsize=N/A time=00:00:08.04 bitrate=N/A speed=15.1x    
video:832kB audio:111kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
[libx264 @ 0x561d3604dc00] frame I:1     Avg QP: 7.73  size:  2019
[libx264 @ 0x561d3604dc00] frame P:192   Avg QP: 3.23  size:  4422
[libx264 @ 0x561d3604dc00] mb I  I16..4: 95.1%  0.4%  4.4%
[libx264 @ 0x561d3604dc00] mb P  I16..4: 10.4%  0.2%  0.2%  P16..4: 11.5%  2.8%  2.2%  0.0%  0.0%    skip:72.7%
[libx264 @ 0x561d3604dc00] 8x8 transform intra:1.5% inter:3.2%
[libx264 @ 0x561d3604dc00] coded y,uvDC,uvAC intra: 6.3% 9.5% 8.2% inter: 7.2% 6.3% 4.9%
[libx264 @ 0x561d3604dc00] i16 v,h,dc,p: 93%  2%  5%  1%
[libx264 @ 0x561d3604dc00] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 28% 21% 31%  2%  5%  5%  4%  1%  3%
[libx264 @ 0x561d3604dc00] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 24% 23% 30%  3%  6%  5%  4%  2%  2%
[libx264 @ 0x561d3604dc00] i8c dc,h,v,p: 93%  3%  3%  2%
[libx264 @ 0x561d3604dc00] Weighted P-Frames: Y:3.6% UV:0.5%
[libx264 @ 0x561d3604dc00] kb/s:846.59
```

I will try to investigate this further when I find the time, maybe you can see something obvious.

**Comment by markusressel** [comment]
**I got it working now**, by simply stopping and restarting the existing docker container on the cloud instance. 

Maybe this is some kind of race condition? Maybe the ffmpeg process of owncast only works when started at the right time?

**Comment by markusressel** [comment]
I am not able to reproduce this anymore. If I run into this again with some more details on how reproduce it I will post a new issue.

**Comment by gabek** [comment]
Thanks for the update @markusressel!
