### ISSUE TITLE
add Chromecast button

### ISSUE THREAD

**Issue by gingervitis** [owncast/owncast#410]
thought it'd be nice to be able to project the stream on to a bigger screen.

**Comment by gingervitis** [comment]
Just remembered that Chromecast integration requires embedding this google script (which loads other scripts from google). Not sure how folks here feel about this, esp the pinging of external servers.
```<script type="text/javascript" src="https://www.gstatic.com/cv/js/sender/v1/cast_sender.js?loadCastFramework=1"></script>```

**Comment by pgeorgi** [comment]
I suppose the javascript could be loaded only when Chromecast is being requested? Sure, you'll access Google services then but when you're at the point where you select Chromecast, you're likely already dealing with a device that talks a lot with Google services.

**Comment by gingervitis** [comment]
I believe you'll first need the script to determine if there are any Chromecasts available to select.

**Comment by aaronpk** [comment]
How is this different than using the built in "Cast" feature in the browser menu? Isn't that good enough?

**Comment by pgeorgi** [comment]
@gingervitis I guess one could offer "send to chromecast" (besides other options) and only then check if there's anything to cast to, after loading the javascript?

@aaronpk Native ChromeCast support in a webapp can provide a better experience by having a separate UI on the TV - As I understand it that UI is driven with a separate HTML page that the browser can communicate with, so the TV could show only the video stream and maybe chat message bubbles for certain messages, while the browser provides the full UI (or even a different UI without the video, but with more space for the chat?)

Such extensions require work obviously and are more than a barebones "mirror the tab to the TV" option, which can be done with the browser's own streaming facilities, indeed.

**Comment by aaronpk** [comment]
Ah thanks, I haven't seen that in action before. Definitely sounds like some extra work but would be potentially useful. That said, it still requires loading google's javascript so I'd expect this to be something the server admin could disable. There's definitely times where it would be unacceptable to load third party javascript (especially google) into the player.

**Comment by gabek** [comment]
@lindner mentioned he might have an idea on how we can support Chromecast without fetching the remote cast Javascript, so I'll reopen this.

**Comment by lindner** [comment]
I think we can use the [w3c presentation API](https://www.w3.org/TR/presentation-api/) and things may work.  This is the open implementation of the Cast Web SDK and would also allow a web browser to support other second screen systems.

**Comment by KJThaDon** [comment]
Is this still not a thing?

**Comment by gabek** [comment]
@KJThaDon Nope! Are you interested in working on adding support for the presentation API?
