### ISSUE TITLE
Restream Failure

### ISSUE THREAD

**Issue by graywolf336** [owncast/owncast#432]
```
TRAC[2020-12-06T16:26:35Z]/home/bradley/go/src/github.com/gabek/owncast/core/rtmp/rtmp.go:71 github.com/owncast/owncast/core/rtmp.HandleConn.func1() [Type AMF0 Time 15862 Len 44 Data ["onStatus",{"code":"NetStream.Data.Start"}] Header ]
ERRO[2020-12-06T16:26:35Z]/home/bradley/go/src/github.com/gabek/owncast/core/rtmp/broadcaster.go:14 github.com/owncast/owncast/core/rtmp.setCurrentBroadcasterInfo() Not a onMetaData message
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0xbb8781]

goroutine 141 [running]:
github.com/owncast/owncast/core.setStreamAsConnected.func1()
        /home/bradley/go/src/github.com/gabek/owncast/core/streamState.go:46 +0x41
created by github.com/owncast/owncast/core.setStreamAsConnected
        /home/bradley/go/src/github.com/gabek/owncast/core/streamState.go:44 +0x115
exit status 2
```

**Comment by gabek** [comment]
Could you give the output of `./owncast --enableVerboseLogging` ?

**Comment by gabek** [comment]
For reference in 0.0.3 we started using headers passed along in RTMP and while we've seen some software who send different looking headers, yours looks to not be sending any at all.  But I'm curious if it's like Matt's camera and sending multiple header payloads, and the log should show that.

**Comment by gabek** [comment]
I just added a nil check to stop the crash if nothing else, but not sure what else might happen.

**Comment by graywolf336** [comment]
That was with the verbose logging, but I just sent you it in private due to containing ip addresses. Thanks for looking into this!

**Comment by graywolf336** [comment]
Just pulled the latest changes and will let you know how it works in a few hours.

**Comment by gabek** [comment]
I resubscribed to Restream, so I'll do some troubleshooting.

**Comment by graywolf336** [comment]
It seemed like the connection was unstable and restream had to keep retrying to send the RTMP feed to it. I'll ensure I pull latest Wednesday as it's the next time it will be used.

**Comment by gabek** [comment]
In troubleshooting it turned out a couple things:

1. Passthrough was enabled, turning it off fixed issues with Restream.
1. The CPU was being hit a bit too much, removing one of the video variants in the config resolved that.  I decreased the alerting threshold of hardware utilization to try to help people with this going forward.

After that all seemed to work without an issue.  Closing.
