### ISSUE TITLE
Unable to change the chatname on mobile devices

### ISSUE THREAD

**Issue by jeyemwey** [owncast/owncast#448]
When using **Chrome on Android** phones (not sure about other phones), the "change chatname" feature doesn't work.

I can click on the name so it shows the input element with the button, but when I click on the input element, the keyboard appears and disappears momentarily.

My attempt of a screen recording of my bug: https://photos.app.goo.gl/Bu4ZN8NyMuFWFNYu9

**Comment by gingervitis** [comment]
Oh! Yes I fixed this yesterday! It's in master. This one d4f51625053abcb4e2aa71a74994142bf2fc118e.
