### ISSUE TITLE
Emoji selection window extends from the chatbox to below the screen

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#455]
Saw this in the demo chat:

> emoji selection window extends from the chatbox to below the screen! FF 83.00

**Comment by gingervitis** [comment]
I cannot repro this. 
Ok well, I can only repro this under these cases:
- This can certainly be a problem if your window is shorter than the emoji panel.  If your window is that short, you'll certainly have other issues you may need to reconsider how you watch video.
- Or if you resize your window while the emoji picker panel is already open.  You'll have to close the panel then open it again for it to recenter itself. I think that flow is acceptable.

I'm tempted to mark this as a WON'T FIX.

**Comment by jeyemwey** [comment]
I had that issue on the watch.owncast.online stream on Safari for iPad, too. I'm not sure tho if it was fixed since then.
