### ISSUE TITLE
Subscription via ActivityPub and integration into the Fediverse

### ISSUE THREAD

**Issue by drequivalent** [owncast/owncast#458]
It would be awesome if the Fediverse users from Pleroma, Mastodon, Friendica, etc. could subscribe to their favorite streamers and get the announcements of coming broadcasts.

As I see it now, every user should have an actor with a timeline, into which the "Event" type objects are pushed

https://www.w3.org/TR/activitystreams-vocabulary/#dfn-event

The object will have StartTime and EndTime properties.

After the stream, if the video record is available, we can also publish a Video object, and receive replies as comments, much like Peertube does:

https://www.w3.org/TR/activitystreams-vocabulary/#dfn-video

Also, the mentions that are intercepted during the stream can be treated as chat messages, or something else can be done with them.

**Comment by Gargron** [comment]
What you need to become part of the fediverse:

- `/.well-known/webfinger` that responds to queries and points to
- `/actor`, a JSON response with properties such as `preferredUsername`, `inbox` and some others
- `/inbox` which accepts POST requests and verifies HTTP signatures
- An inbox handler for the `Follow` activity which sends an `Accept` activity back to the sender
- A way to store the list of followers with their inboxes

That would be the basic of it. I have never used it personally but I think the [go-fed library](https://github.com/go-fed/activity) could take care of some of the heavy lifting. Then the interesting part:

- When a stream goes live, distribute a `Create` activity to the followers' inboxes
- When a stream is updated (e.g. title? game being played?), distribute an `Update` activity to the followers' inboxes
- When a stream ends, distribute a `Delete` activity to the followers' inboxes
- I suggest using a custom object type (not `Event`) because there are livestream-specific semantics I'm sure we'd like to preserve

What this could enable in interested parties is a Twitch-type "who's streaming right now" view for people you are following:

![grafik](https://user-images.githubusercontent.com/184731/102285470-a8efbe00-3f36-11eb-9e2b-00b169b4d7e8.png)

Where when you click on it you go to their owncast page.

I don't think video recordings with comments should be part of this issue.

**Comment by Gargron** [comment]
> I suggest using a custom object type (not `Event`) because there are livestream-specific semantics I'm sure we'd like to preserve

To elaborate, I'd call the object `Stream`, it would indeed have the `startTime` so you could display how long it's been live for, its `url` would point to the page where you can watch the stream / use the chat, it would have a `name`.

I don't know how you'd share the number of current viewers. It would have to be a new attribute. It wouldn't ever be 100% up-to-date but that's probably fine, it doesn't update frequently on Twitch either. You could send an `Update` every 10 minutes or so. In fact that might be a good idea to consider a stream as ended on the consumer end if there is no update in x minutes to prevent zombie streams from being displayed as live after the origin server failed to send a `Delete` for any reason.

**Comment by cjslep** [comment]
In addition to what Gargron has said, I'm also happy to help answer questions, in particular around ActivityStreams/ActivityPub and golang.

**Comment by gabek** [comment]
We had a bit of a chat in the Rocket.Chat today about ActivityPub support.

While I still would like to see some type of abstracted notification interface built so people can built notifications for whatever they want (email, text messages, twitter, Discord, etc etc) those all fall into a "fire and forget" scenario, and could work well under some kind of simple external plugin.

However ActivityPub doesn't really follow the same rules, and is not really a "notification" per se.  It doesn't have a lot in common with those other push channels.

So it feels like building ActivityPub support directly into Owncast can make sense and be a core feature, and "notifications" can still be treated in a simpler way.

**Comment by cjslep** [comment]
Ah, I forgot to include the go-fed chat room, apologies. On Matrix, you can visit `#go-fed:feneas.org` to come discuss questions around using any of the associated libraries.

**Comment by aschrijver** [comment]
As @Gargron says, I think Go-Fed is a good choice. If you develop off of `apcore` you have an all-batteries-included basis that shields you from many of the complexities in federation that are not readily apparent when reading the AS/AP specs. Also a lot of time and attention has been spent to make it easy for integrators to define AP extensions, like the `Stream` object mentioned above. And to subsequently evolve your vocabulary gradually as you add roadmap features to Owncast later on (Kudos, wonderful project, btw!).

I am planning to use Go-Fed myself, and recently created an adaptation of the architecture overview with a bit more detail to it:

![gofed-architecture-concept](https://user-images.githubusercontent.com/5111931/102609492-df425e80-412b-11eb-9784-92ce8ccfda8f.png)

Also I co-maintain the [ActivityPub Watchlists](https://git.feneas.org/feneas/fediverse/-/wikis/watchlist-for-activitypub-apps) (research/input for [fediverse.party](https://fediverse.party)) and - given that your AP integration plans seem solid i.e. are tagged to a release - I can add you to that list. Is there a developer/organization Fediverse account I can mention with that entry?

**Comment by cjslep** [comment]
FYI, I outlined what it would take for Gitea to adopt ActivityPub [here](https://github.com/go-gitea/gitea/issues/14186), and I think a lot of general design points are also applicable to Owncast, though I haven't had the time to investigate the Owncast source in detail.

**Comment by aaronpk** [comment]
What are you thinking about for handling responses to the activities this sends out? I'm guessing people will favorite and reply to those posts if they look like other posts in the timeline. If they look like something else, what's the plan for the receiving end to be able to recognize these as something other than regular posts?

**Comment by marek-lach** [comment]
Useful `Go` libraries that could help with the integration into the Fediverse:

https://github.com/MatejLach/astreams - ActivityStreams 2.0 encoding/decoding for Go

https://github.com/go-ap/activitypub - ActivityPub vocabulary for Go

And for `JavaScript`:

https://github.com/dariusk/express-activitypub - A simple reference implementation in Express.js

https://github.com/immers-space/activitypub-express - Add decentralization/federation to Node apps

**Comment by linux-lukas** [comment]
In my eyes, Owncast could not only enrich the Fediverse with a functioning ActivityPub support, but also represent an (even) better alternative to Twitch.

I could imagine that either the stream information of Owncast could be realised in the Fediverse via the "bot" tag or a separate tag in Mastodon.

**Comment by linux-lukas** [comment]
In addition, Owncast would perhaps become more exciting for content creators to build a presence within the Fediverse.

**Comment by cjslep** [comment]
Congrats! :)
