### ISSUE TITLE
allow customize rtmp port through config.yaml

### ISSUE THREAD

**Issue by pedro-nonfree** [owncast/owncast#467]
looks like right now can only be configured at compilation time https://github.com/owncast/owncast/blob/e9c7ff29cfbcaddb324b019626f4e8037b92f74e/config/defaults.go#L6

**Comment by gabek** [comment]
That shouldn't be the case if you set `rtmpServerPort` in your config.

https://github.com/owncast/owncast/commit/e9c7ff29cfbcaddb324b019626f4e8037b92f74e#diff-fe44f09c4d5977b5f5eaea29170b6a0748819c9d02271746a20d81a5f3efca17R180

**Comment by jeyemwey** [comment]
Hi @pedro-nonfree, we have added support for custom RTMP ports after the v0.0.3 release, so it might not work for you if you're running the release version of owncast.

**Comment by gabek** [comment]
If there's a specific issue with the implementation of how it's in 0.0.4 (master) please feel free to re-open.  I'm going to close for now.
