### ISSUE TITLE
Allow admins to disable the chat

### ISSUE THREAD

**Issue by shirt-dev** [owncast/owncast#472]
Please allow admins to completely disable the chat.

**Comment by gabek** [comment]
We can totally do this.  In the mean time if you really don't want it you might want to edit the web UI (you can edit it directly) and remove it from rendering the chat portion or from connecting to the websocket.

**Comment by sytranvn** [comment]
Admin should be able to enable offline chat as well.

**Comment by gabek** [comment]
While this would make sense to go in with chat moderation, we should just wait until we have a configuration interface where it can be disabled through, so pushing it off until then.

**Comment by gabek** [comment]
Thinking for the first pass at this we'll have to keep the websocket open, since that's how we're counting viewers, but just disable the chat input box and throw away messages if somebody were to pragmatically send them.  It'll be an option once the admin has the ability to configure the server
