### ISSUE TITLE
No location for config.yaml in docker instructions

### ISSUE THREAD

**Issue by cmullins83** [owncast/owncast#479]
Basically what's on the tin.
I followed the documentation instructions:
`Use a Docker image #

    Pull the latest version from Dockerhub: docker pull gabekangas/owncast:latest.
    Run docker run -p 8080:8080 -p 1935:1935 -it gabekangas/owncast:latest to start the service.
 `
But I can't seem to locate the config.yaml in the docker container. What folder should I mount externally to view/edit it?

**Comment by muesli** [comment]
You would typically bind mount the config to `/app/config.yaml` inside the container:

```bash
docker ... -v ./config.yaml:/app/config.yaml
```

Agreed tho, this needs better documentation.

**Comment by jeyemwey** [comment]
I will add a menu item. Where would you get the default config? Just from GitHub?

**Comment by jeyemwey** [comment]
Please check if your fine with my changes.

**Comment by jeyemwey** [comment]
I have merged the pr and will now close this issue. Reopen if you feel like I didn't do justice.
