### ISSUE TITLE
Use Websocket for Status Communication

### ISSUE THREAD

**Issue by graywolf336** [owncast/owncast#48]
Maybe it would be useful to use the websocket connection to be notified of the status updates? Instead of continuously polling?

**Comment by gabek** [comment]
Agreed!  It's been something I've been thinking would be a worthwhile update, but just never filed anything for it.

**Comment by graywolf336** [comment]
I'll see what I can accomplish this week :)

**Comment by gingervitis** [comment]
This sounds good and makes more sense to me too.

Note to self: For the JS refactor, I've moved a lot of the logic around that handles Websocket and messaging functionality.  I'll make sure to keep track of this so I don't freak out when I get a merge conflict!

**Comment by graywolf336** [comment]
@gingervitis if you would like, I can wait until your refactoring gets merged to master? That way it makes things easier for you

**Comment by gingervitis** [comment]
Works for me @graywolf336 . I'm just not sure when I'll finish merging it in. I'm aiming for end of this coming weekend.

**Comment by graywolf336** [comment]
Works for me!
