### ISSUE TITLE
Links in the dockerhub's overview are broken.

### ISSUE THREAD

**Issue by pr0PM** [owncast/owncast#481]
Here: https://hub.docker.com/r/gabekangas/owncast in the overview section
for example
Visit the [Quickstart](https://hub.docker.com/r/gabekangas/doc/quickstart.md) to get up and running.

and many others just need to replace the starting docker part with github's url

**Comment by gabek** [comment]
Thank you for catching this!

**Comment by gabek** [comment]
Updated the Dockerhub readme to match the Github one.
