### ISSUE TITLE
How to stream local media

### ISSUE THREAD

**Issue by cmullins83** [owncast/owncast#482]
It's mentioned in the documentation that you can stream media locally from the server.
But I don't see HOW.

Thanks!

**Comment by jeyemwey** [comment]
Hi, you can use ffmpeg to stream to owncast. We have prepared a test script that you can use on your server, too: https://github.com/owncast/owncast/blob/master/test/ocTestStream.sh

**Comment by cmullins83** [comment]
Thanks jeyemwey, but this doesn't work in the docker container. I think primarily because bash isn't included in the docker image.

**Comment by jeyemwey** [comment]
If you have ffmpeg on your hostsystem, you should be able to run the script on the host.

**Comment by gabek** [comment]
@cmullins83 Were you able to figure out what you needed here?
