### ISSUE TITLE
Rate limit inbound chat messages

### ISSUE THREAD

**Issue by sytranvn** [owncast/owncast#484]
Currently same message can be sent multiple times at unlimited rate (tested on local and demo site). Server should detect and disconnect spam client.
```
// ws = websocket instance
const itId = setInterval(() => ws.send({body:`<img src="123" >`,author:"User 1",type:"CHAT"}), 1)
// Chat go brrrrrrrrrrrrr

// This is for testing only so please `clearInterval(itId)`.
```
![image](https://user-images.githubusercontent.com/13009812/102722728-aaa1f300-4335-11eb-8edc-beedf04588a2.png)

**Comment by gabek** [comment]
Agreed!  Thank you!
