### ISSUE TITLE
Streaming fails under SSH tunnel

### ISSUE THREAD

**Issue by ztgasdf** [owncast/owncast#485]
I have a very interesting case for you.

I am attempting to broadcast video on a firewalled server that is being tunneled through Cloudflare's Argo Tunnel. Here's the environment:

- Server running Ubuntu 18.04.5
- Owncast 0.0.3 running on HTTP 8811 and RTMP 1935.
- SSH being tunneled from the server to Cloudflare, and from there to me, the client.
- I access the tunnel using `cloudflared access ssh --hostname <cloudflare's given hostname> --url localhost:5252`
- Me, the client, connects to the SSH server, while setting up local port-fowarding with `ssh -L 1935:127.0.0.1:1935 root@localhost -p 5252`
- I configure OBS Studio to broadcast to `rtmp://localhost/live` with the streamkey as `abc123`.
- I start streaming, and it connects and instantly disconnects right after.

Here are the logs:

Owncast
```
~# ./owncast
INFO[2020-12-21T00:15:08Z] Owncast v0.0.3-linux-64bit (97a86ec388725f5c867cf88e172a59a71d0baf5a)
INFO[2020-12-21T00:15:08Z] Web server is listening on port 8811, RTMP is accepting inbound streams on port 1935.
INFO[2020-12-21T00:15:08Z] The web admin interface is available at /admin.
INFO[2020-12-21T00:15:19Z] Incoming RTMP connected.
INFO[2020-12-21T00:15:19Z] RTMP disconnected.
```

OBS
```
19:31:05.511: ---------------------------------
19:31:05.511: [x264 encoder: 'streaming_h264'] preset: veryfast
19:31:05.511: [x264 encoder: 'streaming_h264'] settings:
19:31:05.511: 	rate_control: CBR
19:31:05.511: 	bitrate:      2500
19:31:05.511: 	buffer size:  2500
19:31:05.511: 	crf:          0
19:31:05.511: 	fps_num:      30
19:31:05.511: 	fps_den:      1
19:31:05.511: 	width:        1280
19:31:05.511: 	height:       720
19:31:05.511: 	keyint:       60
19:31:05.511: 
19:31:05.513: ---------------------------------
19:31:05.513: [FFmpeg aac encoder: 'adv_stream_aac'] bitrate: 160, channels: 2, channel_layout: 3
19:31:05.513: 
19:31:05.514: [rtmp stream: 'adv_stream'] Connecting to RTMP URL rtmp://localhost/live...
19:31:05.515: [rtmp stream: 'adv_stream'] Interface: Software Loopback Interface 1 (type 24, 1073 mbps)
19:31:06.977: [rtmp stream: 'adv_stream'] Connection to rtmp://localhost/live successful
19:31:07.014: ==== Streaming Start ===============================================
19:31:07.963: WriteN, RTMP send error 10053 (16 bytes)
19:31:07.964: WriteN, RTMP send error 10053 (41 bytes)
19:31:07.964: WriteN, RTMP send error 10038 (42 bytes)
19:31:07.964: [rtmp stream: 'adv_stream'] Disconnected from rtmp://localhost/live
19:31:07.964: Output 'adv_stream': stopping
19:31:07.964: Output 'adv_stream': Total frames output: 9
19:31:07.964: Output 'adv_stream': Total drawn frames: 74
19:31:07.964: Output 'adv_stream':  Reconnecting in 10 seconds..
```

---

As a sidenote, I created a rudimentary nginx rtmp server and I was able to connect to the server and also view the stream.

**Comment by ztgasdf** [comment]
Sorry for the sheer amount of edits, I was messing with the settings of OBS and I was getting different logs.

**Comment by gabek** [comment]
Couple things to help troubleshoot:

* Could you try running with `./owncast --enableVerboseLogging` and share the output of that?
* There should be a `transcoder.log` that gets created.  Could you share that as well?
* As a sanity check, what version of `ffmpeg` is being used?

**Comment by ztgasdf** [comment]
Verbose:
```
TRAC[2020-12-21T00:54:08Z] 0xc00021f680 127.0.0.1:1935 127.0.0.1:43352 Connected
INFO[2020-12-21T00:54:09Z] Incoming RTMP connected.
TRAC[2020-12-21T00:54:09Z] Video transcoder started with 1 stream variants.
TRAC[2020-12-21T00:54:09Z] Inbound stream disconnect requested.
INFO[2020-12-21T00:54:09Z] RTMP disconnected.
```

transcoder.log
```
Unrecognized option 'var_stream_map'.
Error splitting the argument list: Option not found
```

FFmpeg: 3.4.8-0ubuntu0.2
^ I think this is the reason. Let me update it and try again.

**Comment by ztgasdf** [comment]
That was the problem.

Updated FFmpeg to 4.3.1-0york0~18.04 using `ppa:jonathonf/ffmpeg-4` and it works perfectly now. Thank you!!

**Comment by gabek** [comment]
Awesome!  Glad it's working!
