### ISSUE TITLE
Provide config option to use h264_omx codec

### ISSUE THREAD

**Issue by aaronpk** [owncast/owncast#488]
Performance on a raspberry pi 4 can be dramatically improved by having ffmpeg use the h264_omx codec. I was able to test this by changing this line https://github.com/owncast/owncast/blob/master/core/ffmpeg/transcoder.go#L305

It'd be great if one of the config options of the `streamQualities` could be used to enable this codec instead.

**Comment by gabek** [comment]
Great idea!  As you saw, we've hardcoded the codec that we know everyone will have access to, but I really look forward to supporting more codecs going forward.

Were you just able to drop in `h264_omx`, or did you have to change other parameters?  Often the codecs go hand in hand with their specific settings so changing just the name of the codec itself isn't enough to make it work.  But it sounds like with yours it's drop-in compatible.

**Comment by aaronpk** [comment]
Yeah! I just replaced the codec on that line and rebuilt the app on the Pi and it worked great! I have no idea if there is further improvement that could be done with other parameters but this seemed to work well enough for a first pass. Here's the link I found with that info https://www.raspberrypi.org/forums/viewtopic.php?t=256572

**Comment by gabek** [comment]
Awesome, thanks Aaron!

**Comment by gabek** [comment]
As a heads up, it looks like `h264_omx` is deprecated and not supported on new Raspberry Pi hardware.

https://github.com/raspberrypi/firmware/issues/1366

**Comment by gabek** [comment]
Merging this into #336 for supporting multiple codecs.
