### ISSUE TITLE
ublock origin breaks javascript due to filename

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#491]
Somebody posted the following on Reddt:

> One thing I noticed is that the webpage didn't load at all for me at first, which is because uBlock Origin blocks https://watch.owncast.online/js/components/social-icons-list.js (using Firefox 84, but that shouldn't matter).
>
> There's a rule that's part of the "Fanboy’s Social" blocklist that seems to block any filename that contains social-icons-. I'm not entirely sure, but I think that list is part of the default uBlock Origin installation, so for any of those users the site probably also doesn't load.

**Comment by ztgasdf** [comment]
On a fresh uBlock Origin installation, this filter is not automatically enabled.

**Comment by gingervitis** [comment]
For a quick fix we can just rename that file to something less obvious.
