### ISSUE TITLE
[FR] Dynamic Title + Tags

### ISSUE THREAD

**Issue by SeaLife** [owncast/owncast#498]
Hey,

i would like a option to update my stream title and tags without restarting or modifying the configuration.

Updating any other options like description could be updateable too but its most common to update the title and the tags...

I would also like a "Category", but as far as i know, owncast handles categories by tags.
I dont think this is a perfect solution for this yet because u can participate in all categories.

**Comment by gabek** [comment]
Hey there!  This is definitely on the roadmap with our configuration work that's coming up.  I'm going to close this duplicate, but feel free to follow https://github.com/owncast/owncast/issues/304.
