### ISSUE TITLE
Too many tags mess with the mobile layout

### ISSUE THREAD

**Issue by jeyemwey** [owncast/owncast#500]
This streamer has added so many tags that the container gets too wide for the layout on mobile. It is currently not possible to scroll from left to right.

I can only suspect that this will also be an issue on smaller desktop screens or if a steamer adds even more tags.

![Screenshot_20201222-183556.png](https://user-images.githubusercontent.com/2796271/102917082-dbdd0900-4484-11eb-8895-9df2a49b59a7.png)

As a user, I want to see all stream information without having to scroll.

As a streamer, I want to add as many tags as I want without thinking of destroying the web interface.

**Comment by SeaLife** [comment]
Thanks for testing that out with my Stream :D

**Comment by gingervitis** [comment]
Oh thanks for reminding me of this! That's been on my list of things to fix..

**Comment by jeyemwey** [comment]
> Thanks for testing that out with my Stream :D 

I just hopped on it and saw that issue. But due to edge-country, I couldn't see your stream :D
