### ISSUE TITLE
Monitoring - Prometheus

### ISSUE THREAD

**Issue by SeaLife** [owncast/owncast#503]
Hey,

would be neat to monitor a owncast instance with prometheus and grafana...

The basic metrics like HTTP Requests would be neat but also more detailed stuff... Currently i could think of:

- ffmpeg_cpu_usage
- ffmpeg_mem_usage
- viewers
- viewers{country="xxx"} // if GeoIP is installed
- bitrate_video_incoming
- bitrate_video_outgoing
- bitrate_audio_incoming
- bitrate_audio_outgoing
- chat_message_count

Those metrics could also help to identify issues later in a running instance.
They may also help on scaling owncast (if scaling is possible later on) automatically. :)

This could also probably help solving: #78

Regards
SeaLife

**Comment by aaronpk** [comment]
I hooked up my instance to Munin today. It was a small script that parses the admin stats JSON and reformats it as a Munin plugin.

`https://admin:{streamkey}@example.com/api/admin/status`

IMO it makes more sense to keep the monitoring service specific stuff out of the main repo though. Maybe there could be a way to fetch the URL using something other than HTTP basic auth with the streaming key.

**Comment by gabek** [comment]
The topic of metrics collecting have come up a couple times, and I think, in general, the direction we want to head is with some type of plugin or adapter that Owncast can talk to.  Just like Aaron said, having this functionality built into the software itself isn't really a direction I want to go, but the idea of being able to pass this kind of information off to somebody else who has a specific implementation might be a nice solution.  But we haven't yet gone down the road of how these types of specific plugins or adapters might work.

**Comment by SeaLife** [comment]
Okay, i understand that. The way prometheus metrics works in imho default in the "hosting business" and the format of the metrics and how they are collected is used in many softwares and i think, they should be in-built or there should be a plugin maintained by the official owncast team :)

Using a "custom" format for this should be - as proposed - done by a plugin (or something like that). But the format prometheus uses is a industrial standard. :D 

See: https://openmetrics.io/
