### ISSUE TITLE
How to reduce latency?

### ISSUE THREAD

**Issue by xabru** [owncast/owncast#504]
Currently with the default configuration, there is a delay of +10 seconds or more on a local server.

Are there any recommended settings for either reducing the video quality and achieving real time video transmission?

**Comment by gabek** [comment]
Unlike one-to-one WebRTC-based conferencing (Zoom, Jitsi, etc) HLS (one-to-many) video will always have latency and might not be a good fit if you have tight real-time requirements.  But you can experiment trying to reduce it by tweaking some values outlined here: https://owncast.online/docs/troubleshooting/#reducing-the-delay-between-the-viewer-and-live

However, if you're hitting ~10sec now, you might be able to squeeze a couple fewer seconds out of that in your configuration, but it's unlikely you're going to get _too_ much lower.  But setting the length of each video segment to something really small might get you a better result, at the risk of possible buffering if there's any blips.
