### ISSUE TITLE
URL base/root path

### ISSUE THREAD

**Issue by ColonelThirtyTwo** [owncast/owncast#505]
Be able to set a "base" or "root" path that is prefixed to all paths to the site, in routing and link generation.

This is a standard feature of web apps, so that you can host multiple apps on the same domain using a proxy server like nginx to direct to different web apps based on the URL path.

Ex. if I set this to `basePath: "/stream"`, then `localhost:8080/stream` will be the home page, `localhost:8080/stream/admin` will be the admin, freeing up other paths on `localhost` to host other content.

**Comment by gabek** [comment]
Thanks for the suggestion!

**Comment by graywolf336** [comment]
With doing this, we will need to always double check how we are loading content. This is something that we at Rocket.Chat have constantly run into issues with, hosting the instance in a "directory" of the domain. So, if we want to support this officially then we probably need to implement a check/test that ensures nothing breaks before a release happens.

**Comment by Fidgetcetera** [comment]
Just popping in to say that I've spent an entire evening trying to get a reverse proxy in nginx trying to set up owncast in a subdirectory, and this would be a very wanted feature.

**Comment by d1vanloon** [comment]
I think this is still a valid request.

**Comment by gabek** [comment]
I agree, still valid.  There's a PR with some discussion at https://github.com/owncast/owncast/pull/631 that ended up losing some steam, but I don't intend to drop this.

**Comment by ColonelThirtyTwo** [comment]
This is a dealbreaker for me. I need to run other things on my server, and I don't have the ability to set up a subdomain just so that owncast can have its own URLs.

Feels like a really big limitation, especially for something that bills itself as something for personal use by people who don't have the resources to set up a bunch of subdomains.

**Comment by pbsds** [comment]
Most reverse-proxy solutions has the ability to strip a prefix from the url path, but this doesn't work due to owncast linking to its assets with absolute paths (starting with `/`) instead of relative paths.

These are good:

```html
  <link href="./styles/video.css" rel="stylesheet" />
  <link href="./styles/chat.css" rel="stylesheet" />
  <link href="./styles/user-content.css" rel="stylesheet" />
  <link href="./styles/app.css" rel="stylesheet" />
```

But the favicons, logo, json manifest and javascript components all use absolute paths.

**Comment by gabek** [comment]
There was a PR around this, but had many more changes. The discussion kind of got dropped when looking at options: https://github.com/owncast/owncast/pull/631/files

<blockquote><img src="https://avatars.githubusercontent.com/u/22523840?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/owncast/owncast/pull/631">Add support for running frontend on URL paths other than root by rdtq · Pull Request #631 · owncast/owncast</a></strong></div><div>This resolves #505
I tested this and it works great when running on / and also on different path, for example with following Caddy config:
my-owncast-instance.xyz

handle_path /my_secret_path/* {
 ...</div></blockquote>

**Comment by Ruskyy** [comment]
> This is a dealbreaker for me. I need to run other things on my server, and I don't have the ability to set up a subdomain just so that owncast can have its own URLs.
> 
> Feels like a really big limitation, especially for something that bills itself as something for personal use by people who don't have the resources to set up a bunch of subdomains.

I have exactly the same issue.
No idea why they inforce absolute paths. Ends up turning Owncast useless in a lot of usecases..

**Comment by pbsds** [comment]
The alternative is to host it behind a separate domain name. Nginx and traefik is able to route this.

**Comment by BluBb-mADe** [comment]
I think everyone is aware that hosting on a subdomain circumvents this issue but I expect a lot of people don't want to or even can create subdomains. It's a very common strategy to host services like this in subfolders and I don't know of any other contained service that just outright doesn't support it at all.

**Comment by gabek** [comment]
The Owncast web application is being rewritten from scratch, and with that rewrite it should make it more flexible for things like this. However, certain paths will always be required. The admin will expect to live under `/admin`, and hls will be expected to be `/hls`, for example.  If you want paths to be different you either need to edit the source yourself, or use a reverse proxy to rewrite the requests and route them any way you want. The current web app does not allow for this, but the new version should open that up to you. But it's still on you to rewrite your requests.

I understand you want it to work whatever way makes sense to you, but certain paths will always be expected, and you'll have to rewrite them with your proxy if you want them to change. The Owncast web server won't be able to read your mind that `/mysite/coolstream/admin` should be interpreted as `/admin`. But that's what your proxy is for.

Hopefully after the web rewrite you should be able to route your requests through your proxy as needed.

**Comment by BluBb-mADe** [comment]
My frustration with this is the HTML. Expecting a fully-fledged rewrite system integrated into the app is of course ludicrous. 
But even with a proper reverse proxy like Nginx, it is currently not possible to run the app in a URL subfolder at all. It's all about those hard-coded root-relative URLs that are spread across the entire project.
I understand that such a change is not a small endeavor.
In other applications, all URLs are either designed to work relative to the root dir which can of course become quite ugly and hard to reason about but can solve this problem entirely, or the application has a place where you can explicitly specify a prefix which the app then prepends to all URLs in some template generation step or whatnot.
The latter is actually more common in my experience.

**Comment by gabek** [comment]
Closing as this discussion is about the previous web interface. If there are specifics involving the new version that can be discussed.

**Comment by lmaddox** [comment]
tbh I'm not too familiar with subdirs and subdomains. Am I to understand that the correct way to configure the nginx reverse proxy is to have it point to owncast.InnovAnon-Inc.chickenkiller.com?

**Comment by gabek** [comment]
That's correct.

**Comment by ztx-lyghters** [comment]
I don't understand, is there still no way to do this? This is something what is expected from any web-service. I tried to configure it to /stream path in nginx and failed, it gives me 404. And if I open /stream/admin, the config page actually loads, but is all over the place.

I want to host multiple instances for different people on the same server, having a subdomain for each of them is insane

**Comment by gabek** [comment]
There are even more reasons now than there were before why this will not be natively supported. I'd be happy to discuss why, but it seems like nobody is interested in the why, they just want to be angry.

I'm sorry this is disappointing to you, and you believe it to be insane.

**Comment by ztx-lyghters** [comment]
I'm sorry, if that sounded angry. I've spent a lot of time trying to figure this out on my end, as I wasn't expecting it to turn out this way

**Comment by ox64** [comment]
We would absolutely like to know the why.  It's like building a car, but adding no wheels.  Explain why wheels are not on the car, maybe there is a definite reason for it we don't know obviously
