### ISSUE TITLE
Proving decentralized identity with Keyoxide 

### ISSUE THREAD

**Issue by YarmoM** [owncast/owncast#510]
Hey all, here's the issue I promised yesterday to submit.

So, identity. Anyone could start an owncast server and claim it to be mine. To what purpose, I'm not sure yet, different possibilities, but in general, we'd like to be ahead and prevent impersonation from becoming a problem.

What Keyoxide does is give people multiple "online identity reference points" to identify me with, as it proves account "ownership". If Keyoxide confirms I hold this github account and also run an owncast server, then next time you watch a stream on said owncast server, you'll know it's the same person who wrote this github issue (as an example).

All owncast needs to do is have an API endpoint with some field that the user can control. And owncast already has that! What I didn't know yesterday was that owncast perfectly handles "social handles" with platforms that aren't listed here: https://owncast.online/docs/configuration/#external-links.

As an example, my server config now has the following social handle:

```
    - platform: keyoxide
      url: https://keyoxide.org/9f0048ac0b23301e1f77e994909f6bd6f80f485d
```

It gets perfectly displayed (kudos!) and is also fetchable using the /config API endpoint.

So, this isn't an issue and it no longer is a feature request. This is just a confirmation that owncast already is perfectly designed to work with decentralized identity proofs. I will add support for owncast to the Keyoxide project as soon as possible. Perhaps we could one day have a little keyoxide logo appear when adding this social handle ;-)

Congrats again on an awesome project!

**Comment by SeaLife** [comment]
Hey, i dont see, how this helps to identify a stream. 
Especially this Service is not a public well-known service and is mostly developed by yourself (u didnt mentioned that in your text)

I think, a Streamer also has some more social media channels were they could link back to their stream they own.
I would not trust such a service but i would trust their Twitter-Accounts or Facebook-Accounts... 🤔

**Comment by aaronpk** [comment]
Yeah @SeaLife is right, most people are going to not know what keyoxide is, or not care, and instead will just look for a link to Twitter and look at the Twitter account for a link back to the streaming site.

This is also related to #511 which lets websites mark up these links between each other in a way that can be parsed if you really want to have that be machine-readable. But in reality a human-visible link between each profile is going to provide a better user experience for most people anyway.

**Comment by YarmoM** [comment]
Yes, it is mostly developed by me, my bad for not clearly stating that. Keyoxide is part of a larger movement to decentralize the concept of online identity. Adding support for owncast will be beneficial to people who choose to not rely on Twitter, Facebook and other internet corporations to provide online identity. Those people, I imagine, will have a particular motivation to use owncast, else why bother? Just use twitch. Hence my interest.

If you see no reason to "acknowledge" a link back to Keyoxide, all good with me! As I have said above, owncast already provides all that's needed for decentralized identity verification.

Enjoy the holidays!

**Comment by gabek** [comment]
Awesome, I'm glad it works!  There was a request that we should update our social icons sometime in the future, so maybe we can get a Keyoxide icon in there as well next time they're updated :100:

**Comment by gingervitis** [comment]
@YarmoM do you have a Keyoxide icon you can provide us?

**Comment by gingervitis** [comment]
@YarmoM  I added your logo as a PNG with this commit ce3a47d5f414cd4baaa281cedd4900102796c13e..  If you're able to get your hands on an SVG version of it in the future that would work well with @SeaLife's conversions.
