### ISSUE TITLE
"stream already running; can not overtake an existing stream"

### ISSUE THREAD

**Issue by aaronpk** [owncast/owncast#512]
I'm doing some long-running tests of streaming several hours continuously. Occasionally I see this in the logs:

> stream already running; can not overtake an existing stream

The uptime counter resets shortly after those messages appear.

<img width="1020" alt="Screen Shot 2020-12-23 at 8 43 10 AM" src="https://user-images.githubusercontent.com/113001/103019226-53e61600-44fb-11eb-9172-933267517464.png">

This error has happened a few times over the last 24 hours, but not consistently. Sometimes it's after only 90 minutes of the stream being up, sometimes it goes 4-6 hours before the error appears. If you have the web viewer up when this happens, it looks like the stream stops briefly, and then you have to reload the page to get it to play again after the stream starts back up.

I'm streaming from an ATEM Mini Pro to OwnCast which is running in an Ubuntu KVM. Both are on my local gigabit network connected through only one switch, so network bandwidth should be no concern here.

Any ideas of what might be causing this or how to troubleshoot it?

**Comment by SeaLife** [comment]
I streamed with Streamlabs OBS for about 4-6 hours sometimes now and had no issues whatsoever 😟

**Comment by gabek** [comment]
We have streams running for weeks, but we've never used an ATEM Mini Pro, so there might be something specific there.  It sounds like the source is trying to reconnect for some reason.  Are you seeing on your source's side, any disconnections or errors?  Or just as a sanity check, are there any other sources that might be trying to connect at the same time?

Maybe we can find some answers in some logs.  Could you try this?

- Run owncast with `./owncast --enableVerboseLogging` to see if there's anything being logged that might point to any RTMP errors.
- Take a look at the `transcoder.log` .

**Comment by aaronpk** [comment]
I updated to 0.0.5 and did a test stream of about 3.5 hours and I haven't seen this reoccur, so I'm just going to close this issue 😄

**Comment by rcutanda** [comment]
Although this is quite an old thread, I am having the same or a similar issue. I broadcast non-stop (24/7) from OBS 28.1.2 (Windows 11) to Owncast v0.0.12 on a dedicated server and a couple of times a day I get the "_stream already running; can not overtake an existing stream_" error. 

This is my server setup:

Intel(R) Xeon(R) CPU E3-1220 v6 @ 3.00GHz (4 core(s))
Ubuntu 22.04.1 LTS
GeForce GT 710 Drivers 470.141.03  CUDA Version: 11.4 

This is my ffmpeg info:

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared

This is the error and my video setup.

![Screenshot_1](https://user-images.githubusercontent.com/589826/200394728-02f5b01f-9a45-41e6-bb1e-a043e5f04093.jpg)

![Screenshot_2](https://user-images.githubusercontent.com/589826/200394744-90d3da18-820c-4f6d-97f8-6e24ba135918.jpg)

And this is my transcoder.log:

[transcoder.log](https://github.com/owncast/owncast/files/9954738/transcoder.log)

Thank you in advance.
