### ISSUE TITLE
Ran as SSL - Chat is offline

### ISSUE THREAD

**Issue by timololipop** [owncast/owncast#516]
Hey, 

I set up a reverse proxy via nginx to secure it with SSL. But when I now access the Instance with SSL the stream and the admin interface work fine, but the Chat says "Chat offline". When I switch to non SSL everything works perfect. 

Is there a solution?

Thanks.

**Comment by gabek** [comment]
Yup, it's a nginx thing with websockets.  You should be able to find the answer here: https://owncast.online/docs/troubleshooting/#chat-is-disabled

**Comment by timololipop** [comment]
Thank you so much for this prompt answer!

Works fine now, thank you gabek.

**Comment by timololipop** [comment]
Just got another question, where are the files located for the admin panel?

**Comment by gabek** [comment]
The admin is bundled into the application and not built to be editable like the user-facing web frontend is.  But if you have any additions, fixes, suggestions, etc the repo is at https://github.com/owncast/owncast-admin

**Comment by timololipop** [comment]
So no chance to edit e.g. the Logo?

**Comment by gabek** [comment]
Not at this time, sorry about that!
