### ISSUE TITLE
[docs] Provide a basic systemd unit file to run owncast

### ISSUE THREAD

**Issue by SkYNewZ** [owncast/owncast#521]
Add a systemd unit file on installation/running methods for those who do not wish to use Docker and are not familiar with systemd, as an example.
On my own, I'm using:
```
[Unit]
Description=Owncast
After=caddy.service # Because I use Caddy as a reverse proxy in front of Owncast

[Service]
Type=simple
Restart=always
RestartSec=2
User=quentin # owncast specific user ?
Group=quentin # owncast specific group ?
WorkingDirectory=/home/quentin/owncast
ExecStart=/home/quentin/owncast/owncast -enableVerboseLogging

[Install]
WantedBy=multi-user.target
```

**Comment by gabek** [comment]
Would you be interested in writing up a little how-to on setting this up?  We could add that to our documentation.

**Comment by gabek** [comment]
Used this example in the new documentation site.
