### ISSUE TITLE
Option for IRC backend

### ISSUE THREAD

**Issue by Amolith** [owncast/owncast#523]
I really like Owncast but the only thing that's keeping me from using it right now is that it has its own chat system. I've got an IRC server set up with an authentication bot for a couple gaming servers I run along with other nice integrations but switching to Owncast would mean leaving all that behind.

I don't know how feasible it is but I would love to see an option to provide IRC server details and have Owncast's chat pane act as a web IRC client!

**Comment by jeyemwey** [comment]
Hi, thanks for your feedback regarding our chat system. There have been several requests to add other chat backends like Mastodon or Rocket Chat, so yours fits right in. :)

**Comment by gabek** [comment]
There's a few reasons why this isn't feasible.  One big one being chat moderation is just not possible on IRC.  
And if we went all in on IRC, in order for this to be work we'd have to ship Owncast with its own IRC server, and unfortunately that's a non-starter.  And while we could continue to ship with our own chat service _and_ support an optional backend of IRC, it means we'd have to manage two completely separate things, something unfortunately we don't have the resources for.

We will improve and enhance our chat functionality in the future, but one-off integrations into 3rd parties won't be the solution we'll be able to take.

**Comment by Amolith** [comment]
Instead of official IRC integration, would extending the API be more doable? That way, no platform requires explicit support, just someone willing to develop a bot and add whatever cross-moderation features they desire.
