### ISSUE TITLE
Add Ko-fi platform

### ISSUE THREAD

**Issue by CosmicToast** [owncast/owncast#525]
https://ko-fi.com/
It's a patreon-like but with a polar-opposite culture (tip jar by default, as opposed to exchange of regular money for privileges).

I would add it myself, but looking at the code it looks like the primary thing that needs changing is just adding image data to a gif file (and maybe some js/css? I couldn't tell).

**Comment by gabek** [comment]
Yeah!  Do you happen to have a nice quality ko-fi icon we can use?  Otherwise I'm sure we can dig one up.

**Comment by CosmicToast** [comment]
They've got a whole package of assets for this exact purpose!
https://more.ko-fi.com/brand-assets (under "Logos")
they ask that it not be modified, but yeah, as long as it's used verbatim (same as twitter iirc?) it should be fine and as high a quality as you can get

**Comment by gabek** [comment]
Awesome, thank you!
