### ISSUE TITLE
[BUG] - No content loads if an adblock plugin is in use

### ISSUE THREAD

**Issue by Monkman08** [owncast/owncast#529]
As per the title, I am using chrome with the AdBlockPlus plugin. when loading any stream, the page is blank. the only console error is that `/js/components/social-icons-list.js` was blocked

**Comment by jeyemwey** [comment]
Hi, thanks for the heads-up! We have fixed this in #491 for the stream page. Have you encountered the problem at an other page than the stream landing page?

**Comment by gabek** [comment]
Closing as it's been resolved in #491.
