### ISSUE TITLE
Add standalone chat with ability to send messages

### ISSUE THREAD

**Issue by Jeglet** [owncast/owncast#531]
With a standalone chat, you could have the stream fullscreen on one display, while still having the chat open separately on a different display or device

**Comment by aaronpk** [comment]
This would also open up the possibility of being able to have the person streaming overlay the chat into the livestream itself. I do this with YouTube chat using a browser extension that restyles the popout chat window. https://github.com/aaronpk/live-chat-overlay

**Comment by gabek** [comment]
> This would also open up the possibility of being able to have the person streaming overlay the chat into the livestream itself.

I'm not sure if this works for your specific use case, but the standalone chat embed was added with this in mind.  https://owncast.online/docs/embed/#embedding-chat

**Comment by aaronpk** [comment]
That's awesome. I can probably adapt my browser extension to work with this too!

**Comment by clohfink** [comment]
embedded chat doesnt give ability to send messages though, its read only

**Comment by gabek** [comment]
Yeah, I was just responding to Aaron.  I understand these are completely different use cases.

**Comment by jeyemwey** [comment]
I think, @aaronpk´s remarks go rather in the direction of #532 ?

**Comment by gabek** [comment]
Wanted to add some clarifications around this for the future.

Keep in mind this is for somebody embedding into another web page to use as a chat component, not as a live stream overlay or any kind of read-only view into chat.  It would need to be fully featured.

1. It should probably be a completely new component and layout that is better suited for embedding and allow for some amount of styling by the person embedding it.
2. A complete chat re-work is taking place right now, so the access flow, events and actions are all going to look different, so we need to get through that before working on this would make sense.
3. We'd have to find a way for people to change their name. Right now that UI lives outside of the actual chat component, so if you were to embed chat as it is you'd get the messages and the input but no way to change your name.

That being said, if this feature is interesting to anybody and wants to work on it, now is a good time to start brainstorming what it would look and act like.

**Comment by Jeglerjeg** [comment]
Sorry if this is noise, but I just want to clarify.
This would still allow a viewer to open owncast.url/chat or similar and use it as a fully featured and functioning chat, while not being embedded, correct?

**Comment by gabek** [comment]
Right now the chat embed `/embed/chat` purposefully hides the input bar, so if anybody wanted to work on this all they might have to do is add support to toggle that depending on if the person embedding it wants it read-only or fully functional.

**Comment by MFTabriz** [comment]
@gabek I’m thinking about how to implement this. The way I see it, lots of code from `app.js` will need to be added to the `app-standalone-chat.js` to handle the username, activation/deactivation of the chat, etc. What is the best approach here to avoid code duplication?

**Comment by gabek** [comment]
ahh yeah forgot about user name stuff living outside of the chat component.  It's easy enough to abstract the logic into shared modules, but I think the challenge here is the name change UI, since it exists outside of chat.  So we'd need some different version of it that works within an embed component.  Maybe @gingervitis can mock a design something up at some point, but given how few people would use this feature I wouldn't want to take her away from other things to work on it.

**Comment by gingervitis** [comment]
Hey @MFTabriz thanks so much for looking into this!

UI-wise, everything visually we care about lives in js/components/chat. (user name change, chat panel + message input). `app-standalone-chat.js` can handle the markup of where to put these components relative to each other, and then we can create and/or override some css from `standalone-chat.css`.

As for the duplicated stuff, those seems to mostly web-socket oriented? Perhaps we'll need to abstract out the `async setupChatAuth` set up and the `handleWebsocketMessage` types handling into something somewhat re-usable, but then again, there will still need to be some delicate app-level state management and declaration of how to handle web socket events specific to this chat only context. Some things will be reasonably duplicated in that sense, and I don't think it's worth the effort to try and fully prevent us from doing so.
