### ISSUE TITLE
Embedding chat endpoint counts as a viewer

### ISSUE THREAD

**Issue by geekgonecrazy** [owncast/owncast#537]
Related to this discussion: https://github.com/owncast/owncast/discussions/374

But if you open the embedded chat view a few times it counts as viewers because we count websockets.

So lets say for a streaming setup we use one for OBS to show on stream and then bring up on ipad or another display dedicated for chat.  We now have 2 fake viewers that aren't consuming the stream at all :)

**Comment by gabek** [comment]
True!  Maybe we can pass something with the websocket connection saying it shouldn't be counted by the system.
