### ISSUE TITLE
Directory doesn't supports IPv6 only instances

### ISSUE THREAD

**Issue by Jaedotmoe** [owncast/owncast#543]
Greetings,
When I'm starting my owncast instance, I'm getting this message in the console:
```
time="2020-12-29T18:10:29Z" level=warning msg="YP Ping error returned from service: Get https://ip6.jae.moe/api/yp: dial tcp [2a01:e0a:14f:5230:fabc:12ff:fe31:97fe]:443: socket: address family not supported by protocol"
```
As my instance (ip6.jae.moe) is served and accessible uniquely through IPv6, it seems that the directory doesn't supports it.

**Comment by gabek** [comment]
Unfortunately the provider I'm hosting the directory at doesn't yet support ipv6.
