### ISSUE TITLE
Document + script how to backup the owncast.db database

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#549]
Since everything is moving to `owncast.db` it's going to be a much more important file.  We should help people back it up.  We should write a simple little script that people can run and document how to run it.

In theory we should use the actual `.backup` command within the sqlite cli, but not everyone will have sqlite installed.  There may be downsides to just making copies of the db due to locking.

**Comment by geekgonecrazy** [comment]
I wonder if instead we should add an api endpoint.  That spits out a .sql file?  Kinda like I think discourse does via their admin interface. 

That way we could perform lock with the actual only client reading from file and we can actually lock

**Comment by gabek** [comment]
I like that idea.  Will we have to format the SQL output ourselves?

**Comment by geekgonecrazy** [comment]
I didn't even think about that.

https://github.com/schollz/sqlite3dump/blob/master/dump.go

Looks like fairly straight forward to generate though.

**Comment by gabek** [comment]
Nice! :+1:

**Comment by gabek** [comment]
I have the backup in, but no way to restore it.  So halfway there.
