### ISSUE TITLE
No default content.md file and adding one does not update the text here

### ISSUE THREAD

**Issue by AtriLahiji** [owncast/owncast#550]
![image](https://user-images.githubusercontent.com/15067795/103390473-da898d00-4ad1-11eb-8610-58105bed96fe.png)

I added the file to webroot/static. No luck. This is on the latest release and using the one-click install I built for cloudron here: https://git.cloudron.io/AtriLahiji/owncast-app

**Comment by gabek** [comment]
Sorry about that, put it in `data` and you should be good to go next time you restart your server.

**Comment by AtriLahiji** [comment]
No worries, thanks for the quick reply. I guess it was changed from what the documentation said. On the note of my one-click app: cloudron has a read only directory we usually try to put code in. Which directories, to your knowledge, require write access? I was hoping to symlink the ones that need write access to a writable directory so people can configure things where needed while securing the rest of the app.

**Comment by gabek** [comment]
What documentation was wrong? We'll get that updated.

There's a few directories that are written to.

hls, webroot/hls, data and the root dir.  It also uses the system's temp directory.

**Comment by AtriLahiji** [comment]
Thanks!

And for the documentation: https://owncast.online/docs/website/
![image](https://user-images.githubusercontent.com/15067795/103398093-572f6200-4af8-11eb-850a-883029561c45.png)

**Comment by gabek** [comment]
Thanks!
