### ISSUE TITLE
ffmpeg not found should show in regular logs

### ISSUE THREAD

**Issue by geekgonecrazy** [owncast/owncast#554]
> DEBU[2020-12-31T20:53:36Z] Unable to determine path to ffmpeg. Please specify it in the config file.

This should show in regular logs and not only just debug logs.  I couldn't figure out why my stream wouldn't start on a new vps.. Turns out it was this.  But would be more helpful if showed in regular log output

**Comment by gabek** [comment]
It should actually be fatal, since there's not much you can do without it.  Not sure why I set it to be debug.

**Comment by geekgonecrazy** [comment]
🙏 awesome
