### ISSUE TITLE
Outbound webhooks for 3rd party integration

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#556]
Primary events that most 3rd parties would care about at first.

- [x] Stream started
- [x] Stream stopped
- [x] Chat message sent

Secondary events that they probably care about less.

- [x] Message visibility changed (from moderation)
- [x] Username changed

We should probably create some kind of "user joined" event, but our chat doesn't have that yet.  Easy enough to add, though.

**Comment by geekgonecrazy** [comment]
Awesome!  Thanks for creating here!  Beat me to summarizing.  

The idea working on so far is allowing specifying as many webhooks as you want and specifying the type of events it will receive.

The yaml file getting a section like:
```
webhooks:
- url: https://something
   events:
   - userJoined
   - messageSent
   - visibilityToggled
   - usernameChanged
```

Would love to hear feedback.  🙏

**Comment by aaronpk** [comment]
I like it! That's actually very similar to how I [define webhooks for my IRC bot](https://github.com/aaronpk/TikTokBot/blob/master/hooks.example.yml)!

**Comment by geekgonecrazy** [comment]
Oh that’s awesome! After playing around on stream a bit and getting it working, this felt right.  Glad this is a familiar pattern

**Comment by gabek** [comment]
@geekgonecrazy Do we want to make a verification secret a built-in part of our webhook implementation?  Something that's generated when adding a new webhook and sent along with each request?

**Comment by geekgonecrazy** [comment]
Hm.. I think actual secret will be taken in url and who knows how it'll be excepted or if the user will have control over it. 

But.. a signing secret would be interesting.  That way could sign and the receivers would know it for sure came from owncast.  I was thinking something like that for down the road.  But for minimum seems un-needed.
