### ISSUE TITLE
Inbound "send message" API for 3rd party integrations

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#557]
We'll want an endpoint where an authorized bot/3rd party can send new messages to the Owncast chat.

We have two different types of chat messages, the standard chat and the `system` chat message.  I feel like 3rd party bots should be able to send messages as either.

Here's an example use case of a bot sending a system message.

1. User clicks on a "donate" link on the Owncast page.
2. They make a donation via a payment processor.
3. Payment processor sends an event to the 3rd party bot.
4. 3rd party bot generates a message that should be displayed in the chat and posts it to the new API.
5. Chat shows, with the "system" chat appearance, this new message, showing everyone who donated.

Remains to be seen what "authorized" means.

**Comment by geekgonecrazy** [comment]
To me simplest solution is: add way for admin to generate api tokens in the admin ui.

**Comment by gabek** [comment]
Yeah, I think so too.  Just a simple token generator.

And as a heads up, I know for development of the outbound webhooks you're using the config file, but the deprecation of the config file is already in motion, so it's likely that'll be a part of the admin UI too soon.  So we'll have to build a UI for adding webhooks.  /cc @gingervitis :D

Luckily I think that's a simple'ish one.  A text field for the URL and some checkboxes to select event scopes.
