### ISSUE TITLE
Add "user joined" chat event

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#558]
1. When user connects to the websocket send a "joined" event from the client along with the current username.
2. Set the username with the client like you would on a name change or chat message sent.
3. (maybe) send a message back to all clients saying "X joined".
4. Send webhook that X user joined.

**Comment by SeaLife** [comment]
Hey,

i think, this would probably bother the stream too much if there a a) many viewers joining/leaving per minute and b) if a user refreshes the page, he can spam that event?

Regards :)

**Comment by gabek** [comment]
This is less about the chat UI and more about registering current users/usernames with the chat service and 3rd party webhooks.  I'm not really all that interested in the message in the chat itself saying somebody joined, and I don't know if we should have it or not.  It's probably fine either way.

**Comment by geekgonecrazy** [comment]
Maybe we reduce the noise here by only sending of a username has been set by the users. If just using auto generated then we don’t say anything?
