### ISSUE TITLE
Add admin page to documentation

### ISSUE THREAD

**Issue by kaffeeringe** [owncast/owncast#560]
I called /admin and was asked for username and password. I looked in the documentation what the login is. Either I missed it, or it's not there. I guessed it might be the stream-key and admin. That worked. Maybe put that into the docs somewhere. Or is it a test? :-D

**Comment by kaffeeringe** [comment]
Oh sorry. There it is: https://owncast.online/docs/quickstart/ Down at the bottom...

**Comment by jeyemwey** [comment]
Have you found everything that you needed?

**Comment by kaffeeringe** [comment]
Yes. Thank you!
