### ISSUE TITLE
Make chat and stats available as docks in OBS

### ISSUE THREAD

**Issue by kaffeeringe** [owncast/owncast#561]
It would be great if the stats an the chat had their own urls so I can add them as docks in OBS.

**Comment by jeyemwey** [comment]
You grab the status information from the public api, if this helps? https://owncast.online/api/latest/#tag/Server/paths/~1api~1status/get

If you want to embed incoming chat messages in your stream, check out this part of our documentation: https://owncast.online/docs/embed/#embedding-chat

**Comment by kaffeeringe** [comment]
Thank you! The chat works like a charm in OBS.
