### ISSUE TITLE
VirtualDJ: When disconnecting from RTMP Owncast says it's still connected

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#564]
Reported in chat: https://owncast.rocket.chat/channel/general?msg=shdFAJMAhRuiHR9nr

This is specific to the VirtualDJ application, it's reported that when you disconnect Owncast doesn't go into an offline mode.

**Comment by gabek** [comment]
Just downloaded VirtualDJ and was able to reproduce this.

**Comment by Jerlag01** [comment]
update on this, as I reported it in chat back then. It's solved thanks

**Comment by gabek** [comment]
It's hopefully resolved in 0.0.6, but real-world testing will tell.  Please report back if you're still experiencing issues as admittedly VirtualDJ isn't something we hear about often.
