### ISSUE TITLE
Custom S3 metadata for playlist files (CDN caching)

### ISSUE THREAD

**Issue by mattdsteele** [owncast/owncast#567]
Now that we're serving playlist files from S3, they're subject to similar storage and caching rules as anything else we upload into a bucket. But since we frequently upload new playlists (while the `.ts` segments are essentially immutable), we need ways to optimize the cache TTL, so CDNs know how frequently they need to refresh files from the bucket.

The goal should be to always request fresh playlist files from the bucket, while the segments can live on the edge for long periods.

In particular I'm running into this with DigitalOcean's Spaces, along with their built-in CDN. It's possible to [set a global cache TTL on the bucket](https://www.digitalocean.com/docs/spaces/how-to/manage-cdn-cache/#ttl), but none of the values are particularly useful for playlists (the minimum TTL is 1 minute; which isn't great either for playlists or media files IMO)

It's possible to [set a custom TTL](https://www.digitalocean.com/docs/spaces/how-to/set-file-metadata/) on a file by setting a metadata value when uploading to S3 (the `x-amz-meta-max-age` key, with a value in seconds).

One way to resolve this might be to add a new configuration property in the s3 space that lets the user add arbitrary S3 metadata elements. Maybe something like:

```yaml
s3:
  playlistAttributes:
    - x-amz-meta-max-age: 0
```

Before starting to put a fix together I wanted to get another set of eyes on the problem. How are others managing CDN-fronted playlist files? Is there a more general approach I should look at?

**Comment by gabek** [comment]
I wonder if we can use the existing way we determine cache duration and just always explicitly set it in that `x-amz-meta-max-age` when uploading?  https://github.com/owncast/owncast/blob/master/utils/utils.go#L115

Do you know if that's a standard piece of metadata?  Or would each user have to figure out the specific way caching is handled on their provider of choice?  I can't imagine if people had to manually add their own arbitrary S3 upload tags things would go well, and we can't test and document it for every provider.

**Comment by geekgonecrazy** [comment]
Maybe if `servingEndpoint` is set we treat as cdn in front?  Then if so provide this header on upload?  

Letting people set any header feels like something that would go wrong.  🙈

of the s3 providers documented I don’t think many of them have a cdn product along side them right?  So probably really DigitalOcean and s3/cloudfront.

**Comment by mattdsteele** [comment]
Some cursory Googling, it looks like Cloudfront uses a `Cache-Control` metadata element with a `max-age=0` value. https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Expiration.html#ExpirationAddingHeadersInS3

Other CDNs have their own ways of determining how to pull; CloudFlare lets you customize via patterns, and KeyCDN has a "[Live Streaming](https://www.keycdn.com/blog/hls-streaming)" mode you can enable.

So it doesn't look like there's any standard :(

**Comment by gabek** [comment]
> of the s3 providers documented I don’t think many of them have a cdn product along side them right? So probably really DigitalOcean and s3/cloudfront.

Unfortunately I think we're looking at a scenario where we'd have to support an infinite combination of storage + CDNs.  If somebody waned to use Fastly as a CDN and B2 for storage we'd have to know what pieces of metadata Fastly specifically uses for caching, and then how to set it on B2.

I know for Cloudfront there's a way to set caching behavior using their control panel.  That seems like the answer to me, I don't think we can support infinite combinations of storage and CDNs, and we certainly don't want to just give people a text field to type arbitrary headers in that they'll screw up.

I don't know the solution to your specific issue, but it doesn't feel like an Owncast specific problem to solve.  If you replaced Owncast with any other web product what would the solution be?  Would the vendor have to build in support for all of these caching specifics?  I feel like something is missing, but I'm not sure what.

**Comment by geekgonecrazy** [comment]
How hard would it be to have query params passed if using cdn?  So that it would act as cache busting

something like:

```
s3:
  cdnPlaylistCacheBust: true
```

Then fetching the playlist something like name.m3u8?hls=1

some field and property that is sequential so would be known by owncast to point to next.  Keeping it cached so any two pulling same iteration of the playlist get the cached copy.

if I had to guess this is why if you peak at twitch’s the next playlist is always some-random-hash-or-id.m3u8

**Comment by mattdsteele** [comment]
I was also hoping we could treat cache busting as something external to Owncast; similar to how we expect folks to expire old S3 objects manually (though we document it for S3 [here](https://owncast.online/docs/s3/#file-expiration-1)).

DigitalOcean does happen to have a means to configure CDN expiration per-file via its dashboard, but it gets overwritten when the file gets overwritten during an update; so we can't rely just on documentation.

I'm starting to agree that a brute-force approach to cache busting might be best.

We actually have some code to add a `?cachebust=${date}` query param to HLS requests, but it doesn't seem to be getting triggered anymore:

https://github.com/owncast/owncast/blob/master/webroot/js/components/player.js#L62-L66

I can look into what's going on there.
