### ISSUE TITLE
Chat Moderation: Toggle visibility of a single message

### ISSUE THREAD

**Issue by jeyemwey** [owncast/owncast#568]
To improve the speed of blocking incoming messages, it would be helpful if we could toggle the visibility of a single chat message right in the row.

I propose these icons at the end of the line, where the Stop icon is shown now:

![image](https://user-images.githubusercontent.com/2796271/103457409-721ff300-4cff-11eb-9db3-f8e392cda1ff.png)

**Comment by gabek** [comment]
The original version of this screen had a single click to hide messages and I found it confusing that there were two completely different ways to hide a row.  It wasn't clear to me what the connection between the checkbox and the per-row hide button was.  I think it's much clearer now that it doesn't matter how many messages you want to hide, it's always the same flow.

**Comment by geekgonecrazy** [comment]
I wonder if we can find a middle ground somewhere?  Cause for me unless being abused.. Mostly always would be finding the message and hiding it.  For multi message it's great.. single message it feels a bit cumbersome to have to use the select process

**Comment by gingervitis** [comment]
Haha. Ok ok, I'll try to add the eye/crossedout-eye as a button at the end of the row when I next get a chance.

**Comment by geekgonecrazy** [comment]
Oddly I can’t even think of someone doing it well or allowing bulk hide like this.  So can’t even use them as example of doing well as inspiration.  🙈

**Comment by gabek** [comment]
Merged into admin.
