### ISSUE TITLE
Chat height calculation fails on iPads

### ISSUE THREAD

**Issue by jeyemwey** [owncast/owncast#572]
When watching a stream with an iPad, I cannot type chat messages. The keyboard lays over the chat input.

The issue gets worse if you have multiple tabs open and exists on both landscape and portrait orientation. I'm using iOS 14 and the Safari Browser.

**Comment by thilobillerbeck** [comment]
I just investigated a little bit and found out, that using `vh` in mobile safari seems to be a common problem. I found a solution by placing the relative to `right` and `bottom` instead of `top` and `right`. Fix is coming soon.
