### ISSUE TITLE
Support dynamic port for HLS file writes

### ISSUE THREAD

**Issue by jeyemwey** [owncast/owncast#577]
https://github.com/owncast/owncast/blob/176861645b32534328048156e9ab79b1e615df1c/core/ffmpeg/fileWriterReceiverService.go#L37

A friend asked me what we use the 8081 port for and I didn't even know that we do use it.

We should document the usage of this port and maybe allow the user to change the port if necassary.

**Comment by gabek** [comment]
We should just hard code some ridiculously high port number that is unlikely for other things to use.  I don't want to add more configuration for this.

**Comment by jeyemwey** [comment]
We can also try to bind port 0, then the host system will assign a random port that is not used by another service: https://gist.github.com/xcsrz/538e291d12be6ee9a8c7

**Comment by geekgonecrazy** [comment]
Oh I like that!  Then there is no need to ever worry about collision as will always be something not used.

**Comment by gabek** [comment]
Yeah, we do need to know what that port is so we can actually connect to it.

**Comment by geekgonecrazy** [comment]
Based on that gist we would programmatically know:

```
listener, err := net.Listen("tcp", "127.0.0.1:0")
if err != nil {
	panic(err)
}
fmt.Println("listening on", listener.Addr().String())
```

so you’d have ip and actual port dynamically assigned:

https://play.golang.org/p/AF4XzzF7pUN

**Comment by gabek** [comment]
Oh nice.  We'll have to save that in the config, so this can be more stuff to get done as we re-work the config.
