### ISSUE TITLE
Crash in performanceTimer: concurrent map writes

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#578]
We need to be locking this when writing.

https://nextcloud.w0rmh0le.net/index.php/s/pAwz8ZHgKncRarD

**Comment by geekgonecrazy** [comment]
https://github.com/owncast/owncast/blob/master/utils/performanceTimer.go#L19

likely would need mutex.

Though i'm wondering if better solution isn't to implement prometheus and then just use the metrics it collects.  Because it takes care of all of that already
