### ISSUE TITLE
Where do you set the port number when you start

### ISSUE THREAD

**Issue by fenglijunnb** [owncast/owncast#580]
I did not find the location of the corresponding port number, please kindly explain it in detail

![image](https://user-images.githubusercontent.com/48191768/103504148-81cf4100-4e91-11eb-93e8-4495eb66ef85.png)

**Comment by jeyemwey** [comment]
Hi, we use this port (Webserver port +1) for our communication with ffmpeg. As you complain, it is not well documented. There is an issue for this: #577
