### ISSUE TITLE
Immediately disconnects after incoming RTMP stream

### ISSUE THREAD

**Issue by iRaven4522** [owncast/owncast#582]
When running OC on a Raspberry Pi 3B, incoming streams from OBS fail to connect.

I run a stream (720p@30fps in this case) to the program, it connects for a split second then disconnects. Owncast then crashes and throws out an error like the following (copied from terminal):

`INFO[2021-01-04T01:53:50-06:00] Owncast v0.0.4-linux-arm7 (cd77eab9714fe9d430b8944aab4baafd906aeb4c)
INFO[2021-01-04T01:53:51-06:00] Web server is listening on port 8080, RTMP is accepting inbound streams on port 1935.
INFO[2021-01-04T01:53:51-06:00] The web admin interface is available at /admin.
INFO[2021-01-04T01:53:52-06:00] Incoming RTMP connected.
INFO[2021-01-04T01:53:53-06:00] RTMP disconnected.
panic: write /tmp/streampipe.flv: file already closed

goroutine 52 [running]:
github.com/owncast/owncast/core/rtmp.HandleConn(0x28e2000, 0xd91b10, 0x22d2078)
        /go/src/github.com/owncast/owncast/core/rtmp/rtmp.go:124 +0x520
github.com/nareix/joy5/format/rtmp.(*Server).HandleNetConn(0x27e41c0, 0xd91b10, 0x22d2078)
        /go/pkg/mod/github.com/nareix/joy5@v0.0.0-20200712071056-a55089207c88/format/rtmp/server.go:75 +0x25c
created by github.com/owncast/owncast/core/rtmp.Start
        /go/src/github.com/owncast/owncast/core/rtmp/rtmp.go:64 +0x2a8
pi@raspberrypi:~/owncast $

This does not happen when I do the same thing on a Mac system and no customized OBS settings are set.
The file referenced (/tmp/streampipe.flv) is fully accessible by the pi user (as it owns it).

I'm not experienced in UNIX and can't find much about this on researching. Could be a bug (can't reproduce with Mac OS as said.)

**Comment by gabek** [comment]
Could you try running with verbose logging enabled?

`./owncast --enableVerboseLogging`

**Comment by iRaven4522** [comment]
Did it shortly after I posted but not much else. 
pi@raspberrypi:~/owncast $ ./owncast --enableVerboseLogging
INFO[2021-01-04T02:03:56-06:00] Owncast v0.0.4-linux-arm7 (cd77eab9714fe9d430b8944aab4baafd906aeb4c)
TRAC[2021-01-04T02:03:56-06:00] Resetting file directories to a clean slate.
TRAC[2021-01-04T02:03:56-06:00] Transcoder response listening on: 127.0.0.1:8081
TRAC[2021-01-04T02:03:56-06:00] Firing transcoder with offline stream state
TRAC[2021-01-04T02:03:56-06:00] Video transcoder started with 1 stream variants.
DEBU[2021-01-04T02:03:57-06:00] Your instance can be listed on the Owncast directory at http://directory.owncast.online by enabling YP in your config.  Learn more at https://directory.owncast.online/get-listed.
INFO[2021-01-04T02:03:57-06:00] Web server is listening on port 8080, RTMP is accepting inbound streams on port 1935.
INFO[2021-01-04T02:03:57-06:00] The web admin interface is available at /admin.
TRAC[2021-01-04T02:03:57-06:00] Web server running on port: 8080
TRAC[2021-01-04T02:03:57-06:00] Starting the websocket listener on: /entry
TRAC[2021-01-04T02:03:57-06:00] RTMP server is listening for incoming stream on port: 1935
TRAC[2021-01-04T02:03:57-06:00] GeoIP support is disabled. visit http://owncast.online/docs/geoip to learn how to enable. open data/GeoLite2-City.mmdb: no such file or directory
TRAC[2021-01-04T02:03:06-06:00] 0x3a8c000 192.168.1.51:1935 192.168.1.3:53970 Connected
INFO[2021-01-04T02:03:06-06:00] Incoming RTMP connected.
TRAC[2021-01-04T02:03:06-06:00] Video transcoder started with 1 stream variants.
TRAC[2021-01-04T02:03:06-06:00] [Type AMF0 Time 0 Len 403 Data ["@setDataFrame","onMetaData",{"duration":0,"fileSize":0,"width":1280,"height":720,"videocodecid":7,"videodatarate":2500,"framerate":30,"audiocodecid":10,"audiodatarate":160,"audiosamplerate":48000,"audiosamplesize":16,"audiochannels":2,"stereo":true,"2.1":false,"3.1":false,"4.0":false,"4.1":false,"5.1":false,"7.1":false,"encoder":"obs-output module (libobs version 26.1.0)"}] Header ]
TRAC[2021-01-04T02:04:07-06:00] Inbound stream disconnect requested.
INFO[2021-01-04T02:04:07-06:00] RTMP disconnected.
panic: write /tmp/streampipe.flv: file already closed

goroutine 51 [running]:
github.com/owncast/owncast/core/rtmp.HandleConn(0x3a8c000, 0xd91b10, 0x3010008)
        /go/src/github.com/owncast/owncast/core/rtmp/rtmp.go:124 +0x520
github.com/nareix/joy5/format/rtmp.(*Server).HandleNetConn(0x3934040, 0xd91b10, 0x3010008)
        /go/pkg/mod/github.com/nareix/joy5@v0.0.0-20200712071056-a55089207c88/format/rtmp/server.go:75 +0x25c
created by github.com/owncast/owncast/core/rtmp.Start
        /go/src/github.com/owncast/owncast/core/rtmp/rtmp.go:64 +0x2a8

Tried it again just now and it doesn't crash, however still immediately disconnects the connection like any other time (same log, minus the panic error). This goes on and off too (sometimes it crashes; sometimes not.)

**Comment by gabek** [comment]
Could you also share what's in the file `transcoder.log`?

**Comment by iRaven4522** [comment]
Unrecognized option 'var_stream_map'.
Error splitting the argument list: Option not found

**Comment by gabek** [comment]
Ah ha.  You might be running an old version of ffmpeg.  Could you update it?  https://owncast.online/docs/troubleshooting/#misc-video-issues

**Comment by gabek** [comment]
3.2.15 is lower than the 4.1.5 listed: https://owncast.online/docs/troubleshooting/#misc-video-issues

**Comment by iRaven4522** [comment]
FFmpeg was the problem and it took a while to update it, however streams work as expected now. I probably broke some things apt-wise however that's irrelevant.
Thanks for the help. :)

**Comment by gabek** [comment]
Awesome, glad it's working!

**Comment by fenglijunnb** [comment]
@gabek Excuse me, this OBS client to push the stream program did not crash, but has been broken

![image](https://user-images.githubusercontent.com/48191768/103751099-ba624c80-5042-11eb-9b7f-1fc06dbec231.png)

**Comment by fenglijunnb** [comment]
@gabek 
![Uploading image.png…]()

**Comment by gabek** [comment]
Could you provide more detail?  Is this the same issue?  If not, would you mind opening a new issue so we can help you troubleshoot it?

**Comment by fenglijunnb** [comment]
@gabek  ok
