### ISSUE TITLE
Non-admin streaming secrets

### ISSUE THREAD

**Issue by deluxghost** [owncast/owncast#586]
I have an owncast instance for my friends, I would like every friend can stream (not at the same time, of course), but only I can access the admin panel. None of them can make port forwarding work.

My thought is to support multiple secrets, but only one has the admin role, others are stream-only. Or, any better idea?

**Comment by gabek** [comment]
I'm inclined to say we probably won't be making any changes to support this type of scenario anytime soon.  It's mostly a single-user server, and while there's nothing stopping you from sharing it with others, we don't have any plans to create different identities for streaming vs. administration purposes. 

If I had to come up with a solution I'd probably do some trickery with an HTTP proxy (that might be doing SSL anyway) and block the `/admin` from everyone except your personal IP or something.

Sorry about that!
