### ISSUE TITLE
Verify version of ffmpeg at launch

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#587]
Just like we check to make sure ffmpeg actually exists, we should also add a check to make sure the version is recent enough.  Would solve problems like #582.

**Comment by graywolf336** [comment]
What's a version that is considered recent enough?

**Comment by gabek** [comment]
We put 4.1.5 in our [documentation](https://owncast.online/docs/troubleshooting/#misc-video-issues) and that seems to have been working well for everyone.

**Comment by gingervitis** [comment]
On a related note, since there'll be a field in the Admin for the path to ffmpeg, could we also verify that path name on submission and return an error if it fails?

**Comment by gabek** [comment]
Absolutely.

**Comment by aaronpk** [comment]
I don't think this is actually working. I did a new install of OwnCast on a machine with ffmpeg 3 and it never threw any warnings in the admin interface or console.

**Comment by gabek** [comment]
Unfortunately it works if it's able to determine the version, but we've found ffmpeg to be oddly difficult to get the real version number of.  So the messages have been demoted to verbose logs because it was just confusing people.

For example one version of ffmpeg on my machine is "4.3.1-static" and another is "version N-100730-g2c424d9630".  So until I can find a more reliable way to get this information, it's likely not as helpful as I hoped it would be.

For future reference, was was the version string for the 3.x.x version you were originally having issues with?

**Comment by aaronpk** [comment]
ah that's too bad. Well I've lost my console logs now and it's upgraded so I don't have the old one anymore. It was whatever the default from Ubuntu 18.04 is though, and I do remember it showing something like `ffmpeg version 3.x.x-.....` in the console.
