### ISSUE TITLE
[Bug] Pinch zooming on mobile Safari seems to affect the responsive site behavior

### ISSUE THREAD

**Issue by thilobillerbeck** [owncast/owncast#594]
As this screen recording shows, pinch-zooming on devices like an iPad seem to trigger some responsive chat-view behavior, which makes it impossible to zoom into the stream description for example.

https://user-images.githubusercontent.com/7442383/103780133-e080f000-5034-11eb-9d09-85b3eb138d6b.mp4

**Comment by gingervitis** [comment]
I wonder if we can do something about that in the `viewport` meta tag to prevent the pinch/zoom on mobile? (if that's what we'd want to do)

**Comment by thilobillerbeck** [comment]
I'll start working on this. 👍

**Comment by gabek** [comment]
Awesome, thank you, @thilobillerbeck!
