### ISSUE TITLE
Instance continues to ping the YP API after stream has ended

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#600]
Only seen this happen once, with @graywolf336's instance.

It logged `Inbound stream disconnect requested`.  It kind of points to some non-clean disconnect that ultimately doesn't stop the YP logic.

**Comment by graywolf336** [comment]
And I am probably the only one who uses restream 😬

**Comment by jeyemwey** [comment]
Would this be solved with https://github.com/owncast/owncast/commit/2b81fcef53b951540fe498bf28f839d3ae461894 ? This commit introduces a timeout if the RTMP stream ends ungracefully, or after a bad video mixer like VirtualDJ or restream does not disconnect like they should.

**Comment by gabek** [comment]
In @graywolf336's case his server did show as offline, unlike the VirtualDJ scenario where Owncast still was showing as online.  And as far as I know it's not reproducible, it only happened once.  So it might fix it, but I'm not sure how we'd know.

**Comment by gabek** [comment]
I think I'm seeing this happen with another instance.  So I believe it to still be a problem.
