### ISSUE TITLE
Example starter code for 3rd party integrations

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#601]
We should provide some example projects to show how to use our 3rd party APIs.  This includes the outbound webhooks and the inbound chat APIs w/ access tokens.

See the milestone for the pieces included to make all this work: https://github.com/owncast/owncast/milestone/11

These can be anything, but should probably be useful things so people can see the possibilities.

- Should be small in scope.
- Can be in any language.  More languages the better!
- Should be easy to run so people can test it themselves.  Glitch is a good option for Node apps so in that case they wouldn't even need a server.
- We can create an official repo of example code, but people can keep it in their own as well as long as we have links to it.

Some ideas:

- Chat bot that responds to commands (!8ball -> Return a magic 8 ball response).
- Tip jar.
- Stream overlay (emoji wall, popup events).
- Follow page where you put in your email and/or phone number and get notified when you go live.  Can have feedback via an overlay that says "Thanks X for following!"
- Notify via your Fediverse/Twitter/etc account when you go live.
- Post to the chat when a song you're playing on your stream changes (Bandcamp, spotify, etc)

Maybe somebody could even make a video of building a basic integration.  @geekgonecrazy has video of him building webhooks, but that's a lot to watch to learn how it works :)

But really it can be anything.

**Comment by geekgonecrazy** [comment]
https://github.com/geekgonecrazy/livestream-banana-bot

Here is a video walking through it https://youtu.be/1bAfwBwdbKg

**Comment by gabek** [comment]
I think @nebunez is going to play around with the 3rd party APIs this weekend.  If what we have as far as existing examples and documentation is clear to him when experimenting then I think we can say we're probably in a good enough place for this first pass.
