### ISSUE TITLE
If you add more than one webhook the events are empty

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#611]
If I only add one it's fine, but the second one never saves the events associated to it, so it never fires.

**Comment by gabek** [comment]
I'm no longer able to reproduce this.

**Comment by gabek** [comment]
This is still happening, but I couldn't reproduce it before.  But Yarmo could.

**Comment by gabek** [comment]
@geekgonecrazy Have you seen this happen to you?

**Comment by geekgonecrazy** [comment]
I saw something like this happen when I first tried this branch.  But I saw it when I wasn't yet live.  I don't know if related or not

**Comment by gabek** [comment]
I think I tracked this down.
