### ISSUE TITLE
Timeout limit

### ISSUE THREAD

**Issue by RickoDean** [owncast/owncast#622]
I think it would be cool if we could adjust how long the system stay running before it timeout or shutdown.

For example: in my environment, I run the command to start the server, I use it and after a while the server port closes and I am forced to run terminal code again to stream again.

**Comment by gabek** [comment]
This could be a pretty straightforward thing to do yourself.   Using the [`timeout`](https://www.man7.org/linux/man-pages/man1/timeout.1.html) command you could limit owncast running to an hour:

```
timeout 1h ./owncast
```

But in general I don't think this is something that we would want as a part of the software itself, sorry about that!
