### ISSUE TITLE
VirtualDJ - invalid streaming key; rejecting incoming stream

### ISSUE THREAD

**Issue by pns2050** [owncast/owncast#625]
Hello,

Just came across owncast today - great work.

I was able to start streaming with OBS in no time. 

With VirtualDJ for some reason, I get the following error: "invalid streaming key; rejecting incoming stream"

It is probably related to how the key is extracted from the URL below, but this is the first time that I read Go code. I also couldn't find where an access.log is being stored to check out the structure of the incoming request https://github.com/owncast/owncast/blob/594722d44796d9ca55e634642e70ff3959159397/core/rtmp/rtmp.go#L82

I did try broadcasting on the available demo page but it fails to connect

**Comment by gabek** [comment]
Does VirtualDJ allow you to put in a stream key?  If not you can add it to the url: rtmp://your.server/live/yourkey

**Comment by gabek** [comment]
I just downloaded and tested VirtualDJ and verified I was successfully able to connect to my owncast instance and stream.

**Comment by gabek** [comment]
<img width="1542" alt="Screen Shot 2021-01-13 at 8 28 21 PM" src="https://user-images.githubusercontent.com/414923/104546265-a7babb00-55e0-11eb-927b-347168192dd7.png">

**Comment by pns2050** [comment]
Ok that's weird , I installed owncast on a digital ocean ubuntu droplet using the install.sh , could we have a different setup?

Can you also broadcast on the demo running at https://watch.owncast.online/ ?

![image](https://user-images.githubusercontent.com/6561841/104548019-90a7b780-5638-11eb-8d10-067679499cc7.png)

**Comment by gabek** [comment]
It does work on the broadcast demo server.

However, regardless of this you probably still don't want to use VirtualDJ with Owncast because this issue is very much a thing: https://github.com/owncast/owncast/issues/564.

I only downloaded virtualdj today so I'm just now testing it.

**Comment by gabek** [comment]
![image](https://user-images.githubusercontent.com/414923/104548895-9b396100-55e6-11eb-84e8-2c2386a96aa3.png)

**Comment by pns2050** [comment]
Thank you for taking the time to look into it @gabek. I figured out what I was doing wrong. If I use rtmp://domainname/live instead of rtmp://domainname:1935 it connects successfully. OBS works with both urls

**Comment by gabek** [comment]
Awesome, glad it's working!  Keep in mind #564.
