### ISSUE TITLE
"TypeError: Cannot read property 'time' of null" in admin interface

### ISSUE THREAD

**Issue by aaronpk** [owncast/owncast#635]
I just updated to version 0.0.5, and when I'm in the admin interface, a few seconds after I start streaming, the console fills with this error:

> TypeError: Cannot read property 'time' of null

<img width="556" alt="Screen Shot 2021-01-15 at 8 21 17 AM" src="https://user-images.githubusercontent.com/113001/104752041-04b29000-570b-11eb-92d2-4576ff1c1334.png">

**Comment by gabek** [comment]
Thanks for letting us know.  This happens every time you visit the admin and you're streaming?

**Comment by aaronpk** [comment]
Yeah I tried clearing the cache and everything too. If I load the admin dashboard when the stream is stopped it loads fine, then I start streaming, and the crash happens right when it looks like the admin dashboard is about to update to show that the stream started.

**Comment by gabek** [comment]
I've asked around to see if other people are seeing this so it can be looked into, but nobody else is experiencing it.  I'll keep an eye out for it, but as of now it's nothing anybody else (that I've asked) is experiencing.

**Comment by aaronpk** [comment]
Thanks, I restarted the server a few times and it hasn't happened since

**Comment by aaronpk** [comment]
Spoke too soon... it's happening again, same problem

**Comment by gabek** [comment]
@nebunez If you happen to see how this might be happening while poking around the admin, maybe we can fix it.

**Comment by gabek** [comment]
@aaronpk Next time you see this, could you post the contents of `/api/admin/status` (remove anything that's sensitive).

**Comment by aaronpk** [comment]
it happened again!

```json
{
"broadcaster": null,
"online": true,
"viewerCount": 2,
"overallPeakViewerCount": 5,
"sessionPeakViewerCount": 0,
"versionNumber": "0.0.5",
"disableUpgradeChecks": false
}
```

**Comment by gabek** [comment]
I wish I could properly troubleshoot this, it seems to be something specific with this RTMP client not sending the tags that are expected to be sent.  It's not something I've seen in other environments.  I put in a patch that will hopefully work around this exception in the UI, but I'm not sure if other things will creep up.  Time will tell!
