### ISSUE TITLE
Add additional 3rd party APIs

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#638]
With people experimenting with the 3rd party APIs it seems like there's use cases for things and people are using the admin APIs to fill that gap.

We should officially support, as 3rd party APIs, things people want to do, and allow them to be used with the access tokens, so the admin apis, secured by the stream key, don't have to be used.

Please chime in with your suggestions!

**Comment by DaneAlex** [comment]
I think I'd like to start with the following being accessible via the access token integration:
- Toggle message visibility (bots can auto moderate messages this way)
- Get current connected users/clients (raffle/giveaway type commands)
- Stream Title (allow bots to edit stream title)
- Get Chat Messages history (mod type bots could use this)

**Comment by gabek** [comment]
TODO: Stream title.  That'll get added when the real stream title property gets added with the data/config rework that's happening now.
