### ISSUE TITLE
Do not log websocket unexpected disconnects as errors

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#639]
We should log them as debug messages instead.

![image](https://user-images.githubusercontent.com/414923/104856327-ef826080-58c6-11eb-83d9-c5fb76d94096.png)

**Comment by petersveter108** [comment]
Hello! I'd like to work on this one, could you please assign me? :)

**Comment by gabek** [comment]
Thanks for the help, @petersveter108!  Let me know if you have any questions.
