### ISSUE TITLE
Add encryption to stream

### ISSUE THREAD

**Issue by ihubgit** [owncast/owncast#646]
Hi, kudos for this project, which fills a gap in self hosting RTMP server and not relying on privacy-enemies such as YT, Vimeo etc...
This being said, in order to promote and preserve privacy and security, it seems an absolute must to me to (be able to) add encryption on top of the livestream, especially when streaming either private or confidential streams.
This ought to be a priority IMO. Thanks for taking this into consideration.

**Comment by jeyemwey** [comment]
There has been a [PR that uses Traefik as a TLS wrapper](https://github.com/owncast/owncast/pull/608). In addition, many many people use a HTTPS wrapper like nginx or Caddy for the public frontend.

I'm not sure, if Owncast should get in the business of dealing with certificates, cert authorities and everything thats around that. There is good software for it, and our knowledge is limited. Quite contrary, a "bad" implementation from us, who don't know what they are doing, might result in greater security problems than if we refer to other, "good" software that wraps Owncast.

**Comment by aaronpk** [comment]
I've deployed this with nginx in front handling the HTTPS certificates and even making users authenticate to view the stream, and I'm firmly in the camp of handling this at that layer rather than building in all the cert stuff into this project.

The other place to add encryption would be the RTMP stream ingestion, but IMO that's not actually super important.

**Comment by ihubgit** [comment]
yea, but that adds quite a burden for the ordinary end user really... I mean, how could a non geek ever add SSL to Owncast?

**Comment by aaronpk** [comment]
> yea, but that adds quite a burden for the ordinary end user really... I mean, how could a non geek ever add SSL to Owncast?

I don't think a non-geek is expected to be installing Owncast from scratch in the first place 😉

There's plenty of use cases that don't require HTTPS at all, such the public livestreams done on YouTube/Twitch that Owncast is clearly targeting. If you do need a private stream, I don't see anything wrong with adding that as an external layer or finding another solution. 🤷 

I'm a big fan of keeping complexity out of the core whenever possible.

**Comment by gabek** [comment]
Closing this as "add encryption to stream" can mean many different things.  Web server SSL, inbound TLS around RTMP, DRM of the segments, etc.  I agree with the above, there are tools for the job that makes more sense.  But as always, if there's enough demand for a specific request we can re-address.  Right now this is vague and not a place to be putting effort.

**Comment by ihubgit** [comment]
What could be possible without too much hassle IMO is to implement TLS for the incoming and outgoing streams (RTPS protocol). Maybe I made myself clearer now.
A quick search on Github shows a project that allows just for that :
https://github.com/aler9/rtsp-simple-server#encryption
It's basically allowing for self-signed SSL certificates.
As it's open source, couldn't you guys simply reuse (part of) the code ? That'd give you a significant head start ...

**Comment by thraeryn** [comment]
> I've deployed this with nginx in front handling the HTTPS certificates and even making users authenticate to view the stream [...]

I'm curious if this still works. Sure, I can set up `auth_basic` either in the `server` or `location` block of my .conf file for the site; that goes to heck as soon as I attempt to log in to the admin interface, as my .conf file has the lines
`proxy_set_header   Authorization $http_authorization;
proxy_pass_header  Authorization;`

...which passes the unhelpful auth_basic info to the admin, as far as I understand it. Can I take those lines out? If I do, will authorizing for admin still work, or will the admin panel simply break?

**Comment by gabek** [comment]
Make sure the admin is being passed the correct `HTTP Basic` headers, and not overwriting them with something else. Add new auth to `/` to be whatever you want, but make sure the auth to `/admin` matches your admin username and password.
