### ISSUE TITLE
Possibility to select quality from web player

### ISSUE THREAD

**Issue by pierreozoux** [owncast/owncast#655]
For ecological reason (or finance, or..) user might want to select themself the quality (like in Youtube).

**Comment by gabek** [comment]
You're not the first person to ask for this, and I see no downsides if it were to be added.  I know there are videojs plugins to help facilitate this kind of thing, but many of them are old and don't work, but maybe it's a start if anybody wants to help with this.

**Comment by gabek** [comment]
In case anybody starts looking into this: https://github.com/silvermine/videojs-quality-selector/issues/61 doesn't work with HLS.

**Comment by gabek** [comment]
https://github.com/chrisboustead/videojs-hls-quality-selector/issues/8 seems to be a decent option, except they describe video qualities by resolution and not by bitrate, and I think most people will use different bitrates more often than different resolutions.  Not sure if there's a way to hack that.

**Comment by gabek** [comment]
I looked into this, and it did what I expected.  Unfortunately it only lists unique _resolutions_.  And while I forked the plugin to edit edit what it shows as a description of a variant (bitrate instead of resolution), the video js quality integration will only surface unique resolutions, so it doesn't really matter what we list in the menu.

Multiple libraries would have to be forked and changed in order to make this work for us.

**Comment by aaronpk** [comment]
tbh I think people will be more likely to recognize the different resolution options compared to different bitrates. It makes sense for software to switch between different bitrates automatically, but if it's going to be a manual option, I think it's fine if it's limited to different resolutions.

**Comment by gabek** [comment]
The problem is many (if not most) people leave the resolution as is, and only change the bitrate.   If you have three 720p variants at different bitrates it will only show a single option, 720p.

**Comment by gabek** [comment]
Thinking about this, it would probably make sense to build our own from scratch, bypassing trying to auto-name things based on resolution and/or bitrate.

1. When you add output variants you give each a description.  They could use generic names like high, medium, low or HD and SD.
2. The player pulls the list of descriptions via a new API.
3. We display the descriptions in a custom player quality selector.
4. The player changes to the variant of the index you selected in the selector.

**Comment by gabek** [comment]
Made some progress on this.  It's not pretty, but I think it'll be polished up for 0.0.7.
