### ISSUE TITLE
Tweaks to offline state of admin viewers page

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#662]
To add clarity let's make the following changes to the admin viewers page, since certain things don't make sense if a stream is not currently online and active.

1. Hide Viewers table if the stream if not live.
2. Hide the "Current Viewers" statistic box if not live.
3. Change the text of "Peak viewers this session" to "Peak viewers last session" if not live.
4. Change text of "Peak viewers overall" to "All time max viewers".  (Anybody have a better phrase to describe the max number of viewers that has ever been seen on a server?)

https://github.com/owncast/owncast-admin/blob/master/pages/viewer-info.tsx

**Comment by gabek** [comment]
@nebunez Would you be interested in looking at this?  Just some small admin tweaks.

**Comment by nebunez** [comment]
I'll take this one, thanks @gabek

**Comment by gabek** [comment]
Awesome!

**Comment by gabek** [comment]
Updated by @nebunez.
