### ISSUE TITLE
Add paywall / Coupon access to stream

### ISSUE THREAD

**Issue by n3myy** [owncast/owncast#667]
Be great to see paywall option to join the stream Or if easier, a Code/Coupon code option to allow access if they entered the code correctly.
Once gained access, their IP get whitelisted to a file so they can re-visit the stream if need to refresh etc. Easily removed later date when stream is done. 

A use-case example:  Live music events can be ticketed, allowing viewers to pre-purchase a 'ticket' (code) to view the live event. Or purchase live access on the night through paywall using paypal or stripe.

Love your work, keep it up!

**Comment by aaronpk** [comment]
I requested a much simpler version of this in #489 just to do a simple password protected stream. Honestly I think something more complex around a ticketing system would be much better served by handling that in an external project and putting OwnCast behind an authenticating reverse proxy. I'm using [Vouch](https://github.com/vouch/vouch-proxy) for that right now just to get a simple password dialog, but you could do whatever you want in the proxy, keeping that logic out of the actual video player itself. I'm also planning on creating some a registration system that I'm going to integrate with Vouch for a similar use case although not with payments integrated. I just am a big fan of handling all that very use case specific stuff at a different layer keeping the content delivery part of it separate.

**Comment by gabek** [comment]
Yeah, it's unlikely this very specific implementation is something we'd ever want in the core software.  Something more general like a password protected stream could be useful to a wider group, but for this use case above it's best, like Aaron said, to either put a proxy that is specifically for that functionality in front of Owncast, or embed your Owncast video into a page or platform that does validation and authorization.
