### ISSUE TITLE
Extend keyboard controls

### ISSUE THREAD

**Issue by thilobillerbeck** [owncast/owncast#670]
Since the user now has the ability to pause and play the video (#579) by pressing the "Space" key, I think it's a good idea to expand on that and introduce more keyboard controls. Some examples would be:

- Mute (M)
- Fullscreen (F)
- Volume (unsure, but maybe use arrow keys or numbers / numblock)

In addition, media keys could be included, which are less common on normal keyboards, but could aid the accessibility entertainment devices like home theatre PCs.

**Comment by thilobillerbeck** [comment]
Since I already worked on the "Space" key part, I think I'll work on this issue as well.

**Comment by gabek** [comment]
Awesome, thank you!
