### ISSUE TITLE
buggy `backtick` rendering in chat messages

### ISSUE THREAD

**Issue by gingervitis** [owncast/owncast#675]
- Messages sent with words wrapped in backtick quote characters (&grave;code&grave;) should render with monospaced text like `code`. Instead they come back with no formatting.
- When sending multiple backticks in a row (&grave;&grave;&grave;), the word `undefined` gets printed out instead.

**Comment by gabek** [comment]
My guess is three backticks gets interpreted by the backend as invalid markdown and then returns back an empty string, and then our chat message formatting logic doesn't like the emptiness.
