### ISSUE TITLE
Put new "stream title" somewhere that makes sense in the web app

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#677]
There's a temporary spot for it right now, but I'm not sure where it should go.  This is kind of a @gingervitis thing.

**Comment by gabek** [comment]
@gingervitis To try it out I put the stream title in the header of the web app, and then when/if it gets cleared it uses the existing server title.  Not sure if that's a good idea or not, but I kind of like the idea of the stream title being in the forefront.

**Comment by nebunez** [comment]
I would get rid of the auto-clear of stream title--let it last as long as the user wants. I also think the title looks good in the webapp where it is now. However, I think the title should be hidden in the webapp when the channel is offline.

**Comment by gabek** [comment]
Closing this as @nebunez tweaked it to hide when offline. And unless @gingervitis is unhappy with how it looks in the header I think it's fine.
