### ISSUE TITLE
3rd party actions + content modal

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#679]
When talking about 3rd party integrations, the logical next step is to have a simple way for developers to display their UI within the Owncast interface after pressing some kind of button that's linked to a 3rd party action.

## Example flow

1. Owncast server admin registers an external url that has UI for 3rd party addons via the Admin.  For example: "Tip Jar" action and optionally an external image that the 3rd party developer provides to use as the button.
2. The new button shows up somewhere in the main Owncast UI stating it's the "Tip Jar" action.
3. When a user presses the button it displays a in-app modal that loads that action URL as an iframe.
4. The 3rd party UI for tipping is displayed in this modal and the user can go through whatever 3rd party flow, or close the modal.

The MVP of this would open the action URL in a new tab instead of in a modal.

## Things required to make something like this work

1. New admin functionality to register external URLs that can be navigated to as actions.  I think this would look a lot like the webhooks screen.
2. A place for 3rd party actions to show up in the Owncast interface.
3. An in-app modal that loads external URLs.

**Comment by gabek** [comment]
The Twitch equivalent to these buttons would be the "Follow" and "Subscribe" buttons.

![image](https://user-images.githubusercontent.com/414923/106534967-0a013000-64aa-11eb-8f3f-d672da4a8a7e.png)

**Comment by brown7477** [comment]
I like this..

**Comment by gabek** [comment]
Still a ways off, but here's my first pass on just the frontend modal that's statically added.

![image](https://user-images.githubusercontent.com/414923/108416377-789cf800-71e3-11eb-95ed-064dd55860b8.png)

**Comment by brown7477** [comment]
This is Awesome. Owncast is going to be incredible. It already is, but it's going to have a huge WOW factor.
