### ISSUE TITLE
Lay out the stream title input field

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#684]
- [ ] Right now it's a tiny box in a very wide header.
- [ ] It breaks the live stream timer on the right when live.
- [ ] The "Submit" button is out of place.  Do we want a submit button here at all?  Or just hit enter to save it?  

![image](https://user-images.githubusercontent.com/414923/106843786-b2a2c180-665b-11eb-9dd8-7ae86c3b33b3.png)

**Comment by gingervitis** [comment]
commit f779abd5b01e41067b5ce866afd178016662c701 fixes this.

<img width="520" alt="image" src="https://user-images.githubusercontent.com/9563255/106930769-c1748d00-66ca-11eb-9a59-6efc8f229b2d.png">
