### ISSUE TITLE
Testing: Verify migration to 0.0.6 works with your config file

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#685]
- [ ] Verify your existing config file is seen as migrated and moved to `backup`.
- [ ] Verify your custom video settings are reflected in the admin and used when streaming.
- [ ] Verify your name, summary, tags, etc are reflected in the admin and show up on your page.
- [ ] Verify your custom page content markdown is reflected in the admin and show up on your page.
- [ ] Verify social links are reflected in the admin and show up on your page.
- [ ] Verify your S3 configuration is reflected in the admin and is used when streaming.

**Comment by nebunez** [comment]
- [x] Verify your existing config file is seen as migrated and moved to backup.
- [ ] Verify your custom video settings are reflected in the admin and used when streaming.
- [ ] Verify your name, summary, tags, etc are reflected in the admin and show up on your page.
- [X] Verify your custom page content markdown is reflected in the admin and show up on your page.
- [X] Verify social links are reflected in the admin and show up on your page.
- [ ] Verify your S3 configuration is reflected in the admin and is used when streaming.

- I got this `WARN` during upgrade:
`WARN[2021-02-20T13:26:03-05:00] open data/logo.svg: no such file or directory`
- My logo is replaced by the owncast logo and I had to re-upload and set it.
- Server URL for directory did not migrate
- I don't fully undersatnd how my config settings translate to the new latency buffer slider--it was set to default after upgrade.
- One of my stream output Video bitrates is "Same as source", which is correct, but I realize now there is no "Same as source option in the admin config"
- Title did not migrate, I got this `PANIC` during upgrade:
```
PANI[2021-02-20T13:49:40-05:00] template: metadata.html:7:18: executing "metadata.html" at <.Config.Title>: can't evaluate field Config in type controllers.MetadataPage    
2021/02/20 13:49:40 http: panic serving [::1]:60204: &{0xc000144c40 map[] 2021-02-20 13:49:40.077746612 -0500 EST m=+1417.569075667 panic <nil> template: metadata.html:7:18: executing "metadata.html" at <.Config.Title>: can't evaluate field Config in type controllers.MetadataPage <nil> <nil> }                                                   
goroutine 156 [running]:
net/http.(*conn).serve.func1(0xc0001f2fa0)
        /usr/local/go/src/net/http/server.go:1801 +0x147
panic(0xedd4a0, 0xc0004f3420)
        /usr/local/go/src/runtime/panic.go:975 +0x47a
github.com/sirupsen/logrus.(*Entry).log(0xc0004f33b0, 0x0, 0xc00002c7e0, 0x88)
        /home/tehj/go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:259 +0x2e5
github.com/sirupsen/logrus.(*Entry).Log(0xc0004f33b0, 0x0, 0xc000a91710, 0x1, 0x1)
        /home/tehj/go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:285 +0x86
github.com/sirupsen/logrus.(*Entry).Logln(0xc0004f33b0, 0xc000000000, 0xc000a918b0, 0x1, 0x1)                                                                               
        /home/tehj/go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:375 +0xd6
github.com/sirupsen/logrus.(*Logger).Logln(0xc000144c40, 0x0, 0xc000a918b0, 0x1, 0x1)
        /home/tehj/go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/logger.go:292 +0x7e
github.com/sirupsen/logrus.(*Logger).Panicln(...)
        /home/tehj/go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/logger.go:333
github.com/sirupsen/logrus.Panicln(...)
        /home/tehj/go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/exported.go:264
github.com/owncast/owncast/controllers.handleScraperMetadataPage(0x136b520, 0xc000a54620, 0xc000d37300)                                                                     
        /var/www/owncast/controllers/index.go:115 +0x97d
github.com/owncast/owncast/controllers.IndexHandler(0x136b520, 0xc000a54620, 0xc000d37300)                                                                                  
        /var/www/owncast/controllers/index.go:44 +0x2f3
net/http.HandlerFunc.ServeHTTP(0x11eb358, 0x136b520, 0xc000a54620, 0xc000d37300)
        /usr/local/go/src/net/http/server.go:2042 +0x44
net/http.(*ServeMux).ServeHTTP(0x1816f40, 0x136b520, 0xc000a54620, 0xc000d37300)
        /usr/local/go/src/net/http/server.go:2417 +0x1ad
net/http.serverHandler.ServeHTTP(0xc000bf80e0, 0x136b520, 0xc000a54620, 0xc000d37300)
        /usr/local/go/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc0001f2fa0, 0x136f720, 0xc00019cc00)
        /usr/local/go/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2969 +0x36c
```
- After running a test stream I get spammed with the following `ERROR` consistently:
`ERRO[2021-02-20T14:14:14-05:00] Unable to generate thumbnail: open hls/1: no such file or directory`
  And, the `PANIC` from above came back a few times.
- I am listed on the directory (after putting my stream url back in manually), but there is no video thumbnail and my custom logo is not shown.
- After ~9min of testing a stream I got the following `WARN`, then my stream was no longer on the directory:
`WARN[2021-02-20T14:21:54-05:00] YP Ping error returned from service: invalid yp key for the provided instance https://live.w0rmh0le.net`

**Comment by gabek** [comment]
Wow, what a mess.  I've migrated config files probably 100 times going between versions and I've never seen anything like this.  I'm going to grab a copy of your config so I can find out what's going on.

**Comment by gabek** [comment]
I think I fixed the `metadata.html` crash you listed above.  Thanks for noticing it!  It's something that would only be seen in a public instance that gets scraped by bots.

**Comment by gabek** [comment]
As far as I can tell from people who have migrated to 0.0.6 things seem to work.  So I'm closing this unless something specific comes up.
