### ISSUE TITLE
Long stream keys break the admin dashboard

### ISSUE THREAD

**Issue by jeyemwey** [owncast/owncast#696]
I'm not sure if this is still online upstream, but this bug appears on the `v0.0.5` release. My stream key is 60 chars long and does not seem to wrap. (I dont even know what would be the right design decision here).

![image](https://user-images.githubusercontent.com/2796271/107088974-22e94880-67fe-11eb-8eb3-39aa60cb45b0.png)

**Comment by gabek** [comment]
No longer an issue with 0.0.6.

**Comment by jeyemwey** [comment]
Thanks for checking!
