### ISSUE TITLE
Chat not working with Cloudflare

### ISSUE THREAD

**Issue by Mxnuuel** [owncast/owncast#710]
Either the Chat goes randomly offline or if it's online it looks like it's a read only mode and can't submit any messages.
![grafik](https://x.mxnuuel.de/QHsOfIz.png)

**Comment by gabek** [comment]
Are there any errors in the browser console?

**Comment by Mxnuuel** [comment]
![grafik](https://x.mxnuuel.de/oxjAdWH.png)
this is what i've got, don't know how to fix that

**Comment by jeyemwey** [comment]
It looks like your ssl proxy does not relay Websocket to the owncast server. Since you're using Cloudflare (from the HTTP headers), you might need to configure stuff on their side?

**Comment by Mxnuuel** [comment]
question would be how then

**Comment by jeyemwey** [comment]
I'm not familiar with anyone who uses Owncast with Cloudflare, nor do I have knowledge of Cloudflare. According to [their docs](https://support.cloudflare.com/hc/en-us/articles/200169466-Using-Cloudflare-with-WebSockets), it should work though. If you find anything out, please share your findings.

**Comment by gabek** [comment]
Looking at the browser on the above server the websocket connection in the browser seems to actually be throwing a 404:

```
Error during WebSocket handshake: Unexpected response code: 404
```

If you go to https://live.lemres.de/entry it should give you a message saying you can't just connect to a websocket directly in a browser.  For example it should look like this: https://watch.owncast.online/entry.

So not only does proxying look like it's not working correctly, but it seems to not be proxying that path *at all*.

**Comment by gabek** [comment]
Hey @Mxnuuel, have any luck troubleshooting this?  Is there anything we can do to help?

**Comment by Mxnuuel** [comment]
Sorry for the long wait!
According to @gabek it is a nginx error that i currently not know how to connect that to the backend. If anyone has a idea how to configure nginx for that i would appreciate some help.

**Comment by gabek** [comment]
It's unclear what's going on with your particular setup.  You have both Cloudflare and NGINX in the mix, but only the websocket URL isn't being routed properly.  I wish I could help, but I'm a little confused what's going on.

I suggest simplifying your setup to find what the problem might be.

**Comment by gabek** [comment]
Closing as it doesn't seem to be an Owncast issue.  Please re-open if there's anything we can do.
