### ISSUE TITLE
Color customization

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#722]
I personally had to change color in source files and a minified CSS file to match "our" colors.

From Admin Dashboard
- Change colors simply with HEX and alpha (Only front-end for viewers is important)

**Here's our example**
[https://live.uddaaktier.com/](url)

_Originally posted by @SonnyBrotherman in https://github.com/owncast/owncast/discussions/721_

**Comment by gabek** [comment]
Closing this in favor of #718, a way to dump some CSS in the admin for overrides.

**Comment by ClundXIII** [comment]
I would actually prefer this as a simple way, especially for people who don't know any `css`. Maybe additionally to #718.
