### ISSUE TITLE
Admin help page topics are being truncated at one line

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#730]
![image](https://user-images.githubusercontent.com/414923/108025012-8b90ac00-6fda-11eb-8090-400f136d84ab.png)

**Comment by gingervitis** [comment]
That's somewhat by (current) design.  If the text was allowed to wrap then you'd get boxes of varying heights which might not look as organized.  But I guess it's not really a big deal right now and readability is more important here.

**Comment by gabek** [comment]
I'll just change the text to make it fit one line.  No biggie.
