### ISSUE TITLE
Admin tables: "No Data" image makes no sense.  Let's replace it with something.

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#735]
The default image for the "No Data" state for tables in the admin is some kind of empty inbox.  It makes no sense for us.  Let's replace it with something, anything, that isn't so weird.

**Comment by gingervitis** [comment]
What, you don't like an empty box?
I think that icon is built into Ant-design's Table component when data=[]. 

If we want to replace it, we'll have to update the data flow in many areas, with code like
```
if (!data.length) {
 return <BetterNoDataThing />;
}
return <AntTable data={data} />;
```

**Comment by gabek** [comment]
Maybe I'll build a wrapper at some point.  Super not important for now.

**Comment by gingervitis** [comment]
I hid the icon with some ant-override css.
https://github.com/owncast/owncast-admin/commit/c6f704c396bae340a5da008f0bfe71d66aa1e09b
