### ISSUE TITLE
[bug] chat not scrolling with images

### ISSUE THREAD

**Issue by compufox** [owncast/owncast#739]
i've noticed that when the chat has a lot of image links pasted into it it resolves the image (which is nice and good!) but it prevents the chat from automatically "sticking" to the bottom of chat unless a new message containing only text is sent

this may not be an issue for bigger streams, but for someone with single digit viewers who don't chat too often it can be a pain.

**Comment by MFTabriz** [comment]
We do not support the image previews in the chat anymore but it is still happening with the emojis.

![Animation](https://user-images.githubusercontent.com/39205857/126909335-f61fbee5-c2a3-4025-8d7e-d7b6b91d44fc.gif)

**Comment by gabek** [comment]
Closed with #1324.
