### ISSUE TITLE
Admin video variant modal: on error loader keeps spinning

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#780]
1. Open video variant edit modal
2. Make some change that will cause a server-side error
3. Error is returned and the loading spinner on the "Ok" button continues to spin, stopping you from fixing the error until you reload the page.

This was discovered when trying to remove the scaled width/scaled height values and it was throwing an error.  In a perfect world we wouldn't experience any server-side errors because we're doing pretty good at holding their hands, but things slip through like this one.

**Comment by gingervitis** [comment]
I'll fix item 3, the part where the loading spinner doesn't go away on error.

**Comment by gingervitis** [comment]
fixed with https://github.com/owncast/owncast-admin/commit/202f3089c441b0ac4dd77951f0188328d771e8ed
