### ISSUE TITLE
Removing scaled height and/or scaled width from stream variant throws error

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#781]

**Comment by gingervitis** [comment]
I know you're going to fix it on the backend @gabek but I think I also need to update the front end so that the Submit button doesn't stay in "loading" state after any error happens to come back (for this page and all pages that use that flow).

**Comment by gingervitis** [comment]
^ Oops that comment was meant for #780 .

**Comment by gabek** [comment]
After thinking about it I figured that sending the wrong type isn't something that should be handled by the backend.  It's the wrong type, and an error should be returned.  Defensively handling and guessing the intentions of requests with incorrect types is the incorrect approach.  So I'm going to fix the frontend so an empty string isn't sent, because that's invalid.
