### ISSUE TITLE
Add a blocklist API + UI for chat usernames

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#782]
Have a default list of names like admin, owncast, operator, etc but allow people to add to the list.

**Comment by gingervitis** [comment]
We should call it a "blocklist" or perhaps a "reserved words" list sounds more appropriate here. :)

**Comment by Th3ju** [comment]
Good idea, in my first test with 10 persons, I had a God, an Emmanuel Macron, a President , an Evil  and 3 persons with my own name ... 

Maybe disallow to have duplicates names to ?

**Comment by gabek** [comment]
Still have to add an admin UI for this.
