### ISSUE TITLE
Admin: Typo in Variant menu

### ISSUE THREAD

**Issue by jeyemwey** [owncast/owncast#803]
> I can see a typo in the CPU section “Reduce the to...” instead of “ Reduce it to...”
> [Src Mastodon](https://mastodon.online/@ankit/105858089576561688)

**Comment by 96RadhikaJadhav** [comment]
@jeyemwey Can I work on it?

**Comment by jeyemwey** [comment]
Sure, it's in the other repository though. Check out owncast/owncast-admin :)

**Comment by jeyemwey** [comment]
Please check `components/config/video-variant-form.tsx` around line 130.

**Comment by 96RadhikaJadhav** [comment]
@jeyemwey  Created a PR in owncast/owncast-admin repo.

**Comment by gabek** [comment]
I can't see any typos anywhere, either :\

**Comment by gabek** [comment]
Fixed two weeks ago before release.  Closing.  https://github.com/owncast/owncast-admin/commit/dd3fbd7780c4ae025d1228b69c9c369b436a8e2b#diff-7ad64bbe757e9cf3cec2e4a487be8e86c6014bd0234c1542ec2dc6c2eea56116R126
