### ISSUE TITLE
Option to enable or disable a stream output

### ISSUE THREAD

**Issue by Th3ju** [owncast/owncast#818]
Hi,

I have several streaming sources that hav not se same output resolution. 
For example, I have visioconferences equipements that don't send 1080p and other that ca send a this resoltution.

Is it possible on the video configuration page to have a checkbox near the edit or drop button to enable or disable a config depending of what we stream to owncast ? It would be easier thant delete and recreate it each time we change the source media

Thank for your good job ! 

Juju

**Comment by gabek** [comment]
Thanks for the suggestion!  While I understand your particular use case, I think it's pretty specific to your setup, as most people set their video configuration once and leave it.  I fear adding the option to enable/disable would add confusion to something that we already have to work to try to make as simple as we can.

As an idea, if I had to do this, I'd probably make a little shell script that uses the admin APIs to switch from one configuration to another when needed.

I'm going to close, but if other people ask for something similar we can re-evaluate.

**Comment by Th3ju** [comment]
Ok, nos problem, that was just an idea ;-)
