### ISSUE TITLE
Player acces protection

### ISSUE THREAD

**Issue by Th3ju** [owncast/owncast#826]
Hi,

Would it be possible to have a sort off token or password to access the player stream ? 

In some case we dont't want public streams and have to control that viewer have been invited. No need to real user / password but a simple think to choose is stream is public or "prvate" 

Ex : https://live.owncat.com/acomplextoken give acces to the stream and https://live.owncat.com/ return an error ?

Maybe too much particular like my other feature request, feel free to close it if you think I'm the only one wo need that ;-)

Ju

**Comment by gabek** [comment]
There's some discussion of approaches over at https://github.com/owncast/owncast/discussions/649, I know some people are doing different things to offer protected streams.
