### ISSUE TITLE
For vanity only: use charmbracelet to fancy up our console launch

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#829]
Since we have @muesli, we should take advantage of his TUI library to have a polished console message.  I'm not sure if importing this entire library to make a fancy looking console launch is worth it, though.  If it's lightweight than maybe it's fine.

https://github.com/charmbracelet/bubbletea

This is super not important, but some days you just want to play with something, so this is around when people have those days :)

**Comment by muesli** [comment]
I guess the lightweight approach would be using [termenv](github.com/muesli/termenv) to only mark-up the output a bit. Bubbletea is a complete TUI framework, and while I'm not sure Owncast strictly requires an interactive TUI mode, if that's something we want to achieve it's certainly an appealing package.

Either way, excited to work on this!
