### ISSUE TITLE
Directory: Add a large player header featuring a single live stream

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#835]
- Create a player for the top of the page.
- Grab the highest ranked instance and play it.
- Autoplay, but muted.

**Comment by gabek** [comment]
@nebunez I was talking with @gingervitis and she offered to do some mockups and design chat if you wanted to go over any ideas with her.  If you wanted to do your own thing that's cool too.

**Comment by graywolf336** [comment]
Question, how would an instance be "highest ranked"? Just the amount of viewers?

**Comment by gabek** [comment]
There's a loosely generated score on the backend that's assigned to instances for ordering them based on a few things.  It shouldn't be taken too seriously, but it's enough to put them in some kind of order.

**Comment by nebunez** [comment]
> @nebunez I was talking with @gingervitis and she offered to do some mockups and design chat if you wanted to go over any ideas with her. If you wanted to do your own thing that's cool too.

I'm definitely open to mockups and collaboration, especially for design consistency.

**Comment by gabek** [comment]
Something that's a bit of an advanced feature, but I think might be important:

We can't guarantee the playability or stability of a stream.  Sometimes due to server issues, sometimes due to bandwidth/geographic issues.  If we feature a player in the header but cannot play for any reason that could look pretty bad.  But since we'll have access to the player events we can detect this scenario and switch out the header player content for another source.

1. We use instance 1 as the header content.
2. It tries to start playing.
3. It buffers or won't play at all.
4. We catch this and switch to instance 2 as the header content.
5. Repeat.
