### ISSUE TITLE
Unable to stream with 0.0.6 release

### ISSUE THREAD

**Issue by aaronpk** [owncast/owncast#836]
Hello! I just installed a new OwnCast instance and am trying to stream to it for the first time. I've tried streaming from OBS, ffmpeg, and an ATEM Mini and am getting the same error every time.

```
INFO[2021-03-18T13:19:39-07:00] Owncast v0.0.6-linux-64bit (36645437ef17f622c8926fc32a2bf2de27a6e8d7)
INFO[2021-03-18T13:19:39-07:00] RTMP is accepting inbound streams on port 1935.
INFO[2021-03-18T13:19:39-07:00] Web server is listening on port 8080.
INFO[2021-03-18T13:19:39-07:00] The web admin interface is available at /admin.
INFO[2021-03-18T13:19:41-07:00] Inbound stream connected.
INFO[2021-03-18T13:19:41-07:00] Inbound stream disconnected.
WARN[2021-03-18T13:19:41-07:00] set tcp 10.11.11.11:1935: use of closed network connection
WARN[2021-03-18T13:19:41-07:00] set tcp 10.11.11.11:1935: use of closed network connection
WARN[2021-03-18T13:19:41-07:00] set tcp 10.11.11.11:1935: use of closed network connection
WARN[2021-03-18T13:19:41-07:00] set tcp 10.11.11.11:1935: use of closed network connection
WARN[2021-03-18T13:19:41-07:00] set tcp 10.11.11.11:1935: use of closed network connection
WARN[2021-03-18T13:19:41-07:00] set tcp 10.11.11.11:1935: use of closed network connection
WARN[2021-03-18T13:19:41-07:00] set tcp 10.11.11.11:1935: use of closed network connection
INFO[2021-03-18T13:20:40-07:00] Inbound stream connected.
INFO[2021-03-18T13:20:41-07:00] Inbound stream disconnected.
WARN[2021-03-18T13:20:41-07:00] set tcp 10.11.11.11:1935: use of closed network connection
```

I am unclear on where the problem is happening and what I need to change to make it work.

**Comment by gabek** [comment]
If I had to guess it's picking up a different, possibly older, version of ffmpeg from somewhere?  I know you had it working before, but it's possible the new version is using a different copy on your machine.

Take a look at `transcoder.log` and see what the errors in there may be.
Take a look at your server settings in your admin and see if it points to [the version of ffmpeg you expect](https://owncast.online/docs/troubleshooting/#misc-video-issues).

**Comment by aaronpk** [comment]
ah I'm an idiot, I only have ffmpeg 3 on this machine. I'm surprised it didn't warn me about it though! (Also I don't seem to have a transcoder.log)

**Comment by aaronpk** [comment]
Closing in favor of my latest comment on #587

**Comment by marcelloboer** [comment]
My ffmpeg is above 4, I'm still unable to cast due to the same error: use of closed network connection.
