### ISSUE TITLE
Experiment with forcing the viewer to be closer to live

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#837]
Right now we control latency by tweaking the number of seconds of available video.  In general we've hit the limits of this.  In an attempt to reduce the latency for a live viewer, we can experiment with possibly speeding up the viewer by a little bit until they get near the live edge.

If the player experiences rebuffering then the player can disable this feature.

This idea may not be possible due to limitations with videojs or something, but we should give it a shot.

**Comment by marrie** [comment]
there is still a 10 second delay even when hitting the seak to live button. I had a user test this actually and they ended up reacting about 10 seconds later. I think they had the low latency setting on. Can this be further looked into? I don't quite know what logs to give you guys if any, the next time I stream which should be in about 3 or so weeks. Thanks.

**Comment by gabek** [comment]
This is to be expected. Please take a look at the documentation under video latency for more information.

**Comment by marrie** [comment]
Ah yeah I’m expecting it to be like twitch in that I can chat and the delay is about 2 seconds. Or someone will hear me and react 2 seconds behind. I cannot code, so is this going to be an easy fix?

**Comment by gabek** [comment]
I'm afraid you might be misunderstanding. Reducing the latency isn't just something I forgot to do and I can slip in quick. You have some control of the latency buffer in the video settings in the admin. How you choose to configure that is up to you to determine your trade offs.

https://owncast.online/docs/troubleshooting/#reducing-the-delay-between-the-viewer-and-live

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="https://owncast.online/favicon.png" height="14"> Owncast</div><div><strong><a href="/docs/troubleshooting/">Troubleshooting</a></strong></div><div>Some categories of issues you might run into and some next steps to help troubleshoot.</div></blockquote>
