### ISSUE TITLE
Web admin not showing saved values.

### ISSUE THREAD

**Issue by Daxcor69** [owncast/owncast#839]
When I edit and save Name & About, the changes take effect. However in the admin panel when I come back to the page.. It doesn't show my values, it shows the default values of   "Owncast" &  "Welcome to your new Owncast server!  This description can be changed in the admin"

All other changes seems to show up. Here is what the page shows after the changes.
![image](https://user-images.githubusercontent.com/61804230/111816312-ec412c00-8899-11eb-9bf3-49609950575f.png)

Another issue, when no tags are selected it leaves a marker on the page.  See image. 
![image](https://user-images.githubusercontent.com/61804230/111816627-4b06a580-889a-11eb-8717-bbb1783018d8.png)

**Comment by gabek** [comment]
Just to clarify, every time you visit the admin's general settings it shows values that are different than what's actually being displayed on your page?

Tags are fixed in the next release.

**Comment by Daxcor69** [comment]
yes so it takes my values and applys them and I see them on the live stream.  However in the admin panel it shows you what I see in that posted image.
