### ISSUE TITLE
Move admin auth to support a simple implementation of OAuth as a step forward to chat logins

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#853]
Adding auth to chat to identify themselves, while has been a topic of discussion for some time, still lives on the back burner until we know exactly, from a product standpoint, we want and how we want it to work.  So zero work has been done.

But there is one place where work can be done that is controlled internally, and only impacts one user: logging into the admin.

My thought is we can start doing some of the heavy lifting of supporting OAuth, but only to login to the admin, and we'd just be our own very simple OAuth provider.  While this is overkill for one user, when we pull the trigger on additional chat user functionality all of this would exist. We could start building on top of it and add support for additional providers.

As a bonus this would allow future support for different moderator users that are separate from the generic admin.

/cc @geekgonecrazy @aaronpk

## Previous Links

- [Discussion around shadow accounts for chat users](https://github.com/owncast/owncast/discussions/440)
- @gingervitis mockups (I can't actually find them, I think they might have been posted to Rocket.Chat and anything that gets posted to chat gets lost).  Ginger, can you rep-post them on Github?
- [Chat user accounts](https://github.com/owncast/owncast/issues/464)

**Comment by aaronpk** [comment]
If you want to continue to avoid dealing with user accounts, there's another option which is to delegate all logins to an external OAuth provider. 

You'd configure OwnCast as an OAuth client at some provider (Google, GitHub, Okta, NextCloud, your own self-hosted whatever), and OwnCast would send the user out there when they want to log in, and accept any user account from the provider as a valid user in OwnCast. 

You could have an explicit list of users who are admins which you could either configure in OwnCast itself, or if you're using a custom OAuth server it could be a property returned by the server's userinfo response.

This is actually what [Vouch](https://github.com/vouch/vouch-proxy) does, (which is also written in Go in case you want some reference code), and it works well for a variety of use cases. It already supports a [bunch of OAuth providers](https://github.com/vouch/vouch-proxy/tree/master/pkg/providers) out of the box on top of the generic OpenID Connect providers.

**Comment by aaronpk** [comment]
I actually have some funding I could put towards this work if you're interested. I'd prefer to talk off the record about that, so feel free to send me an email or twitter DM!

**Comment by gingervitis** [comment]
I don't remember where I had posted them either.  But here's a copy of the rough mock.
![chatuser-compiled](https://user-images.githubusercontent.com/9563255/112244368-6c55f180-8c0c-11eb-8692-d7e682201c56.png)

**Comment by gabek** [comment]
> If you want to continue to avoid dealing with user accounts, there's another option which is to delegate all logins to an external OAuth provider.

In this specific case I think we would want a local admin account, so we can continue to start using Owncast immediately after downloading.  If a requirement of installing Owncast Admin was to first configure OAuth providers it would be a non-starter.  I'm pretty sensitive to requiring additional steps in the initial install since there's enough things people have to worry about with streaming.

For chat it's different, since that can be incrementally added later.  But I'm thinking we can do some of the OAuth work without re-working chat completely by doing just the admin login, and then incrementally add that functionality to chat using external providers.

Emailing you!

**Comment by gabek** [comment]
That all makes sense.  And with that in mind the original thoughts around this admin-first iterative approach probably doesn't make sense.

- A person installing from scratch, if HTTP Basic auth works, is probably unlikely to go out of their way to configure something different if it already works.
- An admin who's interested in Owncast probably isn't the same person who wants to force themselves to "Login with Facebook" or whatever.
- Configuring additional providers as a part of the initial setup adds an entire layer of complexity that could scare people off.

It probably makes sense to ditch this thread and just focus on "users" as a whole, since chat users are more likely to want to "Login with TikTok" than an admin would.

**Comment by gabek** [comment]
Closing this, back to [The Discussion](https://github.com/owncast/owncast/discussions/440) :)
