### ISSUE TITLE
Changing the Sever URL should not appear to reset Name and About

### ISSUE THREAD

**Issue by robertianburton** [owncast/owncast#854]
**Version:**
v0.0.7 (Dev/master branch)

**Expected Behavior:**
Updating the Server URL field only appears to update that field.

**Current Behavior**:
Updating the Server URL field appears to reset the Name and About fields to whatever they were on page load, even if there was a previous edit and update of the field since page load. This persists until refreshing the page.

**Steps to Reproduce:**
1. Start a fresh owncast install.
2. Log into admin.
3. Navigate Configuration > General
4. Change the text in the name field (or about field) and select Update.
5. Change the text in the Server URL field and select Update.
6. Note that the Name or About fields have reset to what they were before the update.
7. Refresh the page
8. The "cached" old values now show as the correct user-updated ones for all changed fields.

**Other Info:**
Some sort of caching issue probably. I'm unfamiliar with next.js but nothing jumped out immediately after looking at the component where the fields are defined.

**Comment by gabek** [comment]
Thank you so much for the detailed steps, we'll get this fixed up for the next release.
