### ISSUE TITLE
Running OwnCast with `webserverport` should save that port in the config

### ISSUE THREAD

**Issue by aaronpk** [owncast/owncast#860]
Problem: The first time I ran a new OwnCast install I provided a `-webserverport 8081` option on the command line. The admin interface shows that port correctly. Restarting OwnCast without that option falls back to the default port 8080.

Workaround: With OwnCast running, I had to change the port in the admin interface to something different (8082) then save, then change it back to 8081, and then I can start OwnCast without the `webserverport` option and it correctly listens on 8081.

Suggested Fix: If OwnCast is launched with the `webserverport` option, it should save that value into the config settings.

**Comment by gabek** [comment]
Totally makes sense, thanks for the suggestion!
