### ISSUE TITLE
add support for Tencent Cloud

### ISSUE THREAD

**Issue by ishelo** [owncast/owncast#862]
save video to the server storage ,or add tencent bucket [https://cloud.tencent.com/document/product/436](url)

**Comment by jeyemwey** [comment]
Hi, according to [their international homepage](https://intl.cloud.tencent.com/product/cos), Tencent Object Storage is compatible with the S3 APIs. Can you check if putting your credentials into Owncast works or what the issue is?

**Comment by gabek** [comment]
Closing this as any S3 provider should be supported, but feel free to re-open if there are issues.
