### ISSUE TITLE
Show news/updates in the admin

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#865]
In order to facilitate a way to push small communications to Owncast users we'd like to add a place to show updates from the Owncast project in the admin.

The plan is to use our existing Hugo project to write content that will get rendered into, hopefully, JSON.  Otherwise RSS is fine too, but we'd just have to add RSS parsing to the Admin project.  I don't expect we want to surface this content on the actual owncast.online web site because it's so targeted and specific to people who already use Owncast, but we could easily add it if we want.

If there's a concern about people not wanting the admin to "phone home" and leak the existence of their server we can add a setting to disable it, but other projects have done this type of thing and I think it's generally ok.  We also ping the GitHub api to know when new releases are available, and people have been fine with that.

**Comment by gingervitis** [comment]
Here's a super rough mock of what we could do.
Just make a new component for News 'n Updates which fetches the feed and displays them. We can make a new column for them like so:

<img width="1382" alt="image" src="https://user-images.githubusercontent.com/9563255/112789385-d0fcbc00-9011-11eb-98ce-ce22032f0e5d.png">

**Comment by gabek** [comment]
@geekgonecrazy Did you still want to look at this?  I'll work on the content side and get some stuff generated.

**Comment by geekgonecrazy** [comment]
@gingervitis with that would title fit and a clickable link?

Maybe bold title on same line that also can be clicked?

@gabek if no one else wants to take a crack I definitely can.  Seems like a good bite sized feature

**Comment by gingervitis** [comment]
Sure! I didn't bother with any detailed formatting in this mock.

But I'm sure the first row could be a title, the 2nd row could be copy. I assume there'll be a date. Maybe url to click somewhere.

<img width="432" alt="image" src="https://user-images.githubusercontent.com/9563255/112790277-de1aaa80-9013-11eb-9223-0eec165f9312.png">

**Comment by gabek** [comment]
Here's a couple example posts that would work as news posts.  https://owncast.online/news/index.json

To add more we just create more posts in the `news` directory on your public site.

**Comment by gabek** [comment]
I'll probably jump on this over the weekend unless somebody else beats me to it so we can get it done.

**Comment by aaronpk** [comment]
May I recommend that you format the JSON data in this format? https://jsonfeed.org That's supported by some other tools as well so could be subscribed to in other news readers too.

**Comment by gabek** [comment]
@gingervitis said she's on it!

**Comment by geekgonecrazy** [comment]
Ah that's a great idea! Looks like fairly close so not huge change hopefully.

**Comment by gabek** [comment]
Thanks @gingervitis!
