### ISSUE TITLE
Favicon and Logo customization

### ISSUE THREAD

**Issue by ClundXIII** [owncast/owncast#868]
Hi,

I would like to replace the default favicon and logo (at the top left of the page). Is there currently an easy way to to this? I am using the docker version.

Thanks,
Simon

**Comment by gabek** [comment]
Hi Simon,

Right now the only way to do that would be to replace `webroot/img/logo.svg` with an image of your own, or to edit the html to point the image tag at something else.

Same goes with the favicon, you could replace the existing icon files, or edit `index.html`.

**Comment by dirtyissa** [comment]
On a docker I used following command:
docker cp CONTAINER:SRC_PATH DEST_PATH

**Comment by gabek** [comment]
I don't see us adding admin options for this, but like mentioned above you can replace these files manually.
