### ISSUE TITLE
Changing resources paths to ./ instead

### ISSUE THREAD

**Issue by ajmandourah** [owncast/owncast#871]
If it's possible to change all paths to ./ instead. Ex. /js/ to ./js/ in the html and Javascript.

In case of proxying through nginx and apache from a virtual dir to owncast this will cause some resources not loading because of the path issue.

If I proxy from example.com/stream/ this will try to load resources marked by /js frome example.com/js instead of example.com/stream/js

Thanks

**Comment by gabek** [comment]
There's been a PR and conversation around it over at https://github.com/owncast/owncast/pull/631.  Feel free to pick up that conversation if you'd like, it kind of got dropped.  Closing this issue in favor of that PR.
