### ISSUE TITLE
Unable to cast: Inbound stream disconnected / use of closed network connection

### ISSUE THREAD

**Issue by marcelloboer** [owncast/owncast#881]
OS: Debian 9
Ffmpeg: 4.4.git
Owncast: 0.0.6-linux-64bit / v0.0.7-dev
Golang: 1.16.2 linux/amd64
OBS Studio: 26.1.1 linux
Error: Unable to cast. I tried directly to the server and through a ssh tunnel. Increased goland's Transport.MaxIdleConnsPerHost from 2 to 10 and 100. Ran both from the binary and from the sources. The webpage loads and runs just fine. ./test/ocTestStream.sh automated/test.mp4 doesn't show any video and prints only a warning alerting for files that differ greatly. Casting with ffmpeg and OBS ends shortly after start with a broken pipe, leaving the same messages of Inbound stream disconnected at the console.

Console log:
INFO[2021-03-31T16:04:09-03:00] RTMP is accepting inbound streams on port 1935.
INFO[2021-03-31T16:04:09-03:00] Web server is listening on port 80.
INFO[2021-03-31T16:04:09-03:00] The web admin interface is available at /admin.
INFO[2021-03-31T16:04:14-03:00] Inbound stream connected.
INFO[2021-03-31T16:04:14-03:00] **Inbound stream disconnected.**
WARN[2021-03-31T16:04:14-03:00] set tcp 127.0.0.1:1935: **use of closed network connection**
INFO[2021-03-31T16:04:25-03:00] Inbound stream connected.
INFO[2021-03-31T16:04:25-03:00] Inbound stream disconnected.
WARN[2021-03-31T16:04:25-03:00] set tcp 127.0.0.1:1935: use of closed network connection

**Comment by marcelloboer** [comment]
Yes, I went through all the online documentation. Nothing helps.

**Comment by gabek** [comment]
What's in your `transcoder.log` file?

**Comment by marcelloboer** [comment]
First run had some complain about x264, then I did an upgrade to latest ffmpeg and the file is clear now, however, the problem persists.

**Comment by gabek** [comment]
Could you share the log?

**Comment by marcelloboer** [comment]
Sure:
Unrecognized option 'x264-params:v:0'.
Error splitting the argument list: Option not found

**Comment by gabek** [comment]
That doesn't look very clear :).  Certainly points to an ffmpeg thing.  You mention you're running ffmpeg 4.4, but 4.3.2 seems to be the most recent: https://johnvansickle.com/ffmpeg/.  Could you just grab one of those static binaries and test with that?

**Comment by marcelloboer** [comment]
Sure...

**Comment by gabek** [comment]
I can't vouch for how you're building it, so that's why I suggest you use a release that already works.  If you build it yourself make sure you're adding all the libraries that any official release would have.  The above makes it look like a problem with the x264 within the copy of ffmpeg.

**Comment by marcelloboer** [comment]
Update: Success!
I built a static version of ffmpeg release n4.1.6 using this project with some modifications: https://github.com/zimbatm/ffmpeg-static
Tried with many other ffmpeg versions and configurations, that is the only one that worked.

Thank you for you time.
