### ISSUE TITLE
Chat user registration API

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#887]
1. Will auto-generate a display name for the user, like we do now (User 42).
1. Will auto-generate a color for the user.
1. Will create a unique ID for the user.
1. Will create a secret access token for the user.
1. Save user created date and IP address.
1. Return back the access token.

**Comment by aaronpk** [comment]
You'll need to create some sort of session identifier (aka access token) that is not just the user ID as well, which is what the client will send back to authenticate as that user ID.

**Comment by gabek** [comment]
Are you talking about for granting access to the websocket (#321) or for user identification?  For locking down the socket we need an additional layer.  I think these two things can work together, however.
