### ISSUE TITLE
Document directory registration protocol

### ISSUE THREAD

**Issue by aaronpk** [owncast/owncast#896]
Documenting the directory registration protocol would allow others to create similar directories of OwnCast instances.

From a quick look through the code, it looks like it works like this:

* When the "Enable directory" checkbox is checked, the instance makes a POST request to the directory API requesting a registration key
* When a stream is running, every 4 minutes it sends a POST to the directory API with the website URL and the registration key
* The response to the ping may include a new key which should be used in future requests

**Comment by gabek** [comment]
Closing this in favor of https://github.com/owncast/owncast/issues/458, using ActivityPub to allow people to build their own directories and stream aggregators.
