### ISSUE TITLE
Allow the admin to enter additional directory URLs to ping when live

### ISSUE THREAD

**Issue by aaronpk** [owncast/owncast#897]
Allowing the instance admin to enter additional directory URLs to ping would enable new topic or community-focused directories to be built.

I'm imagining entering just a list of directory URLs like `https://directory.owncast.online` which would then cause the service to ping each of the directory APIs when live.

**Comment by aaronpk** [comment]
An alternative option, at least for the immediate future, would be to add an additional webhook type that pings at the regular 4 minute interval when streaming, replicating the existing YP service pings.

**Comment by gabek** [comment]
As far as we've been able to tell, the general trend is people don't want to be listed on a directory.  And while that's totally fine, it's a bit of a hard sell to increase the scope of the directory and/or add support for the idea of creating more of them.  I would totally love to see multiple category/genre-based directories with a wide array of Owncast servers, but that just doesn't seem to be what most people want right now.  Hopefully that can change and then we can react to what people want.

We could add an additional webhook, but we'd have to spend some time thinking through it. If the directory host, ping endpoint and owncast servers are public knowledge, then anybody can send requests faking these ping webhooks to the directory.  But if these are intended to be private (people aren't publicly listing their webhook endpoints), like we assume webhooks to be, then it's probably fine.  Next time we add features to webhooks we can look at this.  But again, we're not yet seeing much adoption for this, so I'm seeing it kind of a wait and see situation where we see what people are using it for and we can build out from there.

**Comment by aaronpk** [comment]
Fair enough, I'll open a new issue scoped to the webhook feature and we can discuss it there. This one will live in the backlog until later

**Comment by gabek** [comment]
Closing this in favor of https://github.com/owncast/owncast/issues/458, using ActivityPub to allow people to build their own directories and stream aggregators.
