### ISSUE TITLE
Replace segment generation + Playlist update polling for S3 uploading

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#9]
Right now there's a monitor on the output directory where `ffmpeg` is spitting out updated playlists and HLS segments in order to know when new files are available and when the playlists are updated so we can upload to S3.  This adds both additional CPU utilization since it's constantly polling the filesystem, and additional delay since the poll is timed.

A better solution would be to somehow grab the status from ffmpeg directly that files have been written.  But this would require digging through the verbose output of ffmpeg and pulling out the statuses that we want, and that feels brittle and possibly error-prone.  There might be a better way to do this.  Maybe there's some flags we can pass ffmpeg to get some usable output in order to replace the existing polling.

As a secondary thought, we could replace this polling with native [inotify](https://github.com/tywkeene/go-fsevents) events, but that's limited to POSIX-based operating systems.  It wouldn't support windows.

**Comment by geekgonecrazy** [comment]
https://github.com/xfrr/goffmpeg/blob/master/README.md#how-to-get-the-transcoding-progress Maybe taking a look at how this library grabs progress?

**Comment by gabek** [comment]
Nice, good find.  I'll check that out, thanks!

**Comment by gabek** [comment]
Actually finally working on this!

**Comment by gabek** [comment]
I have this in a branch, and look forward to testing it once we release 0.0.2.  It's a big change of how HLS is handled, so it remains to be seen how it works in long-duration testing.
