### ISSUE TITLE
Empty tag is displayed if there are no tags set in 0.0.6

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#917]
Make sure this isn't happening in 0.0.7 and if it is fix it.

Example:

![image](https://user-images.githubusercontent.com/414923/114320719-203ff380-9acc-11eb-8377-8374c224f04f.png)

**Comment by SchweppeG** [comment]
I was not able to reproduce the issue with Firefox 87.0 on FreeBSD. I checked the current develop branch, see image below.

![grafik](https://user-images.githubusercontent.com/74667519/114616270-f1ca4000-9ca6-11eb-8691-265d0ae5e565.png)

**Comment by gabek** [comment]
Thanks for checking, looks like we're in good shape!
