### ISSUE TITLE
An unexpected error has occurred in admin interface

### ISSUE THREAD

**Issue by aral** [owncast/owncast#921]
When I navigate to `http://localhost:3000/admin` in latest Firefox on a from-source install of Owncast on my machine running elementary OS 5.x (based on Ubuntu 18.04, with ffmpeg updated to version 4.3.2), I get an “An unexpected error has occurred.” error:

```
XHRGEThttps://owncast.online/news/index.json
[HTTP/2 404 Not Found 9ms]

Error: An error has occured: 404
    NextJS 64
99255879d4f8b8cfe2c7f961c00bb703d81986c0.b51284a8156847919b05.js:1:51465
TypeError: t is undefined
    NextJS 69
framework.3105c3e333ee10fd9558.js:1:95720
TypeError: t is undefined
    NextJS 69
```

The URL being loaded (https://owncast.online/news/index.json) is, indeed 404.

![Screenshot from 2021-04-13 10-22-06@2x](https://user-images.githubusercontent.com/41798/114530170-9a928400-9c42-11eb-8b8f-4d0ae46fa1b6.png)

**Comment by gabek** [comment]
There was an issue in the development branch that got fixed last night, sorry about that!
