### ISSUE TITLE
Feature request: Auto update

### ISSUE THREAD

**Issue by aral** [owncast/owncast#924]
It would help non-technical people if the server auto updated.

If [automatic TLS](https://github.com/owncast/owncast/issues/922), [single-command server setup](https://github.com/owncast/owncast/issues/923), and this feature request are implemented, Owncast would become a [Small Web](https://small-tech.org/research-and-development/) app that could easily be installed and maintained by everyday people without any technical knowledge whatsoever (imagine: you hit a web site, choose a domain, and boom, your Owncast server is up and running and you never have to maintain it). 

In [Site.js](https://sitejs.org), this is implemented by a simple GET request that checks the latest version of the single binary, downloads it if necessary, and restarts the systemd service.

Something similar can be implemented for Owncast.

**Comment by aaronpk** [comment]
While auto updates are useful, there should be a way to opt out of them. The version check process is potentially a privacy concern since it will leak info about the instance.

**Comment by gabek** [comment]
@aral How does Site.js handle automatic upgrades?  How does the restarting of the service work once new files are in place as?

Edit: Just realized Site.js will always be running as a systemd service, so you can always guarantee the way to restart it is via systemd, where with Owncast people can be running it different ways.

**Comment by aral** [comment]
@gabek It runs as a systemd service so all it does is exit and it is automatically restarted (using the new binary) by systemd. This does mean a few seconds of downtime on upgrades but that’s entirely acceptable for our use case.

**Comment by aral** [comment]
@gabek Ah, didn’t see your reply. Yes :)

**Comment by ForestJohnson** [comment]
I implemented this for my own personal use

Owncast:

https://git.sequentialread.com/forest/owncast/commit/5e5c7782ff2bdc71f024206ab82c561e412daa66
https://github.com/ForestJohnson/owncast/commit/5e5c7782ff2bdc71f024206ab82c561e412daa66
> adding self-destruct endpoint for restarting the server from admin panel 

https://git.sequentialread.com/forest/owncast/commit/4c8bb05fe27d85d17d548880f3ae5f22344809b6
https://github.com/ForestJohnson/owncast/commit/4c8bb05fe27d85d17d548880f3ae5f22344809b6
> update admin panel with self-destruct button and fix nil pointer in yp


Owncast-Admin: 

https://git.sequentialread.com/forest/owncast-admin/commit/1c1b8ad22e2f97a64c4b5bc5c6294d74ecf42374
https://github.com/ForestJohnson/owncast-admin/commit/1c1b8ad22e2f97a64c4b5bc5c6294d74ecf42374
> add self-destruct button to reboot the server from admin panel


![image](https://user-images.githubusercontent.com/7119703/119894674-83fa7080-bf02-11eb-8de1-8b2b889d3a18.png)

![image](https://user-images.githubusercontent.com/7119703/119894696-8957bb00-bf02-11eb-83cc-74d3e8eb6eb8.png)

**Comment by gabek** [comment]
I was wondering how Caddy did their update, and they take a middle ground.

They update the binary by replacing the existing one when requested, but it's up to the user to restart the binary by whatever means they need to do that.

I think that's a good solution.

While I don't want to do an automatic, in the background, update, I think we can add something where the user can update from the admin.  In the version update page that shows up when there's a new release we can add a new update button that can pretty much just run the installer script.  That already will backup the existing install and update it.  Then we could show a persistent message if a restart is pending just like we do when you change the web port.

**Comment by gabek** [comment]
Though thinking about it more I'm not sure how this would work with Docker.  If we could detect that we're in a containerized environment then we could turn off the update feature.

**Comment by gabek** [comment]
Started working on this.

- Determine if the instance is running under Docker. If so, update is not supported.
- Determine if the instance is running under systemd. If so, support restarting via the admin after the update is supported.
- The update itself is performed via the update feature of the installer script and the script output is returned to the web client.

**Comment by gabek** [comment]
Branch is at https://github.com/owncast/owncast/tree/gek/auto-update.

<blockquote><img src="https://repository-images.githubusercontent.com/266445736/4f82fb80-a5b1-11ea-8f1c-69d316f861b5" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/owncast/owncast">GitHub - owncast/owncast at gek/auto-update</a></strong></div><div>Take control over your live stream video by running it yourself.  Streaming + chat out of the box. - GitHub - owncast/owncast at gek/auto-update</div></blockquote>

**Comment by gabek** [comment]
Made some progress.  I don't like how hackey it is, however.  It makes a lot of guesses about what environments it's running in based on less than awesome datapoints.  I'm not convinced I'll ever be able to ship this.

![auto-updater-force-quit-restart](https://user-images.githubusercontent.com/414923/140594184-663bf3d4-e3b2-4274-80c8-561cd4600b00.gif)
![auto-updater-no-restart](https://user-images.githubusercontent.com/414923/140594187-6254b8f3-535c-4c99-ab54-581b0adeaffb.gif)

**Comment by gabek** [comment]
There's a lots of "ifs" to make this work.  The above examples use the following:

1. If it is determined that Owncast is running within a container no update features are available.
2. If it is determined that Owncast is running under a development (source) environment no update features are available.
3. If at build time the update feature is not enabled then no update features are available.
4. If none of the above stop the update feature from being enabled, then it will be enabled, but with no auto restart.
5. If it is determined that systemd is running a service called "owncast" then it is assumed that exiting Owncast will force a restart of the service, so the updater will offer this one-click exit+restart with a warning that it could go wrong and you may need to manually restart it.

**Comment by gabek** [comment]
I wonder if there's a clean way instead of step 5 to:

1. Natively query systemd via a socket to verify systemd is actually installed and running.
2. Determine the PID of the Owncast service that's running.
3. Determine if systemd is managing this PID via asking systemd for running services.
4. Natively ask systemd to restart the service.

This would be much nicer.

**Comment by gabek** [comment]
Oh I could probably just look in `/run` for a PID file who's contents matches the PID of the running Owncast instance.  That would guarantee that systemd is running, owncast is registered with it, and the currently running instance of owncast is the instance being managed by systemd.
