### ISSUE TITLE
Multiple transmissions at same time

### ISSUE THREAD

**Issue by nilopaim** [owncast/owncast#927]
Sorry for this maybe stupid question but is it possible?

**Comment by gabek** [comment]
If you mean multiple different live streams occurring at the same time, that's not supported.  You could run Owncast multiple times, though if you wanted, and if your hardware supported it.  If you mean a single live stream but with multiple output stream variants for adaptive bitrate support, then that is supported.  Let me know if you have any other questions!

**Comment by jahir9991** [comment]
how can I achieve multiple live stream at a time?
does single oswncast instance responsible for single broadcast?
