### ISSUE TITLE
Add explicit FLOC opt-out headers in all http responses

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#939]
I'd rather not have to add another middleware to do this, so hopefully we can just set some common headers somewhere centrally.

**Comment by gabek** [comment]
@geekgonecrazy Do you have any thoughts how we can easily do this globally?

**Comment by geekgonecrazy** [comment]
Your approach is exactly how I would have done.  It's the simplest.  🙏. I need to read up on this whole floc thing.
