### ISSUE TITLE
Layout request: Fix video to top

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#94]
I know @gingervitis has fought with this time and time again, but it came up in the chat last night.  Not sure if we want to do it, but I wanted to document it anyway.

> I wish the vid stayed at the top of the screen while the conversation scrolled underneath (but maybe it's just because I'm on mobile?)

> Look out, I'm playing with css { position:fixed; top:0; width:100%; z-index:100; }

**Comment by gingervitis** [comment]
I added a solution for this in #120
