### ISSUE TITLE
Owncast installation did not complete successfully

### ISSUE THREAD

**Issue by akbarazimifar** [owncast/owncast#949]
**hi . how to fix ?** 
 
curl -s https://owncast.online/install.sh | bash
Owncast Installer v0.0.6

Existing install found in this directory.  Will update it to v0.0.6. If this is incorrect remove the directory and rerun the installer.
Backing up your files before upgrading to v0.0.6cp: cannot stat 'webroot/*.html': No such file or directory
cp: cannot stat 'webroot/styles/': No such file or directory
cp: cannot stat 'webroot/js': No such file or directory
cp: cannot stat 'webroot/img': No such file or directory
cp: cannot stat 'data/': No such file or directory
cp: cannot stat '*.yaml': No such file or directory
Your Owncast installation did not complete successfully.
Please report your issue at https://github.com/owncast/owncast/issues

**Comment by gabek** [comment]
The installer believed you already had Owncast installed, but the files it tried to backup don't exist.  Do you already have Owncast installed or something that would make it look like you do?  What is in the directory you're running the installer from?  If there's an "owncast" directory, could you remove it?

**Comment by gabek** [comment]
Hi @akbarazimifar, were you able to figure out what was going on?

**Comment by gabek** [comment]
I'm going to close this.  Feel free to reopen if you can report back with any information we can use to troubleshoot.

**Comment by AMGsportsTv** [comment]
### Installation did not complete successfully
Hello I am having this error:
ERROR: Your Owncast installation did not complete successfully.
Please report your issue at https://github.com/owncast/owncast/issues

<blockquote><img src="https://repository-images.githubusercontent.com/266445736/4f82fb80-a5b1-11ea-8f1c-69d316f861b5" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/owncast/owncast">Issues · owncast/owncast</a></strong></div><div>Take control over your live stream video by running it yourself.  Streaming + chat out of the box. - Issues · owncast/owncast</div></blockquote>

**Comment by gabek** [comment]
@AMGsportsTv What is the actual detailed error? Please open a new issue with as much detail as you can. This one is from 2021.
