### ISSUE TITLE
Play button draws over the header bar when scrolling

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#951]
It should scroll behind, just like the video.

![image](https://user-images.githubusercontent.com/414923/115754573-2dbd6f00-a351-11eb-919e-026488322f0d.png)

**Comment by MFTabriz** [comment]
Hi @gabek! Can I get added as the collaborator to this project (and assigned this issue) please?

**Comment by MFTabriz** [comment]
> Hi @gabek! Can I get added as the collaborator to this project (and assigned this issue) please?

I think I found a quick solution! :)

**Comment by gabek** [comment]
Assigned, thanks for looking!
