### ISSUE TITLE
unzip:  cannot find or open

### ISSUE THREAD

**Issue by 880228** [owncast/owncast#956]
Hi!

Created directory  [✓]
Downloading Owncast v0.0.6 for linuxError, do this: mount -t proc proc /proc
Downloaded Owncast v0.0.6 for linux  [✓]
unzip:  cannot find or open /tmp/tmp.c8uh19wcc8/owncast-0.0.6-linux-64bit.zip, /tmp/tmp.c8uh19wcc8/owncast-0.0.6-linux-64bit.zip.zip or /tmp/tmp.c8uh19wcc8/owncast-0.0.6-linux-64bit.zip.ZIP.
Your Owncast installation did not complete successfully.

I installed twice and have the same problem

**Comment by gabek** [comment]
What operating system are you running on?

I'm not familiar with this error, but it sounds like your proc file system isn't mounted?  Did you try doing what it said?
