### ISSUE TITLE
Create chat only url so people can embed it into their video

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#96]
Lots of twitch streamers embed the chat into the video itself.  This can be done by creating a url that's just the chat, read-only, for people to point their streaming software at.  I guess people could also full screen it on another display for following the chat easier, too.

**Comment by gingervitis** [comment]
I'm trying to think about the variety of use cases for this, in order to generalize a layout/style for it.

Also, would it would only be just listing the messages, and no message input?

**Comment by gabek** [comment]
I do think the normal use case wouldn't need the input, such as this type of thing:

![image](https://user-images.githubusercontent.com/414923/90431311-af038a00-e07d-11ea-9f6f-39e5fefe81b8.png)

**Comment by gingervitis** [comment]
So is that just an HTML page layered on video?
I guess I'm not terribly clear on how a Message-only component would actually be implemented.

**Comment by gabek** [comment]
You can point OBS to the URL and it would look something like:
![image](https://user-images.githubusercontent.com/414923/90604694-14589780-e1b2-11ea-8ff0-2d9993420494.png)

![image](https://user-images.githubusercontent.com/414923/90604640-0276f480-e1b2-11ea-8af7-a9dee6b2930a.png)

**Comment by gingervitis** [comment]
Hmm ok
