### ISSUE TITLE
Email Linode to tell them to update version to 0.0.7 post release

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#962]
After #942 is completed.

**Comment by mdonaberger** [comment]
hi. mitch donaberger at linode here. i reached out to hmorris to alert him to an update. he acknowledged, should be a few days.

**Comment by mdonaberger** [comment]
hi. mitch donaberger at linode here. i reached out to our one-click app marketplace team to alert them to an update. they acknowledged, should be a few days.

**Comment by gabek** [comment]
Oh awesome!  Thank you!

The nice thing about the Linode setup is anybody who installs via Linode will always get the most recent version, since it's running a StackScript.  The only thing that needs to be changed is in the Marketplace to change 0.0.6 to 0.0.7.  Or maybe we could change it to say "latest" or something so nobody ever has to change it again :)

**Comment by gabek** [comment]
Sent a note off to Linode to see if they could update that string on their marketplace.
