### ISSUE TITLE
Don't allow people to set their instance name to an empty string (or only whitespace)

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#967]
While in general I think people should be able to set anything they want, the name is pretty important and it should be seen as required.

![image](https://user-images.githubusercontent.com/414923/116501914-ef4f1500-a866-11eb-889f-f2db1e2e0ca8.png)

**Comment by sans2801** [comment]
Hi, I'm a python and js web developer and a newbie to the world of open source, would definitely like to work for this project

**Comment by gabek** [comment]
@sans2801 Awesome!  The admin project lives in https://github.com/owncast/owncast-admin, so if you want to take a look at this issue pull that project down and give it a spin.  The field for setting this name is in the General settings page.  Please reach out if you have any questions!

<blockquote><img src="https://opengraph.githubassets.com/1267cfba04b85951a7c70763ff25145feb078267685bdfbaef21c08f5a7cebfe/owncast/owncast-admin" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/owncast/owncast-admin">owncast/owncast-admin</a></strong></div><div>The admin web application for managing an Owncast server - owncast/owncast-admin</div></blockquote>

**Comment by sans2801** [comment]
@gabek Thank you for assigning me the task. I'll keep you updated with my progress :)

**Comment by sans2801** [comment]
Hello @gabek I cloned and ran the the develop branch of the owncast-admin repo.
I've installed all the dependencies using yarn.
Unfortunately, I'm getting this error as soon as I open the /admin page

![image](https://user-images.githubusercontent.com/56474333/117120063-7bee5b80-adb0-11eb-946e-34b4f37838d6.png)

Would you please guide me through the same

**Comment by gabek** [comment]
Sure!  It looks like maybe there's no copy of Owncast running for the admin to connect to.  For development it looks at `localhost:8080` to be running Owncast so you can use the Admin.

**Comment by gabek** [comment]
Hey @sans2801, were you able to get Owncast running?  I'm happy to help you with any issues you might be running into!

**Comment by sans2801** [comment]
@gabek Yes sir, I'm able to get it running. Sorry for the delay, some university work had come up, I'll be done soon, meanwhile will keep you updated with the progress.

**Comment by gabek** [comment]
Awesome, glad you got it running.  Feel free to let me know if you have any questions!

**Comment by sans2801** [comment]
Yeah, thank you😃

**Comment by sans2801** [comment]
Hello @gabek, regarding the issue with the empty tags, the tags list (which initially is empty) gets almost immediately re-initialized to [""].
![image](https://user-images.githubusercontent.com/56474333/119021178-ba913200-b9bc-11eb-83ae-3858cc7118ef.png)
![image](https://user-images.githubusercontent.com/56474333/119021289-e2809580-b9bc-11eb-9105-28bde551d780.png)

According to me, once the page loads,

![image](https://user-images.githubusercontent.com/56474333/119022265-0f817800-b9be-11eb-9351-1aa101252658.png)
(edit-tags.tsx, line 30 - 34)

 `serverConfig` gets initialized with the current field values and as the tags field is empty, it gets initialized as a list with an empty string which shows up as an empty tag.

![image](https://user-images.githubusercontent.com/56474333/119021859-8d914f00-b9bd-11eb-8fd6-09a1ccd8e124.png)

I tried to resolve this using
`if(tags[0]==="") tags.splice(0,tags.length);`

right before returning the jsx, and it seems to work fine (no more empty tags!). This helped me get familiar with the overall working of the website, now focussing on the current issue.
Would like to get suggestions or improvements regarding the same.

**Comment by sans2801** [comment]
Maybe I got sidetracked a bit from the current issue :sweat_smile: , excuse me for that

**Comment by sans2801** [comment]
Hello @gabek, to prevent the users from updating their instance names to blank space(s):
I tried doing this minor change in the frontend:
![image](https://user-images.githubusercontent.com/56474333/119200934-919b9a80-baab-11eb-8d93-41a877fd314c.png)
This won't let the user set/update their names to whitespace(s)
which was previously
![image](https://user-images.githubusercontent.com/56474333/119201130-e8a16f80-baab-11eb-88bc-fdab34dcbb26.png)
this allowed the users to set their names to >1 blank spaces.
 
I would like to test the changes by actually starting a stream. Would you please guide me through the same

**Comment by gabek** [comment]
Yeah, of course!  Though you don't actually have to start a stream to see the user interface, you just need to run a copy of Owncast and see the results.

Sounds like you already have the [admin](https://github.com/owncast/owncast-admin) running.  So next step is to run a copy of [owncast/owncast](https://github.com/owncast/owncast) on your machine.  You can just use the [Quickstart](https://owncast.online/quickstart/) to make sure you have Owncast running on your machine that the admin can connect to.  Then you can just visit http://localhost:8080 to see the user interface.

**Comment by MFTabriz** [comment]
@gabek what happened to this issue? It is still being worked on? If not, I want to give it a try?

**Comment by gabek** [comment]
It's no longer being worked on, so it's all yours! :)  According to https://github.com/owncast/owncast-admin/pull/180 it might just be as simple as setting the field to `required`.
