### ISSUE TITLE
Reset admin password?

### ISSUE THREAD

**Issue by AE720** [owncast/owncast#973]
I looked all over the documentation and github but I couldn't find anything about this. I forgot the password to get into the admin side of Owncast. Can there be a command to run via SSH to reset it?

**Comment by gabek** [comment]
Yup, here you go!  https://owncast.online/docs/troubleshooting/#resetting-a-lost-stream-key

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="/favicon.png" height="14"> Owncast</div><div><strong><a href="/docs/troubleshooting/">Troubleshooting</a></strong></div><div>Some categories of issues you might run into and some next steps to help troubleshoot.</div></blockquote>

**Comment by AE720** [comment]
D'oh. My bad. I forgot the password IS the stream key also. Hopefully someone can see this that forgot that too for the future. I appreciate the help.
