### ISSUE TITLE
Don't allow people to create tags with just an empty string or whitespace

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#974]
People seem to be creating tags of an empty string for some reason.  I guess they're deleting the contents of the text field and then saving it and we don't stop them.

**Comment by himsngh** [comment]
Hey I would like to work on this issue.

**Comment by gabek** [comment]
Awesome, thank you @himsngh!  There's this other issue, too, that's very similar in case you want to kill two birds with one stone :)

https://github.com/owncast/owncast/issues/967

Let me know if you have any questions getting the admin project up and running: https://github.com/owncast/owncast-admin

**Comment by himsngh** [comment]
I am sorry but i won't be able to do it. I thought the changes are related to golang but from what I understood it would be in the frontend side and I have no idea how that works .

**Comment by controlfreakstudio** [comment]
Having trouble replicating this on a live v0.0.6 Firefox or Chromium on nix in any order of operations or combo of blank out/add/delete/enter. Field is disallowing just spaces or null at point of entry. Even with js disable which of course borks most of the page functionality the field won't submit null.

Do you still want to stick a null check where it's getting recorded?

**Comment by gabek** [comment]
I'm not sure how people are doing it, to be honest, I've noticed a couple servers lately with "empty" tags.

![image](https://user-images.githubusercontent.com/414923/117368010-d0a8d980-ae77-11eb-808c-f5909315f247.png)

Raw data: https://livestream.tomlaipply.com/api/config

I'd want to be able to figure out how they're doing it before we put in a fix, otherwise we don't know if it actually fixes it.

<blockquote></blockquote>

**Comment by gabek** [comment]
Just saw somebody with one of our hosted instances pull off the "empty tag" thing.  This is what it looks like in the admin.  But maybe it's fixed in 0.0.7.

![image](https://user-images.githubusercontent.com/414923/118335668-0297ec80-b4c5-11eb-9481-89bd9cd0ba5f.png)

**Comment by gingervitis** [comment]
This seems to be a backend issue.
After a user has deleted all their tags, the server still return [""] for `tags`.

![image](https://user-images.githubusercontent.com/9563255/119248200-6e70f980-bb44-11eb-805b-8eae4f2d0d80.png)
