### ISSUE TITLE
Request: Restream to other destinations

### ISSUE THREAD

**Issue by timowevel1** [owncast/owncast#977]
Hey,

it would be amazing to have the possibility to enter other Destinations like Instagram, Facebook or YouTube.

**Comment by jeyemwey** [comment]
Hi, thanks for your request. If you need the feature now, try out [prism](https://github.com/muesli/prism) which provides a `1 to n` bridge exactly for this case.

**Comment by gabek** [comment]
Owncast is a streaming destination itself, and isn't a proxy for other services.  So It's unlikely we'll ever build this functionality into Owncast when there are projects that focus on such things, like Prism.  Sorry about that!
