### ISSUE TITLE
Unable to add TLS to RTMP Connection

### ISSUE THREAD

**Issue by LogalDeveloper** [owncast/owncast#988]
I have been making attempts to secure my RTMP connection to Owncast using TLS, forming [RTMPS](https://developers.google.com/youtube/v3/live/guides/rtmps-ingestion). I have tried two different proxies to accomplish this: stunnel and nginx. I have had relative success with both, but I am encountering an odd issue where Owncast sometimes does not broadcast the stream. If I revert back to regular RTMP, Owncast always broadcasts the stream without any problems.

Below is the nginx configuration I used to form the RTMPS proxy.
```
events {}
stream {
    server {
        listen            1935 ssl;
        proxy_pass        owncast-container-hostname:1935;
        proxy_buffer_size 32k;

        ssl_certificate     /path/to/certificate.crt;
        ssl_certificate_key /path/to/privatekey.key;
    }
}
```

Below is the server URL I used in OBS to enable RTMPS.
![OBS Configuration](https://media.logal.dev/Gw_XUeuetK.png)

When I start streaming, OBS starts streaming to Owncast as expected, like shown below.
![OBS Streaming](https://media.logal.dev/fzSC28buKI.png)

Owncast also acknowledges it is receiving the stream from the proxy, like shown below.
![Owncast Receiving Stream](https://media.logal.dev/4iimapLeGq.png)

However, viewers are only presented with the default stream offline clip.
![Viewer's Point of View](https://media.logal.dev/li8Utu4FT.png)

---

I honestly don't know if this is a bug or a feature request. To the best of my knowledge, the TLS proxy should be invisible to Owncast and look like a regular RTMP connection. I figured it would be best to file an issue here to start a discussion about it.

**Comment by gabek** [comment]
While I can't speak to it myself, @felix-engelmann has got RTMPS working in the past without any Owncast changes, and provided a docker-compose example for it.  https://github.com/owncast/owncast/pull/608

The next step I'd look at is to check out the `transcoder.log` file in your Owncast directory and see what specific errors are coming up.

**Comment by LogalDeveloper** [comment]
`transcoder.log` is coming up empty, even when the issue is occurring.
![0 Byte Log File](https://media.logal.dev/tbi2-d0Q1j.png)
![No Log Output](https://media.logal.dev/au1e8-mSi2.png)

**Comment by LogalDeveloper** [comment]
Additionally, the main log looks okay to me.
![Main Log](https://media.logal.dev/6272efjyxP.png)

I can also see the traffic is making it from nginx to Owncast.
![Network Activity](https://media.logal.dev/wU1rfV6cpK.png)

**Comment by gabek** [comment]
Unfortunately I'm not really sure where to look.  If it is truly transparent (as it is with traefik in that above example) then Owncast doesn't know or care that it was encrypted and decrypted, so something is going on.  Maybe experiment with your buffer size you have specified?

**Comment by gabek** [comment]
Hey @LogalDeveloper, were you able to make any progress? Is there anything I can do to help troubleshoot?

**Comment by gabek** [comment]
Going to close this, but please let me know if there's anything I can do to help troubleshoot.

**Comment by andrewfer000** [comment]
I got this to work fine. All I had to do was put that in my /etc/nginx/nginx.conf file. (I changed the port to 1936)
```
stream {
    server {
        listen            1936 ssl;
        proxy_pass        localhost:1935;
        proxy_buffer_size 32k;

       ssl_certificate     /etc/letsencrypt/live/live.myowncast.tld/fullchain.pem;
       ssl_certificate_key /etc/letsencrypt/live/live.myowncast.tld/privkey.pem;
    }
}

```

Please note I am running this on the same physical server. I am also using Apache for the HTTPS.
