### ISSUE TITLE
Allow bitrate to be set to 400 in admin

### ISSUE THREAD

**Issue by controlfreakstudio** [owncast/owncast#989]
with no means to get to a conf file, please allow video slider to go below 600. This is a serious request for the audio centric of us, I often like to pass thru 320 audio and use sweet FA for video as it's never action gaming or HD IRL. And coupled with not always amazing upload speed, super useful.

my current setting from pre upgrade to v6 is video 300 and it works great for my needs and Im assuming will for others who are also music/audio focussed and or internet disadvantaged.

**Comment by gabek** [comment]
For anybody looking for a simple change: https://github.com/owncast/owncast-admin/blob/develop/utils/config-constants.tsx#L239

<blockquote><img src="https://opengraph.githubassets.com/29a44bacb0e289f28df2dfa7ae807714dddcfeaa3436de3cc931b75edee195e3/owncast/owncast-admin" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/owncast/owncast-admin">owncast/owncast-admin</a></strong></div><div>The admin web application for managing an Owncast server - owncast/owncast-admin</div></blockquote>

**Comment by controlfreakstudio** [comment]
tested. gui slider changes appropriately
