### ISSUE TITLE
Video On Demand

### ISSUE THREAD

**Issue by Yuvi-App** [owncast/owncast#997]
Would be great if we can get Video on Demand.
That will allow for us to upload our own videos, or have them stored from after the stream, which will automatically be reflected in a section below the bio.

tag as feature request please :D

**Comment by gabek** [comment]
Hey there!  Recordings of streams is scheduled in the future.  I'm certainly looking forward to when we can add that!

Closing this in favor of the original request: https://github.com/owncast/owncast/issues/102
