### ISSUE TITLE
Instability when using Restream

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#999]
More Restream issues!

controlfreak said he was seeing Owncast literally crash when Restream disconnects.  I thought we had fixed up Restream issues in the past, but it seems to be back.

**Comment by gabek** [comment]
I just tested with Restream and I wasn't able to reproduce a crash.

**Comment by gabek** [comment]
@controlfreakstudio If you encounter this again could you provide the full crash log?

**Comment by gabek** [comment]
Both I and @controlfreakstudio tested with 0.0.7 and Restream and all seems to be fine.  Closing.

**Comment by controlfreakstudio** [comment]
I tested using coming in and out between restream and straight to only owncast repeatedly and threw in real world scenarios like botching a stream key etc.

As at v7, we only get the following warning when coming inbound from restream:
Unable to parse inbound broadcaster details: Not a onMetaData message
it streams and the good news is, doesn't seem to cause any more instability or weirdness at ending stream via restream

at this time we can tentatively say restream is an option with v7 for those that require such commercial splitting
